/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2025 Tetsuo AI
 * https://x.com/tetsuoai
 */

/**
 * @file SocketHTTP3-private.h
 * @brief HTTP/3 connection internal structures.
 *
 * Private header defining the connection struct layout. Only included
 * by the connection implementation and tests that need direct struct access.
 */

#ifndef SOCKETHTTP3_PRIVATE_INCLUDED
#define SOCKETHTTP3_PRIVATE_INCLUDED

#include "http/SocketHTTP3.h"
#include "http/SocketHTTP3-stream.h"

/** Per-stream output buffer: accumulates bytes for one QUIC stream. */
typedef struct
{
  uint64_t stream_id;
  uint8_t *data;
  size_t len;
  size_t capacity;
} H3_StreamBuf;

/** Maximum number of output entries queued between drain calls. */
#define H3_MAX_OUTPUT_ENTRIES 16

/** Output queue: collects (stream_id, data, len) entries for caller to send. */
typedef struct
{
  SocketHTTP3_Output entries[H3_MAX_OUTPUT_ENTRIES];
  size_t count;
} H3_OutputQueue;

/** Maximum number of unidirectional streams awaiting type byte. */
#define H3_MAX_PENDING_UNIDI 8

/** State for unidirectional streams whose type byte hasn't been read yet. */
typedef struct
{
  uint64_t stream_ids[H3_MAX_PENDING_UNIDI];
  size_t count;
} H3_PendingUnidi;

/** Control stream receive buffer size. */
#define H3_CTRL_RECV_BUF_SIZE 256

struct SocketHTTP3_Conn
{
  Arena_T arena;
  SocketHTTP3_Role role;
  SocketHTTP3_ConnState state;
  void *quic; /**< Stored but not called — tests can pass NULL */

  /* Stream map */
  SocketHTTP3_StreamMap_T stream_map;
  uint64_t local_control_id;
  uint64_t local_encoder_id;
  uint64_t local_decoder_id;

  /* Settings */
  SocketHTTP3_Settings local_settings;
  SocketHTTP3_Settings peer_settings;
  int peer_settings_received;

  /* Control stream receive buffer (partial frame headers + payloads) */
  uint8_t ctrl_recv_buf[H3_CTRL_RECV_BUF_SIZE];
  size_t ctrl_recv_len;
  int control_first_frame_seen;

  /* GOAWAY state */
  uint64_t local_goaway_id;
  uint64_t peer_goaway_id;
  int goaway_sent;
  int goaway_received;

  /* Push ID tracking */
  uint64_t max_push_id;
  int max_push_id_received;

  /* Unidi streams waiting for type byte */
  H3_PendingUnidi pending_unidi;

  /* Output queue for frames generated by this connection */
  H3_OutputQueue output;

  /* Per-local-stream output buffers */
  H3_StreamBuf control_out;
  H3_StreamBuf encoder_out;
  H3_StreamBuf decoder_out;
};

#endif /* SOCKETHTTP3_PRIVATE_INCLUDED */
