connection_pool.c File Reference
connection_pool.c File Reference
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "core/Arena.h"
#include "core/Except.h"
#include "poll/SocketPoll.h"
#include "pool/SocketPool.h"
#include "socket/Socket.h"
Functions
static void signal_handler (int signo)
static void simulate_work_wrapper (Connection_T conn, void *arg)
static int is_idle_connection (Connection_T conn, void *userdata)
int main (int argc, char **argv)
Variables
static volatile int running = 1
Function Documentation
is_idle_connection()
static int is_idle_connection (Connection_T conn, void * userdata) static
Definition at line 58 of file connection_pool.c.
References Connection_isactive().
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 65 of file connection_pool.c.
References Arena_dispose(), Arena_new(), END_TRY, EXCEPT, is_idle_connection(), running, signal_handler(), simulate_work_wrapper(), Socket_bind(), Socket_connect(), Socket_Failed, Socket_new(), SocketPoll_free(), SocketPoll_new(), SocketPool_add(), SocketPool_cleanup(), SocketPool_count(), SocketPool_drain(), SocketPool_drain_poll(), SocketPool_Failed, SocketPool_find(), SocketPool_foreach(), SocketPool_free(), SocketPool_get_active_count(), SocketPool_get_hit_rate(), SocketPool_get_idle_count(), SocketPool_new(), and TRY.
signal_handler()
static void signal_handler (int signo) static
Definition at line 32 of file connection_pool.c.
References running.
Referenced by main().
simulate_work_wrapper()
static void simulate_work_wrapper (Connection_T conn, void * arg) static
Definition at line 40 of file connection_pool.c.
References Connection_socket(), Socket_getpeeraddr(), and Socket_getpeerport().
Referenced by main().
Variable Documentation
running
volatile int running = 1 static
connection_pool.c - Connection Pool Example
Demonstrates connection pooling using the SocketPool API. Shows pool creation, connection management, and statistics.
Build: cmake -DBUILD_EXAMPLES=ON .. make example_connection_pool
Usage: ./example_connection_pool [max_connections] [buffer_size] ./example_connection_pool 10 4096
Definition at line 29 of file connection_pool.c.
Referenced by main(), main(), and signal_handler().