Tetsuo Pulse: dns_lookup.c File Reference
dns_lookup.c File Reference
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "core/Except.h"
#include "dns/SocketDNS.h"
Functions
static const char * rrtype_string (int rrtype)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 41 of file dns_lookup.c.
References END_TRY, EXCEPT, rrtype_string(), SocketDNS_check(), SocketDNS_Failed, SocketDNS_free(), SocketDNS_getresult(), SocketDNS_new(), SocketDNS_resolve(), SocketDNS_resolve_sync(), and TRY.
rrtype_string()
static const char * rrtype_string (int rrtype) static
dns_lookup.c - DNS Resolution Example
Demonstrates DNS resolution using the SocketDNS API. Shows both synchronous and asynchronous DNS lookups.
Build: cmake -DBUILD_EXAMPLES=ON .. make example_dns_lookup
Usage: ./example_dns_lookup [hostname] [type] ./example_dns_lookup google.com A ./example_dns_lookup example.com sync
Types: sync - Synchronous resolution (default) async - Asynchronous resolution with timeout
Definition at line 30 of file dns_lookup.c.
Referenced by main().