graceful_shutdown.c File Reference
graceful_shutdown.c File Reference
#include <errno.h>
#include <fcntl.h>
#include <poll.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "core/Arena.h"
#include "core/Except.h"
#include "poll/SocketPoll.h"
#include "pool/SocketPool.h"
#include "socket/Socket.h"
Macros
#define DEFAULT_PORT 8080
#define MAX_CONNECTIONS 100
#define BUFFER_SIZE 4096
#define DRAIN_TIMEOUT_MS 30000 /* 30 seconds */
#define POLL_TIMEOUT_MS 100 /* 100ms - short to check signal pipe */
Functions
static void signal_handler (int signo)
static int setup_signal_handling (void)
static int check_signal_pipe (void)
static void cleanup_signal_handling (void)
static int handle_client_data (Socket_T client, SocketBuf_T inbuf, SocketBuf_T outbuf)
int main (int argc, char *argv[])
Variables
static int g_signal_pipe [2] = { -1, -1 }
static volatile sig_atomic_t g_last_signal = 0
Macro Definition Documentation
BUFFER_SIZE
#define BUFFER_SIZE 4096
Definition at line 47 of file graceful_shutdown.c.
DEFAULT_PORT
#define DEFAULT_PORT 8080
graceful_shutdown.c - Production-grade signal handling example
Demonstrates async-signal-safe shutdown patterns using high-level APIs:
Self-pipe trick for signal notification
Integration with SocketPoll event loop (using poll timeout)
Graceful connection draining with timeout
SocketPool for connection management
Clean resource cleanup
Build: cmake -DBUILD_EXAMPLES=ON .. make example_graceful_shutdown
Usage: ./example_graceful_shutdown [port]
Test:
Start server: ./example_graceful_shutdown 8080
Connect clients: nc localhost 8080
Send SIGINT (Ctrl+C) or SIGTERM to initiate graceful shutdown
Observe connections draining before exit
Definition at line 45 of file graceful_shutdown.c.
DRAIN_TIMEOUT_MS
#define DRAIN_TIMEOUT_MS 30000 /* 30 seconds */
Definition at line 48 of file graceful_shutdown.c.
MAX_CONNECTIONS
#define MAX_CONNECTIONS 100
Definition at line 46 of file graceful_shutdown.c.
POLL_TIMEOUT_MS
#define POLL_TIMEOUT_MS 100 /* 100ms - short to check signal pipe */
Definition at line 49 of file graceful_shutdown.c.
Function Documentation
check_signal_pipe()
static int check_signal_pipe (void) static
check_signal_pipe - Check if signal pipe has data (non-blocking)
Returns: 1 if signal received, 0 otherwise
Definition at line 166 of file graceful_shutdown.c.
References g_signal_pipe.
Referenced by main().
cleanup_signal_handling()
static void cleanup_signal_handling (void) static
cleanup_signal_handling - Clean up signal infrastructure
Definition at line 177 of file graceful_shutdown.c.
References g_signal_pipe.
Referenced by main().
handle_client_data()
static int handle_client_data (Socket_T client, SocketBuf_T inbuf, SocketBuf_T outbuf) static
handle_client_data - Process data from a client connection
Simple echo server: reads data and echoes it back. Returns: 1 to keep connection, 0 to close
Definition at line 199 of file graceful_shutdown.c.
References BUFFER_SIZE, END_TRY, EXCEPT, Socket_Closed, Socket_Failed, Socket_getpeeraddr(), Socket_getpeerport(), Socket_recv(), Socket_sendall(), and TRY.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 242 of file graceful_shutdown.c.
References Arena_dispose(), Arena_new(), BUFFER_SIZE, SocketStats_T::bytes_received, SocketStats_T::bytes_sent, check_signal_pipe(), cleanup_signal_handling(), Connection_inbuf(), Connection_outbuf(), Connection_socket(), SocketStats_T::create_time_ms, SocketEvent_T::data, DEFAULT_PORT, DRAIN_TIMEOUT_MS, END_TRY, EXCEPT, g_last_signal, handle_client_data(), MAX_CONNECTIONS, POLL_READ, POLL_TIMEOUT_MS, running, setup_signal_handling(), Socket_accept(), Socket_bind(), Socket_Failed, Socket_free(), Socket_get_monotonic_ms(), Socket_getpeeraddr(), Socket_getpeerport(), Socket_getstats(), Socket_listen(), Socket_new(), Socket_setnonblocking(), Socket_setreuseaddr(), SocketMetrics_get_peak_connections(), SocketMetrics_get_socket_count(), SocketPoll_add(), SocketPoll_del(), SocketPoll_Failed, SocketPoll_free(), SocketPoll_new(), SocketPoll_wait(), SocketPool_add(), SocketPool_count(), SocketPool_drain(), SocketPool_drain_force(), SocketPool_drain_poll(), SocketPool_drain_remaining_ms(), SocketPool_Failed, SocketPool_free(), SocketPool_get_active_count(), SocketPool_get_hit_rate(), SocketPool_get_idle_count(), SocketPool_new(), SocketPool_remove(), and TRY.
setup_signal_handling()
static int setup_signal_handling (void) static
setup_signal_handling - Initialize signal handling infrastructure
Creates the self-pipe and installs signal handlers for:
SIGINT (Ctrl+C)
SIGTERM (kill default)
SIGHUP (optional: config reload, but we use for shutdown too)
Returns: 0 on success, -1 on error
Definition at line 109 of file graceful_shutdown.c.
References g_signal_pipe, and signal_handler().
Referenced by main().
signal_handler()
static void signal_handler (int signo) static
signal_handler - Async-signal-safe signal handler
ONLY performs async-signal-safe operations:
Saves errno
Writes to pipe (write() is async-signal-safe)
Restores errno
The signal number is written to the pipe so the main loop can determine which signal was received.
Definition at line 79 of file graceful_shutdown.c.
References g_last_signal, and g_signal_pipe.
Referenced by setup_signal_handling().
Variable Documentation
g_last_signal
volatile sig_atomic_t g_last_signal = 0 static
Definition at line 60 of file graceful_shutdown.c.
Referenced by main(), and signal_handler().
g_signal_pipe
int g_signal_pipe[2] = { -1, -1 } static
Definition at line 57 of file graceful_shutdown.c.
Referenced by check_signal_pipe(), cleanup_signal_handling(), setup_signal_handling(), and signal_handler().