Datagram Sockets
Datagram Sockets
Comprehensive API for UDP and datagram sockets including multicast, broadcast, and scatter/gather support.
Files
file SocketDgram.h
High-level UDP/datagram socket interface with multicast and broadcast support.
Macros
#define T SocketDgram_T
Functions
SocketDgram_T SocketDgram_new (int domain, int protocol)
Create a new UDP/datagram socket with specified domain and protocol.
void SocketDgram_free (SocketDgram_T *socket)
Dispose of a datagram socket, closing the underlying file descriptor and freeing resources.
void SocketDgram_bind (SocketDgram_T socket, const char *host, int port)
Bind a datagram socket to a local IP address and port.
void SocketDgram_connect (SocketDgram_T socket, const char *host, int port)
Set default destination for socket.
ssize_t SocketDgram_sendto (SocketDgram_T socket, const void *buf, size_t len, const char *host, int port)
Send datagram to specific address.
ssize_t SocketDgram_recvfrom (SocketDgram_T socket, void *buf, size_t len, char *host, size_t host_len, int *port)
Receive datagram and get sender address.
ssize_t SocketDgram_send (SocketDgram_T socket, const void *buf, size_t len)
Send to default destination (connected socket).
ssize_t SocketDgram_recv (SocketDgram_T socket, void *buf, size_t len)
Receive from default source (connected socket).
ssize_t SocketDgram_sendall (SocketDgram_T socket, const void *buf, size_t len)
Send all data (handles partial sends).
ssize_t SocketDgram_recvall (SocketDgram_T socket, void *buf, size_t len)
Receive all requested data (handles partial receives).
ssize_t SocketDgram_sendv (SocketDgram_T socket, const struct iovec *iov, int iovcnt)
Scatter/gather send (writev wrapper).
ssize_t SocketDgram_recvv (SocketDgram_T socket, struct iovec *iov, int iovcnt)
Scatter/gather receive (readv wrapper).
ssize_t SocketDgram_sendvall (SocketDgram_T socket, const struct iovec *iov, int iovcnt)
Scatter/gather send all (handles partial sends).
ssize_t SocketDgram_recvvall (SocketDgram_T socket, struct iovec *iov, int iovcnt)
Scatter/gather receive all (handles partial receives).
void SocketDgram_setnonblocking (SocketDgram_T socket)
Enable non-blocking mode.
void SocketDgram_setreuseaddr (SocketDgram_T socket)
Enable address reuse.
void SocketDgram_setreuseport (SocketDgram_T socket)
Enable port reuse across sockets.
void SocketDgram_setbroadcast (SocketDgram_T socket, int enable)
Enable broadcast.
void SocketDgram_joinmulticast (SocketDgram_T socket, const char *group, const char *interface)
Join multicast group.
void SocketDgram_leavemulticast (SocketDgram_T socket, const char *group, const char *interface)
Leave multicast group.
void SocketDgram_setttl (SocketDgram_T socket, int ttl)
Set time-to-live (hop limit).
void SocketDgram_settimeout (SocketDgram_T socket, int timeout_sec)
Set socket timeout.
int SocketDgram_gettimeout (SocketDgram_T socket)
Get socket timeout.
int SocketDgram_getbroadcast (SocketDgram_T socket)
Get broadcast setting.
int SocketDgram_getttl (SocketDgram_T socket)
Get time-to-live (hop limit).
int SocketDgram_getrcvbuf (SocketDgram_T socket)
Get receive buffer size.
int SocketDgram_getsndbuf (SocketDgram_T socket)
Get send buffer size.
int SocketDgram_isconnected (SocketDgram_T socket)
Check if datagram socket is connected.
int SocketDgram_isbound (SocketDgram_T socket)
Check if datagram socket is bound to an address.
int SocketDgram_fd (const SocketDgram_T socket)
Get underlying file descriptor.
const char * SocketDgram_getlocaladdr (const SocketDgram_T socket)
Get local IP address.
int SocketDgram_getlocalport (const SocketDgram_T socket)
Get local port number.
void SocketDgram_setcloexec (SocketDgram_T socket, int enable)
Control close-on-exec flag.
int SocketDgram_debug_live_count (void)
Get number of live datagram socket instances.
SocketDgram_T SocketDgram_bind_udp (const char *host, int port)
Create a bound UDP socket in one call.
Variables
const Except_T SocketDgram_Failed
Exception type for general failures in datagram socket operations.
Detailed Description
Comprehensive API for UDP and datagram sockets including multicast, broadcast, and scatter/gather support.
The Datagram Sockets module offers a high-level, exception-based interface for connectionless protocols like UDP. It abstracts low-level socket operations, providing features for reliable messaging over unreliable transports. Supports IPv4, IPv6, and Unix domain datagrams with advanced capabilities for network discovery, streaming, and IPC.
Architecture Overview
┌───────────────────────────────────────────────────────────┐
│                    Application Layer                      │
│  UDP Echo Servers, mDNS Clients, Game Networking, etc.    │
└─────────────────────┬─────────────────────────────────────┘
                      │ Uses
┌─────────────────────▼─────────────────────────────────────┐
│               Datagram Module                             │
│  SocketDgram_T + sendto/recvfrom, joinmulticast, etc.     │
└─────────────────────┬─────────────────────────────────────┘
                      │ Depends on
┌─────────────────────▼─────────────────────────────────────┐
│              Core I/O Foundation                          │
│  SocketBase_T, Except_T, SocketUtil hash & timeouts       │
└───────────────────────────────────────────────────────────┘
Key Features
Connectionless & Connected Modes: Use sendto/recvfrom for arbitrary peers or connect for default destination optimization.
Multicast/Broadcast: Join groups, send to broadcast addresses for discovery protocols (e.g., mDNS, SSDP).
Scatter/Gather I/O: Efficient sendv/recvv for zero-copy from multiple buffers.
Non-Blocking & Timeouts: Full support for async I/O with SocketPoll integration.
Exception Safety: TRY/EXCEPT for clean error handling without error code propagation.
Thread Safety: Individual socket operations are thread-safe; no global state.
Platform Agnostic: Auto-detects backends (epoll, kqueue, poll) for performance.
Module Relationships
Dependencies: core/Except.h (exceptions), socket/SocketCommon.h (base socket), sys/socket.h (POSIX)
Used By: Higher-level modules like dns/SocketDNS.h (UDP DNS queries), tls/SocketDTLS.h (DTLS over UDP)
Integration: poll/SocketPoll.h for event multiplexing, pool/SocketPool.h for UDP connection pooling (rare)
Utilities: Uses core/SocketUtil for hashing, timeouts, logging; core/Arena_T for internal allocations
Platform Requirements & Limitations
Requirement Details
OS POSIX (Linux, BSD, macOS); Windows requires Winsock port
Network IPv6 kernel support for dual-stack; multicast routing enabled
Threads pthreads for error reporting and internal locks
Limits Subject to ulimit -n (open files), SO_MAXCONN
Error Handling
Primary exception: SocketDgram_Failed for syscalls, invalid params, resource issues
Return conventions: ssize_t functions return bytes or 0 (EAGAIN/would-block)
Use Socket_GetLastError() for human-readable messages post-exception
See docs/ERROR_HANDLING.md for TRY/EXCEPT patterns
Performance Notes
O(1) for most operations (syscalls)
Avoid DNS in hot paths; resolve addresses upfront or use SocketDNS async
Buffer sizes tunable via getsockopt (default OS-dependent, often 212KB)
For high-throughput, use recvvall/sendvall to minimize copies
Security Considerations
CLOEXEC enabled by default to prevent fd leaks in forks
Validate sender addresses in recvfrom to prevent spoofing
Use TTL=1 for link-local multicast to limit scope
Integrate with security/SocketSYNProtect.h for rate limiting (though UDP stateless)
See also
SocketDgram_new() for initialization
SocketDgram_bind() for server-side binding
SocketDgram_sendto() / SocketDgram_recvfrom() for core I/O
docs/SECURITY.md for network Security Modules
docs/ASYNC_IO.md for non-blocking integration
Macro Definition Documentation
T
#define T SocketDgram_T
Definition at line 144 of file SocketDgram.h.
Function Documentation
SocketDgram_bind()
void SocketDgram_bind (SocketDgram_T socket, const char * host, int port) extern
Bind a datagram socket to a local IP address and port.
Associates the socket with a specific local endpoint using bind() system call. Required for servers to receive datagrams (recvfrom). For clients, optional but recommended for getting local port or SO_REUSEPORT load balancing. Supports wildcard addresses (NULL or "0.0.0.0"::) to bind to all interfaces. Performs DNS resolution if host is hostname, which may block. Validates port (1-65535) and host format; raises on invalid input.
Edge cases:
Port 0 binds to ephemeral port (OS assigns available).
Privileged ports (<1024) require root or CAP_NET_BIND_SERVICE.
Already bound sockets raise error.
Hostname resolution timeouts after system default (~30s); use IP for speed.
After bind, socket can receive on specified port; use isbound() to check.
Parameters
[in] socket The SocketDgram_T to bind (must be newly created, not already bound).
[in] host Local IP address string ("127.0.0.1", "::1", "0.0.0.0" for any) or hostname. NULL defaults to wildcard any-address.
[in] port Local port number: 0-65535, where 0 = ephemeral (recommended for clients).
Returns
Void on success.
Exceptions
SocketDgram_Failed On bind failure or validation errors, including:
EACCES/EADDRINUSE: Address/port in use or privileged port without perms
EADDRNOTAVAIL: Invalid host address
EINVAL: Invalid port (<0 or >65535) or already bound
ENETDOWN: Network interface down
getaddrinfo failure for hostnames (ENOMEM, HOST_NOT_FOUND) Log and retry or fallback to ephemeral port.
Thread Safety\n Conditional - Safe if socket not concurrently accessed.
Bind is not reentrant on same socket; synchronize if multi-threaded init.
Basic Usage: Server Bind
TRY {
    SocketDgram_T sock = SocketDgram_new(AF_INET, 0);
    SocketDgram_bind(sock, NULL, 12345);  // Bind to any IP, port 12345
    // Now recvfrom will receive on port 12345
} EXCEPT(SocketDgram_Failed) {
    // Handle bind failure (e.g., port in use)
} FINALLY {
    SocketDgram_free(&sock);
} END_TRY;
Client Bind to Ephemeral Port with Reuse
TRY {
    SocketDgram_T sock = SocketDgram_new(AF_INET6, 0);
    SocketDgram_setreuseaddr(sock);  // Allow reuse if port busy
    SocketDgram_bind(sock, "::", 0);  // Ephemeral port, all IPv6 interfaces
    int local_port = SocketDgram_getlocalport(sock);  // Query assigned port
    SOCKET_LOG_INFO_MSG("Bound to port %d", local_port);
} EXCEPT(SocketDgram_Failed) {
    // Fallback to unbind mode if needed
} END_TRY;
Note
Wildcard bind (NULL host) receives from any interface; specify IP for specific NIC.
For IPv6, "::" binds to all; use specific [2001:db8::1] for scoped.
Warning
DNS resolution in host can block; resolve beforehand with getaddrinfo or SocketDNS.
Binding privileged ports requires elevated privileges; catch EACCES and fallback.
Multiple binds to same port possible with SO_REUSEPORT (load balance).
Complexity\n O(1) average - bind() syscall + optional getaddrinfo (O(n) for
DNS)
See also
SocketDgram_new() prerequisite creation.
SocketDgram_isbound() to verify binding success.
SocketDgram_getlocaladdr() / SocketDgram_getlocalport() query bound endpoint.
SocketDgram_setreuseaddr() / SocketDgram_setreuseport() options for reuse.
SocketDgram_connect() complementary for remote endpoint.
getaddrinfo(3) for address resolution details.
docs/SECURITY.md#privileged-ports for permission advice.
docs/ERROR_HANDLING.md for bind-specific errors.
Referenced by main().
SocketDgram_bind_udp()
SocketDgram_T SocketDgram_bind_udp (const char * host, int port) extern
Create a bound UDP socket in one call.
Convenience function that combines SocketDgram_new(), SocketDgram_bind() into a single call. Creates a UDP socket bound to the specified address and port, ready for sending/receiving datagrams.
Parameters
[in] host Local address to bind (NULL or "" for INADDR_ANY)
[in] port Local port to bind (1-65535, or 0 for ephemeral port)
Returns
New bound UDP socket ready for SocketDgram_sendto()/recvfrom()
Exceptions
SocketDgram_Failed on socket creation or bind failure
Thread Safety\n Yes - creates new socket instance
Example
// UDP server
SocketDgram_T server = SocketDgram_bind_udp("0.0.0.0", 5353);
char buf[1024];
char sender_ip[INET6_ADDRSTRLEN];
int sender_port;
while (running) {
    ssize_t n = SocketDgram_recvfrom(server, buf, sizeof(buf),
                                     sender_ip, sizeof(sender_ip),
                                     &sender_port);
    if (n > 0) {
        // Echo back
        SocketDgram_sendto(server, buf, n, sender_ip, sender_port);
    }
}
SocketDgram_free(&server);
Note
Use port 0 to let the OS assign an ephemeral port
For IPv6, use "::" as host for dual-stack binding
See also
SocketDgram_bind() for separate bind operation
SocketDgram_sendto(), SocketDgram_recvfrom() for I/O
Socket_listen_tcp() for TCP server convenience function
SocketDgram_connect()
void SocketDgram_connect (SocketDgram_T socket, const char * host, int port) extern
Set default destination for socket.
Parameters
socket Socket to connect.
host Remote IP address or hostname.
port Remote port.
Exceptions
SocketDgram_Failed on error.
Warning
This function may block during DNS resolution if hostname is provided.
Note
"Connect" for UDP means setting a default destination. After connecting, you can use send/recv instead of sendto/recvfrom.
The socket only accepts packets from the connected address. You can still use sendto/recvfrom to override the default destination.
See also
SocketDgram_bind() for binding to a local address.
SocketDgram_send() for sending to connected destination.
Referenced by main().
SocketDgram_debug_live_count()
int SocketDgram_debug_live_count (void) extern
Get number of live datagram socket instances.
Returns
Number of currently allocated SocketDgram instances.
Thread Safety\n Yes.
Note
Test/debug function for leak detection. Returns count of sockets that have been created but not yet freed.
See also
Socket_debug_live_count() for TCP socket count.
SocketDgram_fd()
int SocketDgram_fd (const SocketDgram_T socket) extern
Get underlying file descriptor.
Parameters
socket Socket instance.
Returns
File descriptor.
See also
Socket_fd() for TCP socket file descriptors.
SocketDgram_free()
void SocketDgram_free (SocketDgram_T * socket) extern
Dispose of a datagram socket, closing the underlying file descriptor and freeing resources.
This function closes the socket FD using close() system call, releases any internal state, and sets the pointer to NULL to prevent use-after-free. It is idempotent if called on NULL. Any pending operations (e.g., in-flight sends) may complete or fail depending on OS. Always pair with SocketDgram_new() in TRY/FINALLY for resource safety.
Edge cases:
Calling on NULL pointer is safe (no-op).
If socket is in use by another thread, behavior is undefined (POSIX not thread-safe for close).
Unclosed multicast memberships are automatically left by kernel on close.
Parameters
[in,out] socket Pointer to the SocketDgram_T handle. Set to NULL on success.
Returns
Void - no return value; errors during close are logged but not raised (to avoid complicating cleanup).
Exceptions
None - Designed for FINALLY blocks; suppresses exceptions during disposal.
Thread Safety\n Conditional - Safe if no concurrent use of this socket instance.
Caller must ensure exclusive access or use mutex. Idempotent for NULL.
Basic Usage
SocketDgram_T sock = NULL;
TRY {
    sock = SocketDgram_new(AF_INET, 0);
    // ... use sock ...
} EXCEPT(SocketDgram_Failed) {
    // handle
} FINALLY {
    SocketDgram_free(&sock);  // Always call, even on error or NULL
} END_TRY;
In Pool or Array Management
SocketDgram_T sockets[10] = {0};
// ... populate some sockets ...
for (int i = 0; i < 10; i++) {
    SocketDgram_free(&sockets[i]);  // Safe for uninitialized (NULL)
}
Note
Internal resources (e.g., buffers allocated from Arena) are freed if associated.
Decrements global live count for leak detection in SocketDgram_debug_live_count().
Warning
Do not access socket after free; leads to undefined behavior (double free, invalid FD).
Close is not atomic; avoid calling while other threads read/write the socket.
Complexity\n O(1) - Single close() call and pointer cleanup.
See also
SocketDgram_new() for paired creation.
Arena_dispose() for arena cleanup if sockets use custom allocator.
SocketDgram_debug_live_count() for verifying all sockets freed in tests.
docs/ERROR_HANDLING.md#finally-blocks for cleanup patterns.
Referenced by main().
SocketDgram_getbroadcast()
int SocketDgram_getbroadcast (SocketDgram_T socket) extern
Get broadcast setting.
Parameters
socket Socket to query.
Returns
1 if broadcast is enabled, 0 if disabled.
Exceptions
SocketDgram_Failed on error.
See also
SocketDgram_setbroadcast() for setting broadcast mode.
SocketDgram_getlocaladdr()
const char * SocketDgram_getlocaladdr (const SocketDgram_T socket) extern
Get local IP address.
Parameters
socket Socket instance.
Returns
IP address string (IPv4/IPv6) or "(unknown)" if unavailable.
Note
Returns "(unknown)" if address info unavailable. String is owned by socket, must not be freed/modified.
Valid until socket freed.
See also
SocketDgram_getlocalport() for local port.
SocketDgram_bind() for binding operations.
SocketDgram_getlocalport()
int SocketDgram_getlocalport (const SocketDgram_T socket) extern
Get local port number.
Parameters
socket Socket instance.
Returns
Port number (1 to SOCKET_MAX_PORT) or 0 if unavailable.
See also
SocketDgram_getlocaladdr() for local address.
SocketDgram_bind() for binding operations.
SocketDgram_getrcvbuf()
int SocketDgram_getrcvbuf (SocketDgram_T socket) extern
Get receive buffer size.
Parameters
socket Socket to query.
Returns
Receive buffer size in bytes.
Exceptions
SocketDgram_Failed on error.
See also
SocketDgram_getsndbuf() for send buffer size.
SocketDgram_getsndbuf()
int SocketDgram_getsndbuf (SocketDgram_T socket) extern
Get send buffer size.
Parameters
socket Socket to query.
Returns
Send buffer size in bytes.
Exceptions
SocketDgram_Failed on error.
See also
SocketDgram_getrcvbuf() for receive buffer size.
SocketDgram_gettimeout()
int SocketDgram_gettimeout (SocketDgram_T socket) extern
Get socket timeout.
Parameters
socket Socket to query.
Returns
Timeout in seconds (0 if disabled).
Exceptions
SocketDgram_Failed on error.
Note
Returns receive timeout (send timeout may differ).
See also
SocketDgram_settimeout() for setting the timeout.
SocketDgram_getttl()
int SocketDgram_getttl (SocketDgram_T socket) extern
Get time-to-live (hop limit).
Parameters
socket Socket to query.
Returns
TTL value (1-255).
Exceptions
SocketDgram_Failed on error.
See also
SocketDgram_setttl() for setting TTL.
SocketDgram_isbound()
int SocketDgram_isbound (SocketDgram_T socket) extern
Check if datagram socket is bound to an address.
Parameters
socket Socket to check.
Returns
1 if bound, 0 if not bound.
Thread Safety\n Yes (operates on single socket).
Note
Uses getsockname() to determine binding state.
A socket is bound if getsockname() succeeds and returns a valid address.
Wildcard addresses (0.0.0.0 or ::) still count as bound.
See also
SocketDgram_bind() for binding sockets.
SocketDgram_isconnected() for checking connection state.
SocketDgram_isconnected()
int SocketDgram_isconnected (SocketDgram_T socket) extern
Check if datagram socket is connected.
Parameters
socket Socket to check.
Returns
1 if connected, 0 if not connected.
Thread Safety\n Yes (operates on single socket).
Note
Uses getpeername() to determine connection state.
For UDP sockets, "connected" means a default destination is set.
See also
SocketDgram_connect() for connecting sockets.
SocketDgram_isbound() for checking binding state.
SocketDgram_joinmulticast()
void SocketDgram_joinmulticast (SocketDgram_T socket, const char * group, const char * interface) extern
Join multicast group.
Parameters
socket Socket to modify.
group Multicast group address (e.g., "224.0.0.1" for IPv4).
interface Interface address or NULL for default.
Exceptions
SocketDgram_Failed on error.
Note
For IPv4, group should be in range 224.0.0.0 - 239.255.255.255.
For IPv6, group should start with ff00::/8.
See also
SocketDgram_leavemulticast() for leaving multicast groups.
SocketDgram_setttl() for controlling multicast reach.
SocketDgram_leavemulticast()
void SocketDgram_leavemulticast (SocketDgram_T socket, const char * group, const char * interface) extern
Leave multicast group.
Parameters
socket Socket to modify.
group Multicast group address.
interface Interface address or NULL for default.
Exceptions
SocketDgram_Failed on error.
See also
SocketDgram_joinmulticast() for joining multicast groups.
SocketDgram_new()
SocketDgram_T SocketDgram_new (int domain, int protocol) extern
Create a new UDP/datagram socket with specified domain and protocol.
Creates and initializes a new datagram socket using the underlying socket() system call. The socket is created in blocking mode by default, unbound, and unconnected. It supports standard socket options and inherits OS defaults for buffers and TTL. Automatic handling of SIGPIPE and EINTR ensures robust operation in multi-threaded environments. Exception-based error handling simplifies code by eliminating manual errno checks.
Edge cases and considerations:
Invalid domain/protocol combinations may fail immediately.
System resource limits (e.g., max open files via ulimit -n) can cause failures.
For AF_UNIX, ensure the path directory exists and has write permissions.
IPv6 sockets can handle IPv4 mappings if V6_V6ONLY is not set (default behavior).
Typical usage patterns include creating a server socket for recvfrom loops or a client socket for sendto with optional connect for optimized repeated sends.
Parameters
[in] domain Address family specifying the protocol family. Common values: AF_INET (IPv4), AF_INET6 (IPv6), AF_UNIX (Unix domain datagrams).
[in] protocol Protocol number within the domain. Usually 0 to auto-select IPPROTO_UDP for SOCK_DGRAM type (implicit).
Returns
A new opaque SocketDgram_T handle representing the created socket.
Exceptions
SocketDgram_Failed If the socket creation fails, typically due to:
EACCES: Insufficient privileges (e.g., binding privileged ports <1024 without root)
EMFILE: Process file descriptor limit exceeded
ENFILE: System-wide file descriptor limit exceeded
ENOMEM: Insufficient memory for socket structures
EPROTONOSUPPORT: Specified protocol not supported
Other system errors mapped via internal SocketError_categorize_errno() Use Socket_GetLastError() post-exception for detailed message and errno.
Thread Safety\n Yes - Each call creates an independent socket instance with no
shared state. Safe to invoke concurrently from multiple threads.
Basic Usage
TRY {
    SocketDgram_T sock = SocketDgram_new(AF_INET, 0);  // IPv4 UDP socket
    if (sock) {
        SocketDgram_bind(sock, "0.0.0.0", 0);  // Bind to ephemeral port
        // Use sock for sendto/recvfrom
    }
} EXCEPT(SocketDgram_Failed) {
    SOCKET_LOG_ERROR_MSG("Socket creation failed: %s",
Socket_GetLastError());
    // Handle (e.g., retry, exit)
} FINALLY {
    SocketDgram_free(&sock);
} END_TRY;
Advanced Usage: IPv6 Multicast Receiver
TRY {
    SocketDgram_T sock = SocketDgram_new(AF_INET6, 0);
    SocketDgram_setreuseaddr(sock);
    SocketDgram_setreuseport(sock);  // Allow multiple instances on same
port SocketDgram_bind(sock, "::", 5353);  // Bind to IPv6 any, mDNS port
    SocketDgram_joinmulticast(sock, "ff02::fb", "::");  // Join mDNS group
on default interface SocketDgram_setttl(sock, 255);  // Full network reach
    SocketDgram_setnonblocking(sock);  // For SocketPoll integration
    // Add to SocketPoll_add(poll, sock, POLL_READ, userdata);
} EXCEPT(SocketDgram_Failed) {
    // Error handling with logging
} END_TRY;
Note
The protocol parameter defaults to IPPROTO_UDP when 0 and domain supports it. Specify explicitly for custom protocols (e.g., IPPROTO_SCTP for SCTP datagrams).
Newly created sockets have SO_REUSEADDR disabled, blocking mode enabled, and default buffer sizes (tunable via getsockopt/SocketDgram_getrcvbuf).
Warning
Do not use large datagrams (>64KB) as they may fail or fragment unpredictably.
For security, always validate parameters; user input should be sanitized before passing.
In production, monitor SocketDgram_debug_live_count() in tests to ensure no leaks.
Complexity\n O(1) - Involves a single socket() system call plus minimal
initialization.
See also
SocketDgram_free() for destruction and FD close.
SocketDgram_bind() to associate with local address/port.
SocketDgram_connect() to set default peer for send/recv optimization.
SocketDgram_setnonblocking() for asynchronous operation.
SocketDgram_setreuseaddr() / SocketDgram_setreuseport() for binding options.
Socket_T::Socket_new() counterpart for stream sockets.
SocketPoll_T::SocketPoll_add() for event loop integration.
SocketDNS_resolve_sync() for resolving hostnames before connect/bind.
docs/ERROR_HANDLING.md for advanced exception patterns.
docs/SECURITY.md for socket permission and firewall considerations.
Referenced by main().
SocketDgram_recv()
ssize_t SocketDgram_recv (SocketDgram_T socket, void * buf, size_t len) extern
Receive from default source (connected socket).
Parameters
socket Connected socket.
buf Buffer for received data.
len Buffer size (must be > 0).
Returns
Number of bytes received (> 0), or 0 if would block (EAGAIN/EWOULDBLOCK).
Exceptions
SocketDgram_Failed on error.
Note
Socket must be connected via SocketDgram_connect() first. Only accepts packets from the connected address.
See also
SocketDgram_send() for sending to connected sockets.
SocketDgram_recvfrom() for receiving with sender info.
Referenced by main().
SocketDgram_recvall()
ssize_t SocketDgram_recvall (SocketDgram_T socket, void * buf, size_t len) extern
Receive all requested data (handles partial receives).
Parameters
socket Connected socket.
buf Buffer for received data.
len Buffer size (> 0).
Returns
Total bytes received (always equals len on success).
Exceptions
SocketDgram_Failed on error.
Thread Safety\n Yes (operates on single socket).
Note
Loops until len bytes are received or an error occurs.
For non-blocking sockets, returns 0 if would block (EAGAIN/EWOULDBLOCK).
Use SocketDgram_isconnected() to verify connection state before calling.
See also
SocketDgram_recv() for partial receive operations.
SocketDgram_sendall() for sending all data.
SocketDgram_recvfrom()
ssize_t SocketDgram_recvfrom (SocketDgram_T socket, void * buf, size_t len, char * host, size_t host_len, int * port) extern
Receive datagram and get sender address.
Parameters
socket Socket to receive from.
buf Buffer for received data.
len Buffer size (must be > 0).
host Output - sender IP address (buffer must be >= 46 bytes for IPv6).
host_len Size of host buffer.
port Output - sender port number.
Returns
Number of bytes received (> 0), or 0 if would block (EAGAIN/EWOULDBLOCK).
Exceptions
SocketDgram_Failed on error.
Note
UDP is message-oriented. If buffer is too small, data is truncated.
Recommended buffer size >= 65507 bytes (max UDP payload) to avoid truncation.
Common buffer sizes: 8192 (8KB), 65536 (64KB).
The host parameter receives the sender's IP address as a string.
The port parameter receives the sender's port number.
See also
SocketDgram_sendto() for sending datagrams.
SocketDgram_recv() for receiving from connected sockets.
Referenced by main().
SocketDgram_recvv()
ssize_t SocketDgram_recvv (SocketDgram_T socket, struct iovec * iov, int iovcnt) extern
Scatter/gather receive (readv wrapper).
Parameters
socket Connected socket.
iov Array of iovec structures.
iovcnt Number of iovec structures (> 0, <= IOV_MAX).
Returns
Total bytes received (> 0) or 0 if would block (EAGAIN/EWOULDBLOCK).
Exceptions
SocketDgram_Failed on error.
Thread Safety\n Yes (operates on single socket).
Note
Receives data into multiple buffers in a single system call.
May receive less than requested. Use SocketDgram_recvvall() for guaranteed complete receive.
See also
SocketDgram_sendv() for scatter/gather send.
SocketDgram_recvvall() for guaranteed complete scatter/gather receive.
SocketDgram_recvvall()
ssize_t SocketDgram_recvvall (SocketDgram_T socket, struct iovec * iov, int iovcnt) extern
Scatter/gather receive all (handles partial receives).
Parameters
socket Connected socket.
iov Array of iovec structures.
iovcnt Number of iovec structures (> 0, <= IOV_MAX).
Returns
Total bytes received (always equals sum of all iov_len on success).
Exceptions
SocketDgram_Failed on error.
Thread Safety\n Yes (operates on single socket).
Note
Loops until all requested data is received into all buffers or an error occurs.
For non-blocking sockets, returns partial progress if would block.
Use SocketDgram_isconnected() to verify connection state before calling.
See also
SocketDgram_recvv() for partial scatter/gather receive.
SocketDgram_sendvall() for sending all scatter/gather data.
SocketDgram_send()
ssize_t SocketDgram_send (SocketDgram_T socket, const void * buf, size_t len) extern
Send to default destination (connected socket).
Parameters
socket Connected socket.
buf Data to send.
len Length of data (must be > 0).
Returns
Number of bytes sent (> 0), or 0 if would block (EAGAIN/EWOULDBLOCK).
Exceptions
SocketDgram_Failed on error.
Note
Socket must be connected via SocketDgram_connect() first.
See also
SocketDgram_recv() for receiving from connected sockets.
SocketDgram_sendto() for sending to arbitrary addresses.
Referenced by main().
SocketDgram_sendall()
ssize_t SocketDgram_sendall (SocketDgram_T socket, const void * buf, size_t len) extern
Send all data (handles partial sends).
Parameters
socket Connected socket.
buf Data to send.
len Length of data (> 0).
Returns
Total bytes sent (always equals len on success).
Exceptions
SocketDgram_Failed on error.
Thread Safety\n Yes (operates on single socket).
Note
Loops until all data is sent or an error occurs.
For non-blocking sockets, returns 0 if would block (EAGAIN/EWOULDBLOCK).
Use SocketDgram_isconnected() to verify connection state before calling.
See also
SocketDgram_send() for partial send operations.
SocketDgram_recvall() for receiving all data.
SocketDgram_sendto()
ssize_t SocketDgram_sendto (SocketDgram_T socket, const void * buf, size_t len, const char * host, int port) extern
Send datagram to specific address.
Parameters
socket Socket to send from.
buf Data to send.
len Length of data (must be > 0).
host Destination IP address or hostname.
port Destination port.
Returns
Number of bytes sent (> 0), or 0 if would block (EAGAIN/EWOULDBLOCK).
Exceptions
SocketDgram_Failed on error.
Warning
This function may block during DNS resolution if hostname is provided.
Note
UDP sends complete datagrams. If len > MTU, fragmentation may occur.
Recommended to keep len <= 1472 bytes to avoid fragmentation (1500 MTU
headers).
Unlike TCP, send may return less than len only on would-block, not partial sends.
See also
SocketDgram_recvfrom() for receiving datagrams.
SocketDgram_connect() for setting default destination.
Referenced by main().
SocketDgram_sendv()
ssize_t SocketDgram_sendv (SocketDgram_T socket, const struct iovec * iov, int iovcnt) extern
Scatter/gather send (writev wrapper).
Parameters
socket Connected socket.
iov Array of iovec structures.
iovcnt Number of iovec structures (> 0, <= IOV_MAX).
Returns
Total bytes sent (> 0) or 0 if would block (EAGAIN/EWOULDBLOCK).
Exceptions
SocketDgram_Failed on error.
Thread Safety\n Yes (operates on single socket).
Note
Sends data from multiple buffers in a single system call.
May send less than requested. Use SocketDgram_sendvall() for guaranteed complete send.
See also
SocketDgram_recvv() for scatter/gather receive.
SocketDgram_sendvall() for guaranteed complete scatter/gather send.
SocketDgram_sendvall()
ssize_t SocketDgram_sendvall (SocketDgram_T socket, const struct iovec * iov, int iovcnt) extern
Scatter/gather send all (handles partial sends).
Parameters
socket Connected socket.
iov Array of iovec structures.
iovcnt Number of iovec structures (> 0, <= IOV_MAX).
Returns
Total bytes sent (always equals sum of all iov_len on success).
Exceptions
SocketDgram_Failed on error.
Thread Safety\n Yes (operates on single socket).
Note
Loops until all data from all buffers is sent or an error occurs.
For non-blocking sockets, returns partial progress if would block.
Use SocketDgram_isconnected() to verify connection state before calling.
See also
SocketDgram_sendv() for partial scatter/gather send.
SocketDgram_recvvall() for receiving all scatter/gather data.
SocketDgram_setbroadcast()
void SocketDgram_setbroadcast (SocketDgram_T socket, int enable) extern
Enable broadcast.
Parameters
socket Socket to modify.
enable 1 to enable, 0 to disable.
Exceptions
SocketDgram_Failed on error.
Note
Required to send broadcast datagrams to 255.255.255.255 or subnet broadcast addresses.
See also
SocketDgram_joinmulticast() for multicast operations.
SocketDgram_sendto() for sending broadcast datagrams.
SocketDgram_setcloexec()
void SocketDgram_setcloexec (SocketDgram_T socket, int enable) extern
Control close-on-exec flag.
Parameters
socket Socket to modify.
enable 1 to enable CLOEXEC, 0 to disable.
Exceptions
SocketDgram_Failed on error.
Thread Safety\n Yes (operates on single socket).
Note
By default, all sockets have CLOEXEC enabled. This function allows disabling it if you need to pass the socket to a child process.
See also
Socket_setcloexec() for TCP socket CLOEXEC control.
SocketDgram_setnonblocking()
void SocketDgram_setnonblocking (SocketDgram_T socket) extern
Enable non-blocking mode.
Parameters
socket Socket to modify.
Exceptions
SocketDgram_Failed on error.
See also
SocketDgram_setreuseaddr() for address reuse.
Socket_bind() for binding operations.
SocketDgram_setreuseaddr()
void SocketDgram_setreuseaddr (SocketDgram_T socket) extern
Enable address reuse.
Parameters
socket Socket to modify.
Exceptions
SocketDgram_Failed on error.
See also
SocketDgram_setreuseport() for port reuse.
SocketDgram_bind() for binding operations.
SocketDgram_setreuseport()
void SocketDgram_setreuseport (SocketDgram_T socket) extern
Enable port reuse across sockets.
Parameters
socket Socket to modify.
Exceptions
SocketDgram_Failed on error (or if SO_REUSEPORT unsupported).
See also
SocketDgram_setreuseaddr() for address reuse.
Socket_bind() for binding operations.
SocketDgram_settimeout()
void SocketDgram_settimeout (SocketDgram_T socket, int timeout_sec) extern
Set socket timeout.
Parameters
socket Socket to modify.
timeout_sec Timeout in seconds (0 to disable).
Exceptions
SocketDgram_Failed on error.
Note
Sets receive timeout to prevent blocking indefinitely.
Useful for signal-responsive servers. With timeout, recvfrom returns 0 (would-block) after timeout.
Allows the event loop to check for shutdown signals.
See also
SocketDgram_gettimeout() for retrieving the current timeout.
SocketDgram_recvfrom() for timeout behavior.
SocketDgram_setttl()
void SocketDgram_setttl (SocketDgram_T socket, int ttl) extern
Set time-to-live (hop limit).
Parameters
socket Socket to modify.
ttl TTL value (1-255).
Exceptions
SocketDgram_Failed on error.
Note
TTL controls how many network hops a packet can traverse.
Default is usually 64. Use 1 for link-local only.
See also
SocketDgram_joinmulticast() for multicast group operations.
SocketDgram_sendto() for sending datagrams.
Variable Documentation
SocketDgram_Failed
const Except_T SocketDgram_Failed extern
Exception type for general failures in datagram socket operations.
This is the primary exception raised by SocketDgram functions for errors such as:
System call failures (bind, connect, sendto, etc.)
Invalid parameters (null pointers, invalid ports, buffer overflows)
Resource exhaustion (out of FDs, memory)
Protocol violations (e.g., invalid multicast address)
It wraps errno and provides context via Socket_GetLastError() for diagnostics. Use in EXCEPT blocks to catch and handle specific conditions, or SocketError_categorize_errno() to classify as retryable/transient vs permanent.
Hierarchy: Extends Except_T base with module-specific message formatting. Thread-local stack via Except_stack for propagation.
Best practice: Catch in FINALLY-free patterns; log with SOCKET_LOG_ERROR_MSG including errno.
Handling Example
TRY {
    SocketDgram_T sock = SocketDgram_new(AF_INET, 0);
    SocketDgram_bind(sock, NULL, 80);  // May fail without root
} EXCEPT(SocketDgram_Failed) {
    int err = Socket_geterrno();
    const char *msg = Socket_GetLastError();
    SOCKET_LOG_ERROR_MSG("Datagram error: %s (errno=%d)", msg, err);
    if (SocketError_is_retryable_errno(err)) {
        // Retry logic
    } else {
        // Fatal error handling
    }
} END_TRY;
Note
Message includes file/line/context from raise site for debugging.
Warning
Suppress only in cleanup; always log for production monitoring.
See also
Except_T base exception type and TRY/EXCEPT syntax.
Socket_GetLastError() / Socket_geterrno() for details.
SocketError_is_retryable_errno() for classification.
docs/ERROR_HANDLING.md for comprehensive guide.
docs/LOGGING.md for logging integration.