Tetsuo Pulse: WebSocket Modules
WebSocket Modules
WebSocket protocol support for client and server, with framing, compression, and integration.
Files
file SocketWS-private.h
Internal implementation details for WebSocket module.
file SocketWS.h
WebSocket Protocol (RFC 6455) implementation with compression support.
Data Structures
struct SocketWS_FrameParse
Context for parsing incoming WebSocket frames.
struct SocketWS_MessageAssembly
State for reassembling fragmented WebSocket messages.
struct SocketWS_Handshake
Context for WebSocket HTTP upgrade handshake.
struct SocketWS_T
Opaque WebSocket connection context holding all protocol state.
struct SocketWS_Config
Configuration parameters for WebSocket instances.
struct SocketWS_Frame
Structure representing a parsed WebSocket frame.
struct SocketWS_Message
Complete reassembled WebSocket message from recv_message().
struct SocketWS_CompressionOptions
WebSocket compression options.
Macros
#define SOCKETWS_MAX_FRAME_SIZE (16 * 1024 * 1024)
#define SOCKETWS_PROTOCOL_VERSION "13"
#define SOCKETWS_XOR_ALIGN_SIZE 8
#define SOCKETWS_BASE_HEADER_SIZE 2
#define SOCKETWS_FIN_BIT 0x80
#define SOCKETWS_SEND_CHUNK_SIZE 8192
#define RAISE_WS_ERROR(e) SOCKET_RAISE_MODULE_ERROR (SocketWS, e)
Thread-local exception declarations for SocketWS module.
#define T SocketWS_T
Enumerations
enum SocketWS_FrameState {
WS_FRAME_STATE_HEADER ,
WS_FRAME_STATE_EXTENDED_LEN ,
WS_FRAME_STATE_MASK_KEY ,
WS_FRAME_STATE_PAYLOAD ,
WS_FRAME_STATE_COMPLETE
}
States for the frame parsing state machine.
enum SocketWS_HandshakeState {
WS_HANDSHAKE_INIT ,
WS_HANDSHAKE_SENDING_REQUEST ,
WS_HANDSHAKE_READING_RESPONSE ,
WS_HANDSHAKE_COMPLETE ,
WS_HANDSHAKE_FAILED
}
States for WebSocket HTTP upgrade handshake.
enum SocketWS_Opcode {
WS_OPCODE_CONTINUATION = 0x0 ,
WS_OPCODE_TEXT = 0x1 ,
WS_OPCODE_BINARY = 0x2 ,
WS_OPCODE_CLOSE = 0x8 ,
WS_OPCODE_PING = 0x9 ,
WS_OPCODE_PONG = 0xA
}
WebSocket frame opcodes as defined in RFC 6455 section 5.2.
enum SocketWS_CloseCode {
WS_CLOSE_NORMAL = 1000 ,
WS_CLOSE_GOING_AWAY = 1001 ,
WS_CLOSE_PROTOCOL_ERROR = 1002 ,
WS_CLOSE_UNSUPPORTED_DATA = 1003 ,
WS_CLOSE_NO_STATUS = 1005 ,
WS_CLOSE_ABNORMAL = 1006 ,
WS_CLOSE_INVALID_PAYLOAD = 1007 ,
WS_CLOSE_POLICY_VIOLATION = 1008 ,
WS_CLOSE_MESSAGE_TOO_BIG = 1009 ,
WS_CLOSE_MANDATORY_EXT = 1010 ,
WS_CLOSE_INTERNAL_ERROR = 1011 ,
WS_CLOSE_SERVICE_RESTART = 1012 ,
WS_CLOSE_TRY_AGAIN_LATER = 1013 ,
WS_CLOSE_BAD_GATEWAY = 1014 ,
WS_CLOSE_TLS_HANDSHAKE = 1015
}
Status codes for WebSocket CLOSE frames (RFC 6455 section 7.4).
enum SocketWS_State {
WS_STATE_CONNECTING ,
WS_STATE_OPEN ,
WS_STATE_CLOSING ,
WS_STATE_CLOSED
}
WebSocket connection lifecycle states.
enum SocketWS_Role {
WS_ROLE_CLIENT ,
WS_ROLE_SERVER
}
WebSocket endpoint roles per RFC 6455.
enum SocketWS_Error {
WS_OK = 0 ,
WS_ERROR ,
WS_ERROR_HANDSHAKE ,
WS_ERROR_PROTOCOL ,
WS_ERROR_FRAME_TOO_LARGE ,
WS_ERROR_MESSAGE_TOO_LARGE ,
WS_ERROR_INVALID_UTF8 ,
WS_ERROR_COMPRESSION ,
WS_ERROR_CLOSED ,
WS_ERROR_WOULD_BLOCK ,
WS_ERROR_TIMEOUT
}
WebSocket-specific error codes for SocketWS_last_error().
Functions
char * ws_copy_string (Arena_T arena, const char *str)
Arena-allocated duplicate of input string.
int ws_send_control_frame (SocketWS_T ws, SocketWS_Opcode opcode, const unsigned char *payload, size_t len)
Sends WebSocket control frame: PING, PONG, or CLOSE.
int ws_send_data_frame (SocketWS_T ws, SocketWS_Opcode opcode, const unsigned char *data, size_t len, int fin)
Sends a WebSocket data frame (TEXT or BINARY).
void ws_frame_reset (SocketWS_FrameParse *frame)
Reset frame parser to initial state for new incoming frame.
SocketWS_Error ws_frame_parse_header (SocketWS_FrameParse *frame, const unsigned char *data, size_t len, size_t *consumed)
Incrementally parses WebSocket frame header from input data.
size_t ws_frame_build_header (unsigned char *header, int fin, SocketWS_Opcode opcode, int masked, const unsigned char *mask_key, uint64_t payload_len)
Builds the binary WebSocket frame header into output buffer.
void ws_mask_payload (unsigned char *data, size_t len, const unsigned char mask[4])
Applies XOR masking to WebSocket payload data in place.
size_t ws_mask_payload_offset (unsigned char *data, size_t len, const unsigned char mask[4], size_t offset)
Applies XOR masking to payload starting from a given mask offset.
int ws_handshake_client_init (SocketWS_T ws)
Initializes the client-side WebSocket handshake.
int ws_handshake_client_process (SocketWS_T ws)
Processes client handshake I/O in non-blocking manner.
int ws_handshake_server_init (SocketWS_T ws, const SocketHTTP_Request *request)
Initializes the server-side WebSocket handshake from HTTP request.
int ws_handshake_server_process (SocketWS_T ws)
Processes server handshake I/O in non-blocking manner.
int ws_handshake_validate_accept (SocketWS_T ws, const char *accept)
Validates the server's Sec-WebSocket-Accept header value.
int ws_send_close (SocketWS_T ws, SocketWS_CloseCode code, const char *reason)
Sends a WebSocket CLOSE control frame to initiate graceful shutdown.
int ws_send_ping (SocketWS_T ws, const unsigned char *payload, size_t len)
Sends a WebSocket PING control frame for keepalive.
int ws_send_pong (SocketWS_T ws, const unsigned char *payload, size_t len)
Sends a WebSocket PONG control frame in response to PING.
int ws_handle_control_frame (SocketWS_T ws, SocketWS_Opcode opcode, const unsigned char *payload, size_t len)
Handles a received WebSocket control frame (CLOSE, PING, PONG).
void ws_message_reset (SocketWS_MessageAssembly *message)
Resets the message reassembly state for a new message.
int ws_message_append (SocketWS_T ws, const unsigned char *data, size_t len, int is_text)
Appends a data frame fragment to the current message assembly.
int ws_message_finalize (SocketWS_T ws)
Finalizes message assembly on last fragment and delivers to user.
int ws_auto_ping_start (SocketWS_T ws, SocketPoll_T poll)
Starts the automatic PING timer for keepalive.
void ws_auto_ping_stop (SocketWS_T ws)
Stops the automatic PING timer.
void ws_auto_ping_callback (void *userdata)
Timer callback invoked to send periodic PING.
ssize_t ws_flush_send_buffer (SocketWS_T ws)
Flushes pending data from send buffer to underlying socket.
ssize_t ws_fill_recv_buffer (SocketWS_T ws)
Fills the receive buffer from the underlying socket.
void ws_set_error (SocketWS_T ws, SocketWS_Error error, const char *fmt,...)
Sets the last error code and formats error message.
static int ws_is_control_opcode (SocketWS_Opcode opcode)
Check if opcode represents a control frame.
static int ws_is_data_opcode (SocketWS_Opcode opcode)
Check if opcode represents a data frame.
static int ws_is_valid_opcode (SocketWS_Opcode opcode)
Checks if a WebSocket opcode is valid per RFC 6455.
static int ws_is_valid_close_code (int code)
Validate close status code per RFC 6455.
void SocketWS_config_defaults (SocketWS_Config *config)
Initialize WebSocket configuration with default values.
SocketWS_T SocketWS_client_new (Socket_T socket, const char *host, const char *path, const SocketWS_Config *config)
Create a new client WebSocket instance from a connected TCP socket.
int SocketWS_is_upgrade (const SocketHTTP_Request *request)
Check if an HTTP request is a valid WebSocket upgrade request.
SocketWS_T SocketWS_server_accept (Socket_T socket, const SocketHTTP_Request *request, const SocketWS_Config *config)
Accept a WebSocket upgrade from a parsed HTTP request on a server socket.
void SocketWS_server_reject (Socket_T socket, int status_code, const char *reason)
Reject a WebSocket upgrade request with an HTTP error response.
void SocketWS_free (SocketWS_T *ws)
Dispose of a WebSocket instance, closing connection if open.
int SocketWS_handshake (SocketWS_T ws)
Perform or continue the WebSocket handshake process.
SocketWS_State SocketWS_state (SocketWS_T ws)
Retrieve the current state of the WebSocket connection.
Socket_T SocketWS_socket (SocketWS_T ws)
Access the underlying TCP socket for the WebSocket.
const char * SocketWS_selected_subprotocol (SocketWS_T ws)
Get the negotiated WebSocket subprotocol.
int SocketWS_compression_enabled (SocketWS_T ws)
Check if compression is enabled.
int SocketWS_send_text (SocketWS_T ws, const char *data, size_t len)
Send a text message over the WebSocket (opcode TEXT).
int SocketWS_send_binary (SocketWS_T ws, const void *data, size_t len)
Send a binary message over the WebSocket (opcode BINARY).
int SocketWS_ping (SocketWS_T ws, const void *data, size_t len)
Send a PING control frame for keepalive or to solicit immediate response from peer.
int SocketWS_pong (SocketWS_T ws, const void *data, size_t len)
Send a PONG control frame, typically in response to PING.
int SocketWS_close (SocketWS_T ws, int code, const char *reason)
Initiate graceful WebSocket close handshake.
int SocketWS_recv_message (SocketWS_T ws, SocketWS_Message *msg)
Receive and reassemble a complete WebSocket message.
int SocketWS_recv_available (SocketWS_T ws)
Check for complete messages ready to receive without blocking.
int SocketWS_pollfd (SocketWS_T ws)
Get the underlying socket file descriptor for use with poll/epoll/kqueue.
unsigned SocketWS_poll_events (SocketWS_T ws)
Determine required poll events for the WebSocket socket.
int SocketWS_process (SocketWS_T ws, unsigned events)
Process socket events to advance WebSocket state machine.
int SocketWS_enable_auto_ping (SocketWS_T ws, SocketPoll_T poll)
Enable automatic periodic PING for connection keepalive.
void SocketWS_disable_auto_ping (SocketWS_T ws)
Disable and cancel automatic PING keepalive timer.
int SocketWS_close_code (SocketWS_T ws)
Get close code from close frame.
const char * SocketWS_close_reason (SocketWS_T ws)
Get close reason text from close frame.
SocketWS_Error SocketWS_last_error (SocketWS_T ws)
Retrieve the most recent error code for this WebSocket instance.
const char * SocketWS_error_string (SocketWS_Error error)
Get a human-readable string describing a WebSocket error code.
SocketWS_T SocketWS_connect (const char *url, const char *protocols)
One-liner WebSocket client connection.
int SocketWS_send_json (SocketWS_T ws, const char *json)
Send JSON as text frame.
SocketWS_Error SocketWS_recv_json (SocketWS_T ws, char **json_out, size_t *json_len)
Receive and return JSON string.
int64_t SocketWS_get_ping_latency (SocketWS_T ws)
Get ping/pong round-trip time.
void SocketWS_compression_options_defaults (SocketWS_CompressionOptions *options)
Initialize compression options with defaults.
int SocketWS_enable_compression (SocketWS_T ws, const SocketWS_CompressionOptions *options)
Enable permessage-deflate compression.
Variables
const Except_T SocketWS_Failed
Exception raised for general WebSocket operation failures.
const Except_T SocketWS_ProtocolError
Exception for WebSocket protocol violations (RFC 6455 non-compliance).
const Except_T SocketWS_Closed
Exception indicating the WebSocket connection has been closed.
Detailed Description
WebSocket protocol support for client and server, with framing, compression, and integration.
The WebSocket module provides full support for the WebSocket protocol (RFC 6455), including client and server roles, message framing, control frames (ping/pong/close), fragmentation, UTF-8 validation, and optional permessage-deflate compression (RFC 7692).
Key Features:
Non-blocking I/O compatible with SocketPoll.
Automatic handling of control frames.
Subprotocol negotiation during handshake.
Integration with SocketTLS for secure WebSocket (wss://).
Configurable limits for frame/message sizes.
Dependencies:
HTTP Modules (SocketHTTP, SocketHTTP1 for upgrade handshake)
Core I/O Modules (Socket, SocketBuf for I/O)
Core Foundation Modules (Arena, Except for memory/errors)
Utilities (SocketUTF8 for text validation, SocketCrypto for masking)
Event System Modules (SocketPoll, SocketTimer for events and keepalive)
Usage:
Server: Detect upgrade in HTTP request, accept with SocketWS_server_accept(), handshake.
Client: Connect socket, create with SocketWS_client_new(), handshake.
Send/Recv: Use send_text/binary, recv_message in OPEN state.
Event Loop: Poll with SocketWS_pollfd/events, process events.
Error Handling:
Uses SocketWS_* exceptions for failures.
SocketWS_Error enum for detailed codes.
See also
SocketWS_Config for configuration options.
SocketWS_Message for received messages.
SocketWS_State for connection states.
Data Structure Documentation
SocketWS_FrameParse
struct SocketWS_FrameParse
Context for parsing incoming WebSocket frames.
Manages incremental parsing of frame headers and payloads. Supports partial reads for non-blocking sockets. Handles variable-length fields: opcode/fin/rsv, mask bit, 7/16/64-bit length, optional mask key.
Usage:
Initialize: memset or ws_frame_reset()
Parse: ws_frame_parse_header() advances state and parses bytes
Payload: Read payload_received bytes after header complete
Reset: ws_frame_reset() for next frame
See also
SocketWS_FrameState for parsing states.
ws_frame_parse_header() main entry point.
ws_frame_build_header() for sending frames.
RFC 6455 Section 5.2 for frame format details.
Definition at line 314 of file SocketWS-private.h.
Data Fields
int fin
FIN bit: final fragment of message
unsigned char header_buf[14]
Temp buffer for header bytes
size_t header_len
Bytes accumulated in header_buf
size_t header_needed
Remaining bytes needed for current field
unsigned char mask_key[4]
4-byte mask key if masked
int masked
MASK bit: payload masked (client->server)
SocketWS_Opcode opcode
Frame opcode (data/control)
uint64_t payload_len
Total payload length
uint64_t payload_received
Bytes of payload received so far
int rsv1
RSV1: compression flag (permessage-deflate)
int rsv2
RSV2: reserved, must be 0
int rsv3
RSV3: reserved, must be 0
SocketWS_FrameState state
Current parsing state
SocketWS_MessageAssembly
struct SocketWS_MessageAssembly
State for reassembling fragmented WebSocket messages.
Accumulates data from multiple CONTINUATION frames into a single message buffer. Supports UTF-8 validation for text messages across fragments. Handles compression flag from first frame (RSV1).
Limits enforced via config: max_message_size, max_fragments.
Usage:
Reset: ws_message_reset() before first fragment
Append: ws_message_append() for each data frame fragment
Finalize: ws_message_finalize() on last fragment (FIN=1), validates and delivers
See also
ws_message_append() for adding fragments.
ws_message_finalize() for completion and validation.
SocketWS_Message for public message interface.
RFC 6455 Section 5.4 for fragmentation rules.
Definition at line 366 of file SocketWS-private.h.
Data Fields
size_t capacity
Allocated buffer capacity
int compressed
RSV1 set on first fragment (compression used)
unsigned char * data
Reassembled message buffer (Arena-allocated)
size_t fragment_count
Number of fragments received so far
size_t len
Current assembled length
SocketWS_Opcode type
Message type: TEXT or BINARY (from first frame opcode)
int utf8_initialized
Whether UTF-8 validation started
SocketUTF8_State utf8_state
Incremental UTF-8 decoder state
SocketWS_Handshake
struct SocketWS_Handshake
Context for WebSocket HTTP upgrade handshake.
Manages client or server handshake state, key generation/validation, header negotiation (subprotocols, compression), and HTTP parsing/serialization.
Client:
Generates Sec-WebSocket-Key, builds GET request with Upgrade: websocket
Parses server response, validates Sec-WebSocket-Accept
Server:
Parses client request, computes Accept from key
Validates required headers, negotiates extensions/subprotocols
Sends 101 Switching Protocols response
See also
SocketWS_HandshakeState for state enum.
ws_handshake_client_init() / ws_handshake_server_init() for init.
ws_handshake_client_process() / ws_handshake_server_process() for I/O loop.
SocketCrypto_websocket_accept_compute() for key validation.
RFC 6455 Section 4.2 for client handshake, Section 4.1 for server.
Definition at line 436 of file SocketWS-private.h.
Data Fields
char client_key[25]
Base64 Sec-WebSocket-Key (24 chars)
int client_max_window_bits
Client max window bits (8-15)
int client_no_context_takeover
Client no context takeover
int compression_negotiated
permessage-deflate negotiated?
char expected_accept[29]
SHA1(key + magic) base64
SocketHTTP1_Parser_T http_parser
Parser for HTTP response/request
char * request_buf
Buffer for HTTP request/response
size_t request_len
Total length of HTTP message
size_t request_sent
Bytes already sent
char * selected_subprotocol
Negotiated subprotocol (Arena alloc)
int server_max_window_bits
Server max window bits (8-15)
int server_no_context_takeover
Server no context takeover
SocketWS_HandshakeState state
Current handshake state
SocketWS
struct SocketWS
Opaque WebSocket connection context holding all protocol state.
Opaque type for WebSocket connection (public interface).
Central opaque structure managing full WebSocket connection lifecycle, from HTTP upgrade handshake through framed data exchange to graceful closure. Publicly accessed only via SocketWS_T pointer and API functions; internal fields private and unstable.
Key Responsibilities
HTTP/1.1 upgrade handshake (client/server)
Frame parsing/serialization with masking/compression
Message fragmentation/reassembly with UTF-8 validation
Control frame handling (PING/PONG/CLOSE)
Auto-keepalive via periodic PINGs
Integration with SocketPoll for non-blocking I/O
Error tracking and diagnostics
Lifecycle Management
Creation: SocketWS_client_new() or SocketWS_server_accept() allocates and inits
Handshake: SocketWS_handshake() or internal ws_handshake_*() completes upgrade
Data Exchange: SocketWS_send(), SocketWS_recv(), SocketWS_process() loop
Closure: SocketWS_close() sends CLOSE frame, awaits response
Cleanup: SocketWS_free() releases arena, buffers, timers
Resource Ownership
Field Ownership Notes
socket Transferred Caller retains? No, owned until free
arena Owned All sub-allocs freed on dispose
recv_buf/send_buf Owned Circular buffers for buffering
poll Referenced Shared event loop instance
State Subsystems
Handshake: HTTP parser, keys, negotiated extensions/subprotocols
Frame Parser: Incremental header/payload parse (SocketWS_FrameParse)
Message Assembly: Fragment collection with decompression/UTF-8 (SocketWS_MessageAssembly)
Compression: zlib streams for permessage-deflate (if enabled)
Timers: Auto-ping via SocketTimer
Error: last_error code + formatted message
Thread Safety: Not thread-safe; single-threaded use only. No internal mutexes; concurrent access may corrupt state. For multi-thread, use one ws per thread or external locking (not recommended).
Non-blocking I/O: All functions handle EAGAIN/partial; integrate with SocketPoll via SocketWS_fd() and SocketWS_process().
Thread Safety\n No - no internal synchronization; serialize all operations on ws
Note
Dynamic fields (strings, buffers) allocated from ws->arena
socket field may be NULL post-transfer to higher layers
Warning
Direct field access undefined; use getters/setters where available
Complexity\n Varies by operation; generally O(1) state access, O(payload) I/O
Example Internal Access (for library code)
// Internal: accessing state (not for users)
if (ws->state == WS_OPEN && ws->role == WS_CLIENT) {
    ws->frame.state = WS_FRAME_STATE_HEADER;
}
See also
SocketWS_T Public opaque typedef
SocketWS_new() Internal constructor
SocketWS_free() Destructor
docs/WEBSOCKET.md Detailed WebSocket guide
In public header (SocketWS.h), defined as define T SocketWS_T
typedef struct SocketWS *T; Here, reveals the pointer to private struct SocketWS. Users should use opaque T without knowledge of internal layout.
See also
SocketWS.h public header.
struct SocketWS private implementation.
Definition at line 600 of file SocketWS-private.h.
Data Fields
Arena_T arena
Memory arena for all dynamic allocations
int awaiting_pong
Expecting PONG response?
SocketWS_CloseCode close_code
Received/sent close code
char close_reason[123+1]
Close reason string
int close_received
Flag: received CLOSE frame?
int close_sent
Flag: sent CLOSE frame?
SocketWS_Config config
User-provided configuration
char error_buf[256]
Human-readable error message
SocketWS_FrameParse frame
Incoming frame parser
SocketWS_Handshake handshake
HTTP upgrade handshake context
char * host
Target host (for client handshake)
SocketWS_Error last_error
Last error code
int64_t last_ping_sent_time
Time last PING sent
int64_t last_pong_received_time
Time last PONG received
int64_t last_pong_sent_time
Time last PONG sent (response)
SocketWS_MessageAssembly message
Fragmented message assembler
char * path
Request path (for client handshake)
size_t pending_ping_len
Length of pending PING payload
unsigned char pending_ping_payload[125]
Pending PING payload
SocketTimer_T ping_timer
Internal timer for auto-pings
SocketPoll_T poll
Associated poll instance (for timers)
int port
Target port
SocketBuf_T recv_buf
Receive circular buffer for incoming data
SocketWS_Role role
Client or server role (affects masking)
SocketBuf_T send_buf
Send circular buffer for outgoing data
Socket_T socket
TCP/TLS socket (may be NULL if ownership transferred)
SocketWS_State state
High-level connection state (CONNECTING/OPEN/CLOSING/CLOSED)
int use_tls
Using TLS? (wss://)
SocketWS_Config
struct SocketWS_Config
Configuration parameters for WebSocket instances.
Passed to SocketWS_client_new() or SocketWS_server_accept(). Defaults set by SocketWS_config_defaults().
See also
SocketWS_config_defaults() to initialize.
RFC 6455 for protocol requirements on limits, etc.
Definition at line 306 of file SocketWS.h.
Data Fields
int deflate_max_window_bits
Deflate window bits (8-15, default: 15).
int deflate_no_context_takeover
No context takeover for deflate (default: 0).
int enable_permessage_deflate
Offer permessage-deflate (RFC 7692, default: 0).
size_t max_fragments
Maximum fragments per message (default: 1000).
size_t max_frame_size
Maximum single frame payload size (default: 16MB).
size_t max_message_size
Maximum reassembled message size (default: 64MB).
int ping_interval_ms
Auto-ping interval in ms (0=disabled, default: 0).
int ping_timeout_ms
Timeout for pong response in ms (default: 5000).
SocketWS_Role role
Role: client masks frames, server validates masks.
const char ** subprotocols
NULL-terminated array of supported subprotocols.
int validate_utf8
Enable UTF-8 validation for text frames (default: 1).
SocketWS_Frame
struct SocketWS_Frame
Structure representing a parsed WebSocket frame.
Filled by internal parsing; not directly filled by user APIs. Payload points to internal buffer; do not free.
See also
SocketWS-private.h for internal frame parsing details.
Definition at line 353 of file SocketWS.h.
Data Fields
int fin
1 if final fragment of message, 0 otherwise.
SocketWS_Opcode opcode
Opcode of the frame (data or control).
const unsigned char * payload
Pointer to frame payload data (unmasked).
size_t payload_len
Length of payload in bytes.
int rsv1
RSV1 bit: 1 if compressed (permessage-deflate).
SocketWS_Message
struct SocketWS_Message
Complete reassembled WebSocket message from recv_message().
Aggregates potentially fragmented data frames into single buffer. type is from first frame's opcode (TEXT or BINARY). Caller owns data; free with free() or arena equivalent when done.
See also
SocketWS_recv_message() populates this structure.
Definition at line 378 of file SocketWS.h.
Data Fields
unsigned char * data
Allocated message payload (caller frees).
size_t len
Total message length in bytes.
SocketWS_Opcode type
Message type: WS_OPCODE_TEXT or WS_OPCODE_BINARY.
SocketWS_CompressionOptions
struct SocketWS_CompressionOptions
WebSocket compression options.
Definition at line 1181 of file SocketWS.h.
Data Fields
int client_max_window_bits
Client LZ77 window (8-15, default 15)
int client_no_context_takeover
Client resets context per message
int level
zlib compression level (1-9, default 6)
int server_max_window_bits
Server LZ77 window (8-15, default 15)
int server_no_context_takeover
Server resets context per message
Macro Definition Documentation
RAISE_WS_ERROR
#define RAISE_WS_ERROR (e) SOCKET_RAISE_MODULE_ERROR (SocketWS, e)
Thread-local exception declarations for SocketWS module.
Declares module exceptions using SOCKET_DECLARE_MODULE_EXCEPTION. These are raised via TRY/EXCEPT or RAISE_WS_ERROR macro.
Public exceptions exposed in SocketWS.h:
SocketWS_Failed: General failures
SocketWS_ProtocolError: RFC violations
SocketWS_Closed: Connection closed
Internal use: RAISE_WS_ERROR for quick error raising with module context.
See also
Except.h for exception framework.
docs/ERROR_HANDLING.md for patterns.
Definition at line 702 of file SocketWS-private.h.
SOCKETWS_BASE_HEADER_SIZE
#define SOCKETWS_BASE_HEADER_SIZE 2
Frame Header Constants
Constants for WebSocket frame header format and lengths. Header: 2-14 bytes (FIN/RSV/opcode + MASK/len + ext len + mask key).
Length encoding: 7-bit direct, 126=16-bit, 127=64-bit. Control frames: max 125 byte payload, no fragmentation.
See also
SocketWS_FrameParse for parsing.
ws_frame_build_header() for serialization.
RFC 6455 Section 5.2 for detailed format. Minimum frame header size: 1 byte (FIN+RSV+opcode) + 1 byte (MASK+len)
Definition at line 147 of file SocketWS-private.h.
SOCKETWS_FIN_BIT
#define SOCKETWS_FIN_BIT 0x80
Frame Header Bit Masks
Bit masks for extracting fields from frame header bytes. First byte: FIN (7), RSV1-3 (6-4), Opcode (3-0) Second byte: MASK (7), Payload len (6-0)
Used in parsing (ws_frame_parse_header) and building (ws_frame_build_header).
See also
RFC 6455 Section 5.2 Table 2-3 for bit positions. FIN bit: indicates final fragment of message
Definition at line 183 of file SocketWS-private.h.
SOCKETWS_MAX_FRAME_SIZE
#define SOCKETWS_MAX_FRAME_SIZE (16 * 1024 * 1024)
Configuration Constants
Compile-time constants controlling WebSocket behavior, limits, and defaults. Override via CMake or preprocessor before including headers.
See also
SocketWS_Config for runtime configuration. Maximum WebSocket frame size (default 16MB)
Definition at line 56 of file SocketWS-private.h.
SOCKETWS_PROTOCOL_VERSION
#define SOCKETWS_PROTOCOL_VERSION "13"
Handshake Constants
Constants for HTTP upgrade handshake (client request, server response). Includes protocol version, header values, buffer sizes, key lengths.
See also
SocketWS_Handshake for runtime handshake state.
RFC 6455 Section 1.3 for version, Section 4 for handshake format. WebSocket protocol version per RFC 6455
Definition at line 72 of file SocketWS-private.h.
SOCKETWS_SEND_CHUNK_SIZE
#define SOCKETWS_SEND_CHUNK_SIZE 8192
Send Buffer Configuration
Runtime constants for send/recv buffering, message limits, control payloads. Defaults suitable for most use cases; override via config or defines.
Buffers sized for efficiency (64KB), chunks for partial sends. Limits prevent DoS: max frame/message, fragments, close reason.
See also
SocketBuf_T for underlying buffer impl.
SocketWS_Config for user-configurable limits. Chunk size for data frame payload sending (8KB)
Definition at line 220 of file SocketWS-private.h.
SOCKETWS_XOR_ALIGN_SIZE
#define SOCKETWS_XOR_ALIGN_SIZE 8
XOR Masking Constants
Constants for client-to-server payload masking (4-byte key XOR). Optimization: 64-bit aligned XOR loops, mask cycling.
Masking required for client frames to prevent proxy attacks. Server frames unmasked.
See also
ws_mask_payload() optimized masking function.
ws_mask_payload_offset() for incremental masking.
RFC 6455 Section 5.3 for masking rationale and algorithm. Alignment size for optimized 64-bit XOR masking
Definition at line 119 of file SocketWS-private.h.
T
#define T SocketWS_T
Definition at line 116 of file SocketWS.h.
Enumeration Type Documentation
SocketWS_CloseCode
enum SocketWS_CloseCode
Status codes for WebSocket CLOSE frames (RFC 6455 section 7.4).
Sent in CLOSE frame payload (2-byte code + optional UTF-8 reason). Codes 0-999 reserved, 1000-1015+ defined, 1016-2999 for libraries, 3000-3999 for apps, 4000+ for private.
Internal codes (1002-1006,1015) not sent on wire.
See also
SocketWS_close() to send close with code.
SocketWS_close_code() to retrieve received code.
RFC 6455 section 7.4 for full list and semantics.
Enumerator
WS_CLOSE_NORMAL
Normal closure, no error.
WS_CLOSE_GOING_AWAY
Endpoint shutting down.
WS_CLOSE_PROTOCOL_ERROR
Generic protocol violation.
WS_CLOSE_UNSUPPORTED_DATA
Received unsupported frame type.
WS_CLOSE_NO_STATUS
No status rcvd (internal use only).
WS_CLOSE_ABNORMAL
Closed without CLOSE frame.
WS_CLOSE_INVALID_PAYLOAD
Invalid UTF-8 or other payload error.
WS_CLOSE_POLICY_VIOLATION
Message violates policy.
WS_CLOSE_MESSAGE_TOO_BIG
Message exceeds size limits.
WS_CLOSE_MANDATORY_EXT
Required extension not offered.
WS_CLOSE_INTERNAL_ERROR
Server internal error.
WS_CLOSE_SERVICE_RESTART
Server restarting.
WS_CLOSE_TRY_AGAIN_LATER
Temporary server condition.
WS_CLOSE_BAD_GATEWAY
Bad gateway or tunnel error.
WS_CLOSE_TLS_HANDSHAKE
Failed TLS handshake (internal).
Definition at line 201 of file SocketWS.h.
SocketWS_Error
enum SocketWS_Error
WebSocket-specific error codes for SocketWS_last_error().
Returned by API functions; 0 indicates success.
See also
SocketWS_last_error() to retrieve after error.
SocketWS_error_string() for descriptions.
Enumerator
WS_OK
Operation succeeded.
WS_ERROR
Generic WebSocket error.
WS_ERROR_HANDSHAKE
Handshake failure (invalid response/key).
WS_ERROR_PROTOCOL
Protocol violation (bad opcode, etc.).
WS_ERROR_FRAME_TOO_LARGE
Frame size exceeds config.max_frame_size.
WS_ERROR_MESSAGE_TOO_LARGE
Reassembled message exceeds config.max_message_size.
WS_ERROR_INVALID_UTF8
Text frame contains invalid UTF-8.
WS_ERROR_COMPRESSION
permessage-deflate compression/decompression error.
WS_ERROR_CLOSED
Connection closed during operation.
WS_ERROR_WOULD_BLOCK
Non-blocking I/O would block.
WS_ERROR_TIMEOUT
Operation timed out (ping or I/O).
Definition at line 274 of file SocketWS.h.
SocketWS_FrameState
enum SocketWS_FrameState
States for the frame parsing state machine.
Tracks progress through frame header parsing, length extension, masking, and payload. Used to handle incremental frame reception in non-blocking mode.
See also
ws_frame_parse_header() for state transitions.
SocketWS_FrameParse for full parse context.
Enumerator
WS_FRAME_STATE_HEADER
Reading frame header (opcode, fin, rsv, mask, len)
WS_FRAME_STATE_EXTENDED_LEN
Reading extended payload length (16/64-bit)
WS_FRAME_STATE_MASK_KEY
Reading 4-byte mask key (client frames only)
WS_FRAME_STATE_PAYLOAD
Reading payload data
WS_FRAME_STATE_COMPLETE
Frame fully parsed
Definition at line 282 of file SocketWS-private.h.
SocketWS_HandshakeState
enum SocketWS_HandshakeState
States for WebSocket HTTP upgrade handshake.
Tracks progress of client or server handshake over HTTP/1.1. Client: INIT -> SEND_REQUEST -> READ_RESPONSE -> COMPLETE/FAILED Server: INIT -> SEND_RESPONSE -> COMPLETE/FAILED (request already parsed)
See also
SocketWS_Handshake for full handshake context.
SocketWS_handshake() public function that drives state machine.
RFC 6455 Section 4 for handshake details.
Enumerator
WS_HANDSHAKE_INIT
Initial state, prepare handshake data
WS_HANDSHAKE_SENDING_REQUEST
Client: Sending HTTP GET upgrade request
WS_HANDSHAKE_READING_RESPONSE
Client: Reading HTTP 101 response; Server: reading client request if needed
WS_HANDSHAKE_COMPLETE
Handshake successful, transition to frame mode
WS_HANDSHAKE_FAILED
Handshake failed, error set
Definition at line 400 of file SocketWS-private.h.
SocketWS_Opcode
enum SocketWS_Opcode
WebSocket frame opcodes as defined in RFC 6455 section 5.2.
Opcodes determine frame type: data (text/binary), control (close/ping/pong), or continuation for fragmented messages.
See also
SocketWS_Frame.opcode for frame parsing.
RFC 6455 for full opcode semantics and reserved values.
Enumerator
WS_OPCODE_CONTINUATION
Continuation frame for fragmented data.
WS_OPCODE_TEXT
Text data frame (UTF-8 encoded).
WS_OPCODE_BINARY
Binary data frame.
WS_OPCODE_CLOSE
Connection close control frame.
WS_OPCODE_PING
Ping control frame (keepalive).
WS_OPCODE_PONG
Pong control frame (response to ping).
Definition at line 172 of file SocketWS.h.
SocketWS_Role
enum SocketWS_Role
WebSocket endpoint roles per RFC 6455.
Clients mask outgoing frames; servers validate masks on incoming. Set in SocketWS_Config.role.
See also
SocketWS_Config.role for configuration.
RFC 6455 section 5.3 for masking requirements.
Enumerator
WS_ROLE_CLIENT
Client: must mask all outgoing data frames.
WS_ROLE_SERVER
Server: rejects unmasked incoming data frames.
Definition at line 254 of file SocketWS.h.
SocketWS_State
enum SocketWS_State
WebSocket connection lifecycle states.
Tracks progression from handshake to closure.
See also
SocketWS_state() to query current state.
SocketWS_handshake() transitions CONNECTING -> OPEN.
SocketWS_close() transitions OPEN -> CLOSING.
Enumerator
WS_STATE_CONNECTING
Handshake (HTTP upgrade) in progress.
WS_STATE_OPEN
Connection established, ready for read/write.
WS_STATE_CLOSING
Close frame sent/received, awaiting ack.
WS_STATE_CLOSED
Connection terminated, resources freed on free().
Definition at line 236 of file SocketWS.h.
Function Documentation
SocketWS_client_new()
SocketWS_T SocketWS_client_new (Socket_T socket, const char * host, const char * path, const SocketWS_Config * config) extern
Create a new client WebSocket instance from a connected TCP socket.
Parameters
[in] socket Connected TCP socket (transferred to WebSocket; do not close externally).
[in] host Value for the Host header in upgrade request (required).
[in] path Resource path for the WebSocket endpoint (e.g., "/chat", defaults to "/").
[in] config Optional SocketWS_Config; NULL applies defaults via SocketWS_config_defaults().
The returned instance starts in WS_STATE_CONNECTING. Call SocketWS_handshake() to send the HTTP/1.1 Upgrade request and receive the server's response.
Supports both blocking and non-blocking sockets, but non-blocking is recommended for production to avoid head-of-line blocking during handshake.
Returns
New SocketWS_T instance, or NULL on failure (except frame raised).
Exceptions
SocketWS_Failed on invalid parameters, allocation failure, or socket issues.
Thread Safety\n Yes - creates independent instance.
Client Usage Example
  SocketWS_Config config;
  SocketWS_config_defaults(&config);
  // Optional customizations
  config.subprotocols = (const char*[]){"chat", NULL};
  config.ping_interval_ms = 30000;  // Auto-ping every 30s
  config.validate_utf8 = 1;          // Enable UTF-8 checks
  TRY {
    Socket_T sock = Socket_new(AF_INET, SOCK_STREAM, 0);
    Socket_connect(sock, "example.com", 443);  // Port 80 or 443 for wss
    // For secure WebSocket (wss://):
    // SocketTLSContext_T ctx = SocketTLSContext_new(...);
    // SocketTLS_enable(sock, ctx);
    // SocketTLS_set_hostname(sock, "example.com");
    // SocketTLS_handshake_auto(sock);
    Socket_setnonblocking(sock);  // Recommended for production
    SocketWS_T ws = SocketWS_client_new(sock, "example.com", "/ws/chat",
&config);
    if (ws == NULL) RAISE(SocketWS_Failed);
    // Non-blocking handshake loop
    int status;
    do {
      status = SocketWS_handshake(ws);
      if (status < 0) break;  // Error
      if (status == 0) break; // Success
      // Poll SocketWS_pollfd(ws) for SocketWS_poll_events(ws)
      // Then SocketWS_process(ws, events)
    } while (1);
    if (SocketWS_state(ws) == WS_STATE_OPEN) {
      // Send text message
      SocketWS_send_text(ws, "{\"msg\":\"Hello WebSocket\"}", 22);
      // Receive messages via SocketWS_recv_message() or event loop
    }
    SocketWS_free(&ws);
  } EXCEPT (SocketWS_Failed | SocketWS_ProtocolError) {
    SOCKET_LOG_ERROR_MSG("Client WebSocket error: %s",
SocketWS_error_string(SocketWS_last_error(ws)));
  } END_TRY;
Note
Socket ownership transfers to ws; close via SocketWS_free().
For wss://, complete TLS handshake before creating ws.
Use SocketWS_enable_auto_ping(ws, poll) after open for keepalive.
Complexity\n O(1) - constant time allocation and initialization
See also
SocketWS_config_defaults() for configuration.
SocketWS_handshake() to complete upgrade.
SocketWS_process() for event-driven I/O.
SocketWS_server_accept() for server equivalent.
SocketHTTP_Request for HTTP upgrade details.
docs/WEBSOCKET.md for full guide.
Referenced by main().
SocketWS_close()
int SocketWS_close (SocketWS_T ws, int code, const char * reason) extern
Initiate graceful WebSocket close handshake.
Parameters
[in] ws SocketWS_T instance in OPEN or CLOSING state.
[in] code Close status code (WS_CLOSE_NORMAL=1000 for no error, see SocketWS_CloseCode).
[in] reason Optional UTF-8 encoded reason string (max 123 bytes after code, may be NULL).
Sends CLOSE frame with code and reason to peer. Transitions state to WS_STATE_CLOSING, awaits peer CLOSE response. On completion or timeout, connection closes. If already closing, updates code/reason if not sent yet.
Returns
0 on success (frame queued), -1 on error.
Exceptions
SocketWS_Closed if already fully closed.
SocketWS_Failed on allocation or queue error.
SocketWS_ProtocolError on invalid code or reason length/UTF-8.
Thread Safety\n No - modifies state and send queue.
See also
SocketWS_state() to check transition to CLOSING.
SocketWS_close_code() and SocketWS_close_reason() for peer's close info.
SocketWS_free() which calls this if open.
RFC 6455 section 7.1-7.4 for close handshake details.
Referenced by main(), and request_handler().
SocketWS_close_code()
int SocketWS_close_code (SocketWS_T ws) extern
Get close code from close frame.
Parameters
[in] ws WebSocket instance.
Returns
Close code, or -1 if not closed or no close frame received.
Thread Safety\n No - reads internal state.
See also
SocketWS_close_reason() for close reason text.
Referenced by main(), and process_websocket_clients().
SocketWS_close_reason()
const char * SocketWS_close_reason (SocketWS_T ws) extern
Get close reason text from close frame.
Parameters
[in] ws WebSocket instance.
Returns
Close reason text, or NULL if not available.
Note
String is valid until WebSocket is freed.
Thread Safety\n No - reads internal state.
See also
SocketWS_close_code() for close code.
Referenced by main().
SocketWS_compression_enabled()
int SocketWS_compression_enabled (SocketWS_T ws) extern
Check if compression is enabled.
Parameters
[in] ws WebSocket instance.
Returns
1 if permessage-deflate enabled, 0 otherwise.
Thread Safety\n No - reads internal state.
See also
SocketWS_Config for compression configuration.
Referenced by main().
SocketWS_compression_options_defaults()
void SocketWS_compression_options_defaults (SocketWS_CompressionOptions * options) extern
Initialize compression options with defaults.
Parameters
[out] options Options structure to initialize
SocketWS_config_defaults()
void SocketWS_config_defaults (SocketWS_Config * config) extern
Initialize WebSocket configuration with default values.
Parameters
config [out] Pointer to the configuration structure to initialize.
Sets reasonable defaults such as 16MB max frame size, UTF-8 validation enabled, compression disabled, and ping interval disabled.
Returns
void
Thread Safety\n Yes - pure function with no side effects.
See also
SocketWS_client_new() for creating client WebSockets.
SocketWS_server_accept() for accepting server WebSockets.
SocketWS_Config for individual field descriptions and customization.
Referenced by main().
SocketWS_connect()
SocketWS_T SocketWS_connect (const char * url, const char * protocols) extern
One-liner WebSocket client connection.
Parameters
[in] url WebSocket URL (ws:// or wss://)
[in] protocols Optional comma-separated subprotocols (may be NULL)
Parses URL, creates socket, performs TLS handshake if wss://, creates WebSocket, and completes the opening handshake. Returns fully connected WebSocket in OPEN state.
Returns
WebSocket in OPEN state, or NULL on error
Exceptions
SocketWS_Failed on connection or handshake failure
Thread Safety\n No
URL Format
ws://host[:port][/path]     - Unencrypted WebSocket
wss://host[:port][/path]    - TLS-encrypted WebSocket
Example
// Simple connection
SocketWS_T ws = SocketWS_connect("wss://echo.websocket.org", NULL);
if (ws) {
    SocketWS_send_text(ws, "Hello!", 6);
    // ... receive ...
    SocketWS_close(ws, WS_CLOSE_NORMAL, NULL);
    SocketWS_free(&ws);
}
// With subprotocol
SocketWS_T ws = SocketWS_connect("ws://api.example.com/ws", "graphql-ws");
Note
For more control, use Socket_new + Socket_connect + SocketWS_client_new
See also
SocketWS_client_new() for manual connection setup
SocketWS_free() for cleanup
SocketWS_disable_auto_ping()
void SocketWS_disable_auto_ping (SocketWS_T ws) extern
Disable and cancel automatic PING keepalive timer.
Parameters
[in] ws SocketWS_T instance.
Removes any installed ping timer from associated poll. Stops sending periodic PINGs and pong monitoring. Does not affect manual ping/pong or current state. Idempotent if not enabled.
Returns
void
Thread Safety\n No - modifies timer state.
See also
SocketWS_enable_auto_ping() to enable.
SocketWS_enable_auto_ping()
int SocketWS_enable_auto_ping (SocketWS_T ws, SocketPoll_T poll) extern
Enable automatic periodic PING for connection keepalive.
Parameters
ws SocketWS_T instance in OPEN state.
[in] poll SocketPoll_T instance for timer callback integration.
Installs repeating timer to send PING every SocketWS_Config.ping_interval_ms. Monitors for timely PONG response within ping_timeout_ms. Closes connection on missed pongs (after retries). Timer events processed via SocketWS_process() on poll. Idempotent: already enabled does nothing.
Requires event loop with provided poll instance.
Returns
0 on success (timer installed), -1 on failure.
Exceptions
SocketWS_Failed on timer or poll error.
SocketWS_Closed if not open.
Thread Safety\n No - installs shared timer.
See also
SocketWS_Config::ping_interval_ms for configuration.
SocketWS_disable_auto_ping() to disable.
SocketWS_process() must be called regularly for pong checks.
SocketTimer for timer details.
SocketWS_enable_compression()
int SocketWS_enable_compression (SocketWS_T ws, const SocketWS_CompressionOptions * options) extern
Enable permessage-deflate compression.
Parameters
[in] ws WebSocket instance (before handshake)
[in] options Compression options (NULL for defaults)
Enables RFC 7692 permessage-deflate compression for this WebSocket. Must be called before the handshake completes. The server may negotiate different parameters.
Returns
0 on success, -1 if compression not supported or already connected
Thread Safety\n No
Example
SocketWS_T ws = SocketWS_client_new(sock, host, path, &config);
// Enable compression before handshake
SocketWS_CompressionOptions opts;
SocketWS_compression_options_defaults(&opts);
opts.level = 9;  // Maximum compression
SocketWS_enable_compression(ws, &opts);
// Now complete handshake
SocketWS_handshake(ws);
Note
Requires zlib; returns -1 if compiled without SOCKETWS_HAS_DEFLATE
See also
SocketWS_compression_enabled() to check if active
SocketWS_Config.enable_compression for config-based setup
SocketWS_error_string()
const char * SocketWS_error_string (SocketWS_Error error) extern
Get a human-readable string describing a WebSocket error code.
Parameters
[in] error SocketWS_Error value to describe.
Returns pointer to static string (do not free or modify). Covers all defined SocketWS_Error values.
Returns
Const char* to error description, never NULL.
Thread Safety\n Yes - returns static immutable strings.
See also
SocketWS_last_error() to get code after failed operation.
SocketWS_Error enum for error codes.
Referenced by main().
SocketWS_free()
void SocketWS_free (SocketWS_T * ws) extern
Dispose of a WebSocket instance, closing connection if open.
Parameters
ws [in,out] Pointer to SocketWS_T; set to NULL after disposal.
Performs graceful close if in OPEN or CLOSING state (sends CLOSE frame if needed). Releases all resources including underlying socket, buffers, compression context, and timers. Arena-allocated memory returned to owning arena.
Safe to call on already-freed or NULL pointers.
Returns
void
Exceptions
None - errors during close logged but not raised.
Thread Safety\n No - instance-specific resources.
See also
SocketWS_close() for explicit close before free.
SocketWS_client_new(), SocketWS_server_accept() for creation.
Referenced by main(), process_websocket_clients(), and request_handler().
SocketWS_get_ping_latency()
int64_t SocketWS_get_ping_latency (SocketWS_T ws) extern
Get ping/pong round-trip time.
Parameters
[in] ws WebSocket instance
Returns the latency (RTT) of the most recent completed PING/PONG cycle. If no ping has been sent or pong not yet received, returns -1.
Returns
RTT in milliseconds (>= 0), or -1 if no data available
Thread Safety\n No - reads internal timestamps
Example
// Send ping and wait for pong
SocketWS_ping(ws, "test", 4);
// ... process events until pong received ...
int64_t rtt = SocketWS_get_ping_latency(ws);
if (rtt >= 0) {
    printf("Latency: %lld ms\n", (long long)rtt);
}
See also
SocketWS_ping() to send PING
SocketWS_enable_auto_ping() for automatic keepalive
SocketWS_handshake()
int SocketWS_handshake (SocketWS_T ws) extern
Perform or continue the WebSocket handshake process.
Parameters
[in] ws SocketWS_T instance in CONNECTING state.
Client mode: Sends HTTP Upgrade request with Sec-WebSocket-Key and extensions, reads response, validates 101 status, Sec-WebSocket-Accept, subprotocols, extensions.
Server mode: Sends HTTP 101 response with computed Sec-WebSocket-Accept, negotiated parameters. Validates client key if not pre-validated.
Non-blocking compatible: returns 1 if more I/O needed (poll and call again). Blocks if socket is blocking.
On success, transitions to WS_STATE_OPEN.
Returns
0 on complete success (now OPEN), 1 if pending (call again after poll), -1 on error (check SocketWS_last_error()).
Exceptions
SocketWS_ProtocolError on invalid handshake response/request.
SocketWS_Failed on I/O or allocation errors.
Thread Safety\n No - modifies instance state.
See also
SocketWS_state() to check current state post-call.
SocketWS_process() for ongoing I/O after handshake.
Socket_geterrorcode() for underlying socket errors.
Referenced by main(), and request_handler().
SocketWS_is_upgrade()
int SocketWS_is_upgrade (const SocketHTTP_Request * request) extern
Check if an HTTP request is a valid WebSocket upgrade request.
Parameters
[in] request Pointer to parsed SocketHTTP_Request from HTTP/1.1 parser.
Validates presence of required headers: Upgrade: websocket, Connection: Upgrade, Sec-WebSocket-Key, Sec-WebSocket-Version: 13. Optionally checks Sec-WebSocket-Protocol against configured subprotocols.
Returns
1 if valid WebSocket upgrade, 0 if not (missing/invalid headers).
Thread Safety\n Yes - pure function, reads const request.
See also
SocketWS_server_accept() to accept the upgrade.
SocketWS_server_reject() to reject with error response.
SocketHTTP_Request for HTTP request structure.
SocketWS_last_error()
SocketWS_Error SocketWS_last_error (SocketWS_T ws) extern
Retrieve the most recent error code for this WebSocket instance.
Parameters
[in] ws SocketWS_T instance.
Provides detailed error from last failed API call on this instance. Returns WS_OK (0) if no error pending. Errors persist until next operation or explicit clear (if any).
Returns
SocketWS_Error code from last operation.
Thread Safety\n Conditional - safe if errors not set concurrently.
See also
SocketWS_error_string() for textual description.
SocketWS_Error enum for possible values.
SocketWS_clear_error() if implemented for reset.
Referenced by main().
SocketWS_ping()
int SocketWS_ping (SocketWS_T ws, const void * data, size_t len) extern
Send a PING control frame for keepalive or to solicit immediate response from peer.
Parameters
[in] ws SocketWS_T instance in OPEN or CONNECTING state.
[in] data Optional application-defined data payload (0-125 bytes, may be NULL).
[in] len Length of data in bytes (must be <=125).
Triggers peer to send PONG with same payload if provided. Queues frame; call SocketWS_process() to send. Used for keepalive or latency checks.
Returns
0 on success (queued for send), -1 on error.
Exceptions
SocketWS_Closed if connection is closed.
SocketWS_Failed on invalid parameters or internal error.
SocketWS_ProtocolError if len > 125.
Thread Safety\n No - modifies send queue.
See also
SocketWS_pong() to send PONG.
SocketWS_enable_auto_ping() for automatic pings.
SocketWS_process() to flush queued frames.
RFC 6455 section 5.5.2 for PING frame details.
Referenced by main().
SocketWS_poll_events()
unsigned SocketWS_poll_events (SocketWS_T ws) extern
Determine required poll events for the WebSocket socket.
Parameters
[in] ws SocketWS_T instance.
Returns bitmask indicating needed events: always POLL_READ for incoming data/handshake/close. POLL_WRITE if send queue has data to flush. Use with SocketPoll_mod() to update registration dynamically.
Returns
Event bitmask (POLL_READ | POLL_WRITE | 0).
Thread Safety\n Conditional - queue state may change.
See also
SocketWS_pollfd() for FD.
SocketWS_process() to handle triggered events.
SocketPoll_Events for bit definitions.
SocketWS_pollfd()
int SocketWS_pollfd (SocketWS_T ws) extern
Get the underlying socket file descriptor for use with poll/epoll/kqueue.
Parameters
[in] ws SocketWS_T instance.
Returns the FD of SocketWS_socket(ws) for registration in external event loops. Use with SocketPoll_add() or native poll APIs. Do not close or modify the FD directly.
Returns
Valid file descriptor (>=0), or -1 if invalid/closed.
Thread Safety\n Yes - simple FD read, but concurrent close possible.
See also
SocketWS_socket() for full Socket_T access.
SocketWS_poll_events() for required events.
Event System Modules for event system integration.
SocketPoll_T::add for example usage.
SocketWS_pong()
int SocketWS_pong (SocketWS_T ws, const void * data, size_t len) extern
Send a PONG control frame, typically in response to PING.
Parameters
[in] ws SocketWS_T instance in OPEN or CONNECTING state.
[in] data Optional payload to echo back (0-125 bytes, may be NULL).
[in] len Length of data in bytes (must be <=125).
Can be sent unsolicited, but usually auto-generated in response to PING. Queues frame for sending.
Returns
0 on success (queued), -1 on error.
Exceptions
SocketWS_Closed if closed.
SocketWS_Failed on invalid params or queue error.
SocketWS_ProtocolError if len > 125.
Thread Safety\n No - modifies send queue.
See also
SocketWS_ping() for sending PING.
RFC 6455 section 5.5.3 for PONG details.
SocketWS_process()
int SocketWS_process (SocketWS_T ws, unsigned events) extern
Process socket events to advance WebSocket state machine.
Parameters
[in] ws SocketWS_T instance.
[in] events Bitmask of occurred events from poller (POLL_READ, POLL_WRITE, POLL_ERROR, etc.).
On POLL_READ: reads and parses incoming frames, handles controls, reassembles messages. On POLL_WRITE: flushes queued send data/frames. On POLL_ERROR/POLL_HANGUP: handles errors, may close connection. Advances handshake if applicable. Integrates with auto-ping timers if enabled.
Call repeatedly in event loop after poller signals readiness.
Returns
0 on success, -1 on error (updates last_error).
Exceptions
SocketWS_ProtocolError on malformed frames.
SocketWS_Failed on I/O failures.
SocketWS_Closed on connection closure detected.
Thread Safety\n No - performs I/O and state changes.
See also
SocketWS_pollfd() and SocketWS_poll_events() for event setup.
SocketWS_recv_available() after process for new messages.
SocketPoll_T for full event loop example.
Referenced by main().
SocketWS_recv_available()
int SocketWS_recv_available (SocketWS_T ws) extern
Check for complete messages ready to receive without blocking.
Parameters
[in] ws SocketWS_T instance.
Useful for non-blocking event loops: poll until >0, then recv_message(). Returns count of fully reassembled messages in internal queue. Handles control frames internally but doesn't return them.
Returns
>=0 number of messages available, -1 on error (check last_error).
Thread Safety\n Conditional - safe if no concurrent recv/process.
See also
SocketWS_recv_message() to consume messages.
SocketWS_process() to advance parsing after poll events.
SocketWS_last_error() for error details.
Referenced by main(), and process_websocket_clients().
SocketWS_recv_json()
SocketWS_Error SocketWS_recv_json (SocketWS_T ws, char ** json_out, size_t * json_len) extern
Receive and return JSON string.
Parameters
[in] ws WebSocket instance in OPEN state
[out] json_out Output: received JSON string (caller must free)
[out] json_len Output: length of JSON string
Receives a complete text message and returns it as a JSON string. Only accepts TEXT frames; returns error for BINARY.
Returns
WS_OK on success, error code on failure
Exceptions
SocketWS_Closed if connection closes
SocketWS_Failed on receive error
Thread Safety\n No
Example
char *json = NULL;
size_t len;
if (SocketWS_recv_json(ws, &json, &len) == WS_OK) {
    printf("Received: %s\n", json);
    // Parse with your JSON library
    free(json);
}
Note
Caller must free(json_out) on success
See also
SocketWS_recv_message() for full message control
SocketWS_send_json() for sending JSON
SocketWS_recv_message()
int SocketWS_recv_message (SocketWS_T ws, SocketWS_Message * msg) extern
Receive and reassemble a complete WebSocket message.
Parameters
[in] ws SocketWS_T in OPEN state.
msg [out] SocketWS_Message to populate with received data.
Handles control frames automatically (pings ponged, closes processed). Reassembles fragmented messages up to max_message_size. Validates UTF-8 for text messages if enabled. Decompresses if negotiated. Blocks until complete message or close/error. For non-blocking: use SocketWS_process() + SocketWS_recv_available().
Caller must free(msg->data) after use.
Returns
1 on success (msg populated), 0 on clean close, -1 on error.
Exceptions
SocketWS_Closed on peer close.
SocketWS_ProtocolError on invalid frames.
SocketWS_Invalid_UTF8 on text validation failure.
Thread Safety\n No - modifies recv state and msg.
See also
SocketWS_Message for structure details.
SocketWS_recv_available() for non-blocking check.
Referenced by main(), and process_websocket_clients().
SocketWS_selected_subprotocol()
const char * SocketWS_selected_subprotocol (SocketWS_T ws) extern
Get the negotiated WebSocket subprotocol.
Parameters
[in] ws SocketWS_T instance (must be post-handshake).
Returns the subprotocol selected from client's Sec-WebSocket-Protocol header matching one in server's config.subprotocols (server) or vice versa (client). NULL if none negotiated.
String is owned by WebSocket, valid until free or re-handshake.
Returns
Const char* to subprotocol name, or NULL.
Thread Safety\n No - reads internal state.
See also
SocketWS_Config.subprotocols for configuration.
RFC 6455 section 1.9 for subprotocol negotiation.
Referenced by main().
SocketWS_send_binary()
int SocketWS_send_binary (SocketWS_T ws, const void * data, size_t len) extern
Send a binary message over the WebSocket (opcode BINARY).
Parameters
[in] ws SocketWS_T in OPEN state.
[in] data Pointer to arbitrary binary data.
[in] len Length of data in bytes.
No UTF-8 validation (binary). Applies masking/compression/fragmentation same as text. Queues for sending.
Returns
0 on success (queued), -1 on error.
Exceptions
SocketWS_Closed if not open.
SocketWS_Failed on queue or state issues.
Thread Safety\n No.
See also
SocketWS_send_text() for text (with UTF-8 validation).
SocketWS_Config.max_frame_size for fragmentation threshold.
Referenced by main(), and process_websocket_clients().
SocketWS_send_json()
int SocketWS_send_json (SocketWS_T ws, const char * json) extern
Send JSON as text frame.
Parameters
[in] ws WebSocket instance in OPEN state
[in] json JSON string to send (must be valid UTF-8)
Convenience wrapper around SocketWS_send_text() that sends JSON data. Validates UTF-8 if config.validate_utf8 is enabled.
Returns
0 on success, -1 on error
Exceptions
SocketWS_Closed if not open
SocketWS_Invalid_UTF8 if validation fails
Thread Safety\n No
Example
const char *msg = "{\"type\": \"ping\", \"id\": 123}";
SocketWS_send_json(ws, msg);
See also
SocketWS_send_text() for raw text sending
SocketWS_recv_json() for receiving JSON
SocketWS_send_text()
int SocketWS_send_text (SocketWS_T ws, const char * data, size_t len) extern
Send a text message over the WebSocket (opcode TEXT).
Parameters
[in] ws SocketWS_T in OPEN state.
[in] data Pointer to UTF-8 encoded text.
[in] len Length of data in bytes (may include embedded NUL).
Validates UTF-8 if config.validate_utf8 enabled (raises on invalid). Applies masking (client) or not (server). Compresses if enabled and negotiated. Fragments if exceeds max_frame_size, using continuation frames. Queues for sending; call SocketWS_process() or poll to flush.
Returns
0 on success (queued), -1 on error (check last_error).
Exceptions
SocketWS_Closed if not open.
SocketWS_Invalid_UTF8 if validation fails.
SocketWS_Failed on queue full or other issues.
Thread Safety\n No - modifies send buffer/state.
See also
SocketWS_send_binary() for binary data.
SocketWS_Config.validate_utf8 for control.
Referenced by main(), and process_websocket_clients().
SocketWS_server_accept()
SocketWS_T SocketWS_server_accept (Socket_T socket, const SocketHTTP_Request * request, const SocketWS_Config * config) extern
Accept a WebSocket upgrade from a parsed HTTP request on a server socket.
Parameters
[in] socket Accepted TCP socket from Socket_accept() (transferred ownership).
[in] request Parsed SocketHTTP_Request confirming WebSocket upgrade via SocketWS_is_upgrade().
[in] config Optional SocketWS_Config; NULL uses defaults.
Validates request, computes Sec-WebSocket-Accept key, prepares 101 Switching Protocols response with negotiated subprotocol and extensions. Instance starts in WS_STATE_CONNECTING. Call SocketWS_handshake() to send response and transition to OPEN.
Returns
New SocketWS_T instance, or NULL on failure.
Exceptions
SocketWS_Failed on validation failure, allocation error, or invalid request.
SocketWS_ProtocolError if request headers invalid for WebSocket.
Thread Safety\n Yes - creates independent instance.
See also
SocketWS_is_upgrade() to validate request first.
SocketWS_handshake() to send the acceptance response.
SocketWS_server_reject() for rejection cases.
SocketHTTP_Response for response structure used internally.
SocketWS_server_reject()
void SocketWS_server_reject (Socket_T socket, int status_code, const char * reason) extern
Reject a WebSocket upgrade request with an HTTP error response.
Parameters
[in] socket TCP socket from accepted connection.
[in] status_code HTTP status code (e.g., 400 Bad Request, 403 Forbidden).
[in] reason Optional human-readable reason phrase for the response body.
Sends HTTP response with given status and reason in body (if provided). Closes the socket after sending. Use before SocketWS_server_accept() if upgrade invalid.
Returns
void
Exceptions
Socket_Failed if send fails (e.g., socket closed).
Thread Safety\n Conditional - socket must not be in use by other threads.
See also
SocketWS_is_upgrade() to check validity before accepting/rejecting.
SocketHTTPServer for full HTTP server handling including upgrades.
SocketWS_socket()
Socket_T SocketWS_socket (SocketWS_T ws) extern
Access the underlying TCP socket for the WebSocket.
Parameters
[in] ws SocketWS_T instance.
Allows integration with external pollers or custom I/O handling. Do NOT close or modify the socket directly; use WebSocket APIs for lifecycle.
Returns
Borrowed reference to Socket_T; valid until SocketWS_free().
Thread Safety\n No - concurrent access may race with internal I/O.
See also
SocketWS_pollfd() for poll integration.
SocketWS_process() for processing events on this socket.
Socket_T for socket operations (use cautiously).
Referenced by main().
SocketWS_state()
SocketWS_State SocketWS_state (SocketWS_T ws) extern
Retrieve the current state of the WebSocket connection.
Parameters
[in] ws SocketWS_T instance.
Possible states: WS_STATE_CONNECTING (handshake), WS_STATE_OPEN (ready), WS_STATE_CLOSING (closing handshake), WS_STATE_CLOSED (terminated).
Returns
SocketWS_State enum value.
Thread Safety\n Yes - atomic read of state variable.
See also
SocketWS_State enum for state details.
SocketWS_handshake() which transitions from CONNECTING to OPEN.
SocketWS_close() which initiates CLOSING.
Referenced by main(), process_websocket_clients(), and request_handler().
ws_auto_ping_callback()
void ws_auto_ping_callback (void * userdata)
Timer callback invoked to send periodic PING.
Parameters
userdata The WebSocket context (cast from void*).
Note
Sends PING with empty payload or config payload.
Sets awaiting_pong and timeout check.
Reschedules next timer.
See also
SocketTimerCallback typedef.
ws_send_ping() for sending.
ws_auto_ping_start()
int ws_auto_ping_start (SocketWS_T ws, SocketPoll_T poll)
Starts the automatic PING timer for keepalive.
Parameters
ws The WebSocket context with config.ping_interval_ms.
poll The SocketPoll instance for timer integration.
Returns
0 on success, -1 on error (timer add fail).
Note
Schedules first ping after interval_ms from now.
Uses SocketTimer_add_repeating for periodic pings.
See also
ws_auto_ping_callback() timer handler.
SocketTimer_T for timer management.
ws_auto_ping_stop()
void ws_auto_ping_stop (SocketWS_T ws)
Stops the automatic PING timer.
Parameters
ws The WebSocket context.
Note
Cancels the repeating timer using SocketTimer_cancel.
Called on close or disable.
See also
ws_auto_ping_start() to start.
SocketTimer_cancel() underlying call.
ws_copy_string()
char * ws_copy_string (Arena_T arena, const char * str)
Arena-allocated duplicate of input string.
Internal Memory Helpers
Utility functions for arena-based string duplication. All allocations use provided Arena_T for lifecycle management.
See also
Arena.h for memory allocation framework.
Provides safe string duplication using the library's arena allocator. Handles NULL input gracefully. Used internally for handshake headers, subprotocols, and other string handling. Preserves null-termination.
Edge cases:
NULL str returns NULL without error.
Empty string "" allocates single null byte.
Allocation failure raises Arena_Failed exception.
Parameters
[in] arena Memory arena for allocation (must be valid).
[in] str Input C string to duplicate (may be NULL).
Returns
Pointer to arena-allocated copy of str, or NULL if str is NULL. Caller should not free(); managed by arena lifecycle.
Exceptions
Arena_Failed If Arena_alloc() fails due to insufficient space.
Thread Safety\n Yes - atomic if arena is thread-local or externally locked.
Concurrent calls safe if arena mutexed.
Basic Usage
Arena_T arena = Arena_new();
char *dup = ws_copy_string(arena, "ws://example.com/path");
assert(strcmp(dup, "ws://example.com/path") == 0);
// dup valid until Arena_clear/dispose
Arena_dispose(&arena);
With Exception Handling
char *header_value;
TRY {
    header_value = ws_copy_string(arena, http_header);
} EXCEPT(Arena_Failed) {
    SOCKET_LOG_ERROR_MSG("Failed to duplicate header: %s", http_header);
    return -1;
} END_TRY;
Note
Equivalent to socket_util_arena_strdup(arena, str) but internal.
Does not perform UTF-8 validation; assumes valid C string.
Warning
Arena must outlive all allocated strings.
Complexity\n O(n) time where n = strlen(str); single allocation.
Complexity\n O(n) space for duplicated string.
See also
socket_util_arena_strdup() Public equivalent in Utilities.
Arena_alloc() Underlying allocation mechanism.
Arena_dispose() For freeing allocated strings.
ws_fill_recv_buffer()
ssize_t ws_fill_recv_buffer (SocketWS_T ws)
Fills the receive buffer from the underlying socket.
Parameters
ws The WebSocket context.
Returns
Bytes received (>0), 0 on EOF or would block, -1 on error.
Note
Uses Socket_recv() or TLS recv.
Fills until buffer full or block/EOF.
Handles partial reads for non-blocking.
See also
SocketBuf_T recv_buf.
Socket_recv() low-level recv.
ws_flush_send_buffer()
ssize_t ws_flush_send_buffer (SocketWS_T ws)
Flushes pending data from send buffer to underlying socket.
Parameters
ws The WebSocket context.
Returns
Number of bytes sent (>0), 0 if would block (EAGAIN), -1 on error.
Note
Uses Socket_send() or TLS send if enabled.
Continues until buffer empty or block.
See also
SocketBuf_T for buffer management.
Socket_send() low-level send.
ws_frame_build_header()
size_t ws_frame_build_header (unsigned char * header, int fin, SocketWS_Opcode opcode, int masked, const unsigned char * mask_key, uint64_t payload_len)
Builds the binary WebSocket frame header into output buffer.
Parameters
header Output buffer for header bytes (must hold at least SOCKETWS_MAX_HEADER_SIZE).
fin Non-zero if final fragment (sets FIN bit).
opcode The frame opcode.
masked Non-zero if payload is masked (client frames).
mask_key 4-byte mask key if masked, ignored otherwise.
payload_len The payload length (encodes as 7/16/64-bit).
Returns
Number of bytes written to header (2-14), or 0 on error (invalid params).
Note
Validates opcode and length; does not include payload or mask application.
See also
ws_mask_payload() to mask payload after header.
RFC 6455 Section 5.2 for header encoding details.
ws_frame_parse_header()
SocketWS_Error ws_frame_parse_header (SocketWS_FrameParse * frame, const unsigned char * data, size_t len, size_t * consumed)
Incrementally parses WebSocket frame header from input data.
Parameters
frame The frame parse state structure.
data Buffer containing incoming frame bytes.
len Length of data buffer.
[out] consumed Number of bytes consumed from data (updated on call).
Returns
SocketWS_Error: WS_OK if header fully parsed, WS_NEED_MORE_DATA if incomplete, or error code (e.g., WS_PROTOCOL_ERROR for invalid header).
Note
Advances frame->state based on bytes parsed.
Handles variable header length (2-14 bytes).
See also
ws_frame_reset() before first call.
RFC 6455 Section 5.2 for frame header format.
ws_frame_reset()
void ws_frame_reset (SocketWS_FrameParse * frame)
Reset frame parser to initial state for new incoming frame.
Prepares SocketWS_FrameParse for parsing a new WebSocket frame header. Clears accumulated header bytes, resets state to HEADER, zeros parsed fields (fin, rsv, opcode, masked, mask_key, payload_len, payload_received), resets header_len and header_needed. Essential for incremental parsing in loops.
Usage pattern: Call after successful frame parse or to recover from partial/error. Does not allocate/deallocate; safe to call frequently.
Parameters
[in,out] frame Pointer to frame parse structure (fields reset)
Returns
void
Exceptions
None
Thread Safety\n Yes - self-contained, no shared state if frame local
Initialization and Reset
// Initial setup
SocketWS_FrameParse frame;
memset(&frame, 0, sizeof(frame));  // Or use ws_frame_reset(&frame);
// In receive loop
size_t consumed;
SocketWS_Error err = ws_frame_parse_header(&frame, recv_data, recv_len,
&consumed); if (err == WS_OK) {
    // Header parsed, now read payload
    // ... process payload ...
    ws_frame_reset(&frame);  // Ready for next
} else if (err == WS_PROTOCOL_ERROR) {
    ws_frame_reset(&frame);  // Recover
}
Note
Can be used interchangeably with memset(&frame, 0, sizeof(frame))
Warning
Ensure frame struct is properly aligned for header_buf
Complexity\n O(1) - fixed field assignments and memset if used
See also
ws_frame_parse_header() Next step after reset
SocketWS_FrameParse Full structure documentation
ws_message_reset() Analogous for message reassembly
ws_handle_control_frame()
int ws_handle_control_frame (SocketWS_T ws, SocketWS_Opcode opcode, const unsigned char * payload, size_t len)
Handles a received WebSocket control frame (CLOSE, PING, PONG).
Parameters
ws The WebSocket context.
opcode The control opcode received.
payload The unmasked payload data.
len The payload length.
Returns
0 on success, -1 on error (e.g., invalid close code).
Note
For PING: sends PONG response, clears timeout.
For CLOSE: sets close_received, may initiate response.
For PONG: updates last_pong_received_time.
See also
ws_send_pong() for PING response.
ws_send_close() for CLOSE response.
RFC 6455 Section 5.5 for control frame processing.
ws_handshake_client_init()
int ws_handshake_client_init (SocketWS_T ws)
Initializes the client-side WebSocket handshake.
Parameters
ws The WebSocket context.
Returns
0 on success, -1 on error (sets last_error).
Note
Generates random Sec-WebSocket-Key and constructs HTTP GET upgrade request.
Sets handshake.state to WS_HANDSHAKE_SENDING_REQUEST.
See also
ws_handshake_client_process() to send request and read response.
SocketCrypto for key generation.
RFC 6455 Section 4.1 for client handshake.
ws_handshake_client_process()
int ws_handshake_client_process (SocketWS_T ws)
Processes client handshake I/O in non-blocking manner.
Parameters
ws The WebSocket context.
Returns
0 if handshake complete (state=COMPLETE), 1 if in progress (need more I/O), -1 on error (sets last_error, state=FAILED).
Note
Handles sending request and receiving response incrementally.
Validates Sec-WebSocket-Accept header.
See also
ws_handshake_client_init() to start.
ws_handshake_validate_accept() for validation.
RFC 6455 Section 1.3 for opening handshake.
ws_handshake_server_init()
int ws_handshake_server_init (SocketWS_T ws, const SocketHTTP_Request * request)
Initializes the server-side WebSocket handshake from HTTP request.
Parameters
ws The WebSocket context.
request The parsed SocketHTTP_Request from client upgrade.
Returns
0 on success, -1 on error (invalid request, sets last_error).
Note
Validates required headers (Upgrade, Connection, Sec-WebSocket-Key).
Computes Sec-WebSocket-Accept from client key.
Negotiates subprotocols and extensions (e.g., permessage-deflate).
See also
SocketHTTP1_Parser for request parsing.
ws_handshake_server_process() to send response.
RFC 6455 Section 4.2.2 for server validation.
ws_handshake_server_process()
int ws_handshake_server_process (SocketWS_T ws)
Processes server handshake I/O in non-blocking manner.
Parameters
ws The WebSocket context.
Returns
0 if handshake complete, 1 if in progress, -1 on error.
Note
Sends 101 response after validation.
Transitions to frame mode on success.
See also
ws_handshake_server_init() prerequisite.
RFC 6455 Section 4.1 for server opening handshake.
ws_handshake_validate_accept()
int ws_handshake_validate_accept (SocketWS_T ws, const char * accept)
Validates the server's Sec-WebSocket-Accept header value.
Parameters
ws The WebSocket context (contains expected_accept).
accept The received accept string from server response.
Returns
0 if matches expected value, -1 if mismatch or invalid.
Note
Computes expected as SHA1(key + magic) base64.
See also
SocketCrypto_websocket_accept_compute() for computation.
RFC 6455 Section 4.2.2 for accept key derivation.
ws_is_control_opcode()
static int ws_is_control_opcode (SocketWS_Opcode opcode) inline static
Check if opcode represents a control frame.
Control frames: CLOSE (8), PING (9), PONG (A) - high bit set. Data frames: CONT (0), TEXT (1), BINARY (2) - low bits.
Used for special handling: immediate processing, no fragmentation.
Parameters
opcode Frame opcode.
Returns
1 if control frame, 0 otherwise.
See also
ws_is_data_opcode() for data frames.
RFC 6455 Section 5.2 for opcode ranges.
Definition at line 1402 of file SocketWS-private.h.
ws_is_data_opcode()
static int ws_is_data_opcode (SocketWS_Opcode opcode) inline static
Check if opcode represents a data frame.
Data frames: CONTINUATION (0), TEXT (1), BINARY (2). Can be fragmented (multiple frames per message).
Parameters
opcode Frame opcode.
Returns
1 if data frame (text/binary/cont), 0 otherwise.
See also
ws_is_control_opcode() for control frames.
RFC 6455 Section 5.2 for data opcodes.
Definition at line 1421 of file SocketWS-private.h.
References WS_OPCODE_BINARY, and WS_OPCODE_TEXT.
ws_is_valid_close_code()
static int ws_is_valid_close_code (int code) inline static
Validate close status code per RFC 6455.
Valid codes: 1000-1014 (excluding 1004-1006 sometimes internal), or 3000-4999 (library-specific). Invalid: <1000, 1004-1006 (internal), 1015 (TLS, internal), others.
Used in CLOSE frame processing/sending to ensure compliance.
Parameters
code Close code from frame.
Returns
1 if valid for transmission, 0 otherwise.
Note
Some codes (1001-1014) valid only on close, not status.
See also
RFC 6455 Section 7.4.1 for defined codes and ranges.
SocketWS_CloseCode enum for common codes.
Definition at line 1461 of file SocketWS-private.h.
ws_is_valid_opcode()
static int ws_is_valid_opcode (SocketWS_Opcode opcode) inline static
Checks if a WebSocket opcode is valid per RFC 6455.
Parameters
opcode The opcode to validate.
Returns
1 if valid (0-2 data, 8-A control), 0 otherwise.
Note
Data: 0 CONT, 1 TEXT, 2 BINARY; Control: 8 CLOSE, 9 PING, A PONG.
See also
ws_is_control_opcode(), ws_is_data_opcode().
RFC 6455 Section 5.2 Table 1 for opcodes.
Definition at line 1437 of file SocketWS-private.h.
References WS_OPCODE_BINARY, WS_OPCODE_CLOSE, and WS_OPCODE_PONG.
ws_mask_payload()
void ws_mask_payload (unsigned char * data, size_t len, const unsigned char mask[4])
Applies XOR masking to WebSocket payload data in place.
Parameters
data The payload buffer to mask (modified in place).
len The length of the data to mask.
mask The 4-byte masking key (cycles every 4 bytes).
Note
Required for client-to-server frames per RFC.
Optimized with 64-bit aligned loops for performance.
Server frames must not be masked.
See also
ws_mask_payload_offset() for incremental masking.
RFC 6455 Section 5.3 for masking algorithm.
ws_mask_payload_offset()
size_t ws_mask_payload_offset (unsigned char * data, size_t len, const unsigned char mask[4], size_t offset)
Applies XOR masking to payload starting from a given mask offset.
Parameters
data The payload buffer to mask (modified in place).
len The length of the data to mask.
mask The 4-byte masking key.
offset Initial offset into the mask cycle (0-3).
Returns
The updated offset for the next chunk ((offset + len) % 4).
Note
Used for incremental masking in streaming scenarios.
Equivalent to ws_mask_payload() when offset=0.
See also
ws_mask_payload() for full payload masking.
RFC 6455 Section 5.3 masking details.
ws_message_append()
int ws_message_append (SocketWS_T ws, const unsigned char * data, size_t len, int is_text)
Appends a data frame fragment to the current message assembly.
Parameters
ws The WebSocket context.
data The fragment payload (unmasked).
len Length of fragment.
is_text Non-zero if text message (enables UTF-8 validation).
Returns
0 on success, -1 on error (exceeds max size/fragments, UTF-8 invalid).
Note
Updates message.len and fragment_count; checks limits.
Decompresses if RSV1 set on first fragment.
See also
ws_message_finalize() called on FIN=1.
SocketWS_MessageAssembly for state.
RFC 6455 Section 5.4 for message fragmentation.
ws_message_finalize()
int ws_message_finalize (SocketWS_T ws)
Finalizes message assembly on last fragment and delivers to user.
Parameters
ws The WebSocket context.
Returns
0 on success, -1 on error (UTF-8 invalid for text, or other).
Note
Called when FIN=1 on data frame.
Performs final UTF-8 validation for text messages.
Invokes user callback with complete SocketWS_Message.
Resets assembly state for next message.
See also
SocketWS_MessageCallback for delivery.
SocketUTF8_State for validation.
ws_message_reset()
void ws_message_reset (SocketWS_MessageAssembly * message)
Resets the message reassembly state for a new message.
Parameters
message The message assembly structure to reset.
Note
Clears data buffer, length, fragments, UTF-8 state.
Called before first fragment of new message.
See also
ws_message_append() to start assembly.
SocketWS_MessageAssembly for fields.
ws_send_close()
int ws_send_close (SocketWS_T ws, SocketWS_CloseCode code, const char * reason)
Sends a WebSocket CLOSE control frame to initiate graceful shutdown.
Parameters
ws The WebSocket context.
code The close status code (valid per RFC or 0 for no code).
reason Optional UTF-8 reason string (truncated to max length).
Returns
0 on success, -1 on error (sets last_error).
Note
Validates code with ws_is_valid_close_code().
Sets close_sent flag; peer should respond with CLOSE.
After mutual CLOSE, connection enters CLOSING state.
See also
SocketWS_close() public API wrapper.
RFC 6455 Section 7.1 for close handshake.
ws_send_control_frame()
int ws_send_control_frame (SocketWS_T ws, SocketWS_Opcode opcode, const unsigned char * payload, size_t len)
Sends WebSocket control frame: PING, PONG, or CLOSE.
Constructs and transmits a control frame over the WebSocket connection. Control frames are processed immediately, cannot be fragmented, and have payload limit of 125 bytes. Used for keepalive (PING/PONG) and graceful closure (CLOSE). Automatically flushes to socket if possible; otherwise queues.
Behavior:
Builds frame header with opcode, no RSV (unless extensions), masked if client.
Validates len <= 125, opcode control type.
Applies masking to payload if client role.
Appends to send_buf, calls ws_flush_send_buffer().
Error conditions:
Invalid opcode (not 8/9/A): SocketWS_Failed
len > SOCKETWS_MAX_CONTROL_PAYLOAD: truncates or fails
Socket send error or closed: sets last_error, returns -1
Parameters
[in] ws Active WebSocket context (state must be OPEN)
[in] opcode Control opcode: WS_OPCODE_CLOSE (8), WS_OPCODE_PING (9), WS_OPCODE_PONG (10)
[in] payload Payload bytes; NULL=empty. For CLOSE: code(2B)+reason(UTF8); PING/PONG: app data
[in] len Exact payload length (0-125 bytes)
Returns
0 Success: frame built and queued/flushed
-1 Failure: error code in ws->last_error, msg in error_buf
Exceptions
SocketWS_Failed Invalid params, build error, or I/O failure
SocketWS_Closed Connection not in OPEN state
SocketWS_ProtocolError Invalid control opcode
Thread Safety\n No - modifies ws->send_buf and socket state; serialize calls
Sending PING for Keepalive
// Simple ping to check peer responsiveness
unsigned char ping_data[] = {'H', 'e', 'l', 'l', 'o'};
if (ws_send_control_frame(ws, WS_OPCODE_PING, ping_data, sizeof(ping_data))
!= 0) { SOCKET_LOG_ERROR("PING failed: %s", SocketWS_get_error_msg(ws));
    // Consider closing connection
}
Initiating Graceful Close
// Send CLOSE with normal code 1000
uint16_t code = htons(1000); // Big-endian
TRY {
    ws_send_control_frame(ws, WS_OPCODE_CLOSE, (unsigned char*)&code, 2);
    ws->state = WS_CLOSING;  // Update state
} EXCEPT(SocketWS_Failed) {
    // Fallback to hard close
    Socket_shutdown(ws->socket, SHUT_RDWR);
} END_TRY;
Responding to PING
// In frame handler: echo payload back as PONG
if (opcode == WS_OPCODE_PING) {
    ws_send_control_frame(ws, WS_OPCODE_PONG, received_payload,
received_len);
}
Note
Payload for CLOSE: first 2 bytes uint16 BE status code, rest UTF-8 reason (total <=125)
Warning
Use only valid close codes; see ws_is_valid_close_code()
Note
If ws->config.close_auto_respond enabled, CLOSE triggers peer response
Complexity\n O(1 + len) - constant time header + linear payload mask/copy
See also
ws_send_data_frame() For fragmented data messages
ws_handle_control_frame() Incoming control processing
ws_send_close() Higher-level CLOSE sender
ws_flush_send_buffer() Underlying flush mechanism
RFC 6455 Sec. 5.5 (Control Frames), 7.1 (Close), 5.5.2 (Ping), 5.5.3 (Pong)
ws_send_data_frame()
int ws_send_data_frame (SocketWS_T ws, SocketWS_Opcode opcode, const unsigned char * data, size_t len, int fin)
Sends a WebSocket data frame (TEXT or BINARY).
Parameters
ws The WebSocket connection context.
opcode The data frame opcode (WS_OPCODE_TEXT or WS_OPCODE_BINARY).
data The payload data to send.
len The length of the payload data.
fin Non-zero if this is the final fragment of the message.
Returns
0 on success, -1 on error (sets last_error).
Exceptions
SocketWS_Failed if send fails, invalid opcode, or exceeds limits.
Note
Supports fragmentation (fin=0 for continuation frames).
Payload masked for client role, unmasked for server.
See also
ws_send_control_frame() for control frames.
RFC 6455 Section 5.6 for data frame format and masking.
ws_send_ping()
int ws_send_ping (SocketWS_T ws, const unsigned char * payload, size_t len)
Sends a WebSocket PING control frame for keepalive.
Parameters
ws The WebSocket context.
payload Optional application data in ping (NULL for empty).
len Length of payload (0 to 125 bytes).
Returns
0 on success, -1 on error.
Note
Peer must respond with PONG containing same payload.
Used for heartbeat; auto-triggered by timer if configured.
See also
ws_send_pong() for response.
ws_auto_ping_start() for automatic pings.
RFC 6455 Section 5.5.2 for PING/PONG.
ws_send_pong()
int ws_send_pong (SocketWS_T ws, const unsigned char * payload, size_t len)
Sends a WebSocket PONG control frame in response to PING.
Parameters
ws The WebSocket context.
payload The payload to echo from received PING (or arbitrary).
len Length of payload (0-125).
Returns
0 on success, -1 on error.
Note
Typically called automatically on PING receipt.
See also
ws_handle_control_frame() for automatic response.
ws_send_ping() for initiating ping.
RFC 6455 Section 5.5.3 for PONG semantics.
ws_set_error()
void ws_set_error (SocketWS_T ws, SocketWS_Error error, const char * fmt, ...)
Sets the last error code and formats error message.
Parameters
ws The WebSocket context.
error The SocketWS_Error code to set.
fmt printf-style format string for error_buf.
... Arguments for format string.
Note
Truncates message to SOCKETWS_ERROR_BUFSIZE.
Used internally for all error paths.
See also
SocketWS_get_last_error() public accessor.
Variable Documentation
SocketWS_Closed
const Except_T SocketWS_Closed extern
Exception indicating the WebSocket connection has been closed.
Raised when attempting operations on a CLOSED connection or after clean close.
See also
SocketWS_state() == WS_STATE_CLOSED.
SocketWS_close() to initiate close.
Referenced by main().
SocketWS_Failed
const Except_T SocketWS_Failed extern
Exception raised for general WebSocket operation failures.
Thrown on allocation failures, invalid states, or unrecoverable errors.
See also
SocketWS_Error for specific error codes.
Referenced by main().
SocketWS_ProtocolError
const Except_T SocketWS_ProtocolError extern
Exception for WebSocket protocol violations (RFC 6455 non-compliance).
Raised on invalid opcodes, malformed frames, missing masks (server), etc.
See also
WS_ERROR_PROTOCOL for related non-exception errors.
Referenced by main().