Tetsuo Pulse: Connection Management Modules
Connection Management Modules
Connection lifecycle management with pooling, reconnection, and resilience patterns.
Modules
SocketReconnect Private Implementation Details
Internal structures and utilities for reconnection logic.
Files
file SocketPool-private.h
Private implementation details and internal structures for SocketPool module.
file SocketPool.h
Connection pooling with automatic lifecycle management.
file SocketReconnect-private.h
Private header for SocketReconnect module internals.
file SocketReconnect.h
Automatic reconnection framework for resilient TCP connections with backoff and circuit breaker patterns.
Data Structures
struct Connection_T
Internal structure representing a pooled connection slot.
struct AsyncConnectContext_T
Internal context structure for tracking asynchronous connect operations.
struct SocketPool_Stats
Pool statistics snapshot structure.
struct SocketReconnect_T
Opaque internal context for reconnecting socket management.
struct SocketReconnect_Policy_T
Configuration structure defining backoff policy, circuit breaker thresholds, and health check parameters for SocketReconnect_T.
Macros
#define SOCKET_DEFAULT_IDLE_TIMEOUT 300 /* 5 minutes */
Default idle timeout.
#define SOCKET_DEFAULT_POOL_SIZE 1000
Default connection pool size.
#define SOCKET_DEFAULT_POOL_BUFSIZE 8192
Default pool buffer size.
#define SOCKET_POOL_DEFAULT_PREWARM_PCT 20
Default pool prewarm percentage.
#define SOCKET_POOL_MAX_BATCH_ACCEPTS 1000
Maximum batch accepts per iteration.
#define SOCKET_POOL_MAX_ASYNC_PENDING 1000
Maximum pending async connect operations per pool.
#define SOCKET_PERCENTAGE_DIVISOR 100
Percentage divisor for calculations.
#define SOCKET_POOL_STATS_WINDOW_SEC 60
Time window for pool statistics calculation.
#define SOCKET_POOL_MAX_RATE_PER_SEC 1000000
Maximum rate limit value (connections per second).
#define SOCKET_POOL_MAX_BURST_MULTIPLIER 100
Maximum burst multiplier relative to rate.
#define SOCKET_POOL_MAX_CONNECTIONS_PER_IP 10000
Maximum connections allowed per IP address.
#define SOCKET_POOL_TOKENS_PER_ACCEPT 1
Tokens consumed per connection accept.
#define SOCKET_LOG_COMPONENT "SocketPool"
Default log component for all SocketPool implementation files.
#define POOL_LOCK(p)
Acquire pool mutex.
#define POOL_UNLOCK(p)
Release pool mutex.
#define SOCKET_HASH_SIZE SOCKET_HASH_TABLE_SIZE
Alias for the library's central hash table size configuration.
#define RAISE_POOL_ERROR(exception)
Raise exception with detailed error message.
#define RAISE_POOL_MSG(exception, fmt, ...)
Format error message (without errno) and raise.
#define RAISE_POOL_FMT(exception, fmt, ...)
Format error message (with errno) and raise.
#define T SocketPool_T
Core internal structure defining the complete SocketPool state.
#define T SocketPool_T
High-level connection pool with lifecycle management.
#define SOCKET_RECONNECT_ERROR_BUFSIZE 256
Maximum buffer capacity for internal error message strings.
#define SOCKET_RECONNECT_MAX_HOST_LEN 255
Maximum length for target hostname/IP strings (excluding null terminator).
Typedefs
typedef int(* SocketPool_ValidationCallback) (Connection_T conn, void *data)
Callback to validate connection before reuse.
typedef void(* SocketPool_ResizeCallback) (SocketPool_T pool, size_t old_size, size_t new_size, void *data)
Callback invoked after pool resize.
typedef void(* SocketPool_IdleCallback) (Connection_T conn, void *data)
Callback invoked when a connection becomes idle.
typedef int(* SocketPool_Predicate) (Connection_T conn, void *data)
Predicate callback for filtering connections.
typedef void(* SocketPool_ConnectCallback) (Connection_T conn, int error, void *data)
Completion callback for async connections.
typedef void(* SocketPool_DrainCallback) (SocketPool_T pool, int timed_out, void *data)
Notification callback when drain completes.
typedef void(* SocketReconnect_Callback) (SocketReconnect_T conn, SocketReconnect_State old_state, SocketReconnect_State new_state, void *userdata)
Callback invoked on reconnection state transitions for monitoring and custom logic.
typedef int(* SocketReconnect_HealthCheck) (SocketReconnect_T conn, Socket_T socket, int timeout_ms, void *userdata)
Custom health check callback to verify connection liveness beyond basic connectivity.
Enumerations
enum SocketPool_State {
POOL_STATE_RUNNING = 0 ,
POOL_STATE_DRAINING ,
POOL_STATE_STOPPED
}
Pool lifecycle states for graceful shutdown.
enum SocketPool_Health {
POOL_HEALTH_HEALTHY = 0 ,
POOL_HEALTH_DRAINING ,
POOL_HEALTH_STOPPED
}
Health status for load balancer integration.
enum SocketPool_ConnHealth {
POOL_CONN_HEALTHY = 0 ,
POOL_CONN_DISCONNECTED ,
POOL_CONN_ERROR ,
POOL_CONN_STALE
}
Connection health status enumeration.
enum SocketReconnect_CircuitState {
CIRCUIT_CLOSED = 0 ,
CIRCUIT_OPEN ,
CIRCUIT_HALF_OPEN
}
Internal circuit breaker states for reconnection resilience.
enum SocketReconnect_State {
RECONNECT_DISCONNECTED = 0 ,
RECONNECT_CONNECTING ,
RECONNECT_CONNECTED ,
RECONNECT_BACKOFF ,
RECONNECT_CIRCUIT_OPEN
}
States of the reconnection state machine for tracking connection lifecycle and backoff status.
Functions
void SocketPool_connections_initialize_slot (struct Connection *conn)
Allocate and zero-initialize array of connection structures.
int SocketPool_connections_alloc_buffers (Arena_T arena, size_t bufsize, Connection_T conn)
Allocate input/output buffers for connection.
Connection_T find_slot (SocketPool_T pool, const Socket_T socket)
Find connection slot by socket (internal).
Connection_T find_free_slot (const SocketPool_T pool)
Find first available free connection slot.
int check_pool_full (const SocketPool_T pool)
Check if pool has reached maximum capacity.
void remove_from_free_list (SocketPool_T pool, Connection_T conn)
Remove connection from free list.
void return_to_free_list (SocketPool_T pool, Connection_T conn)
Return connection to free list.
int prepare_free_slot (SocketPool_T pool, Connection_T conn)
Prepare free slot for new connection.
void update_existing_slot (Connection_T conn, time_t now)
Update existing connection slot activity.
void insert_into_hash_table (SocketPool_T pool, Connection_T conn, Socket_T socket)
Insert connection into hash table.
void increment_pool_count (SocketPool_T pool)
Increment active connection count.
void initialize_connection (Connection_T conn, Socket_T socket, time_t now)
Initialize connection with socket and timestamp.
Connection_T find_or_create_slot (SocketPool_T pool, Socket_T socket, time_t now)
Find existing connection or create new slot.
void remove_from_hash_table (SocketPool_T pool, Connection_T conn, Socket_T socket)
Remove connection from hash table.
void SocketPool_connections_reset_slot (Connection_T conn)
Securely clear (zero) connection's input/output buffers.
void decrement_pool_count (SocketPool_T pool)
Decrement active connection count.
void validate_saved_session (Connection_T conn, time_t now)
Validate TLS session for reuse.
unsigned socketpool_hash (const Socket_T socket)
Allocate temporary buffer for bulk cleanup operations from arena.
time_t safe_time (void)
Get current time with error handling.
static size_t socketpool_enforce_range (size_t val, size_t minv, size_t maxv)
Clamp value to min/max bounds.
static size_t socketpool_enforce_max_connections (size_t maxconns)
Enforce maximum connection limit.
static size_t socketpool_enforce_buffer_size (size_t bufsize)
Enforce buffer size limits.
SocketPool_T SocketPool_new (Arena_T arena, size_t maxconns, size_t bufsize)
Create a new connection pool.
int SocketPool_prepare_connection (SocketPool_T pool, SocketDNS_T dns, const char *host, int port, Socket_T *out_socket, Request_T *out_req)
Prepare async connection using DNS resolution.
void SocketPool_free (SocketPool_T *pool)
Free a connection pool and release all resources.
Request_T SocketPool_connect_async (SocketPool_T pool, const char *host, int port, SocketPool_ConnectCallback callback, void *data)
Create async connection to remote host.
Connection_T SocketPool_get (SocketPool_T pool, Socket_T socket)
Retrieve Connection_T wrapper for a socket in the pool.
Connection_T SocketPool_add (SocketPool_T pool, Socket_T socket)
Add a connected socket to the pool, creating a Connection_T wrapper.
int SocketPool_accept_batch (SocketPool_T pool, Socket_T server, int max_accepts, size_t accepted_capacity, Socket_T *accepted)
Accept multiple connections from server socket.
void SocketPool_remove (SocketPool_T pool, Socket_T socket)
Remove socket from pool.
void SocketPool_cleanup (SocketPool_T pool, time_t idle_timeout)
Remove idle connections.
size_t SocketPool_count (SocketPool_T pool)
Get active connection count.
void SocketPool_resize (SocketPool_T pool, size_t new_maxconns)
Resize pool capacity at runtime.
void SocketPool_prewarm (SocketPool_T pool, int percentage)
Pre-allocate buffers for percentage of free slots.
void SocketPool_set_bufsize (SocketPool_T pool, size_t new_bufsize)
Set buffer size for future connections.
void SocketPool_foreach (SocketPool_T pool, void(*func)(Connection_T, void *), void *arg)
Iterate over active connections.
Connection_T SocketPool_find (SocketPool_T pool, SocketPool_Predicate predicate, void *userdata)
Find first connection matching a predicate.
size_t SocketPool_filter (SocketPool_T pool, SocketPool_Predicate predicate, void *userdata, Connection_T *results, size_t max_results)
Find all connections matching a predicate.
Socket_T Connection_socket (const Connection_T conn)
Get connection's socket.
SocketBuf_T Connection_inbuf (const Connection_T conn)
Get connection's input buffer.
SocketBuf_T Connection_outbuf (const Connection_T conn)
Get connection's output buffer.
void * Connection_data (const Connection_T conn)
Get connection's user data.
void Connection_setdata (Connection_T conn, void *data)
Set connection's user data.
time_t Connection_lastactivity (const Connection_T conn)
Get connection's last activity timestamp.
int Connection_isactive (const Connection_T conn)
Check if connection is active.
void SocketPool_set_reconnect_policy (SocketPool_T pool, const SocketReconnect_Policy_T *policy)
Set default reconnection policy for pool.
void SocketPool_enable_reconnect (SocketPool_T pool, Connection_T conn, const char *host, int port)
Enable auto-reconnect for a connection.
void SocketPool_disable_reconnect (SocketPool_T pool, Connection_T conn)
Disable auto-reconnect for a connection.
void SocketPool_process_reconnects (SocketPool_T pool)
Process reconnection state machines.
int SocketPool_reconnect_timeout_ms (SocketPool_T pool)
Get time until next reconnection action.
SocketReconnect_T Connection_reconnect (const Connection_T conn)
Get reconnection context for connection.
int Connection_has_reconnect (const Connection_T conn)
Check if connection has auto-reconnect enabled.
void SocketPool_setconnrate (SocketPool_T pool, int conns_per_sec, int burst)
Set connection rate limit.
int SocketPool_getconnrate (SocketPool_T pool)
Get connection rate limit.
void SocketPool_setmaxperip (SocketPool_T pool, int max_conns)
Set maximum connections per IP.
int SocketPool_getmaxperip (SocketPool_T pool)
Get maximum connections per IP.
int SocketPool_accept_allowed (SocketPool_T pool, const char *client_ip)
Check if accepting is allowed.
Socket_T SocketPool_accept_limited (SocketPool_T pool, Socket_T server)
Accept connection with rate limiting.
int SocketPool_track_ip (SocketPool_T pool, const char *ip)
Manually track IP for per-IP limiting.
void SocketPool_release_ip (SocketPool_T pool, const char *ip)
Release tracked IP when connection closes.
int SocketPool_ip_count (SocketPool_T pool, const char *ip)
Get connection count for IP.
void SocketPool_set_syn_protection (SocketPool_T pool, SocketSYNProtect_T protect)
Enable SYN flood protection for pool.
SocketSYNProtect_T SocketPool_get_syn_protection (SocketPool_T pool)
Get current SYN protection module.
Socket_T SocketPool_accept_protected (SocketPool_T pool, Socket_T server, SocketSYN_Action *action_out)
Accept with full SYN flood protection.
SocketPool_State SocketPool_state (SocketPool_T pool)
Get current pool lifecycle state.
SocketPool_Health SocketPool_health (SocketPool_T pool)
Get pool health status for load balancers.
int SocketPool_is_draining (SocketPool_T pool)
Check if pool is currently draining.
int SocketPool_is_stopped (SocketPool_T pool)
Check if pool is fully stopped.
void SocketPool_drain (SocketPool_T pool, int timeout_ms)
Initiate graceful shutdown.
int SocketPool_drain_poll (SocketPool_T pool)
Poll drain progress (non-blocking).
int64_t SocketPool_drain_remaining_ms (SocketPool_T pool)
Get time until forced shutdown.
void SocketPool_drain_force (SocketPool_T pool)
Force immediate shutdown.
int SocketPool_drain_wait (SocketPool_T pool, int timeout_ms)
Blocking drain with internal poll loop.
void SocketPool_set_drain_callback (SocketPool_T pool, SocketPool_DrainCallback cb, void *data)
Register drain completion callback.
void SocketPool_set_idle_timeout (SocketPool_T pool, time_t timeout_sec)
Set idle connection timeout.
time_t SocketPool_get_idle_timeout (SocketPool_T pool)
Get idle connection timeout.
int64_t SocketPool_idle_cleanup_due_ms (SocketPool_T pool)
Get time until next idle cleanup.
size_t SocketPool_run_idle_cleanup (SocketPool_T pool)
Run idle connection cleanup if due.
SocketPool_ConnHealth SocketPool_check_connection (SocketPool_T pool, Connection_T conn)
Check health of a connection.
void SocketPool_set_validation_callback (SocketPool_T pool, SocketPool_ValidationCallback cb, void *data)
Set connection validation callback.
void SocketPool_set_resize_callback (SocketPool_T pool, SocketPool_ResizeCallback cb, void *data)
Register pool resize notification callback.
void SocketPool_get_stats (SocketPool_T pool, SocketPool_Stats *stats)
Get pool statistics snapshot.
void SocketPool_reset_stats (SocketPool_T pool)
Reset pool statistics counters.
size_t SocketPool_get_idle_count (SocketPool_T pool)
Get count of currently idle connections.
size_t SocketPool_get_active_count (SocketPool_T pool)
Get count of currently active connections.
double SocketPool_get_hit_rate (SocketPool_T pool)
Get connection reuse rate (hit rate).
size_t SocketPool_shrink (SocketPool_T pool)
Release unused pool capacity.
void SocketPool_set_idle_callback (SocketPool_T pool, SocketPool_IdleCallback cb, void *data)
Register callback for when connections become idle.
time_t Connection_created_at (const Connection_T conn)
Get connection creation timestamp.
static int64_t socketreconnect_now_ms (void)
Retrieve current monotonic time in milliseconds for internal timing.
static int64_t socketreconnect_elapsed_ms (int64_t start_ms)
Compute elapsed monotonic time since provided start timestamp.
static double reconnect_jitter (void)
Generate uniform random double in [0.0, 1.0) for jitter in backoff calculations.
SocketReconnect_T SocketReconnect_new (const char *host, int port, const SocketReconnect_Policy_T *policy, SocketReconnect_Callback callback, void *userdata)
Create a new SocketReconnect_T instance configured for a specific host and port.
void SocketReconnect_free (SocketReconnect_T *conn)
Destroy a SocketReconnect_T instance and release all associated resources.
void SocketReconnect_connect (SocketReconnect_T conn)
Initiate or queue a connection attempt according to current state and policy.
void SocketReconnect_disconnect (SocketReconnect_T conn)
Gracefully disconnect without triggering reconnect.
void SocketReconnect_reset (SocketReconnect_T conn)
Reset reconnection statistics and state machine.
Socket_T SocketReconnect_socket (SocketReconnect_T conn)
Get the underlying Socket_T when connected.
SocketReconnect_State SocketReconnect_state (SocketReconnect_T conn)
Query the current state of the reconnection instance.
int SocketReconnect_isconnected (SocketReconnect_T conn)
Check if reconnection is currently in connected state.
int SocketReconnect_attempts (SocketReconnect_T conn)
Get number of connection attempts since last success or reset.
int SocketReconnect_failures (SocketReconnect_T conn)
Get count of consecutive connection failures.
int SocketReconnect_pollfd (SocketReconnect_T conn)
Retrieve file descriptor for event loop integration (poll/epoll/kqueue/select).
void SocketReconnect_process (SocketReconnect_T conn)
Process I/O events from poll loop.
int SocketReconnect_next_timeout_ms (SocketReconnect_T conn)
Calculate milliseconds until next timer event or action.
void SocketReconnect_tick (SocketReconnect_T conn)
Advance timers and perform periodic maintenance for state transitions and checks.
void SocketReconnect_set_health_check (SocketReconnect_T conn, SocketReconnect_HealthCheck check)
Register a custom health check callback for proactive connection validation.
void SocketReconnect_policy_defaults (SocketReconnect_Policy_T *policy)
Populate a SocketReconnect_Policy_T with safe, production-recommended default values.
ssize_t SocketReconnect_send (SocketReconnect_T conn, const void *buf, size_t len)
Send data over the reconnection-managed connection with automatic retry on transient errors.
ssize_t SocketReconnect_recv (SocketReconnect_T conn, void *buf, size_t len)
Receive data from the reconnection-managed connection, auto-reconnecting on close or errors.
const char * SocketReconnect_state_name (SocketReconnect_State state)
Get human-readable name for a reconnection state.
void SocketReconnect_set_tls (SocketReconnect_T conn, SocketTLSContext_T ctx, const char *hostname)
Configure TLS for reconnecting connections.
void SocketReconnect_disable_tls (SocketReconnect_T conn)
Disable TLS for future connections.
int SocketReconnect_tls_enabled (SocketReconnect_T conn)
Check if TLS is configured for this connection.
const char * SocketReconnect_get_tls_hostname (SocketReconnect_T conn)
Get the configured TLS hostname.
TLSHandshakeState SocketReconnect_tls_handshake_state (SocketReconnect_T conn)
Get current TLS handshake state.
void SocketReconnect_set_session_resumption (SocketReconnect_T conn, int enable)
Enable TLS session resumption for faster reconnects.
int SocketReconnect_is_session_reused (SocketReconnect_T conn)
Check if last connection used session resumption.
Variables
Except_T SocketPool_DetailedException
Thread-local exception for detailed error messages.
const Except_T SocketPool_Failed
Pool operation failure.
const Except_T SocketReconnect_Failed
Exception type for errors in the reconnection module.
Detailed Description
Connection lifecycle management with pooling, reconnection, and resilience patterns.
The Connection Management group handles connection lifecycle, pooling, and resilience patterns. Key components include:
SocketPool (pooling): Connection pooling with automatic lifecycle management
SocketReconnect (reconnection): Auto-reconnection with circuit breaker
SocketRateLimit (rate-limit): Token bucket rate limiting
SocketSYNProtect (syn-flood): SYN flood protection
See also
Core I/O Modules for socket primitives.
Event System Modules for event notification.
Core Foundation Modules for memory management and exceptions.
Asynchronous DNS Resolution for DNS resolution support.
SocketPool_T for connection pooling.
connection_mgmt::SocketReconnect_T for auto-reconnection.
Connection_T for connection accessors.
utilities::SocketRateLimit_T for rate limiting.
security::SocketSYNProtect_T for SYN flood protection.
Data Structure Documentation
Connection
struct Connection
Internal structure representing a pooled connection slot.
Opaque connection handle within a pool.
Internal typedef for connection structure pointer.
Each instance manages a single socket connection with dedicated input/output buffers, activity timestamps, user data, and optional advanced features like auto-reconnection and TLS session persistence.
CORE MANAGEMENT:
Pre-allocated in fixed-size array (pool->connections) for predictable memory
Fast O(1) lookup via hash table (pool->hash_table) keyed on socket FD
Free list (pool->free_list) for quick slot recycling
Linked lists for hash collisions (hash_next) and free slots (free_next)
STATE TRACKING:
active flag distinguishes used vs free slots
last_activity for idle timeout enforcement
created_at for age-based cleanup and stats
EXTENSIONS:
reconnect: Optional SocketReconnect_T for automatic reconnection
tracked_ip: Per-IP rate limiting via SocketIPTracker_T
TLS fields: Context, handshake state, session reuse (conditional on SOCKET_HAS_TLS)
THREAD SAFETY: All modifications protected by pool->mutex. Readers should acquire mutex or use atomic checks for count/state. Accessors in public API handle locking transparently.
LIFECYCLE:
Initialized via SocketPool_connections_initialize_slot()
Buffers allocated in SocketPool_connections_alloc_buffers()
Added to pool via find_or_create_slot() / insert_into_hash_table()
Removed via remove_from_hash_table() / SocketPool_connections_reset_slot()
Buffers released in SocketPool_connections_release_buffers()
Note
Fields like hash_next/free_next are internal linking only; ignore for app logic.
Warning
Direct field access bypasses thread safety - use accessors or lock pool. @security TLS session reuse reduces handshake overhead but validate saved_session via validate_saved_session() before reuse to prevent stale sessions.
See also
SocketPool_T::connections for array allocation.
socketpool_hash() for FD-based hashing.
find_slot() / find_free_slot() for lookup/allocation logic.
SocketPool_add() / SocketPool_get() for public entry points.
SocketPool.h::Connection_T for public opaque interface.
Connection Mgmt Module for pooling patterns.
connection_mgmt::SocketReconnect_T for reconnection integration.
security::SocketTLSContext for TLS support.
Opaque externally; provides handle to managed connection state including socket, buffers, timestamps, and optional TLS/reconnect contexts. Access internal fields only within SocketPool implementation files.
Note
This typedef matches public Connection_T in SocketPool.h but includes full struct definition here for implementation convenience.
See also
SocketPool.h::Connection_T for public opaque type documentation.
struct Connection for detailed field descriptions.
Connection_* accessor functions in SocketPool.h.
Connection Mgmt Module for usage patterns.
Represents a single socket connection within a pool, including associated buffers, metadata, and lifecycle state. Use accessor functions to read/write connection properties. All connection operations are thread-safe.
See also
Connection_socket() for socket access.
Connection_inbuf() and Connection_outbuf() for buffer access.
Connection_data() and Connection_setdata() for user data storage.
Connection_lastactivity() for activity tracking.
Connection_isactive() for connection state.
SocketPool_add() for connection creation.
SocketPool_get() for connection lookup.
SocketPool_remove() for connection removal.
Definition at line 324 of file SocketPool-private.h.
Data Fields
int active
Non-zero if slot contains active connection
time_t created_at
Connection creation timestamp (for age tracking)
void * data
User data pointer
struct Connection * free_next
Next in free list (when inactive)
struct Connection * hash_next
Next in hash table collision chain
SocketBuf_T inbuf
Input buffer for reading data
time_t last_activity
Last activity timestamp for idle timeout
int last_socket_fd
FD of last socket (for session persistence)
SocketBuf_T outbuf
Output buffer for writing data
SocketReconnect_T reconnect
Auto-reconnection context (NULL if disabled)
Socket_T socket
Associated socket (NULL if free)
SocketTLSContext_T tls_ctx
TLS context for this connection
int tls_handshake_complete
TLS handshake state
SSL_SESSION * tls_session
Saved session for potential reuse
char * tracked_ip
Tracked IP for per-IP limiting (NULL if not tracked)
AsyncConnectContext
struct AsyncConnectContext
Internal context structure for tracking asynchronous connect operations.
Internal typedef for async connect context pointer.
Manages state for pending connections initiated via SocketPool_connect_async(), which combines DNS resolution, socket connection, and pool integration. Instances are allocated from the pool's arena and chained in pool->async_ctx list.
LIFECYCLE:
Allocated in SocketPool_connect_async() with user callback and data
DNS resolution started via SocketDNS_resolve() (req field)
Socket created and connect() initiated upon DNS success
Moved to active pool slot on successful connect, callback invoked
Removed and freed on failure, timeout, or pool destruction
Sockets in failed contexts are closed and freed during pool cleanup
THREAD SAFETY: List operations protected by pool mutex. DNS callbacks execute in worker threads; user SocketPool_ConnectCallback must be thread-safe.
MEMORY: All fields arena-allocated; no individual free() calls needed.
Note
Limit concurrent async connects via pool configuration to prevent resource exhaustion.
Warning
User callback runs in DNS worker thread context - avoid blocking operations.
See also
SocketPool_connect_async() for public async connect initiation.
SocketPool_ConnectCallback for completion notification requirements.
SocketDNS.h::Request_T for DNS request handling (Asynchronous DNS Resolution).
AsyncConnectContext_T for opaque typedef.
SocketPool_free() for ensuring pending sockets are cleaned up.
SocketPool.h for overall connection pool API.
Connection Management for resilience patterns.
DNS Module for asynchronous resolution details.
Opaque handle for tracking asynchronous connection operations involving DNS resolution, socket creation, and pool integration. Managed internally by SocketPool during async connect lifecycle.
Note
Not exposed in public API; used only within SocketPool implementation.
See also
struct AsyncConnectContext for private fields.
SocketPool_connect_async() in SocketPool.h for public async API.
SocketPool-private.h for internal async connect details.
Definition at line 408 of file SocketPool-private.h.
Data Fields
SocketPool_ConnectCallback cb
User callback
struct AsyncConnectContext * next
Next context in list
SocketPool_T pool
Pool instance
Request_T req
DNS resolution request (dns::Request_T). Used to track and retrieve results from async DNS lookup for host resolution.
See also
SocketDNS_resolve() for initiating resolution, SocketDNS_cancel() for aborting, SocketDNS_getresult() for retrieving addrinfo results.
Socket_T socket
Socket being connected
void * user_data
User data for callback
SocketPool_Stats
struct SocketPool_Stats
Pool statistics snapshot structure.
All counters are cumulative since pool creation or last reset. Rates are calculated over the configured statistics window. Thread-safe: All fields are read atomically during snapshot.
See also
SocketPool_get_stats() for retrieving statistics.
SocketPool_reset_stats() for resetting counters.
SocketPool_Stats for field descriptions.
Definition at line 1492 of file SocketPool.h.
Data Fields
double avg_connection_age_sec
Average age of active connections (seconds)
double churn_rate_per_sec
Churn rate: (added + removed) / window_sec
size_t current_active
Current active connection count
size_t current_idle
Current idle connection count (active but not in use)
size_t max_connections
Maximum connection capacity
double reuse_rate
Reuse rate: reused / (added + reused)
uint64_t total_added
Total connections added to pool
uint64_t total_health_checks
Total health checks performed
uint64_t total_health_failures
Total health check failures
uint64_t total_idle_cleanups
Connections removed due to idle timeout
uint64_t total_removed
Total connections removed from pool
uint64_t total_reused
Total connections reused (returned via get)
uint64_t total_validation_failures
Total validation callback failures
SocketReconnect_T
struct SocketReconnect_T
Opaque internal context for reconnecting socket management.
Opaque handle for a reconnecting socket connection.
Core data structure holding all configuration, state, timers, and resources for a single reconnection instance. Supports exponential backoff with jitter, circuit breaker pattern, periodic health checks, and automatic I/O recovery.
Key Responsibilities
State machine transitions (connect, backoff, circuit states)
Timer management (backoff delays, health intervals, circuit timeouts)
Failure counting and retry limits
Error logging and last-error tracking
Resource ownership (arena, socket, callbacks)
Field Groups Overview
Group Fields Purpose
Configuration policy, host, port Backoff policy and target endpoint
Resources arena, socket Memory and current connection handle
Callbacks callback, health_check, userdata Event notifications and
custom checks | | State | state, circuit_state | Current FSM and breaker status | | Tracking | attempt_*, failures, successes | Metrics for retries and reliability | | Timing | *_time_ms, backoff_until_ms, etc. | Monotonic timestamps for scheduling | | Connection | connect_in_progress | Async connect flags | | Errors | error_buf, last_error | Diagnostic information |
Lifecycle
Creation: SocketReconnect_new() allocates via arena, initializes policy, copies host/port
Operation: Public functions update fields atomically (e.g., connect starts async, updates timers)
Destruction: SocketReconnect_free() closes socket, disposes arena, clears pointers
Invariants:
arena always valid until free
socket NULL when not CONNECTED
Timestamps use monotonic ms (non-decreasing)
error_buf null-terminated, sized to SOCKET_RECONNECT_ERROR_BUFSIZE
Thread Safety
Thread Safety\n No - Designed for single-threaded access from event loop
All modifications via public API calls
Internal helpers (time, random) are thread-safe
Callbacks invoked from caller's thread context
Performance Notes
O(1) most operations (state checks, timer updates)
Minimal allocations (arena-backed)
Low memory footprint (~200-300 bytes + socket/arena)
Complexity\n Varies by operation; generally O(1)
Note
Host string copied to arena for lifetime management
Warning
Direct field access undefined; use accessors where public
Note
For leak detection, arena tracks all sub-allocs
See also
SocketReconnect_new() creation
SocketReconnect_free() destruction
SocketReconnect_Policy_T embedded policy
socketreconnect_get_time_ms() for timing helpers
Represents a resilient TCP connection that automatically manages reconnections using a state machine with exponential backoff, circuit breaker protection, and health monitoring.
The handle encapsulates:
Internal state machine tracking DISCONNECTED, CONNECTING, CONNECTED, BACKOFF, CIRCUIT_OPEN states
Timers for backoff delays, circuit reset, and health checks
Underlying Socket_T instance when connected
Statistics for attempts and failures
Optional callbacks for state changes and custom health checks
Create with SocketReconnect_new()
Configure policy, callbacks, health check if needed
Call SocketReconnect_connect() to start
Integrate with event loop or use passthrough I/O
Call SocketReconnect_free() to cleanup
// Full lifecycle
SocketReconnect_T conn = SocketReconnect_new(host, port, NULL, state_cb,
userdata); SocketReconnect_connect(conn);
while (SocketReconnect_isconnected(conn)) {
    // Use conn...
}
SocketReconnect_free(&conn);
Thread Safety Characteristics
Not thread-safe: All operations must occur from the same thread
Callbacks execute in the caller's thread context
Internal state protected by non-reentrant design
Integration Notes
For event-driven apps: Use pollfd(), process(), tick(), next_timeout_ms()
For simple apps: Use send()/recv() wrappers for auto-reconnect
Combine with SocketPool for managing multiple reconnections
Host/port are fixed at creation; for dynamic endpoints create new instances
Note
Underlying socket is created/destroyed internally; do not access directly except via SocketReconnect_socket()
Warning
Frequent state changes may indicate network issues; monitor via callbacks and statistics
Complexity\n State queries and timers O(1); connection establishment depends
on network latency
See also
SocketReconnect_new() Creation
SocketReconnect_free() Destruction
SocketReconnect_state() Current state
SocketReconnect_socket() Underlying socket access
SocketReconnect_Policy_T Configuration options
Definition at line 301 of file SocketReconnect-private.h.
Data Fields
Arena_T arena
Memory arena owning host string, error_buf contents, and any sub-allocs; Disposed on free(); all pointers invalidated after
int attempt_count
Attempts since last success or reset; resets on connect success
int64_t backoff_until_ms
Absolute time when current backoff period expires; used for next_timeout_ms
SocketReconnect_Callback callback
Optional state transition notifier (old->new state); Invoked synchronously from public API calls
int64_t circuit_open_time_ms
Timestamp when circuit opened; used for half-open transition
SocketReconnect_CircuitState circuit_state
Internal circuit breaker state; drives protection logic beyond public view
int connect_in_progress
Flag: non-zero if non-blocking connect pending; cleared on completion/error
int consecutive_failures
Consecutive failures; triggers circuit open at threshold
int current_backoff_delay_ms
Currently computed backoff delay (with jitter applied); for logging/metrics
char error_buf[256]
Fixed-size buffer for formatted last error (e.g., "connect failed: Connection refused"); Null-terminated; overwritten on new errors
SocketReconnect_HealthCheck health_check
Optional custom health check; if NULL, uses default poll-based check; Must respect timeout_ms param to avoid blocking
char * host
Target hostname/IP; null-terminated string allocated from arena; Length limited to SOCKET_RECONNECT_MAX_HOST_LEN (255 chars)
int64_t last_attempt_time_ms
Timestamp of most recent connect attempt
int last_error
Cached errno from last failure; 0 if no error
int64_t last_health_check_ms
Timestamp of last health check invocation
int64_t last_success_time_ms
Timestamp of last successful connection
SocketReconnect_Policy_T policy
Embedded backoff, circuit, and health policy; copied from input or defaults
int port
Target TCP/UDP port (1-65535); validated at creation
Socket_T socket
Current underlying socket; NULL when disconnected or connecting; Owned until closed on error/disconnect; do not free externally
SocketReconnect_State state
Public-facing state; updated on transitions
int64_t state_start_time_ms
Timestamp when current state entered
SocketTLSContext_T tls_ctx
TLS context for secure connections; NULL if TLS not configured. NOT owned by SocketReconnect - caller must ensure ctx outlives conn. Applied via SocketTLS_enable() after each successful TCP connect.
int tls_handshake_started
Flag: TLS handshake has been initiated for current connection. Set after SocketTLS_enable(); cleared on disconnect/error.
TLSHandshakeState tls_handshake_state
Current TLS handshake state; tracks progress during async handshake. Reset to TLS_HANDSHAKE_NOT_STARTED on each new connection attempt.
char * tls_hostname
SNI hostname for TLS certificate verification; arena-allocated. Used for SSL_set_tlsext_host_name() and X509 hostname check. NULL if TLS not configured.
unsigned char * tls_session_data
Saved TLS session data for resumption; arena-allocated. Populated after successful handshake if resumption enabled.
size_t tls_session_data_len
Length of saved TLS session data in bytes.
int tls_session_resumption_enabled
Flag: Enable session resumption for faster reconnects. When enabled, saves session after handshake and restores on reconnect.
int total_attempts
Lifetime total connection attempts; for long-term metrics
int total_successes
Lifetime successful connections; for reliability stats
void * userdata
Opaque user data forwarded to callbacks; stored as-is, no ownership
SocketReconnect_Policy_T
struct SocketReconnect_Policy_T
Configuration structure defining backoff policy, circuit breaker thresholds, and health check parameters for SocketReconnect_T.
This structure allows fine-tuning of the reconnection behavior:
Backoff Settings: Control retry timing with exponential growth and randomization
Circuit Breaker: Prevent connection storms after repeated failures
Health Monitoring: Periodic checks to detect connection degradation early
All fields are optional if using defaults via SocketReconnect_policy_defaults(). Invalid values (e.g., negative delays, multiplier <= 1.0) may raise SocketReconnect_Failed.
Field Documentation
See individual field comments for details. Recommended to start with defaults and tune based on application needs.
Default Values Table
Field Default Value Range/Notes
initial_delay_ms 100 >0, first retry delay
max_delay_ms 30000 > initial, cap for backoff
multiplier 2.0 >1.0, exponential factor
jitter 0.25 0.0-1.0, randomization %
max_attempts 10 >0 or 0=unlimited
circuit_failure_threshold 5 >0, consecutive fails to open
circuit_reset_timeout_ms 60000 >0, time to attempt recovery
health_check_interval_ms 30000 >0 or 0=disabled
health_check_timeout_ms 5000 >0, max block time for check
Usage Example
SocketReconnect_Policy_T policy;
SocketReconnect_policy_defaults(&policy);
// Customize for aggressive retry
policy.initial_delay_ms = 50;
policy.max_delay_ms = 10000;
policy.multiplier = 1.5;
policy.max_attempts = 0;  // Unlimited
SocketReconnect_T conn = SocketReconnect_new(host, port, &policy, NULL,
NULL);
Note
Changes take effect only at creation; recreate instance to apply new policy
Thread Safety\n Yes - plain struct, safe to initialize concurrently
Warning
Setting jitter=0 may cause thundering herd in multi-instance scenarios
See also
SocketReconnect_policy_defaults() Initialize with safe defaults
SocketReconnect_new() Apply policy during creation
Definition at line 362 of file SocketReconnect.h.
Data Fields
int circuit_failure_threshold Consecutive failures to trigger circuit open (default: 5). After this many rapid failures, enters CIRCUIT_OPEN state blocking further attempts. Helps prevent cascading failures during outages.
Note
Failures include connect errors and immediate post-connect issues.
int circuit_reset_timeout_ms Time in CIRCUIT_OPEN before attempting recovery probe (default: 60000ms / 60s). During this period, all connect() calls are ignored. After timeout, transitions to CONNECTING for one probe attempt.
Warning
Too short may retry into ongoing outage; too long delays recovery.
int health_check_interval_ms Interval between health checks when CONNECTED (default: 30000ms / 30s). 0 disables health checks entirely. Checks run via tick() or internal timer. Failed check triggers transition to BACKOFF.
Note
Overhead: Each check blocks briefly (up to health_check_timeout_ms).
int health_check_timeout_ms Maximum time a health check may block (default: 5000ms / 5s). Custom health callbacks must respect this limit to avoid DoS. Default check polls socket for readability.
Warning
Exceeding this may cause tick()/process() to hang.
int initial_delay_ms Initial delay before first retry after failure (default: 100ms). Must be positive (>0). This is the starting point for exponential backoff: delay = initial * (multiplier ^ attempt) +/- jitter.
Note
Too small values may overload the target during recovery.
double jitter Jitter factor for randomization (default: 0.25 / 25%). Adds +/- jitter * delay randomness to avoid synchronized retries (thundering herd). Range: 0.0 (no jitter) to 1.0 (full randomization).
Warning
Jitter=0 with multiple instances may cause retry storms.
int max_attempts Maximum retry attempts before permanent failure (default: 10). 0 means unlimited retries (use with caution to avoid infinite loops). Counts only connection attempts, not health check failures.
Note
Reset via SocketReconnect_reset() to retry indefinitely.
int max_delay_ms Maximum delay cap for backoff (default: 30000ms / 30s). Prevents unbounded growth. Actual delay clamped to this value.
Warning
Set higher than typical outage duration but low enough to meet SLA.
double multiplier Multiplier for exponential backoff (default: 2.0). New delay = previous * multiplier. Must be >1.0 for growth. Common values: 1.5 (aggressive), 2.0 (standard), 3.0 (conservative).
Note
Values <=1.0 will raise SocketReconnect_Failed.
Macro Definition Documentation
POOL_LOCK
#define POOL_LOCK (p)
Value:
  do                                                                          \
    {                                                                         \
      pthread_mutex_lock (&(p)->mutex);                                       \
    }                                                                         \
  while (0)
Acquire pool mutex.
Parameters
p Pool instance.
Convenience macro for consistent mutex locking across implementation files.
See also
POOL_UNLOCK for releasing the mutex.
pthread_mutex_lock() for underlying operation.
Definition at line 116 of file SocketPool-private.h.
POOL_UNLOCK
#define POOL_UNLOCK (p)
Value:
  do                                                                          \
    {                                                                         \
      pthread_mutex_unlock (&(p)->mutex);                                     \
    }                                                                         \
  while (0)
Release pool mutex.
Parameters
p Pool instance.
Convenience macro for consistent mutex unlocking across implementation files.
See also
POOL_LOCK for acquiring the mutex.
pthread_mutex_unlock() for underlying operation.
Definition at line 133 of file SocketPool-private.h.
RAISE_POOL_ERROR
#define RAISE_POOL_ERROR (exception)
Value:
  do                                                                          \
    {                                                                         \
      SocketPool_DetailedException = (exception);                             \
      SocketPool_DetailedException.reason = socket_error_buf;                 \
      RAISE (SocketPool_DetailedException);                                   \
    }                                                                         \
  while (0)
Raise exception with detailed error message.
Creates thread-local copy of exception with reason from socket_error_buf.
Thread Safety\n Prevents race conditions when multiple threads raise same
exception type. Used throughout SocketPool implementation.
See also
RAISE_POOL_MSG for formatted messages.
RAISE_POOL_FMT for errno-formatted messages.
SocketPool_Failed exception type.
Definition at line 220 of file SocketPool-private.h.
RAISE_POOL_FMT
#define RAISE_POOL_FMT (exception, fmt, ...)
Value:
  do                                                                          \
    {                                                                         \
      SOCKET_ERROR_FMT (fmt, ##__VA_ARGS__);                                  \
      RAISE_POOL_ERROR (exception);                                           \
    }                                                                         \
  while (0)
Format error message (with errno) and raise.
Combines SOCKET_ERROR_FMT + RAISE_POOL_ERROR for cleaner code.
Thread Safety\n Uses thread-local buffers.
See also
RAISE_POOL_MSG for non-errno messages.
RAISE_POOL_ERROR for direct exception raising.
Definition at line 257 of file SocketPool-private.h.
RAISE_POOL_MSG
#define RAISE_POOL_MSG (exception, fmt, ...)
Value:
  do                                                                          \
    {                                                                         \
      SOCKET_ERROR_MSG (fmt, ##__VA_ARGS__);                                  \
      RAISE_POOL_ERROR (exception);                                           \
    }                                                                         \
  while (0)
Format error message (without errno) and raise.
Combines SOCKET_ERROR_MSG + RAISE_POOL_ERROR for cleaner code.
Thread Safety\n Uses thread-local buffers.
See also
RAISE_POOL_FMT for errno-formatted messages.
RAISE_POOL_ERROR for direct exception raising.
Definition at line 239 of file SocketPool-private.h.
SOCKET_DEFAULT_IDLE_TIMEOUT
#define SOCKET_DEFAULT_IDLE_TIMEOUT 300 /* 5 minutes */
Default idle timeout.
See also
SocketPool_T for connection pool timeouts.
Definition at line 1433 of file SocketConfig.h.
SOCKET_DEFAULT_POOL_BUFSIZE
#define SOCKET_DEFAULT_POOL_BUFSIZE 8192
Default pool buffer size.
See also
SocketPool_T for connection pooling.
Definition at line 1596 of file SocketConfig.h.
SOCKET_DEFAULT_POOL_SIZE
#define SOCKET_DEFAULT_POOL_SIZE 1000
Default connection pool size.
See also
SocketPool_T for connection pooling.
Definition at line 1586 of file SocketConfig.h.
SOCKET_HASH_SIZE
#define SOCKET_HASH_SIZE SOCKET_HASH_TABLE_SIZE
Alias for the library's central hash table size configuration.
Reuses foundation::SOCKET_HASH_TABLE_SIZE (default: 1021, a prime number) for consistent hash table sizing across modules like pools, polls, DNS, and timers. This uniformity ensures predictable performance and collision characteristics.
Can be overridden at compile time via -DSOCKET_HASH_TABLE_SIZE=
.
Note
Prime table sizes minimize hash clustering and improve lookup efficiency.
Warning
Changing this may affect hash distribution; test thoroughly.
See also
SocketConfig.h::SOCKET_HASH_TABLE_SIZE for definition and rationale.
socketpool_hash() for SocketPool hash computation.
socket_util_hash_fd() and related functions in Utilities Module.
Foundation Module for core configs.
HASH_GOLDEN_RATIO constant in SocketUtil.h for hash multiplier.
Definition at line 167 of file SocketPool-private.h.
SOCKET_LOG_COMPONENT
#define SOCKET_LOG_COMPONENT "SocketPool"
Default log component for all SocketPool implementation files.
Overrides SOCKET_LOG_COMPONENT from SocketUtil.h for consistent logging. Each implementation file (.c) should not need to redefine this.
Definition at line 99 of file SocketPool-private.h.
SOCKET_PERCENTAGE_DIVISOR
#define SOCKET_PERCENTAGE_DIVISOR 100
Percentage divisor for calculations.
Definition at line 1638 of file SocketConfig.h.
SOCKET_POOL_DEFAULT_PREWARM_PCT
#define SOCKET_POOL_DEFAULT_PREWARM_PCT 20
Default pool prewarm percentage.
See also
SocketPool_T for connection pooling.
Definition at line 1606 of file SocketConfig.h.
SOCKET_POOL_MAX_ASYNC_PENDING
#define SOCKET_POOL_MAX_ASYNC_PENDING 1000
Maximum pending async connect operations per pool.
Prevents resource exhaustion from excessive concurrent connect attempts. Security: Limits memory consumption from async context allocations.
See also
SocketPool_T for connection pooling.
Definition at line 1629 of file SocketConfig.h.
SOCKET_POOL_MAX_BATCH_ACCEPTS
#define SOCKET_POOL_MAX_BATCH_ACCEPTS 1000
Maximum batch accepts per iteration.
See also
SocketPool_T for connection pooling.
Definition at line 1616 of file SocketConfig.h.
SOCKET_POOL_MAX_BURST_MULTIPLIER
#define SOCKET_POOL_MAX_BURST_MULTIPLIER 100
Maximum burst multiplier relative to rate.
Limits burst size to prevent memory exhaustion in rate limiter. Burst capacity = rate * multiplier.
See also
SocketPool_setconnrate() for rate limiting.
Definition at line 1685 of file SocketConfig.h.
SOCKET_POOL_MAX_CONNECTIONS_PER_IP
#define SOCKET_POOL_MAX_CONNECTIONS_PER_IP 10000
Maximum connections allowed per IP address.
Security limit to prevent single-source attacks via per-IP limiting. Generous default allows legitimate load balancers while limiting abuse.
See also
SocketPool_setmaxperip() for per-IP limiting.
SocketIPTracker_T for IP tracking implementation.
Definition at line 1699 of file SocketConfig.h.
SOCKET_POOL_MAX_RATE_PER_SEC
#define SOCKET_POOL_MAX_RATE_PER_SEC 1000000
Maximum rate limit value (connections per second).
Security limit to prevent resource exhaustion from overly permissive rate configurations. Practical upper bound for most servers.
See also
SocketPool_setconnrate() for rate limiting.
SocketRateLimit_T for token bucket implementation.
Definition at line 1672 of file SocketConfig.h.
SOCKET_POOL_STATS_WINDOW_SEC
#define SOCKET_POOL_STATS_WINDOW_SEC 60
Time window for pool statistics calculation.
See also
SocketPool_T for connection pooling.
Definition at line 1658 of file SocketConfig.h.
SOCKET_POOL_TOKENS_PER_ACCEPT
#define SOCKET_POOL_TOKENS_PER_ACCEPT 1
Tokens consumed per connection accept.
Number of rate limit tokens consumed per successful connection accept. Typically 1 for simple connection counting.
See also
SocketPool_accept_limited() for rate-limited accepting.
Definition at line 1712 of file SocketConfig.h.
SOCKET_RECONNECT_ERROR_BUFSIZE
#define SOCKET_RECONNECT_ERROR_BUFSIZE 256
Maximum buffer capacity for internal error message strings.
Defines the fixed size (including null terminator) for error_buf in SocketReconnect_T. Selected to fit detailed messages: errno description + connection context (host, port, attempt #).
Example capacity usage: "connection attempt 5 to host:port failed: [errno str] (err=123)"
Note
Avoids dynamic allocations in hot error paths; snprintf-safe size
Warning
Messages truncated if exceeding limit; prioritize essential info
See also
SocketReconnect_T::error_buf field
socketreconnect_error_fmt() internal formatting (in .c)
strerror() or Socket_safe_strerror() sources
Definition at line 137 of file SocketReconnect-private.h.
SOCKET_RECONNECT_MAX_HOST_LEN
#define SOCKET_RECONNECT_MAX_HOST_LEN 255
Maximum length for target hostname/IP strings (excluding null terminator).
Limits size of host field in SocketReconnect_T. Aligns with DNS max label length and accommodates IPv6 literals (e.g., "[2001:db8::1]"), Unix paths if extended.
Validation occurs at SocketReconnect_new(): truncates or raises exception if exceeded.
Note
255 chars +1 for null = 256 bytes allocated from arena
Excludes port; full URI not supported here
Warning
Longer hosts rejected to prevent buffer issues or DoS via oversized alloc
See also
SocketReconnect_T::host field storage
SocketReconnect_new() validation and copying
getaddrinfo() compatibility for resolution
Definition at line 163 of file SocketReconnect-private.h.
T [1/2]
#define T SocketPool_T
Core internal structure defining the complete SocketPool state.
High-level connection pool with lifecycle management.
Comprehensive state container for connection pooling, including pre-allocated slots, hash tables, rate limiters, SYN protection, drain logic, and statistics. Designed for thread-safe concurrent access with minimal contention.
CORE STRUCTURES:
connections[]: Fixed array of Connection slots (pre-allocated for performance)
hash_table[]: O(1) lookup by socket FD using socketpool_hash()
free_list: Linked free slots for rapid recycling
cleanup_buffer: Temp storage for bulk operations like idle cleanup
SYNCHRONIZATION:
mutex: pthread_mutex_t protects all mutable state except atomic fields
state: Atomic int for lock-free drain state reads (POOL_STATE* enums)
ASYNC OPERATIONS:
dns: Lazy-init SocketDNS_T for async resolution in connect_async()
async_ctx: Linked list of pending AsyncConnectContext_T
async_pending_count: Security limit on concurrent async operations
RESILIENCE FEATURES:
reconnect_policy: Default policy for SocketReconnect integration
conn_limiter: SocketRateLimit_T for global connection rate
ip_tracker: SocketIPTracker_T for per-IP limits
syn_protect: SocketSYNProtect_T for flood protection
GRACEFUL SHUTDOWN (DRAIN):
state: Atomic enum (RUNNING/DRAINING/STOPPED)
drain_deadline_ms: Monotonic timer for force-stop after timeout
drain_cb: Optional user notification on drain complete
CLEANUP & MONITORING:
idle_timeout_sec: Per-connection idle eviction
last_cleanup_ms / cleanup_interval_ms: Periodic maintenance scheduling
validation_cb: User-defined health checks before reuse
resize_cb: Notification on pool capacity changes
stats_*: Atomic counters for performance metrics (added/removed/reused/etc.)
stats_start_time_ms: Sliding window for rate calculations
THREAD SAFETY:
Mutex guards all operations except atomic state/count reads
Accessors (public API) acquire/release mutex transparently
Stats counters use atomic increments for concurrent updates
DNS callbacks execute in worker threads (user must handle synchronization)
MEMORY MANAGEMENT:
arena: Root allocator; all internal allocations (buffers, lists, trackers) from here
No manual free(); arena_clear() or dispose() handles bulk cleanup
Pre-warming allocates buffers proactively to reduce latency
CONFIGURATION ENFORCEMENT:
Limits clamped via socketpool_enforce_*() inline functions
Compile-time overrides via SocketConfig.h defines
Note
Atomic state enables non-blocking checks for draining/stopped conditions.
Warning
Avoid long-held locks in callbacks; prefer quick operations or defer work. @security Rate limiters and trackers prevent DoS; configure conservatively for prod. @performance Hash table size (SOCKET_HASH_SIZE) impacts lookup speed; tune if needed.
See also
SocketPool_T for public opaque typedef (in SocketPool.h).
struct Connection for per-connection state.
socketpool_enforce_range() family for param validation.
SocketPool_new() / SocketPool_free() for lifecycle.
SocketPool_resize() / SocketPool_prewarm() for dynamic sizing.
SocketPool_cleanup() for idle management.
SocketPool_drain() for graceful shutdown.
SocketPool_setconnrate() / SocketPool_setmaxperip() for limits.
Connection Management Modules for module overview and patterns.
foundation::Arena_T for memory model.
utilities::SocketRateLimit_T for rate limiting details.
Opaque type representing a pool of socket connections with automatic lifecycle management, rate limiting, SYN flood protection, and health monitoring.
See also
SocketPool_new() for creation.
SocketPool_add() for adding connections.
SocketPool_drain() for graceful shutdown.
SocketPool_setconnrate() for rate limiting.
SocketPool_set_syn_protection() for SYN flood protection.
Definition at line 524 of file SocketPool-private.h.
T [2/2]
#define T SocketPool_T
High-level connection pool with lifecycle management.
Opaque type representing a pool of socket connections with automatic lifecycle management, rate limiting, SYN flood protection, and health monitoring.
See also
SocketPool_new() for creation.
SocketPool_add() for adding connections.
SocketPool_drain() for graceful shutdown.
SocketPool_setconnrate() for rate limiting.
SocketPool_set_syn_protection() for SYN flood protection.
Definition at line 91 of file SocketPool.h.
Typedef Documentation
SocketPool_ConnectCallback
typedef void(* SocketPool_ConnectCallback) (Connection_T conn, int error, void *data)
Completion callback for async connections.
Parameters
conn Completed connection or NULL on error/failure.
error 0 on success, error code on failure.
[in] data User data from SocketPool_connect_async().
Called when async connection (DNS + connect + pool add) completes. Invoked from DNS worker thread - MUST be thread-safe.
THREAD SAFETY REQUIREMENTS:
MUST NOT access thread-local storage from main thread
MUST NOT call non-thread-safe functions without synchronization
Pool mutex is NOT held - MAY safely call other SocketPool functions
MAY call SocketPool_free() if connection failed
Safe patterns: mutex protection, atomic operations, work queueing, condition variables, self-pipes, event loop signaling.
Error codes: ENOTFOUND (DNS), ECONNREFUSED (connect), ETIMEDOUT (timeout), EHOSTUNREACH (routing), ECONNRESET (reset), or other socket errors.
See also
SocketPool_connect_async() for initiation.
SocketDNS_T for DNS resolution details.
async_dns for async DNS patterns.
SocketPool_ConnectCallback for callback requirements.
Definition at line 236 of file SocketPool.h.
SocketPool_DrainCallback
typedef void(* SocketPool_DrainCallback) (SocketPool_T pool, int timed_out, void *data)
Notification callback when drain completes.
Parameters
pool Pool instance that completed draining.
timed_out 1 if drain timed out (forced), 0 if graceful completion.
[in] data User data from SocketPool_set_drain_callback().
Called exactly once when pool transitions to STOPPED state. Safe to call SocketPool_free() from within this callback. Invoked from thread calling drain_poll/drain_wait.
See also
SocketPool_drain() for initiating drain.
SocketPool_set_drain_callback() for registration.
SocketPool_drain_poll() for non-blocking drain monitoring.
Definition at line 1170 of file SocketPool.h.
SocketPool_IdleCallback
typedef void(* SocketPool_IdleCallback) (Connection_T conn, void *data)
Callback invoked when a connection becomes idle.
Parameters
conn Connection that became idle.
[in] data User data from SocketPool_set_idle_callback().
Called when a connection transitions to idle state (e.g., after being returned to the pool or after activity timeout). Useful for connection monitoring, logging, or cleanup of per-connection state.
THREAD SAFETY REQUIREMENTS:
MAY be called from pool operations with pool mutex held
MUST NOT call SocketPool_add/remove/get (will deadlock)
SHOULD complete quickly (<1ms) to avoid blocking pool ops
MAY use Connection_* accessors safely
See also
SocketPool_set_idle_callback() for registration.
SocketPool_set_idle_timeout() for automatic idle cleanup.
Definition at line 187 of file SocketPool.h.
SocketPool_Predicate
typedef int(* SocketPool_Predicate) (Connection_T conn, void *data)
Predicate callback for filtering connections.
Parameters
conn Connection to test.
[in] data User data from SocketPool_find/filter().
Returns
Non-zero if connection matches criteria, 0 otherwise.
Used with SocketPool_find() and SocketPool_filter() to select connections based on custom criteria. Called with pool mutex held.
THREAD SAFETY REQUIREMENTS:
Called with pool mutex held - keep operations quick
MUST NOT call SocketPool_add/remove (will deadlock)
MAY use Connection_* accessors safely
See also
SocketPool_find() for finding first matching connection.
SocketPool_filter() for finding all matching connections.
Definition at line 207 of file SocketPool.h.
SocketPool_ResizeCallback
typedef void(* SocketPool_ResizeCallback) (SocketPool_T pool, size_t old_size, size_t new_size, void *data)
Callback invoked after pool resize.
Parameters
pool Pool instance that was resized.
old_size Previous maximum connection capacity.
new_size New maximum connection capacity.
[in] data User data from SocketPool_set_resize_callback().
Called after successful pool resize operations for monitoring/logging.
Thread Safety\n Yes - callback is invoked outside pool mutex.
See also
SocketPool_set_resize_callback() for registration.
SocketPool_resize() for resize operations.
Definition at line 165 of file SocketPool.h.
SocketPool_ValidationCallback
typedef int(* SocketPool_ValidationCallback) (Connection_T conn, void *data)
Callback to validate connection before reuse.
Parameters
conn Connection being validated for reuse.
[in] data User data from SocketPool_set_validation_callback().
Returns
Non-zero if connection is valid for reuse, 0 to remove it (forces removal from pool).
Called during SocketPool_get() before returning the connection to the caller. If returns 0, the connection is automatically removed from the pool and NULL is returned to the caller.
CRITICAL THREAD SAFETY REQUIREMENTS: The callback is invoked with the pool mutex held:
MUST NOT call any SocketPool_* functions (will cause deadlock)
MUST NOT call functions that acquire the pool mutex
MUST NOT block for extended periods (degrades pool performance for all users)
SHOULD complete in <1ms for optimal performance
MAY safely read via Connection_* accessors (thread-safe)
MAY perform quick socket health checks (e.g., poll(fd, 0 timeout))
Violating these may cause deadlocks or severe performance degradation. For complex validation:
Use a separate validation thread with async notification
Perform additional validation after SocketPool_get() returns
Rely on SocketPool_check_connection() for simple cases
Use for application-specific health checks beyond built-in validation.
See also
SocketPool_set_validation_callback() for registration.
SocketPool_check_connection() for built-in health checks.
SocketPool_get() for invocation context.
Connection Management Modules for connection management patterns.
Definition at line 148 of file SocketPool.h.
SocketReconnect_Callback
typedef void(* SocketReconnect_Callback) (SocketReconnect_T conn, SocketReconnect_State old_state, SocketReconnect_State new_state, void *userdata)
Callback invoked on reconnection state transitions for monitoring and custom logic.
Parameters
[in] conn The SocketReconnect_T instance changing state
[in] old_state State before the transition
[in] new_state State after the transition
[in] userdata User data provided at SocketReconnect_new()
This callback is invoked synchronously from the thread calling process(), tick(), or I/O functions that trigger state changes. Useful for:
Logging state transitions for debugging
Updating metrics (e.g., increment failure counters)
Triggering application-level actions (e.g., alert on CIRCUIT_OPEN)
Custom backoff adjustments (but avoid blocking)
Invocation Guarantees
Called exactly once per state transition
Non-reentrant: No nested calls from within callback
Short-lived: Should complete quickly to avoid delaying I/O processing
Usage Example
static void
state_change_cb(SocketReconnect_T conn, SocketReconnect_State old,
SocketReconnect_State new, void *ud) { const char *old_name =
SocketReconnect_state_name(old); const char *new_name =
SocketReconnect_state_name(new); SOCKET_LOG_INFO_MSG("Reconnect %p: %s ->
%s", conn, old_name, new_name);
    if (new == RECONNECT_CIRCUIT_OPEN) {
        // Alert or log outage
        // ud might be app context
    } else if (new == RECONNECT_CONNECTED) {
        // Resume operations
    }
}
// Register at creation
SocketReconnect_T conn = SocketReconnect_new(host, port, NULL,
state_change_cb, app_context);
Note
Do not call SocketReconnect_free(), connect(), or other mutating functions from within the callback to avoid recursion or use-after-free
Warning
Blocking operations (e.g., I/O, sleeps) in callback may stall the event loop
Thread Safety\n No - executes in caller's thread; ensure caller is
single-threaded per instance
See also
SocketReconnect_new() Register callback during creation
SocketReconnect_state() Query state directly
SocketReconnect_state_name() String names for logging
Definition at line 534 of file SocketReconnect.h.
SocketReconnect_HealthCheck
typedef int(* SocketReconnect_HealthCheck) (SocketReconnect_T conn, Socket_T socket, int timeout_ms, void *userdata)
Custom health check callback to verify connection liveness beyond basic connectivity.
Parameters
[in] conn Reconnection context performing the check
[in] socket Underlying connected Socket_T to test
[in] timeout_ms Maximum milliseconds to block/wait for the check; 0=non-blocking
[in] userdata User data from SocketReconnect_new() or set_health_check()
Returns
1 if healthy (connection responsive), 0 if unhealthy (triggers BACKOFF transition)
Invoked periodically (per policy.health_check_interval_ms) during CONNECTED state to proactively detect issues like high latency or partial failures. The check should verify application-level health if possible (e.g., ping endpoint, read heartbeat).
Requirements
Must complete within timeout_ms or risk blocking the event loop
Non-blocking preferred when timeout_ms=0
Return 0 on any failure to err on side of caution
Default: Polls socket for readability (detects dead peers)
Security Considerations
Respect timeout to prevent DoS from slow/malicious health checks
Avoid external calls (DNS, HTTP) that could be exploited
Use Socket_set_timeout() on socket if needed for check operations
Usage Example
static int
my_health_check(SocketReconnect_T conn, Socket_T sock, int timeout_ms, void
*ud) {
    // Simple ping: send heartbeat, expect response within timeout
    char ping[] = "PING";
    char buf[64];
    ssize_t sent = Socket_send(sock, ping, sizeof(ping)-1);
    if (sent < 0) return 0;
    struct pollfd pfd = { Socket_fd(sock), POLLIN, 0 };
    int ready = poll(&pfd, 1, timeout_ms);
    if (ready <= 0) return 0;  // Timeout or error
    ssize_t rcvd = Socket_recv(sock, buf, sizeof(buf)-1);
    return (rcvd > 0 && strncmp(buf, "PONG", 4) == 0);
}
// Set after creation
SocketReconnect_set_health_check(conn, my_health_check);
Warning
Exceeding timeout_ms may cause overall system hangs; always check time remaining
Note
Custom checks run in caller's thread; ensure non-blocking where possible
Thread Safety\n No - executes in tick()/process() caller's context
See also
SocketReconnect_set_health_check() Register custom check
SocketReconnect_Policy_T::health_check_interval_ms Control frequency
SocketReconnect_Policy_T::health_check_timeout_ms Set max block time
Definition at line 604 of file SocketReconnect.h.
Enumeration Type Documentation
SocketPool_ConnHealth
enum SocketPool_ConnHealth
Connection health status enumeration.
Enumerator
POOL_CONN_HEALTHY
Connection is healthy and usable
POOL_CONN_DISCONNECTED
Connection has been disconnected
POOL_CONN_ERROR
Connection has a socket error
POOL_CONN_STALE
Connection has exceeded max age
Definition at line 1397 of file SocketPool.h.
SocketPool_Health
enum SocketPool_Health
Health status for load balancer integration.
Enumerator
POOL_HEALTH_HEALTHY
Accept traffic normally
POOL_HEALTH_DRAINING
Finishing existing connections, reject new
POOL_HEALTH_STOPPED
Not accepting any traffic
Definition at line 1148 of file SocketPool.h.
SocketPool_State
enum SocketPool_State
Pool lifecycle states for graceful shutdown.
Enumerator
POOL_STATE_RUNNING
Normal operation - accepting connections
POOL_STATE_DRAINING
Rejecting new, waiting for existing to close
POOL_STATE_STOPPED
Fully stopped - safe to free
Definition at line 1137 of file SocketPool.h.
SocketReconnect_CircuitState
enum SocketReconnect_CircuitState
Internal circuit breaker states for reconnection resilience.
Manages the circuit breaker pattern to prevent connection storms and cascading failures during service outages. Provides three internal states that map to public SocketReconnect_State behaviors but allow precise control over transitions.
State Descriptions
State Description Behavior
CIRCUIT_CLOSED Normal operation Allows all connection attempts;
failures increment counters | | CIRCUIT_OPEN | Protection mode | Blocks attempts after failure threshold; waits for reset timeout | | CIRCUIT_HALF_OPEN | Probe mode | Permits one probe connection; success closes circuit, failure re-opens |
Transitions
CLOSED OPEN: Consecutive failures reach policy.circuit_failure_threshold
OPEN HALF_OPEN: Timeout expires (policy.circuit_reset_timeout_ms)
HALF_OPEN CLOSED: Probe connection succeeds
HALF_OPEN OPEN: Probe fails
CLOSED CLOSED: Successful connections reset failure counters
Transitions are atomic and handled internally by the state machine.
Usage
Accessed only via SocketReconnect_T::circuit_state. Never set directly from outside the module. Public API reflects these states through SocketReconnect_State.
Complexity\n O(1) for state checks and transitions
Thread Safety\n Internal - modifications protected by reconnect instance logic
Note
Resets to CLOSED on SocketReconnect_reset()
Warning
Manipulating directly may cause inconsistent state or infinite loops
See also
SocketReconnect_State for public state view
SocketReconnect_T::circuit_state for storage
SocketReconnect_Policy_T::circuit_failure_threshold configuration
Enumerator
CIRCUIT_CLOSED
Normal operation: connections allowed, failures tracked
CIRCUIT_OPEN
Blocked: too many consecutive failures, waiting timeout
CIRCUIT_HALF_OPEN
Probe allowed: single connection attempt to test recovery
Definition at line 218 of file SocketReconnect-private.h.
SocketReconnect_State
enum SocketReconnect_State
States of the reconnection state machine for tracking connection lifecycle and backoff status.
The state machine transitions as follows:
DISCONNECTED: Idle state, ready for connect() or after graceful disconnect
CONNECTING: Active connection attempt in progress (non-blocking connect)
CONNECTED: Successfully established and healthy connection
BACKOFF: Waiting exponential delay before next retry after failure
CIRCUIT_OPEN: Circuit breaker tripped, blocking attempts until reset timeout
Transitions are triggered by connect(), process(), tick(), send/recv errors, health checks, and timeouts.
State Transition Diagram
+-------------+     connect()     +-------------+
| DISCONNECTED| ----------------> | CONNECTING  |
+-------------+                  +-------------+
     ^                                   |
     | disconnect()                      | success/fail
     |                                   v
+-------------+    timeout/error    +-------------+    health fail
| CIRCUIT_OPEN| <-------------------|   BACKOFF   | <-------------- |
+-------------+                     +-------------+                 |
     ^                                             |                |
     | timeout                                     |                |
     |                                             |                |
     +--------------------------- reset() ---------+                |
                                                            failure |
                                                             |     |
                                                             v     |
                                                      +-------------+
                                                      | CONNECTED   |
                                                      +-------------+
                                                             |
                                                        send/recv |
                                                             |
                                                      disconnect() |
                                                             v
                                                      DISCONNECTED
State Properties Table
State Description pollfd() send/recv Actions
DISCONNECTED Not connected, idle -1 Block/0 connect() starts
transition CONNECTING Non-blocking connect in progress Valid FD
Block | process() completes | | CONNECTED | Active connection | Valid FD | Available | Errors trigger BACKOFF | | BACKOFF | Exponential wait | -1 | Block | tick() advances timer | | CIRCUIT_OPEN | Breaker open, no attempts | -1 | Block | tick() resets after timeout |
Note
Use SocketReconnect_state_name() for logging/debugging state strings
Warning
Avoid direct state manipulation; use public API functions
See also
SocketReconnect_state() Query current state
SocketReconnect_state_name() Human-readable names
SocketReconnect_Callback() For state change notifications
Enumerator
RECONNECT_DISCONNECTED
Not connected, not attempting
RECONNECT_CONNECTING
Connection attempt in progress
RECONNECT_CONNECTED
Successfully connected
RECONNECT_BACKOFF
Waiting before retry (exponential backoff)
RECONNECT_CIRCUIT_OPEN
Circuit breaker open, blocking attempts
Definition at line 289 of file SocketReconnect.h.
Function Documentation
check_pool_full()
int check_pool_full (const SocketPool_T pool) extern
Check if pool has reached maximum capacity.
Parameters
pool Pool instance.
Returns
Non-zero if pool is full, 0 if slots available.
Fast check without acquiring locks.
See also
SocketPool_add() for capacity enforcement.
Connection_created_at()
time_t Connection_created_at (const Connection_T conn) extern
Get connection creation timestamp.
Parameters
[in] conn Connection instance.
Returns
Creation timestamp as time_t.
Thread Safety\n Yes.
See also
Connection_lastactivity() for last activity time.
Connection_data()
void * Connection_data (const Connection_T conn) extern
Get connection's user data.
Parameters
[in] conn Connection instance.
Returns
User data pointer.
Thread Safety\n Yes - read-only accessor.
See also
Connection_setdata() for setting user data.
Connection_has_reconnect()
int Connection_has_reconnect (const Connection_T conn) extern
Check if connection has auto-reconnect enabled.
Parameters
[in] conn Connection instance.
Returns
Non-zero if auto-reconnect is enabled.
Thread Safety\n Yes.
See also
SocketPool_enable_reconnect() to enable reconnection.
Connection_reconnect() to get context.
Connection_inbuf()
SocketBuf_T Connection_inbuf (const Connection_T conn) extern
Get connection's input buffer.
Parameters
[in] conn Connection instance.
Returns
Input buffer for reading data.
Thread Safety\n Yes - read-only accessor.
See also
Connection_outbuf() for output buffer.
SocketBuf_T for buffer operations.
Referenced by main().
Connection_isactive()
int Connection_isactive (const Connection_T conn) extern
Check if connection is active.
Parameters
[in] conn Connection instance.
Returns
Non-zero if connection is active.
Thread Safety\n Yes - read-only accessor.
See also
SocketPool_get() for automatic activity timestamp updates.
SocketPool_cleanup() for inactive connection removal.
Referenced by is_idle_connection().
Connection_lastactivity()
time_t Connection_lastactivity (const Connection_T conn) extern
Get connection's last activity timestamp.
Parameters
[in] conn Connection instance.
Returns
Last activity time as time_t.
Thread Safety\n Yes - read-only accessor.
See also
Connection_created_at() for creation timestamp.
SocketPool_cleanup() for idle connection removal.
Connection_outbuf()
SocketBuf_T Connection_outbuf (const Connection_T conn) extern
Get connection's output buffer.
Parameters
[in] conn Connection instance.
Returns
Output buffer for writing data.
Thread Safety\n Yes - read-only accessor.
See also
Connection_inbuf() for input buffer.
SocketBuf_T for buffer operations.
Referenced by main().
Connection_reconnect()
SocketReconnect_T Connection_reconnect (const Connection_T conn) extern
Get reconnection context for connection.
Parameters
[in] conn Connection instance.
Returns
SocketReconnect_T context, or NULL if reconnection not enabled.
Thread Safety\n Yes - returned context is not thread-safe.
See also
Connection_has_reconnect() to check if enabled.
SocketPool_enable_reconnect() to enable reconnection.
Connection_setdata()
void Connection_setdata (Connection_T conn, void * data) extern
Set connection's user data.
Parameters
conn Connection_T instance (must not be NULL).
data void* data pointer to store (may be NULL).
Thread Safety\n No - requires external synchronization for concurrent access.
Note
Other Connection_* accessors are thread-safe, but this modifies state.
Data is not freed automatically - caller responsible for cleanup.
Warning
Concurrent calls to Connection_setdata() without synchronization will cause data races. Use mutex or atomic operations if needed.
See also
Connection_data() for reading user data.
Connection_T for connection management.
Connection_socket()
Socket_T Connection_socket (const Connection_T conn) extern
Get connection's socket.
Parameters
conn Connection_T instance (must not be NULL).
Returns
Associated Socket_T (never NULL for valid connections).
Thread Safety\n Yes - read-only accessor, no synchronization needed.
Note
Socket remains valid until connection is removed from pool.
See also
Connection_inbuf() and Connection_outbuf() for buffer access.
Connection_data() for user data access.
Socket_T for socket operations.
Socket_fd() for getting file descriptor.
Referenced by main(), and simulate_work_wrapper().
decrement_pool_count()
void decrement_pool_count (SocketPool_T pool) extern
Decrement active connection count.
Parameters
pool Pool instance.
Thread-safe decrement of pool's active connection counter.
See also
increment_pool_count() for reverse operation.
find_free_slot()
Connection_T find_free_slot (const SocketPool_T pool) extern
Find first available free connection slot.
Parameters
pool Pool instance.
Returns
Free connection slot or NULL if pool is full.
Scans free list to find available slot for new connections.
See also
SocketPool_add() for usage.
check_pool_full() for pool capacity checking.
remove_from_free_list() for slot activation.
return_to_free_list() for slot deactivation.
find_or_create_slot()
Connection_T find_or_create_slot (SocketPool_T pool, Socket_T socket, time_t now) extern
Find existing connection or create new slot.
Parameters
pool Pool instance.
socket Socket to find or add.
now Current timestamp.
Returns
Existing connection or new slot, NULL if pool full.
Core function for SocketPool_get() and SocketPool_add().
See also
SocketPool_get() for lookup-only.
SocketPool_add() for add-only.
find_slot()
Connection_T find_slot (SocketPool_T pool, const Socket_T socket) extern
Find connection slot by socket (internal).
Parameters
pool Pool instance.
socket Socket to find.
Returns
Connection slot or NULL if not found.
Performs O(1) hash table lookup to find existing connection.
See also
SocketPool_get() for public interface.
insert_into_hash_table() for insertion.
remove_from_hash_table() for removal.
socketpool_hash() for hash computation.
increment_pool_count()
void increment_pool_count (SocketPool_T pool) extern
Increment active connection count.
Parameters
pool Pool instance.
Thread-safe increment of pool's active connection counter.
See also
decrement_pool_count() for reverse operation.
initialize_connection()
void initialize_connection (Connection_T conn, Socket_T socket, time_t now) extern
Initialize connection with socket and timestamp.
Parameters
conn Connection to initialize.
socket Socket for connection.
now Current timestamp.
Sets up connection with socket, timestamps, and initial state.
See also
prepare_free_slot() for buffer allocation.
insert_into_hash_table()
void insert_into_hash_table (SocketPool_T pool, Connection_T conn, Socket_T socket) extern
Insert connection into hash table.
Parameters
pool Pool instance.
conn Connection to insert.
socket Socket for hash computation.
Inserts connection into hash table for O(1) lookup.
See also
remove_from_hash_table() for removal.
socketpool_hash() for hash computation.
prepare_free_slot()
int prepare_free_slot (SocketPool_T pool, Connection_T conn) extern
Prepare free slot for new connection.
Parameters
pool Pool instance.
conn Free slot to prepare.
Returns
0 on success, -1 on buffer allocation failure.
Cleans up old connection state and allocates new buffers.
See also
initialize_connection() for connection setup.
reconnect_jitter()
static double reconnect_jitter (void) static
Generate uniform random double in [0.0, 1.0) for jitter in backoff calculations.
Produces randomness for exponential backoff jitter to avoid thundering herd (synchronized retries). Prioritizes secure crypto RNG, falls back to fast thread-local PRNG for performance.
Returns
double uniformly distributed in [0.0, 1.0)
Usage in Backoff
Jitter applied as: delay *= (1.0 + jitter_factor * (2*rand - 1)) Where jitter_factor from policy (0.0-1.0).
double r = socketreconnect_random_double();
int64_t jittered_delay = base_delay * (1.0 + policy.jitter * (2*r - 1.0));
Implementation Details
Primary: SocketCrypto_random_bytes() for 32-bit uint normalized double
Fallback: Thread-local xorshift32 PRNG, seeded once by monotonic time
xorshift: seed ^= seed <<13; ^= >>17; ^= <<5
Period: 2^32 -1; good for non-crypto use
Secure source preferred but not required; fallback ensures availability.
Complexity\n O(1) amortized - crypto may block briefly, PRNG instant
Thread Safety\n Yes - crypto reentrant, PRNG per-thread (__thread static)
Note
Fallback seeded lazily on first call per thread
Warning
NON-CRYPTO: Do not use for keys, nonces, or security decisions
Note
If crypto fails (e.g., /dev/urandom unavailable), logs warning internally
See also
SocketCrypto_random_bytes() primary secure source
SocketReconnect_Policy_T::jitter usage context
xorshift algorithm for PRNG details
Definition at line 560 of file SocketReconnect-private.h.
References Socket_get_monotonic_ms(), and SocketCrypto_random_bytes().
remove_from_free_list()
void remove_from_free_list (SocketPool_T pool, Connection_T conn) extern
Remove connection from free list.
Parameters
pool Pool instance.
conn Connection to remove from free list.
Updates free list pointers when slot becomes active.
See also
return_to_free_list() for reverse operation.
remove_from_hash_table()
void remove_from_hash_table (SocketPool_T pool, Connection_T conn, Socket_T socket) extern
Remove connection from hash table.
Parameters
pool Pool instance.
conn Connection to remove.
socket Socket for hash computation.
Removes connection from hash table during cleanup/removal.
See also
insert_into_hash_table() for insertion.
return_to_free_list()
void return_to_free_list (SocketPool_T pool, Connection_T conn) extern
Return connection to free list.
Parameters
pool Pool instance.
conn Connection to return to free list.
Updates free list pointers when slot becomes inactive.
See also
remove_from_free_list() for reverse operation.
safe_time()
time_t safe_time (void) extern
Get current time with error handling.
Returns
Current time as time_t.
Exceptions
SocketPool_Failed on system error.
Thread Safety\n Yes.
Safe wrapper around time() that raises exception on failure. Used for connection timestamps and idle timeout tracking.
See also
Connection_lastactivity() for usage.
Connection_created_at() for creation timestamps.
SocketPool_accept_allowed()
int SocketPool_accept_allowed (SocketPool_T pool, const char * client_ip) extern
Check if accepting is allowed.
Parameters
[in] pool Pool instance.
client_ip Client IP address (NULL to skip IP check).
Returns
1 if allowed, 0 if rate limited or IP limit reached.
Thread Safety\n Yes.
Checks both connection rate and per-IP limits. Does NOT consume rate limit tokens - use SocketPool_accept_limited() for that.
See also
SocketPool_accept_limited() for actual accepting with rate limiting.
SocketPool_accept_batch()
int SocketPool_accept_batch (SocketPool_T pool, Socket_T server, int max_accepts, size_t accepted_capacity, Socket_T * accepted) extern
Accept multiple connections from server socket.
Parameters
[in] pool Pool instance.
server Server socket (listening, non-blocking).
max_accepts Maximum number to accept (1 to SOCKET_POOL_MAX_BATCH_ACCEPTS).
accepted_capacity Size of accepted array (must be >= max_accepts).
[out] accepted Output array for accepted Socket_T pointers (caller-allocated).
Returns
Number accepted (0 to max_accepts).
Exceptions
SocketPool_Failed on error.
Thread Safety\n Yes.
Efficient batch accept using accept4() where available. Automatically adds accepted sockets to pool.
CALLER RESPONSIBILITY: The accepted array MUST be pre-allocated with at least max_accepts elements. No bounds checking - undersized array causes overflow.
Safe usage: Socket_T accepted[100]; int count = SocketPool_accept_batch(pool, server, 100, 100, accepted);
See also
SocketPool_accept_limited() for rate-limited single accept.
SocketPool_accept_protected() for SYN protection.
SocketPool_accept_limited()
Socket_T SocketPool_accept_limited (SocketPool_T pool, Socket_T server) extern
Accept connection with rate limiting.
Parameters
[in] pool Pool instance.
server Server Socket_T to accept from (must be listening).
Returns
Socket_T or NULL if draining/stopped, rate limited, or accept failed.
Thread Safety\n Yes - acquires pool mutex internally.
Comprehensive accept function combining multiple protection mechanisms:
Returns NULL immediately if pool is draining or stopped
Consumes rate token before attempting accept
If per-IP limiting enabled, automatically tracks client IP
On SocketPool_add failure, caller MUST call SocketPool_release_ip() and Socket_free()
FAILURE MODES:
Pool draining/stopped: Returns NULL immediately
Rate limited: Returns NULL, no tokens consumed
IP limit reached: Returns NULL, tracked IP remains blocked
Accept failed: Returns NULL (network error)
Pool full: Returns Socket_T but SocketPool_add() returns NULL
See also
SocketPool_setconnrate() to configure rate limits.
SocketPool_setmaxperip() for per-IP limits.
SocketPool_accept_protected() for SYN protection.
SocketPool_release_ip() for cleanup on SocketPool_add() failure.
Socket_free() for socket cleanup.
utilities::SocketRateLimit_T for token bucket implementation.
SocketPool_accept_protected()
Socket_T SocketPool_accept_protected (SocketPool_T pool, Socket_T server, SocketSYN_Action * action_out) extern
Accept with full SYN flood protection.
Parameters
[in] pool Pool instance.
server Server socket (listening, non-blocking).
action_out Output - action taken (optional, may be NULL).
Returns
New socket if allowed, NULL if blocked/would block.
Exceptions
SocketPool_Failed on actual errors (not protection blocking).
Thread Safety\n Yes.
Combines rate limiting, per-IP limits, and SYN protection into a single accept operation. Actions taken depend on SYN protection result:
SYN_ACTION_ALLOW: Accept normally (fastest path)
SYN_ACTION_THROTTLE: Accept after artificial delay (congestion control)
SYN_ACTION_CHALLENGE: Set TCP_DEFER_ACCEPT on socket (require data)
SYN_ACTION_BLOCK: Close connection immediately, return NULL
If SYN protection is not enabled, behaves like SocketPool_accept_limited().
Reports success/failure to SYN protection module automatically based on whether connection completes or fails.
SocketPool_add()
Connection_T SocketPool_add (SocketPool_T pool, Socket_T socket) extern
Add a connected socket to the pool, creating a Connection_T wrapper.
Parameters
[in] pool Pool instance.
[in] socket Connected Socket_T (must not be NULL or already in pool).
Returns
Connection_T wrapper or NULL if pool full, socket invalid, or allocation failed.
Exceptions
SocketPool_Failed on invalid parameters or internal allocation failures.
Thread Safety\n Yes - acquires pool mutex internally.
Allocates per-connection I/O buffers, initializes metadata (timestamps, user data = NULL), adds to hash table for O(1) lookup, and increments active count/statistics.
Failure cases:
Pool at capacity: Returns NULL (no exception)
Socket already in pool: Returns NULL (no exception)
Invalid socket (not connected): Returns NULL (no exception)
Allocation failure: Raises SocketPool_Failed
Mutex deadlock (rare): Raises SocketPool_Failed
Usage Example
Socket_T client_sock = Socket_accept(server_sock);
if (client_sock != NULL) {
    TRY {
        Connection_T conn = SocketPool_add(pool, client_sock);
        if (conn != NULL) {
            // Connection successfully added - use conn->socket, buffers,
etc. Connection_setdata(conn, my_user_data); } else {
            // Pool full or invalid - close socket
            Socket_free(&client_sock);
        }
    } EXCEPT (SocketPool_Failed) {
        // Allocation or param error - cleanup
        Socket_free(&client_sock);
    } END_TRY;
}
Note
Socket must be connected and valid before adding.
Buffers are allocated from pool's arena - share lifecycle with pool.
Warning
Do not add the same socket twice - results in undefined behavior.
Complexity\n O(1) average - hash insertion, buffer allocation is amortized
constant
See also
SocketPool_get() for looking up connections by socket.
SocketPool_remove() for removing connections.
SocketPool_accept_limited() for rate-limited server accepting.
SocketPool_resize() for changing pool capacity.
SocketPool_count() for current connection statistics.
Connection_T for connection wrapper details.
Referenced by main(), and main().
SocketPool_check_connection()
SocketPool_ConnHealth SocketPool_check_connection (SocketPool_T pool, Connection_T conn) extern
Check health of a connection.
Parameters
[in] pool Pool instance.
conn Connection to check.
Returns
Health status of the connection.
Thread Safety\n Yes.
Checks:
Socket is still connected (SO_ERROR check)
Socket is not in error state
Connection has not exceeded idle timeout.
See also
SocketPool_ConnHealth for health status values.
SocketPool_set_validation_callback() for custom validation.
SocketPool_cleanup()
void SocketPool_cleanup (SocketPool_T pool, time_t idle_timeout) extern
Remove idle connections.
Parameters
[in] pool Pool instance.
idle_timeout Seconds inactive before removal (0 = remove all).
Thread Safety\n Yes.
Note
O(n) scan of all slots; closes/removes idle ones.
See also
SocketPool_count() for counting connections.
SocketPool_set_idle_timeout() for configuring timeout.
Referenced by main().
SocketPool_connect_async()
Request_T SocketPool_connect_async (SocketPool_T pool, const char * host, int port, SocketPool_ConnectCallback callback, void * data) extern
Create async connection to remote host.
Parameters
[in] pool Pool instance.
host Remote hostname or IP address.
port Remote port number (1-65535).
callback Completion callback (see SocketPool_ConnectCallback).
[in] data User data passed to callback.
Returns
Request_T (DNS request handle) for monitoring completion.
Exceptions
SocketPool_Failed on invalid params, allocation error, or limit reached.
Thread Safety\n Yes.
Starts async DNS resolution + connect + pool add. On completion:
Success: callback(conn, 0, data) with Connection_T added to pool
Failure: callback(NULL, error_code, data)
Callback invoked from DNS worker thread - see SocketPool_ConnectCallback for thread safety requirements. Limited to SOCKET_POOL_MAX_ASYNC_PENDING concurrent operations for security.
See also
SocketPool_prepare_connection() for lower-level control.
SocketPool_ConnectCallback for callback requirements.
SocketDNS_T for DNS resolution details.
SocketPool_add() for adding completed connections to pool.
SocketPool_connections_alloc_buffers()
int SocketPool_connections_alloc_buffers (Arena_T arena, size_t bufsize, Connection_T conn) extern
Allocate input/output buffers for connection.
Parameters
arena Memory arena for allocation.
bufsize Size of each buffer.
conn Connection to allocate buffers for.
Returns
0 on success, -1 on allocation failure.
Allocates SocketBuf_T instances for connection's input and output buffers.
See also
SocketPool_new() for buffer allocation.
SocketBuf_new() for buffer creation.
SocketPool_connections_release_buffers() for cleanup.
Connection_inbuf() and Connection_outbuf() for access.
SocketPool_connections_initialize_slot()
void SocketPool_connections_initialize_slot (struct Connection * conn) extern
Allocate and zero-initialize array of connection structures.
Pre-allocates fixed-size array of Connection structs for efficient pool slot management. Uses direct system calloc() for large arrays to avoid arena fragmentation and overhead. All slots are zero-initialized, ready for SocketPool_connections_initialize_slot().
Parameters
[in] maxconns Number of Connection slots to allocate (enforced 1 to SOCKET_MAX_CONNECTIONS).
Returns
Pointer to allocated and zeroed array.
Exceptions
SocketPool_Failed if calloc() fails due to ENOMEM or system limits.
Thread Safety\n Yes - no shared state, pure allocation function.
Complexity\n O(maxconns) time and space - allocates and memset-zeros the
entire array.
Internal Usage Pattern
// Called during SocketPool_new() after parameter validation
TRY {
  pool->connections = SocketPool_connections_allocate_array(safe_maxconns);
  // Success: array allocated and zeroed
} EXCEPT(SocketPool_Failed) {
  // Handle allocation failure (e.g., log, propagate)
  RERAISE;  // Or clean up and return error
} END_TRY;
Error Handling
Allocation failure typically indicates:
System memory exhaustion (ulimit -v exceeded)
Process memory limits reached
Kernel OOM killer intervention imminent
Note
Direct calloc() allocation - not managed by pool arena. Freed explicitly with free() in SocketPool_free().
Warning
Avoid calling with very large maxconns (>1M) without checking system limits (e.g., via getrlimit(RLIMIT_AS)).
Zero-initialization ensures safe default state but does not initialize buffers or complex fields - use initialize_slot().
See also
socketpool_enforce_max_connections() for parameter clamping.
SocketPool_new() for full pool creation context.
SocketPool_connections_initialize_slot() for post-allocation slot setup (links free list, etc.).
SocketPool_free() for explicit free() of this array.
calloc(3) for underlying POSIX allocation primitive.
foundation::Arena_T for arena-based alternatives (used for other components).
Allocate and zero-initialize hash table array from arena.
Allocates fixed-size array of Connection_T* pointers for O(1) average-case connection lookup. Uses arena-managed CALLOC for integration with pool's memory lifecycle. All entries zero-initialized (NULL), ready for insert_into_hash_table(). Table size fixed to SOCKET_HASH_SIZE (compile-time prime for low collisions).
Parameters
[in] arena Arena_T for allocation (must not be NULL).
Returns
Pointer to allocated and zeroed hash table array.
Exceptions
SocketPool_Failed if Arena_calloc() fails (Arena_Failed wrapped).
Arena_Failed if arena has insufficient space (propagates through wrapper).
Thread Safety\n No - arena allocation not thread-safe without external
synchronization. Caller must ensure exclusive arena access or use thread-local arenas.
Complexity\n O(1) time and space - fixed-size allocation independent of pool
size.
Internal Usage Pattern
// Called during SocketPool_new() in allocate_pool_components()
TRY {
  pool->hash_table =
SocketPool_connections_allocate_hash_table(pool->arena);
  // Success: hash_table ready for insertions
} EXCEPT(SocketPool_Failed | Arena_Failed) {
  // Handle: log, cleanup partial allocations, propagate exception
  RERAISE;
} END_TRY;
Allocation Details
Size: SOCKET_HASH_SIZE * sizeof(Connection_T*) (typically ~8KB for 1021 entries)
Zero-initialized: All buckets NULL, no chaining needed initially
Arena-managed: Freed automatically via Arena_clear/dispose in SocketPool_free
Note
Fixed size at compile-time - override via -DSOCKET_HASH_SIZE=N (prime recommended).
Warning
Small table sizes increase collision chains, degrading to O(n) worst-case lookup.
Arena exhaustion may occur if pool creation coincides with high memory pressure.
See also
SOCKET_HASH_SIZE in SocketConfig.h for configuration and rationale.
socketpool_hash() for FD-based hashing into table buckets.
insert_into_hash_table() / remove_from_hash_table() for chain management.
find_slot() for traversal of collision chains.
foundation::Arena_T::Arena_calloc() for underlying allocation (via CALLOC macro).
utilities::socket_util_hash_fd() for hash function implementation.
Initialize a connection slot to default state.
Parameters
conn Connection structure to initialize.
Zeroes all fields and sets up initial state for a connection slot.
See also
SocketPool_connections_reset_slot() for cleanup.
SocketPool_connections_allocate_array() for allocation.
find_free_slot() for finding available slots.
SocketPool_connections_reset_slot()
void SocketPool_connections_reset_slot (Connection_T conn) extern
Securely clear (zero) connection's input/output buffers.
Performs secure zeroing of buffer contents using SocketBuf_secureclear(). Used before buffer reuse (to erase sensitive data) or final disposal. Does NOT deallocate memory (arena-managed) or NULL pointers - only clears data. Callers typically follow with SocketBuf_release(&conn->inbuf) if deallocating.
Parameters
[in,out] conn Connection whose buffers to securely clear.
Thread Safety\n Yes - individual buffer operations are atomic/thread-safe.
Complexity\n O(bufsize) - linearly scans and zeros buffer contents (inbuf +
outbuf).
Usage for Buffer Reuse
// Before reusing existing buffers in prepare_free_slot()
if (buffers_exist(conn)) {
  SocketPool_connections_release_buffers(conn);  // Zero sensitive data
  // Buffers now safe for reuse, pointers still valid
} else {
  SocketPool_connections_alloc_buffers(arena, bufsize, conn);
}
Usage for Final Cleanup
// In SocketPool_connections_reset_slot() or removal
SocketPool_connections_release_buffers(conn);  // Zero data
SocketBuf_release(&conn->inbuf);               // NULL pointer
SocketBuf_release(&conn->outbuf);              // NULL pointer
Note
Arena-managed buffers: Memory freed only on Arena_clear/dispose().
Warning
Secure clearing prevents data leaks (e.g., passwords, tokens) on reuse/disposal.
Does not NULL pointers - use SocketBuf_release() for that (sets buf = NULL).
See also
SocketBuf_secureclear() for underlying zeroing primitive (handles circular buffer semantics).
SocketPool_connections_alloc_buffers() for buffer allocation.
SocketBuf_release() for pointer nullification (post-clearing).
SocketPool_connections_reset_slot() for full slot reset including buffers.
core_io::SocketBuf_T for buffer lifecycle management.
Reset connection slot to clean state.
Parameters
conn Connection slot to reset.
Clears all fields and prepares slot for reuse.
See also
SocketPool_connections_initialize_slot() for initial setup.
SocketPool_count()
size_t SocketPool_count (SocketPool_T pool) extern
Get active connection count.
Parameters
[in] pool Pool instance.
Returns
Number of active connections.
Thread Safety\n Yes.
See also
SocketPool_resize() for changing capacity.
SocketPool_cleanup() for removing idle connections.
Referenced by main(), and main().
SocketPool_disable_reconnect()
void SocketPool_disable_reconnect (SocketPool_T pool, Connection_T conn) extern
Disable auto-reconnect for a connection.
Parameters
[in] pool Pool instance.
conn Connection to disable reconnection for.
Thread Safety\n Yes.
Disables automatic reconnection for the specified connection.
See also
SocketPool_enable_reconnect() for enabling reconnection.
SocketPool_drain()
void SocketPool_drain (SocketPool_T pool, int timeout_ms) extern
Initiate graceful shutdown.
Parameters
[in] pool Pool instance.
timeout_ms Maximum time to wait for connections to close (milliseconds). Use 0 for immediate force-close, -1 for infinite wait.
Thread Safety\n Yes - atomic state transitions.
Note
Transitions pool from RUNNING to DRAINING state.
Rejects new connections, allows existing to close naturally.
Force-closes remaining connections after timeout.
Multiple calls are idempotent - extends timeout if already draining.
STATE TRANSITIONS:
RUNNING -> DRAINING: Start rejecting new connections
DRAINING -> STOPPED: When all connections closed or timeout reached
STOPPED: Final state, pool can be safely freed
See also
SocketPool_drain_poll() for non-blocking completion.
SocketPool_drain_wait() for blocking completion.
SocketPool_drain_force() for immediate shutdown.
SocketPool_state() to check current state.
SocketPool_State for state definitions.
SocketPool_DrainCallback for completion notifications.
Referenced by main(), and main().
SocketPool_drain_force()
void SocketPool_drain_force (SocketPool_T pool) extern
Force immediate shutdown.
Parameters
[in] pool Pool instance.
Thread Safety\n Yes.
Note
Complexity: O(n) where n = active connections.
Immediately closes all connections and transitions to STOPPED. Can be called at any time, regardless of current state. Invokes drain callback with timed_out=1.
Logs: "Pool drain forced" at WARN level.
See also
SocketPool_drain() for graceful shutdown.
Referenced by main().
SocketPool_drain_poll()
int SocketPool_drain_poll (SocketPool_T pool) extern
Poll drain progress (non-blocking).
Parameters
[in] pool Pool instance.
Returns
>0 active connections (keep polling), 0 graceful completion, -1 timeout.
Thread Safety\n Yes.
Call periodically to check drain progress and trigger force-close on timeout. Invokes drain callback on completion. If not draining, returns current count.
See also
SocketPool_drain() to initiate drain.
SocketPool_drain_wait() for blocking version.
SocketPool_drain_remaining_ms() for timeout info.
Referenced by main(), and main().
SocketPool_drain_remaining_ms()
int64_t SocketPool_drain_remaining_ms (SocketPool_T pool) extern
Get time until forced shutdown.
Parameters
[in] pool Pool instance.
Returns
Milliseconds until timeout, 0 if already expired, -1 if not draining.
Thread Safety\n Yes - atomic read.
Note
Complexity: O(1). Use as timeout hint for poll/select during drain.
See also
SocketPool_drain() for drain initiation.
SocketPool_drain_poll() for progress monitoring.
Referenced by main().
SocketPool_drain_wait()
int SocketPool_drain_wait (SocketPool_T pool, int timeout_ms) extern
Blocking drain with internal poll loop.
Parameters
[in] pool Pool instance.
timeout_ms Maximum wait time (milliseconds), -1 for infinite.
Returns
0 if graceful completion, -1 if timed out (forced).
Thread Safety\n Yes.
Convenience function: calls drain(), polls with backoff, returns on completion. For event-driven apps, prefer drain() + drain_poll() pattern.
See also
SocketPool_drain() for manual control.
SocketPool_drain_poll() for non-blocking polling.
SocketPool_enable_reconnect()
void SocketPool_enable_reconnect (SocketPool_T pool, Connection_T conn, const char * host, int port) extern
Enable auto-reconnect for a connection.
Parameters
[in] pool Pool instance.
conn Connection to enable reconnection for.
host Original hostname for reconnection.
port Original port for reconnection.
Thread Safety\n Yes.
Enables automatic reconnection for the specified connection using the pool's reconnection policy. When the connection fails, it will be automatically reconnected.
NOTE: The original host/port must be provided since the socket may have been created with just an IP address from DNS resolution.
See also
SocketPool_set_reconnect_policy() for setting the policy.
SocketPool_disable_reconnect() for disabling reconnection.
reconnection for reconnection patterns.
socketpool_enforce_buffer_size()
static size_t socketpool_enforce_buffer_size (size_t bufsize) inline static
Enforce buffer size limits.
Parameters
bufsize Requested buffer size.
Returns
Enforced buffer size (clamped between min and max).
Thread Safety\n Yes - pure function.
See also
SocketPool_set_bufsize() for runtime buffer size changes.
SOCKET_MIN_BUFFER_SIZE and SOCKET_MAX_BUFFER_SIZE.
Definition at line 1154 of file SocketPool-private.h.
References SOCKET_MAX_BUFFER_SIZE, SOCKET_MIN_BUFFER_SIZE, and socketpool_enforce_range().
socketpool_enforce_max_connections()
static size_t socketpool_enforce_max_connections (size_t maxconns) inline static
Enforce maximum connection limit.
Parameters
maxconns Requested maximum number of connections.
Returns
Enforced value (clamped to SOCKET_MAX_CONNECTIONS, min 1).
Thread Safety\n Yes - pure function.
See also
SocketPool_resize() for runtime resizing.
SOCKET_MAX_CONNECTIONS for global limit.
Definition at line 1138 of file SocketPool-private.h.
References SOCKET_MAX_CONNECTIONS, and socketpool_enforce_range().
socketpool_enforce_range()
static size_t socketpool_enforce_range (size_t val, size_t minv, size_t maxv) inline static
Clamp value to min/max bounds.
Parameters
val size_t value to clamp.
minv size_t minimum allowed value.
maxv size_t maximum allowed value.
Returns
Clamped value within bounds.
Thread Safety\n Yes - pure function, no side effects.
Used for enforcing configuration limits on pool parameters. Prevents invalid values from causing security issues or crashes.
See also
socketpool_enforce_max_connections().
socketpool_enforce_buffer_size().
SocketPool_new() for parameter validation.
Definition at line 1122 of file SocketPool-private.h.
Referenced by socketpool_enforce_buffer_size(), and socketpool_enforce_max_connections().
SocketPool_filter()
size_t SocketPool_filter (SocketPool_T pool, SocketPool_Predicate predicate, void * userdata, Connection_T * results, size_t max_results) extern
Find all connections matching a predicate.
Parameters
[in] pool Pool instance.
predicate Callback that returns non-zero for matching connections.
[in] userdata User data passed to predicate.
[out] results Array to receive matching connections.
max_results Maximum number of results to return.
Returns
Number of matching connections found (may be less than max_results).
Thread Safety\n Yes - holds mutex during search.
Iterates through active connections and returns all that match the predicate, up to max_results. Results array must be pre-allocated by caller.
Example
int is_idle(Connection_T conn, void *data) {
    time_t threshold = *(time_t *)data;
    return time(NULL) - Connection_lastactivity(conn) > threshold;
}
Connection_T idle_conns[100];
time_t threshold = 300;  // 5 minutes
size_t count = SocketPool_filter(pool, is_idle, &threshold, idle_conns, 100);
for (size_t i = 0; i < count; i++) {
    // Process idle connection
}
Complexity\n O(n) - scans all active connections
See also
SocketPool_Predicate for predicate requirements.
SocketPool_find() for finding first matching connection.
SocketPool_foreach() for iterating all connections.
SocketPool_find()
Connection_T SocketPool_find (SocketPool_T pool, SocketPool_Predicate predicate, void * userdata) extern
Find first connection matching a predicate.
Parameters
[in] pool Pool instance.
predicate Callback that returns non-zero for matching connections.
[in] userdata User data passed to predicate.
Returns
First matching Connection_T or NULL if none found.
Thread Safety\n Yes - holds mutex during search.
Iterates through active connections and returns the first one for which predicate returns non-zero. Stops immediately on first match.
Example
int is_client_ip(Connection_T conn, void *data) {
    const char *target_ip = (const char *)data;
    Socket_T sock = Connection_socket(conn);
    return strcmp(Socket_getpeeraddr(sock), target_ip) == 0;
}
Connection_T conn = SocketPool_find(pool, is_client_ip, "192.168.1.100");
if (conn) {
    // Found connection from that IP
}
Complexity\n O(n) worst case - scans until match or end
See also
SocketPool_Predicate for predicate requirements.
SocketPool_filter() for finding all matching connections.
SocketPool_foreach() for iterating all connections.
Referenced by main().
SocketPool_foreach()
void SocketPool_foreach (SocketPool_T pool, void(*)(Connection_T, void *) func, void * arg) extern
Iterate over active connections.
Parameters
[in] pool Pool instance.
func Callback function (Connection_T, void*).
arg User data passed to callback.
Thread Safety\n Yes - holds mutex during iteration.
Note
O(n) scan; callback must not modify pool structure.
See also
SocketPool_count() for getting connection count.
Referenced by main().
SocketPool_free()
void SocketPool_free (SocketPool_T * pool) extern
Free a connection pool and release all resources.
Parameters
[in,out] pool Pointer to pool (set to NULL on success).
Thread Safety\n Yes.
Usage Example
SocketPool_free(&pool);  // Automatically closes pool resources
// pool == NULL after call
Note
Does NOT close underlying sockets - caller must close them explicitly or use SocketPool_drain_force() before freeing.
Warning
If draining, ensure SocketPool_drain_wait() or SocketPool_drain_poll() completes first to avoid resource leaks.
See also
SocketPool_new() for creation.
SocketPool_drain() for graceful shutdown before freeing.
SocketPool_remove() for individual connection cleanup.
Complexity\n O(1) - quick resource release, no socket operations
Referenced by main(), and main().
SocketPool_get()
Connection_T SocketPool_get (SocketPool_T pool, Socket_T socket) extern
Retrieve Connection_T wrapper for a socket in the pool.
Parameters
[in] pool Pool instance.
[in] socket Socket_T to look up (must be valid file descriptor).
Returns
Connection_T if found and valid, NULL if not in pool, invalid, or validation failed.
Thread Safety\n Yes - acquires pool mutex for duration of lookup.
Performs hash table lookup using socket FD hashed with golden ratio function. If found, runs built-in health check (SocketPool_check_connection()) and optional user validation callback. Updates last_activity timestamp to prevent idle timeout. Returns NULL without exception if:
Socket not in pool
Connection unhealthy (disconnected, error, stale)
Validation callback returns 0
Usage Example
// In event loop, after poll indicates readable socket
Connection_T conn = SocketPool_get(pool, sock);
if (conn != NULL) {
    SocketBuf_T inbuf = Connection_inbuf(conn);
    size_t avail = SocketBuf_available(inbuf);
    if (avail > 0) {
        // Read data from buffer
        char buf[1024];
        size_t read_len = SocketBuf_read(inbuf, buf, sizeof(buf));
        // Process data...
    }
    // Update activity implicitly via get()
} else {
    // Socket not managed by pool - handle directly or close
    Socket_free(&sock);
}
Note
Automatically refreshes connection activity timestamp.
Validation failures increment failure counters in pool stats.
Warning
Returned Connection_T remains valid until SocketPool_remove() or pool free.
Complexity\n O(1) average case - hash lookup; O(n) worst case - hash
collisions
See also
SocketPool_add() for adding connections to pool.
SocketPool_set_validation_callback() for custom validation before return.
SocketPool_check_connection() for manual health checks.
Connection_T accessors like Connection_socket(), Connection_inbuf().
socket_util_hash_fd() for underlying hash function.
Connection Management Modules for full connection lifecycle.
SocketPool_get_active_count()
size_t SocketPool_get_active_count (SocketPool_T pool) extern
Get count of currently active connections.
Parameters
[in] pool Pool instance.
Returns
Number of active connections in the pool.
Thread Safety\n Yes - atomic read.
Complexity\n O(1).
Convenience wrapper around SocketPool_get_stats().current_active.
See also
SocketPool_get_idle_count() for idle connections.
SocketPool_count() for same functionality (alias).
SocketPool_get_stats() for full statistics.
Referenced by main(), and main().
SocketPool_get_hit_rate()
double SocketPool_get_hit_rate (SocketPool_T pool) extern
Get connection reuse rate (hit rate).
Parameters
[in] pool Pool instance.
Returns
Reuse rate as fraction (0.0 to 1.0), or 0.0 if no connections.
Thread Safety\n Yes.
Complexity\n O(1).
Returns the ratio of reused connections to total connection acquisitions. Higher values indicate better pool efficiency. Calculated as: reused / (added + reused)
Example
double hit_rate = SocketPool_get_hit_rate(pool);
printf("Connection reuse: %.1f%%\n", hit_rate * 100.0);
See also
SocketPool_get_stats() for full statistics.
SocketPool_reset_stats() to start fresh measurement window.
Referenced by main(), and main().
SocketPool_get_idle_count()
size_t SocketPool_get_idle_count (SocketPool_T pool) extern
Get count of currently idle connections.
Parameters
[in] pool Pool instance.
Returns
Number of idle connections (active but not currently in use).
Thread Safety\n Yes - atomic read.
Complexity\n O(1).
Convenience wrapper around SocketPool_get_stats().current_idle.
See also
SocketPool_get_active_count() for active connections.
SocketPool_get_stats() for full statistics.
Referenced by main(), and main().
SocketPool_get_idle_timeout()
time_t SocketPool_get_idle_timeout (SocketPool_T pool) extern
Get idle connection timeout.
Parameters
[in] pool Pool instance.
Returns
Current idle timeout in seconds (0 = disabled).
Thread Safety\n Yes.
See also
SocketPool_set_idle_timeout() for setting the timeout.
SocketPool_get_stats()
void SocketPool_get_stats (SocketPool_T pool, SocketPool_Stats * stats) extern
Get pool statistics snapshot.
Parameters
[in] pool Pool instance.
stats Output statistics structure.
Thread Safety\n Yes.
Fills stats with current pool statistics. Calculated metrics (reuse_rate, avg_connection_age, churn_rate) are computed at call time.
See also
SocketPool_Stats for statistics structure.
SocketPool_reset_stats() for resetting counters.
SocketPool_get_syn_protection()
SocketSYNProtect_T SocketPool_get_syn_protection (SocketPool_T pool) extern
Get current SYN protection module.
Parameters
[in] pool Pool instance.
Returns
Current SYN protection instance, or NULL if disabled.
Thread Safety\n Yes.
See also
SocketPool_set_syn_protection() for setting protection.
SocketPool_getconnrate()
int SocketPool_getconnrate (SocketPool_T pool) extern
Get connection rate limit.
Parameters
[in] pool Pool instance.
Returns
Connections per second limit (0 if disabled).
Thread Safety\n Yes.
See also
SocketPool_setconnrate() for setting the limit.
SocketPool_getmaxperip()
int SocketPool_getmaxperip (SocketPool_T pool) extern
Get maximum connections per IP.
Parameters
[in] pool Pool instance.
Returns
Maximum connections per IP (0 = unlimited).
Thread Safety\n Yes.
See also
SocketPool_setmaxperip() for setting the limit.
socketpool_hash()
unsigned socketpool_hash (const Socket_T socket) extern
Allocate temporary buffer for bulk cleanup operations from arena.
Allocates array of Socket_T pointers sized to match pool's maxconns. Used during SocketPool_cleanup() to collect idle connections for batch processing. Arena-managed via CALLOC, zero-initialized (all NULL pointers).
Parameters
[in] arena Arena_T for allocation (must not be NULL).
[in] maxconns Pool's maximum connection count (determines buffer size).
Returns
Pointer to allocated and zeroed Socket_T* array.
Exceptions
SocketPool_Failed if Arena_calloc() fails (ENOMEM equivalent).
Arena_Failed if insufficient arena space available.
Thread Safety\n No - relies on non-thread-safe arena allocation.
Complexity\n O(maxconns) time and space - linear in pool capacity.
Internal Usage Pattern
// Called in allocate_pool_components() during pool creation
pool->cleanup_buffer = SocketPool_cleanup_allocate_buffer(arena, maxconns);
// Later in SocketPool_cleanup():
size_t to_cleanup = 0;
for (size_t i = 0; i < pool->maxconns; ++i) {
  if (is_idle(&pool->connections[i])) {
    pool->cleanup_buffer[to_cleanup++] = pool->connections[i].socket;
  }
}
// Batch process/close sockets in cleanup_buffer[0..to_cleanup-1]
Buffer Lifecycle
Purpose: Avoid realloc() during runtime cleanup scans
Size: maxconns * sizeof(Socket_T*) (~8-64KB depending on arch)
Zero-init: Ensures safe iteration (no dangling pointers)
Arena-managed: Auto-freed on Arena_dispose() in SocketPool_free()
Note
Temporary work buffer - contents overwritten each cleanup cycle.
Warning
Oversized pools consume unnecessary memory; tune via SocketPool_resize().
Arena pressure: Large pools may cause frequent Arena_calloc() reallocations.
See also
SocketPool_cleanup() for buffer usage in idle connection eviction.
SocketPool_new() / allocate_pool_components() for allocation context.
SocketPool_free() for implicit cleanup via arena disposal.
foundation::Arena_T::Arena_calloc() underlying mechanism (via CALLOC).
Compute hash for socket (internal).
Parameters
socket Socket_T to hash (must not be NULL).
Returns
unsigned hash value for hash table lookup.
Uses golden ratio hash function for optimal distribution and collision resistance. Hash is computed from socket file descriptor using multiplication method.
PERFORMANCE: O(1) constant time, optimized for cache performance. DISTRIBUTION: Designed for low collision rate with typical FD ranges.
See also
SOCKET_HASH_SIZE for table size.
socket_util_hash_fd in SocketUtil.h for implementation.
insert_into_hash_table() for usage.
find_slot() for lookup.
HASH_GOLDEN_RATIO in SocketUtil.h for constants.
Socket_fd() for getting file descriptor.
SocketPool_health()
SocketPool_Health SocketPool_health (SocketPool_T pool) extern
Get pool health status for load balancers.
Parameters
[in] pool Pool instance.
Returns
Current SocketPool_Health.
Thread Safety\n Yes - atomic read.
Note
Complexity: O(1). Maps state to health: RUNNING -> HEALTHY, DRAINING -> DRAINING, STOPPED -> STOPPED.
See also
SocketPool_Health for health status definitions.
SocketPool_state() for raw state.
SocketPool_idle_cleanup_due_ms()
int64_t SocketPool_idle_cleanup_due_ms (SocketPool_T pool) extern
Get time until next idle cleanup.
Parameters
[in] pool Pool instance.
Returns
Milliseconds until next cleanup, -1 if disabled.
Thread Safety\n Yes.
Use as timeout hint for poll/select to ensure timely cleanup. Returns -1 if idle timeout is disabled (timeout_sec == 0).
See also
SocketPool_set_idle_timeout() for configuring cleanup.
SocketPool_run_idle_cleanup() for manual cleanup.
SocketPool_ip_count()
int SocketPool_ip_count (SocketPool_T pool, const char * ip) extern
Get connection count for IP.
Parameters
[in] pool Pool instance.
ip IP address to query.
Returns
Number of tracked connections from this IP.
Thread Safety\n Yes.
See also
SocketPool_track_ip() for tracking IPs.
SocketPool_release_ip() for releasing tracked IPs.
SocketPool_is_draining()
int SocketPool_is_draining (SocketPool_T pool) extern
Check if pool is currently draining.
Parameters
[in] pool Pool instance.
Returns
Non-zero if state is DRAINING.
Thread Safety\n Yes - atomic read.
Note
Complexity: O(1).
See also
SocketPool_state() for full state information.
SocketPool_is_stopped()
int SocketPool_is_stopped (SocketPool_T pool) extern
Check if pool is fully stopped.
Parameters
[in] pool Pool instance.
Returns
Non-zero if state is STOPPED.
Thread Safety\n Yes - atomic read.
Note
Complexity: O(1).
See also
SocketPool_state() for full state information.
SocketPool_new()
SocketPool_T SocketPool_new (Arena_T arena, size_t maxconns, size_t bufsize) extern
Create a new connection pool.
Parameters
[in] arena Arena_T for memory allocation (NULL uses default arena).
[in] maxconns Maximum number of connections (enforced to 1-SOCKET_MAX_CONNECTIONS).
[in] bufsize Size of I/O buffers per connection (enforced to min-max bounds).
Returns
New pool instance (never returns NULL on success).
Exceptions
SocketPool_Failed on any allocation or initialization failure.
Thread Safety\n Yes - pool operations are thread-safe after creation.
Usage Example
Arena_T arena = Arena_new();
TRY {
    SocketPool_T pool = SocketPool_new(arena, 1000, 8192);
    // Use pool for connections...
    SocketPool_free(&pool);
} EXCEPT (SocketPool_Failed) {
    // Handle allocation failure
} FINALLY {
    Arena_dispose(&arena);
} END_TRY;
Complexity\n O(maxconns) - initializes hash table and pre-allocates buffers
Note
Automatically pre-warms SOCKET_POOL_DEFAULT_PREWARM_PCT slots for performance.
All connections share the same arena for memory management.
See also
SocketPool_free() for cleanup.
SocketPool_add() for adding connections.
SocketPool_prewarm() for runtime pre-warming.
Arena_new() for arena creation.
SOCKET_MAX_CONNECTIONS for global limits.
SOCKET_MIN_BUFFER_SIZE and SOCKET_MAX_BUFFER_SIZE for buffer limits.
Referenced by main(), and main().
SocketPool_prepare_connection()
int SocketPool_prepare_connection (SocketPool_T pool, SocketDNS_T dns, const char * host, int port, Socket_T * out_socket, Request_T * out_req) extern
Prepare async connection using DNS resolution.
Parameters
pool Pool instance (used for configuration and cleanup).
dns DNS resolver instance.
host Remote hostname or IP address.
port Remote port (1-65535).
[out] out_socket New Socket_T instance.
[out] out_req Pointer to Request_T (DNS request handle) for monitoring.
Returns
0 on success, -1 on error (out_socket/out_req undefined).
Exceptions
SocketPool_Failed on error.
Thread Safety\n Yes.
Creates Socket_T with pool defaults, starts async DNS resolution. Monitor out_req, then complete with Socket_connect_with_addrinfo() and SocketPool_add(). On error, Socket_free() the socket.
See also
SocketPool_connect_async() for higher-level async connection.
SocketDNS_T for DNS resolution details.
SocketPool_add() for adding completed connections.
Socket_connect_with_addrinfo() for completing the connection.
Socket_free() for cleanup on error.
SocketPool_prewarm()
void SocketPool_prewarm (SocketPool_T pool, int percentage) extern
Pre-allocate buffers for percentage of free slots.
Parameters
[in] pool Pool instance.
percentage Percentage of free slots to prewarm (0-100).
Thread Safety\n Yes.
Note
Reduces latency by pre-allocating buffers.
See also
SocketPool_new() for initial prewarming.
SocketPool_process_reconnects()
void SocketPool_process_reconnects (SocketPool_T pool) extern
Process reconnection state machines.
Parameters
[in] pool Pool instance.
Thread Safety\n Yes.
Must be called periodically (e.g., in event loop) to process reconnection timers and state transitions for all connections with auto-reconnect enabled.
See also
SocketPool_reconnect_timeout_ms() for timeout hints.
SocketPool_enable_reconnect() for enabling reconnection.
SocketPool_reconnect_timeout_ms()
int SocketPool_reconnect_timeout_ms (SocketPool_T pool) extern
Get time until next reconnection action.
Parameters
[in] pool Pool instance.
Returns
Milliseconds until next timeout, or -1 if none pending.
Thread Safety\n Yes.
Use as timeout hint for poll/select when reconnections are active.
See also
SocketPool_process_reconnects() for processing reconnections.
SocketPool_release_ip()
void SocketPool_release_ip (SocketPool_T pool, const char * ip) extern
Release tracked IP when connection closes.
Parameters
[in] pool Pool instance.
ip IP address to release.
Thread Safety\n Yes.
Decrements the connection count for the IP address. Safe to call with NULL or untracked IP.
See also
SocketPool_track_ip() for tracking IPs.
SocketPool_remove()
void SocketPool_remove (SocketPool_T pool, Socket_T socket) extern
Remove socket from pool.
Parameters
[in] pool Pool instance.
socket Socket to remove.
Thread Safety\n Yes.
Note
Clears buffers but does not close socket.
See also
SocketPool_add() for adding connections.
SocketPool_cleanup() for bulk removal.
Referenced by main().
SocketPool_reset_stats()
void SocketPool_reset_stats (SocketPool_T pool) extern
Reset pool statistics counters.
Parameters
[in] pool Pool instance.
Thread Safety\n Yes.
Resets all cumulative counters to zero and restarts the statistics window. Current state values (active, idle, max) are not affected.
See also
SocketPool_get_stats() for reading statistics.
SocketPool_resize()
void SocketPool_resize (SocketPool_T pool, size_t new_maxconns) extern
Resize pool capacity at runtime.
Parameters
[in] pool Pool instance.
new_maxconns New maximum connections.
Exceptions
SocketPool_Failed on error.
Thread Safety\n Yes.
Note
Grows/shrinks pool; closes excess connections on shrink.
See also
SocketPool_set_resize_callback() for notifications.
SocketPool_run_idle_cleanup()
size_t SocketPool_run_idle_cleanup (SocketPool_T pool) extern
Run idle connection cleanup if due.
Parameters
[in] pool Pool instance.
Returns
Number of connections cleaned up.
Thread Safety\n Yes.
Call periodically (e.g., after each poll iteration) to remove idle connections. Only performs cleanup if cleanup interval has passed. Does nothing if idle timeout is disabled.
See also
SocketPool_set_idle_timeout() for configuring cleanup.
SocketPool_idle_cleanup_due_ms() for timing information.
SocketPool_set_bufsize()
void SocketPool_set_bufsize (SocketPool_T pool, size_t new_bufsize) extern
Set buffer size for future connections.
Parameters
[in] pool Pool instance.
new_bufsize New buffer size for future connections.
Thread Safety\n Yes.
Note
Existing connections keep their current buffer size.
See also
SocketPool_new() for initial buffer size.
SocketBuf_T for buffer operations.
SocketPool_set_drain_callback()
void SocketPool_set_drain_callback (SocketPool_T pool, SocketPool_DrainCallback cb, void * data) extern
Register drain completion callback.
Parameters
[in] pool Pool instance.
cb Callback function (NULL to clear).
[in] data User data passed to callback.
Thread Safety\n Yes.
Callback is invoked exactly once when drain completes (transitions to STOPPED). Safe to call SocketPool_free() from callback.
See also
SocketPool_DrainCallback for callback signature.
SocketPool_drain() for initiating drain.
SocketPool_set_idle_callback()
void SocketPool_set_idle_callback (SocketPool_T pool, SocketPool_IdleCallback cb, void * data) extern
Register callback for when connections become idle.
Parameters
[in] pool Pool instance.
cb Callback function (NULL to clear).
[in] data User data passed to callback.
Thread Safety\n Yes.
The callback is invoked when a connection transitions to idle state. Useful for monitoring, logging, or cleaning up per-connection resources.
Example
void on_idle(Connection_T conn, void *data) {
    Socket_T sock = Connection_socket(conn);
    printf("Connection from %s went idle\n", Socket_getpeeraddr(sock));
}
SocketPool_set_idle_callback(pool, on_idle, NULL);
See also
SocketPool_IdleCallback for callback requirements.
SocketPool_set_idle_timeout() for automatic idle cleanup.
SocketPool_set_idle_timeout()
void SocketPool_set_idle_timeout (SocketPool_T pool, time_t timeout_sec) extern
Set idle connection timeout.
Parameters
[in] pool Pool instance.
timeout_sec Idle timeout in seconds (0 to disable automatic cleanup).
Thread Safety\n Yes.
When enabled, connections idle longer than timeout_sec will be removed during periodic cleanup. Use SocketPool_idle_cleanup_due_ms() to get the time until next cleanup for poll timeout integration.
See also
SocketPool_get_idle_timeout() for reading the timeout.
SocketPool_idle_cleanup_due_ms() for cleanup timing.
SocketPool_set_reconnect_policy()
void SocketPool_set_reconnect_policy (SocketPool_T pool, const SocketReconnect_Policy_T * policy) extern
Set default reconnection policy for pool.
Parameters
[in] pool Pool instance.
policy Reconnection policy (NULL to disable auto-reconnect).
Thread Safety\n Yes.
Sets the default reconnection policy for connections in this pool. Does not affect existing connections - use SocketPool_enable_reconnect() for those.
See also
SocketReconnect_Policy_T for policy configuration.
SocketPool_enable_reconnect() for enabling on existing connections.
SocketPool_set_resize_callback()
void SocketPool_set_resize_callback (SocketPool_T pool, SocketPool_ResizeCallback cb, void * data) extern
Register pool resize notification callback.
Parameters
[in] pool Pool instance.
cb Callback function (NULL to clear).
[in] data User data passed to callback.
Thread Safety\n Yes.
Callback is invoked after successful pool resize operations.
See also
SocketPool_ResizeCallback for callback signature.
SocketPool_resize() for resize operations.
SocketPool_set_syn_protection()
void SocketPool_set_syn_protection (SocketPool_T pool, SocketSYNProtect_T protect) extern
Enable SYN flood protection for pool.
Parameters
[in] pool Pool instance.
protect SYN protection instance (NULL to disable).
Thread Safety\n Yes.
When enabled, SocketPool_accept_protected() will check with the protection module and apply appropriate actions (throttle, challenge, or block) before accepting connections.
The protection module is NOT owned by the pool - caller must ensure it remains valid and must free it after the pool is freed.
See also
SocketPool_accept_protected() for protected accepting.
security::SocketSYNProtect for SYN flood protection details.
SocketPool_set_validation_callback()
void SocketPool_set_validation_callback (SocketPool_T pool, SocketPool_ValidationCallback cb, void * data) extern
Set connection validation callback.
Parameters
[in] pool Pool instance.
cb Validation callback (NULL to disable).
[in] data User data passed to callback.
Thread Safety\n Yes.
Callback invoked during SocketPool_get() to validate connections before reuse. Use for application-level health checks.
See also
SocketPool_ValidationCallback for callback signature.
SocketPool_check_connection() for built-in health checks.
SocketPool_get() for when validation occurs.
SocketPool_setconnrate()
void SocketPool_setconnrate (SocketPool_T pool, int conns_per_sec, int burst) extern
Set connection rate limit.
Parameters
[in] pool Pool instance.
conns_per_sec Maximum new connections per second (0 to disable).
burst Burst capacity (0 for default = conns_per_sec).
Thread Safety\n Yes.
Enables connection rate limiting using token bucket algorithm. New connections via SocketPool_add() or SocketPool_accept_limited() will be rejected if rate is exceeded.
See also
SocketPool_accept_limited() for rate-limited accepting.
SocketPool_getconnrate() to check current limit.
SocketPool_setmaxperip() for per-IP limits.
utilities::SocketRateLimit_T for token bucket implementation.
SocketPool_setmaxperip()
void SocketPool_setmaxperip (SocketPool_T pool, int max_conns) extern
Set maximum connections per IP.
Parameters
[in] pool Pool instance.
max_conns Maximum connections per IP (0 = unlimited).
Thread Safety\n Yes.
Enables per-IP connection limiting to prevent single-source attacks. New connections from IPs that exceed the limit will be rejected.
See also
SocketPool_getmaxperip() for reading the limit.
SocketPool_accept_limited() for rate-limited accepting.
SocketPool_shrink()
size_t SocketPool_shrink (SocketPool_T pool) extern
Release unused pool capacity.
Parameters
[in] pool Pool instance.
Returns
Number of connection slots released.
Thread Safety\n Yes.
Shrinks the pool by releasing unused (free) connection slots, reducing memory footprint. Only affects slots that have never been used or have been freed. Does not affect currently active connections.
Example
// After peak traffic subsides, reclaim unused memory
size_t released = SocketPool_shrink(pool);
printf("Released %zu unused slots\n", released);
Note
Does not reduce maxconns - pool can still grow back to original size.
Memory is not immediately returned to OS; managed by arena.
See also
SocketPool_resize() for changing pool capacity.
SocketPool_prewarm() for pre-allocating capacity.
SocketPool_state()
SocketPool_State SocketPool_state (SocketPool_T pool) extern
Get current pool lifecycle state.
Parameters
[in] pool Pool instance.
Returns
Current SocketPool_State.
Thread Safety\n Yes - atomic read.
Note
Complexity: O(1).
See also
SocketPool_State for state definitions.
SocketPool_drain() for state transitions.
SocketPool_track_ip()
int SocketPool_track_ip (SocketPool_T pool, const char * ip) extern
Manually track IP for per-IP limiting.
Parameters
[in] pool Pool instance.
ip IP address to track.
Returns
1 if under limit and tracked, 0 if limit reached.
Thread Safety\n Yes.
Use when manually managing connections not via SocketPool_accept_limited(). Call SocketPool_release_ip() when connection closes.
See also
SocketPool_release_ip() for releasing tracked IPs.
SocketPool_ip_count() for checking IP connection count.
SocketReconnect_attempts()
int SocketReconnect_attempts (SocketReconnect_T conn) extern
Get number of connection attempts since last success or reset.
Parameters
conn Reconnection context.
Returns
Number of connection attempts since last success or reset
Thread Safety\n No
SocketReconnect_connect()
void SocketReconnect_connect (SocketReconnect_T conn) extern
Initiate or queue a connection attempt according to current state and policy.
Parameters
[in] conn SocketReconnect_T instance to connect
Triggers transition from DISCONNECTED to CONNECTING if possible. Behavior based on current state:
DISCONNECTED: Starts non-blocking connect to resolved host/port
CONNECTING: No-op (already attempting)
CONNECTED: No-op (already connected)
BACKOFF: Queues retry after current backoff timer expires (via tick())
CIRCUIT_OPEN: Ignored until reset timeout elapses
Success/failure detected via SocketReconnect_process() on poll events or timeouts. Failed attempts increment statistics and may trigger backoff or circuit open.
State Transitions Triggered
DISCONNECTED -> CONNECTING (immediate)
BACKOFF -> CONNECTING (after delay)
CIRCUIT_OPEN -> ignored
Usage Example
SocketReconnect_T conn = SocketReconnect_new("example.com", 80, NULL, NULL,
NULL);
SocketReconnect_connect(conn);  // Start first attempt
// In event loop:
int fd = SocketReconnect_pollfd(conn);
if (event on fd) { // e.g., POLLOUT or POLLIN
    SocketReconnect_process(conn);
}
// After failure, auto-retries per policy
Thread Safety\n No - state mutation not safe across threads
Complexity\n O(1) - defers actual connect to non-blocking socket call
Note
getaddrinfo() cached from creation; no repeated DNS lookups
Warning
Calling repeatedly in rapid succession wastes CPU; rely on auto-retry
See also
SocketReconnect_state() Check if connect was accepted
SocketReconnect_process() Handle connection completion events
SocketReconnect_tick() Advance timers for queued retries
SocketReconnect_disconnect() Stop and reset without retry
SocketReconnect_disable_tls()
void SocketReconnect_disable_tls (SocketReconnect_T conn) extern
Disable TLS for future connections.
Parameters
[in] conn Reconnection context
Clears TLS configuration. Future connections will be plain TCP. If currently connected with TLS, the connection remains encrypted until disconnect; the next reconnect will be unencrypted.
Note
Does not affect current connection if active
Thread Safety\n No
See also
SocketReconnect_set_tls() to enable TLS
SocketReconnect_disconnect()
void SocketReconnect_disconnect (SocketReconnect_T conn) extern
Gracefully disconnect without triggering reconnect.
Parameters
conn Reconnection context.
Thread Safety\n No.
Note
Disconnects without triggering reconnection logic. Resets attempt counter.
Use this for intentional disconnection (e.g., shutdown).
See also
SocketReconnect_connect() for starting connections.
SocketReconnect_free() for complete cleanup.
socketreconnect_elapsed_ms()
static int64_t socketreconnect_elapsed_ms (int64_t start_ms) static
Compute elapsed monotonic time since provided start timestamp.
Calculates duration between start_ms and current time, clamping to 0 if anomalous (e.g., clock adjustment). Essential for timeout checks and delay validation.
Parameters
[in] start_ms Starting timestamp from socketreconnect_get_time_ms()
Returns
Non-negative int64_t milliseconds elapsed; 0 if start_ms >= now
Usage Example
int64_t start = socketreconnect_get_time_ms();
// ... some operation ...
int64_t elapsed = socketreconnect_elapsed_ms(start);
if (elapsed > policy.max_delay_ms) {
    // Timeout handling
}
Guarantees non-negative result for safe comparisons.
Complexity\n O(1) - arithmetic only (calls get_time_ms inline)
Thread Safety\n Yes - pure function, no side effects
Note
Clamps to 0 on underflow to handle rare clock issues
Warning
Input must be valid monotonic timestamp; invalid values may yield large positives
See also
socketreconnect_get_time_ms() to obtain start_ms
Socket_get_monotonic_ms() underlying time source
Definition at line 507 of file SocketReconnect-private.h.
References socketreconnect_now_ms().
SocketReconnect_failures()
int SocketReconnect_failures (SocketReconnect_T conn) extern
Get count of consecutive connection failures.
Parameters
conn Reconnection context.
Returns
Number of consecutive failures (for circuit breaker)
Thread Safety\n No
SocketReconnect_free()
void SocketReconnect_free (SocketReconnect_T * conn) extern
Destroy a SocketReconnect_T instance and release all associated resources.
Parameters
[in,out] conn Pointer to the SocketReconnect_T handle (set to NULL on success)
Performs immediate cleanup:
If CONNECTED or CONNECTING: Calls underlying socket shutdown/close
Cancels any pending timers or health checks
Releases internal memory allocations
Invokes no callbacks (safe during destruction)
Sets *conn to NULL to prevent use-after-free
Cleanup Guarantees
Graceful shutdown of socket if possible (SOCKET_SHUT_RDWR)
All resources returned to system (no leaks)
Underlying Socket_T freed internally
Statistics reset (not preserved)
Usage Example
SocketReconnect_T conn = SocketReconnect_new(host, port, NULL, NULL, NULL);
// ... use connection ...
SocketReconnect_disconnect(conn);  // Optional graceful close
SocketReconnect_free(&conn);       // Required cleanup
assert(conn == NULL);
Thread Safety\n No - must be called from the thread managing the instance
Complexity\n O(1) - socket close is O(1), timers cancelled instantly
Note
Always pair with SocketReconnect_new(); unpaired frees undefined
Warning
Calling on NULL or already-freed pointer is safe (no-op)
See also
SocketReconnect_new() Creation counterpart
SocketReconnect_disconnect() Graceful disconnect without full cleanup
Socket_debug_live_count() Verify no leaks in tests (should be 0 after free)
SocketReconnect_get_tls_hostname()
const char * SocketReconnect_get_tls_hostname (SocketReconnect_T conn) extern
Get the configured TLS hostname.
Parameters
[in] conn Reconnection context
Returns
SNI hostname or NULL if TLS not configured
Thread Safety\n Yes - returns internal pointer (valid until set_tls/free)
See also
SocketReconnect_set_tls() to set hostname
SocketReconnect_is_session_reused()
int SocketReconnect_is_session_reused (SocketReconnect_T conn) extern
Check if last connection used session resumption.
Parameters
[in] conn Reconnection context
Returns
1 if session was resumed (abbreviated handshake), 0 if full handshake was performed, -1 if not connected or TLS not enabled
Thread Safety\n Yes - reads only
See also
SocketReconnect_set_session_resumption() to enable caching
SocketReconnect_isconnected()
int SocketReconnect_isconnected (SocketReconnect_T conn) extern
Check if reconnection is currently in connected state.
Parameters
conn Reconnection context.
Returns
1 if connected, 0 otherwise
Thread Safety\n No
SocketReconnect_new()
SocketReconnect_T SocketReconnect_new (const char * host, int port, const SocketReconnect_Policy_T * policy, SocketReconnect_Callback callback, void * userdata) extern
Create a new SocketReconnect_T instance configured for a specific host and port.
Parameters
[in] host Target hostname (e.g., "example.com") or IP address (IPv4/IPv6)
[in] port Target port (1-65535); 0 invalid and will raise exception
[in] policy Optional custom policy (NULL uses defaults from SocketReconnect_policy_defaults())
[in] callback Optional state transition callback (NULL to disable)
[in] userdata User data passed unchanged to callbacks (may be NULL)
Returns
New opaque SocketReconnect_T handle in DISCONNECTED state
Exceptions
SocketReconnect_Failed On invalid parameters (null host, invalid port, bad policy values), Arena allocation failure, or internal init errors
Initializes a reconnection context with the specified endpoint. Hostname is resolved synchronously using getaddrinfo(); for async resolution integrate with SocketDNS externally. The instance starts in RECONNECT_DISCONNECTED state. No connection attempt is made until SocketReconnect_connect() is called. Resources (timers, state) are allocated from internal Arena; freed on SocketReconnect_free().
Validation Rules
host must be non-null and valid (checked via getaddrinfo)
port 1-65535
policy values validated (positive delays, multiplier >1, etc.)
callback may be NULL
Usage Example
// Basic creation with defaults
TRY {
    SocketReconnect_T conn = SocketReconnect_new("api.example.com", 443,
NULL, NULL, NULL); SocketReconnect_connect(conn);
    // Now integrate with loop or use I/O wrappers
} EXCEPT(SocketReconnect_Failed) {
    // Handle init failure (e.g., invalid host)
} END_TRY;
Advanced Configuration
SocketReconnect_Policy_T policy;
SocketReconnect_policy_defaults(&policy);
policy.max_attempts = 0;  // Unlimited retries
policy.health_check_interval_ms = 10000;  // Check every 10s
static void state_cb(SocketReconnect_T c, SocketReconnect_State o,
SocketReconnect_State n, void *ud) {
    // Log transition
}
SocketReconnect_T conn = SocketReconnect_new("db.internal", 5432, &policy,
state_cb, app_ctx);
Thread Safety\n Yes - each instance independent; safe from any thread but use
single-thread per instance thereafter
Complexity\n O(1) setup + O(n) getaddrinfo() where n=address families
Note
Host/port fixed at creation; for dynamic targets create new instances or use SocketProxy
Warning
Synchronous DNS may block briefly; consider caching resolved addresses for performance
See also
SocketReconnect_policy_defaults() Safe default policy
SocketReconnect_connect() Start connection process
SocketReconnect_free() Cleanup resources
SocketReconnect_set_health_check() Post-creation health customization
SocketReconnect_next_timeout_ms()
int SocketReconnect_next_timeout_ms (SocketReconnect_T conn) extern
Calculate milliseconds until next timer event or action.
Parameters
conn Reconnection context.
Returns
Milliseconds until next timeout, or -1 if none pending
Thread Safety\n No
Returns the time until:
Next backoff retry
Circuit breaker probe
Health check
Use as timeout for poll/select.
socketreconnect_now_ms()
static int64_t socketreconnect_now_ms (void) static
Retrieve current monotonic time in milliseconds for internal timing.
Provides a consistent, non-decreasing timestamp resistant to system clock changes (e.g., NTP adjustments). Used for all backoff, timeout, and health check calculations.
Returns
int64_t milliseconds since arbitrary fixed epoch (monotonic).
Usage Example
int64_t now = socketreconnect_get_time_ms();
if (socketreconnect_elapsed_ms(start) > timeout_ms) {
    // Handle timeout
}
Always prefer this over system time for scheduling to avoid jumps backward/forward.
Complexity\n O(1) - thin wrapper over system clock query
Thread Safety\n Yes - reentrant with no shared mutable state
Note
Backed by CLOCK_MONOTONIC or platform equivalent
Warning
Value wraps after ~292 years; handle int64_t overflow in long-running apps
See also
Socket_get_monotonic_ms() core implementation
socketreconnect_elapsed_ms() for computing durations
Definition at line 464 of file SocketReconnect-private.h.
References Socket_get_monotonic_ms().
Referenced by socketreconnect_elapsed_ms().
SocketReconnect_policy_defaults()
void SocketReconnect_policy_defaults (SocketReconnect_Policy_T * policy) extern
Populate a SocketReconnect_Policy_T with safe, production-recommended default values.
Parameters
[out] policy Pointer to structure to initialize (overwritten)
Sets balanced defaults suitable for most TCP services:
Conservative backoff to avoid overload
Circuit breaker to prevent storms
Health checks for proactive failure detection
Defaults Table
Setting Value Rationale
initial_delay_ms 100 Quick first retry without overwhelming
max_delay_ms 30000 30s cap prevents long hangs
multiplier 2.0 Standard exponential growth
jitter 0.25 25% randomization avoids herd
max_attempts 10 Limit retries to prevent infinite loops
circuit_failure_threshold 5 Quick detection of outages
circuit_reset_timeout_ms 60000 1min cooldown before probe
health_check_interval_ms 30000 Check every 30s, low overhead
health_check_timeout_ms 5000 5s max to avoid blocking
Usage Example
SocketReconnect_Policy_T policy;
SocketReconnect_policy_defaults(&policy);
// Optional tweaks
policy.initial_delay_ms = 200;  // Slower start for busy servers
SocketReconnect_T conn = SocketReconnect_new(host, port, &policy, NULL,
NULL);
Returns
void (populates policy in place)
Thread Safety\n Yes - pure function, no side effects
Complexity\n O(1) - simple assignment
Note
Always use this before custom modifications to ensure valid base
Warning
Modifying after SocketReconnect_new() requires new instance
See also
SocketReconnect_Policy_T Full field documentation
SocketReconnect_new() Apply initialized policy
SocketReconnect_pollfd()
int SocketReconnect_pollfd (SocketReconnect_T conn) extern
Retrieve file descriptor for event loop integration (poll/epoll/kqueue/select).
Parameters
[in] conn SocketReconnect_T instance
Returns
Valid FD (>=0) during CONNECTING/CONNECTED states for polling read/write events, -1 otherwise (no polling needed)
Provides the underlying socket file descriptor for multiplexing with other FDs in event loops. Usage:
During CONNECTING: Poll for write (connect completion) or error
During CONNECTED: Poll for read (data available) or write (send buffer ready)
Other states: -1 (no FD to poll; use next_timeout_ms() for timers)
Always pair with SocketReconnect_process() when events occur on this FD. FD changes on reconnect (new socket created); re-add to epoll etc. after state change callbacks.
Event Loop Integration Example
// Single instance loop example
SocketReconnect_T conn = SocketReconnect_new(...);
SocketReconnect_connect(conn);
while (running) {
    int fd = SocketReconnect_pollfd(conn);
    int timeout = SocketReconnect_next_timeout_ms(conn);
    // Poll setup (pseudocode)
    if (fd >= 0) poll_add(fd, POLLIN | POLLOUT | POLLERR | POLLHUP);
    int ready = poll_events(timeout);  // Implement poll loop
    if (fd >= 0 && event_on_fd(ready)) {
        SocketReconnect_process(conn);
    }
    SocketReconnect_tick(conn);  // Advance timers
}
Thread Safety\n No - FD may change concurrently if multi-threaded (avoid)
Complexity\n O(1)
Note
FD valid only while returned >=0; do not close or modify directly
Warning
In epoll/kqueue, use edge-triggered mode carefully; level-triggered safer
See also
SocketReconnect_process() Process events on this FD
SocketReconnect_next_timeout_ms() Timer integration
SocketReconnect_tick() Periodic timer advancement
poll/SocketPoll.h For high-performance multiplexing
SocketReconnect_process()
void SocketReconnect_process (SocketReconnect_T conn) extern
Process I/O events from poll loop.
Parameters
conn Reconnection context.
Thread Safety\n No
Call when SocketReconnect_pollfd() becomes readable/writable. Handles connection completion, detects disconnection, etc.
SocketReconnect_recv()
ssize_t SocketReconnect_recv (SocketReconnect_T conn, void * buf, size_t len) extern
Receive data from the reconnection-managed connection, auto-reconnecting on close or errors.
Parameters
[in] conn Reconnection context
[out] buf Buffer to receive data into
[in] len Maximum bytes to receive into buf (must >0)
Returns
Bytes received (>0), 0 on EOF/disconnect (triggers reconnect), -1 on error
Symmetric to SocketReconnect_send(): Provides transparent recv with auto-recovery. Behavior:
If CONNECTED: Delegates to Socket_recv() on underlying socket
If not connected: Returns 0 immediately (would block)
On recv error, EOF (0 bytes), or disconnect: Triggers reconnection, returns 0
Partial receives possible; loop until 0 for full messages
TCP ensures ordered delivery when connected; 0 indicates clean close or abrupt disconnect.
Error Handling
Return 0: EOF or error triggering reconnect (check state after)
errno=EAGAIN: Would block (non-blocking mode); try again later
Other errnos from underlying recv propagated
Usage Example - Transparent Recv Loop
char buf[1024];
while (running && SocketReconnect_isconnected(conn)) {
    ssize_t rcvd = SocketReconnect_recv(conn, buf, sizeof(buf));
    if (rcvd > 0) {
        // Process data
        process_data(buf, rcvd);
    } else if (rcvd == 0) {
        SOCKET_LOG_INFO_MSG("Connection closed, reconnecting...");
        // Auto-reconnect happens
        break;  // Or continue to wait
    } else {  // -1
        if (errno != EAGAIN) {
            // Handle error
        }
    }
}
Performance Notes
For high-throughput: Use recvv() variants via direct socket access
Buffering: No internal queue; data lost on disconnect before recv
Non-blocking: Safe in event loops; returns EAGAIN if no data
Thread Safety\n No - may trigger state changes
Complexity\n O(len) - underlying recv syscall
Note
Handles partial reads; application must loop for complete messages
Warning
Recv in non-connected state wastes CPU; check isconnected() first
See also
SocketReconnect_send() Send counterpart
SocketReconnect_socket() For recvv, peek, etc.
Socket_recv() Underlying primitive
SocketReconnect_reset()
void SocketReconnect_reset (SocketReconnect_T conn) extern
Reset reconnection statistics and state machine.
Parameters
conn Reconnection context.
Thread Safety\n No.
Note
Clears attempt counter, consecutive failures, and circuit breaker state.
Does not disconnect if connected. Use after external recovery.
See also
SocketReconnect_connect() for initiating reconnection.
SocketReconnect_state() for current state.
SocketReconnect_send()
ssize_t SocketReconnect_send (SocketReconnect_T conn, const void * buf, size_t len) extern
Send data over the reconnection-managed connection with automatic retry on transient errors.
Parameters
[in] conn Reconnection context
[in] buf Buffer containing data to send
[in] len Number of bytes from buf to send (0 valid, no-op)
Returns
Number of bytes sent (>0 success), 0 if not connected (DISCONNECTED/BACKOFF/CIRCUIT_OPEN), -1 on error
Convenience wrapper providing transparent I/O over the managed connection. Behavior:
If CONNECTED: Delegates to Socket_send() on underlying socket
If not connected: Returns 0 immediately (no blocking)
On send error or disconnection: Triggers reconnect logic, sets errno to ENOTCONN, returns -1
Partial sends possible (like Socket_send); caller must handle retries if needed
Does not buffer unsent data; for reliability use higher-level protocols (TCP ensures delivery if connected).
Error Handling
errno=ENOTCONN: Not connected or lost connection (reconnect queued)
errno=ECONNRESET/EPIPE: Peer closed, triggers reconnect
Other errnos propagated from underlying socket
Usage Example - Transparent Send
// Assume conn connected
const char *msg = "Hello Server";
ssize_t sent = SocketReconnect_send(conn, msg, strlen(msg));
if (sent < 0) {
    if (errno == ENOTCONN) {
        // Reconnect will happen automatically
        SOCKET_LOG_WARN_MSG("Send failed, reconnecting...");
    } else {
        // Handle other errors
    }
} else {
    // sent bytes transmitted or queued in TCP
}
When to Use vs Direct Socket
Use this for simple apps wanting auto-reconnect without event loop
For performance/control: Get socket with SocketReconnect_socket() and use Socket_sendv() etc.
Buffering? Use SocketPool or application-level queues
Thread Safety\n No - modifies internal state
Complexity\n O(len) - underlying send syscall
Note
SIGPIPE handled internally (no signal sent)
Warning
Not for large data; consider Socket_sendfile() or chunking for big transfers
See also
SocketReconnect_recv() Counterpart receive wrapper
SocketReconnect_socket() Direct access for advanced I/O
Socket_send() Underlying primitive
SocketReconnect_set_health_check()
void SocketReconnect_set_health_check (SocketReconnect_T conn, SocketReconnect_HealthCheck check) extern
Register a custom health check callback for proactive connection validation.
Parameters
[in] conn SocketReconnect_T to configure
[in] check Custom health check function (NULL to revert to default)
Overrides the default health check behavior used during CONNECTED state. The default check simply polls the socket for readability within the configured timeout to detect dead peers. Custom checks can perform application-specific validation (e.g., send ping, check latency).
Changes take effect on next health check interval (no immediate invocation). If health checks disabled (interval=0), this has no effect.
Default vs Custom
Default: Socket_poll for POLLIN within timeout_ms (lightweight, detects closes)
Custom: Caller-defined; must return 1=healthy, 0=unhealthy quickly
Usage Example
// Set custom check after creation
SocketReconnect_set_health_check(conn, my_app_ping_check);
// Or revert to default
SocketReconnect_set_health_check(conn, NULL);
Thread Safety\n No - modifies instance configuration
Complexity\n O(1) - simple assignment
Note
Callback userdata is from creation (not set here); for per-check data use conn context
Warning
Custom checks blocking > timeout_ms will hang tick()/process(); always respect limit
See also
SocketReconnect_HealthCheck Callback type definition and requirements
SocketReconnect_Policy_T::health_check_interval_ms Enable/disable checks
SocketReconnect_Policy_T::health_check_timeout_ms Set timeout limit
SocketReconnect_set_session_resumption()
void SocketReconnect_set_session_resumption (SocketReconnect_T conn, int enable) extern
Enable TLS session resumption for faster reconnects.
Parameters
[in] conn Reconnection context
[in] enable 1 to enable session caching, 0 to disable
When enabled, successful TLS sessions are saved and restored on reconnect attempts, enabling abbreviated handshakes (0-RTT for TLS 1.3). This significantly reduces reconnection latency.
Note
Enabled by default when TLS is configured
Session data stored internally; cleared on disable_tls or free
Thread Safety\n No
See also
SocketTLS_is_session_reused() to check if resumption worked
SocketReconnect_set_tls()
void SocketReconnect_set_tls (SocketReconnect_T conn, SocketTLSContext_T ctx, const char * hostname) extern
Configure TLS for reconnecting connections.
Parameters
[in] conn Reconnection context
[in] ctx TLS context (caller retains ownership; must outlive conn)
[in] hostname SNI hostname for certificate verification (copied)
Enables TLS on all future connections made by this reconnection instance. The TLS context is NOT owned by SocketReconnect - caller must ensure it remains valid for the lifetime of the reconnection instance.
After TCP connect completes, TLS handshake is performed automatically. The hostname is used for:
SNI (Server Name Indication) extension per RFC 6066
Certificate hostname verification via X509_check_host()
Usage Example
SocketTLSContext_T ctx = SocketTLSContext_new_client(NULL);
SocketReconnect_T conn = SocketReconnect_new("api.example.com", 443,
                                              NULL, NULL, NULL);
SocketReconnect_set_tls(conn, ctx, "api.example.com");
SocketReconnect_connect(conn);
// TLS handshake happens automatically after TCP connect
while (!SocketReconnect_isconnected(conn)) {
    SocketReconnect_tick(conn);
}
// Now using encrypted connection
SocketReconnect_send(conn, data, len);  // Uses SocketTLS_send internally
Note
Call before SocketReconnect_connect() for first connection
Can be called while disconnected to change TLS settings
Warning
Calling while connected has no effect until next reconnect
Thread Safety\n No - must be called from same thread as other operations
Exceptions
SocketReconnect_Failed if hostname is NULL or too long
See also
SocketReconnect_disable_tls() to remove TLS configuration
SocketReconnect_tls_enabled() to query TLS state
SocketTLSContext_new_client() for context creation
SocketReconnect_socket()
Socket_T SocketReconnect_socket (SocketReconnect_T conn) extern
Get the underlying Socket_T when connected.
Parameters
conn Reconnection context.
Returns
Connected socket, or NULL if not connected.
Thread Safety\n No.
Note
Returns the underlying socket only when in RECONNECT_CONNECTED state.
Do not close or free the returned socket directly.
See also
SocketReconnect_state() for connection state.
SocketReconnect_isconnected() for boolean check.
SocketReconnect_state()
SocketReconnect_State SocketReconnect_state (SocketReconnect_T conn) extern
Query the current state of the reconnection instance.
Parameters
[in] conn SocketReconnect_T to query
Returns
Current SocketReconnect_State (e.g., RECONNECT_CONNECTED)
Thread Safety\n No - but read-only, safe if no concurrent mutations
Provides snapshot of internal state machine for decision making or logging. States reflect connection status, backoff timers, and circuit breaker. Use in conditionals to gate operations (e.g., only send when CONNECTED).
Usage Example
SocketReconnect_State st = SocketReconnect_state(conn);
switch (st) {
    case RECONNECT_CONNECTED:
        // Safe to send/recv
        break;
    case RECONNECT_CIRCUIT_OPEN:
        // Outage detected, alert
        break;
    default:
        // Wait or retry
}
// Log with name
SOCKET_LOG_DEBUG_MSG("State: %s", SocketReconnect_state_name(st));
Complexity\n O(1)
Note
State may change immediately after call due to async nature; check in event handlers
See also
SocketReconnect_isconnected() Convenience for CONNECTED check
SocketReconnect_state_name() String representation for logs
SocketReconnect_Callback() Asynchronous state notifications
SocketReconnect_state_name()
const char * SocketReconnect_state_name (SocketReconnect_State state) extern
Get human-readable name for a reconnection state.
Parameters
state Reconnection state enum value.
Returns
Static string with state name
Thread Safety\n Yes
SocketReconnect_tick()
void SocketReconnect_tick (SocketReconnect_T conn) extern
Advance timers and perform periodic maintenance for state transitions and checks.
Parameters
[in] conn SocketReconnect_T to tick
Essential function for timer-driven operations:
Advances backoff timers (may trigger CONNECTING from BACKOFF)
Checks circuit reset timeout (may allow new attempts)
Performs health checks if interval elapsed (in CONNECTED)
Detects timeouts for ongoing connects
No-op if no timers pending
Call this:
Periodically in main loop (e.g., every 100ms or after poll timeout)
Immediately after SocketReconnect_next_timeout_ms() returns <=0
Does not block; quick execution unless health check active
Integration Patterns
With Event Loop
while (running) {
    int timeout = SocketReconnect_next_timeout_ms(conn);
    timeout = MIN(timeout, 100);  // Cap for responsiveness
    // Poll with timeout
    poll_wait(timeout);
    SocketReconnect_tick(conn);  // Handle expired timers
    int fd = SocketReconnect_pollfd(conn);
    if (event_on_fd(fd)) {
        SocketReconnect_process(conn);
    }
}
Standalone Periodic Call
// In timer thread or main loop
static int64_t last_tick = 0;
int64_t now = Socket_get_monotonic_ms();
if (now - last_tick >= 50) {  // 50ms granularity
    SocketReconnect_tick(conn);
    last_tick = now;
}
Thread Safety\n No - modifies timers and may change state
Complexity\n O(1) average; O(health check time) if check runs
Note
Use Socket_get_monotonic_ms() internally for precision
Warning
Infrequent calls (> policy intervals) may delay detections; call regularly
See also
SocketReconnect_next_timeout_ms() Determine optimal call frequency
SocketReconnect_process() Handle FD events (complement)
SocketReconnect_HealthCheck Custom check during tick
SocketReconnect_tls_enabled()
int SocketReconnect_tls_enabled (SocketReconnect_T conn) extern
Check if TLS is configured for this connection.
Parameters
[in] conn Reconnection context
Returns
1 if TLS is configured (context set), 0 otherwise
Thread Safety\n Yes - reads only
See also
SocketReconnect_set_tls() to configure TLS
SocketReconnect_tls_handshake_state()
TLSHandshakeState SocketReconnect_tls_handshake_state (SocketReconnect_T conn) extern
Get current TLS handshake state.
Parameters
[in] conn Reconnection context
Returns the current TLS handshake progress. Useful for debugging and advanced event loop integration.
Returns
Current TLSHandshakeState, or TLS_HANDSHAKE_NOT_STARTED if TLS not enabled or no handshake in progress
Thread Safety\n Yes - reads only
See also
TLSHandshakeState for state descriptions
update_existing_slot()
void update_existing_slot (Connection_T conn, time_t now) extern
Update existing connection slot activity.
Parameters
conn Connection slot to update.
now Current timestamp.
Updates last activity timestamp for idle timeout tracking.
See also
SocketPool_get() for automatic updates.
validate_saved_session()
void validate_saved_session (Connection_T conn, time_t now) extern
Validate TLS session for reuse.
Parameters
conn Connection with potential saved session.
now Current timestamp.
Checks if saved TLS session is still valid for reuse.
See also
SocketPool_add() for session saving.
Variable Documentation
SocketPool_DetailedException
Except_T SocketPool_DetailedException extern
Thread-local exception for detailed error messages.
Extern declaration - actual definition in SocketPool-core.c. Uses shared socket_error_buf for consistent error formatting.
See also
RAISE_POOL_ERROR macro.
socket_error_buf in SocketUtil.h.
SocketPool_Failed exception type.
SocketPool_Failed
const Except_T SocketPool_Failed extern
Pool operation failure.
Category: RESOURCE or APPLICATION Retryable: Depends on specific operation
Raised for:
Pool capacity exhaustion (RESOURCE, retryable after drain)
Invalid parameters (APPLICATION, not retryable)
Memory allocation failures (RESOURCE, not retryable)
Connection validation failures (NETWORK, retryable)
Socket operation failures (NETWORK, retryable)
DNS resolution failures (NETWORK, retryable)
Check errno or context for specific failure reason. Thread-safe: Uses thread-local error buffers.
See also
SocketPool_Failed exception type.
error-handling for exception handling patterns.
socket_error_buf in SocketUtil.h for error message formatting.
Referenced by main(), and main().
SocketReconnect_Failed
const Except_T SocketReconnect_Failed extern
Exception type for errors in the reconnection module.
This exception is raised for configuration errors, resource allocation failures, or internal state inconsistencies. Common triggers include:
Invalid policy values (negative delays, multiplier <=1.0, jitter <0 or >1)
Arena allocation failure during initialization
Invalid host/port parameters
Unrecoverable state machine errors (rare)
Handling Pattern
TRY {
    SocketReconnect_T conn = SocketReconnect_new(host, port, &policy, NULL,
NULL);
    // Use conn...
} EXCEPT(SocketReconnect_Failed) {
    fprintf(stderr, "Reconnect failed: %s\n",
Except_message(&Except_stack));
    // Log or retry with different params
} END_TRY;
Note
Always check Socket_GetLastError() or Except_message() for detailed error information
See also
SocketReconnect_new() Primary raise point
core/Except.h Base exception handling framework
Socket_GetLastError() For system error details if applicable