Tetsuo Pulse: Core Foundation Modules
Core Foundation Modules
Base infrastructure for memory management, exception handling, and core utilities.The Foundation group provides the fundamental building blocks used by all other modules in the socket library. Key components include:
Modules
Live Socket Counting Utilities
Thread-safe global counter for tracking active Socket_T instances.
Files
file Arena.h
Arena-based memory allocator for efficient bulk memory management.
file Except.h
Structured exception handling for C with TRY/EXCEPT/FINALLY blocks.
file SocketConfig.h
Compile-time and runtime configuration constants, limits, and platform adaptations.
file SocketCrypto.h
Cryptographic utility functions for secure operations.
file SocketSecurity.h
Centralized security configuration, limits, and validation utilities.
file SocketUtil.h
Consolidated utility header for logging, metrics, events, and error handling.
Data Structures
struct Except_T
Exception structure for structured error handling.
struct SocketTimeouts_T
Basic timeout configuration structure for socket operations.
struct SocketTimeouts_Extended_T
Extended per-phase timeout configuration structure.
union align
Alignment union for arena memory management.
struct SocketSecurityLimits
Aggregated security limits for runtime configuration inspection.
struct SocketLogContext
SocketLogContext - Thread-local logging context for correlation.
struct SocketLogField
SocketLogField - Key-value pair for structured logging.
struct SocketMetricsSnapshot
SocketMetricsSnapshot - Thread-safe snapshot of all library metrics.
Macros
#define T Arena_T
Opaque arena type for memory management.
#define ALLOC(arena, nbytes) (Arena_alloc ((arena), (nbytes), __FILE__, __LINE__))
Convenience macro for Arena_alloc with automatic source location tracking.
#define CALLOC(arena, count, nbytes) (Arena_calloc ((arena), (count), (nbytes), __FILE__, __LINE__))
Convenience macro for zero-initialized multi-element allocation with source tracking.
#define RAISE(e) Except_raise (&(e), __FILE__, __LINE__)
Raise an exception with current file and line information.
#define RERAISE
Re-raise the currently caught exception.
#define RETURN
Return from function while cleaning up exception stack.
#define EXCEPT_POP_FRAME_IF_ENTERED
Internal helper macro for exception frame cleanup.
#define TRY
Start a TRY/EXCEPT/FINALLY exception handling block.
#define EXCEPT(e)
Catch a specific exception type within a TRY block.
#define ELSE
Catch any exception not caught by previous EXCEPT blocks.
#define FINALLY
Define cleanup code that executes regardless of exceptions.
#define END_TRY
Complete a TRY/EXCEPT/FINALLY exception handling block.
#define SOCKET_VERSION_MAJOR 0
Major version number.
#define SOCKET_VERSION_MINOR 1
Minor version number.
#define SOCKET_VERSION_PATCH 0
Patch version number.
#define SOCKET_VERSION_STRING "0.1.0"
Version string for human-readable output.
#define SOCKET_VERSION
Numeric version for compile-time comparisons.
#define SOCKET_MAX_CONNECTIONS 10000UL
Maximum number of connections in pool.
#define SOCKET_MAX_BUFFER_SIZE (1024 * 1024) /* 1MB */
Maximum buffer size per connection.
#define SOCKET_MIN_BUFFER_SIZE 512
Minimum buffer size per connection.
#define SOCKET_HASH_TABLE_SIZE 1021
Hash table size for socket data mapping.
#define ARENA_CHUNK_SIZE (10 * 1024) /* 10KB */
Default arena chunk size.
#define ARENA_MAX_ALLOC_SIZE SOCKET_SECURITY_MAX_ALLOCATION /* Matches centralized limit */
Maximum allocation size for arena.
#define ARENA_MAX_FREE_CHUNKS 10
Maximum number of free chunks to cache for reuse.
#define ARENA_ERROR_BUFSIZE 256
Buffer size for arena error messages.
#define SOCKET_ERROR_BUFSIZE 1024
Error buffer size.
#define SOCKET_STRERROR_BUFSIZE 128
Thread-safe strerror buffer size.
#define SOCKET_ERROR_MAX_HOSTNAME 255
Maximum hostname length in error messages.
#define SOCKET_ERROR_MAX_MESSAGE 512
Maximum error message length.
#define SOCKET_ERROR_TRUNCATION_MARKER "... (truncated)"
Truncation marker for error messages.
#define SOCKET_ERROR_TRUNCATION_SIZE (sizeof (SOCKET_ERROR_TRUNCATION_MARKER))
Size of truncation marker.
#define SOCKET_PORT_STR_BUFSIZE 16
Socket port string buffer size.
#define SOCKET_PLATFORM_MACOS 0
Platform detection flag for macOS/Apple systems.
#define SOCKET_DEFAULT_CONNECT_TIMEOUT_MS 30000 /* 30 seconds */
Default connect timeout.
#define SOCKET_DEFAULT_OPERATION_TIMEOUT_MS 0 /* Infinite */
Default operation timeout.
#define SOCKET_DEFAULT_TLS_TIMEOUT_MS 30000
Default TLS handshake timeout.
#define SOCKET_DEFAULT_REQUEST_TIMEOUT_MS 60000
Default request cycle timeout.
#define HASH_GOLDEN_RATIO 2654435761u
Golden ratio constant for multiplicative hashing.
#define ARENA_ALIGNMENT_SIZE sizeof (union align)
Arena alignment size.
#define ARENA_VALIDATION_SUCCESS 1
Arena validation success code.
#define ARENA_VALIDATION_FAILURE 0
Arena validation failure code.
#define ARENA_SUCCESS 0
Arena operation success code.
#define ARENA_FAILURE (-1)
Arena operation failure code.
#define ARENA_CHUNK_REUSED 1
Arena chunk reused indicator.
#define ARENA_CHUNK_NOT_REUSED 0
Arena chunk not reused indicator.
#define ARENA_SIZE_VALID 1
Arena size validation success.
#define ARENA_SIZE_INVALID 0
Arena size validation failure.
#define ARENA_ENOMEM "Out of memory"
Arena out of memory error message.
#define SOCKET_MS_PER_SECOND 1000
Milliseconds per second.
#define SOCKET_NS_PER_MS 1000000LL
Nanoseconds per millisecond.
#define SOCKET_NS_PER_SECOND 1000000000LL
Nanoseconds per second.
#define SOCKET_STRINGIFY(x) #x
Stringify macro for compile-time string conversion.
#define SOCKET_TO_STRING(x) SOCKET_STRINGIFY (x)
Convert macro argument to string.
#define SOCKET_PORT_VALID_RANGE "1-" SOCKET_TO_STRING (SOCKET_MAX_PORT)
Valid port range string for error messages.
#define SOCKET_TTL_VALID_RANGE "1-" SOCKET_TO_STRING (SOCKET_MAX_TTL)
Valid TTL range string for error messages.
#define SOCKET_IPV4_PREFIX_RANGE "0-" SOCKET_TO_STRING (SOCKET_IPV4_MAX_PREFIX)
Valid IPv4 prefix range string for error messages.
#define SOCKET_IPV6_PREFIX_RANGE "0-" SOCKET_TO_STRING (SOCKET_IPV6_MAX_PREFIX)
Valid IPv6 prefix range string for error messages.
#define SOCKET_VALID_PORT(p) ((int)(p) >= 0 && (int)(p) <= 65535)
Port number validation macro.
#define SOCKET_VALID_BUFFER_SIZE(s)
Buffer size validation macro.
#define SOCKET_VALID_CONNECTION_COUNT(c) ((size_t)(c) > 0 && (size_t)(c) <= SOCKET_MAX_CONNECTIONS)
Connection count validation macro.
#define SOCKET_VALID_POLL_EVENTS(e) ((int)(e) > 0 && (int)(e) <= SOCKET_MAX_POLL_EVENTS)
Poll events validation macro.
#define SOCKET_VALID_IP_STRING(ip) ((ip) != NULL && (ip)[0] != '\0')
IP string validation macro.
#define SAFE_CLOSE(fd)
Safe file descriptor close macro.
#define SOCKET_CRYPTO_SHA1_SIZE 20
Size of SHA-1 digest in bytes.
#define SOCKET_CRYPTO_SHA256_SIZE 32
Size of SHA-256 digest in bytes.
#define SOCKET_CRYPTO_MD5_SIZE 16
Size of MD5 digest in bytes.
#define SOCKET_CRYPTO_WEBSOCKET_GUID "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"
Fixed GUID string for WebSocket Sec-WebSocket-Accept computation (RFC 6455).
#define SOCKET_CRYPTO_WEBSOCKET_KEY_SIZE 25
Size of Sec-WebSocket-Key string buffer (Base64-encoded).
#define SOCKET_CRYPTO_WEBSOCKET_ACCEPT_SIZE 29
Size of Sec-WebSocket-Accept string buffer (Base64-encoded).
#define SOCKET_SECURITY_MAX_ALLOCATION (256UL * 1024 * 1024)
Maximum single allocation size permitted by security policy.
#define SOCKET_SECURITY_MAX_BODY_SIZE (100 * 1024 * 1024)
Maximum permitted size for HTTP request/response bodies.
#define SOCKET_SECURITY_MAX_REQUEST_TIMEOUT_MS 60000
Maximum allowed request timeout value in milliseconds.
#define SOCKET_SECURITY_VALID_SIZE(s) ((size_t)(s) > 0 && (size_t)(s) <= SOCKET_SECURITY_MAX_ALLOCATION)
Inline macro for validating a size against allocation security limits.
#define SOCKET_SECURITY_CHECK_OVERFLOW_MUL(a, b) ((b) == 0 || (a) <= SIZE_MAX / (b))
Inline macro to check size multiplication for overflow risk.
#define SOCKET_SECURITY_CHECK_OVERFLOW_ADD(a, b) ((a) <= SIZE_MAX - (b))
Inline macro to check size addition for overflow risk.
Typedefs
typedef struct Arena_T * Arena_T
typedef void(* SocketLogCallback) (void *userdata, SocketLogLevel level, const char *component, const char *message)
Custom logging callback function type.
typedef void(* SocketLogStructuredCallback) (void *userdata, SocketLogLevel level, const char *component, const char *message, const SocketLogField *fields, size_t field_count, const SocketLogContext *context)
Typedef for callback handling structured logs with key-value fields and context.
typedef struct Arena_T * Arena_T
Forward declaration of Arena_T from core foundation module.
Enumerations
enum {
Except_entered = 0 ,
Except_raised ,
Except_handled ,
Except_finalized
}
Exception handling states for TRY/EXCEPT/FINALLY blocks.
enum SocketLogLevel {
SOCKET_LOG_TRACE = 0 ,
SOCKET_LOG_DEBUG ,
SOCKET_LOG_INFO ,
SOCKET_LOG_WARN ,
SOCKET_LOG_ERROR ,
SOCKET_LOG_FATAL
}
Log severity levels.
enum SocketMetric {
SOCKET_METRIC_SOCKET_CONNECT_SUCCESS = 0 ,
SOCKET_METRIC_SOCKET_CONNECT_FAILURE ,
SOCKET_METRIC_SOCKET_SHUTDOWN_CALL ,
SOCKET_METRIC_DNS_REQUEST_SUBMITTED ,
SOCKET_METRIC_DNS_REQUEST_COMPLETED ,
SOCKET_METRIC_DNS_REQUEST_FAILED ,
SOCKET_METRIC_DNS_REQUEST_CANCELLED ,
SOCKET_METRIC_DNS_REQUEST_TIMEOUT ,
SOCKET_METRIC_POLL_WAKEUPS ,
SOCKET_METRIC_POLL_EVENTS_DISPATCHED ,
SOCKET_METRIC_POOL_CONNECTIONS_ADDED ,
SOCKET_METRIC_POOL_CONNECTIONS_REMOVED ,
SOCKET_METRIC_POOL_CONNECTIONS_REUSED ,
SOCKET_METRIC_POOL_DRAIN_INITIATED ,
SOCKET_METRIC_POOL_DRAIN_COMPLETED ,
SOCKET_METRIC_POOL_HEALTH_CHECKS ,
SOCKET_METRIC_POOL_HEALTH_FAILURES ,
SOCKET_METRIC_POOL_VALIDATION_FAILURES ,
SOCKET_METRIC_POOL_IDLE_CLEANUPS ,
SOCKET_METRIC_COUNT
}
SocketMetric - Enumeration of library-wide performance and operational metrics.
enum SocketErrorCode {
SOCKET_ERROR_NONE = 0 ,
SOCKET_ERROR_EINVAL ,
SOCKET_ERROR_EACCES ,
SOCKET_ERROR_EADDRINUSE ,
SOCKET_ERROR_EADDRNOTAVAIL ,
SOCKET_ERROR_EAFNOSUPPORT ,
SOCKET_ERROR_EAGAIN ,
SOCKET_ERROR_EALREADY ,
SOCKET_ERROR_EBADF ,
SOCKET_ERROR_ECONNREFUSED ,
SOCKET_ERROR_ECONNRESET ,
SOCKET_ERROR_EFAULT ,
SOCKET_ERROR_EHOSTUNREACH ,
SOCKET_ERROR_EINPROGRESS ,
SOCKET_ERROR_EINTR ,
SOCKET_ERROR_EISCONN ,
SOCKET_ERROR_EMFILE ,
SOCKET_ERROR_ENETUNREACH ,
SOCKET_ERROR_ENOBUFS ,
SOCKET_ERROR_ENOMEM ,
SOCKET_ERROR_ENOTCONN ,
SOCKET_ERROR_ENOTSOCK ,
SOCKET_ERROR_EOPNOTSUPP ,
SOCKET_ERROR_EPIPE ,
SOCKET_ERROR_EPROTONOSUPPORT ,
SOCKET_ERROR_ETIMEDOUT ,
SOCKET_ERROR_EWOULDBLOCK ,
SOCKET_ERROR_UNKNOWN
}
SocketErrorCode - Normalized error codes mapping POSIX errno values.
enum SocketErrorCategory {
SOCKET_ERROR_CATEGORY_NETWORK = 0 ,
SOCKET_ERROR_CATEGORY_PROTOCOL ,
SOCKET_ERROR_CATEGORY_APPLICATION ,
SOCKET_ERROR_CATEGORY_TIMEOUT ,
SOCKET_ERROR_CATEGORY_RESOURCE ,
SOCKET_ERROR_CATEGORY_UNKNOWN
}
SocketErrorCategory - High-level classification of error types for policy decisions.
Functions
Arena_T Arena_new (void)
Create a new memory arena with initial capacity and thread-safe protection.
void Arena_dispose (Arena_T *ap)
Dispose of an arena and all its allocations, freeing underlying memory chunks.
void * Arena_alloc (Arena_T arena, size_t nbytes, const char *file, int line)
Allocate raw memory block from the specified arena.
void * Arena_calloc (Arena_T arena, size_t count, size_t nbytes, const char *file, int line)
Allocate and zero-initialize a block of memory elements from the arena.
void Arena_clear (Arena_T arena)
Reset the arena by invalidating all current allocations while preserving the arena for reuse.
void Except_raise (const Except_T *e, const char *file, int line)
Raise an exception (internal function - use RAISE() macro instead).
const char * Socket_safe_strerror (int errnum)
Provides a thread-safe and bounds-checked implementation of strerror().
void SocketConfig_set_max_memory (size_t max_bytes)
Sets the global memory limit enforced by all Arena allocators.
size_t SocketConfig_get_max_memory (void)
Retrieves the currently configured global memory limit.
size_t SocketConfig_get_memory_used (void)
Retrieves the total current memory allocated via Arenas.
void SocketCrypto_sha1 (const void *input, size_t input_len, unsigned char output[20])
Compute SHA-1 hash of input data (RFC 3174).
void SocketCrypto_sha256 (const void *input, size_t input_len, unsigned char output[32])
Compute SHA-256 hash of input data (FIPS 180-4).
void SocketCrypto_md5 (const void *input, size_t input_len, unsigned char output[16])
Compute MD5 hash of input data (RFC 1321).
void SocketCrypto_hmac_sha256 (const void *key, size_t key_len, const void *data, size_t data_len, unsigned char output[32])
Compute HMAC-SHA256 message authentication code.
ssize_t SocketCrypto_base64_encode (const void *input, size_t input_len, char *output, size_t output_size)
Encode binary data to Base64 string (RFC 4648).
ssize_t SocketCrypto_base64_decode (const char *input, size_t input_len, unsigned char *output, size_t output_size)
Decode Base64-encoded string to binary data (RFC 4648).
size_t SocketCrypto_base64_encoded_size (size_t input_len)
Calculate buffer size required for Base64 encoding.
size_t SocketCrypto_base64_decoded_size (size_t input_len)
Calculate maximum buffer size needed for Base64 decoding.
void SocketCrypto_hex_encode (const void *input, size_t input_len, char *output, int lowercase)
Encode binary data to hexadecimal string.
ssize_t SocketCrypto_hex_decode (const char *input, size_t input_len, unsigned char *output, size_t output_capacity)
Decode hexadecimal string to binary data.
int SocketCrypto_random_bytes (void *output, size_t len)
Generate cryptographically secure random bytes.
uint32_t SocketCrypto_random_uint32 (void)
Generate a cryptographically secure 32-bit random integer.
int SocketCrypto_websocket_accept (const char *client_key, char output[29])
Compute Sec-WebSocket-Accept value for server handshake (RFC 6455).
int SocketCrypto_websocket_key (char output[25])
Generate random Sec-WebSocket-Key for client handshake (RFC 6455).
int SocketCrypto_secure_compare (const void *a, const void *b, size_t len)
Perform constant-time comparison of two buffers.
void SocketCrypto_secure_clear (void *ptr, size_t len)
Securely clear sensitive data from memory.
void SocketSecurity_get_limits (SocketSecurityLimits *limits)
Retrieve all configured security limits into a structure for inspection.
size_t SocketSecurity_get_max_allocation (void)
Query the maximum allowed size for single memory allocations.
void SocketSecurity_get_http_limits (size_t *max_uri, size_t *max_header_size, size_t *max_headers, size_t *max_body)
Query specific HTTP protocol security limits.
void SocketSecurity_get_ws_limits (size_t *max_frame, size_t *max_message)
Query WebSocket-specific security limits for frame and message sizes.
void SocketSecurity_get_arena_limits (size_t *max_alloc)
Query the maximum allocation size limit for arenas.
void SocketSecurity_get_hpack_limits (size_t *max_table)
Query HPACK dynamic table size limit for HTTP/2 header compression.
int SocketSecurity_check_size (size_t size)
Validate a size value for safe memory allocation or buffer operations.
int SocketSecurity_check_multiply (size_t a, size_t b, size_t *result)
Validate multiplication of two sizes for potential overflow.
int SocketSecurity_check_add (size_t a, size_t b, size_t *result)
Validate addition of two sizes for potential overflow.
static size_t SocketSecurity_safe_multiply (size_t a, size_t b)
Compute product of two sizes with overflow protection (inline).
static size_t SocketSecurity_safe_add (size_t a, size_t b)
Compute sum of two sizes with overflow protection (inline).
static int SocketSecurity_has_tls (void)
Determine if the library was compiled with TLS support.
static int SocketSecurity_has_compression (void)
Determine if HTTP/1.1 content compression/decompression is supported.
void SocketLog_setcallback (SocketLogCallback callback, void *userdata)
Register a custom callback for all library log emissions.
SocketLogCallback SocketLog_getcallback (void **userdata)
Retrieve the currently registered custom logging callback and its userdata.
const char * SocketLog_levelname (SocketLogLevel level)
SocketLog_levelname - Human-readable string for SocketLogLevel enum.
void SocketLog_emit (SocketLogLevel level, const char *component, const char *message)
Emit a log message.
void SocketLog_emitf (SocketLogLevel level, const char *component, const char *fmt,...)
Emit a formatted log message using printf-style variable arguments.
void SocketLog_emitfv (SocketLogLevel level, const char *component, const char *fmt, va_list args)
Emit formatted log message using va_list for arguments.
void SocketLog_setlevel (SocketLogLevel min_level)
SocketLog_setlevel - Configure global minimum log level threshold.
SocketLogLevel SocketLog_getlevel (void)
Retrieve the active global minimum log level threshold.
void SocketLog_setcontext (const SocketLogContext *ctx)
Set thread-local logging context for request tracing and metadata.
const SocketLogContext * SocketLog_getcontext (void)
Retrieve pointer to current thread's logging context.
void SocketLog_clearcontext (void)
Reset thread-local logging context to default state.
void SocketLog_setstructuredcallback (SocketLogStructuredCallback callback, void *userdata)
Register callback for handling structured log emissions with fields.
void SocketLog_emit_structured (SocketLogLevel level, const char *component, const char *message, const SocketLogField *fields, size_t field_count)
Emit log message with attached structured key-value metadata fields.
void SocketMetrics_increment (SocketMetric metric, unsigned long value)
SocketMetrics_increment - Increment a metric counter.
void SocketMetrics_getsnapshot (SocketMetricsSnapshot *snapshot)
SocketMetrics_getsnapshot - Get atomic snapshot of all metrics.
void SocketMetrics_legacy_reset (void)
SocketMetrics_legacy_reset - Reset legacy metrics to zero.
const char * SocketMetrics_name (SocketMetric metric)
SocketMetrics_name - Get human-readable name for a metric.
size_t SocketMetrics_count (void)
SocketMetrics_count - Get total number of defined metrics.
static unsigned long long SocketMetrics_snapshot_value (const SocketMetricsSnapshot *snapshot, SocketMetric metric)
Get a specific value from metrics snapshot.
void SocketEvent_register (SocketEventCallback callback, void *userdata)
SocketEvent_register - Register an event handler.
void SocketEvent_unregister (SocketEventCallback callback, const void *userdata)
SocketEvent_unregister - Unregister an event handler.
void SocketEvent_emit_accept (int fd, const char *peer_addr, int peer_port, const char *local_addr, int local_port)
Event emission functions - Thread-safe notification of key socket events.
void SocketEvent_emit_connect (int fd, const char *peer_addr, int peer_port, const char *local_addr, int local_port)
Emit successful outbound connection event.
void SocketEvent_emit_dns_timeout (const char *host, int port)
Emit DNS resolution timeout event.
void SocketEvent_emit_poll_wakeup (int nfds, int timeout_ms)
Emit poll/epoll/kqueue wakeup event (for performance monitoring).
const char * Socket_GetLastError (void)
Socket_GetLastError - Retrieve the most recent formatted error message.
int Socket_geterrno (void)
Socket_geterrno - Retrieve the raw POSIX errno from the last system call error.Returns the errno value captured at the last error condition (via SOCKET_ERROR_* macros or manual socket_last_errno = errno). Thread-local storage ensures per-thread isolation without locks.
SocketErrorCode Socket_geterrorcode (void)
Socket_geterrorcode - Convert last errno to normalized SocketErrorCode.
SocketErrorCategory SocketError_categorize_errno (int err)
SocketError_categorize_errno - Classify errno into SocketErrorCategory.
int64_t Socket_get_monotonic_ms (void)
Socket_get_monotonic_ms - Get current monotonic time in milliseconds.
static unsigned socket_util_hash_fd (int fd, unsigned table_size)
Hash file descriptor using golden ratio multiplicative.
static unsigned socket_util_hash_ptr (const void *ptr, unsigned table_size)
Hash pointer using golden ratio multiplicative.
static unsigned socket_util_hash_uint (unsigned value, unsigned table_size)
Hash unsigned integer using golden ratio.
static unsigned socket_util_hash_uint_seeded (unsigned value, unsigned table_size, uint32_t seed)
Seeded hash for collision resistance in security contexts.
static unsigned socket_util_hash_djb2 (const char *str, unsigned table_size)
Hash string using DJB2 algorithm.
static unsigned socket_util_hash_djb2_len (const char *str, size_t len, unsigned table_size)
Hash string with explicit length using DJB2.
static unsigned socket_util_hash_djb2_ci (const char *str, unsigned table_size)
Case-insensitive DJB2 hash.
static unsigned socket_util_hash_djb2_ci_len (const char *str, size_t len, unsigned table_size)
Case-insensitive length-aware DJB2 hash.
static size_t socket_util_round_up_pow2 (size_t n)
Round up to next power of 2.
static char * socket_util_arena_strdup (Arena_T arena, const char *str)
Duplicate string into arena.
static char * socket_util_arena_strndup (Arena_T arena, const char *str, size_t maxlen)
Duplicate string with max length into arena.
static int64_t SocketTimeout_now_ms (void)
Get current monotonic time in milliseconds.
static int64_t SocketTimeout_deadline_ms (int timeout_ms)
Create deadline from timeout.
static int64_t SocketTimeout_remaining_ms (int64_t deadline_ms)
Calculate remaining time until deadline.
static int SocketTimeout_expired (int64_t deadline_ms)
Check if deadline has passed.
static int SocketTimeout_poll_timeout (int current_timeout_ms, int64_t deadline_ms)
Adjust poll timeout to not exceed deadline.
static int64_t SocketTimeout_elapsed_ms (int64_t start_ms)
Calculate elapsed time since start.
Variables
const Except_T Arena_Failed
Exception raised when arena allocation fails.
Except_Frame * Except_stack
Thread-local exception stack for TRY/EXCEPT/FINALLY blocks.
const Except_T Assert_Failed
Standard exception raised by failed assertions.
const Except_T SocketCrypto_Failed
General exception for cryptographic operation failures.
const Except_T SocketSecurity_SizeExceeded
Exception indicating security limit violation on size/ allocation.
const Except_T SocketSecurity_ValidationFailed
Exception for general input validation failures in security contexts.
Detailed Description
Base infrastructure for memory management, exception handling, and core utilities.
The Foundation group provides the fundamental building blocks used by all other modules in the socket library. Key components include:
Arena (memory): Region-based memory allocation with fast allocation/deallocation
Except (exceptions): Structured exception handling with TRY/EXCEPT/FINALLY
SocketUtil (utilities): Hash functions, error handling, logging
SocketMetrics (metrics): Comprehensive counters, gauges, and histograms for observability and monitoring
SocketConfig (configuration): Global configuration management
See also
Core I/O Modules for socket primitives built on Core Foundation Modules.
Arena_T for memory management
Except_T for exception handling
Event System Modules for modules using Core Foundation Modules components
Data Structure Documentation
Except_T
struct Except_T
Exception structure for structured error handling.
This value type (copyable struct, not opaque) encapsulates an exception instance with a type identifier (for matching in handlers) and a human-readable reason string. Serves as the payload for all raised exceptions in the system, enabling type-safe dispatch via pointer comparison in EXCEPT blocks.
Key characteristics:
Immutable after creation (const members)
Hierarchical via type chaining (e.type points to base or self)
Thread-safe for reading/copying (no internal state)
Used in Except_frame.exception for handler access
Module-specific exceptions derive conceptually from Assert_Failed or custom bases
Definition pattern for modules: extern const Except_T Module_Failed; // In .h const Except_T Module_Failed = { &BaseException, "Module-specific failure reason" }; // In .c
In handlers, access via Except_frame.exception->reason for details, and compare type.
Fields
Field Type Description
type const Except_T * Pointer to exception type (self or base for
hierarchy matching) | | reason | const char * | Null-terminated string describing the error (compile-time constant typically) |
Thread Safety\n Yes - immutable value type; safe to copy and read from any
thread.
Usage Example: Defining and Using Module Exception
// In module.h
extern const Except_T Socket_Failed;
// In module.c
#include "core/Except.h"
const Except_T Socket_Failed = {
  .type = &Assert_Failed,  // Or custom base
  .reason = "Socket operation failed (check errno)"
};
// Raising
void socket_connect(Socket_T s, ...) {
  TRY {
    // ...
    if (sys_call_fails) {
      RAISE(Socket_Failed);
    }
  } END_TRY;
}
// Handling
TRY {
  connect_socket(...);
} EXCEPT(Socket_Failed) {
  const Except_T *ex = Except_frame.exception;
  fprintf(stderr, "Socket error: %s (type: %p)\n", ex->reason, ex->type);
} END_TRY;
Note
Define exceptions as file-scope const for efficiency and linker dedup.
Warning
Never modify fields after definition; treat as immutable.
Reason strings should be static/constant to avoid lifetime issues.
Complexity\n O(1) - simple struct access.
See also
Assert_Failed for base assertion exception.
Except_frame.exception for runtime access in handlers.
RAISE for raising instances.
EXCEPT for type-based catching via pointer match.
docs/ERROR_HANDLING.md for defining custom exceptions and hierarchies.
Core Foundation Modules for related infrastructure.
Examples
/home/tetsuo/git/tetsuo-socket/include/core/SocketRateLimit.h.
Definition at line 216 of file Except.h.
Data Fields
const char * reason
Human-readable error description
const struct Except_T * type
Exception type identifier
SocketTimeouts_T
struct SocketTimeouts_T
Basic timeout configuration structure for socket operations.
Defines timeout parameters for core socket operations: connection establishment, DNS resolution, and general read/write operations. This structure provides a simple way to configure blocking vs non-blocking behavior across library APIs.
All fields are in milliseconds. A value of 0 means infinite timeout (block until completion, error, or interrupt). Negative values are invalid and may trigger assertions or defaults.
Lifecycle: Stack-allocated or embedded in larger configs; no allocation/free needed. Thread safety: Read-only after initialization; safe to share const instances. Used by high-level APIs like Socket_connect(), SocketHTTPClient, etc., for consistent timeout behavior.
Defaults: See constants like SOCKET_DEFAULT_CONNECT_TIMEOUT_MS (30s).
Fields
Field Default Description
connect_timeout_ms 30000 TCP connect timeout (ms, 0=infinite)
dns_timeout_ms 5000 DNS resolution timeout (ms, 0=infinite)
operation_timeout_ms 0 General I/O timeout (ms, 0=infinite)
Usage Example
SocketTimeouts_T timeouts = {
    .connect_timeout_ms = 5000,  // 5s connect
    .dns_timeout_ms = 2000,     // 2s DNS
    .operation_timeout_ms = 10000 // 10s I/O
};
// Pass to API functions
// e.g., Socket_connect_with_timeout(host, port, &timeouts); (hypothetical)
Note
These timeouts apply unless overridden by extended structs or per-function params.
Infinite timeouts (0) suitable for trusted clients; use finite in untrusted scenarios.
Warning
Very short values may cause unnecessary failures on slow networks.
See also
SocketTimeouts_Extended_T - Granular per-phase timeouts.
SOCKET_DEFAULT_CONNECT_TIMEOUT_MS - Compile-time defaults.
Socket_connect() - Applies connect_timeout_ms.
SocketDNS_T - Uses dns_timeout_ms for resolutions.
Core I/O Modules - Related socket operations.
docs/TIMEOUTS.md - Timeout best practices and tuning.
Definition at line 1500 of file SocketConfig.h.
Data Fields
int connect_timeout_ms
Connect timeout in ms (0 = infinite)
int dns_timeout_ms
DNS resolution timeout in ms (0 = infinite)
int operation_timeout_ms
General operation timeout in ms (0 = infinite)
SocketTimeouts_Extended_T
struct SocketTimeouts_Extended_T
Extended per-phase timeout configuration structure.
Provides granular control over timeouts for specific operation phases like DNS, connect, TLS handshake, and requests. Allows fine-tuning for production environments with varying latency characteristics per phase.
Precedence (highest to lowest):
Per-request timeouts (API-specific)
Per-socket extended timeouts (this structure)
Per-socket basic timeouts (SocketTimeouts_T)
Global defaults
Value meanings:
0: Use value from basic SocketTimeouts_T
-1: Infinite timeout (no limit)
Positive: Specific timeout in ms
See also
SocketTimeouts_T for basic timeouts.
SocketConfig.h constants like SOCKET_DEFAULT_TLS_TIMEOUT_MS for defaults.
SocketTLS_handshake() for TLS phase timeout usage.
Definition at line 1532 of file SocketConfig.h.
Data Fields
int connect_timeout_ms
TCP connect (0 = use basic, -1 = infinite)
int dns_timeout_ms
DNS resolution (0 = use basic, -1 = infinite)
int operation_timeout_ms
Default for other ops (0 = use basic, -1 = infinite)
int request_timeout_ms
Full request cycle (0 = use operation_timeout_ms)
int tls_timeout_ms
TLS handshake (0 = use operation_timeout_ms)
SocketSecurityLimits
struct SocketSecurityLimits
Aggregated security limits for runtime configuration inspection.
Opaque structure holding all library security limits: memory caps, protocol sizes, rate limits, timeouts, etc. Populated by get_limits(); fields are read-only constants derived from compile-time macros and feature flags.
Enables applications to query and log security posture, validate inputs dynamically, or adapt behavior based on build configuration (e.g., TLS enabled?). No mutable state; thread-safe to read after population.
Field Categories
Memory: Allocation/buffer/connection limits
HTTP: URI/headers/body for HTTP/1 & 2
Protocols: WS, TLS, HPACK specifics
Controls: Rate limits, timeouts
Full list in members below. When features disabled (e.g., no TLS), fields set to 0.
Usage Example
See SocketSecurity_get_limits() for population and field access example.
Note
Fields map directly to macros in SocketConfig.h, SocketHTTP.h, etc.
Thread Safety\n Yes (immutable after get_limits())
See also
SocketSecurity_get_limits() primary accessor.
Individual get_*_limits() for partial queries.
SocketConfig.h source of truth for limits.
Core Foundation Modules for base Security Modules infrastructure.
Definition at line 306 of file SocketSecurity.h.
Data Fields
size_t arena_max_alloc_size
Maximum single allocation permitted within Arena instances.
Subset of global max_allocation for pooled memory control.
Default: same as max_allocation (ARENA_MAX_ALLOC_SIZE)
See also
Arena_alloc()
Arena.h
size_t hpack_max_table_size
Maximum size for HPACK dynamic header table in HTTP/2 decompression.
Prevents memory exhaustion from header floods. Default: 64 KiB (SOCKETHPACK_MAX_TABLE_SIZE)
See also
SocketHPACK_Decoder_new()
SocketSecurity_get_hpack_limits()
size_t http1_max_chunk_size
Maximum size of a single chunk in chunked transfer-encoding.
Default: 16 MiB (SOCKETHTTP1_MAX_CHUNK_SIZE)
size_t http1_max_request_line
Max length of HTTP/1.1 request or status line.
Includes method/URI/version or status/reason. Default: 8 KiB
See also
SocketHTTP1_Parser_new()
size_t http2_max_concurrent_streams
Default max concurrent streams per HTTP/2 connection.
SETTINGS_MAX_CONCURRENT_STREAMS. Default: 100
See also
SocketHTTP2_config_defaults()
size_t http2_max_frame_size
Default max HTTP/2 frame size (16 KiB nominal).
SETTINGS_MAX_FRAME_SIZE lower bound.
See also
SocketHTTP2_Conn_process()
size_t http2_max_header_list_size
Max size for HTTP/2 header list (compressed via HPACK).
SETTINGS_MAX_HEADER_LIST_SIZE. Default: 16 KiB
See also
SocketHTTP2_Stream_send_headers()
size_t http_max_body_size
Maximum HTTP request/response body size.
Large upload/download protection. Default: 100 MiB (SOCKET_SECURITY_MAX_BODY_SIZE)
See also
SocketHTTPClient_get() etc.
SocketSecurity_get_http_limits()
size_t http_max_header_name
Max length for individual HTTP header names.
Default: 256 bytes (SOCKETHTTP_MAX_HEADER_NAME)
See also
SocketHTTP_Headers_add()
size_t http_max_header_size
Total size limit for all HTTP headers in a message.
Includes names/values/CRLF. Default: 64 KiB (SOCKETHTTP_MAX_HEADER_SIZE)
See also
SocketHTTP1_Parser_execute()
size_t http_max_header_value
Max length for individual HTTP header values.
Default: 8 KiB (SOCKETHTTP_MAX_HEADER_VALUE)
See also
SocketHTTP_Headers_set()
size_t http_max_headers
Maximum number of HTTP headers per message.
Prevents DoS via many tiny headers. Default: 100 (SOCKETHTTP_MAX_HEADERS)
size_t http_max_uri_length
Max length of HTTP URI/path in bytes.
Prevents long URI DoS/header injection.
Default: 8 KiB (SOCKETHTTP_MAX_URI_LEN)
See also
SocketHTTP_URI_parse()
size_t max_allocation
Maximum bytes for any single memory allocation anywhere in library.
Applies to malloc, Arena_alloc, SocketBuf_new, etc. Core DoS protection.
Default: 256 MiB (SOCKET_SECURITY_MAX_ALLOCATION)
See also
SocketSecurity_get_max_allocation()
SocketSecurity_check_size()
size_t max_buffer_size
Maximum capacity for per-connection I/O buffers (SocketBuf instances).
Limits memory per Socket/Connection to prevent exhaustion.
Default: 1 MiB (SOCKET_MAX_BUFFER_SIZE)
See also
SocketPool_new() bufsize param
SocketBuf_new()
size_t max_connections
Maximum number of connections allowed in SocketPool.
Caps concurrent resource usage (FDs, buffers, threads).
Default: 10000 (SOCKET_MAX_CONNECTIONS)
See also
SocketPool_new() maxconns param
SocketPool_resize()
size_t ratelimit_burst
Allowed burst capacity for connection rate limiting (tokens).
Allows short spikes. Default: 50 (SOCKET_RATELIMIT_DEFAULT_BURST)
See also
SocketPool_setconnrate() burst param
size_t ratelimit_conn_per_sec
Default connections per second global rate limit for pools/servers.
Token bucket rate. Default: 100/s (SOCKET_RATELIMIT_DEFAULT_CONN_PER_SEC)
See also
SocketPool_setconnrate()
SocketRateLimit.h
size_t ratelimit_max_per_ip
Default maximum concurrent connections per client IP.
Per-IP flood protection. Default: 10 (SOCKET_RATELIMIT_DEFAULT_MAX_PER_IP)
See also
SocketPool_setmaxperip()
int timeout_connect_ms
Default timeout for Socket_connect() and TLS handshakes.
Prevents hanging connections. Default: 30s (SOCKET_DEFAULT_CONNECT_TIMEOUT_MS)
See also
Socket_connect()
SocketTLS_handshake()
int timeout_dns_ms
Default timeout for DNS resolutions (SocketDNS).
Default: 5s (SOCKET_DEFAULT_DNS_TIMEOUT_MS)
See also
SocketDNS_resolve_sync()
int timeout_idle_ms
Default idle timeout for connections (ms).
Converted from seconds * 1000. Closes inactive conns.
Default: 5min (SOCKET_DEFAULT_IDLE_TIMEOUT)
See also
SocketPool_cleanup()
Connection_lastactivity()
int timeout_request_ms
Maximum permitted value for request timeouts.
Caps user-configured timeouts to prevent indefinite holds.
Default: 60s (SOCKET_SECURITY_MAX_REQUEST_TIMEOUT_MS)
See also
Socket_set_timeout()
size_t tls_max_alpn_len
Max length of a single ALPN protocol string (e.g., "h2", "http/1.1").
Per RFC, <=255. (SOCKET_TLS_MAX_ALPN_LEN)
See also
SocketTLS_set_alpn_protocols()
size_t tls_max_alpn_protocols
Max number of ALPN protocol identifiers in TLS extension list.
Limits negotiation options. Default: 16 (SOCKET_TLS_MAX_ALPN_PROTOCOLS)
See also
SocketTLSContext_add_alpn_protocol()
size_t tls_max_alpn_total_bytes
Total byte limit for entire ALPN protocol list wire encoding.
Additional DoS protection beyond per-protocol limits. Custom, e.g., 1024 bytes.
size_t tls_max_cert_chain_depth
Max depth for X.509 certificate chain validation during handshake.
Prevents DoS from deeply nested chains. Default: 10 (SOCKET_TLS_MAX_CERT_CHAIN_DEPTH)
See also
SocketTLSContext_set_verify_depth()
SocketTLS_handshake()
size_t tls_session_cache_size
Number of resumable TLS sessions in internal cache.
Improves performance on reconnects. Default: 1000 (SOCKET_TLS_SESSION_CACHE_SIZE)
See also
SocketTLSContext_set_session_cache_size()
size_t ws_max_frame_size
Max size for single WebSocket frame payload (RFC 6455).
Prevents large frame DoS. Default: 16 MiB (SOCKETWS_MAX_FRAME_SIZE)
See also
SocketSecurity_get_ws_limits()
size_t ws_max_message_size
Max aggregated size for multi-frame WebSocket messages (text/binary).
Covers fragmented messages. Default: 64 MiB (SOCKETWS_MAX_MESSAGE_SIZE)
See also
SocketWS_handle_frame()
SocketLogContext
struct SocketLogContext
SocketLogContext - Thread-local logging context for correlation.
Thread-local structure for adding correlation data to logs, enabling distributed tracing, request tracking, and connection-specific logging. Custom logging callbacks (SocketLogCallback or SocketLogStructuredCallback) can access this structure via SocketLog_getcontext() to include fields like trace_id, request_id, and connection_fd in log output (e.g., as JSON).
Usage pattern: SocketLogContext ctx = {0}; strncpy(ctx.trace_id, trace_uuid, sizeof(ctx.trace_id) - 1); ctx.connection_fd = sock_fd; SocketLog_setcontext(&ctx); // ... perform operations - logs now include context ... SocketLog_clearcontext(); // Or let it persist for thread lifetime
See also
SocketLog_setcontext() to establish context for current thread.
SocketLog_getcontext() to retrieve current context in callbacks.
SocketLog_clearcontext() to reset context.
SocketLogStructuredCallback for structured logging integration.
SocketEvent_emit_*() functions automatically set connection_fd.
Definition at line 602 of file SocketUtil.h.
Data Fields
int connection_fd
Associated file descriptor (-1 if none)
char request_id[37]
Request-specific ID
char trace_id[37]
Distributed trace ID (e.g., UUID)
SocketLogField
struct SocketLogField
SocketLogField - Key-value pair for structured logging.
Simple key-value structure for attaching metadata to log messages. Used by SocketLog_emit_structured() to enable machine-readable output. Keys are field names (e.g., "status_code", "response_time_ms", "user_id"). Values are pre-formatted strings (numbers as strings, escaped JSON if needed).
Lifetime: Keys and values must remain valid until the structured log callback completes. Do not pass stack strings that may go out of scope.
Example usage with SOCKET_LOG_FIELDS macro: SocketLog_emit_structured(SOCKET_LOG_INFO, "HTTP", "Request processed", SOCKET_LOG_FIELDS({"method", "GET"}, {"status", "200"}, {"bytes", "1024"}, {"user_agent", ua_str}));
See also
SocketLog_emit_structured() for emitting structured logs.
SocketLogStructuredCallback for processing fields in callbacks.
SOCKET_LOG_FIELDS() convenience macro for array initialization.
SocketLogContext for additional thread-local metadata.
Note
For security, avoid logging sensitive data in fields (use secureclear).
Integrates with SocketMetrics for performance fields like latencies.
Definition at line 753 of file SocketUtil.h.
Data Fields
const char * key
Field name (e.g., "fd", "bytes", "peer")
const char * value
Field value as string
SocketMetricsSnapshot
struct SocketMetricsSnapshot
SocketMetricsSnapshot - Thread-safe snapshot of all library metrics.
Structure holding atomic copies of all SocketMetric counters. Obtained via SocketMetrics_getsnapshot() for reporting without contention. Array values[] indexed by SocketMetric enum (size SOCKET_METRIC_COUNT).
Usage: SocketMetricsSnapshot snap; SocketMetrics_getsnapshot(&snap); // Export snap.values[SOCKET_METRIC_SOCKET_CONNECT_SUCCESS] etc. // Or use SocketMetrics_snapshot_value(&snap, metric) helper.
Thread Safety: Snapshot is atomic read; safe to access from any thread after acquisition. No locking needed for reading snapshot contents.
Export Patterns:
Prometheus: Counter metrics with labels for module/component.
StatsD: Increment during runtime, flush snapshots periodically.
Logging: Structured logs with snapshot deltas for audits.
See also
SocketMetrics_getsnapshot() to capture current state.
SocketMetrics_snapshot_value() inline accessor.
SocketMetric for counter indices and descriptions.
SocketMetrics_increment() for updating underlying counters.
docs/METRICS.md for integration examples and best practices.
Note
Size fixed by SOCKET_METRIC_COUNT; adding metrics requires recompilation.
Use unsigned long long for 64-bit counters supporting high-volume systems.
Definition at line 948 of file SocketUtil.h.
Data Fields
unsigned long long values[SOCKET_METRIC_COUNT]
Macro Definition Documentation
ALLOC
#define ALLOC (arena, nbytes) (Arena_alloc ((arena), (nbytes), __FILE__, __LINE__))
Convenience macro for Arena_alloc with automatic source location tracking.
Wraps Arena_alloc(arena, nbytes, FILE, LINE) to inject compilation-time file and line info for enhanced debugging, leak detection, and profiling. Essential for production code to trace allocation sites without boilerplate.
Macro expansion is transparent: no additional runtime cost beyond the function call. Preferred over direct Arena_alloc unless custom location needed.
Parameters
[in] arena Arena_T to allocate from.
[in] nbytes size_t number of bytes.
Returns
void* allocated memory; NULL if nbytes == 0.
Exceptions
Arena_Failed Propagated from Arena_alloc on failure.
Thread Safety\n Yes - forwards to thread-safe implementation.
Standard Usage
TRY {
    Arena_T arena = Arena_new();
    char *buffer = ALLOC(arena, 4096);  // Location tracked automatically
    // Use buffer...
    // No free(); arena manages
} EXCEPT(Arena_Failed) {
    // Allocation error
} END_TRY;
Note
Macro captures exact allocation site for tools like valgrind or custom debuggers.
Safe in all contexts where Arena_alloc is valid.
Warning
nbytes == 0 returns NULL harmlessly.
Complexity\n Same as Arena_alloc: amortized O(1).
See also
Arena_alloc(arena, nbytes, file, line) for manual location override.
CALLOC(arena, count, nbytes) for zero-initialized variant.
Arena_new() prerequisite for valid arena.
Definition at line 502 of file Arena.h.
ARENA_ALIGNMENT_SIZE
#define ARENA_ALIGNMENT_SIZE sizeof (union align)
Arena alignment size.
Size of the alignment union, ensuring proper alignment for all data types.
See also
union align
Definition at line 1768 of file SocketConfig.h.
ARENA_CHUNK_NOT_REUSED
#define ARENA_CHUNK_NOT_REUSED 0
Arena chunk not reused indicator.
Definition at line 1822 of file SocketConfig.h.
ARENA_CHUNK_REUSED
#define ARENA_CHUNK_REUSED 1
Arena chunk reused indicator.
Definition at line 1813 of file SocketConfig.h.
ARENA_CHUNK_SIZE
#define ARENA_CHUNK_SIZE (10 * 1024) /* 10KB */
Default arena chunk size.
Memory blocks are allocated in chunks of this size.
See also
Arena_T for arena memory management.
Definition at line 416 of file SocketConfig.h.
ARENA_ENOMEM
#define ARENA_ENOMEM "Out of memory"
Arena out of memory error message.
Definition at line 1849 of file SocketConfig.h.
ARENA_ERROR_BUFSIZE
#define ARENA_ERROR_BUFSIZE 256
Buffer size for arena error messages.
Definition at line 450 of file SocketConfig.h.
ARENA_FAILURE
#define ARENA_FAILURE (-1)
Arena operation failure code.
Definition at line 1804 of file SocketConfig.h.
ARENA_MAX_ALLOC_SIZE
#define ARENA_MAX_ALLOC_SIZE SOCKET_SECURITY_MAX_ALLOCATION /* Matches centralized limit */
Maximum allocation size for arena.
Matches centralized security limit to prevent overflow attacks.
See also
SOCKET_MAX_BUFFER_SIZE for buffer size limits.
Definition at line 428 of file SocketConfig.h.
ARENA_MAX_FREE_CHUNKS
#define ARENA_MAX_FREE_CHUNKS 10
Maximum number of free chunks to cache for reuse.
Prevents excessive memory retention while enabling allocation reuse.
See also
Arena_T for arena implementation.
Definition at line 441 of file SocketConfig.h.
ARENA_SIZE_INVALID
#define ARENA_SIZE_INVALID 0
Arena size validation failure.
Definition at line 1840 of file SocketConfig.h.
ARENA_SIZE_VALID
#define ARENA_SIZE_VALID 1
Arena size validation success.
Definition at line 1831 of file SocketConfig.h.
ARENA_SUCCESS
#define ARENA_SUCCESS 0
Arena operation success code.
Definition at line 1795 of file SocketConfig.h.
ARENA_VALIDATION_FAILURE
#define ARENA_VALIDATION_FAILURE 0
Arena validation failure code.
Definition at line 1786 of file SocketConfig.h.
ARENA_VALIDATION_SUCCESS
#define ARENA_VALIDATION_SUCCESS 1
Arena validation success code.
Definition at line 1777 of file SocketConfig.h.
CALLOC
#define CALLOC (arena, count, nbytes) (Arena_calloc ((arena), (count), (nbytes), __FILE__, __LINE__))
Convenience macro for zero-initialized multi-element allocation with source tracking.
Calls Arena_calloc(arena, count, nbytes, FILE, LINE) to allocate count elements of nbytes each, zero them, and record allocation site automatically. Standard pattern for safe struct/array init in arena-managed memory.
Includes overflow protection and atomic zeroing.
Parameters
[in] arena Arena_T for allocation.
[in] count size_t number of elements.
[in] nbytes size_t bytes per element.
Returns
void* to zeroed block; NULL on zero size.
Exceptions
Arena_Failed On underlying failure (alloc, overflow).
Thread Safety\n Yes - via Arena_calloc.
Common Patterns
TRY {
    // Zeroed array
    double *values = CALLOC(arena, 50, sizeof(double));
    // Zeroed single struct
    HeaderEntry *header = CALLOC(arena, 1, sizeof(HeaderEntry));
    // Fields safe: pointers NULL, numerics 0
} EXCEPT(Arena_Failed) {
    // Handle
} END_TRY;
Note
Use sizeof(Type) for nbytes to ensure correctness.
Equivalent to alloc + memset but with debug info and checks.
Warning
Large count * nbytes may be slow due to memset; profile if needed.
Complexity\n Amortized O(1) alloc + O(count * nbytes) zeroing.
See also
Arena_calloc() for direct function with manual file/line.
ALLOC() for uninitialized faster alloc.
sizeof for element sizing.
Definition at line 551 of file Arena.h.
ELSE
#define ELSE
Value:
  EXCEPT_POP_FRAME_IF_ENTERED                                                 \
  }                                                                           \
  else                                                                        \
  {                                                                           \
    Except_flag = Except_handled;
Catch any exception not caught by previous EXCEPT blocks.
This macro provides a catch-all handler for any exception raised in the preceding TRY block that did not match any prior EXCEPT blocks. It executes when an exception is pending (Except_flag == Except_raised) but no specific handler claimed it.
Serves as the default case in exception dispatching, useful for generic error handling, logging unexpected errors, or providing fallback recovery mechanisms. After execution, sets Except_flag to Except_handled unless RERAISE is called.
Behavior:
Automatically triggers on unhandled exceptions from TRY
Access full Except_frame details (exception, reason, file, line)
Only one ELSE per TRY block; placement after all EXCEPTs
Integrates with FINALLY for post-handling cleanup
Best practices:
Use for logging/tracing unexpected exceptions
Decide to RERAISE for propagation or handle terminally
Avoid swallowing exceptions without logging
Edge cases:
No exception raised: ELSE skipped entirely
After ELSE, unhandled exceptions re-raised by END_TRY
Can chain with RERAISE to outer handlers
Parameters
None - triggers on any unmatched exception type.
Returns
None - executes fallback handler code if triggered.
Exceptions
None directly; may re-raise via RERAISE.
Thread Safety\n No - updates thread-local Except_flag and interacts with stack.
Basic Usage Example
extern const Except_T KnownError;
void operation_with_fallback() {
  TRY {
    risky_code();  // May raise KnownError or unexpected exceptions
  } EXCEPT(KnownError) {
    // Handle known case
    recover_from_known();
  } ELSE {
    // Fallback for unknown/unexpected exceptions
    log_unexpected(Except_frame.exception->reason,
                   Except_frame.file, Except_frame.line);
    // Option 1: Terminate handling
    // return; or set error state
    // Option 2: Propagate
    // RERAISE;
  } FINALLY {
    cleanup();
  } END_TRY;
}
Logging and Propagation
TRY {
  // ...
} EXCEPT(NetworkError) {
  // Specific
} EXCEPT(MemoryError) {
  // Specific
} ELSE {
  // Generic handling for all others
  metrics_increment(UNEXPECTED_EXCEPTION);
  error_report("Caught unexpected: %s at %s:%d",
               Except_frame.exception->reason,
               Except_frame.file, Except_frame.line);
  RERAISE;  // Let outer handler deal with it
} END_TRY;
Note
Provides safety net for unanticipated exceptions in robust code.
Warning
Only one ELSE per TRY; multiple compile to invalid syntax.
Must follow all EXCEPT blocks; order matters for dispatching.
Always log or report in ELSE to avoid silent failures.
Complexity\n O(1) - simple flag check and execution.
See also
EXCEPT for specific type matching.
TRY for block initiation.
RERAISE to continue propagation from ELSE.
FINALLY for code after ELSE execution.
END_TRY for block closure and unhandled re-raise.
docs/ERROR_HANDLING.md for catch-all strategies and error reporting.
Definition at line 1208 of file Except.h.
END_TRY
#define END_TRY
Value:
  EXCEPT_POP_FRAME_IF_ENTERED                                                 \
  }                                                                           \
  if (Except_flag == Except_raised)                                           \
    RERAISE;                                                                  \
  }                                                                           \
  while (0)
Complete a TRY/EXCEPT/FINALLY exception handling block.
This macro finalizes the exception handling construct by popping the current exception frame from the thread-local stack, executing any pending FINALLY block (if not already), and re-raising any unhandled exceptions (Except_flag == Except_raised) to propagate them to outer TRY blocks or terminate the program.
Cleanup sequence:
Calls EXCEPT_POP_FRAME_IF_ENTERED to remove frame if entered normally
Checks for pending raised exceptions and invokes RERAISE if needed
Ensures all local variables (Except_flag, Except_frame) are scoped correctly
Closes the do-while(0) loop structure for TRY expansion
Essential for proper resource management and exception propagation. Without END_TRY, frames leak, unhandled exceptions are forgotten, and control flow breaks.
Behavior on exit paths:
Normal completion: stack cleaned, no re-raise
Handled exception: stack cleaned, no re-raise
Unhandled: RERAISE propagates via longjmp()
Early RETURN: already handled via macro, END_TRY finalizes
Edge cases:
Missing END_TRY: compile/link errors or runtime corruption
Nested blocks: each requires own END_TRY
Unhandled in top-level: may terminate program (depends on Except_raise impl)
Parameters
None - concludes the entire TRY construct.
Returns
None - restores normal control flow or propagates via re-raise.
Exceptions
Re-raises unhandled exceptions from this block.
Thread Safety\n No - finalizes thread-local frame and flag state.
Complete Block Example
// Full TRY construct
TRY {
  // Acquisition and protected code
  resource = acquire_resource();
  if (!resource) RAISE(AcquireFailed);
  use_resource(resource);
} EXCEPT(AcquireFailed) {
  // Handle acquisition failure
  error_state = ACQUIRE_ERROR;
} EXCEPT(UseFailed) {
  // Handle usage error
  partial_rollback();
  RERAISE;  // Propagate if needed
} ELSE {
  // Unexpected
  emergency_shutdown();
} FINALLY {
  // Release regardless
  release_resource(resource);
} END_TRY;  // Cleans up, re-raises if unhandled
Minimal TRY-EXCEPT-END_TRY
TRY {
  risky_op();
} EXCEPT(KnownError) {
  recover();
} END_TRY;  // Handles cleanup and propagation
Top-Level Unhandled Propagation
// In main or top function
TRY {
  main_logic();
} EXCEPT(AnyError) {
  // Last chance
  log_fatal();
  // No RERAISE - terminate gracefully
} FINALLY {
  global_cleanup();
} END_TRY;
// If unhandled here, program ends with default handler
Note
Always pair with TRY; forms complete exception handling unit.
Warning
Omitting END_TRY leads to leaks and undefined behavior.
Position after all EXCEPT/ELSE/FINALLY in sequence.
Unhandled exceptions re-raised - ensure outer handling or termination strategy.
Complexity\n O(1) - frame pop and conditional RERAISE.
See also
TRY for block start.
EXCEPT/ELSE for handlers leading to END_TRY.
FINALLY for pre-END_TRY cleanup.
RERAISE mechanism invoked by END_TRY for propagation.
docs/ERROR_HANDLING.md for complete constructs, nesting, and top-level handling.
Definition at line 1439 of file Except.h.
EXCEPT
#define EXCEPT (e)
Value:
  EXCEPT_POP_FRAME_IF_ENTERED                                                 \
  }                                                                           \
  else if (Except_frame.exception && Except_frame.exception->type == &(e))    \
  {                                                                           \
    Except_flag = Except_handled;
Catch a specific exception type within a TRY block.
This macro defines a handler for a specific exception type caught from the preceding TRY block. It compares the raised exception's type pointer exactly with the provided exception variable e. If matching, executes the handler code and sets Except_flag to Except_handled, allowing subsequent FINALLY or END_TRY processing.
Supports chaining multiple EXCEPT blocks for different exception types, evaluated in order (first match wins). Non-matching exceptions propagate to ELSE or outer handlers.
Behavior details:
Pops frame if entered normally (Except_flag == Except_entered)
Exact pointer match on e->type == raised->type
Access Except_frame.exception->reason for error details in handler
After handler, exception is considered handled unless RERAISE used
Best practices:
Order most specific exceptions first
Use for recovery, logging, or partial handling
Combine with FINALLY for resource cleanup
Edge cases:
No preceding TRY: compile error (macro expansion assumes frame)
Multiple matches: only first EXCEPT triggers
RERAISE in handler propagates to outer scopes
Parameters
[in] e Exception variable defining the type to catch (e.g., Socket_Failed). Uses &e for comparison.
Returns
None - executes handler block if match, otherwise skips.
Exceptions
None - handles rather than throws; use RERAISE to propagate.
Thread Safety\n No - accesses and modifies thread-local Except_flag and stack.
Basic Usage Example
extern const Except_T Socket_Failed;
extern const Except_T Memory_Failed;
void connect_with_recovery(const char *host, int port) {
  Socket_T sock = NULL;
  TRY {
    sock = Socket_new(AF_INET, SOCK_STREAM, 0);
    Socket_connect(sock, host, port);  // May raise Socket_Failed
    // Or other ops raising Memory_Failed
  } EXCEPT(Socket_Failed) {
    // Specific network error handling
    fprintf(stderr, "Connection failed: %s\n",
Except_frame.exception->reason); sock = NULL;  // Indicate failure }
EXCEPT(Memory_Failed) {
    // Handle OOM separately
    perror("Memory allocation failed");
    abort();  // Or RERAISE;
  } FINALLY {
    if (sock) Socket_free(&sock);  // Always cleanup
  } END_TRY;
  // Use sock or handle NULL
}
Chained Handlers with Propagation
TRY {
  operation_that_may_fail();
} EXCEPT(SpecificError) {
  // Handle specifically
  log_specific(SpecificError);
  RERAISE;  // Propagate for general handling
} EXCEPT(AnotherError) {
  // Alternative handling
} ELSE {
  // Catch-all for unexpected exceptions
  log_unexpected(Except_frame.exception);
  RERAISE;  // Or handle terminally
} END_TRY;
Note
Compare using exact exception variable; subtypes not supported (use base types for hierarchy).
Warning
Pointer comparison only - different variables with same structure won't match.
Place after TRY, before ELSE/FINALLY/END_TRY in sequence.
Complexity\n O(1) - direct pointer comparison and flag update.
See also
TRY for initiating the protected block.
ELSE for handling unmatched exceptions.
RERAISE to propagate from within handler.
FINALLY for code executing after handling.
END_TRY to close block and re-raise unhandled.
docs/ERROR_HANDLING.md for handler ordering, exception hierarchies, and recovery patterns.
Definition at line 1105 of file Except.h.
EXCEPT_POP_FRAME_IF_ENTERED
#define EXCEPT_POP_FRAME_IF_ENTERED
Value:
  if (Except_flag == Except_entered)                                          \
    {                                                                         \
      Except_Frame *prev_frame = NULL;                                        \
      if (Except_stack != NULL)                                               \
        prev_frame = Except_stack->prev;                                      \
      Except_stack = prev_frame;                                              \
    }
Internal helper macro for exception frame cleanup.
Utility macro invoked by EXCEPT, ELSE, FINALLY, and END_TRY to conditionally pop the current exception frame from Except_stack if the TRY block was entered normally (Except_flag == Except_entered) without raising an exception.
Ensures stack integrity on all exit paths:
Normal completion: pop frame
Raised exception: defer pop until handled or propagated
Avoids leaks in non-exceptional paths
Implementation:
Checks Except_flag state
If entered: save prev = stack->prev, then stack = prev (pop)
No-op if already raised/handled (frame still needed for info)
Used internally to balance TRY pushes with pops.
Note
Strictly internal; part of macro expansion - users never invoke directly.
Warning
Modifies global Except_stack; context-sensitive.
// Appears in expansions like:
#define EXCEPT(e) \
  EXCEPT_POP_FRAME_IF_ENTERED \
  } else if (...) { \
    // handler
See also
TRY for corresponding push.
END_TRY for final cleanup.
Except_stack for the stack variable.
Definition at line 866 of file Except.h.
FINALLY
#define FINALLY
Value:
  EXCEPT_POP_FRAME_IF_ENTERED                                                 \
  }                                                                           \
  {                                                                           \
    if (Except_flag == Except_entered)                                        \
      Except_flag = Except_finalized;
Define cleanup code that executes regardless of exceptions.
This macro defines a block of code guaranteed to execute upon exit from the TRY/EXCEPT/ELSE handlers, irrespective of whether an exception was raised, handled, or propagated. It implements the finally clause semantics for resource management, ensuring cleanup occurs on all control flow paths: normal return, early RETURN, exception handling, or re-raise via RERAISE.
Execution timing:
After TRY (normal path)
After each EXCEPT/ELSE handler (if exception caught)
Before END_TRY re-raises unhandled exceptions
Even if RERAISE called in handlers (post-handler cleanup)
Critical for RAII-like patterns in C: file closes, socket frees, memory releases, locks unlocks, etc. Prevents leaks in exceptional paths.
Behavior details:
Checks Except_flag == Except_entered to finalize if no exception
Integrates with frame popping via EXCEPT_POP_FRAME_IF_ENTERED
No exception propagation from FINALLY; errors inside are not caught by this block
Best practices:
Place resource acquisition in TRY, cleanup in FINALLY
Keep FINALLY idempotent (safe to call multiple times)
Avoid raising exceptions in FINALLY (use logging instead)
Use volatile for shared state if needed
Edge cases:
Empty FINALLY: compiles but executes nothing
Multiple FINALLY: compile error (only one allowed)
FINALLY before EXCEPT: invalid sequence, use correct order
Parameters
None - defines cleanup block post-handlers.
Returns
None - executes cleanup code unconditionally on exit paths.
Exceptions
Exceptions raised in FINALLY propagate outside the TRY block.
Thread Safety\n No - updates local Except_flag; thread-local context.
Basic Resource Cleanup Example
FILE *file = NULL;
TRY {
  file = fopen("data.txt", "r");  // May fail
  if (!file) RAISE(FileOpenFailed);
  // Process file...
} EXCEPT(FileOpenFailed) {
  // Handle open error
} EXCEPT(OtherError) {
  // Handle processing error
} FINALLY {
  // Guaranteed cleanup regardless of path
  if (file) {
    fclose(file);
    file = NULL;
  }
} END_TRY;
With Early Return and RERAISE
Socket_T sock;
TRY {
  sock = Socket_new(...);
  if (connect_fails) RETURN NULL;  // FINALLY still executes
  // Normal ops
} EXCEPT(SocketError) {
  log_error();
  RERAISE;  // FINALLY executes before propagation
} FINALLY {
  Socket_free(&sock);  // Always called
} END_TRY;
Nested Cleanup
TRY {  // Outer
  outer_resource();
  TRY {  // Inner
    inner_resource();
  } FINALLY {
    inner_cleanup();  // Inner first
  } END_TRY;
} FINALLY {
  outer_cleanup();  // Then outer
} END_TRY;
Note
FINALLY ensures deterministic cleanup, complementing RAII where possible.
Warning
Do not rely on FINALLY for exception handling; use EXCEPT for that.
Exceptions in FINALLY escape the block - catch in outer TRY if needed.
Only one per TRY; follows EXCEPT/ELSE in sequence.
Complexity\n O(1) - conditional flag check and execution.
See also
TRY for resource acquisition.
EXCEPT/ELSE for error paths leading to FINALLY.
RERAISE interaction with FINALLY execution.
END_TRY for final block closure.
RETURN for early exit triggering FINALLY.
docs/ERROR_HANDLING.md for cleanup patterns, idempotency, and nesting.
Definition at line 1326 of file Except.h.
HASH_GOLDEN_RATIO
#define HASH_GOLDEN_RATIO 2654435761u
Golden ratio constant for multiplicative hashing.
Calculated as 2^32 * (sqrt(5)-1)/2. Used for optimal hash distribution in hash tables.
See also
socket_util_hash_fd() for hash function usage.
Definition at line 1730 of file SocketConfig.h.
RAISE
#define RAISE (e) Except_raise (&(e), __FILE__, __LINE__)
Raise an exception with current file and line information.
This macro raises the specified exception variable, automatically capturing the current source file (FILE) and line number (LINE) for debugging. It expands to a call to Except_raise(&(e), FILE, LINE), transferring control via longjmp() to the nearest enclosing TRY block's exception handler.
Use this macro in error conditions to provide structured error handling. The exception will propagate up the call stack until caught or the program terminates.
Edge cases:
If called outside a TRY block, leads to undefined behavior (stack corruption possible)
e must be an lvalue (variable); expressions like &SomeException won't work correctly
Thread-local; each thread's exception stack is independent
Parameters
[in] e Exception variable to raise (e.g., Socket_Failed, Arena_Failed). Must be a variable name, not an expression or temporary.
Returns
Does not return normally; control transfers to exception handler via longjmp().
Exceptions
The specified exception e (propagates via non-local jump).
Thread Safety\n No - modifies thread-local exception stack.
Usage Example
#include "core/Except.h"
extern const Except_T MyModule_Failed;
void risky_operation() {
  TRY {
    // Simulate error condition
    if (some_condition_fails()) {
      RAISE(MyModule_Failed);  // Raises with current file/line
    }
    // Normal code path
  } EXCEPT(MyModule_Failed) {
    // Specific handling
    fprintf(stderr, "Operation failed at %s:%d: %s\n",
            Except_frame.file, Except_frame.line, e.reason);
  } FINALLY {
    // Always execute cleanup
    cleanup_resources();
  } END_TRY;
}
Advanced Usage with Custom Exception
// Define module exception
const Except_T MyModule_Failed = { &Assert_Failed, "MyModule operation
failed" };
TRY {
  // ...
  if (validation_error) {
    RAISE(MyModule_Failed);
  }
} EXCEPT(MyModule_Failed) {
  // Recover or log
  RERAISE;  // Propagate if not recoverable
} END_TRY;
Note
For custom exceptions, define as: const Except_T MyError = { &Some_Base, "reason" };
Warning
Must be called within a TRY block; otherwise undefined behavior.
Avoid in signal handlers or other contexts where longjmp is unsafe.
Complexity\n O(1) - constant time, modulo stack unwinding cost.
See also
Except_raise() for low-level implementation details.
TRY for establishing exception handling context.
EXCEPT for catching specific exceptions.
RERAISE for propagating caught exceptions.
docs/ERROR_HANDLING.md for exception best practices and module exception declaration.
Definition at line 636 of file Except.h.
RERAISE
#define RERAISE
Value:
  Except_raise ((const Except_T *)Except_frame.exception, Except_frame.file,  \
                Except_frame.line)
Re-raise the currently caught exception.
This macro re-raises the exception that was caught by the current EXCEPT or ELSE block. It uses the information stored in the current Except_frame (exception, file, line) to propagate the exception up the call stack to the next enclosing TRY block.
Useful for error recovery or logging where the exception is handled locally but needs to be propagated for higher-level handling. Allows chaining of exception handlers.
Behavior:
Extracts exception details from Except_frame (set by the original RAISE)
Performs longjmp() to unwind to parent frame
Preserves original raise location and reason for debugging
Only valid after an exception has been caught (Except_flag == Except_handled)
Edge cases:
Calling outside handler context leads to invalid memory access or wrong exception
Propagates through multiple levels until caught or stack exhausted
Parameters
None - uses current thread-local Except_frame data.
Returns
Does not return normally; re-raises via longjmp().
Exceptions
The originally caught exception (propagated upward).
Thread Safety\n No - relies on and modifies thread-local exception state.
Usage Example
TRY {
  // Nested operation
  inner_function();  // Might raise Socket_Failed
} EXCEPT(Socket_Failed) {
  // Local handling: log the error
  log_error("Socket error in inner_function: %s",
Except_frame.exception->reason);
  // But propagate for higher-level handling
  RERAISE;  // Re-raises the same Socket_Failed exception
} FINALLY {
  // Cleanup
} END_TRY;
Multi-Level Propagation
// Outer handler
TRY {
  risky_call();
} EXCEPT(Socket_Failed) {
  // Final handling or abort
  fprintf(stderr, "Unrecoverable socket failure\n");
  // No RERAISE here - exception stops propagating
} END_TRY;
// Inner function (called by risky_call)
void risky_call() {
  TRY {
    // ...
    if (error) RAISE(Socket_Failed);
  } EXCEPT(Socket_Failed) {
    // Partial recovery or additional checks
    RERAISE;  // Continue propagation
  } END_TRY;
}
Note
RERAISE preserves the original exception details for accurate debugging.
Warning
Only use within EXCEPT/ELSE blocks after exception caught.
Does not create new exception frame; reuses current one.
Complexity\n O(1) - direct use of frame data and longjmp.
See also
RAISE() for initial exception raising.
EXCEPT for catching and entering handler context.
Except_raise() for low-level re-raising mechanism.
TRY for enclosing context required.
docs/ERROR_HANDLING.md for propagation patterns and best practices.
Definition at line 725 of file Except.h.
RETURN
#define RETURN
Value:
  switch (Except_stack = ((Except_Frame *)Except_stack)->prev, 0)             \
  default:                                                                    \
    return
Return from function while cleaning up exception stack.
This macro provides a safe way to return from a function within a TRY block, automatically popping the current exception frame from the thread-local stack before executing the return statement. Prevents exception stack leaks when exiting early from protected code regions.
Implementation uses a switch statement with comma operator to perform the stack cleanup as a side effect, ensuring compatibility with complex return expressions including those with commas (e.g., RETURN a ? b : c;).
Essential for maintaining exception handling integrity and avoiding resource leaks or corrupted stack states in multi-level TRY scenarios.
Edge cases:
Only affects current frame; nested frames remain intact
Safe for both void and value-returning functions
Thread-local operation; no impact on other threads
Parameters
None - the macro consumes the return expression provided after RETURN.
Returns
Returns the value/expression provided (or void); stack cleanup occurs first.
Exceptions
None - does not raise exceptions; only cleans up stack.
Thread Safety\n No - modifies thread-local Except_stack; must be used within
originating thread's TRY context.
Basic Usage Examples
// Void function early return
void process_data() {
  TRY {
    // Setup
    if (invalid_input()) {
      RETURN;  // Cleans stack and returns void
    }
    // Continue processing...
  } END_TRY;
}
Value-Returning Function
int compute_value(int input) {
  int result = 0;
  TRY {
    if (input < 0) {
      RETURN -1;  // Returns -1 after stack cleanup
    }
    result = expensive_computation(input);
    RETURN result;  // Normal return with cleanup
  } END_TRY;
  return result;  // Unreachable if RETURN used
}
Complex Expression Return
Socket_T create_connection(const char *host, int port) {
  TRY {
    // Validation and setup
    if (!valid_host(host)) {
      RETURN NULL;
    }
    Socket_T sock = Socket_new(AF_INET, SOCK_STREAM, 0);
    Socket_connect(sock, host, port);
    // On success, return with cleanup
    RETURN sock;  // Works even with simple expressions
  } EXCEPT(Socket_Failed) {
    // Handle error
    RETURN NULL;
  } END_TRY;
}
Note
Equivalent to manual stack pop + return, but safer and more readable.
Warning
Subtle implementation relies on comma operator precedence; do not modify macro expansion.
Only pops current frame; use in innermost TRY for correct behavior.
Complexity\n O(1) - simple pointer assignment and return.
See also
TRY macro for creating frames that require cleanup on early return.
END_TRY for automatic cleanup on block exit.
Except_stack for the thread-local stack being managed.
docs/ERROR_HANDLING.md for advanced TRY block patterns and stack management.
Definition at line 824 of file Except.h.
SAFE_CLOSE
#define SAFE_CLOSE (fd)
Value:
  do                                                                          \
    {                                                                         \
      if ((fd) >= 0)                                                          \
        {                                                                     \
          int _r = close (fd);                                                \
          if (_r < 0 && errno != EINTR)                                       \
            fprintf (stderr, "close failed: %s\n",                            \
                     Socket_safe_strerror (errno));                           \
        }                                                                     \
    }                                                                         \
  while (0)
Safe file descriptor close macro.
Closes file descriptor with proper POSIX.1-2008 EINTR handling. Per POSIX spec, do NOT retry close() on EINTR as the file descriptor state is unspecified. EINTR is treated as success since the FD is likely closed anyway.
Parameters
fd File descriptor to close (ignored if negative).
See also
close(2) for system call documentation.
Definition at line 2844 of file SocketConfig.h.
SOCKET_CRYPTO_MD5_SIZE
#define SOCKET_CRYPTO_MD5_SIZE 16
Size of MD5 digest in bytes.
Standard MD5 output length (16 bytes / 128 bits). Note: MD5 is deprecated for security-critical uses.
See also
SocketCrypto_md5()
Definition at line 79 of file SocketCrypto.h.
SOCKET_CRYPTO_SHA1_SIZE
#define SOCKET_CRYPTO_SHA1_SIZE 20
Size of SHA-1 digest in bytes.
Standard SHA-1 output length (20 bytes / 160 bits).
See also
SocketCrypto_sha1()
Definition at line 57 of file SocketCrypto.h.
SOCKET_CRYPTO_SHA256_SIZE
#define SOCKET_CRYPTO_SHA256_SIZE 32
Size of SHA-256 digest in bytes.
Standard SHA-256 output length (32 bytes / 256 bits).
See also
SocketCrypto_sha256()
SocketCrypto_hmac_sha256()
Definition at line 68 of file SocketCrypto.h.
SOCKET_CRYPTO_WEBSOCKET_ACCEPT_SIZE
#define SOCKET_CRYPTO_WEBSOCKET_ACCEPT_SIZE 29
Size of Sec-WebSocket-Accept string buffer (Base64-encoded).
SHA-1 digest (20 bytes) Base64-encoded to 28 chars + null terminator = 29 bytes. Per RFC 6455 Section 4.2.2.
See also
SocketCrypto_websocket_accept()
Definition at line 114 of file SocketCrypto.h.
SOCKET_CRYPTO_WEBSOCKET_GUID
#define SOCKET_CRYPTO_WEBSOCKET_GUID "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"
Fixed GUID string for WebSocket Sec-WebSocket-Accept computation (RFC 6455).
Magic GUID concatenated with client key for SHA-1 hashing in server handshake. Per RFC 6455 Section 4.2.2.
See also
SocketCrypto_websocket_accept()
SocketWS for WebSocket implementation.
Definition at line 92 of file SocketCrypto.h.
SOCKET_CRYPTO_WEBSOCKET_KEY_SIZE
#define SOCKET_CRYPTO_WEBSOCKET_KEY_SIZE 25
Size of Sec-WebSocket-Key string buffer (Base64-encoded).
16 random bytes Base64-encoded to 24 chars + null terminator = 25 bytes. Per RFC 6455 Section 4.1.
See also
SocketCrypto_websocket_key()
Definition at line 103 of file SocketCrypto.h.
SOCKET_DEFAULT_CONNECT_TIMEOUT_MS
#define SOCKET_DEFAULT_CONNECT_TIMEOUT_MS 30000 /* 30 seconds */
Default connect timeout.
See also
SocketTimeouts_T for timeout configuration.
Definition at line 1379 of file SocketConfig.h.
SOCKET_DEFAULT_OPERATION_TIMEOUT_MS
#define SOCKET_DEFAULT_OPERATION_TIMEOUT_MS 0 /* Infinite */
Default operation timeout.
0 = infinite.
See also
SocketTimeouts_T for timeout configuration.
Definition at line 1423 of file SocketConfig.h.
SOCKET_DEFAULT_REQUEST_TIMEOUT_MS
#define SOCKET_DEFAULT_REQUEST_TIMEOUT_MS 60000
Default request cycle timeout.
See also
SocketTimeouts_Extended_T 60 seconds for request cycle
Definition at line 1571 of file SocketConfig.h.
SOCKET_DEFAULT_TLS_TIMEOUT_MS
#define SOCKET_DEFAULT_TLS_TIMEOUT_MS 30000
Default TLS handshake timeout.
See also
SocketTimeouts_Extended_T 30 seconds for TLS handshake
Definition at line 1560 of file SocketConfig.h.
SOCKET_ERROR_BUFSIZE
#define SOCKET_ERROR_BUFSIZE 1024
Error buffer size.
See also
SOCKET_ERROR_FMT for error formatting.
Definition at line 1179 of file SocketConfig.h.
SOCKET_ERROR_MAX_HOSTNAME
#define SOCKET_ERROR_MAX_HOSTNAME 255
Maximum hostname length in error messages.
Definition at line 1198 of file SocketConfig.h.
SOCKET_ERROR_MAX_MESSAGE
#define SOCKET_ERROR_MAX_MESSAGE 512
Maximum error message length.
Definition at line 1207 of file SocketConfig.h.
SOCKET_ERROR_TRUNCATION_MARKER
#define SOCKET_ERROR_TRUNCATION_MARKER "... (truncated)"
Truncation marker for error messages.
Definition at line 1216 of file SocketConfig.h.
SOCKET_ERROR_TRUNCATION_SIZE
#define SOCKET_ERROR_TRUNCATION_SIZE (sizeof (SOCKET_ERROR_TRUNCATION_MARKER))
Size of truncation marker.
See also
SOCKET_ERROR_TRUNCATION_MARKER
Definition at line 1226 of file SocketConfig.h.
SOCKET_HASH_TABLE_SIZE
#define SOCKET_HASH_TABLE_SIZE 1021
Hash table size for socket data mapping.
Prime number for optimal hash distribution.
See also
HASH_GOLDEN_RATIO for hash function constant.
Definition at line 399 of file SocketConfig.h.
SOCKET_IPV4_PREFIX_RANGE
#define SOCKET_IPV4_PREFIX_RANGE "0-" SOCKET_TO_STRING (SOCKET_IPV4_MAX_PREFIX)
Valid IPv4 prefix range string for error messages.
See also
SOCKET_IPV4_MAX_PREFIX
Definition at line 1939 of file SocketConfig.h.
SOCKET_IPV6_PREFIX_RANGE
#define SOCKET_IPV6_PREFIX_RANGE "0-" SOCKET_TO_STRING (SOCKET_IPV6_MAX_PREFIX)
Valid IPv6 prefix range string for error messages.
See also
SOCKET_IPV6_MAX_PREFIX
Definition at line 1947 of file SocketConfig.h.
SOCKET_MAX_BUFFER_SIZE
#define SOCKET_MAX_BUFFER_SIZE (1024 * 1024) /* 1MB */
Maximum buffer size per connection.
Can be overridden at compile time with -DSOCKET_MAX_BUFFER_SIZE=value.
See also
SocketBuf_T for buffer implementation.
Definition at line 266 of file SocketConfig.h.
SOCKET_MAX_CONNECTIONS
#define SOCKET_MAX_CONNECTIONS 10000UL
Maximum number of connections in pool.
Can be overridden at compile time with -DSOCKET_MAX_CONNECTIONS=value.
See also
SocketPool_T for connection pool implementation.
Definition at line 254 of file SocketConfig.h.
SOCKET_MIN_BUFFER_SIZE
#define SOCKET_MIN_BUFFER_SIZE 512
Minimum buffer size per connection.
See also
SOCKET_MAX_BUFFER_SIZE for upper limit.
Definition at line 276 of file SocketConfig.h.
SOCKET_MS_PER_SECOND
#define SOCKET_MS_PER_SECOND 1000
Milliseconds per second.
Definition at line 1862 of file SocketConfig.h.
SOCKET_NS_PER_MS
#define SOCKET_NS_PER_MS 1000000LL
Nanoseconds per millisecond.
Definition at line 1869 of file SocketConfig.h.
SOCKET_NS_PER_SECOND
#define SOCKET_NS_PER_SECOND 1000000000LL
Nanoseconds per second.
Definition at line 1876 of file SocketConfig.h.
SOCKET_PLATFORM_MACOS
#define SOCKET_PLATFORM_MACOS 0
Platform detection flag for macOS/Apple systems.
Set to 1 when compiled under APPLE macro (macOS, iOS), enabling platform-specific features such as kqueue event polling backend, SO_NOSIGPIPE socket option, and Darwin-specific workarounds.
Used internally to select optimal I/O primitives and handle platform differences in socket options and system calls.
See also
Event System Modules for platform backend selection (epoll vs kqueue).
SocketPoll_backend.h for backend implementations.
SOCKET_HAS_SO_NOSIGPIPE for SIGPIPE suppression on macOS.
Definition at line 1261 of file SocketConfig.h.
SOCKET_PORT_STR_BUFSIZE
#define SOCKET_PORT_STR_BUFSIZE 16
Socket port string buffer size.
Definition at line 1235 of file SocketConfig.h.
SOCKET_PORT_VALID_RANGE
#define SOCKET_PORT_VALID_RANGE "1-" SOCKET_TO_STRING (SOCKET_MAX_PORT)
Valid port range string for error messages.
See also
SOCKET_MAX_PORT
Definition at line 1923 of file SocketConfig.h.
SOCKET_SECURITY_CHECK_OVERFLOW_ADD
#define SOCKET_SECURITY_CHECK_OVERFLOW_ADD (a, b) ((a) <= SIZE_MAX - (b))
Inline macro to check size addition for overflow risk.
Expands to subtraction-based check: safe if a <= SIZE_MAX - b. Detects overflow before addition, preventing wrap-around.
Ideal for buffer appends, index offsets, or cumulative sizes in loops.
Parameters
[in] a First addend.
[in] b Second addend.
Returns
Non-zero (true) if safe to add, zero (false) if overflow.
Usage Example
size_t offset = current_position;
size_t len = data_length;
if (SOCKET_SECURITY_CHECK_OVERFLOW_ADD(offset, len)) {
    // Safe to compute new offset
    size_t new_offset = offset + len;
    // Further validate new_offset if needed
} else {
    // Overflow: cap or error
    new_offset = SIZE_MAX; // Or handle appropriately
}
Note
No zero-check; complements VALID_SIZE for full validation.
Warning
Avoid in expressions with side effects due to macro expansion.
Complexity\n O(1)
See also
SocketSecurity_check_add() function with result computation.
SOCKET_SECURITY_CHECK_OVERFLOW_MUL for multiplication.
SocketSecurity_safe_add() for protected computation.
Definition at line 1439 of file SocketSecurity.h.
SOCKET_SECURITY_CHECK_OVERFLOW_MUL
#define SOCKET_SECURITY_CHECK_OVERFLOW_MUL (a, b) ((b) == 0 || (a) <= SIZE_MAX / (b))
Inline macro to check size multiplication for overflow risk.
Expands to expression checking if a * b would overflow size_t. Safe if b==0 (product 0) or a <= SIZE_MAX / b. Division-based check avoids overflow.
Use before multiplication in hot paths for zero-cost validation.
Parameters
[in] a First operand for multiplication.
[in] b Second operand for multiplication.
Returns
Non-zero (true) if safe to multiply, zero (false) if overflow risk.
Usage Example
size_t num_elements = parse_count(input);
size_t struct_size = sizeof(MyStruct);
if (SOCKET_SECURITY_CHECK_OVERFLOW_MUL(num_elements, struct_size)) {
    size_t total = num_elements * struct_size; // Safe
    if (SOCKET_SECURITY_VALID_SIZE(total)) {
        MyStruct *arr = Arena_alloc(arena, total, __FILE__, __LINE__);
    }
} else {
    // Overflow risk: limit or error
}
Note
Parenthesizes arguments; safe for expressions but avoid side effects.
Warning
Does not compute product; use safe_multiply or check_multiply for that.
Complexity\n O(1) compile-time expandable
See also
SocketSecurity_check_multiply() function version with result output.
SOCKET_SECURITY_CHECK_OVERFLOW_ADD for addition check.
SocketSecurity_safe_multiply() for computing with protection.
Definition at line 1398 of file SocketSecurity.h.
SOCKET_SECURITY_MAX_ALLOCATION
#define SOCKET_SECURITY_MAX_ALLOCATION (256UL * 1024 * 1024)
Maximum single allocation size permitted by security policy.
Limits individual allocations (e.g., malloc, Arena_alloc, SocketBuf_new) to mitigate denial-of-service attacks from excessively large requests.
Default: 256 MiB (268435456 bytes). Override by defining this macro to a different value before including SocketSecurity.h or any header that includes it.
This limit is enforced in memory allocation hotspots and buffer creations across the library.
See also
SocketSecurity_get_max_allocation() for runtime query.
SocketSecurity_check_size() for validating sizes against this limit.
SocketSecurity_SizeExceeded exception raised when exceeded.
ARENA_MAX_ALLOC_SIZE related arena-specific limit.
Definition at line 143 of file SocketSecurity.h.
SOCKET_SECURITY_MAX_BODY_SIZE
#define SOCKET_SECURITY_MAX_BODY_SIZE (100 * 1024 * 1024)
Maximum permitted size for HTTP request/response bodies.
Limits HTTP body payloads to prevent memory exhaustion from large uploads/downloads. Default: 100 MiB. Override via compile-time definition.
Enforced in SocketHTTPClient, SocketHTTPServer, and protocol parsers. Exceeding this triggers truncation or rejection with 413 Payload Too Large.
See also
SocketSecurity_get_limits() -> http_max_body_size runtime value.
SocketHTTP_Headers_get("Content-Length") for body size indication.
HTTP Module for protocol limits.
Definition at line 161 of file SocketSecurity.h.
SOCKET_SECURITY_MAX_REQUEST_TIMEOUT_MS
#define SOCKET_SECURITY_MAX_REQUEST_TIMEOUT_MS 60000
Maximum allowed request timeout value in milliseconds.
Caps the maximum timeout for operations like connect, read, write to prevent indefinite resource holds. Default: 60 seconds (60000 ms). Override by defining before inclusion.
Used in Socket_connect, SocketHTTPClient config, etc., to bound timeout parameters. Values exceeding this are clamped or rejected.
See also
SocketSecurity_get_limits() -> timeout_request_ms (related).
SocketConfig.h for other timeout defaults.
SocketTimeouts_T for timeout structures.
Definition at line 180 of file SocketSecurity.h.
SOCKET_SECURITY_VALID_SIZE
#define SOCKET_SECURITY_VALID_SIZE (s) ((size_t)(s) > 0 && (size_t)(s) <= SOCKET_SECURITY_MAX_ALLOCATION)
Inline macro for validating a size against allocation security limits.
Fast compile-time or runtime check for safe sizes. Expands to expression checking non-zero and <= max allocation. Casts to size_t for safety.
Preferred in performance-sensitive code over function call; equivalent to SocketSecurity_check_size but without the SIZE_MAX/2 defense check (use function for full).
Parameters
[in] s Size value to validate (any integer type, cast to size_t).
Returns
Non-zero (true) if valid: (size_t)s > 0 && <= SOCKET_SECURITY_MAX_ALLOCATION, else zero (false).
Usage Example
#define MAX_ITEMS 1000
if (!SOCKET_SECURITY_VALID_SIZE(MAX_ITEMS * sizeof(ItemStruct))) {
    compile_error_or_runtime_fail("Array size too large");
}
ItemStruct *items = Arena_calloc(arena, MAX_ITEMS, sizeof(ItemStruct));
Note
Does not check overflow in expression; validate operands first with check_multiply.
Warning
Macro expands directly; avoid side effects in (s) (e.g., no function calls).
Complexity\n O(1) - compile-time if possible
See also
SocketSecurity_check_size() for runtime function with additional defenses.
SOCKET_SECURITY_CHECK_OVERFLOW_MUL for multiplication checks.
SocketSecurity_get_max_allocation() for dynamic limit retrieval.
Definition at line 1356 of file SocketSecurity.h.
SOCKET_STRERROR_BUFSIZE
#define SOCKET_STRERROR_BUFSIZE 128
Thread-safe strerror buffer size.
See also
Socket_safe_strerror() for thread-safe error strings.
Definition at line 1189 of file SocketConfig.h.
SOCKET_STRINGIFY
#define SOCKET_STRINGIFY (x) #x
Stringify macro for compile-time string conversion.
Definition at line 1907 of file SocketConfig.h.
SOCKET_TO_STRING
#define SOCKET_TO_STRING (x) SOCKET_STRINGIFY (x)
Convert macro argument to string.
See also
SOCKET_STRINGIFY
Definition at line 1915 of file SocketConfig.h.
SOCKET_TTL_VALID_RANGE
#define SOCKET_TTL_VALID_RANGE "1-" SOCKET_TO_STRING (SOCKET_MAX_TTL)
Valid TTL range string for error messages.
See also
SOCKET_MAX_TTL
Definition at line 1931 of file SocketConfig.h.
SOCKET_VALID_BUFFER_SIZE
#define SOCKET_VALID_BUFFER_SIZE (s)
Value:
  ((size_t)(s) >= SOCKET_MIN_BUFFER_SIZE                                      \
   && (size_t)(s) <= SOCKET_MAX_BUFFER_SIZE)
Buffer size validation macro.
Parameters
s Buffer size to validate.
Returns
Non-zero if buffer size is valid.
See also
SOCKET_MIN_BUFFER_SIZE, SOCKET_MAX_BUFFER_SIZE
Definition at line 2797 of file SocketConfig.h.
SOCKET_VALID_CONNECTION_COUNT
#define SOCKET_VALID_CONNECTION_COUNT (c) ((size_t)(c) > 0 && (size_t)(c) <= SOCKET_MAX_CONNECTIONS)
Connection count validation macro.
Parameters
c Connection count to validate.
Returns
Non-zero if connection count is valid.
See also
SOCKET_MAX_CONNECTIONS
Definition at line 2809 of file SocketConfig.h.
SOCKET_VALID_IP_STRING
#define SOCKET_VALID_IP_STRING (ip) ((ip) != NULL && (ip)[0] != '\0')
IP string validation macro.
Parameters
ip IP string to validate.
Returns
Non-zero if IP string is valid (non-null, non-empty).
Definition at line 2830 of file SocketConfig.h.
SOCKET_VALID_POLL_EVENTS
#define SOCKET_VALID_POLL_EVENTS (e) ((int)(e) > 0 && (int)(e) <= SOCKET_MAX_POLL_EVENTS)
Poll events validation macro.
Parameters
e Number of poll events to validate.
Returns
Non-zero if poll events count is valid.
See also
SOCKET_MAX_POLL_EVENTS
Definition at line 2820 of file SocketConfig.h.
SOCKET_VALID_PORT
#define SOCKET_VALID_PORT (p) ((int)(p) >= 0 && (int)(p) <= 65535)
Port number validation macro.
Parameters
p Port number to validate.
Returns
Non-zero if port is valid (0-65535).
Definition at line 2787 of file SocketConfig.h.
SOCKET_VERSION
#define SOCKET_VERSION
Value:
  ((SOCKET_VERSION_MAJOR * 10000) + (SOCKET_VERSION_MINOR * 100)              \
   + SOCKET_VERSION_PATCH)
Numeric version for compile-time comparisons.
Calculated as: (MAJOR * 10000) + (MINOR * 100) + PATCH
See also
SOCKET_VERSION_MAJOR, SOCKET_VERSION_MINOR, SOCKET_VERSION_PATCH
Definition at line 210 of file SocketConfig.h.
SOCKET_VERSION_MAJOR
#define SOCKET_VERSION_MAJOR 0
Major version number.
Definition at line 182 of file SocketConfig.h.
SOCKET_VERSION_MINOR
#define SOCKET_VERSION_MINOR 1
Minor version number.
Definition at line 188 of file SocketConfig.h.
SOCKET_VERSION_PATCH
#define SOCKET_VERSION_PATCH 0
Patch version number.
Definition at line 194 of file SocketConfig.h.
SOCKET_VERSION_STRING
#define SOCKET_VERSION_STRING "0.1.0"
Version string for human-readable output.
Definition at line 200 of file SocketConfig.h.
T
#define T Arena_T
Opaque arena type for memory management.
Arena_T is an opaque pointer to a memory arena structure. Arenas provide fast, thread-safe memory allocation with bulk deallocation. All related objects should use the same arena for their lifecycle management.
See also
Arena_new() for creation.
Arena_dispose() for cleanup.
Examples
/home/tetsuo/git/tetsuo-socket/include/core/SocketRateLimit.h.
Definition at line 79 of file Arena.h.
TRY
#define TRY
Value:
  do                                                                          \
    {                                                                         \
      volatile int Except_flag;                                               \
      volatile Except_Frame Except_frame;                                     \
      jmp_buf *env_ptr = (jmp_buf *)&Except_frame.env;                        \
      Except_frame.prev = Except_stack;                                       \
      Except_frame.file = NULL;                                               \
      Except_frame.line = 0;                                                  \
      Except_frame.exception = NULL;                                          \
      Except_stack = (Except_Frame *)&Except_frame;                           \
      Except_flag = setjmp (*env_ptr);                                        \
      if (Except_flag == Except_entered)                                      \
        {
Start a TRY/EXCEPT/FINALLY exception handling block.
This macro initiates a structured exception handling context similar to try/catch in higher-level languages. It pushes a new Except_Frame onto the thread-local Except_stack, captures the current continuation point using setjmp(), and executes the protected code block. If no exception occurs, execution continues normally. If RAISE() is called within the block, control jumps back to the setjmp() point via longjmp(), allowing exception handlers (EXCEPT/ELSE) to execute.
Key features and behavior:
Thread-local stack management - each thread maintains independent contexts
Supports nested TRY blocks with proper frame stacking/unwinding
Integrates with FINALLY for guaranteed cleanup (executes on all exit paths)
Variables modified across potential longjmp() boundaries must be volatile to prevent compiler optimization issues
Automatic frame cleanup on normal exit or RETURN usage
Typical usage patterns include protecting resource acquisition/usage, error-prone system calls, and validation logic where failures need structured recovery.
Edge cases:
Deep nesting may consume stack space (each frame ~sizeof(jmp_buf) + overhead)
setjmp() may not capture all registers on some architectures/compilers
longjmp() from signal handlers or async contexts is unsafe
Parameters
None - macro expands to local variables and control flow setup.
Returns
None - establishes control context; does not return a value.
Exceptions
Exceptions raised via RAISE() within block are caught by subsequent handlers.
Thread Safety\n No - allocates and modifies thread-local Except_stack and frame.
Basic Usage Example
#include "core/Except.h"
extern const Except_T DivideByZeroError;
double safe_divide(double a, double b) {
  double result;
  TRY {
    if (b == 0.0) {
      RAISE(DivideByZeroError);
    }
    result = a / b;  // Protected operation
    RETURN result;   // Early return with stack cleanup
  } EXCEPT(DivideByZeroError) {
    result = 0.0;    // Default value on error
    fprintf(stderr, "Division by zero avoided\n");
  } FINALLY {
    // Always executes: logging, metrics, etc.
    log_operation("divide", a, b, result);
  } END_TRY;
  return result;
}
Nested TRY Blocks
void complex_operation() {
  TRY {  // Outer TRY
    resource_setup();
    TRY {  // Inner TRY
      inner_operation();  // May raise InnerError
    } EXCEPT(InnerError) {
      RERAISE;  // Propagate to outer
    } END_TRY;
  } EXCEPT(OuterError) {
    // Handle or log outer-level error
  } FINALLY {
    resource_cleanup();  // Both levels ensure cleanup
  } END_TRY;
}
With Volatile Variables
volatile int status = 0;  // Volatile to survive longjmp
TRY {
  status = setup();
  if (status < 0) {
    RAISE(Error);
  }
  // Use status...
  RETURN status;
} END_TRY;
Note
Declare modified variables as volatile int/pointer etc. to ensure visibility post-longjmp.
Warning
Avoid non-volatile locals modified in TRY if RAISE possible - optimizer may eliminate them.
Limit nesting depth to avoid excessive stack usage or performance overhead.
Complexity\n O(1) - setjmp() call and frame allocation (amortized).
See also
RAISE() for raising exceptions within protected blocks.
EXCEPT for specific exception handling.
ELSE for catch-all handling.
FINALLY for guaranteed cleanup code.
END_TRY to finalize the block and propagate unhandled exceptions.
RETURN for early returns with automatic stack cleanup.
docs/ERROR_HANDLING.md for detailed patterns, volatile usage, and nesting guidelines.
Core Foundation Modules for other base infrastructure modules.
Definition at line 991 of file Except.h.
Typedef Documentation
Arena_T [1/2]
typedef struct Arena_T* Arena_T
Definition at line 80 of file Arena.h.
Arena_T [2/2]
typedef struct Arena_T* Arena_T
Forward declaration of Arena_T from core foundation module.
Used for arena-based memory allocation of requests and internal structures.
See also
Foundation module for details.
Arena_new(), Arena_alloc() in include/core/Arena.h
Definition at line 87 of file SocketDNS-private.h.
SocketLogCallback
typedef void(* SocketLogCallback) (void *userdata, SocketLogLevel level, const char *component, const char *message)
Custom logging callback function type.
Parameters
userdata User-provided context.
level Log severity level.
component Module/component name.
message Log message.
See also
SocketLog_setcallback() for registration.
Definition at line 69 of file SocketUtil.h.
SocketLogStructuredCallback
typedef void(* SocketLogStructuredCallback) (void *userdata, SocketLogLevel level, const char *component, const char *message, const SocketLogField *fields, size_t field_count, const SocketLogContext *context)
Typedef for callback handling structured logs with key-value fields and context.
Extended variant of SocketLogCallback that receives metadata fields separately for machine-readable output formats like JSON or logfmt. Invoked by SocketLog_emit_structured() when registered via SocketLog_setstructuredcallback().
Parameters
userdata User-provided opaque context passed during registration.
level Log severity level (SOCKET_LOG_TRACE to SOCKET_LOG_FATAL).
component String identifying emitting module or subsystem (non-NULL).
message Descriptive event string (non-NULL, may be empty).
fields Pointer to array of SocketLogField structs or NULL if none.
field_count Number of valid fields in array (0 if fields NULL).
context Pointer to current thread's SocketLogContext or NULL.
Thread Safety\n Conditional - implementor must handle concurrency if userdata
shared.
Guidelines:
Validate NULL fields/context before access to avoid crashes.
Fields values are caller-provided strings; lifetime until callback returns.
Format output as needed (JSON, key=value pairs, etc.); no default formatting.
Integrate with external systems like ELK stack or Prometheus for observability.
See also
SocketLog_setstructuredcallback() to register this callback.
SocketLog_emit_structured() emission trigger.
SocketLogField for field structure.
SocketLogContext for context details.
SocketLogCallback base callback fallback.
docs/LOGGING.md for examples and integration.
Note
Fields array not copied; valid only during call.
Prefer for new code; enables better tooling and analysis.
Definition at line 799 of file SocketUtil.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Exception handling states for TRY/EXCEPT/FINALLY blocks.
Internal enumeration tracking the phase of exception processing within a TRY construct. Managed via local volatile Except_flag variable in macro expansion. Determines control flow: entering protected code, handling raised exceptions, post-handling cleanup, or finalization.
State transitions:
Except_entered (0): Initial setjmp() returns 0, enter TRY body
Except_raised (1): longjmp() returns non-zero, check handlers
Except_handled (2): Matched EXCEPT/ELSE, mark handled
Except_finalized (3): FINALLY executed or normal path finalized
Used internally by macros for conditional execution and cleanup decisions. Values are small integers for efficient flag comparison.
State Values
| Value | Name | Description | Triggered By | |----—|---—|----------—|-----------—| | 0 | Except_entered | TRY block entered successfully, no exception yet | setjmp() normal return | | 1 | Except_raised | Exception raised, dispatch to handlers | longjmp() from RAISE/RERAISE | | 2 | Except_handled | Exception caught by EXCEPT/ELSE | Handler match in macros | | 3 | Except_finalized | FINALLY or block exit processed | FINALLY exec or normal END_TRY |
Note
Internal to macro implementation; users do not interact directly.
Warning
Values are hardcoded; changes require macro updates.
Thread Safety\n Implicit - local volatile flag per TRY block.
// Example transition in macro (simplified)
Except_flag = setjmp(env);  // 0 -> entered
if (Except_flag == 0) {  // TRY body
  // ...
} else if (match_except) {  // raised -> handled
  Except_flag = Except_handled;
  // Handler code
}
// FINALLY checks flag for finalization
See also
TRY macro expansion using Except_flag.
EXCEPT/ELSE setting to Except_handled.
FINALLY using Except_entered for conditional exec.
docs/ERROR_HANDLING.md for macro internals and state machine.
Enumerator
Except_entered
TRY block entered, no exception raised
Except_raised
Exception raised, executing EXCEPT or FINALLY
Except_handled
Exception handled, executing FINALLY or END_TRY
Except_finalized
FINALLY block executed, cleaning up
Definition at line 346 of file Except.h.
SocketErrorCategory
enum SocketErrorCategory
SocketErrorCategory - High-level classification of error types for policy decisions.
Abstracts errno and SocketErrorCode into semantic categories to guide error handling, retry policies, alerting, and logging strategies across modules. Enables uniform treatment of similar errors regardless of platform or cause.
Category Behaviors:
SOCKET_ERROR_CATEGORY_NETWORK: Transient network issues (e.g., ECONNRESET, ENETUNREACH) - usually retryable with backoff.
SOCKET_ERROR_CATEGORY_PROTOCOL: Malformed data or unsupported protocols (e.g., EINVAL in parsing) - typically fatal or requires client fix.
SOCKET_ERROR_CATEGORY_APPLICATION: Business logic errors (e.g., auth failures, 4xx HTTP) - propagate to app layer.
SOCKET_ERROR_CATEGORY_TIMEOUT: Time-bound operations exceeded (ETIMEDOUT)
retryable, but watch for cascading failures.
SOCKET_ERROR_CATEGORY_RESOURCE: System limits hit (ENOMEM, EMFILE) - may self-resolve or require scaling.
SOCKET_ERROR_CATEGORY_UNKNOWN: Uncategorized (log and handle conservatively).
Usage in Modules: SocketErrorCategory cat = SocketError_categorize_errno(errno); if (cat == SOCKET_ERROR_CATEGORY_NETWORK) { SocketRetry_attempt_with_backoff(...); } else if (cat == SOCKET_ERROR_CATEGORY_RESOURCE) { SocketLog_emit(SOCKET_LOG_WARN, "Resource limit hit", fields); // Trigger pool drain or config alert }
See also
SocketError_categorize_errno() to classify raw errno values.
SocketError_is_retryable_errno() for quick retry checks.
Socket_geterrorcode() for normalized error codes.
SOCKET_RAISE_* macros to raise categorized exceptions.
SocketRetry for backoff policies based on category.
docs/ERROR_HANDLING.md for comprehensive error strategies.
docs/SECURITY.md for Security Modules implications of error categories.
Note
Categories are conservative; custom modules can extend via SocketErrorCode.
Thread-safe pure functions; use in signal handlers if needed.
Maps Windows WSA errors to equivalent POSIX categories.
Enumerator
SOCKET_ERROR_CATEGORY_NETWORK
Network-level: ECONNRESET, ECONNREFUSED, etc.
SOCKET_ERROR_CATEGORY_PROTOCOL
Protocol-level: Parse errors, invalid responses
SOCKET_ERROR_CATEGORY_APPLICATION
App-level: Auth failures, 4xx responses
SOCKET_ERROR_CATEGORY_TIMEOUT
Timeout errors: ETIMEDOUT, deadline exceeded
SOCKET_ERROR_CATEGORY_RESOURCE
Resource exhaustion: OOM, fd limits
SOCKET_ERROR_CATEGORY_UNKNOWN
Unclassified errors
Definition at line 1566 of file SocketUtil.h.
SocketErrorCode
enum SocketErrorCode
SocketErrorCode - Normalized error codes mapping POSIX errno values.
Enumeration providing a library-specific abstraction over platform errno values. Maps common socket-related errors to consistent codes for uniform handling across modules. Enables retry logic, categorization, and logging without direct errno dependencies.
Key Mappings:
SOCKET_ERROR_EAGAIN / SOCKET_ERROR_EWOULDBLOCK: Non-blocking operation would block (retryable)
SOCKET_ERROR_ECONNREFUSED: Connection refused (network/transient)
SOCKET_ERROR_ETIMEDOUT: Operation timed out (retryable with backoff)
SOCKET_ERROR_ENOMEM: Memory allocation failed (resource exhaustion)
SOCKET_ERROR_EADDRINUSE: Address already in use (configuration)
SOCKET_ERROR_EINVAL: Invalid argument (programming error)
And others for network, protocol, resource errors.
Usage: if (Socket_geterrorcode() == SOCKET_ERROR_ECONNREFUSED) { // Implement exponential backoff retry } SocketErrorCategory cat = SocketError_categorize_errno(errno);
See also
Socket_geterrorcode() to retrieve normalized code from last error.
SocketError_categorize_errno() for high-level classification.
SocketError_is_retryable_errno() to check retry eligibility.
Socket_safe_strerror() for safe error string conversion.
docs/ERROR_HANDLING.md for error patterns and exception raising.
Note
Extensible: Add new codes for library-specific errors (e.g., TLS errors).
Platform-agnostic: Abstracts Windows WSA errors to POSIX equivalents.
Integrates with SOCKET_RAISE_* macros for exception throwing.
Enumerator
SOCKET_ERROR_NONE
SOCKET_ERROR_EINVAL
SOCKET_ERROR_EACCES
SOCKET_ERROR_EADDRINUSE
SOCKET_ERROR_EADDRNOTAVAIL
SOCKET_ERROR_EAFNOSUPPORT
SOCKET_ERROR_EAGAIN
SOCKET_ERROR_EALREADY
SOCKET_ERROR_EBADF
SOCKET_ERROR_ECONNREFUSED
SOCKET_ERROR_ECONNRESET
SOCKET_ERROR_EFAULT
SOCKET_ERROR_EHOSTUNREACH
SOCKET_ERROR_EINPROGRESS
SOCKET_ERROR_EINTR
SOCKET_ERROR_EISCONN
SOCKET_ERROR_EMFILE
SOCKET_ERROR_ENETUNREACH
SOCKET_ERROR_ENOBUFS
SOCKET_ERROR_ENOMEM
SOCKET_ERROR_ENOTCONN
SOCKET_ERROR_ENOTSOCK
SOCKET_ERROR_EOPNOTSUPP
SOCKET_ERROR_EPIPE
SOCKET_ERROR_EPROTONOSUPPORT
SOCKET_ERROR_ETIMEDOUT
SOCKET_ERROR_EWOULDBLOCK
SOCKET_ERROR_UNKNOWN
Definition at line 1217 of file SocketUtil.h.
SocketLogLevel
enum SocketLogLevel
Log severity levels.
Enumerator
SOCKET_LOG_TRACE
SOCKET_LOG_DEBUG
SOCKET_LOG_INFO
SOCKET_LOG_WARN
SOCKET_LOG_ERROR
SOCKET_LOG_FATAL
Definition at line 50 of file SocketUtil.h.
SocketMetric
enum SocketMetric
SocketMetric - Enumeration of library-wide performance and operational metrics.
These metrics track key events across all modules for monitoring, alerting, and performance analysis. Use SocketMetrics_increment() to update counters from module code. Snapshots via SocketMetrics_getsnapshot() provide atomic reads for reporting.
Categories:
Socket connections (success/failure, shutdowns)
DNS resolution (requests, completions, failures, timeouts)
Event polling (wakeups, dispatched events)
Connection pooling (adds, removes, reuses, health checks, drains)
Integration: Emit metrics in hot paths with minimal overhead (atomic ops). Export snapshots to Prometheus, StatsD, or custom telemetry systems.
See also
SocketMetrics_increment() to update counters.
SocketMetrics_getsnapshot() for atomic reads.
SocketMetrics_name() for human-readable labels.
SocketMetrics_count() for enum size.
Utilities for related retry and rate-limit metrics.
docs/METRICS.md for usage guidelines and best practices.
Note
Thread-safe; use in async callbacks and worker threads.
SOCKET_METRIC_COUNT must match values[] size in snapshot.
Enumerator
SOCKET_METRIC_SOCKET_CONNECT_SUCCESS
SOCKET_METRIC_SOCKET_CONNECT_FAILURE
SOCKET_METRIC_SOCKET_SHUTDOWN_CALL
SOCKET_METRIC_DNS_REQUEST_SUBMITTED
SOCKET_METRIC_DNS_REQUEST_COMPLETED
SOCKET_METRIC_DNS_REQUEST_FAILED
SOCKET_METRIC_DNS_REQUEST_CANCELLED
SOCKET_METRIC_DNS_REQUEST_TIMEOUT
SOCKET_METRIC_POLL_WAKEUPS
SOCKET_METRIC_POLL_EVENTS_DISPATCHED
SOCKET_METRIC_POOL_CONNECTIONS_ADDED
SOCKET_METRIC_POOL_CONNECTIONS_REMOVED
SOCKET_METRIC_POOL_CONNECTIONS_REUSED
SOCKET_METRIC_POOL_DRAIN_INITIATED
SOCKET_METRIC_POOL_DRAIN_COMPLETED
SOCKET_METRIC_POOL_HEALTH_CHECKS
SOCKET_METRIC_POOL_HEALTH_FAILURES
SOCKET_METRIC_POOL_VALIDATION_FAILURES
SOCKET_METRIC_POOL_IDLE_CLEANUPS
SOCKET_METRIC_COUNT
Definition at line 891 of file SocketUtil.h.
Function Documentation
Arena_alloc()
void * Arena_alloc (Arena_T arena, size_t nbytes, const char * file, int line) extern
Allocate raw memory block from the specified arena.
Allocates a block of nbytes from the arena's current chunk. If insufficient space remains in the current chunk, a new chunk is allocated automatically. The returned pointer is aligned to the system's maximum alignment requirement (typically 16 bytes). Debug information (file and line) is recorded internally for leak detection and profiling if enabled.
Behavior:
Does not initialize memory contents (use memset or Arena_calloc for zeroing).
Fast path if space available in current chunk (no system malloc).
Grows arena by doubling chunk size (up to max) to minimize reallocs.
On failure (arena cannot grow due to system limits), throws Arena_Failed.
Zero-byte allocation returns NULL without error or exception.
Parameters
[in] arena Valid non-NULL arena instance.
[in] nbytes Number of bytes to allocate (>0 for actual allocation).
[in] file Source file name for debug tracking (typically FILE).
[in] line Source line number for debug tracking (typically LINE).
Returns
Pointer to allocated memory, valid until arena clear/dispose; NULL for 0 bytes.
Exceptions
Arena_Failed If insufficient space and arena growth fails (e.g., malloc ENOMEM).
Thread Safety\n Yes - acquires per-arena mutex; low contention for
small/frequent allocs.
Basic Usage via Macro
Arena_T arena = Arena_new();
TRY {
    void *ptr = ALLOC(arena, 512);  // Macro calls Arena_alloc with
__FILE__, __LINE__
    // Safe to use ptr
    // No individual free needed
} EXCEPT(Arena_Failed) {
    // OOM handling
} END_TRY;
Arena_dispose(&arena);
Direct Function Call
TRY {
    // Explicit debug info (rarely needed outside macros)
    void *buf = Arena_alloc(arena, 1024, "myfile.c", 123);
    // Initialize manually
    memset(buf, 0, 1024);  // Or use calloc for auto-zero
} EXCEPT(Arena_Failed) {
    fprintf(stderr, "Allocation failed\n");
} END_TRY;
Note
For most cases, use the ALLOC() macro which automatically provides file/line.
Allocated memory remains valid across Arena_clear() calls? No, cleared.
Warning
Invalid to call on NULL arena; assumes valid input.
Large allocations may cause chunk growth; monitor for performance.
Complexity\n Amortized O(1) - direct from chunk most times; occasional chunk
allocation O(1).
See also
ALLOC(arena, nbytes) macro for convenient usage with auto debug info.
Arena_calloc() for zero-initialized blocks.
Arena_new() to create the arena first.
Arena_clear() and Arena_dispose() for when memory becomes invalid.
Referenced by ctx_arena_alloc(), ctx_arena_strdup(), http1_tokenbuf_append(), http1_tokenbuf_init(), http1_tokenbuf_terminate(), socket_util_arena_strdup(), and socket_util_arena_strndup().
Arena_calloc()
void * Arena_calloc (Arena_T arena, size_t count, size_t nbytes, const char * file, int line) extern
Allocate and zero-initialize a block of memory elements from the arena.
Performs allocation similar to Arena_alloc but ensures the entire block is zeroed using memset after allocation. Total size is count * nbytes, with checks for overflow. Ideal for initializing structs, arrays, or any data requiring default zero values. Debug tracking with file/line as standard.
Edge cases and behavior:
If count == 0 or nbytes == 0, returns NULL immediately without allocation.
Size computation overflow (e.g., SIZE_MAX crossed) raises Arena_Failed.
Memory zeroed atomically with allocation under mutex protection.
Slower than plain alloc due to memset overhead; use when zero-init is required.
Parameters
[in] arena Valid arena instance.
[in] count Number of elements to zero-allocate.
[in] nbytes Bytes per element (use sizeof(Type)).
[in] file Debug file name (FILE via macro).
[in] line Debug line number (LINE via macro).
Returns
Pointer to zero-filled memory block; NULL if count==0 || nbytes==0.
Exceptions
Arena_Failed On allocation failure, size overflow, or arena growth issues.
Thread Safety\n Yes - mutex protected; concurrent safe with serialization.
Usage Example
// Zero-init struct array via macro (recommended)
TRY {
    MyStruct *arr = CALLOC(arena, 20, sizeof(MyStruct));
    // All fields in arr[0..19] are zero; safe for C structs
    arr[0].id = 1;  // Set specific fields as needed
} EXCEPT(Arena_Failed) {
    // OOM or overflow
} END_TRY;
Explicit Call
size_t elem_size = sizeof(int);
int *ints = Arena_calloc(arena, 1000, elem_size, __FILE__, __LINE__);
// ints[0] to ints[999] == 0
Note
Prefer CALLOC() macro for automatic debug info injection.
Ensures C-standard zero-initialization for structs (NULL pointers, zero ints, etc.).
Warning
memset overhead scales with size; for large blocks, consider alloc
selective init.
Verify sizeof() correctness to avoid under/over-allocation bugs.
Complexity\n Amortized O(1) for allocation + O(total_bytes) for memset
zeroing.
See also
CALLOC() macro for convenient zero-allocation with debug info.
Arena_alloc() for faster non-zeroed allocation.
sizeof operator for accurate nbytes calculation.
docs/ERROR_HANDLING.md for handling allocation exceptions.
Arena_clear()
void Arena_clear (Arena_T arena) extern
Reset the arena by invalidating all current allocations while preserving the arena for reuse.
Frees all memory chunks allocated within the arena, returning it to a fresh state ready for new allocations. Unlike dispose, the arena object itself (mutex, config) is retained, enabling efficient reuse in loops or repeated operations. Freed chunks are recycled to a global pool to minimize future system allocations.
Key behaviors:
All pointers from previous allocations become invalid/dangling.
No exceptions thrown by clear itself; failures in underlying free rare and logged.
Faster than dispose + new for cyclic usage (e.g., per-client session reset).
Maintains thread-safety during clear operation.
Parameters
[in] arena Valid non-NULL arena instance to reset.
Thread Safety\n Yes - acquires arena mutex; concurrent operations wait briefly.
Reuse Pattern Example
Arena_T arena = Arena_new();
while (accept_connections) {
    Connection_T conn = SocketPool_add(pool, sock);
    TRY {
        // Connection-specific allocations
        SocketBuf_T inbuf = SocketBuf_new(arena, 4096);
        SocketHTTP_Headers_T req_headers = SocketHTTP_Headers_new(arena);
        // ... process connection ...
    } EXCEPT(...) {
        // Error handling
    } END_TRY;
    SocketPool_remove(pool, sock);
    Arena_clear(arena);  // Reset for next connection
}
Arena_dispose(&arena);
Simple Reset
// No TRY needed as clear doesn't throw
Arena_clear(arena);
// Immediately safe to allocate again
void *fresh = ALLOC(arena, 1024);
Note
Optimal for scenarios like HTTP servers resetting per-request state.
Does not reset arena statistics or debug info; those persist.
Warning
Update any long-lived pointers/caches after clear to avoid use-after-clear bugs.
If arena is empty, clear is near-no-op (just mutex acquire/release).
Complexity\n O(c) where c = number of active chunks; each chunk relinked or
freed.
See also
Arena_dispose() for full destruction when reuse no longer needed.
Arena_new() for creating arena before reuse cycles.
ALLOC() for allocations post-clear.
Connection Management Modules for pool integration examples.
Arena_dispose()
void Arena_dispose (Arena_T * ap) extern
Dispose of an arena and all its allocations, freeing underlying memory chunks.
Releases all memory chunks associated with the arena and destroys the arena structure. The pointer *ap is set to NULL after successful disposal to prevent use-after-free. This is the standard way to clean up an arena after use. All allocations made from this arena become invalid after disposal.
Edge cases:
Safe to call on NULL (no-op).
If called concurrently from multiple threads, only one will perform disposal due to mutex.
Recycles freed chunks to global pool for future arenas to reuse (reduces malloc pressure).
Parameters
[in,out] ap Pointer to the arena instance (set to NULL on success).
Thread Safety\n Yes - internal mutex ensures atomic disposal; concurrent calls
block until complete.
Basic Usage
TRY {
    Arena_T arena = Arena_new();
    // ... make allocations ...
    Arena_dispose(&arena);  // Frees everything, sets arena = NULL
    assert(arena == NULL);  // Verify cleanup
} EXCEPT(Arena_Failed) {
    // Handle creation failure; no dispose needed
} END_TRY;
Usage in FINALLY Block
Arena_T arena = NULL;
TRY {
    arena = Arena_new();
    // ... operations with allocations ...
} EXCEPT(Arena_Failed) {
    fprintf(stderr, "Arena creation failed\n");
} FINALLY {
    if (arena != NULL) {
        Arena_dispose(&arena);
    }
} END_TRY;
Note
Always pass the address of the arena pointer (&arena) to enable NULL setting and prevent dangling references.
For reusing the arena across multiple cycles (e.g., request handling loop), prefer Arena_clear().
Warning
Do not attempt to access the arena or any pointers allocated from it after disposal.
Concurrent disposal calls are serialized by mutex, but avoid if possible for performance.
Complexity\n O(c) where c is the number of memory chunks in the arena - each
chunk is individually freed.
See also
Arena_new() for corresponding creation.
Arena_clear() for resetting allocations without destroying the arena structure.
docs/ERROR_HANDLING.md for integrating with exception handling.
Referenced by main(), and main().
Arena_new()
Arena_T Arena_new (void) extern
Create a new memory arena with initial capacity and thread-safe protection.
Initializes a new arena allocator. The arena begins with an initial chunk of memory (typically 4KB or system page size) and grows automatically by allocating additional chunks as needed. All allocations are tracked with file and line information for debugging purposes. The arena is fully thread-safe, allowing concurrent allocations from multiple threads.
Edge cases:
Returns NULL only if exception handling is disabled; otherwise throws Arena_Failed.
Initial mutex initialization failure (rare, ENOMEM) triggers exception.
Suitable for short-lived objects or request-scoped memory management.
Returns
New arena instance on success.
Exceptions
Arena_Failed When underlying malloc or pthread_mutex_init fails. Common causes: Out of memory (ENOMEM), resource limits (RLIMIT_AS).
Thread Safety\n Yes - creates independent arena with its own mutex protecting
allocation state; safe from any thread.
Usage Example
TRY {
    Arena_T arena = Arena_new();
    // Allocations will use this arena
    char *buf = ALLOC(arena, 1024);
    // ... use buf ...
    // Arena automatically tracks all allocations
} EXCEPT(Arena_Failed) {
    fprintf(stderr, "Failed to create arena: out of memory\n");
    // Handle error - perhaps exit or fallback
} FINALLY {
    // No need to free individual allocations; dispose will handle
} END_TRY;
Advanced Usage with Reuse
Arena_T arena = Arena_new();
while (running) {
    TRY {
        // Per-iteration allocations
        void *data = CALLOC(arena, 1, sizeof(struct Request));
        // ... process request ...
    } EXCEPT(Arena_Failed) {
        // Handle allocation failure
    } END_TRY;
    Arena_clear(arena);  // Reset for next iteration
}
Arena_dispose(&arena);
Note
Use arenas to group related allocations (e.g., per-connection buffers, HTTP headers) for efficient bulk deallocation.
Warning
Avoid long-lived arenas with unbounded growth; monitor usage and clear periodically.
Does not support individual free(); all memory freed in bulk via clear() or dispose().
Complexity\n O(1) - single malloc for initial chunk and mutex initialization.
See also
Arena_dispose() for complete cleanup and memory reclamation.
Arena_alloc() and ALLOC() for making allocations from the arena.
Arena_clear() for resetting the arena without disposal.
docs/ERROR_HANDLING.md for exception handling best practices.
Referenced by main(), and main().
Except_raise()
void Except_raise (const Except_T * e, const char * file, int line)
Raise an exception (internal function - use RAISE() macro instead).
This internal function stores the provided exception information in the current thread's exception frame and performs a non-local jump using longjmp() to unwind the call stack to the nearest enclosing TRY block's setjmp() buffer. It enables structured exception handling in C without traditional unwinding.
Important behavior and edge cases:
Updates the top Except_frame with exception, file, and line information
Traverses the thread-local Except_stack to find the target frame
If no TRY frame exists on the stack, results in undefined behavior (likely crash)
Exception propagation continues up the call stack if not handled
Compatible with volatile variables to prevent optimizer issues
Typical internal usage within RAISE() and RERAISE macros for error conditions after failed operations, validations, or system calls.
Parameters
[in] e Exception to raise (must not be NULL; typically a const Except_T variable).
[in] file Source file name where the exception occurred (from FILE).
[in] line Source line number where the exception occurred (from LINE).
Returns
This function does not return normally; control is transferred via longjmp().
Exceptions
N/A - This function implements the raising mechanism itself.
Thread Safety\n No - modifies thread-local Except_stack and Except_frame.
Usage Example (via RAISE macro - preferred)
extern const Except_T Socket_Failed;
TRY {
  // Potentially failing operation
  if (connect(fd, addr, addrlen) < 0) {
    RAISE(Socket_Failed);  // Expands to Except_raise(&Socket_Failed,
__FILE__, __LINE__)
  }
} EXCEPT(Socket_Failed) {
  // Handle specific exception
  fprintf(stderr, "Connection failed: %s\n",
Except_frame.exception->reason); } FINALLY {
  // Cleanup resources
} END_TRY;
Direct Call (not recommended)
if (error) {
  Except_raise(&MyException, __FILE__, __LINE__);
}
Note
Always prefer RAISE() macro to automatically capture file and line info.
Warning
longjmp() bypasses destructors/cleanup; use FINALLY blocks for resource management.
Caller must ensure a valid TRY frame exists on the stack.
Complexity\n O(d) where d is depth of nested TRY blocks (stack traversal).
See also
RAISE() macro for convenient user-level exception raising with source location.
RERAISE for propagating caught exceptions.
TRY macro for establishing exception handling context.
Except_T for exception structure.
docs/ERROR_HANDLING.md for best practices and patterns.
Socket_get_monotonic_ms()
int64_t Socket_get_monotonic_ms (void)
Socket_get_monotonic_ms - Get current monotonic time in milliseconds.
Helper macros for common module patterns - use RAISE_MODULE_ERROR macro defined in each module that sets module_name appropriately.
Example module setup: SOCKET_DECLARE_MODULE_EXCEPTION(MyModule); #define RAISE_MODULE_ERROR(e) SOCKET_RAISE_MODULE_ERROR(MyModule, e) #define RAISE_FMT(e, fmt, ...) SOCKET_RAISE_FMT(MyModule, e, fmt,
<strong>VA_ARGS</strong>) #define RAISE_MSG(e, fmt, ...) SOCKET_RAISE_MSG(MyModule, e,
fmt, ##__VA_ARGS__)
Returns
Current monotonic time in milliseconds since arbitrary epoch
Thread Safety\n Yes (no shared state)
Uses CLOCK_MONOTONIC with CLOCK_REALTIME fallback. Immune to wall-clock changes (NTP adjustments, manual time changes). Returns 0 on failure.
Use for:
Rate limiting timestamps
Timer expiry calculations
Elapsed time measurements
Referenced by main(), reconnect_jitter(), and socketreconnect_now_ms().
Socket_geterrno()
int Socket_geterrno (void) extern
Socket_geterrno - Retrieve the raw POSIX errno from the last system call error.Returns the errno value captured at the last error condition (via SOCKET_ERROR_* macros or manual socket_last_errno = errno). Thread-local storage ensures per-thread isolation without locks.
Use after failed system calls, library functions, or when errno is set. Example: int err = Socket_geterrno(); if (err == EAGAIN) { // Handle non-blocking case (retryable) } else { SocketLog_error("Error: %s", Socket_safe_strerror(err)); }
Returns
Last errno (platform-specific, 0 if no error recorded).
Thread Safety\n Yes - thread-local.
Note
Persists until overwritten; not auto-reset.
Windows: Maps WSAGetLastError() to POSIX errno equivalents.
See also
Socket_GetLastError() for descriptive message.
Socket_geterrorcode() for SocketErrorCode mapping.
Socket_safe_strerror(err) for string conversion.
SocketError_categorize_errno(err) for category.
SocketError_is_retryable_errno(err) for retry logic.
docs/ERROR_HANDLING.md for errno best practices.
Socket_geterrorcode()
SocketErrorCode Socket_geterrorcode (void) extern
Socket_geterrorcode - Convert last errno to normalized SocketErrorCode.
Maps the raw errno from Socket_geterrno() to SocketErrorCode enum for platform-agnostic error handling. Facilitates switch statements, policy decisions, and logging without errno-specific code.
Example policy logic: SocketErrorCode code = Socket_geterrorcode(); switch (code) { case SOCKET_ERROR_ETIMEDOUT: // Exponential backoff retry via SocketRetry break; case SOCKET_ERROR_EINVAL: RAISE(Socket_InvalidArg); // Using SOCKET_RAISE_MSG break; case SOCKET_ERROR_ENOMEM: Arena_clear(global_arena); // Mitigate resource issue break; default: SocketLog_emitf(SOCKET_LOG_WARN, "Unhandled error code %d", code); }
Returns
Mapped SocketErrorCode (SOCKET_ERROR_UNKNOWN if no mapping).
Thread Safety\n Yes - stateless mapping.
See also
Socket_geterrno() source of raw errno.
SocketErrorCode for enum values and errno mappings.
SocketError_categorize_errno() higher-level abstraction.
SocketError_is_retryable_errno() quick retry check.
SOCKET_RAISE_FMT() macros that integrate error codes.
SocketHTTP and SocketTLS for protocol-specific extensions.
docs/ERROR_HANDLING.md for mapping tables and patterns.
Note
Covers 90%+ of socket errnos; unmapped fall to UNKNOWN.
Windows compatibility: WSA to POSIX translation.
Socket_GetLastError()
const char * Socket_GetLastError (void) extern
Socket_GetLastError - Retrieve the most recent formatted error message.
Returns pointer to thread-local buffer containing the last error description, formatted via SOCKET_ERROR_FMT() or SOCKET_ERROR_MSG() macros. Includes errno details, system messages, and custom context (e.g., "bind failed on fd=3: Address in use").
Buffer Management:
Thread-local: Each thread has independent buffer, no synchronization needed.
Overwritten on next error: Capture immediately after error condition.
Truncation-safe: Long messages append "[truncated]" marker.
Lifetime: Buffer valid until next error in same thread.
Typical Usage: if (some_socket_op() < 0) { const char *err = Socket_GetLastError(); SocketLog_emit(SOCKET_LOG_ERROR, MODULE, "%s", err); // Or raise exception with SOCKET_RAISE_MSG() }
Returns
Const pointer to null-terminated error string (never NULL, empty on no error).
Thread Safety\n Yes - returns thread-local static buffer.
Note
Do not free or modify returned string.
Integrates with Except_T for detailed exception reasons.
See also
Socket_geterrno() for raw errno value.
Socket_geterrorcode() for normalized SocketErrorCode.
Socket_safe_strerror() for raw errno strings.
SOCKET_ERROR_FMT() / SOCKET_ERROR_MSG() macros for formatting.
SOCKET_RAISE_FMT() / SOCKET_RAISE_MSG() for exception integration.
docs/ERROR_HANDLING.md for full error patterns.
Referenced by main().
Socket_safe_strerror()
const char * Socket_safe_strerror (int errnum) extern
Provides a thread-safe and bounds-checked implementation of strerror().
Socket_safe_strerror - Secure, thread-safe errno to string conversion.
This function converts a system error number (typically errno) into a human-readable string description. It serves as a safer alternative to the standard strerror() function, addressing common issues such as buffer overflows, non-thread-safe behavior, and potential modifications to errno. The implementation prefers strerror_r() when available (both GNU and POSIX variants are supported) and falls back to a platform-appropriate mechanism, such as thread-local storage or a static buffer.
Key features and behaviors:
Thread Safety: Each thread receives its own error string buffer, preventing race conditions in multi-threaded applications.
Bounds Checking: Input validation ensures no buffer overruns.
Fallback Handling: For unknown error codes or conversion failures, returns a descriptive string like "Unknown error #123".
No Side Effects: Does not modify errno or any global state.
Portability: Works across POSIX systems, with adaptations for variations in strerror_r() behavior (GNU returns char* vs POSIX int).
Typical usage includes error logging, user-facing messages, and debugging. It is particularly useful in exception handlers or after failed system calls.
Parameters
[in] errnum The error number to convert to a string (e.g., errno value). Supports 0 (success) and all standard POSIX error codes.
Returns
A pointer to a static, null-terminated string describing the error. The string is valid until the next call to this function in the same thread or thread exit. Never returns NULL.
Exceptions
None - This function does not raise exceptions; failures result in fallback strings.
Thread Safety\n Yes - Internal per-thread buffering or reentrant system calls
ensure concurrent access safety without locks.
Usage Example
// Simple error reporting after a system call
int fd = open("file.txt", O_RDONLY);
if (fd < 0) {
    const char *err = Socket_safe_strerror(errno);
    fprintf(stderr, "Failed to open file: %s\n", err);
}
Integration with Library Exceptions
TRY {
    Socket_T sock = Socket_connect("example.com", 80);
} EXCEPT(Socket_Failed) {
    // Socket_GetLastError() internally uses Socket_safe_strerror()
    SOCKET_LOG_ERROR_MSG("Connection failed: %s", Socket_GetLastError());
} END_TRY;
Note
The returned string should not be freed or modified; it points to internal static or thread-local data.
On some platforms, strerror_r() may require special handling for buffer sizes; this function abstracts those details.
Warning
Avoid using in signal handlers unless confirmed async-signal-safe on your platform (generally not recommended).
Complexity\n O(1) - Constant time operation involving string lookup or copy.
See also
strerror(3p) - Standard POSIX strerror() (unsafe in threads).
strerror_r(3p) - Reentrant version used internally.
Socket_GetLastError() - For library-specific errors with additional context.
Socket_geterrorcode() - Categorizes errors for retry logic.
SocketError_categorize_errno() - Classifies errno values.
Core Foundation Modules - Base infrastructure including other Utilities.
docs/ERROR-HANDLING.md - Detailed guide on error patterns in the library.
Provides strerror_r-like functionality with thread-local buffer to prevent races and buffer overflows common in strerror(). Handles invalid/unknown errnos gracefully, supports Windows WSA errors, and avoids locale dependencies.
Key Features:
Thread-safe: Per-thread buffer, no shared state or locks.
Overflow-safe: Fixed buffer with truncation handling.
Portable: POSIX errno + Windows WSA error translation.
Defensive: Returns "Unknown error" for invalid errnum (<0 or excessive).
Example: int err = errno; const char *msg = Socket_safe_strerror(err); SocketLog_emitf(SOCKET_LOG_ERROR, "Operation failed: %s (errno=%d)", msg, err); // Safe in multi-threaded servers, signal handlers (if no malloc needed).
Performance: Faster than strerror_r in contended scenarios; suitable for hot paths.
Parameters
errnum errno or WSA error code to convert (0 = "Success").
Returns
Const pointer to descriptive string (e.g., "No such file or directory").
Thread Safety\n Yes - thread-local buffer.
Note
Buffer overwritten on next call in thread; copy if needed.
Does not modify errno; pure function.
See also
Socket_GetLastError() for rich, contextual messages.
Socket_geterrno() to obtain current errno.
Socket_geterrorcode() for enum abstraction.
SocketError_categorize_errno(errnum) for error type.
docs/ERROR_HANDLING.md for strerror patterns and alternatives.
Note
Avoid dynamic allocation in signal-safe contexts on some platforms.
Customizable buffer size via SOCKET_ERROR_BUFSIZE (default 256).
socket_util_arena_strdup()
static char * socket_util_arena_strdup (Arena_T arena, const char * str) inline static
Duplicate string into arena.
Parameters
arena Arena for allocation.
str String to duplicate (may be NULL).
Returns
Duplicated string in arena, or NULL if str is NULL or alloc fails.
Thread Safety\n Yes (if arena is thread-safe)
Convenience function to duplicate a string into an arena. Avoids repeated strlen+alloc+memcpy pattern in calling code.
Definition at line 2010 of file SocketUtil.h.
References Arena_alloc().
socket_util_arena_strndup()
static char * socket_util_arena_strndup (Arena_T arena, const char * str, size_t maxlen) inline static
Duplicate string with max length into arena.
Parameters
arena Arena for allocation.
str String to duplicate (may be NULL).
maxlen Maximum characters to copy (excluding null terminator).
Returns
Duplicated string in arena, or NULL if str is NULL or alloc fails.
Thread Safety\n Yes (if arena is thread-safe)
Duplicates at most maxlen characters from str. Always null-terminates.
Definition at line 2038 of file SocketUtil.h.
References Arena_alloc().
socket_util_hash_djb2()
static unsigned socket_util_hash_djb2 (const char * str, unsigned table_size) inline static
Hash string using DJB2 algorithm.
Parameters
str String to hash (must not be NULL).
table_size Hash table size (should be prime for best distribution).
Returns
Hash value in range [0, table_size).
Thread Safety\n Yes (pure function, no shared state)
DJB2 hash: hash = hash * 33 + c The multiplication by 33 is optimized as (hash << 5) + hash. Provides good distribution for string keys like IP addresses.
Security note: DJB2 is a fast, simple hash for load distribution. NOT cryptographic - do not use for security-sensitive purposes.
Definition at line 1873 of file SocketUtil.h.
References SOCKET_UTIL_DJB2_SEED.
socket_util_hash_djb2_ci()
static unsigned socket_util_hash_djb2_ci (const char * str, unsigned table_size) inline static
Case-insensitive DJB2 hash.
Parameters
str String to hash (must not be NULL).
table_size Hash table size (should be prime for best distribution).
Returns
Hash value in range [0, table_size).
Thread Safety\n Yes (pure function, no shared state)
Case-insensitive variant for HTTP headers and similar keys. Converts ASCII uppercase to lowercase before hashing.
Definition at line 1920 of file SocketUtil.h.
References SOCKET_UTIL_DJB2_SEED.
socket_util_hash_djb2_ci_len()
static unsigned socket_util_hash_djb2_ci_len (const char * str, size_t len, unsigned table_size) inline static
Case-insensitive length-aware DJB2 hash.
Parameters
str String to hash (may contain null bytes).
len Length of string.
table_size Hash table size (should be prime for best distribution).
Returns
Hash value in range [0, table_size).
Thread Safety\n Yes (pure function, no shared state)
Combines length-aware and case-insensitive variants. Ideal for HTTP header name hashing where names aren't null-terminated.
Definition at line 1949 of file SocketUtil.h.
References SOCKET_UTIL_DJB2_SEED.
Referenced by httpclient_host_hash().
socket_util_hash_djb2_len()
static unsigned socket_util_hash_djb2_len (const char * str, size_t len, unsigned table_size) inline static
Hash string with explicit length using DJB2.
Parameters
str String to hash (may contain null bytes).
len Length of string.
table_size Hash table size (should be prime for best distribution).
Returns
Hash value in range [0, table_size).
Thread Safety\n Yes (pure function, no shared state)
Length-aware variant for non-null-terminated strings. Useful for parsing buffers where strings aren't null-terminated.
Definition at line 1897 of file SocketUtil.h.
References SOCKET_UTIL_DJB2_SEED.
socket_util_hash_fd()
static unsigned socket_util_hash_fd (int fd, unsigned table_size) inline static
Hash file descriptor using golden ratio multiplicative.
Parameters
fd File descriptor to hash (non-negative).
table_size Hash table size (should be prime for best distribution).
Returns
Hash value in range [0, table_size).
Thread Safety\n Yes (pure function, no shared state)
Uses the golden ratio constant (2^32 * (sqrt(5)-1)/2) for excellent distribution properties. Suitable for file descriptors, socket IDs, and other small integer keys.
Definition at line 1796 of file SocketUtil.h.
References HASH_GOLDEN_RATIO.
socket_util_hash_ptr()
static unsigned socket_util_hash_ptr (const void * ptr, unsigned table_size) inline static
Hash pointer using golden ratio multiplicative.
Parameters
ptr Pointer to hash (may be NULL).
table_size Hash table size (should be prime for best distribution).
Returns
Hash value in range [0, table_size).
Thread Safety\n Yes (pure function, no shared state)
Converts pointer to integer and applies golden ratio hash. Suitable for hashing opaque handles and memory addresses.
Definition at line 1813 of file SocketUtil.h.
References HASH_GOLDEN_RATIO.
socket_util_hash_uint()
static unsigned socket_util_hash_uint (unsigned value, unsigned table_size) inline static
Hash unsigned integer using golden ratio.
Parameters
value Unsigned integer to hash.
table_size Hash table size (should be prime for best distribution).
Returns
Hash value in range [0, table_size).
Thread Safety\n Yes (pure function, no shared state)
General-purpose hash for unsigned integers including request IDs.
Definition at line 1829 of file SocketUtil.h.
References HASH_GOLDEN_RATIO.
Referenced by httpclient_host_hash().
socket_util_hash_uint_seeded()
static unsigned socket_util_hash_uint_seeded (unsigned value, unsigned table_size, uint32_t seed) inline static
Seeded hash for collision resistance in security contexts.
Parameters
value Unsigned integer to hash.
table_size Hash table size (should be prime).
seed Per-instance random seed (e.g., from SocketCrypto_random_bytes).
Returns
Hash value in range [0, table_size).
Thread Safety\n Yes (pure function)
Adds seed to prevent predictable collisions in tables like HTTP/2 streams. Use for security-sensitive lookups where attacker may control keys.
Definition at line 1847 of file SocketUtil.h.
References HASH_GOLDEN_RATIO.
socket_util_round_up_pow2()
static size_t socket_util_round_up_pow2 (size_t n) inline static
Round up to next power of 2.
Parameters
n Value to round up (must be > 0).
Returns
Smallest power of 2 >= n.
Thread Safety\n Yes (pure function)
Useful for hash table sizing and circular buffer capacities where power-of-2 sizes allow efficient modulo via bitwise AND.
Definition at line 1977 of file SocketUtil.h.
SocketConfig_get_max_memory()
size_t SocketConfig_get_max_memory (void) extern
Retrieves the currently configured global memory limit.
Returns the maximum allowed total memory for all Arena allocations library-wide. A value of 0 indicates no limit (unlimited). This query is useful for monitoring, logging, and dynamic adjustment decisions in long-running applications.
This function is lightweight and can be called frequently without performance impact. It reflects the most recent limit set via SocketConfig_set_max_memory().
Returns
Current global memory limit in bytes (0 = unlimited).
Exceptions
None.
Thread Safety\n Yes - Atomic load operation.
Usage Example
size_t limit = SocketConfig_get_max_memory();
if (limit == 0) {
    printf("No global memory limit set.\n");
} else {
    printf("Global memory limit: %zu bytes\n", limit);
}
Note
Value may change concurrently if other threads call set_max_memory().
For usage stats, combine with SocketConfig_get_memory_used().
Complexity\n O(1).
See also
SocketConfig_set_max_memory() - Set the limit.
SocketConfig_get_memory_used() - Get current usage.
Arena_T - Related memory management.
Core Foundation Modules - Base Utilities.
SocketConfig_get_memory_used()
size_t SocketConfig_get_memory_used (void) extern
Retrieves the total current memory allocated via Arenas.
Returns the aggregate bytes currently allocated across all arenas in the process. This includes active allocations but excludes freed chunks that may be cached for reuse within arenas. Provides visibility into memory footprint for monitoring, alerting, and debugging memory leaks.
Tracked atomically to support concurrent updates from multiple threads. Value increases on successful alloc/calloc, decreases on arena clear/dispose.
Use in conjunction with get_max_memory() to compute utilization percentage. Helps detect leaks if value grows unbounded or doesn't decrease after load.
Returns
Total bytes currently in use by all arenas (0 if none allocated).
Exceptions
None.
Thread Safety\n Yes - Atomic load with memory barriers for consistency.
Usage Example
// Monitor memory usage
size_t used = SocketConfig_get_memory_used();
size_t max_allowed = SocketConfig_get_max_memory();
double utilization = max_allowed ? (double)used / max_allowed : 0.0;
if (utilization > 0.8) {
    SOCKET_LOG_WARN_MSG("High memory utilization: %.1f%% (%zu / %zu)",
                        utilization * 100, used, max_allowed);
}
In Tests for Leak Detection
// At end of test
assert(SocketConfig_get_memory_used() == 0 && "Memory leak detected!");
Note
Does not include malloc() or other non-arena allocations.
Cached free chunks within arenas may inflate the value slightly.
Multi-process: Each process tracks its own usage independently.
Warning
Not a replacement for heap profilers; focused on arena subsystem.
Complexity\n O(1) - Direct atomic read of global counter.
See also
SocketConfig_set_max_memory() - Configure limit checked against this.
SocketConfig_get_max_memory() - Get configured limit.
Arena_clear(), Arena_dispose() - Operations that reduce usage.
Core Foundation Modules - Memory management primitives.
docs/MEMORY-MANAGEMENT.md - Arena best practices and monitoring.
SocketConfig_set_max_memory()
void SocketConfig_set_max_memory (size_t max_bytes) extern
Sets the global memory limit enforced by all Arena allocators.
Configures a hard limit on total memory usage across all arenas created by the library. When this limit is reached, subsequent Arena_alloc() and Arena_calloc() calls will return NULL, triggering Arena_Failed exceptions in TRY blocks. This provides a defense against memory exhaustion attacks and helps in containerized environments with strict resource constraints.
The limit is tracked atomically and applies globally, shared across all threads and arenas. Setting to 0 disables the limit (unlimited memory). Initial default is unlimited (0). Changes take effect immediately for new allocations but do not retroactively affect existing ones.
Use cases:
Production servers: Limit to prevent DoS from malicious clients allocating excessive buffers via HTTP bodies or other means.
Embedded systems: Enforce deterministic memory usage.
Testing: Simulate out-of-memory conditions.
Monitoring: Pair with SocketConfig_get_memory_used() for runtime tracking and alerting when approaching the limit.
Parameters
[in] max_bytes The new global limit in bytes (0 = unlimited). Must be non-negative; values > SIZE_MAX are clamped.
Returns
None (void).
Exceptions
None - This function does not allocate memory or raise exceptions.
Thread Safety\n Yes - Uses atomic operations (stdatomic.h or compiler
intrinsics) for cross-thread safe updates without locks.
Usage Example
// Set 100MB global limit at startup
SocketConfig_set_max_memory(100 * 1024 * 1024);
// Later, check usage
size_t used = SocketConfig_get_memory_used();
size_t max = SocketConfig_get_max_memory();
if (used > max * 0.9) {
    SOCKET_LOG_WARN_MSG("Memory usage high: %zu / %zu bytes", used, max);
}
With Arena Allocation
Arena_T arena = Arena_new();
TRY {
    void *buf = ALLOC(arena, 1 << 30);  // 1GB attempt
    // If limit is 100MB, this will fail and raise Arena_Failed
} EXCEPT(Arena_Failed) {
    SOCKET_LOG_ERROR_MSG("Allocation failed - global limit exceeded");
} FINALLY {
    Arena_dispose(&arena);
} END_TRY;
Note
Existing allocations are not reclaimed; only new ones are limited.
Limit is enforced per allocation, not per arena - total across all arenas.
To reset to unlimited: SocketConfig_set_max_memory(0);
Warning
Setting a low limit mid-runtime may cause immediate OOM for ongoing operations.
In multi-process scenarios, each process has independent tracking.
Complexity\n O(1) - Atomic update with no locking or traversal.
See also
SocketConfig_get_max_memory() - Query current limit.
SocketConfig_get_memory_used() - Get current total usage.
Arena_alloc() - Allocation function that checks this limit.
Arena_T - Memory arena implementation.
Core Foundation Modules - Core memory management Utilities.
docs/MEMORY-MANAGEMENT.md - Guide to arena usage and limits.
SocketCrypto_base64_decode()
ssize_t SocketCrypto_base64_decode (const char * input, size_t input_len, unsigned char * output, size_t output_size) extern
Decode Base64-encoded string to binary data (RFC 4648).
Decodes Base64 string to binary data per RFC 4648.
Supports:
Standard Base64 alphabet (A-Za-z0-9+/).
URL-safe variant (-_ instead of +/) per RFC 4648 Section 5.
Padding with '=' characters.
Ignores whitespace per RFC 4648 Section 3.3.
Parameters
[in] input Base64-encoded input string (null-terminated if input_len == 0).
[in] input_len Length of input string (0 for auto-detection via null terminator).
[out] output Output buffer for decoded binary data.
[in] output_size Size of output buffer in bytes (must be at least SocketCrypto_base64_decoded_size(input_len) to guarantee space).
Returns
Length of decoded data on success, or -1 on error (invalid Base64 input, insufficient output size).
Exceptions
SocketCrypto_Failed if TLS not available or internal error.
Thread Safety\n Yes.
See also
SocketCrypto_base64_encode() for encoding.
SocketCrypto_base64_decoded_size() for buffer sizing.
SocketHTTP for header value decoding.
SocketCrypto_base64_decoded_size()
size_t SocketCrypto_base64_decoded_size (size_t input_len) extern
Calculate maximum buffer size needed for Base64 decoding.
Computes the maximum possible decoded size for SocketCrypto_base64_decode(). Actual decoded size may be smaller due to padding.
Formula: (input_len * 3 / 4) rounded up, excluding padding.
Parameters
[in] input_len Length of Base64 input string in bytes.
Returns
Maximum possible decoded binary size in bytes.
Thread Safety\n Yes.
See also
SocketCrypto_base64_decode() for decoding.
SocketCrypto_base64_encoded_size() for encoding size.
SocketCrypto_base64_encode()
ssize_t SocketCrypto_base64_encode (const void * input, size_t input_len, char * output, size_t output_size) extern
Encode binary data to Base64 string (RFC 4648).
Encodes binary data as Base64 string per RFC 4648. Output is null-terminated.
Required buffer size: ((input_len + 2) / 3) * 4 + 1 bytes. Use SocketCrypto_base64_encoded_size() to calculate required size.
Parameters
[in] input Input binary data to encode.
[in] input_len Length of input data in bytes (must not exceed SOCKET_SECURITY_MAX_ALLOCATION to avoid triggering security limits).
[out] output Output buffer for null-terminated Base64-encoded string.
[in] output_size Size of output buffer in bytes (must be at least SocketCrypto_base64_encoded_size(input_len)).
Returns
Length of encoded string (excluding null terminator) on success, or -1 on error (insufficient output size or invalid input).
Exceptions
SocketCrypto_Failed if TLS not available or internal error.
Thread Safety\n Yes.
See also
SocketCrypto_base64_decode() for decoding.
SocketCrypto_base64_encoded_size() for buffer sizing.
SocketWS for WebSocket key generation.
SocketCrypto_base64_encoded_size()
size_t SocketCrypto_base64_encoded_size (size_t input_len) extern
Calculate buffer size required for Base64 encoding.
Computes the exact buffer size needed for SocketCrypto_base64_encode(), including space for null terminator.
Formula: ((input_len + 2) / 3) * 4 + 1
Parameters
[in] input_len Length of input data in bytes (must not exceed SOCKET_SECURITY_MAX_ALLOCATION, though this function only computes size).
Returns
Required output buffer size in bytes, including null terminator.
Thread Safety\n Yes.
See also
SocketCrypto_base64_encode() for encoding.
SocketCrypto_base64_decoded_size() for decoding size calculation.
SocketCrypto_hex_decode()
ssize_t SocketCrypto_hex_decode (const char * input, size_t input_len, unsigned char * output, size_t output_capacity) extern
Decode hexadecimal string to binary data.
Decodes null-terminated or length-specified hex string to binary data. Accepts both uppercase (A-F) and lowercase (a-f) digits.
Input length must be even. Invalid characters cause error.
Required output capacity: input_len / 2 bytes.
Parameters
[in] input Hex-encoded input string (supports A-F a-f 0-9).
[in] input_len Length of input string (0 for auto-detect via null terminator; must be even number of hex digits).
[out] output Output buffer for decoded binary data.
[in] output_capacity Capacity of output buffer in bytes (at least input_len / 2).
Returns
Number of decoded bytes on success (min(input_len / 2, output_capacity)), or -1 on error (odd length, invalid chars, insufficient capacity).
Thread Safety\n Yes.
See also
SocketCrypto_hex_encode() for encoding.
SocketCrypto_secure_compare() for comparing decoded values securely.
SocketCrypto_hex_encode()
void SocketCrypto_hex_encode (const void * input, size_t input_len, char * output, int lowercase) extern
Encode binary data to hexadecimal string.
Encodes binary data as hexadecimal string (null-terminated). Each byte becomes two hex digits.
Required output buffer size: input_len * 2 + 1 bytes.
Parameters
[in] input Input binary data to encode.
[in] input_len Length of input in bytes (must not exceed SOCKET_SECURITY_MAX_ALLOCATION / 2 to fit output within limits).
[out] output Output buffer for null-terminated hexadecimal string (must have space for 2 * input_len + 1 bytes).
[in] lowercase 1 for lowercase hex digits (a-f), 0 for uppercase (A-F).
Thread Safety\n Yes.
See also
SocketCrypto_hex_decode() for decoding.
SocketCrypto_base64_encode() for alternative encoding.
SocketCrypto_hmac_sha256()
void SocketCrypto_hmac_sha256 (const void * key, size_t key_len, const void * data, size_t data_len, unsigned char output[32]) extern
Compute HMAC-SHA256 message authentication code.
Computes HMAC-SHA256 (RFC 2104, FIPS 198-1) of data using the given key.
Used for cookie signing, session tokens, and message authentication.
Security: Provides integrity and authenticity. Key should be at least 32 bytes for full security.
Parameters
[in] key HMAC key (should be cryptographically strong random bytes).
[in] key_len Key length in bytes (recommended: >= 32 bytes for security).
[in] data Input data to authenticate.
[in] data_len Data length in bytes (must not exceed SOCKET_SECURITY_MAX_ALLOCATION to avoid triggering security limits).
[out] output Output buffer for the HMAC-SHA256 digest (must be pre-allocated with at least SOCKET_CRYPTO_SHA256_SIZE bytes).
Exceptions
SocketCrypto_Failed on error or if TLS not available.
Thread Safety\n Yes.
See also
SocketCrypto_sha256() for plain hashing without key.
SocketHTTPServer for cookie signing examples.
SocketCrypto_md5()
void SocketCrypto_md5 (const void * input, size_t input_len, unsigned char output[16]) extern
Compute MD5 hash of input data (RFC 1321).
Computes the MD5 message digest of the input data.
Security: MD5 is cryptographically broken. Only use where required by specification (e.g., HTTP Digest authentication per RFC 7616).
Parameters
[in] input Input data to hash.
[in] input_len Length of input data in bytes (must not exceed SOCKET_SECURITY_MAX_ALLOCATION to avoid triggering security limits).
[out] output Output buffer for the MD5 digest (must be pre-allocated with at least SOCKET_CRYPTO_MD5_SIZE bytes).
Exceptions
SocketCrypto_Failed on error or if TLS not available.
Thread Safety\n Yes.
See also
SocketHTTPClient for HTTP authentication usage.
SocketCrypto_sha256() for secure alternative.
SocketCrypto_random_bytes()
int SocketCrypto_random_bytes (void * output, size_t len) extern
Generate cryptographically secure random bytes.
Fills output buffer with cryptographically secure random bytes. Uses OpenSSL RAND_bytes() if available, falls back to /dev/urandom or equivalent secure source.
Parameters
[out] output Output buffer to fill with cryptographically secure random bytes.
[in] len Number of bytes to generate (must not exceed SOCKET_SECURITY_MAX_ALLOCATION to avoid security limits).
Returns
0 on success, -1 on error (RNG failure or insufficient entropy).
Exceptions
SocketCrypto_Failed on internal error.
Thread Safety\n Yes.
See also
SocketCrypto_random_uint32() for 32-bit random integers.
SocketCrypto_websocket_key() for WebSocket key generation.
Security module for TLS session randomness.
Referenced by reconnect_jitter().
SocketCrypto_random_uint32()
uint32_t SocketCrypto_random_uint32 (void) extern
Generate a cryptographically secure 32-bit random integer.
Produces a uniform random uint32_t using secure RNG source.
Returns
Random uint32_t value (0 to UINT32_MAX).
Exceptions
SocketCrypto_Failed on RNG failure.
Thread Safety\n Yes.
See also
SocketCrypto_random_bytes() for arbitrary-length randomness.
SocketRateLimit for using random in token bucket jitter.
SocketCrypto_secure_clear()
void SocketCrypto_secure_clear (void * ptr, size_t len) extern
Securely clear sensitive data from memory.
Overwrites memory buffer with zeros using volatile operations and memory barriers to prevent compiler optimizations from eliminating the clear. Essential for securely erasing passwords, private keys, and other sensitive data from memory.
Parameters
[in,out] ptr Buffer containing sensitive data to securely clear (overwritten with zeros).
[in] len Length of buffer in bytes to clear.
Thread Safety\n Yes - uses volatile writes safe across threads.
Complexity\n O(len) - linear time to overwrite each byte.
Usage Example
char credentials[128];  // Temporary storage for auth info
// ... populate credentials ...
TRY {
    // Perform authentication or crypto op
} FINALLY {
    SocketCrypto_secure_clear(credentials, sizeof(credentials));
} END_TRY;
Use in FINALLY blocks to ensure clearing on all paths.
Note
Includes memory barriers to prevent dead-store elimination by compiler.
Warning
Insufficient against cold boot or memory dumps; layer with encryption.
See also
SocketHTTPClient-auth.c for HTTP auth credential clearing examples.
docs/HTTP-REFACTOR.md#secure-clear for refactoring notes.
Security Modules for broader Security Modules features.
Referenced by tls_secure_free_pkey().
SocketCrypto_secure_compare()
int SocketCrypto_secure_compare (const void * a, const void * b, size_t len) extern
Perform constant-time comparison of two buffers.
Compares two memory buffers in constant time, regardless of content, to prevent timing side-channel attacks. Essential for comparing MACs, hashes, signatures, or other security-sensitive data where early exits could leak information.
Parameters
[in] a First buffer to compare.
[in] b Second buffer to compare.
[in] len Number of bytes to compare (0 if buffers equal).
Returns
0 if buffers are equal, non-zero otherwise.
Thread Safety\n Yes.
See also
SocketCrypto_hmac_sha256() for generating comparison values.
SocketCrypto_secure_clear() for cleaning sensitive data after comparison.
Security module for protection mechanisms.
SocketCrypto_sha1()
void SocketCrypto_sha1 (const void * input, size_t input_len, unsigned char output[20]) extern
Compute SHA-1 hash of input data (RFC 3174).
Computes the SHA-1 message digest of the input data.
Security: SHA-1 is cryptographically broken for signatures but acceptable for WebSocket Sec-WebSocket-Accept computation per RFC 6455.
Parameters
[in] input Input data to hash.
[in] input_len Length of input data in bytes (must not exceed SOCKET_SECURITY_MAX_ALLOCATION to avoid triggering security limits).
[out] output Output buffer for the SHA-1 digest (must be pre-allocated with at least SOCKET_CRYPTO_SHA1_SIZE bytes).
Exceptions
SocketCrypto_Failed If underlying crypto fails (e.g., OpenSSL error), invalid parameters (null output, excessive length), or #SOCKET_HAS_TLS == 0.
Thread Safety\n Yes - no shared state, uses thread-local crypto contexts if
available.
Complexity\n O(input_len) - linear time proportional to input size.
Usage Example
unsigned char digest[SOCKET_CRYPTO_SHA1_SIZE];
const char *data = "example message";
size_t len = strlen(data);
TRY {
    SocketCrypto_sha1(data, len, digest);
    // digest now holds SHA-1 hash; safe to use in WebSocket handshake
} EXCEPT(SocketCrypto_Failed) {
    // Handle crypto failure (rare, e.g., no entropy)
} END_TRY;
Note
SHA-1 is legacy; used primarily for WebSocket RFC 6455 compliance.
Warning
Do not use for new cryptographic signatures due to known collision attacks.
See also
SocketCrypto_sha256() for secure hashing alternative.
SocketCrypto_websocket_accept() for WebSocket server handshake integration.
docs/WEBSOCKET.md for full WebSocket Security Modules guide.
SocketCrypto_sha256()
void SocketCrypto_sha256 (const void * input, size_t input_len, unsigned char output[32]) extern
Compute SHA-256 hash of input data (FIPS 180-4).
Computes the SHA-256 message digest of the input data.
Parameters
[in] input Input data to hash.
[in] input_len Length of input data in bytes (must not exceed SOCKET_SECURITY_MAX_ALLOCATION to avoid triggering security limits).
[out] output Output buffer for the SHA-256 digest (must be pre-allocated with at least SOCKET_CRYPTO_SHA256_SIZE bytes).
Exceptions
SocketCrypto_Failed If underlying crypto fails (e.g., OpenSSL error), invalid parameters (null output, excessive length), or #SOCKET_HAS_TLS == 0.
Thread Safety\n Yes - no shared state.
Complexity\n O(input_len) - linear time in input size.
Usage Example
unsigned char hash[SOCKET_CRYPTO_SHA256_SIZE];
const char *password = "user_password";
SocketCrypto_sha256(password, strlen(password), hash);
// Use hash for data integrity checks or key derivation (with salt/pepper)
Note
Recommended for general-purpose hashing where SHA-1 is insufficient.
Warning
Not suitable for password storage without additional salting/PBKDF.
See also
SocketCrypto_hmac_sha256() for keyed message authentication.
SocketCrypto_secure_compare() to verify hashes securely.
docs/SECURITY.md for cryptographic best practices.
SocketCrypto_websocket_accept()
int SocketCrypto_websocket_accept (const char * client_key, char output[29]) extern
Compute Sec-WebSocket-Accept value for server handshake (RFC 6455).
Validates client Sec-WebSocket-Key by computing base64(SHA1(key + GUID)), where GUID is "258EAFA5-E914-47DA-95CA-C5AB0DC85B11". Per RFC 6455 Section 4.2.2 server handshake.
Parameters
[in] client_key Client-provided Sec-WebSocket-Key header value (Base64, 24 chars).
[out] output Output buffer for Sec-WebSocket-Accept value (must be at least SOCKET_CRYPTO_WEBSOCKET_ACCEPT_SIZE bytes; null-terminated on success).
Returns
0 on success, -1 on error (invalid key length or crypto failure).
Exceptions
SocketCrypto_Failed on internal crypto error.
Thread Safety\n Yes.
See also
SocketCrypto_websocket_key() for client key generation.
SocketWS for full WebSocket protocol implementation.
SocketCrypto_websocket_key()
int SocketCrypto_websocket_key (char output[25]) extern
Generate random Sec-WebSocket-Key for client handshake (RFC 6455).
Generates 16 cryptographically secure random bytes, Base64-encodes them to 24 characters, and null-terminates the output. Per RFC 6455 Section 4.1 client handshake.
Parameters
[out] output Output buffer for generated Sec-WebSocket-Key (must be at least SOCKET_CRYPTO_WEBSOCKET_KEY_SIZE bytes; null-terminated on success).
Returns
0 on success, -1 on error (RNG failure).
Exceptions
SocketCrypto_Failed on internal error.
Thread Safety\n Yes.
See also
SocketCrypto_websocket_accept() for server validation.
SocketWS for WebSocket client connections.
SocketError_categorize_errno()
SocketErrorCategory SocketError_categorize_errno (int err) extern
SocketError_categorize_errno - Classify errno into SocketErrorCategory.
Pure function mapping raw errno to high-level SocketErrorCategory for policy decisions like retry, alert, or propagate. Conservative classification prioritizing safety and observability.
Detailed Mappings (POSIX errno examples):
NETWORK (retryable/transient): ECONNREFUSED, ECONNRESET, ECONNABORTED, ENETUNREACH, EHOSTUNREACH, ENETDOWN, EPIPE, ENOTCONN, EHOSTDOWN
TIMEOUT (backoff retry): ETIMEDOUT, operation deadline exceeded
RESOURCE (scale/relieve): ENOMEM, EMFILE, ENFILE, ENOBUFS, ENOSPC, EAGAIN (resource form)
PROTOCOL (fix input/config): EINVAL, EPROTO, EPROTONOSUPPORT, EAFNOSUPPORT, EISCONN, EALREADY
APPLICATION: Passed through for module-specific (e.g., HTTP 4xx)
UNKNOWN: Rare or platform-specific; log for analysis
Usage in Error Handling: int err = errno; // Or Socket_geterrno() SocketErrorCategory cat = SocketError_categorize_errno(err); if (cat == SOCKET_ERROR_CATEGORY_NETWORK || cat == SOCKET_ERROR_CATEGORY_TIMEOUT) { // Retry with backoff using SocketRetry_policy } else if (cat == SOCKET_ERROR_CATEGORY_RESOURCE) { SocketMetrics_increment(SOCKET_METRIC_RESOURCE_EXHAUSTED); // Alert or drain pools } SocketLog_emit_structured(SOCKET_LOG_WARN, MODULE, "Error categorized", SOCKET_LOG_FIELDS({"category", SocketError_category_name(cat)}, {"errno", "%d", err}));
Extension: Modules can use category in custom exceptions or rate limiting.
Parameters
err errno value to classify (0 or positive; negative treated as UNKNOWN).
Returns
Appropriate SocketErrorCategory (UNKNOWN for unmapped).
Thread Safety\n Yes - pure function, no state.
Note
Optimizes common cases with switch or table lookup for speed.
Windows: Translates WSA errors to POSIX errno before classification.
See also
SocketErrorCategory for category behaviors and retry guidelines.
SocketError_is_retryable_errno(err) complementary check.
Socket_geterrorcode() for finer-grained enum.
SocketError_category_name(cat) for string representation.
SocketRateLimit for category-based throttling.
SocketPool for resource error handling in pools.
docs/ERROR_HANDLING.md for full categorization table and strategies.
docs/SECURITY.md for secure error handling (avoid info leaks).
Note
Pure function: Deterministic, side-effect free, suitable for fuzzing/tests.
SocketEvent_emit_accept()
void SocketEvent_emit_accept (int fd, const char * peer_addr, int peer_port, const char * local_addr, int local_port)
Event emission functions - Thread-safe notification of key socket events.
These functions emit events to registered callbacks for observability, metrics, tracing, and alerting integration. Events are dispatched asynchronously from worker threads or main event loops to avoid blocking.
See also
SocketEvent_register() to register global event handlers.
SocketEventCallback for the callback signature.
SocketEventRecord for the event data structure.
SocketEvent_unregister() to remove handlers.
SocketLogContext for correlating events with per-connection logs.
Emit new connection accept event.
Parameters
fd Newly accepted client file descriptor.
peer_addr Peer IP address as null-terminated C string (IPv4/IPv6).
peer_port Peer port number (host byte order).
local_addr Local bound IP address as null-terminated C string.
local_port Local listening port number (host byte order).
Thread Safety\n Yes - invokes callbacks with mutex protection.
Note
Caller must ensure strings remain valid until all callbacks complete.
Automatically sets SocketLogContext.connection_fd for the event.
See also
SocketEvent_register() to handle accept events (e.g., for metrics).
SocketPool_add() to immediately add connection to managed pool.
Socket_accept() for the underlying accept operation.
Socket_getpeeraddr() and Socket_getpeerport() for address queries.
SocketEvent_emit_connect()
void SocketEvent_emit_connect (int fd, const char * peer_addr, int peer_port, const char * local_addr, int local_port)
Emit successful outbound connection event.
Parameters
fd Connected socket file descriptor.
peer_addr Remote peer IP address as null-terminated C string.
peer_port Remote peer port number (host byte order).
local_addr Local source IP address as null-terminated C string.
local_port Local ephemeral source port (host byte order).
Thread Safety\n Yes - invokes callbacks with mutex protection.
Note
Caller must ensure strings remain valid until callbacks complete.
Sets SocketLogContext.connection_fd for event correlation.
See also
SocketEvent_register() to handle connect events.
SocketReconnect_state() integration for auto-reconnect scenarios.
Socket_connect() or SocketTLS_handshake() for connection establishment.
Socket_getlocaladdr() for local address retrieval.
SocketEvent_emit_dns_timeout()
void SocketEvent_emit_dns_timeout (const char * host, int port)
Emit DNS resolution timeout event.
Parameters
host Hostname or address that timed out during resolution.
port Destination port associated with the DNS request (for context).
Thread Safety\n Yes
See also
SocketEvent_register() to handle DNS timeout events.
SocketDNS_resolve() for initiating async DNS lookups.
SocketDNS_settimeout() to configure DNS operation timeouts.
SocketHappyEyeballs for parallel resolution strategies.
SocketMetrics_increment(SOCKET_METRIC_DNS_REQUEST_TIMEOUT) for metrics.
SocketEvent_emit_poll_wakeup()
void SocketEvent_emit_poll_wakeup (int nfds, int timeout_ms)
Emit poll/epoll/kqueue wakeup event (for performance monitoring).
Parameters
nfds Number of file descriptors monitored in the poll set.
timeout_ms Timeout value passed to poll() or equivalent (-1 = infinite).
Thread Safety\n Yes
Note
Primarily for debugging high-frequency wakeups or timeout tuning.
See also
SocketEvent_register() to monitor poll performance.
SocketPoll_wait() for the underlying polling mechanism.
SocketPoll_getregisteredcount() to correlate with registered FDs.
SocketTimer for timer-driven wakeups.
SocketMetrics_increment(SOCKET_METRIC_POLL_WAKEUPS) for metrics tracking.
SocketEvent_register()
void SocketEvent_register (SocketEventCallback callback, void * userdata)
SocketEvent_register - Register an event handler.
Parameters
callback Callback function to register
userdata User data passed to callback
Thread Safety\n Yes
SocketEvent_unregister()
void SocketEvent_unregister (SocketEventCallback callback, const void * userdata)
SocketEvent_unregister - Unregister an event handler.
Parameters
callback Callback function to unregister
userdata User data that was passed to register
Thread Safety\n Yes
SocketLog_clearcontext()
void SocketLog_clearcontext (void) extern
Reset thread-local logging context to default state.
Thread Safety\n Yes - local TLS update, no synchronization.
Returns
void
Clears current thread's logging context by setting all fields to defaults: trace_id and request_id to empty strings, connection_fd to -1. Ensures no leakage of previous request data to subsequent logs. Idempotent; safe to call multiple times.
Recommended after completing request/connection handling to isolate logs. Alternative to SocketLog_setcontext(NULL); slightly more explicit.
See also
SocketLog_setcontext(NULL) functional equivalent.
SocketLog_getcontext() to verify cleared (returns non-NULL but empty).
SocketLogContext default values.
docs/LOGGING.md context management patterns.
Note
Does not affect global log level or callbacks.
SocketLog_emit()
void SocketLog_emit (SocketLogLevel level, const char * component, const char * message)
Emit a log message.
Parameters
level Log level.
component Component name (may be NULL).
message Log message (may be NULL).
Thread Safety\n Yes
Emit a plain log message without formatting or variable arguments.
Parameters
level Log severity level (e.g., SOCKET_LOG_INFO).
component Component or module name for categorization (may be NULL for default "Socket").
message Fixed log message string (may be NULL, logged as empty string).
Thread Safety\n Yes - synchronized emission to callback or default handler.
Dispatches the message to the registered SocketLogCallback or default stdout logger. Automatically filtered by global minimum level from SocketLog_setlevel(). Includes thread-local SocketLogContext data if set, for correlation.
Best for static messages; use SocketLog_emitf() for dynamic content.
Returns
void
See also
SocketLog_emitf() for formatted variant.
SocketLog_emit_structured() for key-value metadata.
SocketLog_setlevel() to control filtering.
SocketLogCallback for custom handling.
SocketLogContext for auto-included thread metadata.
docs/LOGGING.md for subsystem overview and examples.
Note
No formatting performed; message should be pre-formatted if needed.
Integrates with SocketMetrics for log-related counters if emitted.
SocketLog_emit_structured()
void SocketLog_emit_structured (SocketLogLevel level, const char * component, const char * message, const SocketLogField * fields, size_t field_count) extern
Emit log message with attached structured key-value metadata fields.
@level: Log level @component: Component name @message: Log message @fields: Array of key-value pairs (may be NULL) @field_count: Number of fields
Thread Safety\n Yes
Emits a log message with structured key-value pairs. If a structured callback is set, it receives the fields directly. Otherwise, fields are formatted as "key=value" pairs appended to the message.
SocketLog_emitf()
void SocketLog_emitf (SocketLogLevel level, const char * component, const char * fmt, ...)
Emit a formatted log message using printf-style variable arguments.
Parameters
level Log level.
component Component name.
fmt Printf-style format string.
... Format arguments.
Thread Safety\n Yes
Returns
void
Performs safe formatting using internal buffer, then emits to registered callback or default logger. Supports common printf specifiers; limits length to prevent DoS from excessive args. Automatically includes thread-local SocketLogContext for tracing and correlation IDs.
Use via convenience macros like SOCKET_LOG_INFO_MSG() which define component and expand to this function. Essential for dynamic logging in hot paths.
Warning
fmt must be a compile-time literal string to prevent format string vulnerabilities (e.g., x, n exploits with user input). Validate or escape user data in arguments, not fmt.
Note
Truncates long messages; failure in formatting logs internal error.
Filtered by global SocketLog_getlevel(); lower levels suppressed.
See also
SocketLog_emit() for non-formatted logs.
SocketLog_emitfv() va_list variant for wrappers.
SocketLog_emit_structured() for structured/metadata logs.
SOCKET_LOG_*_MSG macros for module-specific usage.
SocketLog_setcallback() for output customization.
SocketLogContext auto-appended metadata.
docs/LOGGING.md Security Modules and performance guidelines.
Core Foundation Modules for related Utilities like SocketMetrics.
SocketLog_emitfv()
void SocketLog_emitfv (SocketLogLevel level, const char * component, const char * fmt, va_list args)
Emit formatted log message using va_list for arguments.
Parameters
level Log level.
component Component name.
fmt Printf-style format string.
args Format arguments as va_list.
Thread Safety\n Yes
Returns
void
Identical to SocketLog_emitf() but accepts pre-prepared va_list for functions that need to forward variable arguments (e.g., logging wrappers, error handlers). Performs formatting and emission with same safety checks, filtering, and context integration.
Use when va_list is available from caller; avoids variadic overhead. Same security requirement: fmt literal only.
Warning
fmt must be compile-time literal; same risks as emitf().
Note
Does not consume or modify args; valid until callback completes.
See also
SocketLog_emitf() primary variadic version.
SocketLog_emit() non-formatted.
SocketLog_emit_structured() structured alternative.
docs/LOGGING.md for advanced usage.
SocketLog_setcallback() for output routing.
SocketLog_getcallback()
SocketLogCallback SocketLog_getcallback (void ** userdata)
Retrieve the currently registered custom logging callback and its userdata.
Queries the global logging callback previously set via SocketLog_setcallback(). Useful for verification, dynamic reconfiguration, or integration with config systems. Returns the active callback function and optionally populates userdata pointer. If no custom callback set, returns the internal default logger reference.
Behavior details:
Thread-safe read: Safe to call from any thread without blocking.
Default return: Points to static default_logger; do not free or modify.
Userdata output: If provided, sets to the userdata passed in setcallback(); may be NULL.
Immediate reflection: Sees changes from SocketLog_setcallback() atomically.
Edge cases: Calling before any setcallback() returns default. Userdata NULL if not set. Typical use: In config reload to check/restore state, or logging system introspection.
Parameters
[out] userdata Pointer to receive the userdata associated with current callback (may be NULL; not modified if param NULL).
Returns
Pointer to current SocketLogCallback, or internal default if none registered.
Exceptions
None - pure query function, no allocations or side effects.
Thread Safety\n Yes - atomic read or lock-free; no blocking or state change.
Usage Example
// Verify logging configuration at startup or reload
void verify_logging_config(void) {
  void **ud_ptr = NULL;  // Not interested in userdata
  SocketLogCallback cb = SocketLog_getcallback(&ud_ptr);
  if (cb == default_logger) {  // Assume default_logger defined or check
    SOCKET_LOG_WARN_MSG("No custom logger set; using default console
output");
    // Optionally set one
    SocketLog_setcallback(custom_logger, some_ud);
  } else {
    void *ud = ud_ptr ? *ud_ptr : NULL;
    SOCKET_LOG_INFO_MSG("Custom logger active with userdata %p", ud);
  }
}
// In main after potential config changes
verify_logging_config();
Retrieving Userdata for Dynamic Behavior
// Get userdata to access logger-specific config
void *logger_ud = NULL;
SocketLogCallback cb = SocketLog_getcallback(&logger_ud);
if (logger_ud) {
  // Cast to app-specific struct, e.g., LoggerConfig *cfg = logger_ud;
  // Adjust levels or rotate files based on cfg
  if (cfg->max_size_reached) rotate_log_file(cfg);
}
Note
Returned callback pointer remains valid until next setcallback(); do not free.
Default logger is static internal; applications should not call it directly.
Userdata is exactly as passed to setcallback(); may be NULL even if cb custom.
Warning
Do not modify userdata through output param; it's read-only view.
Complexity\n O(1) - direct access to global state, no loops or allocations.
See also
SocketLog_setcallback() complementary setter function.
SocketLogCallback type definition for signature.
default_logger internal fallback (not public).
SocketLogContext usable in callbacks retrieved this way.
docs/LOGGING.md for logging configuration management.
SocketLog_getcontext()
const SocketLogContext * SocketLog_getcontext (void) extern
Retrieve pointer to current thread's logging context.
Returns
Const pointer to thread-local SocketLogContext or NULL if unset.
Thread Safety\n Yes - direct read from TLS, read-only access.
Returns
Const pointer to thread-local SocketLogContext or NULL if unset.
For use in custom SocketLogCallback or SocketLogStructuredCallback to append context fields (trace_id, request_id, connection_fd) to log output. Enables distributed tracing, request correlation, and per-connection logging. Returned pointer remains valid until next set/clear in this thread. Do not free or mutate; structure owned by logging subsystem.
Example in callback: const SocketLogContext *ctx = SocketLog_getcontext(); if (ctx) { fprintf(stream, "[%s] fd=%d %s\n", ctx->trace_id ?: "none", ctx->connection_fd, message); }
Note
NULL if never set or cleared; check before deref.
Fields may be empty strings or -1; validate as needed.
See also
SocketLog_setcontext() to populate.
SocketLog_clearcontext() to NULLify.
SocketLogContext field semantics.
docs/LOGGING.md for callback patterns.
SocketLogStructuredCallback context param.
SocketLog_getlevel()
SocketLogLevel SocketLog_getlevel (void) extern
Retrieve the active global minimum log level threshold.
Returns
Current global SocketLogLevel threshold (e.g., SOCKET_LOG_WARN).
Thread Safety\n Yes - atomic or mutex-protected read.
Returns
Current global SocketLogLevel threshold (e.g., SOCKET_LOG_WARN).
Queries the minimum severity for log emission. Logs below this level are suppressed. Useful for runtime configuration checks or conditional detailed logging. Reflects last call to SocketLog_setlevel() or default (SOCKET_LOG_INFO).
Example: if (SocketLog_getlevel() <= SOCKET_LOG_DEBUG) { SOCKET_LOG_DEBUG_MSG("Detailed state: %d", state); }
See also
SocketLog_setlevel() to configure.
SocketLogLevel enum definitions.
SocketLog_levelname() for string conversion.
docs/LOGGING.md configuration details.
Note
Global value; changes affect all threads immediately.
SocketLog_levelname()
const char * SocketLog_levelname (SocketLogLevel level)
SocketLog_levelname - Human-readable string for SocketLogLevel enum.
Converts log level enum to static string for logging, UI display, or config parsing. Enables readable output in logs, metrics labels, or error messages.
Returns:
"TRACE" for SOCKET_LOG_TRACE
"DEBUG" for SOCKET_LOG_DEBUG
"INFO" for SOCKET_LOG_INFO
"WARN" for SOCKET_LOG_WARN
"ERROR" for SOCKET_LOG_ERROR
"FATAL" for SOCKET_LOG_FATAL
Usage: SocketLogLevel lvl = SocketLog_getlevel(); const char *name = SocketLog_levelname(lvl); SocketLog_emit_structured(SOCKET_LOG_INFO, "Config", "Log level set", SOCKET_LOG_FIELDS({"level", name}));
Parameters
level Log level enum value.
Returns
Static const string (e.g., "INFO"); never NULL.
Thread Safety\n Yes - returns static readonly data.
Note
Strings are uppercase English; extend for i18n if needed.
See also
SocketLogLevel enum for values and semantics.
SocketLog_setlevel() for level configuration.
SocketLog_getlevel() to get current level.
SocketLog_emit*() functions that may use level names internally.
docs/LOGGING.md for logging configuration and levels.
SocketLog_setcallback()
void SocketLog_setcallback (SocketLogCallback callback, void * userdata)
Register a custom callback for all library log emissions.
Allows applications to override the default stdout/stderr logging with a custom handler for integration with file systems, syslog, structured logging (JSON), or monitoring tools like ELK or Splunk. The callback receives every log message emitted by the library across all modules and threads.
Key behaviors:
Global effect: Affects all SocketLog_emit*() calls after registration.
Synchronous invocation: Called directly from emitting thread; must be non-blocking.
Filtering integration: Respects global SocketLog_getlevel() threshold.
Context enrichment: Callbacks can access thread-local SocketLogContext for trace IDs, request IDs, and connection FDs to correlate logs.
Edge cases and best practices:
Heavy callbacks may block event loops; use async queues or batching for production.
No reentrancy guarantee; avoid logging from within callback to prevent recursion.
Userdata is passed verbatim; application owns memory management and lifetime.
Default fallback: If NULL, uses timestamped console output with level prefixes.
Typical usage: Register early in application init after parsing config (e.g., log file path). For structured logging, also set SocketLog_setstructuredcallback() for field support.
Parameters
[in] callback Callback function or NULL for default logger.
[in] userdata Opaque user data passed unchanged to callback on every invocation.
Thread Safety\n Yes - internal lock protects registration; effective immediately
across threads.
Returns
void
Thread Safety\n Yes - internal lock protects registration; effective immediately
across threads.
Usage Example
  // Custom logger to file with timestamps
  static void file_logger(void *userdata, SocketLogLevel level,
                          const char *component, const char *message) {
    FILE *logfile = (FILE *)userdata;
    if (!logfile) return;  // Safety check
    time_t now = time(NULL);
    struct tm *tm_info = localtime(&now);
    char timebuf[32];
    strftime(timebuf, sizeof(timebuf), "%Y-%m-%d %H:%M:%S", tm_info);
    const SocketLogContext *ctx = SocketLog_getcontext();
    fprintf(logfile, "[%s] [%s] %s %s: %s", timebuf,
SocketLog_levelname(level),
            component ? component : "unknown", ctx && ctx->trace_id[0] ?
ctx->trace_id : "no-trace",
            message ? message : "(null)");
    fputc('\n', logfile);
    fflush(logfile);
  }
  // Registration in application startup
  TRY {
    FILE *logf = fopen("app_socket.log", "a");
    if (logf) {
      SocketLog_setcallback(file_logger, logf);
      SocketLog_setlevel(SOCKET_LOG_INFO);  // Production level
      SOCKET_LOG_INFO_MSG("Custom logging initialized to file");
    }
  } EXCEPT (Socket_Failed) {
    // Handle file open failure
    fprintf(stderr, "Failed to open log file: %s\n", Socket_GetLastError());
  } END_TRY;
Advanced Usage with Error Handling and Cleanup
// With cleanup in shutdown
static FILE *g_logfile = NULL;
static void shutdown_logger(void) {
  if (g_logfile) {
    SocketLog_setcallback(NULL, NULL);  // Restore default
    fclose(g_logfile);
    g_logfile = NULL;
  }
}
// In main: atexit(shutdown_logger);
// Register as above
Note
The default logger outputs to stderr for ERROR/FATAL, stdout for others.
Callback invoked even for filtered levels? No, filtered before callback.
Warning
Manage userdata lifetime; library won't free it or track ownership.
Synchronous calls: Slow callbacks can impact library performance.
Complexity\n O(1) - constant time registration, no allocation or loops.
See also
SocketLogCallback for the exact function signature and parameters.
SocketLog_getcallback() to retrieve or verify the current registered callback.
SocketLogContext for accessing trace and connection info inside callback.
SocketLog_setlevel() to control which levels reach the callback.
SocketLog_setstructuredcallback() for separate handling of structured logs.
SocketLog_emitf() and SOCKET_LOG_*_MSG macros that trigger the callback.
docs/LOGGING.md for full logging subsystem guide and best practices.
Core Foundation Modules for metrics and error Utilities integrated with logging.
SocketLog_setcontext()
void SocketLog_setcontext (const SocketLogContext * ctx) extern
Set thread-local logging context for request tracing and metadata.
Parameters
ctx Context to copy (NULL clears context).
Thread Safety\n Yes - thread-local storage (TLS), no locks or races.
Returns
void
Copies ctx into per-thread storage for use by subsequent SocketLog_emit*() calls in this thread. Custom callbacks can access via SocketLog_getcontext() to enrich logs with trace_id (e.g., UUID), request_id, or connection_fd. NULL ctx clears to defaults (empty strings, fd=-1).
Pattern for request handling: SocketLogContext ctx = { .connection_fd = sock_fd }; snprintf(ctx.trace_id, sizeof(ctx.trace_id), "%llx", generate_trace()); SocketLog_setcontext(&ctx); // ... process request with contextual logs ... SocketLog_clearcontext(); // Or let persist per thread
Note
Fixed-size strings; caller must null-terminate and fit within limits.
Context visible only to current thread; inter-thread via app logic.
See also
SocketLog_getcontext() retrieval in callbacks.
SocketLog_clearcontext() reset equivalent to set(NULL).
SocketLogContext fields details.
SocketLogStructuredCallback for field usage in structured logs.
docs/LOGGING.md tracing integration.
SocketEvent_emit_* auto-setting connection_fd for events.
SocketLog_setlevel()
void SocketLog_setlevel (SocketLogLevel min_level) extern
SocketLog_setlevel - Configure global minimum log level threshold.
Filters log emissions by severity, suppressing verbose messages in production while enabling detailed tracing in development. Thread-safe update with immediate effect on all subsequent logs across threads (via atomic or mutex).
Levels from verbose to critical:
SOCKET_LOG_TRACE: Ultra-verbose (internal state changes)
SOCKET_LOG_DEBUG: Debugging info (function entry/exit, params)
SOCKET_LOG_INFO: Normal operations (connections, requests)
SOCKET_LOG_WARN: Recoverable issues (retries, timeouts)
SOCKET_LOG_ERROR: Errors (failed ops, exceptions)
SOCKET_LOG_FATAL: Critical failures (abort imminent)
Global effect: Applies to all modules using SocketLog_emit*(). Change via config file, env var, or runtime API. Persists until changed or process exit.
Best Practices:
Production: SOCKET_LOG_WARN or higher to reduce noise.
Development: SOCKET_LOG_DEBUG for troubleshooting.
Use SocketLog_getlevel() to read current for conditional logging.
Integrate with SocketHTTPClient_config for per-client levels if needed.
Example: // Runtime adjustment SocketLog_setlevel(SOCKET_LOG_DEBUG); // Verbose mode // Or from config/env if (getenv("SOCKET_LOG_LEVEL")) { SocketLogLevel lvl = SocketLog_method_parse(getenv("SOCKET_LOG_LEVEL")); Assume parse func SocketLog_setlevel(lvl); } const char *current = SocketLog_levelname(SocketLog_getlevel()); SocketLog_emit(SOCKET_LOG_INFO, "Config", "Log level set to %s", current);
Parameters
min_level New minimum level (SOCKET_LOG_TRACE = most verbose).
Thread Safety\n Yes - atomic update or mutex-protected.
Returns
void (no return; errors logged internally).
Note
Default: SOCKET_LOG_INFO; set early in main() or init.
Dynamic change safe; no restart needed.
See also
SocketLog_getlevel() to query current threshold.
SocketLog_levelname() for string representation.
SocketLogLevel enum for level definitions.
SocketLog_emit*() functions affected by this setting.
docs/LOGGING.md for advanced configuration and integration.
SocketConfig for global config management including logs.
Note
Affects SocketLog_emit*() calls after invocation; pending buffered logs unaffected.
SocketLog_setstructuredcallback()
void SocketLog_setstructuredcallback (SocketLogStructuredCallback callback, void * userdata) extern
Register callback for handling structured log emissions with fields.
@callback: Callback function or NULL to disable structured logging @userdata: User data passed to callback
Thread-safe: Yes (mutex protected)
When set, SocketLog_emit_structured() will invoke this callback instead of the regular callback, providing access to structured fields.
SocketMetrics_count()
size_t SocketMetrics_count (void)
SocketMetrics_count - Get total number of defined metrics.
Returns
Number of metrics
Thread Safety\n Yes
SocketMetrics_getsnapshot()
void SocketMetrics_getsnapshot (SocketMetricsSnapshot * snapshot)
SocketMetrics_getsnapshot - Get atomic snapshot of all metrics.
Parameters
snapshot Output structure to receive metric values
Thread Safety\n Yes
SocketMetrics_increment()
void SocketMetrics_increment (SocketMetric metric, unsigned long value)
SocketMetrics_increment - Increment a metric counter.
Parameters
metric Metric to increment
value Amount to add
Thread Safety\n Yes
SocketMetrics_legacy_reset()
void SocketMetrics_legacy_reset (void)
SocketMetrics_legacy_reset - Reset legacy metrics to zero.
Thread Safety\n Yes
Note
This is the legacy API. For new code, use SocketMetrics_reset() from SocketMetrics.h.
SocketMetrics_name()
const char * SocketMetrics_name (SocketMetric metric)
SocketMetrics_name - Get human-readable name for a metric.
Parameters
metric Metric to get name for
Returns
Static string with metric name
Thread Safety\n Yes
SocketMetrics_snapshot_value()
static unsigned long long SocketMetrics_snapshot_value (const SocketMetricsSnapshot * snapshot, SocketMetric metric) inline static
Get a specific value from metrics snapshot.
Parameters
snapshot Snapshot to read from.
metric Metric to retrieve.
Returns
Metric value, or 0 for invalid inputs.
Thread Safety\n Yes (read-only operation)
Definition at line 1005 of file SocketUtil.h.
References SOCKET_METRIC_COUNT, and SocketMetricsSnapshot::values.
SocketSecurity_check_add()
int SocketSecurity_check_add (size_t a, size_t b, size_t * result) extern
Validate addition of two sizes for potential overflow.
Checks if adding two size_t values would overflow size_t before performing the operation. Optionally computes and stores the result in *result if safe.
Essential for safe buffer expansions, offset calculations, or total size computations (e.g., current_size + additional). Check: safe if a <= SIZE_MAX
b.
Parameters
[in] a First addend (size_t operand).
[in] b Second addend (size_t operand).
[out] result Optional pointer to store a + b if no overflow, or NULL to check only.
Returns
1 if addition safe (no overflow), 0 if would overflow.
Thread Safety\n Yes - pure function.
Usage Example
size_t current_buf = SocketBuf_available(buf);
size_t incoming = recv_len;
size_t new_total;
if (SocketSecurity_check_add(current_buf, incoming, &new_total)) {
    if (new_total > SocketSecurity_get_max_allocation()) {
        // Still too large, even if no overflow
        return -1;
    }
    // Safe to append to buffer
    SocketBuf_write(buf, data, incoming);
} else {
    // Overflow: handle by truncating or error
    fprintf(stderr, "Buffer expansion %zu + %zu overflows\n", current_buf,
incoming);
}
Note
For inline use, SOCKET_SECURITY_CHECK_OVERFLOW_ADD macro available.
Complexity\n O(1)
See also
SocketSecurity_safe_add() computes sum or SIZE_MAX on failure.
SocketSecurity_check_multiply() companion for multiplication.
SocketSecurity_check_size() for validating the resulting size.
Referenced by hpack_entry_size().
SocketSecurity_check_multiply()
int SocketSecurity_check_multiply (size_t a, size_t b, size_t * result) extern
Validate multiplication of two sizes for potential overflow.
Checks if multiplying two size_t values would overflow before performing the operation. Optionally computes and stores the result in *result if safe.
Critical for safe size calculations like buffer sizing (e.g., count * element_size) or capacity computations. Uses division-based check: safe if a <= SIZE_MAX / b (b != 0).
Parameters
[in] a First multiplier (size_t operand).
[in] b Second multiplier (size_t operand).
[out] result Optional pointer to store a * b if no overflow, or NULL to check only.
Returns
1 if multiplication safe (no overflow, including b==0 case), 0 if overflow risk.
Thread Safety\n Yes - pure arithmetic function.
Usage Example
size_t count = 1000;
size_t elem_size = 1024;
size_t product;
if (SocketSecurity_check_multiply(count, elem_size, &product)) {
    // Safe: allocate buffer of product bytes
    void *array = Arena_alloc(arena, product, __FILE__, __LINE__);
} else {
    fprintf(stderr, "%zu * %zu would overflow\n", count, elem_size);
    // Handle: reduce size, use smaller type, or error
}
Edge Cases
b == 0: Returns 1 (safe, product=0)
a == 0: Returns 1 (safe, product=0)
Overflow: e.g., SIZE_MAX * 2 -> 0
Note
Equivalent to SOCKET_SECURITY_CHECK_OVERFLOW_MUL macro for inline use.
Complexity\n O(1)
See also
SocketSecurity_safe_multiply() computes product or 0 on failure.
SocketSecurity_check_add() for addition validation.
SocketSecurity_check_size() for single size validation.
docs/SAFE_ARITHMETIC.md for secure coding practices.
SocketSecurity_check_size()
int SocketSecurity_check_size (size_t size) extern
Validate a size value for safe memory allocation or buffer operations.
Performs comprehensive validation of a size parameter before use in allocations, buffer creations, or size calculations. Checks include:
Non-zero (rejects zero-size as likely error)
Within global max allocation limit
Defense-in-depth: rejects sizes > SIZE_MAX/2 to catch overflows
Used internally by Arena, SocketBuf, and other modules; applications can call directly for custom validations.
Parameters
[in] size Proposed size in bytes to validate.
Returns
1 if size is safe (positive, within limits, no overflow risk), 0 otherwise.
Thread Safety\n Yes - pure function, no state.
Usage Example
size_t user_size = get_user_input_size(); // From untrusted source
if (!SocketSecurity_check_size(user_size)) {
    fprintf(stderr, "Invalid size %zu: exceeds security limits\n",
user_size); return -1;
}
// Safe to allocate
void *buf = malloc(user_size);
if (!buf) {
    perror("malloc");
    return -1;
}
// Use buf...
free(buf);
Validation Criteria
Check Condition Rationale
Non-zero size > 0 Avoid zero-alloc
bugs | | Within limit | size <= max_allocation | DoS protection | | Overflow defense | size <= SIZE_MAX/2 | Catch signed->unsigned casts |
Note
For performance-critical code, use SOCKET_SECURITY_VALID_SIZE macro inline.
Warning
Failing validation should trigger user-friendly errors, not silent clamps.
Complexity\n O(1) - simple comparisons
See also
SocketSecurity_get_max_allocation() to retrieve current limit.
SOCKET_SECURITY_VALID_SIZE() inline macro equivalent.
SocketSecurity_SizeExceeded for raising exceptions on failure.
SocketSecurity_check_multiply() for compound size checks.
SocketSecurity_get_arena_limits()
void SocketSecurity_get_arena_limits (size_t * max_alloc) extern
Query the maximum allocation size limit for arenas.
Returns the limit on single allocations from an Arena instance. This provides an additional layer of protection within arena-managed memory, complementing the global SOCKET_SECURITY_MAX_ALLOCATION.
Defined via ARENA_MAX_ALLOC_SIZE macro (defaults to SOCKET_SECURITY_MAX_ALLOCATION if undefined). Enforced in Arena_alloc and Arena_calloc to prevent large allocations within pooled memory.
Parameters
[out] max_alloc Maximum allowed allocation from arena in bytes (ARENA_MAX_ALLOC_SIZE), or NULL.
Thread Safety\n Yes - constant query.
Usage Example
size_t arena_max;
SocketSecurity_get_arena_limits(&arena_max);
Arena_T arena = Arena_new();
size_t large_alloc = arena_max + 1;
TRY {
    void *ptr = Arena_alloc(arena, large_alloc, __FILE__, __LINE__);
    // Unreachable - raises exception
} EXCEPT(Arena_Failed) {
    // Handle: allocation exceeded arena limit
    fprintf(stderr, "Arena alloc %zu > limit %zu\n", large_alloc,
arena_max); } FINALLY { Arena_dispose(&arena); } END_TRY;
Note
Arena limits apply per-allocation within an arena; total arena size limited by system memory and configuration.
Complexity\n O(1)
See also
SocketSecurity_get_max_allocation() for global allocation limit.
Arena_alloc() / Arena_calloc() which enforce this limit.
ARENA_MAX_ALLOC_SIZE macro for configuration.
Foundation Modules for memory management.
SocketSecurity_get_hpack_limits()
void SocketSecurity_get_hpack_limits (size_t * max_table) extern
Query HPACK dynamic table size limit for HTTP/2 header compression.
Returns the maximum size allowed for the dynamic header table in HPACK (HTTP/2 header compression). This limit prevents memory exhaustion attacks via maliciously crafted headers that force large table growth during decompression.
Enforced in SocketHPACK_Decoder during table updates. Default: 64KB. When SOCKET_HAS_HTTP=0, returns 0.
Parameters
[out] max_table Maximum dynamic table size in bytes (SOCKETHPACK_MAX_TABLE_SIZE), or NULL.
Thread Safety\n Yes.
Usage Example
size_t hpack_max_table;
SocketSecurity_get_hpack_limits(&hpack_max_table);
// Configure HTTP/2 connection with safe table size
SocketHTTP2_Config config;
SocketHTTP2_config_defaults(&config, HTTP2_CLIENT);
config.hpack_max_table_size = hpack_max_table; // Respect security limit
SocketHTTP2_Conn_T conn = SocketHTTP2_Conn_new(socket, &config, arena);
// Proceed with HTTP/2 handshake...
Note
HPACK table size affects compression efficiency vs memory usage tradeoff.
Warning
Large tables (>1MB) increase vulnerability to decompression bombs.
Complexity\n O(1)
See also
SocketHPACK_DecoderConfig for table configuration.
SocketHTTP2_Conn_new() which uses this limit.
SOCKETHPACK_MAX_TABLE_SIZE macro.
HTTP Modules for HTTP/2 details.
SocketSecurity_get_http_limits()
void SocketSecurity_get_http_limits (size_t * max_uri, size_t * max_header_size, size_t * max_headers, size_t * max_body) extern
Query specific HTTP protocol security limits.
Retrieves individual HTTP-related limits such as maximum URI length, header sizes, header count, and body payload size. These optional output parameters allow selective querying without populating the full SocketSecurityLimits structure.
Limits are enforced in SocketHTTP, SocketHTTPClient, and SocketHTTPServer modules to prevent buffer overflows and DoS attacks via malformed requests. NULL pointers are ignored, allowing partial queries.
When SOCKET_HAS_HTTP=0, returns 0 for all values (feature disabled).
Parameters
[out] max_uri Maximum URI length in bytes (SOCKETHTTP_MAX_URI_LEN), or NULL.
[out] max_header_size Maximum total headers size in bytes (SOCKETHTTP_MAX_HEADER_SIZE), or NULL.
[out] max_headers Maximum number of HTTP headers allowed (SOCKETHTTP_MAX_HEADERS), or NULL.
[out] max_body Maximum HTTP body size in bytes (SOCKET_SECURITY_MAX_BODY_SIZE), or NULL.
Thread Safety\n Yes - constant reads; no side effects.
Usage Example
size_t max_uri, max_body;
SocketSecurity_get_http_limits(&max_uri, NULL, NULL, &max_body);
// Validate incoming request URI
if (strlen(request_uri) > max_uri) {
    // Reject with 414 URI Too Long
    return send_error_response(client, 414);
}
// Check Content-Length header
const char *clen = SocketHTTP_Headers_get(headers, "Content-Length");
size_t body_size = clen ? atol(clen) : 0;
if (body_size > max_body) {
    // Reject with 413 Payload Too Large
    return send_error_response(client, 413);
}
HTTP Limits Table
Limit Default Enforced In Rationale
max_uri 8KB URI parsing Prevent
header injection | | max_header_size | 64KB | Header parsing | Buffer overflow protection | | max_headers | 100 | Header list | DoS via many small headers | | max_body | 100 MiB | Body reading | Large upload DoS prevention|
Note
These limits can be overridden in SocketHTTP.h via compile-time macros.
Warning
Disabling HTTP module sets limits to 0; always check SOCKET_HAS_HTTP.
Complexity\n O(1) - direct constant assignments
See also
SocketSecurity_get_limits() for all limits including HTTP.
SocketHTTP_Headers_add() which respects header limits.
SocketHTTP_URI_parse() which checks URI length.
HTTP Modules for full protocol Security Modules features.
docs/HTTP_SECURITY.md for HTTP-specific hardening guide.
SocketSecurity_get_limits()
void SocketSecurity_get_limits (SocketSecurityLimits * limits) extern
Retrieve all configured security limits into a structure for inspection.
This function populates a SocketSecurityLimits structure with the current security configuration limits from across the library. These limits include memory allocation caps, HTTP payload sizes, TLS parameters, rate limiting defaults, and timeouts. Limits are derived from compile-time constants and feature flags (e.g., SOCKET_HAS_TLS, SOCKET_HAS_HTTP).
Useful for runtime validation, logging security posture, or dynamic configuration checks in applications. No allocations or state changes occur. Edge cases: When optional modules (TLS, HTTP, WebSocket) are disabled at compile-time, corresponding limits are set to 0 or safe minimal values.
Parameters
[out] limits Pointer to a SocketSecurityLimits structure to populate. Must not be NULL; validated before use.
Exceptions
SocketSecurity_ValidationFailed If limits is NULL (input validation failure).
Thread Safety\n Yes - reads only compile-time constants; no shared state or
locks.
Usage Example
// Query security limits for logging or validation
SocketSecurityLimits limits;
TRY {
    SocketSecurity_get_limits(&limits);
    printf("Max allocation: %zu bytes\n", limits.max_allocation);
    printf("Max HTTP body: %zu bytes\n", limits.http_max_body_size);
    if (SocketSecurity_has_tls()) {
        printf("TLS cert chain depth: %zu\n",
limits.tls_max_cert_chain_depth);
    }
} EXCEPT(SocketSecurity_ValidationFailed) {
    fprintf(stderr, "Invalid limits pointer provided\n");
} END_TRY;
Limit Categories
The structure groups limits into categories for easy inspection:
Category Key Limits Purpose
Memory max_allocation, max_buffer_size DoS prevention via
size caps | | HTTP | http_max_body_size, http_max_headers| Payload and header validation | | HTTP/2 | http2_max_concurrent_streams | Stream multiplexing limits | | TLS | tls_max_cert_chain_depth | Certificate validation bounds | | Rate Limiting | ratelimit_conn_per_sec | Connection flood protection | | Timeouts | timeout_connect_ms | Prevent indefinite hangs |
Note
Limits reflect compile-time configuration via CMake options and macros; no runtime reconfiguration supported to maintain security guarantees.
Warning
Applications should respect these limits; exceeding them in custom code may lead to exceptions or undefined behavior in library modules.
Complexity\n O(1) - direct assignment of pre-defined constants
See also
SocketSecurityLimits for detailed field documentation and types.
SocketSecurity_get_max_allocation() for querying individual limits.
SocketSecurity_check_size() for validating user-provided sizes.
SocketSecurity_has_tls() to check feature availability.
docs/SECURITY_GUIDE.md for comprehensive Security Modules configuration.
SocketSecurity_get_max_allocation()
size_t SocketSecurity_get_max_allocation (void) extern
Query the maximum allowed size for single memory allocations.
Returns the compile-time configured limit on individual memory allocations (e.g., via malloc, Arena_alloc, SocketBuf_new). This cap prevents denial-of-service from oversized requests and memory exhaustion attacks.
Default value: 256 MiB (268435456 bytes). Overridable via -DSOCKET_SECURITY_MAX_ALLOCATION=
at compile time.
Used internally for validation in allocation hotspots; applications can use this for preemptive checks or logging. Edge case: Returns the limit even if overridden to 0 (disabled protection).
Returns
Maximum permitted allocation size in bytes.
Thread Safety\n Yes - returns compile-time constant; no side effects or locks.
Usage Example
// Pre-validate large buffer allocation
size_t max_alloc = SocketSecurity_get_max_allocation();
size_t buf_size = 100 * 1024 * 1024; // 100 MiB buffer
TRY {
    if (buf_size > max_alloc) {
        RAISE(SocketSecurity_SizeExceeded);
    }
    SocketBuf_T buf = SocketBuf_new(arena, buf_size);
    // Use buffer...
    SocketBuf_release(&buf);
} EXCEPT(SocketSecurity_SizeExceeded) {
    fprintf(stderr, "Buffer size %zu exceeds security limit %zu\n",
buf_size, max_alloc); } END_TRY;
Configuration
Macro Default Value Purpose
SOCKET_SECURITY_MAX_ALLOCATION 256 MiB Single allocation DoS
protection |
Note
Applies to all single allocations; multi-allocation structures (e.g., arenas) have separate aggregate limits.
Warning
Overriding to excessively large values (>1GB) may expose to memory exhaustion; use system ulimit for additional protection.
Complexity\n O(1) - simple constant return
See also
SocketSecurity_check_size() for comprehensive validation including zero-check.
SocketSecurity_SizeExceeded exception raised on violations.
Arena.h for arena-specific allocation with integrated checks.
SocketBuf.h for buffer creation limits.
SOCKET_SECURITY_MAX_ALLOCATION for macro definition and override.
SocketSecurity_get_ws_limits()
void SocketSecurity_get_ws_limits (size_t * max_frame, size_t * max_message) extern
Query WebSocket-specific security limits for frame and message sizes.
Retrieves limits on WebSocket frame and message sizes to mitigate DoS attacks from oversized payloads. Frames are individual WebSocket data units; messages may span multiple frames (e.g., fragmented text/binary messages).
Enforced in SocketWS module during frame parsing and message reassembly. When SOCKET_HAS_WEBSOCKET=0, returns 0 (disabled).
Parameters
[out] max_frame Maximum single WebSocket frame size in bytes (SOCKETWS_MAX_FRAME_SIZE), or NULL.
[out] max_message Maximum aggregated message size in bytes (SOCKETWS_MAX_MESSAGE_SIZE), or NULL.
Thread Safety\n Yes - constant reads only.
Usage Example
size_t max_frame, max_msg;
SocketSecurity_get_ws_limits(&max_frame, &max_msg);
// In WebSocket handler, before processing incoming frame
if (incoming_frame_size > max_frame) {
    // Close connection with protocol error (1002)
    SocketWS_close(conn, WS_STATUS_PROTOCOL_ERROR, "Oversized frame");
    return;
}
// Track message size across fragments
static size_t current_msg_size = 0;
current_msg_size += incoming_frame_size;
if (current_msg_size > max_msg) {
    // Close with message too big (1009)
    SocketWS_close(conn, WS_STATUS_MESSAGE_TOO_BIG, "Message exceeds
limit"); current_msg_size = 0; return;
}
WebSocket Limits
Limit Default Purpose
max_frame 16 MiB Single frame DoS protection
max_message 64 MiB Aggregated message safety
Note
Limits configurable via macros in SocketWS-private.h.
Warning
Large limits increase memory usage; tune based on application needs.
Complexity\n O(1)
See also
SocketSecurity_get_limits() for broader limits including WS.
SocketWS.h for WebSocket API and error codes.
Utilities for integration with rate limiting.
docs/WEBSOCKET_SECURITY.md for WebSocket hardening.
SocketSecurity_has_compression()
static int SocketSecurity_has_compression (void) inline static
Determine if HTTP/1.1 content compression/decompression is supported.
Checks if zlib, libbrotli, etc., were detected during build and compression feature enabled (CMake ENABLE_HTTP_COMPRESSION=ON). Supports gzip, deflate, brotli for HTTP Content-Encoding.
When disabled, compression headers ignored, no encode/decode APIs available. Reduces binary size and dependencies.
Returns
1 if compression enabled (SOCKETHTTP1_HAS_COMPRESSION=1), 0 otherwise.
Thread Safety\n Yes - constant.
Usage Example
if (SocketSecurity_has_compression()) {
    // Enable compression in HTTP server config
    SocketHTTPServer_set_compress_response(server, true);
    // Or client: request Accept-Encoding: gzip,deflate
} else {
    SOCKET_LOG_INFO_MSG("HTTP compression disabled; larger payloads
expected");
    // Disable compression-related features
}
Dependencies
Library Algorithms Supported CMake Detection
zlib gzip, deflate find_package(ZLIB)
libbrotli brotli find_package(Brotli)
Note
Only HTTP/1.1; HTTP/2 uses built-in HPACK compression.
Warning
Compressed data may amplify certain attacks; validate limits.
Complexity\n O(1)
See also
SocketSecurity_has_tls() for TLS feature check.
SOCKETHTTP1_HAS_COMPRESSION macro.
SocketHTTP1_config_defaults() compression config.
HTTP Modules for encoding details.
Definition at line 1549 of file SocketSecurity.h.
SocketSecurity_has_tls()
static int SocketSecurity_has_tls (void) inline static
Determine if the library was compiled with TLS support.
Returns whether OpenSSL/LibreSSL was detected and TLS features enabled during build (via CMake -DENABLE_TLS=ON). When false, all TLS-related code is excluded, headers not included, and functions stubbed or absent.
Applications use this to conditionally enable/disable TLS features or provide fallbacks.
Returns
1 if TLS enabled (SOCKET_HAS_TLS=1), 0 if disabled.
Thread Safety\n Yes - compile-time constant evaluation.
Usage Example
if (SocketSecurity_has_tls()) {
    // TLS available: configure secure connections
    SocketTLSContext_T ctx = SocketTLSContext_new_server(certs, key);
    SocketTLS_enable(sock, ctx);
} else {
    // Fallback to plain TCP
    SOCKET_LOG_WARN_MSG("TLS disabled at compile-time; using insecure
connections");
    // Proceed without TLS...
}
Build Configuration
CMake Option Effect Dependencies
ENABLE_TLS=ON Enables TLS modules OpenSSL/LibreSSL
ENABLE_TLS=OFF Disables TLS (smaller binary) None
Note
Defined as #if SOCKET_HAS_TLS in code paths.
Warning
When disabled, TLS functions unavailable; link errors if used.
Complexity\n O(1)
See also
SocketSecurity_has_compression() for compression feature check.
SOCKET_HAS_TLS macro definition.
Security Modules for TLS implementation.
CMakeLists.txt build instructions.
Definition at line 1493 of file SocketSecurity.h.
SocketSecurity_safe_add()
static size_t SocketSecurity_safe_add (size_t a, size_t b) inline static
Compute sum of two sizes with overflow protection (inline).
Inline safe addition for size_t values. Returns exact sum if no overflow, SIZE_MAX on overflow detection. Useful for buffer growth or offset calculations.
Check condition: overflow if a > SIZE_MAX - b. Does not validate individual sizes (use check_size separately).
Parameters
[in] a First size_t addend.
[in] b Second size_t addend.
Returns
a + b if safe, SIZE_MAX if overflow would occur.
Thread Safety\n Yes - pure inline arithmetic.
Usage Example
size_t buf_used = 4096;
size_t append_len = 1024;
size_t new_used = SocketSecurity_safe_add(buf_used, append_len);
if (new_used == SIZE_MAX) {
    // Overflow detected
    return ERROR_OVERFLOW;
}
// Check if still within limits
if (!SocketSecurity_check_size(new_used)) {
    return ERROR_TOO_LARGE;
}
// Safe to resize or append
// e.g., SocketBuf_reserve(buf, new_used);
Note
To distinguish valid SIZE_MAX sum from overflow, use check_add first.
Warning
SIZE_MAX may be valid in some contexts (e.g., unlimited buffers); validate.
Complexity\n O(1)
See also
SocketSecurity_check_add() for prior validation with optional result.
SocketSecurity_safe_multiply() for multiplication analog.
SOCKET_SECURITY_CHECK_OVERFLOW_ADD for check-only macro.
Definition at line 1304 of file SocketSecurity.h.
SocketSecurity_safe_multiply()
static size_t SocketSecurity_safe_multiply (size_t a, size_t b) inline static
Compute product of two sizes with overflow protection (inline).
Inline function for safe size_t multiplication. Returns exact product if safe, 0 on zero operands or detected overflow. Does not distinguish between zero input and overflow (use check_multiply for that).
Optimized for performance in hot paths; compiler may inline the checks.
Parameters
[in] a First size_t operand.
[in] b Second size_t operand.
Returns
a * b if safe and both non-zero, else 0 (overflow or zero input).
Thread Safety\n Yes - pure function, no state.
Usage Example
size_t rows = 100;
size_t cols = 100;
size_t matrix_size = SocketSecurity_safe_multiply(rows, cols);
if (matrix_size == 0) {
    // Overflow or zero: handle error
    return ERROR_BUFFER_TOO_LARGE;
}
// Also validate against allocation limit
if (!SocketSecurity_check_size(matrix_size)) {
    return ERROR_SECURITY_LIMIT;
}
double *matrix = calloc(matrix_size, sizeof(double)); // Safe now
Note
Returns 0 for zero inputs (mathematically correct, but check if needed).
Warning
Cannot distinguish overflow from zero; pair with check_multiply if required.
Complexity\n O(1)
See also
SocketSecurity_check_multiply() for separate validation and result storage.
SocketSecurity_safe_add() companion for addition.
SOCKET_SECURITY_CHECK_OVERFLOW_MUL macro for check-only inline.
Definition at line 1246 of file SocketSecurity.h.
SocketTimeout_deadline_ms()
static int64_t SocketTimeout_deadline_ms (int timeout_ms) inline static
Create deadline from timeout.
Parameters
timeout_ms Timeout in milliseconds (0 or negative = no deadline).
Returns
Absolute deadline in milliseconds, or 0 if no timeout.
Thread Safety\n Yes
Definition at line 2091 of file SocketUtil.h.
References SocketTimeout_now_ms().
SocketTimeout_elapsed_ms()
static int64_t SocketTimeout_elapsed_ms (int64_t start_ms) inline static
Calculate elapsed time since start.
Parameters
start_ms Start time from SocketTimeout_now_ms().
Returns
Elapsed milliseconds since start.
Thread Safety\n Yes
Definition at line 2182 of file SocketUtil.h.
References SocketTimeout_now_ms().
SocketTimeout_expired()
static int SocketTimeout_expired (int64_t deadline_ms) inline static
Check if deadline has passed.
Parameters
deadline_ms Deadline from SocketTimeout_deadline_ms() (0 = no deadline).
Returns
1 if expired, 0 if not expired or no deadline.
Thread Safety\n Yes
Definition at line 2127 of file SocketUtil.h.
References SocketTimeout_now_ms().
SocketTimeout_now_ms()
static int64_t SocketTimeout_now_ms (void) inline static
Get current monotonic time in milliseconds.
Returns
Current time in milliseconds from monotonic clock.
Thread Safety\n Yes
Definition at line 2076 of file SocketUtil.h.
Referenced by SocketTimeout_deadline_ms(), SocketTimeout_elapsed_ms(), SocketTimeout_expired(), and SocketTimeout_remaining_ms().
SocketTimeout_poll_timeout()
static int SocketTimeout_poll_timeout (int current_timeout_ms, int64_t deadline_ms) inline static
Adjust poll timeout to not exceed deadline.
Parameters
current_timeout_ms Current poll timeout (-1 = infinite).
deadline_ms Deadline from SocketTimeout_deadline_ms() (0 = no deadline).
Returns
Adjusted timeout for poll() (minimum of current and remaining).
Thread Safety\n Yes
Usage: Use as the timeout argument to poll() when you need to respect both a regular poll interval and an overall operation deadline.
Definition at line 2148 of file SocketUtil.h.
References SocketTimeout_remaining_ms().
SocketTimeout_remaining_ms()
static int64_t SocketTimeout_remaining_ms (int64_t deadline_ms) inline static
Calculate remaining time until deadline.
Parameters
deadline_ms Deadline from SocketTimeout_deadline_ms() (0 = no deadline).
Returns
Remaining milliseconds (0 if expired, -1 if no deadline).
Thread Safety\n Yes
Definition at line 2107 of file SocketUtil.h.
References SocketTimeout_now_ms().
Referenced by SocketTimeout_poll_timeout().
Variable Documentation
Arena_Failed
const Except_T Arena_Failed extern
Exception raised when arena allocation fails.
This exception is raised when:
Memory allocation (malloc) fails
Mutex initialization fails
Arena expansion fails due to system limits
See also
ERROR_HANDLING.md for exception handling patterns.
Assert_Failed
const Except_T Assert_Failed extern
Standard exception raised by failed assertions.
This base-level exception serves as the root for assertion failures and programming errors detected via assert() or manual RAISE(Assert_Failed). Indicates invariant violations, invalid states, or bugs that should never occur in production code under correct usage.
Purpose and usage:
Base type for module-specific assertion exceptions (e.type = &Assert_Failed)
Triggered automatically by standard assert() integration
In release builds (-DNDEBUG), assert() may be no-op, but manual raises persist
Handlers can catch Assert_Failed for generic bug reporting/dumps
In the library, used for:
Precondition/postcondition checks
Internal consistency assertions
API contract violations
Custom assertions: assert(condition && "Detailed failure message"); // Auto-raises with reason Or manual: RAISE(Assert_Failed); for no message
Hierarchy Example
// Base
extern const Except_T Assert_Failed;
// Module derives (conceptually)
const Except_T Arena_AssertFailed = { &Assert_Failed, "Arena internal
assertion failed" };
// In code
assert(arena != NULL && "Arena must be valid");
// If fails, raises Assert_Failed with runtime-generated reason including
message
Note
Compile with asserts enabled in debug; consider runtime checks in production.
assert() reason includes C string literal for diagnostics.
Warning
Not for recoverable runtime errors; use domain-specific exceptions.
Thread Safety\n Yes - const global variable.
See also
assert() standard macro integration.
RAISE(Assert_Failed) for manual assertion-like raises.
Module-specific exceptions deriving from this base.
docs/ERROR_HANDLING.md for assertion strategies vs runtime exceptions.
Core Foundation Modules for error handling infrastructure.
Except_stack
Except_Frame* Except_stack extern
Thread-local exception stack for TRY/EXCEPT/FINALLY blocks.
External thread-local variable serving as the head of a linked list of Except_Frame structures, representing the stack of active exception handling contexts for the current thread. Manipulated exclusively by exception macros (TRY pushes, END_TRY pops).
Implementation:
Declared with __thread (GCC/Clang) or __declspec(thread) (MSVC) for TLS
Points to top-most (innermost) frame; NULL when no active TRY blocks
Stack grows downward via frame->prev links
Unwinding via longjmp() doesn't require explicit pops (handled by macros)
Access patterns (internal):
TRY: Except_stack = new_frame; new_frame->prev = old_stack
RAISE/END_TRY: Traverse via prev for propagation if needed
RETURN: Manual pop via assignment to prev
Threading model:
Per-thread isolation: no synchronization needed between threads
Safe for concurrent TRY blocks in different threads
Not shared; multi-threaded apps have independent stacks
Debugging/Inspection:
Can query depth or top frame for diagnostics (advanced, not recommended)
Stack overflow possible with excessive nesting (monitor via valgrind/ASan)
Usage Notes (Indirect via Macros)
// No direct access; example macro usage affecting stack
void threaded_example() {
  TRY {  // Pushes frame to this thread's Except_stack
    shared_resource_op();  // Other thread unaffected
  } END_TRY;  // Pops frame
}
// In multi-threaded context
// Thread A: own stack with frames
// Thread B: independent stack
Note
Users never access directly; macros ensure correctness.
Initial value NULL; indicates no active contexts.
Warning
Direct modification corrupts handling; undefined behavior.
Thread Safety\n Yes - TLS ensures isolation; read/write safe within thread.
See also
Except_Frame for node structure in the stack.
TRY for push operation.
END_TRY/RETURN for pop operations.
RAISE for frame update during raise.
docs/ERROR_HANDLING.md for threading considerations and stack management.
SocketCrypto_Failed
const Except_T SocketCrypto_Failed extern
General exception for cryptographic operation failures.
Thrown when cryptographic operations fail due to:
Underlying library errors (e.g., OpenSSL API failures)
Invalid parameters (null pointers, out-of-bounds lengths)
Resource constraints (buffer too small, allocation limits)
Missing crypto support (SOCKET_HAS_TLS == 0)
See also
Except_T for C exception handling mechanism.
SocketCrypto functions that may throw this exception.
SocketSecurity_SizeExceeded
const Except_T SocketSecurity_SizeExceeded extern
Exception indicating security limit violation on size/ allocation.
Thrown by library modules when a requested size exceeds configured security limits or when size computations detect potential overflow/invalidity.
Common triggers:
Arena_alloc() / SocketBuf_new() with size > max_allocation
Buffer appends exceeding capacity limits
Detected integer overflow in safe arithmetic wrappers
Applications should catch and handle by reducing request size, logging, or rejecting client input (e.g., 413/400 responses).
See also
SocketSecurity_SizeExceeded for exception instance.
Handling Example
TRY {
    SocketBuf_T buf = SocketBuf_new(arena, too_large_size);
} EXCEPT(SocketSecurity_SizeExceeded) {
    SOCKET_LOG_ERROR_MSG("Size %zu exceeds max %zu; rejecting request",
                         too_large_size,
SocketSecurity_get_max_allocation());
    // Send error response to client
    return send_http_error(client, 413, "Payload Too Large");
} END_TRY;
Note
Message includes context like "Allocation exceeds security limits".
See also
SocketSecurity_check_size() to preemptively validate.
SocketSecurity_get_max_allocation() for current limit.
Except.h for TRY/EXCEPT/FINALLY usage.
docs/ERROR_HANDLING.md for patterns.
SocketSecurity_ValidationFailed
const Except_T SocketSecurity_ValidationFailed extern
Exception for general input validation failures in security contexts.
Indicates invalid or malicious input detected during security-related validations, such as NULL pointers in required params, malformed protocol data, or invalid characters/formats.
Examples:
SocketSecurity_get_limits(NULL) - invalid param
UTF-8 validation fails in headers/URIs
Protocol-specific checks (e.g., invalid HTTP methods)
Differentiates from SizeExceeded (quantitative limits) for better error handling.
See also
SocketSecurity_ValidationFailed instance.
Handling Example
SocketSecurityLimits *lim = NULL; // Bad input
TRY {
    SocketSecurity_get_limits(lim);
} EXCEPT(SocketSecurity_ValidationFailed) {
    fprintf(stderr, "%s\n", Except_message(Except_stack)); // "Input
validation failed"
    // Validate pointers before calls
    lim = &local_limits;
    SocketSecurity_get_limits(lim); // Now safe
} END_TRY;
Note
Generic message; specific raisers may append details via RAISE_FMT.
See also
SocketSecurity_check_size() / other validators to prevent.
SocketUTF8_validate() for string validations.
Except_stack for current exception details.
docs/ERROR_HANDLING.md exception best practices.