HTTP Client Module
HTTP Client Module
HTTP Modules
High-level HTTP client library supporting HTTP/1.1, HTTP/2, connection pooling, async I/O, authentication, cookies, redirects, compression, and proxy support.
Modules
Connection and Resource Limits
Limits on redirects, connections, and retries for safety and performance.
Retry Configuration Constants
Parameters for automatic retry logic on transient failures.
Cookie Configuration Constants
Limits and buffer sizes for HTTP client cookie handling and jar management.
Authentication Buffer Constants
Internal buffer sizes for HTTP authentication header generation and computation.
Request/Response Buffer Constants
Buffer sizes for HTTP request serialization, response reading, and headers.
Content-Encoding Flags
Bit flags indicating supported Content-Encoding methods for HTTP client.
Files
file SocketHTTPClient-config.h
Configuration constants for HTTP client with compile-time override support.
file SocketHTTPClient.h
Public API for the HTTP client module, including types, functions, and configuration.
Data Structures
struct SocketHTTPClient_Auth
Authentication credentials structure.
struct SocketHTTPClient_Config
HTTP client configuration structure.
struct SocketHTTPClient_Response
HTTP response structure returned by client functions.
struct SocketHTTPClient_Cookie
Cookie attributes structure (RFC 6265).
struct SocketHTTPClient_PoolStats
Connection pool statistics snapshot.
Macros
#define HTTPCLIENT_ERROR_BUFSIZE 256
Size of internal buffer for formatting HTTP client error messages.Used in SocketHTTPClient_error_format() and related functions to prevent buffer overflows.
#define HTTPCLIENT_POOL_HASH_SIZE 127
Default initial hash table size for HTTP client connection pool.Prime number 127 chosen for good distribution with low load factor. Automatically resizes to larger table when exceeding HTTPCLIENT_POOL_LARGE_THRESHOLD connections.
#define HTTPCLIENT_POOL_LARGE_HASH_SIZE 251
Larger hash table size for HTTP client connection pools exceeding 100 connections.
#define HTTPCLIENT_POOL_LARGE_THRESHOLD 100
Threshold for switching to larger hash table in connection pool.
#define HTTPCLIENT_IO_BUFFER_SIZE 8192
I/O buffer size for pooled connections in HTTP client.
#define HTTPCLIENT_DEFAULT_CONNECT_TIMEOUT_MS 30000
Default timeout for establishing new connections (30 seconds).Applies to TCP connect, TLS handshake, and proxy connections. Override via SocketHTTPClient_Config.connect_timeout_ms or per-request.
#define HTTPCLIENT_DEFAULT_REQUEST_TIMEOUT_MS 60000
Default timeout for full HTTP request completion (60 seconds).
#define HTTPCLIENT_DEFAULT_DNS_TIMEOUT_MS 10000
Default timeout for DNS resolution (10 seconds).
#define HTTPCLIENT_DEFAULT_IDLE_TIMEOUT_MS 60000
Default idle timeout for pooled connections (60 seconds).
#define HTTPCLIENT_DEFAULT_MAX_REDIRECTS 10
Default maximum number of redirects to follow (10).
#define HTTPCLIENT_DEFAULT_MAX_CONNS_PER_HOST 6
Default maximum concurrent connections per host (6).
#define HTTPCLIENT_DEFAULT_MAX_TOTAL_CONNS 100
Default total maximum connections across all hosts (100).
#define HTTPCLIENT_DEFAULT_MAX_RETRIES 3
Default maximum number of retry attempts for transient failures (3).
#define HTTPCLIENT_DEFAULT_RETRY_INITIAL_DELAY_MS 100
Default initial backoff delay for retries (100ms).
#define HTTPCLIENT_DEFAULT_RETRY_MAX_DELAY_MS 10000
Default maximum backoff delay between retries (10 seconds).
#define HTTPCLIENT_DEFAULT_RETRY_ON_CONNECT 1
Default flag to retry on connection establishment errors (1 = enabled).
#define HTTPCLIENT_DEFAULT_RETRY_ON_TIMEOUT 1
Default flag to retry on request timeouts (1 = enabled).
#define HTTPCLIENT_DEFAULT_MAX_RESPONSE_SIZE (10ULL * 1024 * 1024) /* 10MB default to prevent DoS */
Default maximum size for HTTP response bodies (10MB).
#define HTTPCLIENT_AUTH_CREDENTIALS_SIZE 512
Buffer size for Basic auth credentials string (username:password, 512 bytes).
#define HTTPCLIENT_DIGEST_A_BUFFER_SIZE 512
Buffer size for Digest auth A1/A2 intermediate hashes (512 bytes).
#define HTTPCLIENT_DIGEST_RESPONSE_SIZE 256
Buffer size for Digest auth response value (256 bytes).
#define HTTPCLIENT_DIGEST_CNONCE_SIZE 16
Size of client nonce (cnonce) in bytes for Digest auth (16 bytes random).
#define HTTPCLIENT_DIGEST_CNONCE_HEX_SIZE 33
Size of hex-encoded client nonce string for Digest auth headers (33 bytes).
#define HTTPCLIENT_DIGEST_NC_SIZE 16
Buffer size for Digest auth nonce-count (nc) hex string (16 bytes).
#define HTTPCLIENT_REQUEST_BUFFER_SIZE 8192
Buffer size for serializing HTTP request lines and headers (8192 bytes).
#define HTTPCLIENT_BODY_CHUNK_SIZE 4096
Chunk size for reading response bodies incrementally (4096 bytes).
#define HTTPCLIENT_HOST_HEADER_SIZE 256
Buffer size for generating Host header (256 bytes).
#define HTTPCLIENT_COOKIE_HEADER_SIZE 4096
Buffer size for serializing Cookie header in outgoing requests (4096 bytes).
#define HTTPCLIENT_AUTH_HEADER_SIZE 512
Buffer size for standard Authorization headers (Basic/Digest/Bearer, 512 bytes).
#define HTTPCLIENT_AUTH_HEADER_LARGE_SIZE 1024
Larger buffer for complex Authorization headers, e.g., Digest with long nonces (1024 bytes).
#define HTTPCLIENT_URI_BUFFER_SIZE 512
Buffer size for URI string in Digest auth calculations (512 bytes).
#define HTTPCLIENT_MAX_SET_COOKIES 16
Maximum Set-Cookie headers processed per HTTP response (16).
#define HTTPCLIENT_ACCEPT_ENCODING_SIZE 64
Buffer size for constructing Accept-Encoding request header (64 bytes).
#define HTTPCLIENT_CONTENT_LENGTH_SIZE 32
Buffer size for Content-Length header value string (32 bytes).
#define HTTPCLIENT_RETRY_JITTER_FACTOR 0.25
Default retry backoff parameters: jitter factor (0.25) and multiplier (2.0).
#define HTTPCLIENT_DEFAULT_USER_AGENT "SocketHTTPClient/1.0"
Default User-Agent header string sent in requests.
#define HTTPCLIENT_ENCODING_IDENTITY 0x00
Identity (no compression) encoding flag.
#define HTTPCLIENT_ENCODING_GZIP 0x01
GZIP compression encoding flag.
#define HTTPCLIENT_ENCODING_DEFLATE 0x02
DEFLATE compression encoding flag.
#define HTTPCLIENT_ENCODING_BR 0x04
Brotli compression encoding flag.
Typedefs
typedef void(* SocketHTTPClient_Callback) (SocketHTTPClient_AsyncRequest_T req, SocketHTTPClient_Response *response, SocketHTTPClient_Error error, void *userdata)
Enumerations
enum SocketHTTPClient_Error {
HTTPCLIENT_OK = 0 ,
HTTPCLIENT_ERROR_DNS ,
HTTPCLIENT_ERROR_CONNECT ,
HTTPCLIENT_ERROR_TLS ,
HTTPCLIENT_ERROR_TIMEOUT ,
HTTPCLIENT_ERROR_PROTOCOL ,
HTTPCLIENT_ERROR_TOO_MANY_REDIRECTS ,
HTTPCLIENT_ERROR_RESPONSE_TOO_LARGE ,
HTTPCLIENT_ERROR_CANCELLED ,
HTTPCLIENT_ERROR_OUT_OF_MEMORY ,
HTTPCLIENT_ERROR_LIMIT_EXCEEDED
}
Error codes for HTTP client operations.
enum SocketHTTPClient_AuthType {
HTTP_AUTH_NONE = 0 ,
HTTP_AUTH_BASIC ,
HTTP_AUTH_DIGEST ,
HTTP_AUTH_BEARER
}
Authentication scheme types supported by the HTTP client.
enum SocketHTTPClient_SameSite {
COOKIE_SAMESITE_NONE = 0 ,
COOKIE_SAMESITE_LAX = 1 ,
COOKIE_SAMESITE_STRICT = 2
}
Cookie SameSite attribute values (RFC 6265bis draft).
Functions
int SocketHTTPClient_error_is_retryable (SocketHTTPClient_Error error)
Check if error code is retryable.
void SocketHTTPClient_config_defaults (SocketHTTPClient_Config *config)
Initialize SocketHTTPClient_Config structure with production-safe defaults.
SocketHTTPClient_T SocketHTTPClient_new (const SocketHTTPClient_Config *config)
Create new HTTP client instance.
void SocketHTTPClient_free (SocketHTTPClient_T *client)
Destroy HTTP client and release all resources.
int SocketHTTPClient_get (SocketHTTPClient_T client, const char *url, SocketHTTPClient_Response *response)
Perform synchronous GET request.
int SocketHTTPClient_head (SocketHTTPClient_T client, const char *url, SocketHTTPClient_Response *response)
Perform synchronous HEAD request.
int SocketHTTPClient_post (SocketHTTPClient_T client, const char *url, const char *content_type, const void *body, size_t body_len, SocketHTTPClient_Response *response)
Perform synchronous POST request.
int SocketHTTPClient_put (SocketHTTPClient_T client, const char *url, const char *content_type, const void *body, size_t body_len, SocketHTTPClient_Response *response)
Perform synchronous PUT request.
int SocketHTTPClient_delete (SocketHTTPClient_T client, const char *url, SocketHTTPClient_Response *response)
Perform synchronous DELETE request.
void SocketHTTPClient_Response_free (SocketHTTPClient_Response *response)
Free response resources.
SocketHTTPClient_Request_T SocketHTTPClient_Request_new (SocketHTTPClient_T client, SocketHTTP_Method method, const char *url)
Create request builder.
void SocketHTTPClient_Request_free (SocketHTTPClient_Request_T *req)
Free request builder and release resources.
int SocketHTTPClient_Request_header (SocketHTTPClient_Request_T req, const char *name, const char *value)
Add header.
int SocketHTTPClient_Request_body (SocketHTTPClient_Request_T req, const void *data, size_t len)
Set request body.
int SocketHTTPClient_Request_body_stream (SocketHTTPClient_Request_T req, ssize_t(*read_cb)(void *buf, size_t len, void *userdata), void *userdata)
Set streaming body.
void SocketHTTPClient_Request_timeout (SocketHTTPClient_Request_T req, int ms)
Set per-request timeout.
void SocketHTTPClient_Request_auth (SocketHTTPClient_Request_T req, const SocketHTTPClient_Auth *auth)
Set per-request authentication.
int SocketHTTPClient_Request_execute (SocketHTTPClient_Request_T req, SocketHTTPClient_Response *response)
Execute request.
SocketHTTPClient_AsyncRequest_T SocketHTTPClient_get_async (SocketHTTPClient_T client, const char *url, SocketHTTPClient_Callback callback, void *userdata)
Start async GET.
SocketHTTPClient_AsyncRequest_T SocketHTTPClient_post_async (SocketHTTPClient_T client, const char *url, const char *content_type, const void *body, size_t body_len, SocketHTTPClient_Callback callback, void *userdata)
Start async POST.
SocketHTTPClient_AsyncRequest_T SocketHTTPClient_Request_async (SocketHTTPClient_Request_T req, SocketHTTPClient_Callback callback, void *userdata)
Start async custom request.
void SocketHTTPClient_AsyncRequest_cancel (SocketHTTPClient_AsyncRequest_T req)
Cancel async request.
int SocketHTTPClient_process (SocketHTTPClient_T client, int timeout_ms)
Process async requests.
SocketHTTPClient_CookieJar_T SocketHTTPClient_CookieJar_new (void)
Create cookie jar.
void SocketHTTPClient_CookieJar_free (SocketHTTPClient_CookieJar_T *jar)
Free cookie jar and all stored cookies.
void SocketHTTPClient_set_cookie_jar (SocketHTTPClient_T client, SocketHTTPClient_CookieJar_T jar)
Associate jar with client.
SocketHTTPClient_CookieJar_T SocketHTTPClient_get_cookie_jar (SocketHTTPClient_T client)
Get associated cookie jar.
int SocketHTTPClient_CookieJar_set (SocketHTTPClient_CookieJar_T jar, const SocketHTTPClient_Cookie *cookie)
Set cookie.
Variables
const Except_T SocketHTTPClient_Failed
General client failure.
const Except_T SocketHTTPClient_DNSFailed
DNS resolution failure.
const Except_T SocketHTTPClient_ConnectFailed
TCP connection failure.
const Except_T SocketHTTPClient_TLSFailed
TLS/SSL handshake or I/O failure.
const Except_T SocketHTTPClient_Timeout
Request timeout exceeded.
const Except_T SocketHTTPClient_ProtocolError
HTTP protocol error.
const Except_T SocketHTTPClient_TooManyRedirects
Redirect limit exceeded.
const Except_T SocketHTTPClient_ResponseTooLarge
Response body exceeds limit.
SocketHTTPClient_AuthType SocketHTTPClient_Auth::type
const char * SocketHTTPClient_Auth::username
const char * SocketHTTPClient_Auth::password
const char * SocketHTTPClient_Auth::token
const char * SocketHTTPClient_Auth::realm
SocketHTTP_Version SocketHTTPClient_Config::max_version
int SocketHTTPClient_Config::allow_http2_cleartext
int SocketHTTPClient_Config::enable_connection_pool
size_t SocketHTTPClient_Config::max_connections_per_host
size_t SocketHTTPClient_Config::max_total_connections
int SocketHTTPClient_Config::idle_timeout_ms
int SocketHTTPClient_Config::max_connection_age_ms
int SocketHTTPClient_Config::acquire_timeout_ms
int SocketHTTPClient_Config::connect_timeout_ms
int SocketHTTPClient_Config::request_timeout_ms
int SocketHTTPClient_Config::dns_timeout_ms
int SocketHTTPClient_Config::follow_redirects
int SocketHTTPClient_Config::redirect_on_post
int SocketHTTPClient_Config::accept_encoding
int SocketHTTPClient_Config::auto_decompress
SocketTLSContext_T SocketHTTPClient_Config::tls_context
int SocketHTTPClient_Config::verify_ssl
SocketProxy_Config * SocketHTTPClient_Config::proxy
const char * SocketHTTPClient_Config::user_agent
size_t SocketHTTPClient_Config::max_response_size
int SocketHTTPClient_Config::enable_retry
int SocketHTTPClient_Config::max_retries
int SocketHTTPClient_Config::retry_initial_delay_ms
int SocketHTTPClient_Config::retry_max_delay_ms
int SocketHTTPClient_Config::retry_on_connection_error
int SocketHTTPClient_Config::retry_on_timeout
int SocketHTTPClient_Config::retry_on_5xx
int SocketHTTPClient_Config::enforce_samesite
int SocketHTTPClient_Response::status_code
SocketHTTP_Headers_T SocketHTTPClient_Response::headers
void * SocketHTTPClient_Response::body
size_t SocketHTTPClient_Response::body_len
SocketHTTP_Version SocketHTTPClient_Response::version
Arena_T SocketHTTPClient_Response::arena
const char * SocketHTTPClient_Cookie::name
const char * SocketHTTPClient_Cookie::value
const char * SocketHTTPClient_Cookie::domain
const char * SocketHTTPClient_Cookie::path
time_t SocketHTTPClient_Cookie::expires
int SocketHTTPClient_Cookie::secure
int SocketHTTPClient_Cookie::http_only
SocketHTTPClient_SameSite SocketHTTPClient_Cookie::same_site
size_t SocketHTTPClient_PoolStats::active_connections
size_t SocketHTTPClient_PoolStats::idle_connections
size_t SocketHTTPClient_PoolStats::total_requests
size_t SocketHTTPClient_PoolStats::reused_connections
size_t SocketHTTPClient_PoolStats::connections_created
size_t SocketHTTPClient_PoolStats::connections_failed
size_t SocketHTTPClient_PoolStats::connections_timed_out
size_t SocketHTTPClient_PoolStats::stale_connections_removed
size_t SocketHTTPClient_PoolStats::pool_exhausted_waits
Cookie name
Get cookie by name
Parameters
jar Cookie jar
domain Domain to match
path Path to match
Returns
Cookie or NULL if not found
const SocketHTTPClient_Cookie * SocketHTTPClient_CookieJar_get (SocketHTTPClient_CookieJar_T jar, const char *domain, const char *path, const char *name)
Clear all cookies.
void SocketHTTPClient_CookieJar_clear (SocketHTTPClient_CookieJar_T jar)
Clear all cookies.
void SocketHTTPClient_CookieJar_clear_expired (SocketHTTPClient_CookieJar_T jar)
Clear expired cookies.
int SocketHTTPClient_CookieJar_load (SocketHTTPClient_CookieJar_T jar, const char *filename)
Load cookies from file.
int SocketHTTPClient_CookieJar_save (SocketHTTPClient_CookieJar_T jar, const char *filename)
Save cookies to file.
void SocketHTTPClient_set_auth (SocketHTTPClient_T client, const SocketHTTPClient_Auth *auth)
Set default authentication credentials for all requests.
void SocketHTTPClient_pool_stats (SocketHTTPClient_T client, SocketHTTPClient_PoolStats *stats)
Get pool statistics.
void SocketHTTPClient_pool_clear (SocketHTTPClient_T client)
Close and clear all connections in the pool.
SocketHTTPClient_Error SocketHTTPClient_last_error (SocketHTTPClient_T client)
Get last error code.
const char * SocketHTTPClient_error_string (SocketHTTPClient_Error error)
Get error description.
Detailed Description
High-level HTTP client library supporting HTTP/1.1, HTTP/2, connection pooling, async I/O, authentication, cookies, redirects, compression, and proxy support.
The HTTP client module offers a production-ready implementation for making HTTP requests with modern features, security, and performance optimizations.
Key Features:
Synchronous and asynchronous request execution
Automatic protocol negotiation (HTTP/2 via ALPN prioritized)
Efficient connection pooling with per-host limits, idle timeouts, and reuse statistics
RFC 6265-compliant cookie management including SameSite attributes
Support for authentication schemes: Basic (RFC 7617), Digest (RFC 7616), Bearer tokens (RFC 6750)
Automatic compression handling (gzip, deflate, brotli) with decompression
Intelligent redirect following with loop detection and method preservation
Proxy configuration and Happy Eyeballs for dual-stack IPv6 preference
Configurable timeouts, retries, and error recovery for resilience
Comprehensive logging, metrics, and pool management APIs
Components:
SocketHTTPClient_T: Core client instance managing pool and configuration
SocketHTTPClient_Config: Detailed runtime configuration options
SocketHTTPClient_Request_T: Builder pattern for custom requests (sync/async)
SocketHTTPClient_AsyncRequest_T: Handle for monitoring/canceling async operations
SocketHTTPClient_Response: Structured access to response data and metadata
SocketHTTPClient_CookieJar_T: Secure cookie storage, loading, and saving
SocketHTTPClient_Auth: Configuration for authentication credentials
SocketHTTPClient_Error: Enumerated errors with retryability classification
SocketHTTPClient_PoolStats: Connection pool performance metrics
Dependencies and Integration:
HTTP Protocol Modules for parsing, serialization, and HPACK
Connection Management for advanced pooling and reconnection
Security Modules for TLS, certificate verification, and SYN protection
Async I/O and Event System for non-blocking workflows
DNS Resolution for efficient hostname lookup
Utilities for rate limiting, retry policies, and metrics
Foundation for arena allocation and exception handling
Security Considerations:
Strict certificate validation and hostname matching (configurable bypass for testing)
Protection against memory exhaustion via response size limits and header validation
Secure handling of sensitive data (cleartext credentials warning; recommend secure storage)
Enforcement of cookie security flags (Secure, HttpOnly, SameSite)
Rejection of malformed responses to mitigate injection and smuggling attacks
Configurable limits on redirects, retries, and connection counts to prevent abuse
Thread Safety:
Client instances are NOT thread-safe; design for one instance per thread or use mutexes
Pure functions (e.g., config_defaults, error_is_retryable) are thread-safe
Cookie jar is thread-safe with internal locking
Platform Support:
POSIX-compliant (Linux, BSD, macOS)
Requires pthread for internal threading (DNS workers, timers)
Optional TLS via CMake -DENABLE_TLS=ON (OpenSSL or LibreSSL)
Poll backends auto-detected (epoll/kqueue/poll)
Examples:
Documentation:
See also
docs/HTTP_CLIENT_GUIDE.md for tutorials and patterns
docs/SECURITY_GUIDE.md for authentication and TLS best practices
Cookie Configuration Constants
Content Encoding Configuration
Data Structure Documentation
SocketHTTPClient_Auth
struct SocketHTTPClient_Auth
Authentication credentials structure.
Configure authentication for requests using this structure. Pass to SocketHTTPClient_set_auth() or SocketHTTPClient_Request_auth().
Fields:
type: Authentication scheme (Basic, Digest, Bearer)
username/password: For Basic and Digest
token: For Bearer authentication
realm: Optional realm filter for Digest (matches server challenge)
Note
Credentials are stored in cleartext internally. Use secure storage practices.
Basic auth sends credentials with every request; prefer over HTTPS only.
See also
SocketHTTPClient_AuthType for scheme details.
docs/SECURITY_GUIDE.md for best practices.
Definition at line 433 of file SocketHTTPClient.h.
Data Fields
const char * password
For Basic, Digest
const char * realm
Optional realm filter
const char * token
For Bearer
SocketHTTPClient_AuthType type
const char * username
For Basic, Digest
SocketHTTPClient_Config
struct SocketHTTPClient_Config
HTTP client configuration structure.
Customize client behavior via this structure. Pass to SocketHTTPClient_new(). Use SocketHTTPClient_config_defaults() to initialize with sensible defaults.
Key sections:
Protocol: HTTP version negotiation and HTTP/2 settings
Connection pooling: Reuse connections for performance
Timeouts: Prevent hanging requests/connections
Redirects: Automatic following with limits
Compression: Accept and auto-decompress encoded responses
TLS: Secure connections (requires SOCKET_HAS_TLS)
Proxy: Forward requests through proxy
Limits: Prevent resource exhaustion
Retry: Automatic retries for transient failures (experimental)
See also
SocketHTTPClient_config_defaults() for initialization.
SocketHTTP_Version for protocol versions.
SocketTLSContext_T for TLS configuration.
Note
Changes take effect on next SocketHTTPClient_new(). Existing clients unaffected.
Thread Safety\n Yes - structure is plain data, no methods.
Definition at line 486 of file SocketHTTPClient.h.
Data Fields
int accept_encoding
Bitmask: GZIP | DEFLATE | BR
int acquire_timeout_ms
Timeout waiting for pool slot
int allow_http2_cleartext
Allow h2c upgrade (default: 0)
int auto_decompress
Auto-decompress responses (default: 1)
int connect_timeout_ms
Connection timeout
int dns_timeout_ms
DNS resolution timeout
int enable_connection_pool
Enable pooling (default: 1)
int enable_retry
Enable automatic retry (default: 0)
int enforce_samesite
Security configuration Enforce SameSite attribute (default: 1)
int follow_redirects
Max redirects (0 = disabled)
int idle_timeout_ms
Idle connection timeout
int max_connection_age_ms
Max connection age (0 = unlimited)
size_t max_connections_per_host
Per-host limit (default: 6)
size_t max_response_size
Max response body (0 = unlimited)
int max_retries
Max retry attempts (default: 3)
size_t max_total_connections
Total limit (default: 100)
SocketHTTP_Version max_version
Max HTTP version (default: HTTP/2)
SocketProxy_Config * proxy
Default proxy (NULL for none)
int redirect_on_post
Follow redirects for POST (default: 0)
int request_timeout_ms
Request timeout
int retry_initial_delay_ms
Initial backoff delay (default: 100ms)
int retry_max_delay_ms
Max backoff delay (default: 10s)
int retry_on_5xx
Retry on 5xx responses (default: 0)
int retry_on_connection_error
Retry on connect failures (default: 1)
int retry_on_timeout
Retry on timeouts (default: 1)
SocketTLSContext_T tls_context
Custom TLS context (NULL for default)
const char * user_agent
User-Agent header
int verify_ssl
Verify certificates (default: 1)
SocketHTTPClient_Response
struct SocketHTTPClient_Response
HTTP response structure returned by client functions.
Contains status, headers, body, and metadata from server response. Caller owns the response and must call SocketHTTPClient_Response_free() to release resources (arena, headers, body).
Fields:
status_code: HTTP status (200, 404, etc.)
headers: Parsed headers (SocketHTTP_Headers_T)
body: Response body data (may be NULL for HEAD or empty)
body_len: Length of body (0 if no body)
version: Negotiated HTTP version
arena: Arena used for allocation (dispose via Response_free)
Note
Body is allocated from response->arena. Do not free separately.
For large responses, consider streaming APIs to avoid memory usage.
See also
SocketHTTPClient_get() for usage example.
SocketHTTPClient_Response_free() for cleanup.
Definition at line 601 of file SocketHTTPClient.h.
Data Fields
Arena_T arena
For cleanup - caller must dispose
void * body
size_t body_len
SocketHTTP_Headers_T headers
int status_code
SocketHTTP_Version version
SocketHTTPClient_Cookie
struct SocketHTTPClient_Cookie
Cookie attributes structure (RFC 6265).
Represents a single HTTP cookie with attributes for storage and transmission. Used for setting cookies via CookieJar_set() or parsing from Set-Cookie headers.
Key attributes:
name/value: Cookie name-value pair
domain/path: Scope for matching requests
expires: Expiration time (0 = session cookie)
secure: Transmit only over HTTPS
http_only: Prevent JavaScript access (XSS protection)
same_site: Cross-site request policy
Note
Fields are const char* pointers owned by caller or arena.
See also
SocketHTTPClient_CookieJar for management.
docs/SECURITY_GUIDE.md for SameSite and Security Modules considerations.
Definition at line 1121 of file SocketHTTPClient.h.
Data Fields
const char * domain
time_t expires
int http_only
const char * name
const char * path
SocketHTTPClient_SameSite same_site
int secure
const char * value
SocketHTTPClient_PoolStats
struct SocketHTTPClient_PoolStats
Connection pool statistics snapshot.
Provides metrics on pool usage, efficiency, and health. Retrieved via SocketHTTPClient_pool_stats().
Metrics include:
Connection counts (active/idle)
Request/reuse counters for performance
Failure counters for debugging
See also
SocketHTTPClient_pool_stats() to populate.
SocketHTTPClient_Config for pool configuration.
Definition at line 1283 of file SocketHTTPClient.h.
Data Fields
size_t active_connections
Connections currently in use
size_t connections_created
Total connections created
size_t connections_failed
Connection attempts that failed
size_t connections_timed_out
Connections that timed out waiting
size_t idle_connections
Connections available for reuse
size_t pool_exhausted_waits
Times we waited for pool slot
size_t reused_connections
Times a pooled connection was reused
size_t stale_connections_removed
Stale/dead connections cleaned up
size_t total_requests
Total requests made
Macro Definition Documentation
HTTPCLIENT_ACCEPT_ENCODING_SIZE
#define HTTPCLIENT_ACCEPT_ENCODING_SIZE 64
Buffer size for constructing Accept-Encoding request header (64 bytes).
Builds "Accept-Encoding: gzip, deflate, br" based on config flags. Small size sufficient for standard encodings; extensible.
See also
Content-Encoding Flags: GZIP, DEFLATE, BR.
SocketHTTPClient_Config::accept_encoding bitmask.
RFC 9110 Content-Encoding and Accept-Encoding.
Definition at line 1073 of file SocketHTTPClient-config.h.
HTTPCLIENT_AUTH_CREDENTIALS_SIZE
#define HTTPCLIENT_AUTH_CREDENTIALS_SIZE 512
Buffer size for Basic auth credentials string (username:password, 512 bytes).
Temporary buffer for concatenating username:password before Base64 encoding in Basic auth. 512 bytes accommodates long usernames/passwords with margin; prevents overflows. Used in SocketHTTPClient_Auth for header generation.
See also
SocketHTTPClient_Auth::username and ::password fields.
HTTPCLIENT_AUTH_HEADER_SIZE encoded header buffer.
RFC 7617 Basic Authentication scheme.
Definition at line 818 of file SocketHTTPClient-config.h.
HTTPCLIENT_AUTH_HEADER_LARGE_SIZE
#define HTTPCLIENT_AUTH_HEADER_LARGE_SIZE 1024
Larger buffer for complex Authorization headers, e.g., Digest with long nonces (1024 bytes).
Extended size for cases where standard buffer insufficient, like verbose Digest params or long bearer tokens. Fallback or realloc if needed. Used when params exceed HTTPCLIENT_AUTH_HEADER_SIZE.
See also
HTTPCLIENT_AUTH_HEADER_SIZE standard size.
HTTP_AUTH_DIGEST full param list potential length.
RFC 7616 Digest auth header format.
Definition at line 1025 of file SocketHTTPClient-config.h.
HTTPCLIENT_AUTH_HEADER_SIZE
#define HTTPCLIENT_AUTH_HEADER_SIZE 512
Buffer size for standard Authorization headers (Basic/Digest/Bearer, 512 bytes).
For Basic: "Basic base64(creds)"; Digest: full params; Bearer: "Bearer token". 512 bytes covers typical cases; see LARGE variant for complex Digest.
See also
SocketHTTPClient_Auth for credential types.
HTTPCLIENT_AUTH_HEADER_LARGE_SIZE for extended Digest params.
RFC 7235 HTTP Authentication framework.
Definition at line 1008 of file SocketHTTPClient-config.h.
HTTPCLIENT_BODY_CHUNK_SIZE
#define HTTPCLIENT_BODY_CHUNK_SIZE 4096
Chunk size for reading response bodies incrementally (4096 bytes).
Size of buffers used to read and accumulate response body data from socket. 4KB balances I/O efficiency with memory usage during body parsing. Used in chunked, content-length, or connection-close modes.
Larger chunks reduce syscalls but increase latency for small responses. Contributes to HTTPCLIENT_DEFAULT_MAX_RESPONSE_SIZE limit checks.
See also
HTTPCLIENT_DEFAULT_MAX_RESPONSE_SIZE total body limit.
Socket_recvv() or similar for underlying I/O.
SocketHTTPClient_Response::body accumulated result.
Definition at line 958 of file SocketHTTPClient-config.h.
HTTPCLIENT_CONTENT_LENGTH_SIZE
#define HTTPCLIENT_CONTENT_LENGTH_SIZE 32
Buffer size for Content-Length header value string (32 bytes).
Formats numeric body length up to ~10^18 bytes (far beyond practical limits). 32 chars for digits + "Content-Length: " prefix space.
See also
RFC 7230 section 3.3.2 Content-Length.
SocketHTTPClient_Request_body() setting body length.
HTTPCLIENT_REQUEST_BUFFER_SIZE including this in request.
Definition at line 1088 of file SocketHTTPClient-config.h.
HTTPCLIENT_COOKIE_HEADER_SIZE
#define HTTPCLIENT_COOKIE_HEADER_SIZE 4096
Buffer size for serializing Cookie header in outgoing requests (4096 bytes).
Accumulates "Cookie: name1=value1; name2=value2; ..." from jar matching current request. 4KB handles sites with many cookies (analytics, session, prefs). Truncates if exceeds (rare); logs warning.
See also
SocketHTTPClient_CookieJar for source jar.
SocketHTTPClient_set_cookie_jar() associating jar with client.
RFC 6265 section 5.4 Cookie header format.
Definition at line 991 of file SocketHTTPClient-config.h.
HTTPCLIENT_DEFAULT_CONNECT_TIMEOUT_MS
#define HTTPCLIENT_DEFAULT_CONNECT_TIMEOUT_MS 30000
Default timeout for establishing new connections (30 seconds).Applies to TCP connect, TLS handshake, and proxy connections. Override via SocketHTTPClient_Config.connect_timeout_ms or per-request.
See also
Socket_connect()
SocketTLS_handshake()
SocketHTTPClient_Request_timeout()
Definition at line 170 of file SocketHTTPClient-config.h.
HTTPCLIENT_DEFAULT_DNS_TIMEOUT_MS
#define HTTPCLIENT_DEFAULT_DNS_TIMEOUT_MS 10000
Default timeout for DNS resolution (10 seconds).
Maximum time allowed for hostname resolution via SocketDNS. Includes query submission, worker thread processing, and result retrieval. Exceeding this raises SocketHTTPClient_DNSFailed or contributes to overall timeout.
10s accommodates slow DNS servers or network latency; reduce for faster failure detection. Override via SocketHTTPClient_Config.dns_timeout_ms.
See also
SocketDNS for underlying async DNS implementation.
SocketHTTPClient_DNSFailed exception on resolution failure.
SocketHTTPClient_Config::dns_timeout_ms for runtime configuration.
HTTPCLIENT_DEFAULT_REQUEST_TIMEOUT_MS includes this timeout.
Definition at line 212 of file SocketHTTPClient-config.h.
HTTPCLIENT_DEFAULT_IDLE_TIMEOUT_MS
#define HTTPCLIENT_DEFAULT_IDLE_TIMEOUT_MS 60000
Default idle timeout for pooled connections (60 seconds).
Time after which idle (unused) connections in the pool are closed and removed. Prevents resource leaks from stale connections and reduces server load. 60s allows reuse for typical web browsing patterns while reclaiming unused slots.
Override via SocketHTTPClient_Config.idle_timeout_ms. Set to 0 to disable (not recommended). Affects pool efficiency and memory usage.
See also
SocketHTTPClient_Config::enable_connection_pool must be enabled.
SocketHTTPClient_Config::max_total_connections pool limits.
SocketPool_cleanup() underlying pool maintenance.
Definition at line 232 of file SocketHTTPClient-config.h.
HTTPCLIENT_DEFAULT_MAX_CONNS_PER_HOST
#define HTTPCLIENT_DEFAULT_MAX_CONNS_PER_HOST 6
Default maximum concurrent connections per host (6).
Limits parallel connections to a single host to prevent overwhelming servers and respect typical server connection limits. Matches common browser behavior (Chrome/Firefox default ~6 per domain).
Exceeding limit blocks new requests until connections free up or timeout. Helps with fair resource sharing in multi-host scenarios. Override via SocketHTTPClient_Config.max_connections_per_host.
See also
HTTPCLIENT_DEFAULT_MAX_TOTAL_CONNS global limit.
SocketHTTPClient_Config::max_connections_per_host runtime override.
SocketPool for underlying connection pooling mechanics.
Definition at line 291 of file SocketHTTPClient-config.h.
HTTPCLIENT_DEFAULT_MAX_REDIRECTS
#define HTTPCLIENT_DEFAULT_MAX_REDIRECTS 10
Default maximum number of redirects to follow (10).
Limits automatic redirect following to prevent infinite loops or excessive hops. Exceeding this raises SocketHTTPClient_TooManyRedirects exception. 10 allows for common redirect chains (e.g., www -> non-www -> https) with margin.
Only follows 3xx status codes (301, 302, 303, 307, 308) per RFC 7231. POST redirects converted to GET unless redirect_on_post configured. Override via SocketHTTPClient_Config.follow_redirects (0 to disable).
See also
SocketHTTPClient_TooManyRedirects exception on limit exceed.
SocketHTTPClient_Config::follow_redirects runtime override.
SocketHTTPClient_Config::redirect_on_post for POST handling.
Definition at line 271 of file SocketHTTPClient-config.h.
HTTPCLIENT_DEFAULT_MAX_RESPONSE_SIZE
#define HTTPCLIENT_DEFAULT_MAX_RESPONSE_SIZE (10ULL * 1024 * 1024) /* 10MB default to prevent DoS */
Default maximum size for HTTP response bodies (10MB).
0 in SocketHTTPClient_Config allows unlimited, but compile-time default is 10MB to mitigate DoS.
ENFORCEMENT: During response body accumulation in HTTP/1.1 parsing. If exceeded, raises SocketHTTPClient_ResponseTooLarge exception. Increments SOCKET_CTR_LIMIT_RESPONSE_SIZE_EXCEEDED metric for monitoring.
Recommendation: Keep non-zero in production; adjust based on expected payload sizes (e.g., 1MB for APIs, larger for file downloads). Override at runtime via SocketHTTPClient_Config.max_response_size.
See also
SocketHTTPClient_ResponseTooLarge
SocketHTTPClient_Config::max_response_size
SocketMetrics for counter details.
Definition at line 576 of file SocketHTTPClient-config.h.
HTTPCLIENT_DEFAULT_MAX_RETRIES
#define HTTPCLIENT_DEFAULT_MAX_RETRIES 3
Default maximum number of retry attempts for transient failures (3).
Limits retries for retryable errors (connect, timeout, DNS) when enable_retry is true. Prevents excessive retries on persistent failures. 3 attempts with exponential backoff provides good balance of resilience and efficiency.
Total attempts = 1 initial + max_retries. Does not retry non-retryable errors (TLS, protocol, redirects, size limits). Override via SocketHTTPClient_Config.max_retries.
See also
HTTPCLIENT_DEFAULT_ENABLE_RETRY to enable retry logic.
SocketHTTPClient_error_is_retryable() determines retry eligibility.
SocketHTTPClient_Config::max_retries runtime override.
HTTPCLIENT_DEFAULT_RETRY_INITIAL_DELAY_MS backoff configuration.
Definition at line 398 of file SocketHTTPClient-config.h.
HTTPCLIENT_DEFAULT_MAX_TOTAL_CONNS
#define HTTPCLIENT_DEFAULT_MAX_TOTAL_CONNS 100
Default total maximum connections across all hosts (100).
Global limit on pooled connections regardless of host. Prevents uncontrolled memory and FD growth when connecting to many different hosts. 100 suitable for client applications; servers may need higher.
When reached, new connections block or fail based on acquire_timeout_ms. Influences hash table resize via HTTPCLIENT_POOL_LARGE_THRESHOLD. Override via SocketHTTPClient_Config.max_total_connections.
See also
HTTPCLIENT_DEFAULT_MAX_CONNS_PER_HOST per-host sub-limit.
SocketHTTPClient_Config::max_total_connections runtime override.
HTTPCLIENT_POOL_LARGE_THRESHOLD related pool performance tuning.
Definition at line 311 of file SocketHTTPClient-config.h.
HTTPCLIENT_DEFAULT_REQUEST_TIMEOUT_MS
#define HTTPCLIENT_DEFAULT_REQUEST_TIMEOUT_MS 60000
Default timeout for full HTTP request completion (60 seconds).
Total time allowed from request start to final response receipt, including DNS, connect, TLS handshake, sending request, and receiving response. Exceeding this raises SocketHTTPClient_Timeout exception.
Override via SocketHTTPClient_Config.request_timeout_ms or per-request timeout. 60s suitable for most APIs; reduce for latency-sensitive operations.
See also
HTTPCLIENT_DEFAULT_CONNECT_TIMEOUT_MS for connect-only timeout.
SocketHTTPClient_Timeout exception details.
SocketHTTPClient_Config::request_timeout_ms runtime override.
SocketHTTPClient_Request_timeout() per-request override.
Definition at line 191 of file SocketHTTPClient-config.h.
HTTPCLIENT_DEFAULT_RETRY_INITIAL_DELAY_MS
#define HTTPCLIENT_DEFAULT_RETRY_INITIAL_DELAY_MS 100
Default initial backoff delay for retries (100ms).
Starting delay before first retry attempt. Subsequent retries use exponential backoff: delay *= HTTPCLIENT_RETRY_MULTIPLIER + jitter. Short initial delay (100ms) allows quick recovery from transient issues without overwhelming servers.
Jitter (HTTPCLIENT_RETRY_JITTER_FACTOR) adds randomness to prevent thundering herd. Override via SocketHTTPClient_Config.retry_initial_delay_ms.
See also
HTTPCLIENT_DEFAULT_RETRY_MAX_DELAY_MS upper bound on backoff.
HTTPCLIENT_RETRY_MULTIPLIER backoff factor (2.0).
HTTPCLIENT_RETRY_JITTER_FACTOR randomization (0.25).
SocketHTTPClient_Config::retry_initial_delay_ms runtime override.
Definition at line 420 of file SocketHTTPClient-config.h.
HTTPCLIENT_DEFAULT_RETRY_MAX_DELAY_MS
#define HTTPCLIENT_DEFAULT_RETRY_MAX_DELAY_MS 10000
Default maximum backoff delay between retries (10 seconds).
Caps exponential backoff to prevent excessively long waits on repeated failures. After reaching this, further retries use this fixed delay (no further increase). 10s prevents client from hanging indefinitely while allowing recovery time.
Combined with initial delay and multiplier, provides graceful degradation. Override via SocketHTTPClient_Config.retry_max_delay_ms.
See also
HTTPCLIENT_DEFAULT_RETRY_INITIAL_DELAY_MS starting delay.
HTTPCLIENT_RETRY_MULTIPLIER exponential factor.
SocketHTTPClient_Config::retry_max_delay_ms runtime override.
SocketHTTPClient_error_is_retryable() for retry conditions.
Definition at line 441 of file SocketHTTPClient-config.h.
HTTPCLIENT_DEFAULT_RETRY_ON_CONNECT
#define HTTPCLIENT_DEFAULT_RETRY_ON_CONNECT 1
Default flag to retry on connection establishment errors (1 = enabled).
When enabled (and overall retry enabled), retries on TCP connect failures like ECONNREFUSED (server down), ENETUNREACH (network issue), ETIMEDOUT. Common transient errors where server/network may recover quickly.
Does not retry permanent errors (e.g., invalid address). Uses backoff logic. Override via SocketHTTPClient_Config.retry_on_connection_error.
See also
SocketHTTPClient_ConnectFailed underlying exception.
SocketError_is_retryable_errno() for errno classification.
SocketHTTPClient_Config::retry_on_connection_error runtime flag.
HTTPCLIENT_DEFAULT_ENABLE_RETRY master retry switch.
Definition at line 462 of file SocketHTTPClient-config.h.
HTTPCLIENT_DEFAULT_RETRY_ON_TIMEOUT
#define HTTPCLIENT_DEFAULT_RETRY_ON_TIMEOUT 1
Default flag to retry on request timeouts (1 = enabled).
When enabled (with overall retry), retries requests that exceed request_timeout_ms. Timeouts often transient due to network congestion, slow servers, or temporary load. Uses backoff to avoid immediate re-failure.
Caution: May amplify load on struggling servers. Monitor metrics for retry loops. Override via SocketHTTPClient_Config.retry_on_timeout.
See also
SocketHTTPClient_Timeout exception triggered by timeout.
HTTPCLIENT_DEFAULT_REQUEST_TIMEOUT_MS configurable timeout.
SocketHTTPClient_Config::retry_on_timeout runtime flag.
HTTPCLIENT_DEFAULT_ENABLE_RETRY required for any retries.
Definition at line 482 of file SocketHTTPClient-config.h.
HTTPCLIENT_DEFAULT_USER_AGENT
#define HTTPCLIENT_DEFAULT_USER_AGENT "SocketHTTPClient/1.0"
Default User-Agent header string sent in requests.
Simple identifier "SocketHTTPClient/1.0" for library requests. Servers may use for rate limiting or logging; override for application-specific ID. Includes version for compatibility tracking. Configurable via SocketHTTPClient_Config.user_agent (NULL uses default).
See also
SocketHTTPClient_Config::user_agent runtime override.
RFC 7231 section 5.5.3 User-Agent header.
SocketHTTP_Headers_add() header insertion.
Definition at line 1138 of file SocketHTTPClient-config.h.
HTTPCLIENT_DIGEST_A_BUFFER_SIZE
#define HTTPCLIENT_DIGEST_A_BUFFER_SIZE 512
Buffer size for Digest auth A1/A2 intermediate hashes (512 bytes).
Internal buffer for computing HA1 = MD5(username:realm:password) and HA2 = MD5(method:digest-uri) used in Digest response calculation. 512 bytes safe for hash outputs + temporary strings; prevents overflows in crypto ops.
See also
HTTP_AUTH_DIGEST scheme requiring these intermediates.
HTTPCLIENT_DIGEST_RESPONSE_SIZE for final response.
RFC 7616 Digest Access Authentication.
Definition at line 835 of file SocketHTTPClient-config.h.
HTTPCLIENT_DIGEST_CNONCE_HEX_SIZE
#define HTTPCLIENT_DIGEST_CNONCE_HEX_SIZE 33
Size of hex-encoded client nonce string for Digest auth headers (33 bytes).
Buffer for ASCII hex representation of cnonce (2 hex chars per byte + null terminator). For 16-byte cnonce: 32 hex chars + NUL = 33 bytes. Included in Authorization header as cnonce param.
See also
HTTPCLIENT_DIGEST_CNONCE_SIZE binary cnonce size.
RFC 7616 section 3.2.1 nonce format (hex lowercase recommended).
HTTPCLIENT_AUTH_HEADER_SIZE overall auth header buffer.
Definition at line 885 of file SocketHTTPClient-config.h.
HTTPCLIENT_DIGEST_CNONCE_SIZE
#define HTTPCLIENT_DIGEST_CNONCE_SIZE 16
Size of client nonce (cnonce) in bytes for Digest auth (16 bytes random).
Random data generated per request for replay protection in Digest auth. 16 bytes (128 bits) provides sufficient entropy against guessing. Hex-encoded to 32 chars in header.
See also
HTTPCLIENT_DIGEST_CNONCE_HEX_SIZE encoded string size.
RFC 7616 section 3.2.1 client nonce requirement.
SocketCrypto for random generation (if available).
Definition at line 868 of file SocketHTTPClient-config.h.
HTTPCLIENT_DIGEST_NC_SIZE
#define HTTPCLIENT_DIGEST_NC_SIZE 16
Buffer size for Digest auth nonce-count (nc) hex string (16 bytes).
Holds 8-digit hex nonce count (00000001 to FFFFFFFF) + null terminator. Incremented per request with same nonce for replay detection. 16 bytes allows padding and future extensions.
See also
RFC 7616 section 3.2.2 nonce-count format (8 hex digits).
HTTPCLIENT_AUTH_HEADER_SIZE including nc in header.
Digest auth state management for rollover handling.
Definition at line 901 of file SocketHTTPClient-config.h.
HTTPCLIENT_DIGEST_RESPONSE_SIZE
#define HTTPCLIENT_DIGEST_RESPONSE_SIZE 256
Buffer size for Digest auth response value (256 bytes).
Holds final response-digest = KD(HA1, nonce:nonce-count:cnonce:qop:HA2) or without qop. Sufficient for hex-encoded MD5 (32 chars) + params. Used in Authorization header construction.
See also
HTTPCLIENT_DIGEST_A_BUFFER_SIZE intermediates.
HTTP_AUTH_DIGEST response calculation.
RFC 7616 section 3.4 response computation.
Definition at line 851 of file SocketHTTPClient-config.h.
HTTPCLIENT_ENCODING_BR
#define HTTPCLIENT_ENCODING_BR 0x04
Brotli compression encoding flag.
Bit value 0x04. Supports Brotli compression (RFC 7932). Advertises "br" in Accept-Encoding header. Modern, efficient for text; requires Brotli library support. Client decompresses br-encoded responses if enabled.
See also
Content-Encoding Flags
Note
Brotli support may require additional dependencies or conditional compilation.
Definition at line 1199 of file SocketHTTPClient-config.h.
HTTPCLIENT_ENCODING_DEFLATE
#define HTTPCLIENT_ENCODING_DEFLATE 0x02
DEFLATE compression encoding flag.
Bit value 0x02. Supports deflate compression (RFC 9110). Advertises "deflate" in Accept-Encoding. Note: zlib wrapper often used; raw deflate deprecated. Client handles decompression for responses with this encoding.
See also
Content-Encoding Flags
SocketHTTPClient.c line ~918 for Accept-Encoding handling.
Definition at line 1187 of file SocketHTTPClient-config.h.
HTTPCLIENT_ENCODING_GZIP
#define HTTPCLIENT_ENCODING_GZIP 0x01
GZIP compression encoding flag.
Bit value 0x01. Supports gzip compression (RFC 9110, formerly RFC 7230). Advertises "gzip" in Accept-Encoding header. Client must decompress gzip-encoded responses.
See also
Content-Encoding Flags
SocketHTTPClient.c for header construction and decompression logic.
Definition at line 1176 of file SocketHTTPClient-config.h.
HTTPCLIENT_ENCODING_IDENTITY
#define HTTPCLIENT_ENCODING_IDENTITY 0x00
Identity (no compression) encoding flag.
Bit value 0x00. Represents uncompressed data transfer. Used as base flag or when no encoding is applied.
See also
Content-Encoding Flags
Definition at line 1166 of file SocketHTTPClient-config.h.
HTTPCLIENT_ERROR_BUFSIZE
#define HTTPCLIENT_ERROR_BUFSIZE 256
Size of internal buffer for formatting HTTP client error messages.Used in SocketHTTPClient_error_format() and related functions to prevent buffer overflows.
See also
SocketHTTPClient_Error
Definition at line 73 of file SocketHTTPClient-config.h.
HTTPCLIENT_HOST_HEADER_SIZE
#define HTTPCLIENT_HOST_HEADER_SIZE 256
Buffer size for generating Host header (256 bytes).
Temporary buffer for "Host: hostname:port" construction per RFC 7230. 256 bytes covers long FQDNs + port + optional userinfo. Automatically included unless suppressed.
See also
SocketHTTP_URI for host/port extraction from URL.
SocketHTTP_Headers_add() header insertion.
RFC 7230 section 5.4 Host header requirements.
Definition at line 974 of file SocketHTTPClient-config.h.
HTTPCLIENT_IO_BUFFER_SIZE
#define HTTPCLIENT_IO_BUFFER_SIZE 8192
I/O buffer size for pooled connections in HTTP client.
Size of read/write buffers allocated per connection in the pool. 8KB (8192 bytes) chosen as efficient size for typical HTTP requests/responses while minimizing memory overhead. Affects performance for small vs. large payloads.
Larger buffers reduce system call overhead for large transfers but increase memory usage per connection. Adjustable at compile-time for tuning.
See also
SocketHTTPClient_Config::enable_connection_pool to enable pooling.
SocketBuf_T underlying buffer implementation in core I/O.
HTTPCLIENT_REQUEST_BUFFER_SIZE for request serialization buffer.
Definition at line 152 of file SocketHTTPClient-config.h.
HTTPCLIENT_MAX_SET_COOKIES
#define HTTPCLIENT_MAX_SET_COOKIES 16
Maximum Set-Cookie headers processed per HTTP response (16).
Limits parsing of multiple Set-Cookie headers to prevent DoS from header flooding. Servers rarely send >5-10; 16 provides margin for complex apps. Excess ignored with warning log.
See also
SocketHTTP_Headers for header parsing.
SocketHTTPClient_CookieJar_set() per-cookie insertion.
HTTPCLIENT_MAX_COOKIES total jar limit.
RFC 6265 multiple Set-Cookie handling.
Definition at line 1057 of file SocketHTTPClient-config.h.
HTTPCLIENT_POOL_HASH_SIZE
#define HTTPCLIENT_POOL_HASH_SIZE 127
Default initial hash table size for HTTP client connection pool.Prime number 127 chosen for good distribution with low load factor. Automatically resizes to larger table when exceeding HTTPCLIENT_POOL_LARGE_THRESHOLD connections.
See also
HTTPCLIENT_POOL_LARGE_HASH_SIZE
SocketHTTPClient_pool_init()
Definition at line 91 of file SocketHTTPClient-config.h.
HTTPCLIENT_POOL_LARGE_HASH_SIZE
#define HTTPCLIENT_POOL_LARGE_HASH_SIZE 251
Larger hash table size for HTTP client connection pools exceeding 100 connections.
Prime number 251 selected for optimal hash distribution under higher load factors. Automatically used when pool connection count exceeds HTTPCLIENT_POOL_LARGE_THRESHOLD. Helps maintain O(1) average lookup performance in larger pools.
See also
HTTPCLIENT_POOL_HASH_SIZE for initial small-pool hash table.
HTTPCLIENT_POOL_LARGE_THRESHOLD for automatic resize trigger.
SocketHTTPClient_Config::max_total_connections for pool capacity configuration.
SocketHTTPClient_pool_init() internal pool initialization (implementation detail).
Definition at line 112 of file SocketHTTPClient-config.h.
HTTPCLIENT_POOL_LARGE_THRESHOLD
#define HTTPCLIENT_POOL_LARGE_THRESHOLD 100
Threshold for switching to larger hash table in connection pool.
When active connection count exceeds this value, the pool resizes its internal hash table from HTTPCLIENT_POOL_HASH_SIZE to HTTPCLIENT_POOL_LARGE_HASH_SIZE. Prevents performance degradation due to hash collisions in growing pools.
Default 100 balances memory usage and performance for typical workloads.
See also
HTTPCLIENT_POOL_HASH_SIZE initial table size.
HTTPCLIENT_POOL_LARGE_HASH_SIZE enlarged table size.
SocketHTTPClient_Config::max_total_connections influences when resize occurs.
Definition at line 132 of file SocketHTTPClient-config.h.
HTTPCLIENT_REQUEST_BUFFER_SIZE
#define HTTPCLIENT_REQUEST_BUFFER_SIZE 8192
Buffer size for serializing HTTP request lines and headers (8192 bytes).
Temporary buffer for building complete request string before sending. 8KB handles typical requests with many headers (e.g., cookies, auth). Prevents reallocations during header accumulation.
See also
SocketHTTP1_serialize_request() underlying serialization.
HTTPCLIENT_AUTH_HEADER_SIZE for auth-specific buffers.
SocketHTTPClient_Request_header() adding custom headers.
Definition at line 939 of file SocketHTTPClient-config.h.
HTTPCLIENT_RETRY_JITTER_FACTOR
#define HTTPCLIENT_RETRY_JITTER_FACTOR 0.25
Default retry backoff parameters: jitter factor (0.25) and multiplier (2.0).
Jitter: Random variation +/- jitter_factor * delay to prevent synchronized retries (thundering herd) across clients. 25% provides good randomization without excessive variance.
Multiplier: Exponential backoff factor. delay_{n} = min(max_delay, delay_{n-1} * multiplier). 2.0 standard for doubling delays (100ms -> 200 -> 400 -> ... capped at max).
Both used in retry logic when HTTPCLIENT_DEFAULT_ENABLE_RETRY active. Not runtime configurable; compile-time constants.
See also
HTTPCLIENT_DEFAULT_RETRY_INITIAL_DELAY_MS starting delay.
HTTPCLIENT_DEFAULT_RETRY_MAX_DELAY_MS cap.
SocketHTTPClient_Config::enable_retry prerequisite.
Exponential backoff with jitter best practices.
Definition at line 1113 of file SocketHTTPClient-config.h.
HTTPCLIENT_URI_BUFFER_SIZE
#define HTTPCLIENT_URI_BUFFER_SIZE 512
Buffer size for URI string in Digest auth calculations (512 bytes).
Holds normalized request-uri for HA2 hash (method:uri without query per RFC). 512 bytes for long paths/queries; used in digest-uri param.
See also
SocketHTTP_URI for URI parsing/normalization.
HTTPCLIENT_DIGEST_A_BUFFER_SIZE including HA2 computation.
RFC 7616 section 3.4.2 digest-uri definition.
Definition at line 1040 of file SocketHTTPClient-config.h.
Typedef Documentation
SocketHTTPClient_Callback
typedef void(* SocketHTTPClient_Callback) (SocketHTTPClient_AsyncRequest_T req, SocketHTTPClient_Response *response, SocketHTTPClient_Error error, void *userdata)
Async completion callback
Definition at line 1024 of file SocketHTTPClient.h.
Enumeration Type Documentation
SocketHTTPClient_AuthType
enum SocketHTTPClient_AuthType
Authentication scheme types supported by the HTTP client.
Supported schemes:
HTTP_AUTH_BASIC: RFC 7617 - Simple base64-encoded credentials
HTTP_AUTH_DIGEST: RFC 7616 - Challenge-response with MD5/SHA-256
HTTP_AUTH_BEARER: RFC 6750 - OAuth 2.0 bearer tokens
See also
SocketHTTPClient_Auth for credential configuration.
SocketHTTPClient_set_auth() to set default credentials.
Enumerator
HTTP_AUTH_NONE
No authentication
HTTP_AUTH_BASIC
RFC 7617 - Basic Authentication
HTTP_AUTH_DIGEST
RFC 7616 - Digest Access Authentication
HTTP_AUTH_BEARER
RFC 6750 - Bearer Token (OAuth 2.0)
Definition at line 405 of file SocketHTTPClient.h.
SocketHTTPClient_Error
enum SocketHTTPClient_Error
Error codes for HTTP client operations.
Used in asynchronous APIs and error reporting. Indicates specific failure modes.
Retryability guide:
HTTPCLIENT_ERROR_DNS: YES - DNS may recover
HTTPCLIENT_ERROR_CONNECT: YES - Server may restart
HTTPCLIENT_ERROR_TLS: NO - Configuration issue
HTTPCLIENT_ERROR_TIMEOUT: YES - Transient congestion
HTTPCLIENT_ERROR_PROTOCOL: NO - Server bug
HTTPCLIENT_ERROR_TOO_MANY_REDIRECTS: NO - Redirect loop
HTTPCLIENT_ERROR_RESPONSE_TOO_LARGE: NO - Size limit
HTTPCLIENT_ERROR_CANCELLED: NO - User cancelled
HTTPCLIENT_ERROR_OUT_OF_MEMORY: NO - Resource exhaustion
HTTPCLIENT_ERROR_LIMIT_EXCEEDED: NO - Pool limits reached
See also
SocketHTTPClient_error_is_retryable() to check programmatically.
SocketHTTPClient_error_string() for descriptions.
Enumerator
HTTPCLIENT_OK
HTTPCLIENT_ERROR_DNS
HTTPCLIENT_ERROR_CONNECT
HTTPCLIENT_ERROR_TLS
HTTPCLIENT_ERROR_TIMEOUT
HTTPCLIENT_ERROR_PROTOCOL
HTTPCLIENT_ERROR_TOO_MANY_REDIRECTS
HTTPCLIENT_ERROR_RESPONSE_TOO_LARGE
HTTPCLIENT_ERROR_CANCELLED
HTTPCLIENT_ERROR_OUT_OF_MEMORY
HTTPCLIENT_ERROR_LIMIT_EXCEEDED
Definition at line 323 of file SocketHTTPClient.h.
SocketHTTPClient_SameSite
enum SocketHTTPClient_SameSite
Cookie SameSite attribute values (RFC 6265bis draft).
Controls cross-site request protection:
NONE: No restrictions (requires Secure flag)
LAX: Allows safe methods (GET, HEAD) on top-level navigation
STRICT: Blocks all cross-site requests
See also
SocketHTTPClient_Cookie for full cookie structure.
SocketHTTPClient_CookieJar_set() for setting cookies.
Enumerator
COOKIE_SAMESITE_NONE
COOKIE_SAMESITE_LAX
COOKIE_SAMESITE_STRICT
Definition at line 1094 of file SocketHTTPClient.h.
Function Documentation
SocketHTTPClient_AsyncRequest_cancel()
void SocketHTTPClient_AsyncRequest_cancel (SocketHTTPClient_AsyncRequest_T req) extern
Cancel async request.
SocketHTTPClient_config_defaults()
void SocketHTTPClient_config_defaults (SocketHTTPClient_Config * config) extern
Initialize SocketHTTPClient_Config structure with production-safe defaults.
Populates the configuration with values optimized for secure, performant HTTP client usage in production environments. This function sets up a balanced configuration that prioritizes security (TLS verification, limited redirects/connections), performance (HTTP/2 preference, pooling), and resilience (timeouts, optional retries).
Detailed defaults include:
Protocol: Max HTTP/2 with ALPN negotiation for modern servers; falls back to HTTP/1.1.
Pooling: 6 connections per host (RFC 7540 recommendation), total 100 to prevent resource exhaustion.
Timeouts: Conservative values to avoid hanging: 30s connect, 60s request, 10s DNS.
Redirects: Follow up to 10 for GET/HEAD (safe methods); POST redirects disabled to prevent unintended repeats.
Compression: Accept all common encodings with auto-decompression to save bandwidth.
TLS: Strict verification; uses system default context (customizable via tls_context).
Retry: Disabled (safe default); enable for idempotent requests only.
Limits: Unlimited response size (monitor max_response_size for memory safety).
Security: SameSite enforcement for cookies.
After calling, override specific fields as needed for application requirements (e.g., shorter timeouts for mobile). Invalid configs (e.g., negative timeouts) will cause SocketHTTPClient_new() to fail with SocketHTTPClient_Failed.
Parameters
[in,out] config Pointer to SocketHTTPClient_Config structure to initialize and modify.
This function modifies the structure in place, setting all fields to defaults. No allocation performed; pure data initialization.
Thread Safety\n Yes - pure function with no side effects or shared state access.
Usage Example
SocketHTTPClient_Config config;
SocketHTTPClient_config_defaults(&config);
// Override for custom needs
config.connect_timeout_ms = 5000;  // 5s for faster failure
config.follow_redirects = 5;       // Limit redirects
config.user_agent = "MyApp/1.0";   // Custom UA
SocketHTTPClient_T client = SocketHTTPClient_new(&config);
if (client) {
    // Use client...
    SocketHTTPClient_free(&client);
}
Advanced Usage with TLS
TRY {
    SocketTLSContext_T tls_ctx = SocketTLSContext_new(); // Custom TLS
    SocketTLSContext_load_certs(tls_ctx, "ca.pem");
    SocketHTTPClient_Config config;
    SocketHTTPClient_config_defaults(&config);
    config.tls_context = tls_ctx;
    config.verify_ssl = 1; // Strict verify
    SocketHTTPClient_T client = SocketHTTPClient_new(&config);
    // HTTPS requests will use custom TLS
} EXCEPT(SocketHTTPClient_Failed) {
    // Handle config error
} END_TRY;
Note
Defaults assume SOCKET_HAS_TLS=1 for HTTPS; disable via config.verify_ssl=0 for testing (insecure!).
Warning
Unlimited max_response_size can lead to memory exhaustion on large responses; set limit for untrusted servers.
Complexity\n O(1) - constant time structure initialization, no loops or
allocations.
See also
SocketHTTPClient_new() to create client from config.
SocketHTTPClient_Config for all field descriptions and valid ranges.
docs/HTTP_CLIENT_GUIDE.md#configuration for tuning guide.
SocketTLSContext_new() for TLS customization.
Referenced by main().
SocketHTTPClient_CookieJar_clear()
void SocketHTTPClient_CookieJar_clear (SocketHTTPClient_CookieJar_T jar) extern
Clear all cookies.
Parameters
jar Cookie jar
SocketHTTPClient_CookieJar_clear_expired()
void SocketHTTPClient_CookieJar_clear_expired (SocketHTTPClient_CookieJar_T jar) extern
Clear expired cookies.
Parameters
jar Cookie jar
SocketHTTPClient_CookieJar_free()
void SocketHTTPClient_CookieJar_free (SocketHTTPClient_CookieJar_T * jar) extern
Free cookie jar and all stored cookies.
Parameters
jar Pointer to jar handle (set to NULL on success)
Releases all memory associated with the cookie jar, including all cookies. Safe to call on NULL. Cookies are cleared before free.
Thread Safety\n Yes - internal mutex protection
See also
SocketHTTPClient_CookieJar_new() for creation.
SocketHTTPClient_CookieJar_clear() to clear without freeing jar.
SocketHTTPClient_CookieJar_get()
const SocketHTTPClient_Cookie * SocketHTTPClient_CookieJar_get (SocketHTTPClient_CookieJar_T jar, const char * domain, const char * path, const char * name) extern
Clear all cookies.
Parameters
jar Cookie jar
SocketHTTPClient_CookieJar_load()
int SocketHTTPClient_CookieJar_load (SocketHTTPClient_CookieJar_T jar, const char * filename) extern
Load cookies from file.
Parameters
jar Cookie jar
filename File path
Returns
0 on success, -1 on error
SocketHTTPClient_CookieJar_new()
SocketHTTPClient_CookieJar_T SocketHTTPClient_CookieJar_new (void) extern
Create cookie jar.
Returns
New cookie jar
Thread Safety\n Yes
SocketHTTPClient_CookieJar_save()
int SocketHTTPClient_CookieJar_save (SocketHTTPClient_CookieJar_T jar, const char * filename) extern
Save cookies to file.
Parameters
jar Cookie jar
filename File path
Returns
0 on success, -1 on error
SocketHTTPClient_CookieJar_set()
int SocketHTTPClient_CookieJar_set (SocketHTTPClient_CookieJar_T jar, const SocketHTTPClient_Cookie * cookie) extern
Set cookie.
Parameters
jar Cookie jar
cookie Cookie to set
Returns
0 on success, -1 on error
SocketHTTPClient_delete()
int SocketHTTPClient_delete (SocketHTTPClient_T client, const char * url, SocketHTTPClient_Response * response) extern
Perform synchronous DELETE request.
Parameters
client Client instance
url Full URL (http:// or https://)
response Output response (caller must free via Response_free)
Sends DELETE request to remove resource at URL. Idempotent; multiple calls have same effect. Body is optional but rarely used.
Returns
0 on success, -1 on error
Exceptions
SocketHTTPClient_DNSFailed,SocketHTTPClient_ConnectFailed,SocketHTTPClient_Timeout,SocketHTTPClient_ProtocolError,etc.
Thread Safety\n No
See also
SocketHTTPClient_put() for resource updates.
SocketHTTPClient_get() for retrieval.
SocketHTTPClient_error_is_retryable()
int SocketHTTPClient_error_is_retryable (SocketHTTPClient_Error error) extern
Check if error code is retryable.
Parameters
error Error code from async operation
Returns
1 if error is typically retryable, 0 if fatal
Thread Safety\n Yes (pure function)
Use this to decide whether to retry a failed request:
Example: SocketHTTPClient_Error err = SocketHTTPClient_Request_error(req); if (SocketHTTPClient_error_is_retryable(err)) // Schedule retry with exponential backoff else // Log error and give up
Retryable errors:
DNS failures (server may recover)
Connection failures (server may restart)
Timeouts (network may clear)
SocketHTTPClient_error_string()
const char * SocketHTTPClient_error_string (SocketHTTPClient_Error error) extern
Get error description.
Parameters
error Error code
Returns
Static string
Thread Safety\n Yes
SocketHTTPClient_free()
void SocketHTTPClient_free (SocketHTTPClient_T * client) extern
Destroy HTTP client and release all resources.
Parameters
client Pointer to client handle (set to NULL on success)
Closes all pooled connections, frees internal arenas, DNS resolver, timers. Any in-flight async requests are cancelled and callbacks invoked with CANCELLED error. Safe to call on NULL.
Thread Safety\n No - concurrent use may race with ongoing operations
Warning
Call only when no threads are using the client.
See also
SocketHTTPClient_new() for creation.
SocketHTTPClient_pool_clear() to close connections without destroying client.
SocketHTTPClient_process() to drain async before free.
Referenced by main().
SocketHTTPClient_get()
int SocketHTTPClient_get (SocketHTTPClient_T client, const char * url, SocketHTTPClient_Response * response) extern
Perform synchronous GET request.
Parameters
client Client instance
url Full URL (http:// or https://). Supports http/https schemes; relative URLs invalid.
response Output response structure (caller must free via Response_free)
Retrieves resource at URL. Automatically handles:
DNS resolution (via SocketDNS)
Connection establishment (TCP + optional TLS)
Protocol negotiation (HTTP/1.1 or HTTP/2 via ALPN)
Redirect following (configurable)
Compression (gzip/deflate/brotli)
Cookie handling (if jar configured)
Authentication (if configured)
Response body loaded fully into memory unless max_response_size limits it. For streaming large responses, use custom Request API with body_stream callback.
Returns
0 on success (status_code in response), -1 on error
Exceptions
SocketHTTPClient_DNSFailed on hostname resolution failure
SocketHTTPClient_ConnectFailed on TCP connection failure
SocketHTTPClient_TLSFailed on TLS handshake/certificate issues
SocketHTTPClient_Timeout on connect/request timeouts
SocketHTTPClient_ProtocolError on malformed server response
SocketHTTPClient_TooManyRedirects on redirect loops
SocketHTTPClient_ResponseTooLarge if body exceeds limit
SocketHTTPClient_Failed for other errors (check errno)
Thread Safety\n No - client not thread-safe
See also
SocketHTTPClient_head() for header-only request.
SocketHTTPClient_post() for requests with body.
SocketHTTPClient_get_async() for non-blocking version.
SocketHTTPClient_Config for customization (timeouts, pooling, etc.).
Core I/O for underlying socket operations.
Security for TLS details.
Referenced by main().
SocketHTTPClient_get_async()
SocketHTTPClient_AsyncRequest_T SocketHTTPClient_get_async (SocketHTTPClient_T client, const char * url, SocketHTTPClient_Callback callback, void * userdata) extern
Start async GET.
SocketHTTPClient_get_cookie_jar()
SocketHTTPClient_CookieJar_T SocketHTTPClient_get_cookie_jar (SocketHTTPClient_T client) extern
Get associated cookie jar.
Parameters
client Client
Returns
Cookie jar or NULL
SocketHTTPClient_head()
int SocketHTTPClient_head (SocketHTTPClient_T client, const char * url, SocketHTTPClient_Response * response) extern
Perform synchronous HEAD request.
Parameters
client Client instance
url Full URL (http:// or https://)
response Output response (caller must free via Response_free)
Sends HEAD request to retrieve headers only (no body). Useful for checking resource existence, size, or modification time without downloading body.
Returns
0 on success, -1 on error
Exceptions
SocketHTTPClient_DNSFailed,SocketHTTPClient_ConnectFailed,SocketHTTPClient_TLSFailed,SocketHTTPClient_Timeout,SocketHTTPClient_ProtocolError,etc.
Thread Safety\n No
See also
SocketHTTPClient_get() for full GET request with body.
SocketHTTP_Method for other methods.
SocketHTTPClient_Response_free() for cleanup.
SocketHTTPClient_last_error()
SocketHTTPClient_Error SocketHTTPClient_last_error (SocketHTTPClient_T client) extern
Get last error code.
Parameters
client Client
Returns
Error code
SocketHTTPClient_new()
SocketHTTPClient_T SocketHTTPClient_new (const SocketHTTPClient_Config * config) extern
Create new HTTP client instance.
Parameters
config Configuration structure (NULL uses defaults from SocketHTTPClient_config_defaults())
Initializes client with connection pool, DNS resolver, and optional TLS context. Pool size, timeouts, and features configured via config.
Returns
Opaque client handle or NULL on failure
Exceptions
SocketHTTPClient_Failed on memory allocation failure or invalid config
Arena_Failed if underlying arena allocation fails
Thread Safety\n Yes - initialization is atomic
Note
Client must be freed with SocketHTTPClient_free() when done.
Default config enables pooling, HTTP/2, compression, and certificate verification.
See also
SocketHTTPClient_config_defaults() to populate config.
SocketHTTPClient_free() for cleanup.
SocketHTTPClient_Config for detailed options.
Referenced by main().
SocketHTTPClient_pool_clear()
void SocketHTTPClient_pool_clear (SocketHTTPClient_T client) extern
Close and clear all connections in the pool.
Parameters
client Client instance
Immediately closes all active and idle connections in the connection pool. Useful for graceful shutdown, configuration changes, or error recovery. Any in-flight requests will fail with SocketHTTPClient_ConnectFailed or similar.
Does not affect ongoing requests but prevents reuse of existing connections.
Thread Safety\n No
Note
Pool will repopulate on next request as needed.
See also
SocketHTTPClient_pool_stats() to inspect pool before clearing.
SocketHTTPClient_new() for pool recreation.
SocketHTTPClient_pool_stats()
void SocketHTTPClient_pool_stats (SocketHTTPClient_T client, SocketHTTPClient_PoolStats * stats) extern
Get pool statistics.
Parameters
client Client
stats Output statistics
SocketHTTPClient_post()
int SocketHTTPClient_post (SocketHTTPClient_T client, const char * url, const char * content_type, const void * body, size_t body_len, SocketHTTPClient_Response * response) extern
Perform synchronous POST request.
Parameters
client Client instance
url Full URL (http:// or https://)
content_type Content-Type header (e.g., "application/json")
body Request body data (may be NULL for empty)
body_len Length of body data
response Output response (caller must free via Response_free)
Sends POST request with provided body. Automatically sets Content-Length header. Supports connection pooling, redirects, compression, and authentication.
Returns
0 on success, -1 on error
Exceptions
SocketHTTPClient_DNSFailed,SocketHTTPClient_ConnectFailed,SocketHTTPClient_Timeout,SocketHTTPClient_ProtocolError,SocketHTTPClient_ResponseTooLarge,etc.
Thread Safety\n No
Note
Non-idempotent: Retries may cause duplicate submissions if enabled.
See also
SocketHTTPClient_Request_new() for custom headers/body.
SocketHTTPClient_put() for PUT requests.
SocketHTTPClient_post_async() for asynchronous version.
Referenced by main().
SocketHTTPClient_post_async()
SocketHTTPClient_AsyncRequest_T SocketHTTPClient_post_async (SocketHTTPClient_T client, const char * url, const char * content_type, const void * body, size_t body_len, SocketHTTPClient_Callback callback, void * userdata) extern
Start async POST.
SocketHTTPClient_process()
int SocketHTTPClient_process (SocketHTTPClient_T client, int timeout_ms) extern
Process async requests.
Parameters
client Client
timeout_ms Poll timeout
Returns
Number of completed requests
Thread Safety\n No
Call in event loop to process pending async requests.
SocketHTTPClient_put()
int SocketHTTPClient_put (SocketHTTPClient_T client, const char * url, const char * content_type, const void * body, size_t body_len, SocketHTTPClient_Response * response) extern
Perform synchronous PUT request.
Parameters
client Client instance
url Full URL (http:// or https://)
content_type Content-Type header (e.g., "application/json")
body Request body data (may be NULL for empty)
body_len Length of body data
response Output response (caller must free via Response_free)
Sends PUT request to update/replace resource with provided body. Idempotent operation; safe for retries.
Returns
0 on success, -1 on error
Exceptions
SocketHTTPClient_DNSFailed,SocketHTTPClient_ConnectFailed,SocketHTTPClient_Timeout,SocketHTTPClient_ProtocolError,etc.
Thread Safety\n No
See also
SocketHTTPClient_post() for creating new resources.
SocketHTTPClient_Request_new() for custom configuration.
SocketHTTPClient_Request_async()
SocketHTTPClient_AsyncRequest_T SocketHTTPClient_Request_async (SocketHTTPClient_Request_T req, SocketHTTPClient_Callback callback, void * userdata) extern
Start async custom request.
SocketHTTPClient_Request_auth()
void SocketHTTPClient_Request_auth (SocketHTTPClient_Request_T req, const SocketHTTPClient_Auth * auth) extern
Set per-request authentication.
Parameters
req Request
auth Authentication credentials
SocketHTTPClient_Request_body()
int SocketHTTPClient_Request_body (SocketHTTPClient_Request_T req, const void * data, size_t len) extern
Set request body.
Parameters
req Request
data Body data
len Data length
Returns
0 on success, -1 on error
Referenced by main().
SocketHTTPClient_Request_body_stream()
int SocketHTTPClient_Request_body_stream (SocketHTTPClient_Request_T req, ssize_t(*)(void *buf, size_t len, void *userdata) read_cb, void * userdata) extern
Set streaming body.
Parameters
req Request
read_cb Callback to read body data
userdata User data for callback
Returns
0 on success, -1 on error
SocketHTTPClient_Request_execute()
int SocketHTTPClient_Request_execute (SocketHTTPClient_Request_T req, SocketHTTPClient_Response * response) extern
Execute request.
Parameters
req Request
response Output response
Returns
0 on success, -1 on error
Thread Safety\n No
Referenced by main().
SocketHTTPClient_Request_free()
void SocketHTTPClient_Request_free (SocketHTTPClient_Request_T * req) extern
Free request builder and release resources.
Parameters
req Pointer to request handle (set to NULL on success)
Cleans up SocketHTTPClient_Request_T instance created by SocketHTTPClient_Request_new(). Releases any temporary allocations (headers, body buffers). Safe to call on NULL.
Thread Safety\n No
See also
SocketHTTPClient_Request_new() for creation.
Referenced by main().
SocketHTTPClient_Request_header()
int SocketHTTPClient_Request_header (SocketHTTPClient_Request_T req, const char * name, const char * value) extern
Add header.
Parameters
req Request
name Header name
value Header value
Returns
0 on success, -1 on error
Referenced by main().
SocketHTTPClient_Request_new()
SocketHTTPClient_Request_T SocketHTTPClient_Request_new (SocketHTTPClient_T client, SocketHTTP_Method method, const char * url) extern
Create request builder.
Parameters
client Client instance
method HTTP method
url Full URL
Returns
Request builder
Thread Safety\n No
Referenced by main().
SocketHTTPClient_Request_timeout()
void SocketHTTPClient_Request_timeout (SocketHTTPClient_Request_T req, int ms) extern
Set per-request timeout.
Parameters
req Request
ms Timeout in milliseconds
Referenced by main().
SocketHTTPClient_Response_free()
void SocketHTTPClient_Response_free (SocketHTTPClient_Response * response) extern
Free response resources.
Parameters
response Response to free
Thread Safety\n No
Referenced by main().
SocketHTTPClient_set_auth()
void SocketHTTPClient_set_auth (SocketHTTPClient_T client, const SocketHTTPClient_Auth * auth) extern
Set default authentication credentials for all requests.
Parameters
client Client instance
auth Authentication configuration (may be NULL to disable)
Applies auth to all subsequent requests unless overridden by Request_auth(). Supports Basic, Digest, and Bearer schemes.
Thread Safety\n No
Note
Digest auth requires server challenges; may require retry on 401.
See also
SocketHTTPClient_Auth for scheme details.
SocketHTTPClient_Request_auth() for per-request override.
SocketHTTPClient_set_cookie_jar()
void SocketHTTPClient_set_cookie_jar (SocketHTTPClient_T client, SocketHTTPClient_CookieJar_T jar) extern
Associate jar with client.
Parameters
client Client
jar Cookie jar (NULL to remove)
Variable Documentation
accept_encoding
int SocketHTTPClient_Config::accept_encoding
Bitmask: GZIP | DEFLATE | BR
Definition at line 510 of file SocketHTTPClient.h.
acquire_timeout_ms
int SocketHTTPClient_Config::acquire_timeout_ms
Timeout waiting for pool slot
Definition at line 498 of file SocketHTTPClient.h.
active_connections
size_t SocketHTTPClient_PoolStats::active_connections
Connections currently in use
Definition at line 1285 of file SocketHTTPClient.h.
allow_http2_cleartext
int SocketHTTPClient_Config::allow_http2_cleartext
Allow h2c upgrade (default: 0)
Definition at line 490 of file SocketHTTPClient.h.
arena
Arena_T SocketHTTPClient_Response::arena
For cleanup - caller must dispose
Definition at line 608 of file SocketHTTPClient.h.
auto_decompress
int SocketHTTPClient_Config::auto_decompress
Auto-decompress responses (default: 1)
Definition at line 511 of file SocketHTTPClient.h.
body
void* SocketHTTPClient_Response::body
Definition at line 605 of file SocketHTTPClient.h.
Referenced by main().
body_len
size_t SocketHTTPClient_Response::body_len
Definition at line 606 of file SocketHTTPClient.h.
Referenced by main().
connect_timeout_ms
int SocketHTTPClient_Config::connect_timeout_ms
Connection timeout
Definition at line 501 of file SocketHTTPClient.h.
connections_created
size_t SocketHTTPClient_PoolStats::connections_created
Total connections created
Definition at line 1289 of file SocketHTTPClient.h.
connections_failed
size_t SocketHTTPClient_PoolStats::connections_failed
Connection attempts that failed
Definition at line 1290 of file SocketHTTPClient.h.
connections_timed_out
size_t SocketHTTPClient_PoolStats::connections_timed_out
Connections that timed out waiting
Definition at line 1291 of file SocketHTTPClient.h.
dns_timeout_ms
int SocketHTTPClient_Config::dns_timeout_ms
DNS resolution timeout
Definition at line 503 of file SocketHTTPClient.h.
domain
const char* SocketHTTPClient_Cookie::domain
Definition at line 1125 of file SocketHTTPClient.h.
enable_connection_pool
int SocketHTTPClient_Config::enable_connection_pool
Enable pooling (default: 1)
Definition at line 493 of file SocketHTTPClient.h.
Referenced by main().
enable_retry
int SocketHTTPClient_Config::enable_retry
Enable automatic retry (default: 0)
Definition at line 534 of file SocketHTTPClient.h.
enforce_samesite
int SocketHTTPClient_Config::enforce_samesite
Security configuration Enforce SameSite attribute (default: 1)
Definition at line 543 of file SocketHTTPClient.h.
expires
time_t SocketHTTPClient_Cookie::expires
Definition at line 1127 of file SocketHTTPClient.h.
follow_redirects
int SocketHTTPClient_Config::follow_redirects
Max redirects (0 = disabled)
Definition at line 506 of file SocketHTTPClient.h.
headers
SocketHTTP_Headers_T SocketHTTPClient_Response::headers
Definition at line 604 of file SocketHTTPClient.h.
http_only
int SocketHTTPClient_Cookie::http_only
Definition at line 1129 of file SocketHTTPClient.h.
idle_connections
size_t SocketHTTPClient_PoolStats::idle_connections
Connections available for reuse
Definition at line 1286 of file SocketHTTPClient.h.
idle_timeout_ms
int SocketHTTPClient_Config::idle_timeout_ms
Idle connection timeout
Definition at line 496 of file SocketHTTPClient.h.
max_connection_age_ms
int SocketHTTPClient_Config::max_connection_age_ms
Max connection age (0 = unlimited)
Definition at line 497 of file SocketHTTPClient.h.
max_connections_per_host
size_t SocketHTTPClient_Config::max_connections_per_host
Per-host limit (default: 6)
Definition at line 494 of file SocketHTTPClient.h.
Referenced by main().
max_response_size
size_t SocketHTTPClient_Config::max_response_size
Max response body (0 = unlimited)
Definition at line 524 of file SocketHTTPClient.h.
max_retries
int SocketHTTPClient_Config::max_retries
Max retry attempts (default: 3)
Definition at line 535 of file SocketHTTPClient.h.
max_total_connections
size_t SocketHTTPClient_Config::max_total_connections
Total limit (default: 100)
Definition at line 495 of file SocketHTTPClient.h.
max_version
SocketHTTP_Version SocketHTTPClient_Config::max_version
Max HTTP version (default: HTTP/2)
Definition at line 489 of file SocketHTTPClient.h.
Referenced by main().
name
const char* SocketHTTPClient_Cookie::name
Definition at line 1123 of file SocketHTTPClient.h.
password
const char* SocketHTTPClient_Auth::password
For Basic, Digest
Definition at line 437 of file SocketHTTPClient.h.
path
const char* SocketHTTPClient_Cookie::path
Definition at line 1126 of file SocketHTTPClient.h.
pool_exhausted_waits
size_t SocketHTTPClient_PoolStats::pool_exhausted_waits
Times we waited for pool slot
Definition at line 1293 of file SocketHTTPClient.h.
proxy
SocketProxy_Config* SocketHTTPClient_Config::proxy
Default proxy (NULL for none)
Definition at line 518 of file SocketHTTPClient.h.
realm
const char* SocketHTTPClient_Auth::realm
Optional realm filter
Definition at line 439 of file SocketHTTPClient.h.
redirect_on_post
int SocketHTTPClient_Config::redirect_on_post
Follow redirects for POST (default: 0)
Definition at line 507 of file SocketHTTPClient.h.
request_timeout_ms
int SocketHTTPClient_Config::request_timeout_ms
Request timeout
Definition at line 502 of file SocketHTTPClient.h.
retry_initial_delay_ms
int SocketHTTPClient_Config::retry_initial_delay_ms
Initial backoff delay (default: 100ms)
Definition at line 536 of file SocketHTTPClient.h.
retry_max_delay_ms
int SocketHTTPClient_Config::retry_max_delay_ms
Max backoff delay (default: 10s)
Definition at line 537 of file SocketHTTPClient.h.
retry_on_5xx
int SocketHTTPClient_Config::retry_on_5xx
Retry on 5xx responses (default: 0)
Definition at line 540 of file SocketHTTPClient.h.
retry_on_connection_error
int SocketHTTPClient_Config::retry_on_connection_error
Retry on connect failures (default: 1)
Definition at line 538 of file SocketHTTPClient.h.
retry_on_timeout
int SocketHTTPClient_Config::retry_on_timeout
Retry on timeouts (default: 1)
Definition at line 539 of file SocketHTTPClient.h.
reused_connections
size_t SocketHTTPClient_PoolStats::reused_connections
Times a pooled connection was reused
Definition at line 1288 of file SocketHTTPClient.h.
same_site
SocketHTTPClient_SameSite SocketHTTPClient_Cookie::same_site
Definition at line 1130 of file SocketHTTPClient.h.
secure
int SocketHTTPClient_Cookie::secure
Definition at line 1128 of file SocketHTTPClient.h.
SocketHTTPClient_ConnectFailed
const Except_T SocketHTTPClient_ConnectFailed extern
TCP connection failure.
Category: NETWORK Retryable: YES - Server may restart, network may recover
Raised when TCP connect() fails. Common causes:
ECONNREFUSED: Server not listening (may start later)
ENETUNREACH: Network route unavailable (may recover)
EHOSTUNREACH: Host unreachable (may become reachable)
Referenced by main().
SocketHTTPClient_DNSFailed
const Except_T SocketHTTPClient_DNSFailed extern
DNS resolution failure.
Category: NETWORK Retryable: YES - DNS servers may recover, cache may refresh
Raised when hostname cannot be resolved. May be transient (DNS server overloaded) or permanent (invalid hostname).
Referenced by main().
SocketHTTPClient_Failed
const Except_T SocketHTTPClient_Failed extern
General client failure.
Category: Varies Retryable: Depends on underlying cause - check errno
Raised for unclassified errors. Check Socket_geterrno() for details.
Referenced by main().
SocketHTTPClient_ProtocolError
const Except_T SocketHTTPClient_ProtocolError extern
HTTP protocol error.
Category: PROTOCOL Retryable: NO - Server response is malformed
Raised when HTTP response cannot be parsed:
Invalid status line
Malformed headers
Invalid chunked encoding
Indicates server bug or proxy corruption.
SocketHTTPClient_ResponseTooLarge
const Except_T SocketHTTPClient_ResponseTooLarge extern
Response body exceeds limit.
Category: RESOURCE Retryable: NO - Server response is too large
Raised when response body exceeds max_response_size config. Retry would produce same result. Increase limit or use streaming API for large responses.
SocketHTTPClient_Timeout
const Except_T SocketHTTPClient_Timeout extern
Request timeout exceeded.
Category: TIMEOUT Retryable: YES - Network congestion may clear
Raised when request exceeds configured timeout. May succeed on retry if server/network recovers.
Referenced by main().
SocketHTTPClient_TLSFailed
const Except_T SocketHTTPClient_TLSFailed extern
TLS/SSL handshake or I/O failure.
Category: PROTOCOL Retryable: NO - Usually indicates configuration mismatch
Raised for TLS errors:
Certificate verification failure
Protocol version mismatch
Cipher suite negotiation failure
Retrying won't help unless TLS configuration is changed.
Referenced by main().
SocketHTTPClient_TooManyRedirects
const Except_T SocketHTTPClient_TooManyRedirects extern
Redirect limit exceeded.
Category: APPLICATION Retryable: NO - Indicates redirect loop or misconfiguration
Raised when redirect count exceeds max_redirects config. Usually indicates server misconfiguration (redirect loop).
stale_connections_removed
size_t SocketHTTPClient_PoolStats::stale_connections_removed
Stale/dead connections cleaned up
Definition at line 1292 of file SocketHTTPClient.h.
status_code
int SocketHTTPClient_Response::status_code
Definition at line 603 of file SocketHTTPClient.h.
Referenced by main().
tls_context
SocketTLSContext_T SocketHTTPClient_Config::tls_context
Custom TLS context (NULL for default)
Definition at line 514 of file SocketHTTPClient.h.
token
const char* SocketHTTPClient_Auth::token
For Bearer
Definition at line 438 of file SocketHTTPClient.h.
total_requests
size_t SocketHTTPClient_PoolStats::total_requests
Total requests made
Definition at line 1287 of file SocketHTTPClient.h.
type
SocketHTTPClient_AuthType SocketHTTPClient_Auth::type
Definition at line 435 of file SocketHTTPClient.h.
user_agent
const char* SocketHTTPClient_Config::user_agent
User-Agent header
Definition at line 521 of file SocketHTTPClient.h.
username
const char* SocketHTTPClient_Auth::username
For Basic, Digest
Definition at line 436 of file SocketHTTPClient.h.
value
const char* SocketHTTPClient_Cookie::value
Definition at line 1124 of file SocketHTTPClient.h.
verify_ssl
int SocketHTTPClient_Config::verify_ssl
Verify certificates (default: 1)
Definition at line 515 of file SocketHTTPClient.h.
version
SocketHTTP_Version SocketHTTPClient_Response::version
Definition at line 607 of file SocketHTTPClient.h.
Referenced by main().