HTTP Modules
HTTP Modules
Complete HTTP/1.1 and HTTP/2 protocol implementation with client and server support.
Modules
HPACK Header Compression Module
HTTP/1.1 Parser and Serializer Module
Comprehensive HTTP/1.1 parsing, serialization, and transfer encoding support.
HTTP/2 Private Implementation Details
HTTP/2 Protocol Implementation
HTTP/2 (RFC 9113) support with framing, streams, flow control, and HPACK integration.
HTTP Client Module
High-level HTTP client library supporting HTTP/1.1, HTTP/2, connection pooling, async I/O, authentication, cookies, redirects, compression, and proxy support.
HTTP Server Error Handling Macros
Migration guide for deprecated HTTP server statistics macros.
Internal HTTP Server Connection Management Helpers
Helper functions for managing individual HTTP server connections.
Files
file SocketHPACK-private.h
file SocketHPACK.h
HPACK header compression/decompression module for HTTP/2 (RFC 7541).
file SocketHTTP-private.h
Internal HTTP core structures and helper functions.
file SocketHTTP.h
Protocol-agnostic HTTP types, header handling, URI parsing, and utilities.
file SocketHTTP1-private.h
Internal HTTP/1.1 parser structures and DFA state machine.
file SocketHTTP1.h
HTTP/1.1 message syntax parsing and serialization (RFC 9112).
file SocketHTTP2-private.h
Internal HTTP/2 connection and stream structures.
file SocketHTTPClient-private.h
Internal HTTP client structures and connection pooling.
file SocketHTTPServer-private.h
Private implementation details for HTTP server connection and state management.
file SocketHTTPServer.h
High-level HTTP server supporting HTTP/1.1 and HTTP/2 protocols.
Data Structures
struct HPACK_DynamicEntry
Entry in the HPACK dynamic table storing a header field name-value pair.
struct SocketHPACK_Table_T
Dynamic table for storing header fields in HPACK compression (RFC 7541).
struct SocketHPACK_Encoder_T
Internal structure for HPACK header encoder.
struct SocketHPACK_Decoder_T
Internal structure for HPACK header decoder.
struct HPACK_StaticEntry
Structure for entries in the HPACK static table (RFC 7541 Table 2).
struct HPACK_HuffmanSymbol
Entry in the HPACK Huffman encoding table for a specific symbol.
struct HPACK_HuffmanTransition
Transition entry in the Huffman decoding DFA table.
struct SocketHPACK_Header
HPACK header field representation.
struct SocketHPACK_EncoderConfig
Configuration for HPACK encoder instance.
struct SocketHPACK_DecoderConfig
Configuration for HPACK decoder instance.
struct HeaderEntry
Individual HTTP header entry (name-value pair).
struct SocketHTTP_Headers_T
Internal implementation of SocketHTTP_Headers_T header collection.
struct SocketHTTP_MethodProperties
Semantic properties of an HTTP method as defined in RFC 9110 Section 9.2.
struct SocketHTTP_Header
Single HTTP header field representation for iteration and access.
struct SocketHTTP_URI
Parsed URI components according to RFC 3986.
struct SocketHTTP_MediaType
Parsed representation of an HTTP media type (Content-Type, Accept, etc.).
struct SocketHTTP_QualityValue
Single entry from quality-sorted list in Accept-like headers for content negotiation.
struct SocketHTTP_Request
Protocol-agnostic representation of an HTTP request message.
struct SocketHTTP_Response
Protocol-agnostic representation of an HTTP response message.
struct HTTP1_TokenBuf
Dynamic resizable buffer for accumulating parsed HTTP tokens.
struct SocketHTTP1_Parser_T
Internal implementation structure for the HTTP/1.1 parser (SocketHTTP1_Parser_T).
struct SocketHTTP2_Stream_T
Internal structure for managing an HTTP/2 stream.
struct SocketHTTP2_Conn_T
Internal structure for HTTP/2 connection management.
struct HTTPPoolEntry
HTTP connection pool entry for reusing connections to the same host:port.
struct HTTPPool
HTTP connection pool managing reusable connections by host:port key.
struct SocketHTTPClient_T
Main HTTP client instance managing configuration, pool, auth, and state.
struct SocketHTTPClient_Request_T
Per-request builder and state for custom HTTP requests.
struct SocketHTTPClient_AsyncRequest_T
Asynchronous HTTP request state and callback handler.
struct CookieEntry
Individual cookie storage in the client cookie jar.
struct SocketHTTPClient_CookieJar_T
Cookie jar for storing and managing HTTP cookies per domain.
struct RateLimitEntry
Linked list entry for per-path rate limiters.
struct ServerConnection
Core internal structure representing an active HTTP client connection.
struct SocketHTTPServer_Request_T
Internal implementation details of the SocketHTTPServer_Request opaque type.
struct SocketHTTPServer_T
Internal implementation of the SocketHTTPServer opaque type.
struct SocketHTTPServer_Config
HTTP server configuration structure.
struct SocketHTTPServer_Stats
Comprehensive server statistics structure for monitoring and debugging.
union SocketHTTP1_Parser.message
union HTTPPoolEntry.proto
struct HTTPPoolEntry.proto.h1
struct HTTPPoolEntry.proto.h2
Macros
#define SOCKET_HAS_HTTP 1
HTTP protocol support flag.
#define SOCKET_HAS_WEBSOCKET 1
WebSocket protocol support flag.
#define SOCKETHPACK_DEFAULT_TABLE_SIZE 4096
Default dynamic table size in bytes (RFC 7541 default).
#define SOCKETHPACK_MAX_TABLE_SIZE (64 * 1024)
Maximum allowable dynamic table size in bytes.
#define SOCKETHPACK_MAX_HEADER_SIZE (8 * 1024)
Maximum size for individual header (name + value) in bytes.
#define SOCKETHPACK_MAX_HEADER_LIST_SIZE (64 * 1024)
Maximum total size for decoded header list in bytes.
#define SOCKETHPACK_MAX_TABLE_UPDATES 2
Maximum allowed dynamic table size updates per header block.
#define SOCKETHPACK_STATIC_TABLE_SIZE 61
Size of the static table (RFC 7541 Appendix A).
#define SOCKETHPACK_ENTRY_OVERHEAD 32
Overhead bytes per dynamic table entry (RFC 7541 Section 4.1).
#define SOCKETHTTP_HEADER_BUCKETS 31
Hash table bucket count for header collections (internal constant).
#define SOCKETHTTP_IS_TCHAR(c) (sockethttp_tchar_table[(unsigned char)(c)])
Check if a character is a valid HTTP token character (tchar).
#define SOCKETHTTP_IS_UNRESERVED(c) (sockethttp_uri_unreserved[(unsigned char)(c)])
Test if a character is URI unreserved (no percent-encoding required).
#define SOCKETHTTP_HEX_VALUE(c) (sockethttp_hex_value[(unsigned char)(c)])
Extract numeric value from hexadecimal digit character.
#define SOCKETHTTP_MAX_HEADER_NAME 256
Maximum allowed length for HTTP header names, in bytes.
#define SOCKETHTTP_MAX_HEADER_VALUE (8 * 1024)
Maximum allowed length for individual HTTP header values, in bytes.
#define SOCKETHTTP_MAX_HEADER_SIZE (64 * 1024)
Maximum total size for all HTTP headers combined, in bytes.
#define SOCKETHTTP_MAX_HEADERS 100
Maximum number of HTTP headers allowed in a collection.
#define SOCKETHTTP_MAX_URI_LEN (8 * 1024)
Maximum length for URI strings during parsing, in bytes.
#define SOCKETHTTP_DATE_BUFSIZE 30
Recommended buffer size for HTTP-date formatting output.
#define HTTP_STATUS_CODE_MIN 100
Boundary constants for HTTP status code validation and categorization.
#define HTTP_STATUS_CODE_MAX 599
Maximum valid HTTP status code.
#define HTTP_STATUS_1XX_MIN HTTP_STATUS_CONTINUE
Minimum 1xx informational status code.
#define HTTP_STATUS_1XX_MAX 199
Maximum 1xx informational status code.
#define HTTP_STATUS_2XX_MIN HTTP_STATUS_OK
Minimum 2xx successful status code.
#define HTTP_STATUS_2XX_MAX 299
Maximum 2xx successful status code.
#define HTTP_STATUS_3XX_MIN HTTP_STATUS_MULTIPLE_CHOICES
Minimum 3xx redirection status code.
#define HTTP_STATUS_3XX_MAX 399
Maximum 3xx redirection status code.
#define HTTP_STATUS_4XX_MIN HTTP_STATUS_BAD_REQUEST
Minimum 4xx client error status code.
#define HTTP_STATUS_4XX_MAX 499
Maximum 4xx client error status code.
#define HTTP_STATUS_5XX_MIN HTTP_STATUS_INTERNAL_ERROR
Minimum 5xx server error status code.
#define HTTP_STATUS_5XX_MAX 599
Maximum 5xx server error status code.
#define http1_is_tchar(c) SOCKETHTTP_IS_TCHAR (c)
Determine if a byte is a valid HTTP token character (tchar).
#define http1_is_digit(c) ((c) >= '0' && (c) <= '9')
Check if a character is an ASCII decimal digit (0-9).
#define http1_is_hex(c)
Test if a character is a valid hexadecimal digit (0-9, a-f, A-F).
#define http1_hex_value(c) SOCKETHTTP_HEX_VALUE (c)
Convert a hexadecimal digit character to its integer value (0-15).
#define http1_is_ows(c) ((c) == ' ' || (c) == '\t')
Check if character is optional whitespace (OWS: SP or HTAB).
#define http1_is_vchar(c) ((unsigned char)(c) >= 0x21 && (unsigned char)(c) <= 0x7E)
Check if byte is a visible (non-control) US-ASCII character (VCHAR).
#define http1_is_obs_text(c) ((unsigned char)(c) >= 0x80)
Check if byte is obsolete text (high octet characters 0x80-0xFF).
#define http1_is_field_vchar(c) (http1_is_vchar (c) || http1_is_obs_text (c))
Check if character is valid in HTTP header field values (field-vchar).
#define HTTP1_DEFAULT_METHOD_BUF_SIZE 16
Default initial capacities for HTTP/1.1 token buffers used in parsing.
#define HTTP2_SETTING_ENTRY_SIZE 6
Fixed size of a SETTINGS frame parameter entry.
#define HTTP2_PING_PAYLOAD_SIZE 8
Fixed size of PING frame payload (opaque data).
#define HTTP2_GOAWAY_HEADER_SIZE 8
Fixed size of GOAWAY frame header fields (excluding debug data).
#define HTTP2_WINDOW_UPDATE_SIZE 4
Fixed size of WINDOW_UPDATE frame payload (window increment).
#define RAISE_HTTPCLIENT_ERROR(e) SOCKET_RAISE_MODULE_ERROR (SocketHTTPClient, e)
Raise HTTP client exception with detailed error message.
Typedefs
typedef int(* SocketHTTP_HeaderCallback) (const char *name, size_t name_len, const char *value, size_t value_len, void *userdata)
Callback function for iterating over HTTP headers in SocketHTTP_Headers_iterate().
typedef void(* SocketHTTPServer_Handler) (SocketHTTPServer_Request_T req, void *userdata)
Primary request handler callback invoked for each incoming HTTP request.
typedef int(* SocketHTTPServer_BodyCallback) (SocketHTTPServer_Request_T req, const void *chunk, size_t len, int is_final, void *userdata)
Callback for streaming request body data incrementally.
typedef int(* SocketHTTPServer_Validator) (SocketHTTPServer_Request_T req, int *reject_status, void *userdata)
Middleware callback for request validation and authentication.
typedef void(* SocketHTTPServer_DrainCallback) (SocketHTTPServer_T server, int timed_out, void *userdata)
Callback notified when graceful drain (shutdown) completes.
Enumerations
enum SocketHPACK_Result {
HPACK_OK = 0 ,
HPACK_INCOMPLETE ,
HPACK_ERROR ,
HPACK_ERROR_INVALID_INDEX ,
HPACK_ERROR_HUFFMAN ,
HPACK_ERROR_INTEGER ,
HPACK_ERROR_TABLE_SIZE ,
HPACK_ERROR_HEADER_SIZE ,
HPACK_ERROR_LIST_SIZE ,
HPACK_ERROR_BOMB
}
HPACK operation result codes.
enum URIParserState {
URI_STATE_START ,
URI_STATE_SCHEME ,
URI_STATE_SCHEME_COLON ,
URI_STATE_AUTHORITY_START ,
URI_STATE_AUTHORITY ,
URI_STATE_HOST ,
URI_STATE_HOST_IPV6 ,
URI_STATE_PORT ,
URI_STATE_PATH ,
URI_STATE_QUERY ,
URI_STATE_FRAGMENT
}
Internal states for DFA-based URI parser (RFC 3986 compliant).
enum SocketHTTP_Version {
HTTP_VERSION_0_9 = 9 ,
HTTP_VERSION_1_0 = 10 ,
HTTP_VERSION_1_1 = 11 ,
HTTP_VERSION_2 = 20 ,
HTTP_VERSION_3 = 30
}
HTTP protocol versions supported by the library.
enum SocketHTTP_Method {
HTTP_METHOD_GET = 0 ,
HTTP_METHOD_HEAD ,
HTTP_METHOD_POST ,
HTTP_METHOD_PUT ,
HTTP_METHOD_DELETE ,
HTTP_METHOD_CONNECT ,
HTTP_METHOD_OPTIONS ,
HTTP_METHOD_TRACE ,
HTTP_METHOD_PATCH ,
HTTP_METHOD_UNKNOWN = -1
}
Standard HTTP request methods as defined in RFC 9110 and extensions.
enum SocketHTTP_StatusCode {
HTTP_STATUS_CONTINUE = 100 ,
HTTP_STATUS_SWITCHING_PROTOCOLS = 101 ,
HTTP_STATUS_PROCESSING = 102 ,
HTTP_STATUS_EARLY_HINTS = 103 ,
HTTP_STATUS_OK = 200 ,
HTTP_STATUS_CREATED = 201 ,
HTTP_STATUS_ACCEPTED = 202 ,
HTTP_STATUS_NON_AUTHORITATIVE = 203 ,
HTTP_STATUS_NO_CONTENT = 204 ,
HTTP_STATUS_RESET_CONTENT = 205 ,
HTTP_STATUS_PARTIAL_CONTENT = 206 ,
HTTP_STATUS_MULTI_STATUS = 207 ,
HTTP_STATUS_ALREADY_REPORTED = 208 ,
HTTP_STATUS_IM_USED = 226 ,
HTTP_STATUS_MULTIPLE_CHOICES = 300 ,
HTTP_STATUS_MOVED_PERMANENTLY = 301 ,
HTTP_STATUS_FOUND = 302 ,
HTTP_STATUS_SEE_OTHER = 303 ,
HTTP_STATUS_NOT_MODIFIED = 304 ,
HTTP_STATUS_USE_PROXY = 305 ,
HTTP_STATUS_TEMPORARY_REDIRECT = 307 ,
HTTP_STATUS_PERMANENT_REDIRECT = 308 ,
HTTP_STATUS_BAD_REQUEST = 400 ,
HTTP_STATUS_UNAUTHORIZED = 401 ,
HTTP_STATUS_PAYMENT_REQUIRED = 402 ,
HTTP_STATUS_FORBIDDEN = 403 ,
HTTP_STATUS_NOT_FOUND = 404 ,
HTTP_STATUS_METHOD_NOT_ALLOWED = 405 ,
HTTP_STATUS_NOT_ACCEPTABLE = 406 ,
HTTP_STATUS_PROXY_AUTH_REQUIRED = 407 ,
HTTP_STATUS_REQUEST_TIMEOUT = 408 ,
HTTP_STATUS_CONFLICT = 409 ,
HTTP_STATUS_GONE = 410 ,
HTTP_STATUS_LENGTH_REQUIRED = 411 ,
HTTP_STATUS_PRECONDITION_FAILED = 412 ,
HTTP_STATUS_CONTENT_TOO_LARGE = 413 ,
HTTP_STATUS_URI_TOO_LONG = 414 ,
HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE = 415 ,
HTTP_STATUS_RANGE_NOT_SATISFIABLE = 416 ,
HTTP_STATUS_EXPECTATION_FAILED = 417 ,
HTTP_STATUS_IM_A_TEAPOT = 418 ,
HTTP_STATUS_MISDIRECTED_REQUEST = 421 ,
HTTP_STATUS_UNPROCESSABLE_CONTENT = 422 ,
HTTP_STATUS_LOCKED = 423 ,
HTTP_STATUS_FAILED_DEPENDENCY = 424 ,
HTTP_STATUS_TOO_EARLY = 425 ,
HTTP_STATUS_UPGRADE_REQUIRED = 426 ,
HTTP_STATUS_PRECONDITION_REQUIRED = 428 ,
HTTP_STATUS_TOO_MANY_REQUESTS = 429 ,
HTTP_STATUS_HEADER_TOO_LARGE = 431 ,
HTTP_STATUS_UNAVAILABLE_LEGAL = 451 ,
HTTP_STATUS_INTERNAL_ERROR = 500 ,
HTTP_STATUS_NOT_IMPLEMENTED = 501 ,
HTTP_STATUS_BAD_GATEWAY = 502 ,
HTTP_STATUS_SERVICE_UNAVAILABLE = 503 ,
HTTP_STATUS_GATEWAY_TIMEOUT = 504 ,
HTTP_STATUS_VERSION_NOT_SUPPORTED = 505 ,
HTTP_STATUS_VARIANT_ALSO_NEGOTIATES = 506 ,
HTTP_STATUS_INSUFFICIENT_STORAGE = 507 ,
HTTP_STATUS_LOOP_DETECTED = 508 ,
HTTP_STATUS_NOT_EXTENDED = 510 ,
HTTP_STATUS_NETWORK_AUTH_REQUIRED = 511
}
HTTP status codes as defined in RFC 9110 Section 15 and common extensions.
enum SocketHTTP_StatusCategory {
HTTP_STATUS_INFORMATIONAL = 1 ,
HTTP_STATUS_SUCCESSFUL = 2 ,
HTTP_STATUS_REDIRECTION = 3 ,
HTTP_STATUS_CLIENT_ERROR = 4 ,
HTTP_STATUS_SERVER_ERROR = 5
}
Categories of HTTP status codes for quick classification.
enum SocketHTTP_URIResult {
URI_PARSE_OK = 0 ,
URI_PARSE_ERROR ,
URI_PARSE_INVALID_SCHEME ,
URI_PARSE_INVALID_HOST ,
URI_PARSE_INVALID_PORT ,
URI_PARSE_INVALID_PATH ,
URI_PARSE_INVALID_QUERY ,
URI_PARSE_TOO_LONG
}
Result codes from URI parsing and related operations.
enum SocketHTTP_Coding {
HTTP_CODING_IDENTITY = 0 ,
HTTP_CODING_CHUNKED ,
HTTP_CODING_GZIP ,
HTTP_CODING_DEFLATE ,
HTTP_CODING_COMPRESS ,
HTTP_CODING_BR ,
HTTP_CODING_UNKNOWN = -1
}
Common HTTP transfer encodings and content codings per RFC 9110.
enum HTTP1_InternalState {
HTTP1_PS_START = 0 ,
HTTP1_PS_METHOD ,
HTTP1_PS_SP_AFTER_METHOD ,
HTTP1_PS_URI ,
HTTP1_PS_SP_AFTER_URI ,
HTTP1_PS_STATUS_CODE ,
HTTP1_PS_SP_AFTER_STATUS ,
HTTP1_PS_REASON ,
HTTP1_PS_VERSION_H ,
HTTP1_PS_VERSION_T1 ,
HTTP1_PS_VERSION_T2 ,
HTTP1_PS_VERSION_P ,
HTTP1_PS_VERSION_SLASH ,
HTTP1_PS_VERSION_MAJOR ,
HTTP1_PS_VERSION_DOT ,
HTTP1_PS_VERSION_MINOR ,
HTTP1_PS_LINE_CR ,
HTTP1_PS_LINE_LF ,
HTTP1_PS_HEADER_START ,
HTTP1_PS_HEADER_NAME ,
HTTP1_PS_HEADER_COLON ,
HTTP1_PS_HEADER_VALUE ,
HTTP1_PS_HEADER_VALUE_OWS ,
HTTP1_PS_HEADER_CR ,
HTTP1_PS_HEADER_LF ,
HTTP1_PS_HEADERS_END_LF ,
HTTP1_PS_BODY_IDENTITY ,
HTTP1_PS_BODY_UNTIL_CLOSE ,
HTTP1_PS_CHUNK_SIZE ,
HTTP1_PS_CHUNK_SIZE_EXT ,
HTTP1_PS_CHUNK_SIZE_CR ,
HTTP1_PS_CHUNK_SIZE_LF ,
HTTP1_PS_CHUNK_DATA ,
HTTP1_PS_CHUNK_DATA_CR ,
HTTP1_PS_CHUNK_DATA_LF ,
HTTP1_PS_TRAILER_START ,
HTTP1_PS_TRAILER_NAME ,
HTTP1_PS_TRAILER_COLON ,
HTTP1_PS_TRAILER_VALUE ,
HTTP1_PS_TRAILER_CR ,
HTTP1_PS_TRAILER_LF ,
HTTP1_PS_TRAILERS_END_LF ,
HTTP1_PS_COMPLETE ,
HTTP1_PS_ERROR ,
HTTP1_NUM_STATES
}
Low-level internal parser states for the DFA-based HTTP/1.1 parser.
enum SocketHTTP2_ConnState {
HTTP2_CONN_STATE_INIT = 0 ,
HTTP2_CONN_STATE_PREFACE_SENT ,
HTTP2_CONN_STATE_PREFACE_RECV ,
HTTP2_CONN_STATE_SETTINGS_SENT ,
HTTP2_CONN_STATE_SETTINGS_RECV ,
HTTP2_CONN_STATE_READY ,
HTTP2_CONN_STATE_GOAWAY_SENT ,
HTTP2_CONN_STATE_GOAWAY_RECV ,
HTTP2_CONN_STATE_CLOSED
}
HTTP/2 connection lifecycle states.
enum HTTPAsyncState {
ASYNC_STATE_IDLE = 0 ,
ASYNC_STATE_CONNECTING ,
ASYNC_STATE_SENDING ,
ASYNC_STATE_RECEIVING_HEADERS ,
ASYNC_STATE_RECEIVING_BODY ,
ASYNC_STATE_COMPLETE ,
ASYNC_STATE_FAILED ,
ASYNC_STATE_CANCELLED
}
States for asynchronous HTTP requests.
enum ServerConnState {
CONN_STATE_READING_REQUEST ,
CONN_STATE_READING_BODY ,
CONN_STATE_HANDLING ,
CONN_STATE_STREAMING_RESPONSE ,
CONN_STATE_SENDING_RESPONSE ,
CONN_STATE_CLOSED
}
Internal states tracking the processing pipeline of a server connection.
enum SocketHTTPServer_State {
HTTPSERVER_STATE_RUNNING ,
HTTPSERVER_STATE_DRAINING ,
HTTPSERVER_STATE_STOPPED
}
Server lifecycle states for monitoring server operation and graceful shutdown.
Functions
SocketHPACK_Table_T SocketHPACK_Table_new (size_t max_size, Arena_T arena)
Create a new dynamic HPACK table for header compression.
void SocketHPACK_Table_free (SocketHPACK_Table_T *table)
Dispose of a dynamic table instance and release its resources.
void SocketHPACK_Table_set_max_size (SocketHPACK_Table_T table, size_t max_size)
Update the maximum size of the dynamic table.
size_t SocketHPACK_Table_size (SocketHPACK_Table_T table)
Query the current size of the dynamic table in bytes.
size_t SocketHPACK_Table_count (SocketHPACK_Table_T table)
Get number of entries.
size_t SocketHPACK_Table_max_size (SocketHPACK_Table_T table)
Get maximum table size.
SocketHPACK_Result SocketHPACK_Table_get (SocketHPACK_Table_T table, size_t index, SocketHPACK_Header *header)
Get entry by index.
SocketHPACK_Result SocketHPACK_Table_add (SocketHPACK_Table_T table, const char *name, size_t name_len, const char *value, size_t value_len)
Add entry to dynamic table.
void SocketHPACK_encoder_config_defaults (SocketHPACK_EncoderConfig *config)
Initialize encoder config with defaults.
SocketHPACK_Encoder_T SocketHPACK_Encoder_new (const SocketHPACK_EncoderConfig *config, Arena_T arena)
Create HPACK encoder instance.
void SocketHPACK_Encoder_free (SocketHPACK_Encoder_T *encoder)
Free encoder.
ssize_t SocketHPACK_Encoder_encode (SocketHPACK_Encoder_T encoder, const SocketHPACK_Header *headers, size_t count, unsigned char *output, size_t output_size)
Encode header block.
void SocketHPACK_Encoder_set_table_size (SocketHPACK_Encoder_T encoder, size_t max_size)
Signal table size change.
SocketHPACK_Table_T SocketHPACK_Encoder_get_table (SocketHPACK_Encoder_T encoder)
Get encoder's dynamic table.
void SocketHPACK_decoder_config_defaults (SocketHPACK_DecoderConfig *config)
Initialize decoder config with defaults.
SocketHPACK_Decoder_T SocketHPACK_Decoder_new (const SocketHPACK_DecoderConfig *config, Arena_T arena)
Create HPACK decoder instance.
void SocketHPACK_Decoder_free (SocketHPACK_Decoder_T *decoder)
Free decoder.
SocketHPACK_Result SocketHPACK_Decoder_decode (SocketHPACK_Decoder_T decoder, const unsigned char *input, size_t input_len, SocketHPACK_Header *headers, size_t max_headers, size_t *header_count, Arena_T arena)
Decode a complete HPACK header block into headers array.
void SocketHPACK_Decoder_set_table_size (SocketHPACK_Decoder_T decoder, size_t max_size)
Handle SETTINGS table size update.
SocketHPACK_Table_T SocketHPACK_Decoder_get_table (SocketHPACK_Decoder_T decoder)
Get decoder's dynamic table.
ssize_t SocketHPACK_huffman_encode (const unsigned char *input, size_t input_len, unsigned char *output, size_t output_size)
Huffman encode string.
ssize_t SocketHPACK_huffman_decode (const unsigned char *input, size_t input_len, unsigned char *output, size_t output_size)
Huffman decode string.
size_t SocketHPACK_huffman_encoded_size (const unsigned char *input, size_t input_len)
Calculate encoded size.
size_t SocketHPACK_int_encode (uint64_t value, int prefix_bits, unsigned char *output, size_t output_size)
Encode integer with prefix.
SocketHPACK_Result SocketHPACK_int_decode (const unsigned char *input, size_t input_len, int prefix_bits, uint64_t *value, size_t *consumed)
Decode integer with prefix.
SocketHPACK_Result SocketHPACK_static_get (size_t index, SocketHPACK_Header *header)
Get entry from static table.
int SocketHPACK_static_find (const char *name, size_t name_len, const char *value, size_t value_len)
Find entry in static table.
const char * SocketHPACK_result_string (SocketHPACK_Result result)
Get error description.
static unsigned sockethttp_hash_name (const char *name, size_t len)
Hash HTTP header name for case-insensitive bucket lookup.
static int sockethttp_name_equal (const char *a, size_t a_len, const char *b, size_t b_len)
Perform case-insensitive comparison of HTTP header names.
const char * SocketHTTP_version_string (SocketHTTP_Version version)
Get version string.
SocketHTTP_Version SocketHTTP_version_parse (const char *str, size_t len)
Parse version string.
const char * SocketHTTP_method_name (SocketHTTP_Method method)
Get method name string.
SocketHTTP_Method SocketHTTP_method_parse (const char *str, size_t len)
Parse method string.
SocketHTTP_MethodProperties SocketHTTP_method_properties (SocketHTTP_Method method)
Get method semantic properties.
int SocketHTTP_method_valid (const char *str, size_t len)
Check if string is valid HTTP method token.
const char * SocketHTTP_status_reason (int code)
Get reason phrase for status code.
SocketHTTP_StatusCategory SocketHTTP_status_category (int code)
Get status code category.
int SocketHTTP_status_valid (int code)
Check if status code is valid.
SocketHTTP_Headers_T SocketHTTP_Headers_new (Arena_T arena)
Create a new empty HTTP header collection.
void SocketHTTP_Headers_clear (SocketHTTP_Headers_T headers)
Remove all headers.
int SocketHTTP_Headers_add (SocketHTTP_Headers_T headers, const char *name, const char *value)
Add header (null-terminated strings).
int SocketHTTP_Headers_add_n (SocketHTTP_Headers_T headers, const char *name, size_t name_len, const char *value, size_t value_len)
Add header with explicit lengths.
int SocketHTTP_Headers_set (SocketHTTP_Headers_T headers, const char *name, const char *value)
Set header (replace if exists).
const char * SocketHTTP_Headers_get (SocketHTTP_Headers_T headers, const char *name)
Get first header value (case-insensitive).
int SocketHTTP_Headers_get_int (SocketHTTP_Headers_T headers, const char *name, int64_t *value)
Get header value as integer.
size_t SocketHTTP_Headers_get_all (SocketHTTP_Headers_T headers, const char *name, const char **values, size_t max_values)
Get all values for header.
int SocketHTTP_Headers_has (SocketHTTP_Headers_T headers, const char *name)
Check if header exists.
int SocketHTTP_Headers_contains (SocketHTTP_Headers_T headers, const char *name, const char *token)
Check if header contains token.
int SocketHTTP_Headers_remove (SocketHTTP_Headers_T headers, const char *name)
Remove first header with name.
int SocketHTTP_Headers_remove_all (SocketHTTP_Headers_T headers, const char *name)
Remove all headers with name.
size_t SocketHTTP_Headers_count (SocketHTTP_Headers_T headers)
Get total header count.
const SocketHTTP_Header * SocketHTTP_Headers_at (SocketHTTP_Headers_T headers, size_t index)
Get header by index.
int SocketHTTP_Headers_iterate (SocketHTTP_Headers_T headers, SocketHTTP_HeaderCallback callback, void *userdata)
Iterate over all headers.
int SocketHTTP_header_name_valid (const char *name, size_t len)
Validate header name.
int SocketHTTP_header_value_valid (const char *value, size_t len)
Validate header value.
SocketHTTP_URIResult SocketHTTP_URI_parse (const char *uri, size_t len, SocketHTTP_URI *result, Arena_T arena)
Parse and validate a URI string into components.
const char * SocketHTTP_URI_result_string (SocketHTTP_URIResult result)
Get error description.
int SocketHTTP_URI_get_port (const SocketHTTP_URI *uri, int default_port)
Get port with default fallback.
int SocketHTTP_URI_is_secure (const SocketHTTP_URI *uri)
Check if URI uses secure scheme.
ssize_t SocketHTTP_URI_encode (const char *input, size_t len, char *output, size_t output_size)
Percent-encode string.
ssize_t SocketHTTP_URI_decode (const char *input, size_t len, char *output, size_t output_size)
Percent-decode string.
ssize_t SocketHTTP_URI_build (const SocketHTTP_URI *uri, char *output, size_t output_size)
Build URI string from components.
int SocketHTTP_date_parse (const char *date_str, size_t len, time_t *time_out)
Parse HTTP-date.
int SocketHTTP_date_format (time_t t, char *output)
Format time as HTTP-date (IMF-fixdate)
int SocketHTTP_MediaType_parse (const char *value, size_t len, SocketHTTP_MediaType *result, Arena_T arena)
Parse Content-Type header.
int SocketHTTP_MediaType_matches (const SocketHTTP_MediaType *type, const char *pattern)
Check if media type matches pattern.
size_t SocketHTTP_parse_accept (const char *value, size_t len, SocketHTTP_QualityValue *results, size_t max_results, Arena_T arena)
Parse Accept-style header.
SocketHTTP_Coding SocketHTTP_coding_parse (const char *name, size_t len)
Parse coding name.
const char * SocketHTTP_coding_name (SocketHTTP_Coding coding)
Get coding name string.
static int http1_tokenbuf_init (HTTP1_TokenBuf *buf, Arena_T arena, size_t initial_capacity)
Initialize HTTP1_TokenBuf, allocating initial buffer from arena.
static void http1_tokenbuf_reset (HTTP1_TokenBuf *buf)
Reset token buffer to empty (len=0) without deallocating memory or changing capacity.
static int http1_tokenbuf_append (HTTP1_TokenBuf *buf, Arena_T arena, char c, size_t max_size)
Append a single character to the token buffer, growing capacity if necessary.
static char * http1_tokenbuf_terminate (HTTP1_TokenBuf *buf, Arena_T arena, size_t max_size)
Null-terminate the token buffer and return pointer to the string.
SocketHTTP2_ErrorCode http2_frame_validate (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader *header)
Validate an HTTP/2 frame header against protocol rules.
int http2_flow_adjust_window (int32_t *window, int32_t delta)
Adjust flow control window by signed delta, typically from SETTINGS update.
int http2_frame_send (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader *header, const void *payload, size_t payload_len)
Serialize HTTP/2 frame and queue it in send buffer.
SocketHTTP2_Stream_T http2_stream_lookup (const SocketHTTP2_Conn_T conn, uint32_t stream_id)
Retrieve HTTP/2 stream from connection by stream identifier.
SocketHTTP2_Stream_T http2_stream_create (SocketHTTP2_Conn_T conn, uint32_t stream_id, int is_local_initiated)
Create and initialize a new HTTP/2 stream structure.
void http2_stream_destroy (SocketHTTP2_Stream_T stream)
Deallocate HTTP/2 stream resources and remove from connection.
SocketHTTP2_ErrorCode http2_stream_transition (SocketHTTP2_Stream_T stream, uint8_t frame_type, uint8_t flags, int is_send)
Validate and apply stream state transition for frame receipt or send.
int http2_flow_consume_recv (SocketHTTP2_Conn_T conn, SocketHTTP2_Stream_T stream, size_t bytes)
Deduct bytes from receive flow control windows (connection and stream).
int http2_flow_consume_send (SocketHTTP2_Conn_T conn, SocketHTTP2_Stream_T stream, size_t bytes)
Deduct bytes from send flow control windows prior to frame transmission.
int http2_flow_update_recv (SocketHTTP2_Conn_T conn, SocketHTTP2_Stream_T stream, uint32_t increment)
Increase receive flow control window after data consumption.
int http2_flow_update_send (SocketHTTP2_Conn_T conn, SocketHTTP2_Stream_T stream, uint32_t increment)
Update send flow control windows based on peer WINDOW_UPDATE frame.
int32_t http2_flow_available_send (const SocketHTTP2_Conn_T conn, const SocketHTTP2_Stream_T stream)
Get available send window for HTTP/2 connection or stream.
int http2_process_frame (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader *header, const unsigned char *payload)
Main entry for processing a received HTTP/2 frame.
int http2_process_data (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader *header, const unsigned char *payload)
Handle incoming HTTP/2 DATA frame for stream data transfer.
int http2_process_headers (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader *header, const unsigned char *payload)
Process incoming HTTP/2 HEADERS frame (pseudo-headers and HPACK decoding).
int http2_process_priority (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader *header, const unsigned char *payload)
Process incoming HTTP/2 PRIORITY frame for dependency tree updates.
int http2_process_rst_stream (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader *header, const unsigned char *payload)
Process incoming HTTP/2 RST_STREAM frame to abort a stream.
int http2_process_settings (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader *header, const unsigned char *payload)
Process incoming HTTP/2 SETTINGS frame for parameter negotiation.
int http2_process_push_promise (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader *header, const unsigned char *payload)
Process incoming HTTP/2 PUSH_PROMISE frame for server push promise.
int http2_process_ping (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader *header, const unsigned char *payload)
Process incoming HTTP/2 PING frame for connection liveness checks and timing.
int http2_process_goaway (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader *header, const unsigned char *payload)
Process incoming HTTP/2 GOAWAY frame for connection shutdown notification.
int http2_process_window_update (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader *header, const unsigned char *payload)
Process incoming HTTP/2 WINDOW_UPDATE frame to replenish flow control windows.
int http2_process_continuation (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader *header, const unsigned char *payload)
Process incoming HTTP/2 CONTINUATION frame to continue oversized header blocks.
int http2_decode_headers (SocketHTTP2_Conn_T conn, SocketHTTP2_Stream_T stream, const unsigned char *block, size_t len)
Decode HPACK-compressed header block into stream headers/trailers.
ssize_t http2_encode_headers (SocketHTTP2_Conn_T conn, const SocketHPACK_Header *headers, size_t count, unsigned char *output, size_t output_size)
Encode array of headers into HPACK-compressed block for transmission.
void http2_send_connection_error (SocketHTTP2_Conn_T conn, SocketHTTP2_ErrorCode error_code)
Emit GOAWAY frame with error code and shutdown connection gracefully.
void http2_send_stream_error (SocketHTTP2_Conn_T conn, uint32_t stream_id, SocketHTTP2_ErrorCode error_code)
Send RST_STREAM frame to terminate a specific stream abruptly.
void http2_emit_stream_event (SocketHTTP2_Conn_T conn, SocketHTTP2_Stream_T stream, int event)
Invoke registered stream event callback for notifications.
void http2_emit_conn_event (SocketHTTP2_Conn_T conn, int event)
Invoke registered connection event callback for notifications.
HTTPPool * httpclient_pool_new (Arena_T arena, const SocketHTTPClient_Config *config)
Create and initialize a new HTTP connection pool.
void httpclient_pool_free (HTTPPool *pool)
Dispose of HTTP connection pool and all associated resources.
HTTPPoolEntry * httpclient_pool_get (HTTPPool *pool, const char *host, int port, int is_secure)
Get or create a pool entry for the specified host:port and security.
void httpclient_pool_release (HTTPPool *pool, HTTPPoolEntry *entry)
Release a pool entry back to available state.
void httpclient_pool_close (HTTPPool *pool, HTTPPoolEntry *entry)
Close and remove a pool entry from the pool.
void httpclient_pool_cleanup_idle (HTTPPool *pool)
Clean up idle connections that have exceeded timeout.
HTTPPoolEntry * httpclient_connect (SocketHTTPClient_T client, const SocketHTTP_URI *uri)
Establish connection to target URI, handling proxy and TLS.
int httpclient_send_request (HTTPPoolEntry *conn, SocketHTTPClient_Request_T req)
Send HTTP request over the connection entry.
int httpclient_receive_response (HTTPPoolEntry *conn, SocketHTTPClient_Response *response, Arena_T arena)
Receive and parse HTTP response from connection.
int httpclient_auth_basic_header (const char *username, const char *password, char *output, size_t output_size)
Generate Basic authentication header value.
int httpclient_auth_digest_response (const char *username, const char *password, const char *realm, const char *nonce, const char *uri, const char *method, const char *qop, const char *nc, const char *cnonce, int use_sha256, char *output, size_t output_size)
Compute Digest authentication response value.
int httpclient_auth_digest_challenge (const char *www_authenticate, const char *username, const char *password, const char *method, const char *uri, const char *nc_value, char *output, size_t output_size)
Handle Digest authentication challenge from WWW-Authenticate header and generate Authorization response.
int httpclient_auth_bearer_header (const char *token, char *output, size_t output_size)
Generate Authorization header for Bearer token authentication (RFC 6750).
int httpclient_auth_is_stale_nonce (const char *www_authenticate)
Check if Digest challenge indicates stale nonce.
int httpclient_cookies_for_request (SocketHTTPClient_CookieJar_T jar, const SocketHTTP_URI *uri, char *output, size_t output_size, int enforce_samesite)
Generate Cookie header value from jar cookies applicable to URI.
int httpclient_parse_set_cookie (const char *value, size_t len, const SocketHTTP_URI *request_uri, SocketHTTPClient_Cookie *cookie, Arena_T arena)
Parse Set-Cookie header and populate cookie structure.
static unsigned httpclient_host_hash (const char *host, int port, size_t table_size)
Compute hash value for host:port pair used as connection pool key.
int httpclient_should_retry_error (const SocketHTTPClient_T client, SocketHTTPClient_Error error)
Determine if an HTTP client error is retryable.
int httpclient_should_retry_status (const SocketHTTPClient_T client, int status)
Determine if HTTP status code warrants retry.
int httpclient_calculate_retry_delay (const SocketHTTPClient_T client, int attempt)
Calculate exponential backoff delay for retry attempt.
void httpclient_retry_sleep_ms (int ms)
Sleep for the specified milliseconds during retry backoff.
void clear_response_for_retry (SocketHTTP_Response *response)
Clear HTTP response for retry, preserving useful fields.
void httpclient_clear_response_for_retry (SocketHTTPClient_Response *response)
Clear client-specific HTTP response for retry.
void SocketHTTPServer_config_defaults (SocketHTTPServer_Config *config)
Initialize SocketHTTPServer_Config with safe default values.
SocketHTTPServer_T SocketHTTPServer_new (const SocketHTTPServer_Config *config)
Allocate and initialize a new HTTP server instance.
void SocketHTTPServer_free (SocketHTTPServer_T *server)
Dispose of HTTP server instance and release all resources.
int SocketHTTPServer_start (SocketHTTPServer_T server)
Bind to address/port and start listening for incoming connections.
void SocketHTTPServer_stop (SocketHTTPServer_T server)
Stop accepting new connections while allowing existing ones to complete.
void SocketHTTPServer_set_handler (SocketHTTPServer_T server, SocketHTTPServer_Handler handler, void *userdata)
Register the primary request handler callback and associated user data.
int SocketHTTPServer_fd (SocketHTTPServer_T server)
Retrieve the file descriptor of the listening socket for external polling.
int SocketHTTPServer_process (SocketHTTPServer_T server, int timeout_ms)
Main event loop step: poll, accept, parse, handle requests.
SocketPoll_T SocketHTTPServer_poll (SocketHTTPServer_T server)
Access the internal SocketPoll_T instance for custom event handling.
SocketHTTP_Method SocketHTTPServer_Request_method (SocketHTTPServer_Request_T req)
Retrieve the parsed HTTP method from the request.
const char * SocketHTTPServer_Request_path (SocketHTTPServer_Request_T req)
Get the request path (URI path component).
const char * SocketHTTPServer_Request_query (SocketHTTPServer_Request_T req)
Get the query string portion of the request URI.
SocketHTTP_Headers_T SocketHTTPServer_Request_headers (SocketHTTPServer_Request_T req)
Access the parsed request headers as a headers container.
const void * SocketHTTPServer_Request_body (SocketHTTPServer_Request_T req)
Get pointer to fully buffered request body data.
size_t SocketHTTPServer_Request_body_len (SocketHTTPServer_Request_T req)
Retrieve the length of the request body in bytes.
const char * SocketHTTPServer_Request_client_addr (SocketHTTPServer_Request_T req)
Get the client (peer) IP address as string.
SocketHTTP_Version SocketHTTPServer_Request_version (SocketHTTPServer_Request_T req)
Determine the HTTP protocol version of the request.
Arena_T SocketHTTPServer_Request_arena (SocketHTTPServer_Request_T req)
Get the Arena_T used for this request's allocations.
size_t SocketHTTPServer_Request_memory_used (SocketHTTPServer_Request_T req)
Query approximate memory usage for the underlying connection.
void SocketHTTPServer_Request_status (SocketHTTPServer_Request_T req, int code)
Set the HTTP status code for the response.
void SocketHTTPServer_Request_header (SocketHTTPServer_Request_T req, const char *name, const char *value)
Add a header field to the HTTP response.
void SocketHTTPServer_Request_body_data (SocketHTTPServer_Request_T req, const void *data, size_t len)
Set the complete response body from a data buffer.
void SocketHTTPServer_Request_body_string (SocketHTTPServer_Request_T req, const char *str)
Set the response body from a null-terminated C string.
void SocketHTTPServer_Request_finish (SocketHTTPServer_Request_T req)
Finalize the response and transmit it to the client.
void SocketHTTPServer_Request_body_stream (SocketHTTPServer_Request_T req, SocketHTTPServer_BodyCallback callback, void *userdata)
Enable streaming body callback.
int64_t SocketHTTPServer_Request_body_expected (SocketHTTPServer_Request_T req)
Retrieve the expected total length of the request body.
int SocketHTTPServer_Request_is_chunked (SocketHTTPServer_Request_T req)
Determine if the request body uses chunked transfer encoding.
int SocketHTTPServer_Request_begin_stream (SocketHTTPServer_Request_T req)
Initiate a streaming (chunked) response to the client.
int SocketHTTPServer_Request_send_chunk (SocketHTTPServer_Request_T req, const void *data, size_t len)
Send response chunk.
int SocketHTTPServer_Request_end_stream (SocketHTTPServer_Request_T req)
End streaming response.
int SocketHTTPServer_Request_push (SocketHTTPServer_Request_T req, const char *path, SocketHTTP_Headers_T headers)
Initiate an HTTP/2 server push of a related resource to the client.
int SocketHTTPServer_Request_is_http2 (SocketHTTPServer_Request_T req)
Check if the underlying connection uses HTTP/2 protocol.
int SocketHTTPServer_Request_is_websocket (SocketHTTPServer_Request_T req)
Check if the request is a WebSocket upgrade attempt.
SocketWS_T SocketHTTPServer_Request_upgrade_websocket (SocketHTTPServer_Request_T req)
Accept WebSocket upgrade and switch protocol.
void SocketHTTPServer_set_rate_limit (SocketHTTPServer_T server, const char *path_prefix, SocketRateLimit_T limiter)
Register a rate limiter for specific endpoints or globally.
void SocketHTTPServer_set_validator (SocketHTTPServer_T server, SocketHTTPServer_Validator validator, void *userdata)
Install a middleware validator callback for incoming requests.
int SocketHTTPServer_drain (SocketHTTPServer_T server, int timeout_ms)
Initiate graceful server shutdown by draining active connections.
int SocketHTTPServer_drain_poll (SocketHTTPServer_T server)
Non-blocking check of drain progress and remaining work.
int SocketHTTPServer_drain_wait (SocketHTTPServer_T server, int timeout_ms)
Block until graceful drain completes or times out.
int64_t SocketHTTPServer_drain_remaining_ms (SocketHTTPServer_T server)
Calculate remaining time before drain timeout forces connection closure.
void SocketHTTPServer_set_drain_callback (SocketHTTPServer_T server, SocketHTTPServer_DrainCallback callback, void *userdata)
Register callback for graceful drain completion notification.
SocketHTTPServer_State SocketHTTPServer_state (SocketHTTPServer_T server)
Query the current lifecycle state of the server.
void SocketHTTPServer_stats (SocketHTTPServer_T server, SocketHTTPServer_Stats *stats)
Populate statistics structure with current server metrics snapshot.
void SocketHTTPServer_stats_reset (SocketHTTPServer_T server)
Reset all resettable statistics counters to zero.
Variables
const Except_T SocketHPACK_Error
SocketHPACK_Error - General HPACK operation failure.
const unsigned char sockethttp_tchar_table [256]
Lookup table for valid HTTP token characters (tchar) per RFC 9110 5.6.
const unsigned char sockethttp_uri_unreserved [256]
Lookup table for URI unreserved characters per RFC 3986 2.3.
const unsigned char sockethttp_hex_value [256]
Hexadecimal digit value lookup table for decoding and validation.
const Except_T SocketHTTP_Failed
SocketHTTP_Failed - Generic HTTP module failure.
const Except_T SocketHTTP_ParseError
SocketHTTP_ParseError - Error during core HTTP parsing operations.
const Except_T SocketHTTP_InvalidURI
SocketHTTP_InvalidURI - Invalid URI syntax or validation failure.
const Except_T SocketHTTP_InvalidHeader
SocketHTTP_InvalidHeader - Invalid HTTP header name or value.
static const unsigned char HTTP2_CLIENT_PREFACE [24] = "PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n"
Client connection preface magic string per RFC 9113.
const Except_T SocketHTTPServer_Failed
Exception raised on general server failures such as allocation errors or internal state corruption.
const Except_T SocketHTTPServer_BindFailed
Exception raised when binding to address/port fails (EADDRINUSE, EADDRNOTAVAIL, etc.).
const Except_T SocketHTTPServer_ProtocolError
Exception raised on HTTP protocol violations or parsing errors.
Detailed Description
Complete HTTP/1.1 and HTTP/2 protocol implementation with client and server support.
The HTTP group provides comprehensive HTTP protocol support including parsing, serialization, client/server implementations, and advanced features. Key components include:
SocketHTTP (core): HTTP types, headers, URI parsing, status codes (HTTP Modules)
SocketHTTP1: HTTP/1.1 parsing and serialization (HTTP/1.1 Module)
SocketHTTP2: HTTP/2 protocol implementation (HTTP/2 Module)
SocketHTTPClient: High-level HTTP client with pooling (HTTP Client Module)
SocketHTTPServer: HTTP server implementation (HTTP Server Module)
SocketHPACK: HTTP/2 header compression (HPACK Module)
See also
Core Foundation Modules for base infrastructure.
Core I/O Modules for socket primitives.
Security Modules for TLS integration.
SocketHTTPClient_T for HTTP client usage.
SocketHTTPServer_T for HTTP server implementation.
Data Structure Documentation
HPACK_DynamicEntry
struct HPACK_DynamicEntry
Entry in the HPACK dynamic table storing a header field name-value pair.
Stored in circular buffer. Strings are allocated from arena and managed by SocketHPACK_Table_T.
See also
SocketHPACK_Table_T
RFC 7541 Section 4.1
Definition at line 149 of file SocketHPACK-private.h.
Data Fields
char * name
Header name (arena-allocated)
size_t name_len
Name length
char * value
Header value (arena-allocated)
size_t value_len
Value length
SocketHPACK_Table
struct SocketHPACK_Table
Dynamic table for storing header fields in HPACK compression (RFC 7541).
HPACK dynamic table (opaque type)
Implements a circular buffer (ring buffer) for efficient eviction of oldest entries. Indices follow HPACK convention: index 1 is most recent, increasing indices are older. Supports dynamic resizing based on SETTINGS_HEADER_TABLE_SIZE.
See also
HPACK_DynamicEntry for individual entries.
hpack_table_evict() for eviction mechanism.
SocketHPACK_Encoder::table and SocketHPACK_Decoder::table for usage.
Definition at line 176 of file SocketHPACK-private.h.
Data Fields
Arena_T arena
Arena for allocating entries and strings
size_t capacity
Maximum number of entries (power-of-2)
size_t count
Current number of entries
HPACK_DynamicEntry * entries
Ring buffer of dynamic entries
size_t head
Index of oldest entry
size_t max_size
Maximum allowed size in bytes (from settings)
size_t size
Current total size in bytes (sum of entry sizes)
size_t tail
Index for next insertion (one past newest)
SocketHPACK_Encoder
struct SocketHPACK_Encoder
Internal structure for HPACK header encoder.
HPACK encoder (opaque type)
Manages dynamic table updates, Huffman encoding decisions, and indexing strategy. Used by SocketHTTP2 for compressing outgoing headers.
See also
SocketHPACK_EncoderConfig for configuration options.
SocketHPACK_Table_T for dynamic table details.
Definition at line 205 of file SocketHPACK-private.h.
Data Fields
Arena_T arena
Arena for temporary allocations during encoding
int huffman_encode
Flag to enable Huffman coding for strings
size_t pending_table_size
Pending dynamic table size update (0 if none)
int pending_table_size_update
Flag indicating a table size update is queued
SocketHPACK_Table_T table
Dynamic table shared with decoder if symmetric
int use_indexing
Flag to enable dynamic table indexing
SocketHPACK_Decoder
struct SocketHPACK_Decoder
Internal structure for HPACK header decoder.
HPACK decoder (opaque type)
Handles decompression of HPACK-encoded headers with security checks against decompression bombs (excessive expansion). Used by SocketHTTP2 for processing incoming headers.
See also
SocketHPACK_DecoderConfig for configuration.
SocketHPACK_Table_T for dynamic table.
Warning
Decompression bomb protection limits ratio of output to input bytes.
Definition at line 234 of file SocketHPACK-private.h.
Data Fields
Arena_T arena
Arena for decoded header allocations
uint64_t decode_input_bytes
Cumulative input bytes processed in current session
uint64_t decode_output_bytes
Cumulative output bytes produced in current session
double max_expansion_ratio
Maximum allowed output/input expansion ratio (default 10.0)
size_t max_header_list_size
Maximum size for the entire header list
size_t max_header_size
Maximum size for a single decoded header field
size_t settings_max_table_size
Maximum dynamic table size from peer SETTINGS
SocketHPACK_Table_T table
Dynamic table for header field references
HPACK_StaticEntry
struct HPACK_StaticEntry
Structure for entries in the HPACK static table (RFC 7541 Table 2).
Contains 61 predefined HTTP header fields. Field order minimizes padding. Strings are compile-time constants, no allocation needed.
See also
hpack_static_table for the full array of entries.
SocketHPACK_StaticEntry for public typedef (if exposed).
Definition at line 265 of file SocketHPACK-private.h.
Data Fields
const char * name
Header field name (compile-time constant string)
uint8_t name_len
Length of name in bytes
const char * value
Header field value (compile-time constant string)
uint8_t value_len
Length of value in bytes
HPACK_HuffmanSymbol
struct HPACK_HuffmanSymbol
Entry in the HPACK Huffman encoding table for a specific symbol.
Maps a symbol (0-256) to its variable-length Huffman code. Code is left-aligned in 32-bit field for easy bit manipulation.
See also
hpack_huffman_encode for the full table.
RFC 7541 Appendix B for Huffman code assignment.
Definition at line 290 of file SocketHPACK-private.h.
Data Fields
uint8_t bits
Number of valid bits in the code (1-30)
uint32_t code
Huffman code bits (left-aligned in 32-bit integer)
HPACK_HuffmanTransition
struct HPACK_HuffmanTransition
Transition entry in the Huffman decoding DFA table.
Defines state transition and output for a given input byte (nibble-indexed). Supports efficient single-pass decoding with minimal branching.
See also
hpack_huffman_decode for the DFA table.
HPACK_DFA_* flags for behavior indicators.
Definition at line 308 of file SocketHPACK-private.h.
Data Fields
uint8_t flags
Bit flags controlling output and error handling (HPACK_DFA_*)
uint8_t next_state
Next state in DFA (or special values like error/accept)
uint8_t sym
Primary output symbol if accepting state reached
SocketHPACK_Header
struct SocketHPACK_Header
HPACK header field representation.
Represents a single header with optional never_index flag. The never_index flag indicates sensitive data that should never be added to the dynamic table.
Definition at line 236 of file SocketHPACK.h.
Data Fields
const char * name
Header name
size_t name_len
Name length in bytes
int never_index
Sensitive - never add to dynamic table
const char * value
Header value
size_t value_len
Value length in bytes
SocketHPACK_EncoderConfig
struct SocketHPACK_EncoderConfig
Configuration for HPACK encoder instance.
Allows customization of table size, Huffman usage, and indexing behavior.
Definition at line 549 of file SocketHPACK.h.
Data Fields
int huffman_encode
Use Huffman encoding (default: 1)
size_t max_table_size
Maximum dynamic table size
int use_indexing
Add headers to dynamic table (default: 1)
SocketHPACK_DecoderConfig
struct SocketHPACK_DecoderConfig
Configuration for HPACK decoder instance.
Controls security limits like max header sizes and decompression bomb prevention.
Definition at line 650 of file SocketHPACK.h.
Data Fields
double max_expansion_ratio
Max decoded/encoded ratio to prevent decompression bombs (default: 10.0)
size_t max_header_list_size
Maximum total decoded size
size_t max_header_size
Maximum individual header size
size_t max_table_size
Maximum dynamic table size
HeaderEntry
struct HeaderEntry
Individual HTTP header entry (name-value pair).
Internal node structure used by SocketHTTP_Headers_T for storing individual headers in both hash table collision chains and insertion-order doubly-linked list.
Header names are stored case-preserved but looked up case-insensitively. Both name and value are null-terminated C strings allocated from the containing headers' arena.
Note
All fields are private; access via SocketHTTP_Headers_* public functions only.
See also
SocketHTTP_Headers_T for the containing collection.
sockethttp_name_equal() for case-insensitive name matching.
sockethttp_hash_name() for hash computation.
Definition at line 66 of file SocketHTTP-private.h.
Data Fields
struct HeaderEntry * hash_next
Next entry in same hash bucket (collision resolution)
struct HeaderEntry * list_next
Next entry in insertion-order doubly-linked list
struct HeaderEntry * list_prev
Previous entry in insertion-order doubly-linked list
char * name
Header name (case-preserved, null-terminated, arena-allocated)
size_t name_len
Length of name excluding null terminator
char * value
Header value (null-terminated, arena-allocated)
size_t value_len
Length of value excluding null terminator
SocketHTTP_Headers
struct SocketHTTP_Headers
Internal implementation of SocketHTTP_Headers_T header collection.
Opaque type for HTTP header collection with efficient operations.
Private structure providing case-insensitive header lookup via hash table (separate chaining) and ordered iteration via doubly-linked list.
All memory allocations (entries, strings) from provided arena. Not thread-safe; external locking required for concurrent access.
Note
Direct field access prohibited; use public SocketHTTP_Headers_* functions.
See also
SocketHTTP_Headers_T public opaque type.
HeaderEntry for individual header nodes.
sockethttp_hash_name() and sockethttp_name_equal() for internal lookup logic.
Manages a dynamic collection of HTTP headers with O(1) case-insensitive lookup using hash table. Memory allocated from provided arena; lifetime tied to arena. Supports duplicates, iteration, and validation against HTTP limits. Thread-unsafe; synchronize externally if shared across threads.
See also
SocketHTTP_Headers_new() to create a new collection.
SocketHTTP_Headers_add() to add headers.
SocketHTTP_Headers_get() for lookup.
SocketHTTP_Headers_clear() to remove all headers without freeing collection.
Definition at line 94 of file SocketHTTP-private.h.
Data Fields
Arena_T arena
Arena for all allocations in this collection
HeaderEntry * buckets[31]
Hash table buckets (fixed-size array)
size_t count
Number of headers currently stored
HeaderEntry * first
Head of insertion-order doubly-linked list (or NULL if empty)
HeaderEntry * last
Tail of insertion-order doubly-linked list (or NULL if empty)
size_t total_size
Cumulative size of all header names + values (bytes)
SocketHTTP_MethodProperties
struct SocketHTTP_MethodProperties
Semantic properties of an HTTP method as defined in RFC 9110 Section 9.2.
Bit fields indicating method safety, idempotency, cacheability, and body expectations. Used for request validation, caching decisions, and protocol compliance.
See also
SocketHTTP_method_properties() to retrieve properties for a method.
Definition at line 312 of file SocketHTTP.h.
Data Fields
unsigned cacheable: 1
1 if response to successful request is cacheable
unsigned has_body: 1
1 if request is allowed to have a body
unsigned idempotent: 1
1 if multiple identical requests have same effect as one
unsigned response_body: 1
1 if successful response includes a body (except for HEAD)
unsigned safe: 1
1 if method is safe (does not modify server resources)
SocketHTTP_Header
struct SocketHTTP_Header
Single HTTP header field representation for iteration and access.
Single header field (for iteration)
Used by functions like SocketHTTP_Headers_at() and SocketHTTP_Headers_iterate() to provide access to individual headers without copying. Name is case-preserved as received/sent; lookup is case-insensitive.
See also
SocketHTTP_Headers_at() to get header by index.
SocketHTTP_Headers_iterate() for callback-based iteration.
Definition at line 604 of file SocketHTTP.h.
Data Fields
const char * name
Header name (case-preserved, null-terminated)
size_t name_len
Length of name (excluding null)
const char * value
Header value (null-terminated; may be empty)
size_t value_len
Length of value (excluding null)
SocketHTTP_URI
struct SocketHTTP_URI
Parsed URI components according to RFC 3986.
Structure holding the generic syntax components of a URI or URI reference. All string pointers reference substrings from the original input or arena-allocated copies; they remain valid until the arena is cleared or disposed. Strings are null-terminated for convenience but lengths are provided for efficiency. Does not perform percent-decoding; use SocketHTTP_URI_decode() for that. Supports absolute URIs, origin form, and relative references. Host may include IPv6 literals in [brackets]; userinfo is parsed but deprecated per RFC 3986.
See also
SocketHTTP_URI_parse() to populate this structure from URI string.
SocketHTTP_URI_get_port() to get effective port with defaults (80/443).
SocketHTTP_URI_is_secure() to check if scheme indicates TLS (https/wss).
SocketHTTP_URI_build() to serialize back to string.
SocketHTTP_URI_encode() and SocketHTTP_URI_decode() for percent handling.
Definition at line 889 of file SocketHTTP.h.
Data Fields
const char * fragment
Fragment identifier (after #; NULL if absent)
size_t fragment_len
Length of fragment
const char * host
Authority host (hostname, IPv4, or [IPv6]; required for absolute URI)
size_t host_len
Length of host
const char * path
Path component (absolute or relative; never NULL, may be empty "/")
size_t path_len
Length of path
int port
Port number (0-65535) or -1 if not present
const char * query
Query string (everything after ?; NULL if absent)
size_t query_len
Length of query
const char * scheme
Scheme name (lowercase, e.g., "http", "https"; NULL for relative URI)
size_t scheme_len
Length of scheme
const char * userinfo
Userinfo "username:password" (deprecated by RFC 3986, may be NULL)
size_t userinfo_len
Length of userinfo
SocketHTTP_MediaType
struct SocketHTTP_MediaType
Parsed representation of an HTTP media type (Content-Type, Accept, etc.).
Extracts type/subtype from Content-Type header per RFC 9110 Section 8.3. Also parses common parameters: charset (for text types) and boundary (for multipart types). Other parameters ignored; full parsing requires custom handling. Strings point into arena or input buffer; null-terminated with lengths provided.
See also
SocketHTTP_MediaType_parse() to populate from header value string.
SocketHTTP_MediaType_matches() to check against pattern (supports wildcard patterns like * / * for any media type).
Definition at line 1082 of file SocketHTTP.h.
Data Fields
const char * boundary
Multipart boundary parameter (NULL if absent or not multipart)
size_t boundary_len
Length of boundary
const char * charset
Charset parameter value (e.g., "utf-8"; NULL if absent)
size_t charset_len
Length of charset
const char * subtype
Subtype (e.g., "html", "json", "form-data"; token)
size_t subtype_len
Length of subtype
const char * type
Top-level type (e.g., "text", "application", "multipart"; token per RFC 9110)
size_t type_len
Length of type
SocketHTTP_QualityValue
struct SocketHTTP_QualityValue
Single entry from quality-sorted list in Accept-like headers for content negotiation.
Represents a media type or language tag with its quality factor (q-value) from headers like Accept, Accept-Language. Parsed and sorted by descending quality (highest preference first). Quality defaults to 1.0 if not specified; 0.0 indicates rejection. Used in content negotiation to select best match.
See also
SocketHTTP_parse_accept() which populates arrays of this type.
Definition at line 1142 of file SocketHTTP.h.
Data Fields
float quality
Preference level 0.0-1.0 (1.0 highest; default 1.0 if omitted)
const char * value
Value string (media type, language tag, etc.; null-terminated)
size_t value_len
Length of value
SocketHTTP_Request
struct SocketHTTP_Request
Protocol-agnostic representation of an HTTP request message.
Captures the essential semantics of an HTTP request independent of transport (HTTP/1.x, HTTP/2, HTTP/3). Request target can be in absolute form (scheme+authority+path), origin form (authority+path), or asterisk form. Used by parsers, serializers, and high-level clients/servers. Body information provided for transfer decisions; actual body data handled separately.
See also
SocketHTTP1_Parser_get_request() for HTTP/1.1 parsing into this structure.
SocketHTTP2_Stream_send_request() for HTTP/2 usage.
SocketHTTP_Response for corresponding response structure.
Definition at line 1230 of file SocketHTTP.h.
Data Fields
const char * authority
Authority component (host[:port]; NULL for relative/asterisk form)
int64_t content_length
Exact body length or -1 for chunked/unknown
int has_body
1 if request includes body data
SocketHTTP_Headers_T headers
Request headers (NULL if none)
SocketHTTP_Method method
Request method (e.g., GET, POST)
const char * path
Path and query (e.g., "/resource?param=value"; "*" for OPTIONS *)
const char * scheme
Scheme for absolute-form URI (e.g., "https"; NULL otherwise)
SocketHTTP_Version version
Protocol version (e.g., HTTP/1.1)
SocketHTTP_Response
struct SocketHTTP_Response
Protocol-agnostic representation of an HTTP response message.
Captures semantics of HTTP response independent of wire format. Reason phrase is optional and only relevant for HTTP/1.x; ignored in HTTP/2+. Used by protocol parsers and high-level APIs. Body info for transfer; actual body separate.
See also
SocketHTTP1_Parser_get_response() for HTTP/1.1 parsing.
SocketHTTP2_Stream_recv_headers() for HTTP/2 headers reception.
SocketHTTP_Request for request counterpart.
Definition at line 1259 of file SocketHTTP.h.
Data Fields
int64_t content_length
Body length or -1 for chunked/unknown/transfer-encoding
int has_body
1 if response includes body
SocketHTTP_Headers_T headers
Response headers (NULL if none)
const char * reason_phrase
Reason phrase (HTTP/1.x only; NULL or empty for HTTP/2+)
int status_code
Status code (100-599)
SocketHTTP_Version version
Protocol version of response
HTTP1_TokenBuf
struct HTTP1_TokenBuf
Dynamic resizable buffer for accumulating parsed HTTP tokens.
Used to build method names, URIs, header names/values, reason phrases during incremental parsing. Allocations from provided Arena_T; grows by doubling capacity as needed up to configured limits.
Fields:
data: Pointer to the allocated buffer data (null-terminated after terminate()).
len: Current length of data stored (excluding null terminator).
capacity: Current allocated size of the data buffer.
See also
http1_tokenbuf_init() to allocate and initialize.
http1_tokenbuf_append() to add characters with growth.
http1_tokenbuf_reset() to clear without deallocation.
http1_tokenbuf_terminate() to null-terminate for string use.
Arena_T for underlying memory management and Arena_alloc() for growth.
SocketHTTP1_Config for max sizes enforced during append/terminate.
Definition at line 443 of file SocketHTTP1-private.h.
Data Fields
size_t capacity
Buffer capacity
char * data
Buffer data
size_t len
Current length
SocketHTTP1_Parser
struct SocketHTTP1_Parser
Internal implementation structure for the HTTP/1.1 parser (SocketHTTP1_Parser_T).
HTTP/1.1 parser instance (opaque type)
Manages all aspects of incremental HTTP/1.1 message parsing: configuration, DFA state machine, message construction (request/response), header/trailer accumulation, token buffering, body handling (content-length, chunked, until-close), limits enforcement, and connection flags.
Memory: All dynamic allocations (buffers, headers) from the 'arena' member. Parsing: Advances via internal_state using DFA tables; high-level state tracks progress. Limits: Counters prevent DoS (e.g., too many headers, oversized lines). Body: Supports transfer-encoding: chunked (with trailers) or content-length. Flags: Determines keep-alive, upgrades (e.g., WebSocket), 100-continue expectations.
Field groups:
Configuration: mode, config, arena
Parser state: state, error, internal_state
Current message: message union (request or response)
Headers/Trailers: headers (main), trailers (chunked end)
Token buffers: method_buf, uri_buf, reason_buf, name_buf, value_buf
Counters: header_count, total_header_size, line_length, etc. (and trailers)
Body state: body_mode, content_length, body_remaining, body_complete
Chunked state: chunk_size, chunk_remaining
Parsed values: version_major/minor, status_code
Flags: keepalive, is_upgrade, upgrade_protocol, expects_continue
Note
Not thread-safe; single-threaded use only.
User must not access fields directly; use public API getters.
See also
SocketHTTP1_Parser_new() for creation with config.
SocketHTTP1_Parser_execute() for feeding data and advancing state.
SocketHTTP1_Parser_get_request(), SocketHTTP1_Parser_get_response() for results.
SocketHTTP_Request, SocketHTTP_Response for message details.
SocketHTTP_Headers_T for header handling.
HTTP1_TokenBuf for token accumulation.
HTTP1_InternalState for DFA states.
SocketHTTP1_Config for configurable limits and behavior.
RFC 7230 for HTTP/1.1 specification compliance details.
Definition at line 495 of file SocketHTTP1-private.h.
Data Fields
Arena_T arena
int body_complete
SocketHTTP1_BodyMode body_mode
int64_t body_remaining
size_t chunk_remaining
size_t chunk_size
SocketHTTP1_Config config
int64_t content_length
SocketHTTP1_Result error
int expects_continue
size_t header_count
size_t header_line_length
SocketHTTP_Headers_T headers
HTTP1_InternalState internal_state
int is_upgrade
int keepalive
size_t line_length
union SocketHTTP1_Parser.message message
HTTP1_TokenBuf method_buf
SocketHTTP1_ParseMode mode
HTTP1_TokenBuf name_buf
HTTP1_TokenBuf reason_buf
SocketHTTP1_State state
int status_code
size_t total_header_size
size_t total_trailer_size
size_t trailer_count
SocketHTTP_Headers_T trailers
const char * upgrade_protocol
HTTP1_TokenBuf uri_buf
HTTP1_TokenBuf value_buf
int version_major
int version_minor
SocketHTTP2_Stream
struct SocketHTTP2_Stream
Internal structure for managing an HTTP/2 stream.
HTTP/2 stream (opaque type)
Tracks stream ID, state, flow control windows, received DATA buffering, header/trailer decoding state, and user data. Supports split headers via CONTINUATION frames and distinguishes push vs. regular streams.
Note
Fields are subject to change; use public API functions for access.
Thread Safety\n No - internal fields modified by protocol processing; direct access unsafe in multi-threaded contexts without external synchronization
See also
SocketHTTP2_Stream_T for opaque public handle.
http2_stream_create() for instantiation.
http2_stream_lookup() for retrieval by ID.
RFC 9113 Section 5.1 for stream lifecycle.
Represents a single bidirectional stream within an HTTP/2 connection. Supports headers, data, trailers, and flow control.
See also
SocketHTTP2_Stream_new() for creation.
SocketHTTP2_Stream_close() for termination.
SocketHTTP2_Stream_send_headers() and SocketHTTP2_Stream_send_data() for sending.
Definition at line 177 of file SocketHTTP2-private.h.
Data Fields
SocketHTTP2_Conn_T conn
Parent connection
int end_stream_received
END_STREAM flag received
int end_stream_sent
END_STREAM flag sent
struct SocketHTTP2_Stream * hash_next
unsigned char * header_block
Accumulated header block
size_t header_block_capacity
Allocated capacity
size_t header_block_len
Current length
size_t header_count
Number of initial headers
SocketHPACK_Header headers[128]
Decoded initial headers
int headers_consumed
Headers already consumed by user
int headers_received
Headers have been received
uint32_t id
Stream identifier
bool is_local_initiated
True if locally initiated (for limit enforcement)
int is_push_stream
1 if this is a server push stream, 0 otherwise
int pending_end_stream
Pending END_STREAM flag from initial frame in split headers
SocketBuf_T recv_buf
Received DATA frames
int32_t recv_window
Receive window size
int32_t send_window
Send window size
SocketHTTP2_StreamState state
Current state
size_t trailer_count
Number of trailers
SocketHPACK_Header trailers[128]
Decoded trailers
int trailers_consumed
Trailers already consumed by user
int trailers_received
Trailers received
void * userdata
SocketHTTP2_Conn
struct SocketHTTP2_Conn
Internal structure for HTTP/2 connection management.
HTTP/2 connection (opaque type)
Central state holder for an HTTP/2 connection: underlying socket, memory arena, role (client/server), HPACK encoder/decoder, I/O buffers, settings (local/peer), flow control, stream hash table with counts and rate limits, frame state (e.g., CONTINUATION, GOAWAY, PING), callbacks, timeouts, and DoS protections (RST/PING/ SETTINGS rate limiting per CVE-2023-44487 and similar).
Handles protocol compliance, security hardening, and event emission.
Note
Internal fields; access via public SocketHTTP2_Conn_T functions.
Thread Safety\n No - shared connection state modified without internal mutex; applications must serialize calls to connection functions (e.g., via external locking or single-threaded event loop)
See also
SocketHTTP2_Conn_T opaque public type.
SocketHTTP2_Conn_new() for public creation.
RFC 9113 for full HTTP/2 specification.
SocketHPACK_Encoder_T and SocketHPACK_Decoder_T for header compression.
Manages connection state, streams, flow control windows, and frame processing. Not thread-safe; use one per thread or synchronize externally.
See also
SocketHTTP2_Conn_new() for creation.
SocketHTTP2_Conn_free() for destruction.
SocketHTTP2_Conn_process() for event-driven processing.
Definition at line 251 of file SocketHTTP2-private.h.
Data Fields
Arena_T arena
Memory arena
uint32_t client_initiated_count
Count of client-initiated streams
SocketHTTP2_ConnCallback conn_callback
void * conn_callback_data
uint32_t continuation_frame_count
Current CONTINUATION count for header block
uint32_t continuation_stream_id
Stream expecting CONTINUATION
SocketHPACK_Decoder_T decoder
Header decoder
SocketHPACK_Encoder_T encoder
Header encoder
int expecting_continuation
Expecting CONTINUATION frame
SocketHTTP2_ErrorCode goaway_error_code
GOAWAY error code
int goaway_received
GOAWAY frame received
int goaway_sent
GOAWAY frame sent
uint32_t hash_seed
Random seed for stream hash randomization
int idle_timeout_ms
int32_t initial_recv_window
Initial stream recv window
int32_t initial_send_window
Initial stream send window
uint32_t last_peer_stream_id
Last peer stream ID processed
uint32_t local_settings[6]
Our settings
uint32_t max_peer_stream_id
Max stream ID from GOAWAY
uint32_t next_stream_id
Next stream ID to use
uint32_t peer_settings[6]
Peer's settings
uint32_t ping_count_in_window
PING count in current window
unsigned char ping_opaque[8]
Last PING opaque data
int ping_pending
Waiting for PING ACK
int ping_timeout_ms
int64_t ping_window_start_ms
Window start timestamp (monotonic)
SocketBuf_T recv_buf
Receive buffer
int32_t recv_window
Connection receive window
SocketHTTP2_Role role
Client or server
uint32_t rst_count_in_window
RST_STREAM count in current window
int64_t rst_window_start_ms
Window start timestamp (monotonic)
SocketBuf_T send_buf
Send buffer
int32_t send_window
Connection send window
uint32_t server_initiated_count
Count of server-initiated streams (incl push)
int settings_ack_pending
Waiting for SETTINGS ACK
uint32_t settings_count_in_window
SETTINGS count in current window
int settings_timeout_ms
int64_t settings_window_start_ms
Window start timestamp (monotonic)
Socket_T socket
Underlying transport
SocketHTTP2_ConnState state
Connection state
SocketHTTP2_StreamCallback stream_callback
void * stream_callback_data
SocketRateLimit_T stream_close_rate_limit
Rate limit for stream closes/RST
size_t stream_count
Active stream count (total for legacy, deprecate)
SocketRateLimit_T stream_open_rate_limit
Rate limit for stream creations
struct SocketHTTP2_Stream ** streams
Hash table
HTTPPoolEntry
struct HTTPPoolEntry
HTTP connection pool entry for reusing connections to the same host:port.
Manages a single connection supporting both HTTP/1.1 (sequential requests) and HTTP/2 (multiplexed streams) protocols. Includes protocol-specific state, buffers, and lifecycle tracking.
See also
HTTPPool for overall pool structure and management.
SocketHTTPClient.c for usage in client operations.
Definition at line 101 of file SocketHTTPClient-private.h.
Data Fields
int closed
Connection closed by peer
time_t created_at
Connection creation time
struct HTTPPoolEntry * hash_next
Hash chain for host:port
char * host
Target hostname (owned, null-terminated)
int in_use
For H1.1: currently handling request
int is_secure
Using TLS
time_t last_used
Last activity time
struct HTTPPoolEntry * next
Free list / all connections list
int port
Target port
struct HTTPPoolEntry * prev
Doubly linked for removal
union HTTPPoolEntry.proto proto
SocketHTTP_Version version
Negotiated protocol version
HTTPPool
struct HTTPPool
HTTP connection pool managing reusable connections by host:port key.
Hash-based storage with per-host and total connection limits. Supports idle timeout cleanup and statistics tracking. Thread-safe with mutex protection.
See also
httpclient_pool_new() for creation.
SocketHTTPClient-pool.c for implementation.
Definition at line 154 of file SocketHTTPClient-private.h.
Data Fields
HTTPPoolEntry * all_conns
All connections (for cleanup)
Arena_T arena
Memory arena
size_t connections_failed
size_t current_count
Current connection count
HTTPPoolEntry * free_entries
Free entry pool
size_t hash_size
Hash table size
HTTPPoolEntry ** hash_table
Hash table for host:port lookup
int idle_timeout_ms
Idle connection timeout
size_t max_per_host
Max connections per host
size_t max_total
Max total connections
pthread_mutex_t mutex
Thread safety
size_t reused_connections
size_t total_requests
SocketHTTPClient
struct SocketHTTPClient
Main HTTP client instance managing configuration, pool, auth, and state.
HTTP client instance.
Internal structure holding connection pool, default auth, cookie jar, TLS context (if SOCKET_HAS_TLS), and last error state. Protected by mutex for thread-safe shared access.
See also
SocketHTTPClient_new() in SocketHTTPClient.h for public creation.
SocketHTTPClient_free() for cleanup.
docs/HTTP-REFACTOR.md for design rationale.
Definition at line 193 of file SocketHTTPClient-private.h.
Data Fields
Arena_T arena
SocketHTTPClient_Config config
Configuration copy
SocketHTTPClient_CookieJar_T cookie_jar
Associated cookie jar
SocketHTTPClient_Auth * default_auth
Default auth (owned)
SocketTLSContext_T default_tls_ctx
Default TLS context (owned)
SocketHTTPClient_Error last_error
pthread_mutex_t mutex
Protects shared client state (auth, cookies, pool access)
HTTPPool * pool
Connection pool
SocketHTTPClient_AsyncRequest
struct SocketHTTPClient_AsyncRequest
Asynchronous HTTP request state and callback handler.
Async request handle.
Manages async request lifecycle, connection, response accumulation, and callback invocation upon completion or error. Linked for pending queue in client.
See also
SocketHTTPClient_get_async() for starting async requests.
SocketHTTPClient_Callback for response handling.
Definition at line 294 of file SocketHTTPClient-private.h.
Data Fields
SocketHTTPClient_Callback callback
SocketHTTPClient_T client
HTTPPoolEntry * conn
Connection being used
SocketHTTPClient_Error error
struct SocketHTTPClient_AsyncRequest * next
SocketHTTPClient_Request_T request
SocketHTTPClient_Response response
HTTPAsyncState state
void * userdata
CookieEntry
struct CookieEntry
Individual cookie storage in the client cookie jar.
Stores cookie data, creation time for eviction, and hash chain link.
See also
SocketHTTPClient_CookieJar_T for jar structure.
SocketHTTPClient_Cookie for cookie fields.
Definition at line 329 of file SocketHTTPClient-private.h.
Data Fields
SocketHTTPClient_Cookie cookie
Cookie data (strings owned)
time_t created
Creation timestamp for eviction
struct CookieEntry * next
Hash chain
SocketHTTPClient_CookieJar
struct SocketHTTPClient_CookieJar
Cookie jar for storing and managing HTTP cookies per domain.
Cookie jar.
Hash-based storage with eviction by age, max size limit, and thread safety. Supports SameSite policy enforcement and automatic Set-Cookie parsing.
See also
SocketHTTPClient_set_cookie_jar() to associate with client.
SocketHTTPClient_CookieJar_new() for creation.
docs/SECURITY.md "Cookies" section for Security Modules notes.
Definition at line 347 of file SocketHTTPClient-private.h.
Data Fields
Arena_T arena
size_t count
unsigned hash_seed
Random seed for hash collision resistance
size_t hash_size
CookieEntry ** hash_table
size_t max_cookies
pthread_mutex_t mutex
RateLimitEntry
struct RateLimitEntry
Linked list entry for per-path rate limiters.
Allows configuring different rate limits for different URL path prefixes. For example, API endpoints can have stricter limits than static files.
See also
SocketRateLimit_T for the underlying token bucket limiter.
SocketHTTPServer_set_rate_limiter() for adding limiters.
Definition at line 55 of file SocketHTTPServer-private.h.
Data Fields
SocketRateLimit_T limiter
struct RateLimitEntry * next
char * path_prefix
ServerConnection
struct ServerConnection
Core internal structure representing an active HTTP client connection.
Encapsulates all state for one client connection:
Socket handle and client address
Parsing and buffering (HTTP/1.1 parser, in/out buffers)
Request data (parsed request, body handling/streaming)
Response data (status, headers, body streaming)
Timing (creation, activity, request/response start times)
Metrics (request count, active streams for HTTP/2)
Resource tracking (memory used, arena)
Linked list pointers for server-wide connection management
State transitions managed via state field. Memory managed via arena; cleared on connection close. Thread-unsafe; accessed only from server event loop thread.
See also
connection_new() for allocation.
connection_close() for cleanup.
SocketHTTPServer::connections for list integration.
SocketHTTP_Request for parsed request details.
SocketHTTP1_Parser_T for HTTP/1.1 parsing state.
Definition at line 111 of file SocketHTTPServer-private.h.
Data Fields
size_t active_requests
Arena_T arena
void * body
SocketHTTPServer_BodyCallback body_callback
void * body_callback_userdata
size_t body_capacity
size_t body_len
SocketHTTP1_BodyMode body_mode
size_t body_received
int body_streaming
char client_addr[64]
int64_t created_at_ms
SocketBuf_T inbuf
int64_t last_activity_ms
size_t memory_used
struct ServerConnection * next
SocketBuf_T outbuf
SocketHTTP1_Parser_T parser
struct ServerConnection * prev
const SocketHTTP_Request * request
size_t request_count
int64_t request_start_ms
void * response_body
size_t response_body_len
int response_finished
SocketHTTP_Headers_T response_headers
int response_headers_sent
int64_t response_start_ms
int response_status
int response_streaming
Socket_T socket
ServerConnState state
SocketHTTPServer_Request
struct SocketHTTPServer_Request
Internal implementation details of the SocketHTTPServer_Request opaque type.
Opaque request context for handling individual HTTP requests.
This structure is passed to user-defined request handlers (SocketHTTPServer_Handler). It provides:
Reference to owning server for configuration and stats access
Underlying connection for low-level operations (internal use)
Per-request Arena_T for temporary allocations (freed after handler completes)
Start timestamp for latency calculations
Users MUST NOT access fields directly. Use public accessors like:
SocketHTTPServer_request_server()
SocketHTTPServer_request_arena()
SocketHTTPServer_request_time()
See also
SocketHTTPServer_Request in SocketHTTPServer.h for public opaque declaration.
SocketHTTPServer_Handler for usage in callbacks.
Arena_T for memory management details.
Contains parsed request details (method, URI, headers, body) and provides API for building responses (status, headers, body streaming). Lifetime scoped to the handler callback; do not store beyond callback execution. Memory managed by server arena.
See also
SocketHTTPServer_Handler callback usage.
SocketHTTPServer_Request_method(), SocketHTTPServer_Request_headers() etc.
SocketHTTPServer_Request_finish() to complete response.
Definition at line 183 of file SocketHTTPServer-private.h.
Data Fields
Arena_T arena
ServerConnection * conn
SocketHTTPServer_T server
int64_t start_time_ms
SocketHTTPServer
struct SocketHTTPServer
Internal implementation of the SocketHTTPServer opaque type.
Opaque HTTP server instance managing connections, requests, and protocol handling.
Central structure managing the entire HTTP server instance:
Configuration (config)
Listening socket and event poll (listen_socket, poll)
User callbacks for handling, validation, draining (handler, validator, drain_callback)
Connection list and counts (connections, connection_count)
Rate limiting configuration (rate_limiters, global_rate_limiter)
IP-based connection limiting (ip_tracker)
Graceful shutdown state (state, drain_start_ms, drain_timeout_ms)
Legacy stats fields (being phased out in favor of SocketMetrics)
Server arena for allocations
Thread-unsafe by design; intended for single-threaded use with SocketPoll. All access serialized by the event loop.
Note
Statistics and latency tracking migrated to SocketMetrics for centralized, thread-safe metrics. Legacy fields (stats_prev_requests, etc.) retained for compatibility but deprecated.
No embedded TLS; use SocketTLS integration via public API.
See also
SocketHTTPServer_new() for creation and initialization.
SocketHTTPServer_free() for cleanup and resource release.
SocketPoll_T for event loop integration details.
SocketIPTracker_T for client limiting implementation.
SocketRateLimit_T for rate limiting details.
Handles listening, accepting connections, parsing HTTP requests (1.1/2), invoking handlers, and sending responses. Integrates with SocketPoll for event-driven operation. Supports TLS, rate limiting, and graceful shutdown.
See also
SocketHTTPServer_new() for creation.
SocketHTTPServer_Config for configuration options.
SocketHTTPServer_process() for event processing.
Definition at line 220 of file SocketHTTPServer-private.h.
Data Fields
Arena_T arena
SocketHTTPServer_Config config
size_t connection_count
ServerConnection * connections
SocketHTTPServer_DrainCallback drain_callback
void * drain_callback_userdata
int64_t drain_start_ms
int drain_timeout_ms
SocketRateLimit_T global_rate_limiter
SocketHTTPServer_Handler handler
void * handler_userdata
SocketIPTracker_T ip_tracker
Socket_T listen_socket
SocketPoll_T poll
RateLimitEntry * rate_limiters
int running
volatile int state
pthread_mutex_t stats_mutex
uint64_t stats_prev_requests
int64_t stats_prev_time_ms
SocketHTTPServer_Validator validator
void * validator_userdata
SocketHTTPServer_Config
struct SocketHTTPServer_Config
HTTP server configuration structure.
Defines listening parameters, TLS settings, protocol options, resource limits, and timeout behaviors for the HTTP server.
Use SocketHTTPServer_config_defaults() to initialize with sensible defaults, then customize as needed before passing to SocketHTTPServer_new().
See also
SocketHTTPServer_config_defaults()
SocketHTTPServer_new()
Definition at line 306 of file SocketHTTPServer.h.
Data Fields
int backlog Listen backlog (default: 128).
const char * bind_address Bind address (NULL = all interfaces, default: "0.0.0.0").
int enable_h2c_upgrade Enable HTTP/2 upgrade via HTTP/1.1 Upgrade header (default: 0). Allows clients to upgrade from HTTP/1.1 to HTTP/2 over cleartext (h2c). Requires prior HTTP/1.1 connection; not for initial h2 connections.
Warning
Security risk if not behind trusted proxy; prefer ALPN/TLS for h2.
int keepalive_timeout_ms Keep-alive timeout in ms (default: 60s). Maximum time a connection can remain idle before closure.
Note
Overrides or complements request_timeout_ms for persistent connections.
size_t max_body_size Maximum request body size in bytes (default: 10MB). Exceeding triggers 413 Payload Too Large before body allocation. Set to 0 for unlimited (use with caution).
size_t max_concurrent_requests Maximum concurrent requests/streams per connection (default: 100). For HTTP/2 multiplexing; limits open streams. For HTTP/1.1, typically 1 but affects pipelining if enabled.
size_t max_connections Total maximum concurrent connections (default: 1000). Enforced globally; new connections rejected when reached.
int max_connections_per_client Maximum connections per client IP (default: 100). Prevents abuse from single IP; uses SocketIPTracker internally. Negative values disable limit.
size_t max_header_size Maximum total header size in bytes (default: 64KB). Exceeding triggers 431 Request Header Fields Too Large. Enforced by underlying HTTP parsers.
size_t max_requests_per_connection Maximum requests per connection (default: 1000). Limits pipelining/abuse on single connection; closes after limit. For HTTP/2, applies to total streams processed.
SocketHTTP_Version max_version Maximum supported HTTP version (default: HTTP_VERSION_2). Controls protocol negotiation and feature availability.
See also
SocketHTTP_Version enum for values.
int port Listen port (default: 8080).
int request_read_timeout_ms Maximum time to read complete request in ms (default: 30s). Applies to entire request parsing including headers and body. Prevents slowloris-style attacks.
int request_timeout_ms Idle timeout between requests in ms (default: 30s). Closes idle keep-alive connections after this period.
int response_write_timeout_ms Maximum time to send complete response in ms (default: 60s). Ensures timely response delivery; aborts on timeout.
SocketTLSContext_T tls_context TLS context for HTTPS (NULL = plain HTTP). Requires SOCKET_HAS_TLS and valid OpenSSL/LibreSSL context.
See also
SocketTLSContext_new() for creating TLS contexts.
SocketHTTPServer_Stats
struct SocketHTTPServer_Stats
Comprehensive server statistics structure for monitoring and debugging.
Aggregates counters, gauges, and histograms for server health, performance, and error tracking. Updated atomically during operation; snapshot via SocketHTTPServer_stats(). Includes connections, requests, bytes, errors, timeouts, rate limits, and latency percentiles (us resolution).
Reset with SocketHTTPServer_stats_reset() (preserves active_connections). Use for logging, metrics export (Prometheus), or alerting.
See also
SocketHTTPServer_stats() to populate.
SocketMetrics for global library metrics.
SocketPool stats for connection pool details.
Definition at line 1697 of file SocketHTTPServer.h.
Data Fields
size_t active_connections Current number of active client connections.
int64_t avg_request_time_us Arithmetic mean of request processing times.
size_t connections_rejected Connections rejected due to limits (max_conns, per-IP).
size_t errors_4xx Count of 4xx client errors returned.
size_t errors_5xx Count of 5xx server errors returned.
int64_t max_request_time_us Maximum observed request latency (reset on stats reset).
int64_t p50_request_time_us Median (50th percentile) request latency.
int64_t p95_request_time_us 95th percentile request latency (tail latency).
int64_t p99_request_time_us 99th percentile request latency (extreme tail).
size_t rate_limited Requests rejected by rate limiters (429).
size_t requests_per_second Recent RPS calculated over config window (10s default).
size_t timeouts Connections/requests closed due to timeout.
size_t total_bytes_received Total request bytes received (headers + body).
size_t total_bytes_sent Total response bytes sent to clients (headers + body).
size_t total_connections Cumulative connections accepted since start/reset.
size_t total_requests Total HTTP requests processed (successful + errors).
SocketHTTP1_Parser.message
union SocketHTTP1_Parser.message
Definition at line 510 of file SocketHTTP1-private.h.
Data Fields
SocketHTTP_Request request
SocketHTTP_Response response
HTTPPoolEntry.proto
union HTTPPoolEntry.proto
Definition at line 110 of file SocketHTTPClient-private.h.
Data Fields
struct HTTPPoolEntry.proto.h1 h1
struct HTTPPoolEntry.proto.h2 h2
HTTPPoolEntry.proto.h1
struct HTTPPoolEntry.proto.h1
Definition at line 112 of file SocketHTTPClient-private.h.
Data Fields
Arena_T conn_arena
Arena for connection resources (parser, buffers)
SocketBuf_T inbuf
SocketBuf_T outbuf
SocketHTTP1_Parser_T parser
Socket_T socket
HTTPPoolEntry.proto.h2
struct HTTPPoolEntry.proto.h2
Definition at line 121 of file SocketHTTPClient-private.h.
Data Fields
int active_streams
Count of active streams
SocketHTTP2_Conn_T conn
Macro Definition Documentation
HTTP1_DEFAULT_METHOD_BUF_SIZE
#define HTTP1_DEFAULT_METHOD_BUF_SIZE 16
Default initial capacities for HTTP/1.1 token buffers used in parsing.
Chosen to balance memory efficiency and common case performance:
Small for fixed-size tokens (methods, names)
Larger for variable (URIs, values) Buffers start at these sizes in http1_tokenbuf_init() and grow dynamically. Enforced against SocketHTTP1_Config limits during growth.
See also
HTTP1_TokenBuf for buffer management.
http1_tokenbuf_init() where these are passed as initial_capacity.
SocketHTTP1_Config::max_method_size, max_uri_size, etc. for runtime limits.
Default initial capacity for method token buffer (e.g., "GET", "POST").
Definition at line 829 of file SocketHTTP1-private.h.
http1_hex_value
#define http1_hex_value (c) SOCKETHTTP_HEX_VALUE (c)
Convert a hexadecimal digit character to its integer value (0-15).
Parameters
c Valid hex digit char ('0'-'9', 'a'-'f', 'A'-'F').
Returns
Integer value 0-15 corresponding to the hex digit; behavior undefined for invalid input.
Warning
Caller must validate with http1_is_hex(c) before calling to avoid garbage.
Note
Delegates to core HTTP module's macro for table lookup or computation.
See also
http1_is_hex() for validation prior to conversion.
SocketHTTP-private.h SOCKETHTTP_HEX_VALUE for implementation.
Chunk size parsing in HTTP1_PS_CHUNK_SIZE state.
Definition at line 754 of file SocketHTTP1-private.h.
http1_is_digit
#define http1_is_digit (c) ((c) >= '0' && (c) <= '9')
Check if a character is an ASCII decimal digit (0-9).
Parameters
c Character to test.
Returns
1 (true) if '0' <= c <= '9', 0 (false) otherwise.
Note
Simple range check; used in version parsing, status codes, chunk sizes.
See also
http1_is_hex() for hexadecimal digit check.
http1_char_class[HTTP1_CC_DIGIT] in DFA classification.
Definition at line 726 of file SocketHTTP1-private.h.
http1_is_field_vchar
#define http1_is_field_vchar (c) (http1_is_vchar (c) || http1_is_obs_text (c))
Check if character is valid in HTTP header field values (field-vchar).
Parameters
c Character/byte to test.
Returns
1 (true) if valid field-vchar (VCHAR or obs-text), 0 otherwise.
Note
field-vchar = VCHAR / obs-text (RFC 7230); excludes whitespace (separate).
Used in DFA for HTTP1_PS_HEADER_VALUE state to validate value chars.
Full field-value = *(field-content / obs-fold); field-content = field-vchar [ 1*(SP / HTAB) field-vchar ]
See also
http1_is_vchar() for VCHAR (0x21-0x7E).
http1_is_obs_text() for obs-text (0x80+).
RFC 7230 section 3.2.4 "header fields" for field-value grammar.
Definition at line 808 of file SocketHTTP1-private.h.
http1_is_hex
#define http1_is_hex (c)
Value:
  (((c) >= '0' && (c) <= '9') || ((c) >= 'a' && (c) <= 'f')                   \
   || ((c) >= 'A' && (c) <= 'F'))
Test if a character is a valid hexadecimal digit (0-9, a-f, A-F).
Parameters
c Character to test.
Returns
1 (true) if valid hex digit, 0 (false) otherwise.
Note
Used primarily for chunk-size parsing in transfer-encoding: chunked.
See also
http1_hex_value() to convert valid hex to numeric 0-15.
http1_char_class[HTTP1_CC_HEX] for DFA usage (hex letters only, excluding digits).
Definition at line 738 of file SocketHTTP1-private.h.
http1_is_obs_text
#define http1_is_obs_text (c) ((unsigned char)(c) >= 0x80)
Check if byte is obsolete text (high octet characters 0x80-0xFF).
Parameters
c Byte/character to test (unsigned char).
Returns
1 (true) if c >= 0x80 (allows legacy non-ASCII in headers), 0 otherwise.
Note
obs-text from RFC 7230: allows HTTP/1.0 legacy high bytes in field values.
Lenient for interoperability; strict mode may reject.
See also
http1_is_field_vchar() = VCHAR / SP / HTAB / obs-text for header values.
RFC 7230 section 3.2.6 errata for obs-text allowance.
Definition at line 793 of file SocketHTTP1-private.h.
http1_is_ows
#define http1_is_ows (c) ((c) == ' ' || (c) == '\t')
Check if character is optional whitespace (OWS: SP or HTAB).
Parameters
c Character to test.
Returns
1 (true) if c == ' ' (SP, 0x20) or c == '\t' (HTAB, 0x09), 0 otherwise.
Note
OWS = *(SP / HTAB) per RFC 7230; used after colon in headers, around values.
See also
RFC 7230 section 3.2.3 "optional whitespace" (OWS).
http1_char_class[HTTP1_CC_SP, HTTP1_CC_HTAB] for DFA classes.
Definition at line 766 of file SocketHTTP1-private.h.
http1_is_tchar
#define http1_is_tchar (c) SOCKETHTTP_IS_TCHAR (c)
Determine if a byte is a valid HTTP token character (tchar).
Parameters
c The input byte/character to classify (treated as unsigned char).
Returns
Non-zero (true) if c is a valid tchar per HTTP/1.1 token rules, 0 (false) otherwise.
Token chars (tchar): !#$%&'*+-.^_`|~ and ALPHA/DIGIT, excluding separators. Optimized via precomputed table lookup from core HTTP module. Used in DFA for header names, methods, etc.
See also
SocketHTTP-private.h for SOCKETHTTP_IS_TCHAR and tchar_table definition.
RFC 7230 section 3.2.6 "token" production.
http1_char_class[HTTP1_CC_TCHAR] related DFA class.
Definition at line 714 of file SocketHTTP1-private.h.
http1_is_vchar
#define http1_is_vchar (c) ((unsigned char)(c) >= 0x21 && (unsigned char)(c) <= 0x7E)
Check if byte is a visible (non-control) US-ASCII character (VCHAR).
Parameters
c Byte/character to test (cast to unsigned char internally).
Returns
1 (true) if 0x21 <= c <= 0x7E (printable ASCII excluding controls), 0 otherwise.
Note
VCHAR from RFC 5234 ABNF: visible US-ASCII excluding NUL, controls, DEL.
Used in header field values, reason phrases; excludes SP (separate class).
See also
http1_is_field_vchar() which adds obs-text for header values.
RFC 7230 section 3.2.4 field-value allows VCHAR / SP / HTAB / obs-text.
Definition at line 779 of file SocketHTTP1-private.h.
HTTP2_GOAWAY_HEADER_SIZE
#define HTTP2_GOAWAY_HEADER_SIZE 8
Fixed size of GOAWAY frame header fields (excluding debug data).
8 bytes: last stream ID (4) + error code (4).
See also
RFC 9113 Section 6.8 GOAWAY.
Definition at line 114 of file SocketHTTP2-private.h.
HTTP2_PING_PAYLOAD_SIZE
#define HTTP2_PING_PAYLOAD_SIZE 8
Fixed size of PING frame payload (opaque data).
8 bytes of arbitrary data for round-trip measurement or app use.
See also
RFC 9113 Section 6.7 PING.
Definition at line 105 of file SocketHTTP2-private.h.
HTTP2_SETTING_ENTRY_SIZE
#define HTTP2_SETTING_ENTRY_SIZE 6
Fixed size of a SETTINGS frame parameter entry.
6 bytes: 2-byte identifier + 4-byte value (RFC 9113).
Definition at line 96 of file SocketHTTP2-private.h.
HTTP2_WINDOW_UPDATE_SIZE
#define HTTP2_WINDOW_UPDATE_SIZE 4
Fixed size of WINDOW_UPDATE frame payload (window increment).
4 bytes unsigned integer for flow control window adjustment.
See also
RFC 9113 Section 6.9 WINDOW_UPDATE.
Definition at line 123 of file SocketHTTP2-private.h.
HTTP_STATUS_1XX_MAX
#define HTTP_STATUS_1XX_MAX 199
Maximum 1xx informational status code.
Definition at line 491 of file SocketHTTP.h.
HTTP_STATUS_1XX_MIN
#define HTTP_STATUS_1XX_MIN HTTP_STATUS_CONTINUE
Minimum 1xx informational status code.
Definition at line 485 of file SocketHTTP.h.
HTTP_STATUS_2XX_MAX
#define HTTP_STATUS_2XX_MAX 299
Maximum 2xx successful status code.
Definition at line 503 of file SocketHTTP.h.
HTTP_STATUS_2XX_MIN
#define HTTP_STATUS_2XX_MIN HTTP_STATUS_OK
Minimum 2xx successful status code.
Definition at line 497 of file SocketHTTP.h.
HTTP_STATUS_3XX_MAX
#define HTTP_STATUS_3XX_MAX 399
Maximum 3xx redirection status code.
Definition at line 515 of file SocketHTTP.h.
HTTP_STATUS_3XX_MIN
#define HTTP_STATUS_3XX_MIN HTTP_STATUS_MULTIPLE_CHOICES
Minimum 3xx redirection status code.
Definition at line 509 of file SocketHTTP.h.
HTTP_STATUS_4XX_MAX
#define HTTP_STATUS_4XX_MAX 499
Maximum 4xx client error status code.
Definition at line 527 of file SocketHTTP.h.
HTTP_STATUS_4XX_MIN
#define HTTP_STATUS_4XX_MIN HTTP_STATUS_BAD_REQUEST
Minimum 4xx client error status code.
Definition at line 521 of file SocketHTTP.h.
HTTP_STATUS_5XX_MAX
#define HTTP_STATUS_5XX_MAX 599
Maximum 5xx server error status code.
Note
Extends to 599 for future standard codes.
Definition at line 540 of file SocketHTTP.h.
HTTP_STATUS_5XX_MIN
#define HTTP_STATUS_5XX_MIN HTTP_STATUS_INTERNAL_ERROR
Minimum 5xx server error status code.
Definition at line 533 of file SocketHTTP.h.
HTTP_STATUS_CODE_MAX
#define HTTP_STATUS_CODE_MAX 599
Maximum valid HTTP status code.
Note
Codes above 599 are not standard; extensions may use higher but library limits to 599.
Definition at line 479 of file SocketHTTP.h.
HTTP_STATUS_CODE_MIN
#define HTTP_STATUS_CODE_MIN 100
Boundary constants for HTTP status code validation and categorization.
These defines provide ranges for status code classes (1xx-5xx) and overall valid range (100-599). Used in SocketHTTP_status_valid(), SocketHTTP_status_category(), and internal checks. The SocketHTTP_StatusCode enum defines specific codes; these are for range checks.
Note
Not all codes in 100-599 are standardized; custom codes should use valid range.
See also
SocketHTTP_status_valid() to check if a code is in valid range.
SocketHTTP_status_category() to get category (1-5).
SocketHTTP_StatusCode for enumerated status codes.
Minimum valid HTTP status code.
Note
Codes below 100 are informational or invalid per RFC 9110.
Definition at line 472 of file SocketHTTP.h.
RAISE_HTTPCLIENT_ERROR
#define RAISE_HTTPCLIENT_ERROR (e) SOCKET_RAISE_MODULE_ERROR (SocketHTTPClient, e)
Raise HTTP client exception with detailed error message.
Creates a thread-local copy of the exception with reason from socket_error_buf. Thread-safe: prevents race conditions when multiple threads raise same exception type.
Requires: SOCKET_DECLARE_MODULE_EXCEPTION(HTTPClient) in .c file.
See also
SocketUtil.h for centralized error infrastructure.
docs/ERROR_HANDLING.md for exception patterns.
Definition at line 82 of file SocketHTTPClient-private.h.
SOCKET_HAS_HTTP
#define SOCKET_HAS_HTTP 1
HTTP protocol support flag.
Includes full HTTP/1.1 and HTTP/2 implementation with HPACK header compression, client (SocketHTTPClient) and server (SocketHTTPServer) APIs, WebSocket support.
Set to 1 to enable HTTP features (default), 0 to disable for reduced footprint. Controlled by CMake -DENABLE_HTTP=ON/OFF.
See also
include/http/ for HTTP module headers.
SocketHTTPClient_T for high-level HTTP client.
SocketHTTPServer_T for HTTP server.
SocketWS_T for WebSocket over HTTP.
Definition at line 1242 of file SocketConfig.h.
SOCKET_HAS_WEBSOCKET
#define SOCKET_HAS_WEBSOCKET 1
WebSocket protocol support flag.
Enables WebSocket RFC 6455 implementation with permessage-deflate extension support. Builds on HTTP module for handshake and framing.
Set to 1 to enable WebSocket features (default), 0 to disable. Requires SOCKET_HAS_HTTP=1.
See also
SocketWS_T for WebSocket API.
SocketWS_client_connect() for client connections.
SocketWS_server_accept() for server upgrades.
docs/WEBSOCKET.md for usage guide.
Definition at line 1260 of file SocketConfig.h.
SOCKETHPACK_DEFAULT_TABLE_SIZE
#define SOCKETHPACK_DEFAULT_TABLE_SIZE 4096
Default dynamic table size in bytes (RFC 7541 default).
Used when no explicit table size is configured.
Definition at line 124 of file SocketHPACK.h.
SOCKETHPACK_ENTRY_OVERHEAD
#define SOCKETHPACK_ENTRY_OVERHEAD 32
Overhead bytes per dynamic table entry (RFC 7541 Section 4.1).
32 bytes minimum overhead for name/value storage and indexing.
Definition at line 180 of file SocketHPACK.h.
SOCKETHPACK_MAX_HEADER_LIST_SIZE
#define SOCKETHPACK_MAX_HEADER_LIST_SIZE (64 * 1024)
Maximum total size for decoded header list in bytes.
Definition at line 153 of file SocketHPACK.h.
SOCKETHPACK_MAX_HEADER_SIZE
#define SOCKETHPACK_MAX_HEADER_SIZE (8 * 1024)
Maximum size for individual header (name + value) in bytes.
Definition at line 145 of file SocketHPACK.h.
SOCKETHPACK_MAX_TABLE_SIZE
#define SOCKETHPACK_MAX_TABLE_SIZE (64 * 1024)
Maximum allowable dynamic table size in bytes.
ENFORCEMENT: Table size updates are validated in SocketHPACK_Decoder_decode(). Rejects updates exceeding settings_max_table_size.
See also
SocketHPACK_Decoder_set_table_size()
Definition at line 137 of file SocketHPACK.h.
SOCKETHPACK_MAX_TABLE_UPDATES
#define SOCKETHPACK_MAX_TABLE_UPDATES 2
Maximum allowed dynamic table size updates per header block.
Prevents excessive updates that could be used in attacks.
Definition at line 163 of file SocketHPACK.h.
SOCKETHPACK_STATIC_TABLE_SIZE
#define SOCKETHPACK_STATIC_TABLE_SIZE 61
Size of the static table (RFC 7541 Appendix A).
Contains 61 predefined common header fields.
Definition at line 172 of file SocketHPACK.h.
SOCKETHTTP_DATE_BUFSIZE
#define SOCKETHTTP_DATE_BUFSIZE 30
Recommended buffer size for HTTP-date formatting output.
IMF-fixdate format requires 29 bytes + null terminator = 30 bytes. Use this constant for stack-allocated buffers in SocketHTTP_date_format().
Note
Fixed size; all valid HTTP-dates fit within this.
See also
SocketHTTP_date_format() for formatting time_t to HTTP-date string.
SocketHTTP_date_parse() for parsing HTTP-date strings.
Definition at line 174 of file SocketHTTP.h.
SOCKETHTTP_HEADER_BUCKETS
#define SOCKETHTTP_HEADER_BUCKETS 31
Hash table bucket count for header collections (internal constant).
Fixed prime number (31) providing good distribution for typical HTTP header counts (10-30). Balances low collision rate with minimal memory overhead.
See also
sockethttp_hash_name() for the hashing function used.
Thread Safety\n Yes - compile-time constant.
See also
SocketHTTP_Headers::buckets for the hash table implementation.
Definition at line 46 of file SocketHTTP-private.h.
SOCKETHTTP_HEX_VALUE
#define SOCKETHTTP_HEX_VALUE (c) (sockethttp_hex_value[(unsigned char)(c)])
Extract numeric value from hexadecimal digit character.
Parameters
c ASCII character to convert ('0'-'9', 'a'-'f', 'A'-'F')
Returns
0-15 for valid hex digit, 255 for invalid input.
Constant-time table lookup used in percent-decoding and hex parsing. Invalid characters (non-hex) return 255 to simplify error checking.
See also
sockethttp_hex_value table.
Thread Safety\n Yes - static const array, read-only.
Thread Safety\n Yes - macro, pure function.
See also
SocketHTTP_URI_decode() usage example.
Definition at line 298 of file SocketHTTP-private.h.
SOCKETHTTP_IS_TCHAR
#define SOCKETHTTP_IS_TCHAR (c) (sockethttp_tchar_table[(unsigned char)(c)])
Check if a character is a valid HTTP token character (tchar).
Parameters
c Character to validate (automatically promoted to unsigned char via cast)
Returns
Non-zero if valid tchar per RFC 9110, zero otherwise.
Fast O(1) table lookup used throughout HTTP parsing for validating header field names, values, media type parameters, etc.
See also
sockethttp_tchar_table for the underlying validation table.
Thread Safety\n Yes - macro, pure function.
See also
RFC 9110 5.6 for complete tchar grammar.
Definition at line 231 of file SocketHTTP-private.h.
SOCKETHTTP_IS_UNRESERVED
#define SOCKETHTTP_IS_UNRESERVED (c) (sockethttp_uri_unreserved[(unsigned char)(c)])
Test if a character is URI unreserved (no percent-encoding required).
Parameters
c Character to test (promoted to unsigned char)
Returns
Non-zero if unreserved per RFC 3986, zero otherwise.
Used in URI encoding to skip encoding for safe characters and in validation.
See also
sockethttp_uri_unreserved table.
SocketHTTP_URI_encode() for encoding context.
Thread Safety\n Yes - macro, pure function.
See also
RFC 3986 2.3 unreserved characters.
Definition at line 264 of file SocketHTTP-private.h.
SOCKETHTTP_MAX_HEADER_NAME
#define SOCKETHTTP_MAX_HEADER_NAME 256
Maximum allowed length for HTTP header names, in bytes.
This configurable limit protects against denial-of-service attacks via excessively long header names. The default value of 256 bytes is sufficient for all standard HTTP headers (e.g., "Authorization", "Content-Type") and most custom headers.
Redefine before including SocketHTTP.h to adjust for specific needs, but keep conservative for security. Exceeding this during parsing raises SocketHTTP_Failed.
Note
Header names must also be valid tokens per RFC 9110 (tchar characters only).
See also
SocketHTTP_header_name_valid() for validation function.
SocketHTTP_MAX_HEADER_VALUE for value length limits.
SocketHTTP_MAX_HEADER_SIZE for total headers limit.
Definition at line 94 of file SocketHTTP.h.
SOCKETHTTP_MAX_HEADER_SIZE
#define SOCKETHTTP_MAX_HEADER_SIZE (64 * 1024)
Maximum total size for all HTTP headers combined, in bytes.
Cumulative limit on header block size to mitigate DoS from many/small headers or few/large ones. Default 64 KiB is generous for typical requests but protects servers from abuse. Used in parsing to prevent excessive memory use.
Note
Enforced in header collection; exceeding raises SocketHTTP_Failed in parsers.
See also
SocketHTTP_Headers_count() for number of headers.
SocketHTTP_MAX_HEADERS for maximum count.
Definition at line 129 of file SocketHTTP.h.
SOCKETHTTP_MAX_HEADER_VALUE
#define SOCKETHTTP_MAX_HEADER_VALUE (8 * 1024)
Maximum allowed length for individual HTTP header values, in bytes.
Limits single header values to prevent memory exhaustion or buffer overflows. Default 8 KiB accommodates large values like base64-encoded data in Authorization or cookies. Larger values may indicate attacks; adjust cautiously.
Exceeding this during addition or parsing triggers error or exception.
Note
Values are validated to exclude control characters (CR/LF/NUL) for security.
See also
SocketHTTP_header_value_valid() for validation.
SocketHTTP_MAX_HEADER_NAME for name limits.
SocketHTTP_MAX_HEADERS for count limits.
Definition at line 113 of file SocketHTTP.h.
SOCKETHTTP_MAX_HEADERS
#define SOCKETHTTP_MAX_HEADERS 100
Maximum number of HTTP headers allowed in a collection.
Limits header count to prevent resource exhaustion from header flooding attacks. Default 100 is ample for standard HTTP/1.1 and HTTP/2 requests. Duplicate headers (e.g., multiple Set-Cookie) count separately.
Note
HTTP/2 has separate frame limits; this applies to logical header sets.
See also
SocketHTTP_Headers_T for header collection.
SocketHTTP_MAX_HEADER_SIZE for total size limit.
Definition at line 145 of file SocketHTTP.h.
SOCKETHTTP_MAX_URI_LEN
#define SOCKETHTTP_MAX_URI_LEN (8 * 1024)
Maximum length for URI strings during parsing, in bytes.
Prevents DoS from oversized URIs. Default 8 KiB covers complex queries and paths. Enforced in SocketHTTP_URI_parse(); longer URIs raise URI_PARSE_TOO_LONG.
Note
Does not limit encoded size; decoded may be smaller.
See also
SocketHTTP_URI_parse() for URI parsing.
SocketHTTP_URI_encode() and SocketHTTP_URI_decode() for percent handling.
Definition at line 160 of file SocketHTTP.h.
Typedef Documentation
SocketHTTP_HeaderCallback
typedef int(* SocketHTTP_HeaderCallback) (const char *name, size_t name_len, const char *value, size_t value_len, void *userdata)
Callback function for iterating over HTTP headers in SocketHTTP_Headers_iterate().
Invoked for each header in the collection. Parameters provide name/value with lengths for efficiency. Case-insensitive name matching via hash table in collection.
Parameters
name Header name (null-terminated string, case-preserved).
name_len Length of name (excluding null).
value Header value (null-terminated, may be empty string).
value_len Length of value (excluding null).
userdata User data passed from SocketHTTP_Headers_iterate().
Returns
0 to continue iteration, non-zero to stop early.
Thread Safety\n No - called from caller context.
Note
Callback should not modify collection; undefined behavior.
See also
SocketHTTP_Headers_iterate() for usage.
SocketHTTP_Header for structure with name/value.
Definition at line 818 of file SocketHTTP.h.
SocketHTTPServer_BodyCallback
typedef int(* SocketHTTPServer_BodyCallback) (SocketHTTPServer_Request_T req, const void *chunk, size_t len, int is_final, void *userdata)
Callback for streaming request body data incrementally.
Enables memory-efficient handling of large request bodies (e.g., file uploads) by processing data in chunks as received, without loading the entire body into memory. To use, call SocketHTTPServer_Request_body_stream() in the handler before finishing. The server will then invoke this callback for each chunk parsed from the wire.
Parameters
req Request context (same as handler; use for response setup if needed).
chunk Pointer to body data chunk (valid only during callback; do not store or free).
len Length of the chunk in bytes.
is_final Non-zero if this is the final chunk (end of body), zero otherwise.
userdata User-provided data passed unchanged from SocketHTTPServer_Request_body_stream().
Returns
0 to continue receiving and processing more body chunks, non-zero to abort the request (server sends 400 Bad Request and closes connection).
Note
Chunks may arrive in any size up to internal buffer limits (typically 4-8KB).
For chunked encoding, is_final is set after final zero-length chunk.
Body data is temporary; copy if needed for later use (use request arena).
Thread-safety depends on server configuration; typically called from event thread.
Warning
Aborting mid-body closes the connection immediately; client may retry.
See also
SocketHTTPServer_Request_body_stream() to enable streaming mode.
SocketHTTPServer_Request_body_expected() for expected total length.
SocketHTTPServer_Request_is_chunked() for transfer encoding info.
Definition at line 477 of file SocketHTTPServer.h.
SocketHTTPServer_DrainCallback
typedef void(* SocketHTTPServer_DrainCallback) (SocketHTTPServer_T server, int timed_out, void *userdata)
Callback notified when graceful drain (shutdown) completes.
Invoked by the server when the drain process finishes: either all active connections and requests have completed gracefully, or the timeout expired forcing closure of remaining connections. Useful for cleanup, logging, or signaling other services.
Set via SocketHTTPServer_set_drain_callback() before initiating drain.
Parameters
server The server instance entering STOPPED state.
timed_out Non-zero if drain timed out (remaining connections force-closed), zero if completed gracefully within timeout.
userdata User data provided at callback registration.
Note
Called from the event loop thread during or after drain_poll().
Server is still valid but in STOPPED state; do not start it again.
If timed_out, some requests may have been aborted; check stats for details.
See also
SocketHTTPServer_set_drain_callback() for registration.
SocketHTTPServer_drain() to initiate graceful shutdown.
SocketHTTPServer_drain_wait() for blocking variant.
SocketHTTPServer_state() to query state independently.
Definition at line 541 of file SocketHTTPServer.h.
SocketHTTPServer_Handler
typedef void(* SocketHTTPServer_Handler) (SocketHTTPServer_Request_T req, void *userdata)
Primary request handler callback invoked for each incoming HTTP request.
This is the main entry point for application logic. For each parsed HTTP request, the server calls this callback with the request context. The handler is responsible for:
Inspecting request via accessors: method, path, headers, body.
Setting response: status with SocketHTTPServer_Request_status(), headers with SocketHTTPServer_Request_header().
Providing body: either static with SocketHTTPServer_Request_body_data() or streaming with SocketHTTPServer_Request_begin_stream().
Finalizing with SocketHTTPServer_Request_finish() or SocketHTTPServer_Request_end_stream().
The req context is valid only during callback execution. Do not store pointers to it or its contents beyond the callback; they may be invalidated or freed. All allocations use the per-request arena available via SocketHTTPServer_Request_arena().
Parameters
req Request context containing parsed request data and response builders.
userdata Arbitrary user data set via SocketHTTPServer_set_handler().
Thread Safety\n No - invoked from server's event loop thread (SocketPoll integration).
Server instances should not be shared across threads without external sync.
Note
For WebSocket upgrades, check SocketHTTPServer_Request_is_websocket() and use SocketHTTPServer_Request_upgrade_websocket() instead of standard response.
For HTTP/2 push, use SocketHTTPServer_Request_push() if supported.
See also
SocketHTTPServer_set_handler() to register this callback.
SocketHTTPServer_Request_T for full request/response API.
SocketHTTP_Headers_T for header manipulation.
HTTP Module Group for protocol details.
Definition at line 446 of file SocketHTTPServer.h.
SocketHTTPServer_Validator
typedef int(* SocketHTTPServer_Validator) (SocketHTTPServer_Request_T req, int *reject_status, void *userdata)
Middleware callback for request validation and authentication.
Executed before the main handler for every request. Ideal for common checks like authentication (e.g., API keys, JWT), authorization, rate limiting, CORS preflight, or input sanitization. Can short-circuit and reject invalid requests early, avoiding handler invocation and resource waste.
Available data: method, path, query, headers (body not yet parsed/available). To reject, set *reject_status to an HTTP error code (e.g., 401 Unauthorized, 403 Forbidden, 429 Too Many Requests) and return 0.
Parameters
req Request context with method, path, headers accessible.
reject_status Output: HTTP status code for rejection response. Ignored if allowing request (return non-zero). Server sends basic error response with this status.
userdata User data set via SocketHTTPServer_set_validator().
Returns
Non-zero (true) to approve request and proceed to handler callback, 0 (false) to reject with the status in *reject_status (connection may close).
Note
Validator runs after initial parsing but before body handling; efficient for headers-only checks.
Multiple validators can be chained externally if needed, but server supports only one.
For per-endpoint validation, implement in handler or use rate limiting API.
Thread-safety: Called from event thread; ensure validator is reentrant if sharing state.
See also
SocketHTTPServer_set_validator() to register.
SocketHTTPServer_Request_headers() for header access in validator.
SocketHTTP_status_reason() for status code phrases.
Utilities Group for rate limiting integration.
Definition at line 513 of file SocketHTTPServer.h.
Enumeration Type Documentation
HTTP1_InternalState
enum HTTP1_InternalState
Low-level internal parser states for the DFA-based HTTP/1.1 parser.
These states drive the table-driven deterministic finite automaton (DFA) for efficient, single-pass parsing of HTTP/1.1 messages including request/response lines, headers, chunked bodies, and trailers.
Parsing flows:
Request: HTTP1_PS_START HTTP1_PS_METHOD HTTP1_PS_SP_AFTER_METHOD HTTP1_PS_URI HTTP1_PS_SP_AFTER_URI version states HTTP1_PS_LINE_CR HTTP1_PS_LINE_LF
Response: HTTP1_PS_START version states HTTP1_PS_STATUS_CODE HTTP1_PS_SP_AFTER_STATUS HTTP1_PS_REASON HTTP1_PS_LINE_CR HTTP1_PS_LINE_LF
Headers loop: HTTP1_PS_HEADER_START HTTP1_PS_HEADER_NAME HTTP1_PS_HEADER_COLON HTTP1_PS_HEADER_VALUE HTTP1_PS_HEADER_CR HTTP1_PS_HEADER_LF (repeat until HTTP1_PS_HEADERS_END_LF)
Chunked body: HTTP1_PS_CHUNK_SIZE states HTTP1_PS_CHUNK_DATA HTTP1_PS_CHUNK_DATA_CR HTTP1_PS_CHUNK_DATA_LF
Trailers: Similar to headers after final chunk.
Individual state descriptions provided in enum values.
See also
http1_char_class for character classification used in transitions.
http1_req_state, http1_resp_state for state transition tables.
http1_req_action, http1_resp_action for actions triggered by transitions.
RFC 7230 sections 3 (message format) and 4 (request/response) for grammar.
SocketHTTP1_Parser_execute() for how states are advanced.
SocketHTTP1.h for public parser interface.
HTTP/1.1 Module for group documentation.
Enumerator
HTTP1_PS_START
HTTP1_PS_METHOD
HTTP1_PS_SP_AFTER_METHOD
HTTP1_PS_URI
HTTP1_PS_SP_AFTER_URI
HTTP1_PS_STATUS_CODE
HTTP1_PS_SP_AFTER_STATUS
HTTP1_PS_REASON
HTTP1_PS_VERSION_H
HTTP1_PS_VERSION_T1
HTTP1_PS_VERSION_T2
HTTP1_PS_VERSION_P
HTTP1_PS_VERSION_SLASH
HTTP1_PS_VERSION_MAJOR
HTTP1_PS_VERSION_DOT
HTTP1_PS_VERSION_MINOR
HTTP1_PS_LINE_CR
HTTP1_PS_LINE_LF
HTTP1_PS_HEADER_START
HTTP1_PS_HEADER_NAME
HTTP1_PS_HEADER_COLON
HTTP1_PS_HEADER_VALUE
HTTP1_PS_HEADER_VALUE_OWS
HTTP1_PS_HEADER_CR
HTTP1_PS_HEADER_LF
HTTP1_PS_HEADERS_END_LF
HTTP1_PS_BODY_IDENTITY
HTTP1_PS_BODY_UNTIL_CLOSE
HTTP1_PS_CHUNK_SIZE
HTTP1_PS_CHUNK_SIZE_EXT
HTTP1_PS_CHUNK_SIZE_CR
HTTP1_PS_CHUNK_SIZE_LF
HTTP1_PS_CHUNK_DATA
HTTP1_PS_CHUNK_DATA_CR
HTTP1_PS_CHUNK_DATA_LF
HTTP1_PS_TRAILER_START
HTTP1_PS_TRAILER_NAME
HTTP1_PS_TRAILER_COLON
HTTP1_PS_TRAILER_VALUE
HTTP1_PS_TRAILER_CR
HTTP1_PS_TRAILER_LF
HTTP1_PS_TRAILERS_END_LF
HTTP1_PS_COMPLETE
HTTP1_PS_ERROR
HTTP1_NUM_STATES
Definition at line 219 of file SocketHTTP1-private.h.
HTTPAsyncState
enum HTTPAsyncState
States for asynchronous HTTP requests.
Tracks lifecycle from idle to complete, failed, or cancelled.
Enumerator
ASYNC_STATE_IDLE
ASYNC_STATE_CONNECTING
ASYNC_STATE_SENDING
ASYNC_STATE_RECEIVING_HEADERS
ASYNC_STATE_RECEIVING_BODY
ASYNC_STATE_COMPLETE
ASYNC_STATE_FAILED
ASYNC_STATE_CANCELLED
Definition at line 271 of file SocketHTTPClient-private.h.
ServerConnState
enum ServerConnState
Internal states tracking the processing pipeline of a server connection.
State machine transitions:
CONN_STATE_READING_REQUEST CONN_STATE_READING_BODY (if content-length/chunked) CONN_STATE_HANDLING
CONN_STATE_HANDLING CONN_STATE_STREAMING_RESPONSE (if streaming response) CONN_STATE_SENDING_RESPONSE
CONN_STATE_SENDING_RESPONSE CONN_STATE_CLOSED or back to CONN_STATE_READING_REQUEST (keep-alive)
Used for timeout enforcement, logging, and resource cleanup.
See also
ServerConnection::state
SocketHTTPServer_Config for timeout configurations per state.
Enumerator
CONN_STATE_READING_REQUEST
CONN_STATE_READING_BODY
CONN_STATE_HANDLING
CONN_STATE_STREAMING_RESPONSE
CONN_STATE_SENDING_RESPONSE
CONN_STATE_CLOSED
Definition at line 76 of file SocketHTTPServer-private.h.
SocketHPACK_Result
enum SocketHPACK_Result
HPACK operation result codes.
Enumerator
HPACK_OK
Success
HPACK_INCOMPLETE
Need more data
HPACK_ERROR
Generic error
HPACK_ERROR_INVALID_INDEX
Index out of range
HPACK_ERROR_HUFFMAN
Huffman decoding error
HPACK_ERROR_INTEGER
Integer overflow
HPACK_ERROR_TABLE_SIZE
Dynamic table size update invalid
HPACK_ERROR_HEADER_SIZE
Individual header too large
HPACK_ERROR_LIST_SIZE
Total header list too large
HPACK_ERROR_BOMB
HPACK bomb detected
Definition at line 209 of file SocketHPACK.h.
SocketHTTP2_ConnState
enum SocketHTTP2_ConnState
HTTP/2 connection lifecycle states.
Defines the finite state machine states for HTTP/2 connection establishment, settings exchange, operational phase, GOAWAY handling, and closure.
See also
SocketHTTP2_Conn::state for storage in connection struct.
RFC 9113 Section 5.1 for connection preface and state transitions.
Enumerator
HTTP2_CONN_STATE_INIT
Initial state
HTTP2_CONN_STATE_PREFACE_SENT
Client preface sent
HTTP2_CONN_STATE_PREFACE_RECV
Server preface received
HTTP2_CONN_STATE_SETTINGS_SENT
SETTINGS sent
HTTP2_CONN_STATE_SETTINGS_RECV
SETTINGS received
HTTP2_CONN_STATE_READY
Connection ready
HTTP2_CONN_STATE_GOAWAY_SENT
GOAWAY sent
HTTP2_CONN_STATE_GOAWAY_RECV
GOAWAY received
HTTP2_CONN_STATE_CLOSED
Connection closed
Definition at line 141 of file SocketHTTP2-private.h.
SocketHTTP_Coding
enum SocketHTTP_Coding
Common HTTP transfer encodings and content codings per RFC 9110.
Used in Transfer-Encoding and Content-Encoding headers. Supports standard compression algorithms and chunked for streaming. HTTP_CODING_IDENTITY is no-encoding (default).
See also
SocketHTTP_coding_parse() to parse from header value.
SocketHTTP_coding_name() to get string name.
Enumerator
HTTP_CODING_IDENTITY
No encoding (identity/default)
HTTP_CODING_CHUNKED
Chunked transfer encoding for unknown length
HTTP_CODING_GZIP
Gzip compression (RFC 1952)
HTTP_CODING_DEFLATE
Deflate compression (zlib, RFC 1950/1951)
HTTP_CODING_COMPRESS
Unix compress (LZW, rarely used/obsolete)
HTTP_CODING_BR
Brotli compression (RFC 7932)
HTTP_CODING_UNKNOWN
Unrecognized or unsupported encoding
Definition at line 1182 of file SocketHTTP.h.
SocketHTTP_Method
enum SocketHTTP_Method
Standard HTTP request methods as defined in RFC 9110 and extensions.
Includes all methods from RFC 9110 Section 9 plus PATCH (RFC 5789). HTTP_METHOD_UNKNOWN indicates an unrecognized or custom method.
See also
SocketHTTP_method_name() to get canonical string name.
SocketHTTP_method_parse() to parse method from request line.
SocketHTTP_method_properties() for semantic properties like safety and idempotency.
SocketHTTP_method_valid() to validate custom method tokens per RFC 9110 token rules.
Enumerator
HTTP_METHOD_GET
RFC 9110 Section 9.3.1 - Safe, idempotent, cacheable; retrieves resource
HTTP_METHOD_HEAD
RFC 9110 Section 9.3.2 - Like GET but response has no body; used for metadata
HTTP_METHOD_POST
RFC 9110 Section 9.3.3 - Not safe or idempotent; creates/submits data
HTTP_METHOD_PUT
RFC 9110 Section 9.3.4 - Idempotent; creates or replaces resource at URI
HTTP_METHOD_DELETE
RFC 9110 Section 9.3.5 - Idempotent; requests deletion of resource
HTTP_METHOD_CONNECT
RFC 9110 Section 9.3.6 - Establishes tunnel to target host; used by proxies
HTTP_METHOD_OPTIONS
RFC 9110 Section 9.3.7 - Safe; describes communication options for target resource
HTTP_METHOD_TRACE
RFC 9110 Section 9.3.8 - Safe, idempotent; performs test loop-back for diagnostics
HTTP_METHOD_PATCH
RFC 5789 - Applies partial modifications to resource; not always idempotent
HTTP_METHOD_UNKNOWN
Unrecognized or extension method
Definition at line 290 of file SocketHTTP.h.
SocketHTTP_StatusCategory
enum SocketHTTP_StatusCategory
Categories of HTTP status codes for quick classification.
Maps to first digit of status code (1-5). Used for error handling, logging, and conditional logic.
See also
SocketHTTP_status_category() to get category from code.
Enumerator
HTTP_STATUS_INFORMATIONAL
1xx - Informational responses
HTTP_STATUS_SUCCESSFUL
2xx - Success responses
HTTP_STATUS_REDIRECTION
3xx - Redirection responses
HTTP_STATUS_CLIENT_ERROR
4xx - Client errors
HTTP_STATUS_SERVER_ERROR
5xx - Server errors
Definition at line 550 of file SocketHTTP.h.
SocketHTTP_StatusCode
enum SocketHTTP_StatusCode
HTTP status codes as defined in RFC 9110 Section 15 and common extensions.
Includes standard 1xx-5xx codes plus WebDAV (RFC 4918), HTTP/2 extensions, and others. Use SocketHTTP_status_valid() to check range, SocketHTTP_status_category() for class, and SocketHTTP_status_reason() for reason phrase.
See also
SocketHTTP_status_reason() to get standardized reason phrase.
SocketHTTP_status_category() to get category (1-5).
SocketHTTP_status_valid() to validate code is in 100-599 range.
Enumerator
HTTP_STATUS_CONTINUE
Continue with request
HTTP_STATUS_SWITCHING_PROTOCOLS
Server agrees to upgrade protocol
HTTP_STATUS_PROCESSING
RFC 2518 WebDAV - Processing request
HTTP_STATUS_EARLY_HINTS
RFC 8297 - Early hints for resource links
HTTP_STATUS_OK
Standard success
HTTP_STATUS_CREATED
Resource created
HTTP_STATUS_ACCEPTED
Accepted for processing
HTTP_STATUS_NON_AUTHORITATIVE
Non-authoritative information
HTTP_STATUS_NO_CONTENT
Success, no content
HTTP_STATUS_RESET_CONTENT
Reset content (user agent refresh)
HTTP_STATUS_PARTIAL_CONTENT
Partial content (range request)
HTTP_STATUS_MULTI_STATUS
RFC 4918 WebDAV - Multiple statuses
HTTP_STATUS_ALREADY_REPORTED
RFC 5842 WebDAV - Avoid infinite loops
HTTP_STATUS_IM_USED
RFC 3229 Delta encoding - Instance manipulated
HTTP_STATUS_MULTIPLE_CHOICES
Multiple resource representations
HTTP_STATUS_MOVED_PERMANENTLY
Permanent redirect
HTTP_STATUS_FOUND
Temporary redirect
HTTP_STATUS_SEE_OTHER
See other location
HTTP_STATUS_NOT_MODIFIED
Not modified (conditional request)
HTTP_STATUS_USE_PROXY
Deprecated - Use proxy (absolute URI)
HTTP_STATUS_TEMPORARY_REDIRECT
Temporary redirect, preserve method
HTTP_STATUS_PERMANENT_REDIRECT
RFC 7238 - Permanent redirect, preserve method
HTTP_STATUS_BAD_REQUEST
Invalid request syntax
HTTP_STATUS_UNAUTHORIZED
Authentication required
HTTP_STATUS_PAYMENT_REQUIRED
Payment required (reserved)
HTTP_STATUS_FORBIDDEN
Forbidden
HTTP_STATUS_NOT_FOUND
Resource not found
HTTP_STATUS_METHOD_NOT_ALLOWED
Method not allowed for resource
HTTP_STATUS_NOT_ACCEPTABLE
No acceptable representation
HTTP_STATUS_PROXY_AUTH_REQUIRED
Proxy authentication required
HTTP_STATUS_REQUEST_TIMEOUT
Request timeout
HTTP_STATUS_CONFLICT
Resource conflict
HTTP_STATUS_GONE
Resource permanently gone
HTTP_STATUS_LENGTH_REQUIRED
Content-Length required
HTTP_STATUS_PRECONDITION_FAILED
Precondition failed
HTTP_STATUS_CONTENT_TOO_LARGE
Payload too large
HTTP_STATUS_URI_TOO_LONG
URI too long
HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE
Unsupported media type
HTTP_STATUS_RANGE_NOT_SATISFIABLE
Range not satisfiable
HTTP_STATUS_EXPECTATION_FAILED
Expectation failed
HTTP_STATUS_IM_A_TEAPOT
RFC 2324 - I'm a teapot (humorous)
HTTP_STATUS_MISDIRECTED_REQUEST
Mis-directed request (HTTP/2+)
HTTP_STATUS_UNPROCESSABLE_CONTENT
Unprocessable entity (WebDAV)
HTTP_STATUS_LOCKED
RFC 4918 WebDAV - Resource locked
HTTP_STATUS_FAILED_DEPENDENCY
RFC 4918 WebDAV - Dependency failed
HTTP_STATUS_TOO_EARLY
RFC 8470 - Too early (anti-replay)
HTTP_STATUS_UPGRADE_REQUIRED
Upgrade required (e.g., TLS)
HTTP_STATUS_PRECONDITION_REQUIRED
RFC 6585 - Precondition required
HTTP_STATUS_TOO_MANY_REQUESTS
RFC 6585 - Rate limiting
HTTP_STATUS_HEADER_TOO_LARGE
RFC 6585 - Header fields too large
HTTP_STATUS_UNAVAILABLE_LEGAL
RFC 7725 - Unavailable for legal reasons
HTTP_STATUS_INTERNAL_ERROR
Internal server error
HTTP_STATUS_NOT_IMPLEMENTED
Not implemented
HTTP_STATUS_BAD_GATEWAY
Bad gateway
HTTP_STATUS_SERVICE_UNAVAILABLE
Service unavailable (maintenance)
HTTP_STATUS_GATEWAY_TIMEOUT
Gateway timeout
HTTP_STATUS_VERSION_NOT_SUPPORTED
HTTP version not supported
HTTP_STATUS_VARIANT_ALSO_NEGOTIATES
RFC 2295 - Variant also negotiates
HTTP_STATUS_INSUFFICIENT_STORAGE
RFC 4918 WebDAV - Insufficient storage
HTTP_STATUS_LOOP_DETECTED
RFC 5842 WebDAV - Loop detected
HTTP_STATUS_NOT_EXTENDED
RFC 2774 - Not extended
HTTP_STATUS_NETWORK_AUTH_REQUIRED
RFC 6585 - Network authentication required
Definition at line 378 of file SocketHTTP.h.
SocketHTTP_URIResult
enum SocketHTTP_URIResult
Result codes from URI parsing and related operations.
Indicates success or specific failure mode during URI parsing. Use SocketHTTP_URI_result_string() to get human-readable description.
See also
SocketHTTP_URI_parse() which returns one of these codes.
SocketHTTP_URI_result_string() for string representation.
Enumerator
URI_PARSE_OK
Successful parse
URI_PARSE_ERROR
Generic syntax or validation error
URI_PARSE_INVALID_SCHEME
Scheme contains invalid characters or empty
URI_PARSE_INVALID_HOST
Host invalid: empty, bad characters, or malformed IPv6
URI_PARSE_INVALID_PORT
Port not numeric or out of range (0-65535)
URI_PARSE_INVALID_PATH
Path contains disallowed characters (per RFC 3986)
URI_PARSE_INVALID_QUERY
Query contains disallowed characters
URI_PARSE_TOO_LONG
URI length exceeds SOCKETHTTP_MAX_URI_LEN limit
Definition at line 915 of file SocketHTTP.h.
SocketHTTP_Version
enum SocketHTTP_Version
HTTP protocol versions supported by the library.
Enum values are major version * 10 + minor version for easy comparison (e.g., 11 for HTTP/1.1). Supports HTTP/0.9 to HTTP/3 for compatibility and future-proofing.
See also
SocketHTTP_version_string() to get the string representation (e.g., "HTTP/1.1").
SocketHTTP_version_parse() to parse version from string.
Enumerator
HTTP_VERSION_0_9
HTTP/0.9 (simple, no headers)
HTTP_VERSION_1_0
HTTP/1.0
HTTP_VERSION_1_1
HTTP/1.1
HTTP_VERSION_2
HTTP/2
HTTP_VERSION_3
HTTP/3 (future)
Definition at line 245 of file SocketHTTP.h.
SocketHTTPServer_State
enum SocketHTTPServer_State
Server lifecycle states for monitoring server operation and graceful shutdown.
Enum values indicate the current phase of the server lifecycle, particularly during drain operations for graceful shutdown.
See also
SocketHTTPServer_state()
SocketHTTPServer_drain()
Enumerator
HTTPSERVER_STATE_RUNNING
Normal operation
HTTPSERVER_STATE_DRAINING
Draining - finishing existing requests
HTTPSERVER_STATE_STOPPED
Stopped - all requests complete
Definition at line 281 of file SocketHTTPServer.h.
URIParserState
enum URIParserState
Internal states for DFA-based URI parser (RFC 3986 compliant).
State machine states used by SocketHTTP_URI_parse() for parsing URI components: scheme://[userinfo@]host[:port]/path?query::fragment
Handles generic syntax including IPv6 literals, percent-encoding, and reserved chars. Invalid transitions lead to SocketHTTP_InvalidURI exception.
See also
SocketHTTP_URI_parse() public API.
SocketHTTP_URI for parsed result structure.
docs/HTTP.md for URI handling in HTTP context.
Enumerator
URI_STATE_START
URI_STATE_SCHEME
URI_STATE_SCHEME_COLON
URI_STATE_AUTHORITY_START
URI_STATE_AUTHORITY
URI_STATE_HOST
URI_STATE_HOST_IPV6
URI_STATE_PORT
URI_STATE_PATH
URI_STATE_QUERY
URI_STATE_FRAGMENT
Definition at line 178 of file SocketHTTP-private.h.
Function Documentation
clear_response_for_retry()
void clear_response_for_retry (SocketHTTP_Response * response) extern
Clear HTTP response for retry, preserving useful fields.
Resets body buffer, status, headers for new request/response cycle. Keeps connection info if keep-alive. Used before retrying same connection.
Parameters
response The response struct to clear.
Exceptions
None.
Thread Safety\n Conditional - no locks, caller synchronize.
See also
SocketHTTP_Response for fields reset.
httpclient_clear_response_for_retry() for client-specific.
http1_tokenbuf_append()
static int http1_tokenbuf_append (HTTP1_TokenBuf * buf, Arena_T arena, char c, size_t max_size) inline static
Append a single character to the token buffer, growing capacity if necessary.
Parameters
buf The HTTP1_TokenBuf to append to (must be initialized).
arena Arena_T for reallocating larger buffer if full.
c The character (char) to append to buf->data[buf->len++].
max_size Absolute maximum len allowed (enforced before append and growth).
Returns
0 on success (char appended, len increased), -1 if len would exceed max_size or Arena_alloc fails.
Note
If buf->len == buf->capacity, doubles capacity (capped at max_size) and copies data.
Does not null-terminate; call http1_tokenbuf_terminate() after completion.
Exceptions
Arena_Failed via Arena_alloc() during growth.
See also
Arena_alloc() for reallocation details.
http1_tokenbuf_terminate() to finalize string.
SocketHTTP1_Config for parser-wide size limits (this is per-call cap).
Definition at line 630 of file SocketHTTP1-private.h.
References Arena_alloc(), HTTP1_TokenBuf::capacity, HTTP1_TokenBuf::data, and HTTP1_TokenBuf::len.
http1_tokenbuf_init()
static int http1_tokenbuf_init (HTTP1_TokenBuf * buf, Arena_T arena, size_t initial_capacity) inline static
Initialize HTTP1_TokenBuf, allocating initial buffer from arena.
Parameters
buf Pointer to HTTP1_TokenBuf structure to initialize (overwritten).
arena Arena_T from which to allocate buf->data.
initial_capacity Initial size (in bytes) for the data buffer.
Returns
0 on success (buf ready for use), -1 on allocation failure.
Note
Sets buf->len = 0, buf->capacity = initial_capacity.
Does not zero the buffer contents; undefined until first append.
Exceptions
Arena_Failed if Arena_alloc() fails (via exception handling).
See also
Arena_alloc() invoked internally with file/line tracking.
HTTP1_TokenBuf for structure fields.
http1_tokenbuf_reset() if needing to clear after init (though len=0).
http1_tokenbuf_append() for first data addition.
Definition at line 585 of file SocketHTTP1-private.h.
References Arena_alloc(), HTTP1_TokenBuf::capacity, HTTP1_TokenBuf::data, and HTTP1_TokenBuf::len.
http1_tokenbuf_reset()
static void http1_tokenbuf_reset (HTTP1_TokenBuf * buf) inline static
Reset token buffer to empty (len=0) without deallocating memory or changing capacity.
Parameters
buf Pointer to initialized HTTP1_TokenBuf to reset.
Note
data and capacity unchanged; safe to call repeatedly for reuse.
Previous data remains in buffer until overwritten; use secureclear if sensitive.
See also
http1_tokenbuf_init() for initial setup.
http1_tokenbuf_append() to start adding new data after reset.
HTTP1_TokenBuf::len for the reset field.
Definition at line 608 of file SocketHTTP1-private.h.
References HTTP1_TokenBuf::len.
http1_tokenbuf_terminate()
static char * http1_tokenbuf_terminate (HTTP1_TokenBuf * buf, Arena_T arena, size_t max_size) inline static
Null-terminate the token buffer and return pointer to the string.
Parameters
buf The HTTP1_TokenBuf to terminate (adds '\0' at buf->len).
arena Arena_T for possible reallocation if no space for null terminator.
max_size Maximum allowed len INCLUDING the null terminator (buf->len + 1 <= max_size).
Returns
Pointer to buf->data (now null-terminated string) on success, NULL if reallocation fails or too large.
Note
If buf->len < buf->capacity, simply sets data[len] = '\0' without realloc.
If realloc needed, allocates buf->len + 1, copies data, updates buf->data/capacity; old data invalid.
Returned pointer valid until next append/reset/growth; do not free.
Exceptions
Arena_Failed via Arena_alloc() if growth required and fails.
See also
Arena_alloc() for reallocation.
http1_tokenbuf_append() which may invalidate previous terminate result.
SocketHTTP1_Config for overall size limits.
Definition at line 673 of file SocketHTTP1-private.h.
References Arena_alloc(), HTTP1_TokenBuf::capacity, HTTP1_TokenBuf::data, and HTTP1_TokenBuf::len.
http2_decode_headers()
int http2_decode_headers (SocketHTTP2_Conn_T conn, SocketHTTP2_Stream_T stream, const unsigned char * block, size_t len) extern
Decode HPACK-compressed header block into stream headers/trailers.
Uses connection's SocketHPACK_Decoder_T to decompress block, validating against max header list size setting. Stores decoded SocketHPACK_Header in stream's headers[] or trailers[] array, handling pseudo-headers order and duplicates. Supports CONTINUATION by appending to pending block if in progress.
Parameters
conn The HTTP/2 connection with decoder context.
stream The target stream for storing decoded headers (non-NULL).
block Compressed HPACK header block bytes.
len Length of block.
Returns
0 on successful decoding and storage, -1 on HPACK error or limits exceeded.
Precondition
Decoder initialized; stream expecting headers (HEADERS/PUSH_PROMISE frame).
Exceptions
SocketHTTP2_ProtocolError on decompression failure or invalid headers.
See also
SocketHPACK_Decoder_T::decode for low-level HPACK.
SocketHTTP2_Stream::headers and ::trailers for storage.
RFC 9114 HPACK Section 4 Header Block Decoding.
http2_emit_conn_event()
void http2_emit_conn_event (SocketHTTP2_Conn_T conn, int event) extern
Invoke registered connection event callback for notifications.
Calls the connection's conn_callback function if registered (non-null), passing the connection context, the event type (e.g., HTTP2_EVENT_SETTINGS_ACK, HTTP2_EVENT_PING_ACK, HTTP2_EVENT_GOAWAY_RECEIVED, HTTP2_EVENT_CONN_CLOSED), and the associated userdata. Includes null check on conn to safely skip if invalid. Emitted internally after significant connection-level events like settings negotiation complete, ping acknowledgments, GOAWAY receipt, or connection closure/ready states, allowing user code to monitor health, adjust configuration, or initiate failover. Synchronous direct call; no queuing.
Parameters
conn The HTTP/2 connection containing the callback registration (null-safe).
event Event identifier from HTTP2_EVENT_* constants (connection-specific).
Note
Immediate execution; user callback should not destroy the connection.
Fire-and-forget; callback return ignored.
Thread-unsafe: Direct access; protect with locks in concurrent use.
See also
SocketHTTP2_Conn::conn_callback and ::conn_callback_data for registration.
SocketHTTP2_ConnCallback typedef in SocketHTTP2.h for function signature.
http2_emit_stream_event() for stream-specific events.
Examples: emitted in http2_process_settings(), http2_process_ping(), http2_process_goaway().
http2_emit_stream_event()
void http2_emit_stream_event (SocketHTTP2_Conn_T conn, SocketHTTP2_Stream_T stream, int event) extern
Invoke registered stream event callback for notifications.
Calls the connection's stream_callback function if registered (non-null), passing the connection context, the affected stream, the specific event type (e.g., HTTP2_EVENT_HEADERS_RECEIVED, HTTP2_EVENT_DATA_RECEIVED, HTTP2_EVENT_STREAM_RESET, HTTP2_EVENT_WINDOW_UPDATE), and the associated userdata. Includes null checks on conn and stream parameters to safely skip invocation if invalid. Emitted internally after key stream lifecycle events like header decoding complete, data buffering, flow control updates, or error conditions, enabling user code to react (e.g., parse headers, forward data, retry logic). Synchronous direct call; does not queue events.
Parameters
conn The HTTP/2 connection containing the callback registration (null-safe).
stream The stream associated with the event (null-safe).
event Event identifier from HTTP2_EVENT_* constants.
Note
Callback execution is immediate; user must avoid modifying conn/stream destructively.
No return value from callback; fire-and-forget notification.
Thread-unsafe: Direct state access; serialize if multi-threaded.
See also
SocketHTTP2_Conn::stream_callback and ::stream_callback_data for registration.
SocketHTTP2_StreamCallback typedef in SocketHTTP2.h for function signature.
http2_emit_conn_event() counterpart for connection events.
Usage in frame processors like http2_process_headers(), http2_process_data().
http2_encode_headers()
ssize_t http2_encode_headers (SocketHTTP2_Conn_T conn, const SocketHPACK_Header * headers, size_t count, unsigned char * output, size_t output_size) extern
Encode array of headers into HPACK-compressed block for transmission.
Utilizes connection's SocketHPACK_Encoder_T to compress headers, applying dynamic table updates, huffman coding where beneficial, and size limits. Ensures pseudo- headers first, validates against peer MAX_HEADER_LIST_SIZE. Produces block for HEADERS, PUSH_PROMISE, or CONTINUATION frames.
Parameters
conn The HTTP/2 connection with encoder context.
headers Array of SocketHPACK_Header to encode (non-NULL).
count Number of headers in array (>0).
output Buffer to write compressed block (non-NULL).
output_size Available space in output (>= header block size).
Returns
Number of bytes written to output, or -1 on compression failure or overflow.
Precondition
Encoder initialized via settings.
Exceptions
SocketHTTP2_ProtocolError if headers violate encoding rules (e.g., size).
See also
SocketHPACK_Encoder_T::encode for core logic.
http2_frame_send() to frame and queue the block.
RFC 9114 HPACK Section 3 Header Block Encoding and Section 6. Huffman Coding.
http2_flow_adjust_window()
int http2_flow_adjust_window (int32_t * window, int32_t delta) extern
Adjust flow control window by signed delta, typically from SETTINGS update.
Safely modifies a 32-bit signed window size, preventing underflow (negative) or overflow beyond INT32_MAX. Used when peer's INITIAL_WINDOW_SIZE setting change requires updating connection and all active stream windows.
Parameters
window Pointer to int32_t window value to modify (non-NULL).
delta Signed integer delta (positive increase, negative decrease).
Returns
0 on successful adjustment, -1 if delta would cause invalid state.
Note
Logs debug info on clamping; may trigger flow control errors if extreme.
See also
http2_process_settings() for applying INITIAL_WINDOW_SIZE changes.
Thread Safety\n Yes - modifies only the caller-provided window value via pointer; no shared state or connection access, safe for concurrent calls on distinct windows
Complexity\n O(1) - simple arithmetic adjustment and bounds check
// Adjust stream window after SETTINGS change
int32_t stream_window = get_initial_window();
int32_t delta = new_setting - old_setting;
if (http2_flow_adjust_window(&stream_window, delta) == 0) {
    // Apply to all active streams
    for each stream {
        stream->send_window += delta;  // Already validated per-stream
    }
    conn->initial_send_window = new_setting;
} else {
    // Log clamping or error
    SOCKET_LOG_WARN_MSG("Window adjustment failed");
}
See also
RFC 9113 Section 6.5.2 SETTINGS and Section 6.9.2 Flow Control Windows for adjustment triggers.
http2_flow_available_send()
int32_t http2_flow_available_send (const SocketHTTP2_Conn_T conn, const SocketHTTP2_Stream_T stream) extern
Get available send window for HTTP/2 connection or stream.
Computes the minimum available send window between the connection-level and stream-level windows, clamped to >= 0. Performs validation to ensure the provided stream (if any) belongs to the connection.
Parameters
conn The HTTP/2 connection (const, non-NULL).
stream The stream (const, may be NULL for connection window only).
Returns
Number of bytes available in send window (>=0), or negative error code.
Note
Thread-safe: Yes - read-only access to internal state.
Exceptions
SocketHTTP2_FlowControlError If stream does not belong to connection.
See also
http2_flow_consume_send() to reduce the send window.
http2_flow_update_send() to increase the send window via WINDOW_UPDATE.
http2_flow_consume_recv()
int http2_flow_consume_recv (SocketHTTP2_Conn_T conn, SocketHTTP2_Stream_T stream, size_t bytes) extern
Deduct bytes from receive flow control windows (connection and stream).
Reduces recv_window on stream (if provided) and connection level by bytes. Validates against current available; atomic update to prevent race. Called after processing received DATA payload to account for buffered bytes.
Parameters
conn The HTTP/2 connection (non-NULL).
stream The stream (NULL for connection-level only).
bytes Positive count of bytes to consume from windows.
Returns
0 if windows sufficient and deducted, -1 otherwise (no change made).
Note
Triggers PROTOCOL_ERROR GOAWAY if persistent violation detected.
Exceptions
SocketHTTP2_FlowControlError on window underflow attempt.
See also
http2_flow_update_recv() to increase receive window via WINDOW_UPDATE ack.
RFC 9113 Section 6.9.1 Flow Control Principles.
http2_flow_consume_send()
int http2_flow_consume_send (SocketHTTP2_Conn_T conn, SocketHTTP2_Stream_T stream, size_t bytes) extern
Deduct bytes from send flow control windows prior to frame transmission.
Subtracts from stream and connection send_windows before adding DATA to send buffer. Validates available via http2_flow_available_send(); atomic to avoid races in multi-thread. Used in http2_frame_send for DATA frames to enforce flow control.
Parameters
conn The HTTP/2 connection (non-NULL).
stream The stream (NULL for connection headers/priority etc.).
bytes Number of bytes to consume for sending (>0).
Returns
0 if windows allow and deducted, -1 if insufficient (no deduction).
Note
Send blocked until window replenished by peer WINDOW_UPDATE.
Exceptions
SocketHTTP2_FlowControlError if violation would occur.
See also
http2_flow_available_send() for pre-check.
http2_flow_update_send() for peer window increase.
RFC 9113 Section 6.9.2 Flow Control for sending.
http2_flow_update_recv()
int http2_flow_update_recv (SocketHTTP2_Conn_T conn, SocketHTTP2_Stream_T stream, uint32_t increment) extern
Increase receive flow control window after data consumption.
Adds increment to connection recv_window and stream recv_window (if stream). Clamps to INT32_MAX; sends WINDOW_UPDATE frame if increment >0 and thresholds met. Called when app reads/consumes buffered received data, advertising capacity for more.
Parameters
conn The HTTP/2 connection (non-NULL).
stream The stream (NULL for connection-level window update).
increment uint32 amount to add (0-2^31-1 typically).
Returns
0 if updated successfully, -1 if overflow or invalid increment (<=0).
Note
Batch updates possible; frame sent only if significant change.
Exceptions
SocketHTTP2_FlowControlError on arithmetic overflow.
See also
http2_flow_consume_recv() counterpart for consumption.
http2_process_window_update() for handling peer increments.
RFC 9113 Section 6.9.2 Receiving WINDOW_UPDATE Frames.
http2_flow_update_send()
int http2_flow_update_send (SocketHTTP2_Conn_T conn, SocketHTTP2_Stream_T stream, uint32_t increment) extern
Update send flow control windows based on peer WINDOW_UPDATE frame.
Applies validated increment to connection send_window and stream send_window. Ensures increment >0 and no overflow; may unblock pending sends if window was starved. Logs suspicious large increments as potential DoS.
Parameters
conn The HTTP/2 connection (non-NULL).
stream The stream (NULL for connection window).
increment The uint32 increment from received WINDOW_UPDATE payload.
Returns
0 if successfully added (clamped if needed), -1 if invalid (<=0 or overflow).
Note
Affects http2_flow_available_send() immediately.
Exceptions
SocketHTTP2_FlowControlError on invalid update parameters.
See also
http2_process_window_update() for frame parsing and call to this.
http2_flow_consume_send() for symmetric consumption on send.
RFC 9113 Section 6.9.2 Flow Control Windows: Receiving Updates.
http2_frame_send()
int http2_frame_send (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader * header, const void * payload, size_t payload_len) extern
Serialize HTTP/2 frame and queue it in send buffer.
Builds the 9-byte frame header (length, type, flags, stream ID, reserved bits), appends payload (if any), and writes to connection's send buffer. Applies frame-specific serialization (e.g., big-endian integers) and preliminary flow control checks for DATA frames.
Parameters
conn The HTTP/2 connection (non-NULL).
header Frame header with type, flags, length, stream ID populated.
payload Optional frame payload bytes (NULL if length=0).
payload_len Must match header->length; validated.
Returns
0 if successfully queued, -1 on buffer overflow or param mismatch.
Exceptions
SocketHTTP2_FlowControlError for DATA frames exceeding send window.
Thread Safety\n No - modifies connection send buffer and flow control state; caller must ensure exclusive access to conn
Complexity\n O(frame length) - serializes and copies frame data to buffer
// Send a SETTINGS ACK frame
SocketHTTP2_FrameHeader hdr = {0};
hdr.type = HTTP2_SETTINGS_FRAME;
hdr.flags = HTTP2_SETTINGS_ACK_FLAG;
hdr.length = 0;
hdr.stream_id = 0;
if (http2_frame_send(conn, &hdr, NULL, 0) != 0) {
    SOCKET_LOG_ERROR_MSG("Failed to queue SETTINGS ACK");
    // Handle error, possibly close connection
}
// Buffer queued; flush later via SocketHTTP2_Conn_process() or manual send
Note
Does not flush; call SocketHTTP2_Conn_flush() or process events to transmit.
See also
SocketHTTP2_Conn::send_buf for buffering details.
RFC 9113 Section 4 Frame Format for header and payload serialization rules.
http2_frame_validate()
SocketHTTP2_ErrorCode http2_frame_validate (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader * header) extern
Validate an HTTP/2 frame header against protocol rules.
Performs comprehensive checks including frame length bounds, type-specific flags, stream ID validity (odd/even for client/server), dependency rules, and connection state constraints (e.g., no frames before preface verification).
Parameters
conn The HTTP/2 connection context (non-NULL).
header Pointer to frame header structure.
Returns
0 if valid, otherwise specific HTTP/2 error code (e.g., PROTOCOL_ERROR, REFUSED_STREAM).
Note
Early validation prevents malformed frames from proceeding to payload processing.
Exceptions
SocketHTTP2_ProtocolError if validation triggers connection-level error.
Thread Safety\n No - reads connection state without internal synchronization; caller must ensure exclusive access to the connection object
Complexity\n O(1) - performs a fixed set of validation checks independent of input size
// Example: Validate frame header in frame reader loop
SocketHTTP2_ErrorCode err = http2_frame_validate(conn, &header);
if (err != HTTP2_NO_ERROR) {
    SOCKET_LOG_WARN_MSG("Frame validation failed: %d", err);
    http2_send_connection_error(conn, err);
    return -1;
}
// Safe to process payload
int processed = http2_process_frame(conn, &header, payload);
See also
http2_process_frame() for subsequent frame dispatching after validation.
RFC 9113 Sections 4.1 Frame Parsing and 4.2 Frame Layout for detailed validation rules.
http2_process_continuation()
int http2_process_continuation (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader * header, const unsigned char * payload) extern
Process incoming HTTP/2 CONTINUATION frame to continue oversized header blocks.
Validates the frame occurs immediately after a HEADERS, PUSH_PROMISE, or previous CONTINUATION without END_HEADERS (checks expecting_continuation and stream_id match). Retrieves the target stream; failure or no pending header_block triggers PROTOCOL_ERROR GOAWAY. Enforces limit on CONTINUATION frames per header block to mitigate DoS floods (exceed -> GOAWAY ENHANCE_YOUR_CALM). Appends payload fragment to stream's accumulated header_block, validating total size <= MAX_HEADER_LIST_SIZE setting (exceed -> RST_STREAM ENHANCE_YOUR_CALM). Dynamically grows the temporary buffer if needed via arena allocation. If END_HEADERS flag set, finalizes the block: resets continuation state, decodes complete HPACK header block into stream's headers[] or trailers[] array (depending on context), emits headers event via stream callback, applies any pending END_STREAM from initial frame, and frees the temporary header_block. Supports split headers for large or compressed blocks.
Parameters
conn The HTTP/2 connection context (must be expecting CONTINUATION).
header CONTINUATION frame header (type=CONTINUATION, stream_id=pending stream, flags=END_HEADERS or 0, length=fragment size; no padding/priority).
payload Raw header block fragment bytes to append (HPACK compressed).
Returns
0 on successful append or complete processing/decode, -1 on validation, size exceed, or DoS detection (sends GOAWAY or RST_STREAM).
Precondition
Frame header validated by http2_frame_validate(); prior frame set continuation state.
Exceptions
SocketHTTP2_ProtocolError on unexpected CONTINUATION or state mismatch.
SocketHTTP2_StreamError via RST on size limits or stream issues.
Note
CONTINUATION must strictly follow without interleaving other frames for same stream.
Temporary buffer grown via arena; cleared after decode to free memory.
See also
SocketHTTP2_Conn::expecting_continuation, ::continuation_stream_id, ::continuation_frame_count.
SocketHTTP2_Stream::header_block, ::header_block_len for accumulation.
http2_decode_headers() invoked on END_HEADERS for HPACK decompression.
grow_header_block() for buffer expansion.
RFC 9113 Section 6.10 CONTINUATION Frames for sequencing and format.
RFC 9113 Section 4.3 Header Block Fragment for split handling rules.
RFC 9114 Section 4 for HPACK block processing after reassembly.
http2_process_data()
int http2_process_data (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader * header, const unsigned char * payload) extern
Handle incoming HTTP/2 DATA frame for stream data transfer.
Extracts padding length if PADDED flag, validates total length, deducts from receive flow control windows using http2_flow_consume_recv(). Appends unpadded payload to stream's recv_buf, processes END_STREAM flag for state transition and trailers if present. May emit stream data event to user callback.
Parameters
conn The HTTP/2 connection.
header The DATA frame header (includes stream ID, padding flag/len).
payload Raw frame payload including optional padding.
Returns
0 on successful processing and buffering, -1 on error (e.g., padding mismatch, flow exceeded).
Precondition
Frame validated and stream exists/open.
Exceptions
SocketHTTP2_FlowControlError if DATA exceeds recv window.
SocketHTTP2_StreamError if stream closed or invalid state.
See also
http2_flow_consume_recv() window consumption.
SocketHTTP2_Stream::recv_buf for data buffering.
RFC 9113 Section 6.1 DATA for format and flow control rules.
http2_process_frame()
int http2_process_frame (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader * header, const unsigned char * payload) extern
Main entry for processing a received HTTP/2 frame.
After header parsing and validation, dispatches to frame-type specific processor based on header->type. Handles common logic like stream lookup, state transitions, flow consumption, and error propagation (RST_STREAM or GOAWAY). Updates connection/stream states and may trigger callbacks.
Parameters
conn The HTTP/2 connection context.
header The parsed frame header structure.
payload Pointer to frame payload bytes (validated length).
Returns
0 on successful processing, -1 on any error (may close connection).
Precondition
Frame header validated by caller or http2_frame_validate().
Exceptions
SocketHTTP2_ProtocolError or sub-errors leading to GOAWAY.
See also
http2_frame_validate() for header checks.
http2_process_data(), http2_process_headers() etc. for type handlers.
RFC 9113 Chapter 4 Frame Parsing and Chapter 6 Frame Types.
http2_process_goaway()
int http2_process_goaway (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader * header, const unsigned char * payload) extern
Process incoming HTTP/2 GOAWAY frame for connection shutdown notification.
Parses the GOAWAY payload to extract the highest stream ID the sender has processed successfully (last_stream_id, 31-bit unsigned) and the error code indicating the reason for initiating shutdown (e.g., NO_ERROR for graceful close, PROTOCOL_ERROR for issues). Updates connection state: sets goaway_received flag, records max_peer_stream_id to prevent new streams beyond this ID, and stores error code. Emits HTTP2_EVENT_GOAWAY_RECEIVED event via connection callback, allowing application to handle (e.g., close higher streams, retry elsewhere). Ignores frame header (pre-validated) and any optional debug data following the 8-byte fixed header fields in payload. Does not respond or alter other state.
Parameters
conn The HTTP/2 connection context.
header GOAWAY frame header (type=GOAWAY, stream_id=0, length >=8).
payload Payload: last_stream_id (4 bytes big-endian u31), error_code (4 bytes u32), optional variable-length debug data (ignored).
Returns
0 on successful parsing and state update (always succeeds post-validation).
Precondition
Frame header validated by http2_frame_validate().
Note
NO_ERROR (0) indicates graceful shutdown; non-zero codes signal errors affecting new streams.
Application must poll connection state or events to detect and react.
See also
SocketHTTP2_Conn::goaway_received, ::max_peer_stream_id, ::goaway_error_code for updated fields.
http2_emit_conn_event() for event notification.
http2_send_connection_error() for sending local GOAWAY.
RFC 9113 Section 6.8 GOAWAY for format, semantics, and error code details.
RFC 9113 Section 9.3 for HTTP/2 error handling and connection closure.
http2_process_headers()
int http2_process_headers (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader * header, const unsigned char * payload) extern
Process incoming HTTP/2 HEADERS frame (pseudo-headers and HPACK decoding).
Decodes HPACK-compressed headers from payload, validates pseudo-headers (e.g., :method, :path), handles END_HEADERS and PRIORITY flags, updates stream state (may transition to OPEN or CLOSED). Applies header table size updates if SETTINGS_ENABLE_PUSH, emits headers event to callback. Handles CONTINUATION chaining for oversized headers.
Parameters
conn HTTP/2 connection context.
header Parsed frame header (includes stream ID, flags, length).
payload Raw frame payload bytes for HPACK decoding.
Returns
0 on success (headers decoded and applied), -1 on error (e.g., HPACK decode fail, invalid pseudo-header).
Precondition
Frame header validated, stream exists or valid for new stream.
Exceptions
SocketHTTP2_ProtocolError for malformed headers or forbidden pseudo-headers.
SocketHTTP2_StreamError if stream state invalid for HEADERS.
See also
SocketHPACK_decode() for header decompression.
http2_frame_validate() pre-validation.
RFC 9113 6.3 HEADERS format and semantics.
RFC 7541 4.3 Pseudo-Header Fields for server/client rules.
http2_process_ping()
int http2_process_ping (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader * header, const unsigned char * payload) extern
Process incoming HTTP/2 PING frame for connection liveness checks and timing.
Applies DoS protection by rate limiting PING frames within a sliding time window; exceeds limit triggers connection closure with ENHANCE_YOUR_CALM error. For frames with ACK flag, verifies the 8-byte opaque payload matches any outstanding ping request opaque data, clears pending state if matched, and emits HTTP2_EVENT_PING_ACK event via connection callback. For non-ACK PING frames (probes from peer), immediately responds by queuing a PING ACK frame echoing the same opaque payload for round-trip time measurement. PING frames are connection-level (stream_id must be 0) and do not affect flow control or streams.
Parameters
conn The HTTP/2 connection context.
header PING frame header (type=PING, length=8, stream_id=0, flags=ACK or 0).
payload Fixed 8-byte opaque arbitrary data for correlation between request/ACK.
Returns
0 on successful processing (ACK queued or verified), -1 on rate limit exceeded or validation failure (sends GOAWAY via connection error).
Precondition
Frame header validated (fixed length 8, stream_id 0).
Exceptions
SocketHTTP2_ProtocolError indirectly if validation or state mismatch.
Note
Rate limiting uses monotonic timestamps; window reset on timeout.
Thread-safe: No - modifies connection state (use mutex if multi-threaded).
See also
SocketHTTP2_Conn::ping_count_in_window and ::ping_window_start_ms for limits.
http2_frame_send() for queuing ACK response.
http2_emit_conn_event() for PING_ACK notification.
RFC 9113 Section 6.7 PING Frames for protocol details and usage.
SocketHTTP2_Conn::ping_pending and ::ping_opaque for request/ACK matching.
http2_process_priority()
int http2_process_priority (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader * header, const unsigned char * payload) extern
Process incoming HTTP/2 PRIORITY frame for dependency tree updates.
Parses 4-byte stream dependency ID, weight (1-256), and exclusive flag. Updates stream's parent/weight/exclusive in priority tree, may rebalance scheduler. Valid only on open streams; ignores on idle/closed. No flow control impact.
Parameters
conn HTTP/2 connection.
header PRIORITY frame header (stream ID must be non-zero).
payload Fixed 5-byte payload: dep_stream_id (31 bits) + exclusive (1 bit) + weight (8 bits).
Returns
0 on success (priority updated), -1 if invalid (e.g., self-dependency, closed stream).
Precondition
Frame length == 5, header validated.
Exceptions
SocketHTTP2_ProtocolError for malformed priority or invalid deps.
See also
SocketHTTP2_Stream_T::parent, ::weight, ::exclusive for fields updated.
RFC 9113 6.6 PRIORITY frame specification.
HTTP/2 priority tree for scheduling implications.
http2_process_push_promise()
int http2_process_push_promise (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader * header, const unsigned char * payload) extern
Process incoming HTTP/2 PUSH_PROMISE frame for server push promise.
Handles server-sent PUSH_PROMISE frames on client side: validates receipt conditions (client role, push enabled in settings, associated stream open), extracts promised stream ID (must be even, unused), creates promised stream in RESERVED_REMOTE state marked as push, handles padding if flagged, initiates HPACK header block decoding into promised stream's headers, sets up CONTINUATION state if END_HEADERS not flagged, checks against MAX_HEADER_LIST_SIZE setting.
On failure (invalid promised ID, size exceed, etc.), sends RST_STREAM (REFUSED_STREAM) or triggers GOAWAY (PROTOCOL_ERROR). Successfully starts header decoding process.
Parameters
conn The HTTP/2 connection context (must be client role).
header PUSH_PROMISE frame header (stream_id identifies associated open request stream).
payload Raw payload: optional pad length (1 byte if PADDED), promised_stream_id (4 bytes), header block fragment, optional padding bytes.
Returns
0 on successful processing (stream created, decoding queued), -1 on error (connection/stream error sent, may lead to GOAWAY).
Precondition
Frame header validated by http2_frame_validate(); connection ready.
Exceptions
SocketHTTP2_ProtocolError via http2_send_connection_error() on validation failure.
SocketHTTP2_StreamError via RST if stream creation fails or limits exceeded.
Note
Server push only; servers ignore incoming PUSH_PROMISE.
See also
validate_push_promise() internal validation.
extract_push_promise_payload() payload parsing.
http2_stream_create() for promised stream allocation.
http2_decode_headers() for header block decompression.
SocketHTTP2_Conn::expecting_continuation for chaining support.
RFC 9113 Section 6.6 PUSH_PROMISE for format and semantics.
RFC 9113 Section 8.2 Server Push for usage and client control via settings.
http2_process_rst_stream()
int http2_process_rst_stream (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader * header, const unsigned char * payload) extern
Process incoming HTTP/2 RST_STREAM frame to abort a stream.
Parses 4-byte error code from payload, looks up stream by ID, transitions to CLOSED state, releases recv/send windows, notifies user callback of RST with error details. Counts protocol errors for potential GOAWAY if threshold exceeded.
Parameters
conn HTTP/2 connection context.
header RST_STREAM frame header (stream ID identifies aborted stream).
payload Fixed 4-byte error code (SocketHTTP2_ErrorCode enum value).
Returns
0 on success (stream aborted cleanly), -1 if invalid (e.g., ID=0, unknown stream).
Precondition
Frame length == 4, header validated (flags must be 0).
Exceptions
SocketHTTP2_ProtocolError if malformed or invalid stream ID.
See also
SocketHTTP2_ErrorCode for standard error values (e.g., PROTOCOL_ERROR, CANCEL).
RFC 9113 6.4 RST_STREAM for abort semantics and codes.
Connection GOAWAY for repeated error handling.
http2_process_settings()
int http2_process_settings (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader * header, const unsigned char * payload) extern
Process incoming HTTP/2 SETTINGS frame for parameter negotiation.
Parses variable-length settings pairs (ID + value), applies valid ones to connection config (e.g., MAX_CONCURRENT_STREAMS, INITIAL_WINDOW_SIZE), acknowledges with ACK frame if ACK flag not set. Logs deprecated settings, rejects invalid IDs/values, may trigger flow control window adjustments or stream limits update.
Parameters
conn HTTP/2 connection (updates conn->settings).
header SETTINGS frame header (flags: ACK or none).
payload Sequence of 6-byte settings (2-byte ID + 4-byte value, multiple possible).
Returns
0 on success (settings applied/acked), -1 on error (invalid settings).
Precondition
Frame length even, multiple of 6 if not ACK.
Exceptions
SocketHTTP2_ProtocolError for unknown settings ID or invalid values.
See also
SocketHTTP2_Setting enum for standard IDs and defaults.
RFC 9113 6.5 SETTINGS for negotiation rules and ACK requirement.
http2_send_settings_ack() for response generation.
http2_process_window_update()
int http2_process_window_update (SocketHTTP2_Conn_T conn, const SocketHTTP2_FrameHeader * header, const unsigned char * payload) extern
Process incoming HTTP/2 WINDOW_UPDATE frame to replenish flow control windows.
Deserializes the 31-bit unsigned window increment from the fixed 4-byte payload. Rejects increment == 0 as PROTOCOL_ERROR, sending GOAWAY (connection-level) or RST_STREAM (stream-level) accordingly. For connection-level updates (stream_id=0), applies increment to connection send window using http2_flow_update_send (NULL stream); arithmetic overflow or invalid state triggers GOAWAY with FLOW_CONTROL_ERROR. For stream-level (stream_id >0), retrieves stream via lookup; if found, updates both stream and connection send windows, emits HTTP2_EVENT_WINDOW_UPDATE via stream callback on success; failure sends RST_STREAM with FLOW_CONTROL_ERROR to that stream. Unknown or closed streams are silently ignored per RFC. This frame allows receiver to advertise additional data capacity after consuming buffered DATA, unblocking peer sends.
Parameters
conn The HTTP/2 connection context.
header WINDOW_UPDATE frame header (type=WINDOW_UPDATE, length=4, stream_id=0 or stream ID).
payload Fixed 4-byte big-endian unsigned 31-bit increment (>0 required).
Returns
0 on successful update (or ignore for unknown stream), -1 on validation or update error (sends GOAWAY or RST_STREAM as appropriate).
Precondition
Frame header validated by http2_frame_validate().
Exceptions
SocketHTTP2_FlowControlError via error frames on window update failure (e.g., overflow).
SocketHTTP2_ProtocolError for zero increment.
Note
Updates affect http2_flow_available_send() immediately, potentially unblocking sends.
See also
http2_flow_update_send() for window arithmetic and validation.
process_connection_window_update() and process_stream_window_update() for dispatch logic.
http2_stream_lookup() for stream retrieval.
http2_emit_stream_event() for event emission on stream updates.
RFC 9113 Section 6.9 WINDOW_UPDATE Frames for details and rules.
RFC 9113 Section 6.9.2 Flow-Control Windows: receiving updates.
RFC 9113 Section 5.1 Stream States: window updates only on open/half-closed streams.
http2_send_connection_error()
void http2_send_connection_error (SocketHTTP2_Conn_T conn, SocketHTTP2_ErrorCode error_code) extern
Emit GOAWAY frame with error code and shutdown connection gracefully.
Builds GOAWAY frame identifying last processed stream ID and error code, optionally appends debug data. Sends via frame_send, sets internal flags, transitions state to GOAWAY_SENT, closes higher streams, notifies via callback, and finally closes underlying socket after drain.
Parameters
conn The HTTP/2 connection in error state.
error_code The SocketHTTP2_ErrorCode to include in GOAWAY (e.g., NO_ERROR for clean close).
Note
Does not block; asynchronous close after send.
Exceptions
SocketHTTP2_Failed if frame send fails (socket error).
See also
http2_send_stream_error() for per-stream RST_STREAM.
SocketHTTP2_Conn::goaway_sent and ::goaway_error_code.
RFC 9113 Section 6.8 GOAWAY for error notification and shutdown sequence.
http2_send_stream_error()
void http2_send_stream_error (SocketHTTP2_Conn_T conn, uint32_t stream_id, SocketHTTP2_ErrorCode error_code) extern
Send RST_STREAM frame to terminate a specific stream abruptly.
Serializes 4-byte error code into RST_STREAM payload, targets stream_id, sends via http2_frame_send without flow check (control frame). Applies close rate limiting; immediately closes local stream state/resources. Notifies peer of error for cleanup.
Parameters
conn The HTTP/2 connection.
stream_id The 31-bit ID of stream to reset.
error_code SocketHTTP2_ErrorCode reason (e.g., PROTOCOL_ERROR, CANCEL).
Note
Does not affect other streams or connection.
Exceptions
SocketHTTP2_StreamError if stream ID invalid or rate limited.
See also
http2_process_rst_stream() for receiving RST.
SocketHTTP2_Conn::stream_close_rate_limit for flood protection.
RFC 9113 Section 6.4 RST_STREAM for usage and codes.
http2_stream_create()
SocketHTTP2_Stream_T http2_stream_create (SocketHTTP2_Conn_T conn, uint32_t stream_id, int is_local_initiated) extern
Create and initialize a new HTTP/2 stream structure.
Allocates stream from connection's arena, sets initial state, flow windows from connection defaults, header buffers, and inserts into hash table. Enforces concurrency limits, ID parity rules, and stream open rate limiting. Increments appropriate stream count (client/server initiated).
Parameters
conn The HTTP/2 connection (non-NULL, ready state).
stream_id The 31-bit stream identifier to assign (validated).
is_local_initiated True if stream initiated locally (affects limits).
Returns
Allocated and initialized SocketHTTP2_Stream_T or NULL on error.
Exceptions
SocketHTTP2_ProtocolError for invalid stream ID (e.g., wrong parity).
SocketHTTP2_StreamError if max concurrent streams or rate limit exceeded.
Note
Automatically emits stream event if callbacks registered.
See also
http2_stream_destroy() for symmetric cleanup.
SocketHTTP2_Conn::client_initiated_count etc. for counting.
RFC 9113 Section 5.1.1 Stream Identifiers and Section 5.2 Stream Concurrency.
http2_stream_destroy()
void http2_stream_destroy (SocketHTTP2_Stream_T stream) extern
Deallocate HTTP/2 stream resources and remove from connection.
Extracts stream from hash table, decrements client/server initiated counts, clears recv_buf and header/trailer arrays, frees header_block if allocated, resets flow windows contribution, and emits stream close event via callback. Marks slot available for reuse.
Parameters
stream Pointer to stream to destroy (non-NULL, belonging to valid conn).
Note
Must not be called from stream callback to avoid reentrancy issues.
Automatically handles rate limiting enforcement before destruction.
Exceptions
SocketHTTP2_Failed on arena free issues (rare).
See also
http2_stream_create() for creation counterpart.
http2_emit_stream_event() for event emission.
RFC 9113 Section 5.1.1 Stream Termination.
http2_stream_lookup()
SocketHTTP2_Stream_T http2_stream_lookup (const SocketHTTP2_Conn_T conn, uint32_t stream_id) extern
Retrieve HTTP/2 stream from connection by stream identifier.
Performs hashed lookup using stream_id modulo table size with randomized seed for security, then linear search in chain for exact match. Returns NULL for invalid IDs (e.g., closed streams, wrong parity for role).
Parameters
conn The HTTP/2 connection (non-NULL).
stream_id 31-bit unsigned stream ID (0 invalid for streams).
Returns
Matching SocketHTTP2_Stream_T or NULL if not active.
Note
Average O(1) time; worst-case linear in chain length.
Exceptions
None - safe read-only operation.
See also
http2_stream_create() to insert into hash table.
SocketHTTP2_Conn::streams for hash table details.
RFC 9113 Section 5.1.1 Stream Identifiers and State.
http2_stream_transition()
SocketHTTP2_ErrorCode http2_stream_transition (SocketHTTP2_Stream_T stream, uint8_t frame_type, uint8_t flags, int is_send) extern
Validate and apply stream state transition for frame receipt or send.
Enforces HTTP/2 state machine rules: checks current state vs. frame type/flags, updates state (e.g., OPEN -> HALF_CLOSED on END_STREAM DATA), handles special cases like push promise in odd states. Invalid transitions trigger RST or GOAWAY.
Parameters
stream The HTTP/2 stream (non-NULL).
frame_type The frame type constant (e.g., HTTP2_HEADERS_FRAME).
flags The frame flags bitfield.
is_send True for sender state machine (outgoing frames), false for receiver.
Returns
0 if transition valid and applied, else HTTP/2 error code (e.g., PROTOCOL_ERROR).
Note
Separate state machines for send/receive per RFC.
Exceptions
SocketHTTP2_StreamError on stream-level invalid state change.
See also
SocketHTTP2_StreamState enum for states.
RFC 9113 Section 5.1 Stream State Machine with transition tables.
httpclient_auth_basic_header()
int httpclient_auth_basic_header (const char * username, const char * password, char * output, size_t output_size) extern
Generate Basic authentication header value.
Encodes "username:password" in Base64, formats as "Basic <base64>". No validation on inputs; assumes valid UTF8.
Parameters
username The username string.
password The password string.
output Buffer for the header value string.
output_size Size of output buffer (recommended 512).
Returns
0 on success, -1 if buffer too small or null inputs.
Thread Safety\n Yes - stateless.
See also
SocketCrypto_base64_encode() underlying.
docs/SECURITY.md for auth Security Modules notes.
httpclient_auth_bearer_header()
int httpclient_auth_bearer_header (const char * token, char * output, size_t output_size) extern
Generate Authorization header for Bearer token authentication (RFC 6750).
Parameters
token The Bearer token string (copied as-is, no validation).
output Buffer to receive the formatted "Bearer <token>" header value.
output_size Size of the output buffer (must be >= strlen(token) + 7).
Returns
0 on success, -1 if output buffer is too small or token is NULL.
Thread Safety\n Yes - stateless function.
No encoding, validation, or security checks are performed on the token. Suitable for OAuth 2.0 Bearer tokens in HTTP requests.
See also
SocketHTTP_Headers_set() to add the header to a request.
docs/SECURITY.md for authentication Security Modules considerations.
https://datatracker.ietf.org/doc/html/rfc6750 for specification.
httpclient_auth_digest_challenge()
int httpclient_auth_digest_challenge (const char * www_authenticate, const char * username, const char * password, const char * method, const char * uri, const char * nc_value, char * output, size_t output_size) extern
Handle Digest authentication challenge from WWW-Authenticate header and generate Authorization response.
Parses the WWW-Authenticate header for Digest params (realm, nonce, qop, etc.). Generates client nonce, computes response using httpclient_auth_digest_response(). Formats Authorization: Digest ... header value. Handles MD5 or SHA256 based on algorithm param. NOTE: Supports only qop=auth; not auth-int.
Parameters
www_authenticate The WWW-Authenticate header value string.
username User's username.
password User's password (sensitive).
method HTTP method (e.g., "GET").
uri Request URI (without host).
nc_value Nonce count string like "00000001".
output Buffer for Authorization header value.
output_size Size of output buffer (recommended 1024).
Returns
0 on success, -1 on parse or computation error.
Thread Safety\n Yes - stateless.
Exceptions
None - returns -1 on failure.
See also
httpclient_auth_digest_response() for response calc.
docs/SECURITY.md for Digest auth details.
https://datatracker.ietf.org/doc/html/rfc7616 for spec.
httpclient_auth_digest_response()
int httpclient_auth_digest_response (const char * username, const char * password, const char * realm, const char * nonce, const char * uri, const char * method, const char * qop, const char * nc, const char * cnonce, int use_sha256, char * output, size_t output_size) extern
Compute Digest authentication response value.
Implements RFC 2617 Digest auth response calculation. Supports qop="auth", MD5 or SHA-256 algorithm. Computes HA1 = H({username:realm:password}), HA2 = H({method:uri}), response = H(HA1:nonce:nc:cnonce:qop:HA2). Outputs hex digest to buffer.
Parameters
username The username.
password The password (not stored after call).
realm The realm from challenge.
nonce The server nonce.
uri The request URI without query.
method The HTTP method name (e.g., "GET").
qop The qop value ("auth").
nc The nonce count string (e.g., "00000001").
cnonce The client nonce string.
use_sha256 1 for SHA-256, 0 for MD5.
output Buffer for hex response string.
output_size Size of output (33 for MD5, 65 for SHA256 + null).
Returns
0 on success, -1 on invalid params or hash error.
Thread Safety\n Yes - stateless.
Exceptions
None - returns -1.
See also
SocketCrypto_md5(), SocketCrypto_sha256().
httpclient_auth_digest_challenge() for full handling.
docs/SECURITY.md for auth details.
Note
Password zeroed after use? No, but sensitive; use secure memory if possible.
httpclient_auth_is_stale_nonce()
int httpclient_auth_is_stale_nonce (const char * www_authenticate) extern
Check if Digest challenge indicates stale nonce.
Parses WWW-Authenticate for "stale=true" param. Allows automatic retry on stale nonce (server-side expiration) vs bad credentials.
Parameters
www_authenticate The WWW-Authenticate header string.
Returns
1 if stale=true found, 0 otherwise (or parse fail).
Thread Safety\n Yes - stateless parse.
See also
httpclient_auth_digest_challenge() for full auth.
docs/SECURITY.md for retry logic.
httpclient_calculate_retry_delay()
int httpclient_calculate_retry_delay (const SocketHTTPClient_T client, int attempt) extern
Calculate exponential backoff delay for retry attempt.
Uses client retry policy: initial_delay * multiplier^ (attempt-1) + jitter. Caps at max_delay. Jitter to avoid thundering herd.
Parameters
client The client for retry policy config.
attempt The current attempt number (1 = first retry).
Returns
Delay in milliseconds for sleep before next attempt.
Thread Safety\n Yes.
See also
SocketHTTPClient_Config.retry_policy for params.
httpclient_retry_sleep_ms() to sleep.
docs/HTTP-REFACTOR.md for backoff strategy.
httpclient_clear_response_for_retry()
void httpclient_clear_response_for_retry (SocketHTTPClient_Response * response) extern
Clear client-specific HTTP response for retry.
Resets client response fields like body, headers, status, error. Calls clear_response_for_retry on internal SocketHTTP_Response. Prepares for new response on same or new connection.
Parameters
response The client response to clear.
Exceptions
None.
Thread Safety\n Conditional.
See also
clear_response_for_retry() for core response clear.
SocketHTTPClient_Response for fields.
httpclient_connect()
HTTPPoolEntry * httpclient_connect (SocketHTTPClient_T client, const SocketHTTP_URI * uri) extern
Establish connection to target URI, handling proxy and TLS.
Resolves host via DNS, connects socket, applies TLS if secure or proxy TLS. Performs HTTP CONNECT to proxy if configured in client config. Negotiates HTTP version (1.1 or 2) via ALPN or upgrade. Initializes protocol state (parser or conn) in the pool entry.
Parameters
client The HTTP client instance for config, pool, DNS, TLS.
uri The target URI to connect to (host/port from URI).
Returns
HTTPPoolEntry with connected and initialized protocol state.
Exceptions
SocketHTTPClient_DNSFailed on resolve fail.
SocketHTTPClient_ConnectFailed on socket connect error.
SocketHTTPClient_TLSFailed on handshake fail.
SocketHTTPClient_ProtocolError on HTTP negotiation fail.
Thread Safety\n Conditional - client mutex held.
See also
SocketDNS_resolve_sync() for DNS.
SocketTLS_handshake_auto() for TLS.
SocketHTTPClient_Config for Proxy Tunneling Module configuration options.
httpclient_cookies_for_request()
int httpclient_cookies_for_request (SocketHTTPClient_CookieJar_T jar, const SocketHTTP_URI * uri, char * output, size_t output_size, int enforce_samesite) extern
Generate Cookie header value from jar cookies applicable to URI.
Queries jar for cookies matching URI domain/path, sorts by path length, selects per domain. Formats as "name1=value1; name2=value2; ..." string. Applies SameSite policy if enforce_samesite=1 (skip Lax/Strict for cross-site). Handles secure/httponly flags implicitly by selection.
Parameters
jar The cookie jar to query.
uri The request URI for domain/path/secure match.
output Buffer for the Cookie header value string.
output_size Size of output buffer (grow as needed? No, fixed).
enforce_samesite 1 to enforce SameSite=Lax/Strict policy, 0 to include all.
Returns
0 on success (header written or empty), -1 if buffer too small.
Thread Safety\n Yes - jar mutex held during query.
See also
SocketHTTPClient_CookieJar for jar details.
httpclient_parse_set_cookie() for setting cookies.
docs/SECURITY.md "Cookies" for policy.
Note
Empty string if no cookies; caller adds header only if length >0.
httpclient_host_hash()
static unsigned httpclient_host_hash (const char * host, int port, size_t table_size) inline static
Compute hash value for host:port pair used as connection pool key.
Parameters
host Hostname string (case-insensitive hashing via DJB2).
port Target port number.
table_size Size of the hash table (result modulo this value).
Uses DJB2 case-insensitive hash on hostname, XOR with port hash, final mod. Ensures even distribution for collision-resistant pool lookup.
Returns
Unsigned integer hash index (0 to table_size-1).
See also
socket_util_hash_djb2_ci_len() for hostname hashing.
socket_util_hash_uint() for port hashing.
docs/METRICS.md for performance considerations.
Definition at line 829 of file SocketHTTPClient-private.h.
References socket_util_hash_djb2_ci_len(), and socket_util_hash_uint().
httpclient_parse_set_cookie()
int httpclient_parse_set_cookie (const char * value, size_t len, const SocketHTTP_URI * request_uri, SocketHTTPClient_Cookie * cookie, Arena_T arena) extern
Parse Set-Cookie header and populate cookie structure.
Parses RFC 6265 Set-Cookie string, extracts name=value, attributes (expires, path, domain, secure, httpOnly, SameSite). Sets defaults from request_uri if not specified (domain/path). Allocates strings from arena. Validates dates, domains.
Parameters
value The Set-Cookie header value string.
len Length of value (for non-null term).
request_uri URI for default domain/path/secure.
cookie Output cookie struct to fill (strings allocated).
arena Arena for allocations.
Returns
0 on success, -1 on parse error (invalid format, date, etc.).
Thread Safety\n No - arena not safe, but parse stateless.
See also
SocketHTTPClient_Cookie for struct fields.
httpclient_cookies_for_request() for using cookies.
docs/SECURITY.md "Cookies" for parsing Security Modules.
Note
Handles quoted values, multiple attrs; strict RFC compliance.
httpclient_pool_cleanup_idle()
void httpclient_pool_cleanup_idle (HTTPPool * pool) extern
Clean up idle connections that have exceeded timeout.
Scans all connections in the pool, closes those idle longer than configured timeout. Removes closed entries from hash and lists, updates stats. Called periodically or on pool access.
Parameters
pool The HTTP pool to clean.
Exceptions
None - close failures logged.
Thread Safety\n Yes - acquires mutex.
See also
SocketHTTPClient_Config.idle_timeout_ms for timeout config.
SocketPool_drain() for pool drain during shutdown.
httpclient_pool_close()
void httpclient_pool_close (HTTPPool * pool, HTTPPoolEntry * entry) extern
Close and remove a pool entry from the pool.
Closes the underlying socket connection, marks entry as closed, removes from hash table and lists. Updates pool stats for failed connections. Used when connection error or explicit shutdown needed.
Parameters
pool The HTTP pool.
entry The entry to close.
Exceptions
None - socket close errors logged, not raised.
Thread Safety\n Conditional - hold mutex if concurrent.
See also
httpclient_pool_release() for normal release without close.
Socket_close() for low-level close.
httpclient_pool_free()
void httpclient_pool_free (HTTPPool * pool) extern
Dispose of HTTP connection pool and all associated resources.
Closes all open connections by calling Socket_free on each entry's socket, frees individual HTTPPoolEntry structures back to free list or arena, destroys hash table entries, clears statistics counters, and destroys mutex. Does not dispose or clear the underlying arena; caller must manage arena lifetime to avoid leaks of any remaining arena-allocated data. Handles partial failures gracefully (e.g. one connection close fail doesn't stop others).
Parameters
[in,out] pool Pointer to HTTPPool (set to NULL after successful disposal).
Returns
void
Exceptions
None - socket close or mutex destroy failures are logged via SocketLog but not raised as exceptions.
Thread Safety\n Conditional - safe if no concurrent access to pool; acquire pool->mutex externally if shared.
Usage Example
// Typical paired with creation
HTTPPool *pool = httpclient_pool_new(arena, &config);
// ... use pool ...
httpclient_pool_free(pool);  // Closes all conns, frees entries
pool = NULL;  // Set to NULL per convention
Arena_dispose(&arena);  // Finally dispose arena
Complexity\n O(n) time where n = current connection count (closes each); O(1) space
Note
Caller must ensure no threads are using pool entries during free.
Warning
Concurrent modifications during free may cause use-after-free or mutex poisoning.
See also
httpclient_pool_new() for creation and initialization.
Arena_dispose() for arena cleanup after pool_free.
Socket_free() underlying connection closes.
docs/HTTP-POOL.md for lifecycle management.
httpclient_pool_get()
HTTPPoolEntry * httpclient_pool_get (HTTPPool * pool, const char * host, int port, int is_secure) extern
Get or create a pool entry for the specified host:port and security.
Searches the pool's hash table for an existing idle entry matching the key. If found, returns it marked as in_use. If not, and under limits, creates a new entry. Does not establish the connection; that's done by httpclient_connect().
Parameters
pool The HTTP connection pool.
host The target hostname (copied).
port The target port.
is_secure 1 if TLS connection required, 0 for plain HTTP.
Returns
HTTPPoolEntry* for the connection slot, or raises exception.
Exceptions
SocketHTTPClient_Failed if max per host/total reached or allocation fails.
Thread Safety\n Yes - acquires pool mutex.
See also
httpclient_pool_release() to return after use.
httpclient_connect() to connect the entry.
httpclient_pool_new() for pool creation.
httpclient_pool_new()
HTTPPool * httpclient_pool_new (Arena_T arena, const SocketHTTPClient_Config * config) extern
Create and initialize a new HTTP connection pool.
Allocates the pool structure and hash table from the provided arena. Hash size computed from config max connections with security bounds to ensure efficient lookups while preventing excessive memory allocation or DoS via large configs. Security checks via SocketSecurity_check_multiply prevent overflow. Initializes mutex for thread safety and sets limits from config.
Parameters
[in] arena Memory arena for allocating pool structures, hash table, and entries.
[in] config HTTP client configuration for sizing (max_total_connections, max_connections_per_host, idle_timeout_ms).
Returns
Pointer to new HTTPPool instance, ready for use.
Exceptions
SocketHTTPClient_Failed if arena allocation fails, config invalid (e.g. zero max), or mutex init fails.
Thread Safety\n No - intended for single-threaded initialization; concurrent calls may race on arena.
Usage Example
Arena_T arena = Arena_new();
SocketHTTPClient_Config cfg;
SocketHTTPClient_config_defaults(&cfg);
// Internally, SocketHTTPClient_new calls this:
HTTPPool *pool = httpclient_pool_new(arena, &cfg);
if (pool) {
    // Use pool for connections
    HTTPPoolEntry *entry = httpclient_pool_get(pool, "example.com", 443, 1);
    // ...
    httpclient_pool_release(pool, entry);
}
httpclient_pool_free(pool);
Arena_dispose(&arena);
Configuration Impact
Config Field Effect on Pool
max_total_connections Upper bound on hash size and total entries
max_connections_per_host Per-host limit during get()
idle_timeout_ms Used in cleanup_idle()
Complexity\n O(1) time - constant allocations; O(hash_size) space where hash_size ~ max_total / 8
Note
Pool does not own arena; caller manages lifetime. All entries freed on pool_free but not arena_clear.
Warning
Ensure config values reasonable to avoid large memory use or DoS; security checks mitigate but validate inputs.
See also
httpclient_pool_free() for disposal and cleanup.
httpclient_pool_get() for acquiring connections.
SocketSecurity_check_multiply() for size validation used internally.
docs/HTTP-POOL.md for pool design details (if exists).
httpclient_pool_release()
void httpclient_pool_release (HTTPPool * pool, HTTPPoolEntry * entry) extern
Release a pool entry back to available state.
Marks the entry as idle (in_use = 0), updates last_used timestamp. Does not close the connection; it's kept for reuse. The entry remains in the hash table until idle timeout or explicit close.
Parameters
pool The HTTP pool.
entry The entry to release.
Exceptions
None - failures logged.
Thread Safety\n Yes - mutex protected.
See also
httpclient_pool_get() to acquire entry.
httpclient_pool_close() to close instead.
httpclient_pool_cleanup_idle() for idle cleanup.
httpclient_receive_response()
int httpclient_receive_response (HTTPPoolEntry * conn, SocketHTTPClient_Response * response, Arena_T arena) extern
Receive and parse HTTP response from connection.
Reads from inbuf/socket, parses headers/body based on proto (HTTP/1.1 or 2). Handles chunked, content-length, trailers. Stores in response struct, allocates from arena. Updates last_used time, checks keep-alive.
Parameters
conn The pool entry with socket and proto state.
response Output response to fill.
arena Arena for response allocations (headers, body).
Returns
0 on success, -1 on parse or read error.
Exceptions
SocketHTTPClient_Failed on parse error, SocketHTTP_ParseError propagated.
Thread Safety\n No - conn exclusive.
See also
SocketHTTP1_Parser_execute() for HTTP/1.1 parse.
SocketHTTP2_Conn_process() for HTTP/2.
SocketHTTPClient_Response for fields.
httpclient_retry_sleep_ms()
void httpclient_retry_sleep_ms (int ms) extern
Sleep for the specified milliseconds during retry backoff.
Simple nanosleep or select for delay. Interruptible by signals? Handled per SocketTimeout. Used in retry loops after delay calc.
Parameters
ms Milliseconds to sleep.
Exceptions
None - continues on interrupt.
Thread Safety\n Yes.
See also
httpclient_calculate_retry_delay() for delay value.
Socket_get_monotonic_ms() for timing.
httpclient_send_request()
int httpclient_send_request (HTTPPoolEntry * conn, SocketHTTPClient_Request_T req) extern
Send HTTP request over the connection entry.
Serializes request to outbuf, sends via socket (TLS if secure). Handles HTTP/1.1 or HTTP/2 send (headers frame + data stream). Adds auth headers if needed, cookies from jar. Updates pool stats for requests.
Parameters
conn The pool entry with socket and proto state.
req The request to send (method, URI, headers, body).
Returns
0 on success, -1 on send error (sets error in client).
Exceptions
SocketHTTPClient_Failed on serialization or send fail.
Thread Safety\n No - conn must be exclusively held.
See also
SocketHTTP1_serialize_request() for HTTP/1.1.
SocketHTTP2_Stream_send_request() for HTTP/2.
httpclient_receive_response() to receive reply.
httpclient_should_retry_error()
int httpclient_should_retry_error (const SocketHTTPClient_T client, SocketHTTPClient_Error error) extern
Determine if an HTTP client error is retryable.
Checks error type against client config retry policy. Retryable: transient like DNS fail, connect timeout, server 5xx. Non-retryable: client errors, TLS cert fail, too large response.
Parameters
client The client for config (max_retries, retryable_errors).
error The error code to check.
Returns
1 if retryable (within attempts), 0 otherwise.
Thread Safety\n Yes.
See also
SocketHTTPClient_Error for codes.
SocketHTTPClient_Config.max_retries for policy.
docs/HTTP-REFACTOR.md for retry logic.
httpclient_should_retry_status()
int httpclient_should_retry_status (const SocketHTTPClient_T client, int status) extern
Determine if HTTP status code warrants retry.
Typically retry on 5xx server errors, some 4xx like 429 too many requests. Configurable via client retry policy for specific codes. Does not retry client errors (4xx except retryable) or success.
Parameters
client The client for config retry policy.
status The HTTP status code received.
Returns
1 if retryable, 0 otherwise.
Thread Safety\n Yes.
See also
httpclient_should_retry_error() for error-based retry.
SocketHTTPClient_Config.retry_status_codes for custom codes.
docs/HTTP-REFACTOR.md for status handling.
SocketHPACK_decoder_config_defaults()
void SocketHPACK_decoder_config_defaults (SocketHPACK_DecoderConfig * config) extern
Initialize decoder config with defaults.
Parameters
config Configuration structure to initialize
Thread Safety\n Yes
SocketHPACK_Decoder_decode()
SocketHPACK_Result SocketHPACK_Decoder_decode (SocketHPACK_Decoder_T decoder, const unsigned char * input, size_t input_len, SocketHPACK_Header * headers, size_t max_headers, size_t * header_count, Arena_T arena) extern
Decode a complete HPACK header block into headers array.
Performs full decompression of an HPACK-encoded header block from HTTP/2 HEADERS or PUSH_PROMISE frames. Supports all HPACK representations: indexed headers, literal headers (with/without indexing), dynamic table updates. Single-pass decoding with validation against decoder config limits to prevent security issues like decompression bombs. Decoded headers include pseudo-headers (e.g., :method, :authority) and regular headers, preserving block order. Name and value strings are null-terminated and allocated from the arena for easy use.
Parameters
[in] decoder Initialized decoder with security configuration (max sizes, expansion ratio).
[in] input Pointer to the encoded HPACK header block data.
[in] input_len Number of bytes in the input buffer.
[out] headers Pre-allocated array of SocketHPACK_Header to store decoded results.
[in] max_headers Capacity of headers array (safety limit against excessive headers).
[out] header_count Pointer to receive the number of decoded headers written to array.
[in] arena Arena_T for allocating copies of header name and value strings.
Returns
SocketHPACK_Result indicating success or error:
HPACK_OK: Complete decode, header_count populated.
HPACK_INCOMPLETE: Partial input; call again with more data.
HPACK_ERROR_: Specific failure (e.g., HPACK_ERROR_INVALID_INDEX, HPACK_ERROR_HUFFMAN).
Exceptions
SocketHPACK_Error On validation failures, limit violations, or decoding errors.
Arena_Failed If string allocations exceed arena capacity.
Thread Safety\n No - modifies decoder state (table updates); requires external synchronization for shared use.
Basic Usage Pattern
// In HTTP/2 frame processing loop
SocketHPACK_Header headers[128];  // Reasonable max for most requests
size_t num_headers = 0;
const unsigned char *hpdata = frame->headers.payload;
size_t hplen = frame->headers.length;
TRY {
    SocketHPACK_Result res = SocketHPACK_Decoder_decode(decoder, hpdata, hplen,
                                                       headers, 128, &num_headers, arena);
    if (res == HPACK_OK) {
        // Process headers
        for (size_t i = 0; i < num_headers; ++i) {
            if (headers[i].never_index) {
                // Handle sensitive header (e.g., authorization)
            }
            // Convert to HTTP request/response as needed
        }
    } else if (res == HPACK_INCOMPLETE) {
        // Buffer more data and retry (rare for complete frames)
    } else {
        // Protocol error; consider GOAWAY or connection close
        SOCKET_LOG_ERROR_MSG("HPACK decode failed: %s", SocketHPACK_result_string(res));
        RAISE(SocketHTTP2_ProtocolError);
    }
} EXCEPT (SocketHPACK_Error) {
    // Log and handle
} END_TRY;
Error Codes and Recovery
Code Typical Cause Recommended Action
HPACK_ERROR_INVALID_INDEX Invalid table index Peer error; send RST_STREAM or GOAWAY
HPACK_ERROR_HUFFMAN Corrupt Huffman codes/padding Validate peer; close connection
HPACK_ERROR_TABLE_SIZE Invalid size update > max Protocol violation; reject update
HPACK_ERROR_HEADER_SIZE Single header exceeds limit Increase config or drop oversized
HPACK_ERROR_LIST_SIZE Total size exceeds limit Increase config or truncate headers
HPACK_ERROR_BOMB Excessive expansion ratio Tighten max_expansion_ratio; ban peer IP
Security Considerations
Configurable limits prevent DoS via large headers or table updates.
max_expansion_ratio guards against "HPACK bombs" where encoded is small but decoded huge.
never_index flag respected for sensitive headers (e.g., cookies, auth).
Table size updates limited per block (SOCKETHPACK_MAX_TABLE_UPDATES).
Note
On success, *header_count <= max_headers; array not null-padded.
Pseudo-headers must appear before regular headers per RFC; order preserved.
Supports Huffman decoding with padding validation (max 7 trailing 1-bits).
Partial decodes (HPACK_INCOMPLETE) advance internal state; resume with more input.
Arena strings lifetime ends with arena clear/dispose; copy if needed longer.
Warning
Always validate *header_count before accessing headers array.
Do not reuse headers array across calls without clearing or size check.
In production, log and monitor error rates for HPACK_ERROR_* codes.
Complexity\n O(n + m) where n=input size, m=output headers (linear scan + allocations)
See also
SocketHPACK_Decoder_new() for creating secure decoders
SocketHPACK_DecoderConfig for limit tuning
SocketHPACK_Header for output structure details
SocketHPACK_result_string() to get human-readable errors
SocketHTTP2.h for HTTP/2 frame integration
docs/SECURITY.mdHPACK Header Compression Module-Security Modules for attack mitigations
https://tools.ietf.org/html/rfc7541#section-6 for decoding spec
SocketHPACK_Decoder_free()
void SocketHPACK_Decoder_free (SocketHPACK_Decoder_T * decoder) extern
Free decoder.
Parameters
decoder Pointer to decoder pointer (will be set to NULL)
Thread Safety\n No
SocketHPACK_Decoder_get_table()
SocketHPACK_Table_T SocketHPACK_Decoder_get_table (SocketHPACK_Decoder_T decoder) extern
Get decoder's dynamic table.
Parameters
decoder Decoder
Returns
Dynamic table (for inspection/debugging)
Thread Safety\n No
SocketHPACK_Decoder_new()
SocketHPACK_Decoder_T SocketHPACK_Decoder_new (const SocketHPACK_DecoderConfig * config, Arena_T arena) extern
Create HPACK decoder instance.
Parameters
config Configuration (NULL for defaults).
arena Memory arena for allocations.
Returns
New decoder instance.
Exceptions
SocketHPACK_Error on allocation failure.
Thread Safety\n Yes (arena must be thread-safe or thread-local).
Creates a new HPACK decoder with the specified configuration.
See also
SocketHPACK_Decoder_free() for cleanup.
SocketHPACK_decoder_config_defaults() for default configuration.
SocketHPACK_Decoder_decode() for decoding header blocks.
SocketHTTP2.h for HTTP/2 integration.
SocketHPACK_Decoder_set_table_size()
void SocketHPACK_Decoder_set_table_size (SocketHPACK_Decoder_T decoder, size_t max_size) extern
Handle SETTINGS table size update.
Parameters
decoder Decoder
max_size New maximum size from SETTINGS frame
Thread Safety\n No
SocketHPACK_encoder_config_defaults()
void SocketHPACK_encoder_config_defaults (SocketHPACK_EncoderConfig * config) extern
Initialize encoder config with defaults.
Parameters
config Configuration structure to initialize
Thread Safety\n Yes
SocketHPACK_Encoder_encode()
ssize_t SocketHPACK_Encoder_encode (SocketHPACK_Encoder_T encoder, const SocketHPACK_Header * headers, size_t count, unsigned char * output, size_t output_size) extern
Encode header block.
Parameters
encoder Encoder instance
headers Array of headers to encode
count Number of headers
output Output buffer
output_size Buffer size
Returns
Bytes written, or -1 on error
Thread Safety\n No
Encodes a header block using HPACK compression.
SocketHPACK_Encoder_free()
void SocketHPACK_Encoder_free (SocketHPACK_Encoder_T * encoder) extern
Free encoder.
Parameters
encoder Pointer to encoder pointer (will be set to NULL)
Thread Safety\n No
SocketHPACK_Encoder_get_table()
SocketHPACK_Table_T SocketHPACK_Encoder_get_table (SocketHPACK_Encoder_T encoder) extern
Get encoder's dynamic table.
Parameters
encoder Encoder
Returns
Dynamic table (for inspection/debugging)
Thread Safety\n No
SocketHPACK_Encoder_new()
SocketHPACK_Encoder_T SocketHPACK_Encoder_new (const SocketHPACK_EncoderConfig * config, Arena_T arena) extern
Create HPACK encoder instance.
Parameters
config Configuration (NULL for defaults).
arena Memory arena for allocations.
Returns
New encoder instance.
Exceptions
SocketHPACK_Error on allocation failure.
Thread Safety\n Yes (arena must be thread-safe or thread-local).
Creates a new HPACK encoder with the specified configuration.
See also
SocketHPACK_Encoder_free() for cleanup.
SocketHPACK_encoder_config_defaults() for default configuration.
SocketHPACK_Encoder_encode() for encoding headers.
SocketHPACK_Encoder_set_table_size()
void SocketHPACK_Encoder_set_table_size (SocketHPACK_Encoder_T encoder, size_t max_size) extern
Signal table size change.
Parameters
encoder Encoder
max_size New maximum size
Thread Safety\n No
Signals that a dynamic table size update should be emitted at the start of the next header block.
SocketHPACK_huffman_decode()
ssize_t SocketHPACK_huffman_decode (const unsigned char * input, size_t input_len, unsigned char * output, size_t output_size) extern
Huffman decode string.
Parameters
input Encoded input
input_len Input length
output Output buffer
output_size Buffer size
Returns
Decoded length, or -1 on error
Thread Safety\n Yes
Decodes a Huffman-encoded string using DFA-based decoding. Validates padding (max 7 bits, all 1s).
SocketHPACK_huffman_encode()
ssize_t SocketHPACK_huffman_encode (const unsigned char * input, size_t input_len, unsigned char * output, size_t output_size) extern
Huffman encode string.
Parameters
input Input string
input_len Input length
output Output buffer
output_size Buffer size
Returns
Encoded length, or -1 on error (buffer too small)
Thread Safety\n Yes
Encodes a string using the HPACK Huffman table (RFC 7541 Appendix B).
SocketHPACK_huffman_encoded_size()
size_t SocketHPACK_huffman_encoded_size (const unsigned char * input, size_t input_len) extern
Calculate encoded size.
Parameters
input Input string
input_len Input length
Returns
Encoded size in bytes
Thread Safety\n Yes
Calculates the size of the Huffman-encoded output in bytes.
SocketHPACK_int_decode()
SocketHPACK_Result SocketHPACK_int_decode (const unsigned char * input, size_t input_len, int prefix_bits, uint64_t * value, size_t * consumed) extern
Decode integer with prefix.
Parameters
input Input buffer
input_len Input length
prefix_bits Number of prefix bits (1-8)
value Output value
consumed Output bytes consumed
Returns
Result code
Thread Safety\n Yes
Decodes an HPACK-encoded integer.
SocketHPACK_int_encode()
size_t SocketHPACK_int_encode (uint64_t value, int prefix_bits, unsigned char * output, size_t output_size) extern
Encode integer with prefix.
Parameters
value Integer value to encode
prefix_bits Number of prefix bits (1-8)
output Output buffer
output_size Buffer size
Returns
Bytes written
Thread Safety\n Yes
Encodes an integer using HPACK's variable-length encoding.
SocketHPACK_result_string()
const char * SocketHPACK_result_string (SocketHPACK_Result result) extern
Get error description.
Parameters
result Result code
Returns
Static string describing the result
Thread Safety\n Yes
SocketHPACK_static_find()
int SocketHPACK_static_find (const char * name, size_t name_len, const char * value, size_t value_len) extern
Find entry in static table.
Parameters
name Header name
name_len Name length
value Header value (NULL to match name only)
value_len Value length
Returns
Index (1-61) on exact match, negative index if only name matches, 0 if not found
Thread Safety\n Yes
Searches for an entry in the static table.
SocketHPACK_static_get()
SocketHPACK_Result SocketHPACK_static_get (size_t index, SocketHPACK_Header * header) extern
Get entry from static table.
Parameters
index Entry index (1-61)
header Output header structure
Returns
HPACK_OK on success, HPACK_ERROR_INVALID_INDEX if out of range
Thread Safety\n Yes
Retrieves an entry from the static table by index.
SocketHPACK_Table_add()
SocketHPACK_Result SocketHPACK_Table_add (SocketHPACK_Table_T table, const char * name, size_t name_len, const char * value, size_t value_len) extern
Add entry to dynamic table.
Parameters
table Dynamic table
name Header name
name_len Name length
value Header value
value_len Value length
Returns
HPACK_OK on success
Thread Safety\n No
Adds a new entry to the dynamic table. May evict older entries if the table size would exceed the maximum.
SocketHPACK_Table_count()
size_t SocketHPACK_Table_count (SocketHPACK_Table_T table) extern
Get number of entries.
Parameters
table Dynamic table
Returns
Number of entries in the table
Thread Safety\n No
SocketHPACK_Table_free()
void SocketHPACK_Table_free (SocketHPACK_Table_T * table) extern
Dispose of a dynamic table instance and release its resources.
Safely frees the dynamic table, returning all allocated memory to the arena. The table pointer is set to NULL to prevent use-after-free errors.
This function does not throw exceptions as it performs no allocations. It is safe to call on already-NULL pointers (no-op).
Parameters
[in,out] table Pointer to the dynamic table instance. Set to NULL on success.
Thread Safety\n No - caller must ensure no concurrent access to the table or arena.
Usage Example
Arena_T arena = Arena_new();
TRY {
    SocketHPACK_Table_T table = SocketHPACK_Table_new(SOCKETHPACK_DEFAULT_TABLE_SIZE, arena);
    // ... use table for encoding/decoding ...
} EXCEPT(SocketHPACK_Error) {
    // Handle error
} FINALLY {
    SocketHPACK_Table_free(&table);
} END_TRY;
Arena_dispose(&arena);
Important Notes
Always pair with SocketHPACK_Table_new() using the same arena for lifecycle management.
No individual header strings are freed; they remain in the arena until Arena_clear() or Arena_dispose().
In multi-threaded environments, synchronize access to shared arenas.
Note
This operation does not iterate over table entries; memory is managed by the arena.
Warning
Failing to free tables can lead to arena exhaustion and memory leaks.
Complexity\n O(1) - constant time operation
See also
SocketHPACK_Table_new() for table creation
Arena_dispose() for complete resource cleanup
SocketHPACK_Encoder_free() and SocketHPACK_Decoder_free() for related cleanup patterns
docs/HTTP.md for HTTP/2 header compression overview
SocketHPACK_Table_get()
SocketHPACK_Result SocketHPACK_Table_get (SocketHPACK_Table_T table, size_t index, SocketHPACK_Header * header) extern
Get entry by index.
Parameters
table Dynamic table
index Entry index (1-based, relative to dynamic table start)
header Output header structure
Returns
HPACK_OK on success, HPACK_ERROR_INVALID_INDEX if out of range
Thread Safety\n No
Retrieves an entry from the dynamic table by index. Index 1 is the most recently added entry.
SocketHPACK_Table_max_size()
size_t SocketHPACK_Table_max_size (SocketHPACK_Table_T table) extern
Get maximum table size.
Parameters
table Dynamic table
Returns
Maximum size in bytes
Thread Safety\n No
SocketHPACK_Table_new()
SocketHPACK_Table_T SocketHPACK_Table_new (size_t max_size, Arena_T arena) extern
Create a new dynamic HPACK table for header compression.
Initializes a dynamic table used for storing header fields to reduce redundancy in HTTP/2 header blocks (RFC 7541). The table supports eviction of least recently used (oldest) entries when size limits are reached, using a circular buffer for efficiency. All internal allocations (entries, strings) are arena-managed for fast cleanup.
Parameters
[in] max_size Maximum allowed size for the table in bytes. Includes SOCKETHPACK_ENTRY_OVERHEAD (32 bytes) per entry. Must be 0 <= max_size <= SOCKETHPACK_MAX_TABLE_SIZE. Default recommendation: SOCKETHPACK_DEFAULT_TABLE_SIZE (4096).
[in] arena Arena_T instance for all memory allocations. Table lifetime is bound to this arena.
Returns
Opaque pointer to new dynamic table instance.
Exceptions
SocketHPACK_Error If max_size invalid or internal initialization fails.
Arena_Failed If arena allocation fails (propagated).
Thread Safety\n Yes - atomic creation; arena must be synchronized if shared across threads.
Basic Usage
Arena_T arena = Arena_new();
SocketHPACK_Table_T table = NULL;
TRY {
    table = SocketHPACK_Table_new(SOCKETHPACK_DEFAULT_TABLE_SIZE, arena);
    assert(table != NULL);
    // Table ready for use in encoders/decoders
} EXCEPT(Arena_Failed, SocketHPACK_Error) {
    fprintf(stderr, "Failed to create table: %s\n", Except_message(Except_stack));
    return -1;
} END_TRY;
// Use table...
SocketHPACK_Table_free(&table);
Advanced Configuration
max_size Value Recommended For Expected Entries Compression Impact
0 Minimal memory 0 No dynamic compression
4096 (default) General use ~10-20 Good balance
16384 High-volume HTTP/2 ~50-100 Better ratios
65536 (max) Servers ~200+ Optimal but memory-intensive
Note
Table starts empty (size=0, count=0). Populate during encoding or manually.
Strings added to table are copied into arena; originals can be freed after.
Use with SocketHPACK_Encoder_new() or SocketHPACK_Decoder_new() for HTTP/2.
Warning
Large max_size increases memory footprint; monitor with SocketHPACK_Table_size().
Never pass NULL arena; will raise Arena_Failed.
Complexity\n O(1) - constant time initialization and allocation
See also
SocketHPACK_Table_free() for paired cleanup
SocketHPACK_Table_add() to populate with headers
SocketHPACK_Table_set_max_size() for dynamic resizing
SocketHPACK_Encoder_new() for encoder integration
Arena.h for memory management details
docs/HTTP-REFACTOR.md for performance tuning
https://tools.ietf.org/html/rfc7541#section-4 for RFC specification
SocketHPACK_Table_set_max_size()
void SocketHPACK_Table_set_max_size (SocketHPACK_Table_T table, size_t max_size) extern
Update the maximum size of the dynamic table.
Changes the dynamic table's maximum capacity, potentially evicting the oldest entries to fit within the new limit. This operation is typically triggered by a HTTP/2 SETTINGS frame updating HEADER_TABLE_SIZE. Entries are evicted from the oldest (highest index) until the table size is <= max_size.
Parameters
[in] table The dynamic table instance to update.
[in] max_size New maximum table size in bytes, including overhead per entry. Must be >= 0 and <= SOCKETHPACK_MAX_TABLE_SIZE.
Exceptions
SocketHPACK_Error If max_size is invalid (negative or exceeds maximum allowed).
Thread Safety\n No - concurrent updates or accesses may lead to inconsistent state or data races.
Usage Example
SocketHPACK_Table_T table = ...;  // Initialized table
// Increase for better compression
TRY {
    SocketHPACK_Table_set_max_size(table, 16384);  // 16KB
} EXCEPT(SocketHPACK_Error) {
    SOCKET_LOG_ERROR_MSG("Failed to update table size: %s", Socket_GetLastError());
}
// Reduce size, evicting if necessary
SocketHPACK_Table_set_max_size(table, 2048);   // 2KB
Eviction Behavior
Condition Action
new_size >= current_size No eviction
new_size < current_size Evict oldest entries until compliant
new_size == 0 Clear entire table
Query After Update
After calling, verify with:
SocketHPACK_Table_size(table) <= max_size
SocketHPACK_Table_max_size(table) == max_size
Note
Affects compression efficiency; larger tables improve ratios but use more memory.
Synchronized between encoder/decoder via SETTINGS frames in HTTP/2.
Warning
Frequent size changes can cause unnecessary evictions and performance overhead.
Complexity\n O(n) worst case - linear in number of entries if full eviction needed
Complexity\n O(1) average - if no or few evictions
See also
SocketHPACK_Table_new() for initial configuration
SocketHPACK_Table_size() to get current usage
SocketHPACK_Table_count() for entry count changes
SocketHPACK_Decoder_set_table_size() for decoder synchronization
SocketHPACK_Encoder_set_table_size() for encoder updates
docs/HTTP.mdHPACK Header Compression Module-dynamic-table for HTTP/2 specifics
SocketHPACK_Table_size()
size_t SocketHPACK_Table_size (SocketHPACK_Table_T table) extern
Query the current size of the dynamic table in bytes.
Returns the total size of all entries in the dynamic table, including the 32-byte overhead per entry as per RFC 7541 Section 4.1. This value represents memory usage and is always <= the maximum table size set via SocketHPACK_Table_set_max_size().
Parameters
[in] table The dynamic table instance to query.
Returns
Current table size in bytes (sum of name/value lengths + SOCKETHPACK_ENTRY_OVERHEAD * entry count).
Thread Safety\n No - concurrent table modifications (add/evict) may cause inconsistent return values.
Usage Example
SocketHPACK_Table_T table = SocketHPACK_Table_new(4096, arena);
size_t size = SocketHPACK_Table_size(table);  // Initially 0
// After adding entries
SocketHPACK_Table_add(table, ":method", 7, "GET", 3);
size = SocketHPACK_Table_size(table);  // ~42 bytes (value + name + overhead)
printf("Table size: %zu bytes\n", size);
Size Calculation
Total size = \sum (name_len + value_len) + (count * SOCKETHPACK_ENTRY_OVERHEAD)
Component Description
Header Data Sum of all name and value string lengths
Overhead 32 bytes per entry for indexing and metadata
Note
Size does not include static table; only dynamic entries.
Returns 0 for empty table.
Complexity\n O(1) - maintained incrementally during add/evict operations
See also
SocketHPACK_Table_count() for entry count
SocketHPACK_Table_max_size() for capacity limit
SocketHPACK_Table_add() for adding entries that increase size
SocketHPACK_ENTRY_OVERHEAD for per-entry cost
docs/HTTP-REFACTOR.mdHPACK Header Compression Module-memory-management for tuning advice
SocketHTTP_coding_name()
const char * SocketHTTP_coding_name (SocketHTTP_Coding coding) extern
Get coding name string.
Parameters
coding Coding type
Returns
Static string, or NULL for unknown
Thread Safety\n Yes
SocketHTTP_coding_parse()
SocketHTTP_Coding SocketHTTP_coding_parse (const char * name, size_t len) extern
Parse coding name.
Parameters
name Coding name string
len Name length (0 for strlen)
Returns
Coding type, or HTTP_CODING_UNKNOWN
Thread Safety\n Yes
SocketHTTP_date_format()
int SocketHTTP_date_format (time_t t, char * output) extern
Format time as HTTP-date (IMF-fixdate)
Parameters
t Time to format (UTC)
output Output buffer (must be at least SOCKETHTTP_DATE_BUFSIZE bytes)
Returns
Length written (29), or -1 on error
Thread Safety\n Yes
Output format: "Sun, 06 Nov 1994 08:49:37 GMT"
SocketHTTP_date_parse()
int SocketHTTP_date_parse (const char * date_str, size_t len, time_t * time_out) extern
Parse HTTP-date.
Parameters
date_str Date string in any valid HTTP-date format
len Length of string (0 for strlen)
time_out Output time_t (UTC)
Returns
0 on success, -1 on error
Thread Safety\n Yes
Accepts three formats per RFC 9110:
IMF-fixdate: Sun, 06 Nov 1994 08:49:37 GMT (preferred)
RFC 850: Sunday, 06-Nov-94 08:49:37 GMT (obsolete)
ANSI C: Sun Nov 6 08:49:37 1994 (obsolete)
sockethttp_hash_name()
static unsigned sockethttp_hash_name (const char * name, size_t len) inline static
Hash HTTP header name for case-insensitive bucket lookup.
Parameters
name Pointer to null-terminated or length-bounded header name bytes.
len Exact byte length of name (excluding null if present).
Returns
Computed hash modulo SOCKETHTTP_HEADER_BUCKETS (0-30).
Thread Safety\n Yes - pure function, no side effects or shared state.
Implements case-insensitive DJB2 hash variant: folds input to lowercase during hashing for consistent header name bucketing per RFC 9110. Designed for low collision rate with typical HTTP headers.
See also
SOCKETHTTP_HEADER_BUCKETS for table size.
sockethttp_name_equal() companion for equality checks.
SocketHTTP_Headers_get() for usage in public API.
SocketHTTP_header_name_valid()
int SocketHTTP_header_name_valid (const char * name, size_t len) extern
Validate header name.
Parameters
name Header name
len Name length
Returns
1 if valid, 0 otherwise
Thread Safety\n Yes
Per RFC 9110, header names are tokens (tchar characters only).
SocketHTTP_header_value_valid()
int SocketHTTP_header_value_valid (const char * value, size_t len) extern
Validate header value.
Parameters
value Header value
len Value length
Returns
1 if valid (no NUL/CR/LF), 0 otherwise
Thread Safety\n Yes
SECURITY: Rejects NUL, CR, and LF characters to prevent HTTP header injection attacks (CWE-113). Per RFC 9110 Section 5.5, obs-fold (CRLF followed by SP/HTAB) is deprecated and should not be generated.
This stricter validation prevents:
CRLF injection for header manipulation
Response splitting attacks
Cache poisoning via injected headers
Session hijacking via injected Set-Cookie
SocketHTTP_Headers_add()
int SocketHTTP_Headers_add (SocketHTTP_Headers_T headers, const char * name, const char * value) extern
Add header (null-terminated strings).
Parameters
headers Header collection
name Header name
value Header value
Returns
0 on success, -1 on error (invalid name/value, limits exceeded)
Thread Safety\n No
Adds header, allowing duplicates. Use set() to replace existing.
SocketHTTP_Headers_add_n()
int SocketHTTP_Headers_add_n (SocketHTTP_Headers_T headers, const char * name, size_t name_len, const char * value, size_t value_len) extern
Add header with explicit lengths.
Parameters
headers Header collection
name Header name
name_len Name length
value Header value
value_len Value length
Returns
0 on success, -1 on error
Thread Safety\n No
SocketHTTP_Headers_at()
const SocketHTTP_Header * SocketHTTP_Headers_at (SocketHTTP_Headers_T headers, size_t index) extern
Get header by index.
Parameters
headers Header collection
index Header index (0-based)
Returns
Pointer to header, or NULL if index out of range
Thread Safety\n No
SocketHTTP_Headers_clear()
void SocketHTTP_Headers_clear (SocketHTTP_Headers_T headers) extern
Remove all headers.
Parameters
headers Header collection
Clears all headers but keeps the collection usable.
Thread Safety\n No (use external synchronization)
SocketHTTP_Headers_contains()
int SocketHTTP_Headers_contains (SocketHTTP_Headers_T headers, const char * name, const char * token) extern
Check if header contains token.
Parameters
headers Header collection
name Header name
token Token to search for (comma-separated list)
Returns
1 if token found (case-insensitive), 0 otherwise
Thread Safety\n No
Useful for headers like "Connection: keep-alive, upgrade"
SocketHTTP_Headers_count()
size_t SocketHTTP_Headers_count (SocketHTTP_Headers_T headers) extern
Get total header count.
Parameters
headers Header collection
Returns
Number of headers
Thread Safety\n No
SocketHTTP_Headers_get()
const char * SocketHTTP_Headers_get (SocketHTTP_Headers_T headers, const char * name) extern
Get first header value (case-insensitive).
Parameters
headers Header collection
name Header name to find
Returns
Header value (null-terminated), or NULL if not found
Thread Safety\n No (value may be invalidated by modifications)
SocketHTTP_Headers_get_all()
size_t SocketHTTP_Headers_get_all (SocketHTTP_Headers_T headers, const char * name, const char ** values, size_t max_values) extern
Get all values for header.
Parameters
headers Header collection
name Header name
values Output array of value pointers
max_values Maximum values to return
Returns
Number of values found
Thread Safety\n No
SocketHTTP_Headers_get_int()
int SocketHTTP_Headers_get_int (SocketHTTP_Headers_T headers, const char * name, int64_t * value) extern
Get header value as integer.
Parameters
headers Header collection
name Header name
value Output integer value
Returns
0 on success, -1 if not found or not a valid integer
Thread Safety\n No
SocketHTTP_Headers_has()
int SocketHTTP_Headers_has (SocketHTTP_Headers_T headers, const char * name) extern
Check if header exists.
Parameters
headers Header collection
name Header name
Returns
1 if exists, 0 otherwise
Thread Safety\n No
SocketHTTP_Headers_iterate()
int SocketHTTP_Headers_iterate (SocketHTTP_Headers_T headers, SocketHTTP_HeaderCallback callback, void * userdata) extern
Iterate over all headers.
Parameters
headers Header collection
callback Callback function
userdata User data passed to callback
Returns
0 if completed, or value returned by callback that stopped iteration
Thread Safety\n No
SocketHTTP_Headers_new()
SocketHTTP_Headers_T SocketHTTP_Headers_new (Arena_T arena) extern
Create a new empty HTTP header collection.
Parameters
arena Arena used for all internal allocations; must outlive the collection.
Returns
New header collection instance.
Exceptions
Arena_Failed if memory allocation fails (insufficient space in arena).
SocketHTTP_Failed if arena is NULL or internal initialization fails.
Thread Safety\n Yes, provided the arena is thread-safe or thread-local.
Note
All headers added to this collection will allocate from the provided arena.
See also
SocketHTTP_Headers_clear() to reuse the collection after clearing.
SocketHTTP_Headers_add() to populate with headers.
SocketHTTP_Headers_remove()
int SocketHTTP_Headers_remove (SocketHTTP_Headers_T headers, const char * name) extern
Remove first header with name.
Parameters
headers Header collection
name Header name
Returns
1 if removed, 0 if not found
Thread Safety\n No
SocketHTTP_Headers_remove_all()
int SocketHTTP_Headers_remove_all (SocketHTTP_Headers_T headers, const char * name) extern
Remove all headers with name.
Parameters
headers Header collection
name Header name
Returns
Number of headers removed
Thread Safety\n No
SocketHTTP_Headers_set()
int SocketHTTP_Headers_set (SocketHTTP_Headers_T headers, const char * name, const char * value) extern
Set header (replace if exists).
Parameters
headers Header collection
name Header name
value Header value
Returns
0 on success, -1 on error
Thread Safety\n No
Removes all existing headers with same name, then adds new one.
SocketHTTP_MediaType_matches()
int SocketHTTP_MediaType_matches (const SocketHTTP_MediaType * type, const char * pattern) extern
Check if media type matches pattern.
Parameters
type Parsed media type
pattern Pattern like "text/\*" or "application/json"
Returns
1 if matches, 0 otherwise
Thread Safety\n Yes
Wildcard * matches any subtype.
SocketHTTP_MediaType_parse()
int SocketHTTP_MediaType_parse (const char * value, size_t len, SocketHTTP_MediaType * result, Arena_T arena) extern
Parse Content-Type header.
Parameters
value Content-Type header value
len Length of value (0 for strlen)
result Output structure
arena Arena for parameter strings
Returns
0 on success, -1 on error
Thread Safety\n Yes
Parses: type/subtype[; param=value]*
SocketHTTP_method_name()
const char * SocketHTTP_method_name (SocketHTTP_Method method) extern
Get method name string.
Parameters
method HTTP method
Returns
Static string like "GET", or NULL for unknown
Thread Safety\n Yes
Referenced by request_handler().
SocketHTTP_method_parse()
SocketHTTP_Method SocketHTTP_method_parse (const char * str, size_t len) extern
Parse method string.
Parameters
str Method string (e.g., "GET", "POST")
len String length (0 for strlen)
Returns
HTTP method, or HTTP_METHOD_UNKNOWN if unrecognized
Thread Safety\n Yes
SocketHTTP_method_properties()
SocketHTTP_MethodProperties SocketHTTP_method_properties (SocketHTTP_Method method) extern
Get method semantic properties.
Parameters
method HTTP method
Returns
Method properties structure
Thread Safety\n Yes
SocketHTTP_method_valid()
int SocketHTTP_method_valid (const char * str, size_t len) extern
Check if string is valid HTTP method token.
Parameters
str Method string
len String length
Returns
1 if valid token per RFC 9110, 0 otherwise
Thread Safety\n Yes
Valid token chars: !#$%&'*+-.0-9A-Z^_`a-z|~
sockethttp_name_equal()
static int sockethttp_name_equal (const char * a, size_t a_len, const char * b, size_t b_len) inline static
Perform case-insensitive comparison of HTTP header names.
Parameters
a Pointer to first header name bytes.
a_len Byte length of first name.
b Pointer to second header name bytes.
b_len Byte length of second name.
Returns
1 if names match case-insensitively and lengths equal, 0 otherwise.
Thread Safety\n Yes - pure function using standard library strncasecmp().
Compares HTTP header field names per RFC 9110 5.2 rule: field names case-insensitive. Early length check avoids unnecessary strncasecmp call. Used in hash table lookup collision resolution.
Note
Does not validate input as tokens; assumes pre-validated names.
See also
sockethttp_hash_name() for complementary hashing.
strncasecmp(3) for implementation details.
SocketHTTP_Headers_get() and SocketHTTP_Headers_has() for usage.
Definition at line 150 of file SocketHTTP-private.h.
SocketHTTP_parse_accept()
size_t SocketHTTP_parse_accept (const char * value, size_t len, SocketHTTP_QualityValue * results, size_t max_results, Arena_T arena) extern
Parse Accept-style header.
Parameters
value Header value
len Length (0 for strlen)
results Output array
max_results Maximum results to return
arena Arena for strings
Returns
Number of results parsed
Thread Safety\n Yes
Parses comma-separated values with optional q= quality parameter. Results sorted by quality (highest first).
SocketHTTP_status_category()
SocketHTTP_StatusCategory SocketHTTP_status_category (int code) extern
Get status code category.
Parameters
code HTTP status code
Returns
Category (1-5), or 0 for invalid codes
Thread Safety\n Yes
SocketHTTP_status_reason()
const char * SocketHTTP_status_reason (int code) extern
Get reason phrase for status code.
Parameters
code HTTP status code
Returns
Static reason phrase, or "Unknown" for unrecognized codes
Thread Safety\n Yes
SocketHTTP_status_valid()
int SocketHTTP_status_valid (int code) extern
Check if status code is valid.
Parameters
code HTTP status code
Returns
1 if code is 100-599, 0 otherwise
Thread Safety\n Yes
SocketHTTP_URI_build()
ssize_t SocketHTTP_URI_build (const SocketHTTP_URI * uri, char * output, size_t output_size) extern
Build URI string from components.
Parameters
uri URI components
output Output buffer
output_size Buffer size
Returns
Length written (excluding null), or -1 if buffer too small
Thread Safety\n Yes
Builds: scheme://[userinfo@]host[:port]path[?query][#fragment]
SocketHTTP_URI_decode()
ssize_t SocketHTTP_URI_decode (const char * input, size_t len, char * output, size_t output_size) extern
Percent-decode string.
Parameters
input Input string (may contain XX sequences)
len Input length
output Output buffer
output_size Output buffer size
Returns
Output length, or -1 on error (invalid encoding or buffer too small)
Thread Safety\n Yes
SocketHTTP_URI_encode()
ssize_t SocketHTTP_URI_encode (const char * input, size_t len, char * output, size_t output_size) extern
Percent-encode string.
Parameters
input Input string
len Input length
output Output buffer
output_size Output buffer size
Returns
Output length (excluding null), or -1 if buffer too small
Thread Safety\n Yes
Encodes characters that are not unreserved per RFC 3986. Unreserved: A-Z a-z 0-9 - . _ ~
SocketHTTP_URI_get_port()
int SocketHTTP_URI_get_port (const SocketHTTP_URI * uri, int default_port) extern
Get port with default fallback.
Parameters
uri Parsed URI
default_port Default port if not specified (e.g., 80 for http)
Returns
Explicit port from URI, or default_port if uri->port == -1
Thread Safety\n Yes
SocketHTTP_URI_is_secure()
int SocketHTTP_URI_is_secure (const SocketHTTP_URI * uri) extern
Check if URI uses secure scheme.
Parameters
uri Parsed URI
Returns
1 if scheme is "https" or "wss", 0 otherwise
Thread Safety\n Yes
SocketHTTP_URI_parse()
SocketHTTP_URIResult SocketHTTP_URI_parse (const char * uri, size_t len, SocketHTTP_URI * result, Arena_T arena) extern
Parse and validate a URI string into components.
Parameters
uri Input URI string (absolute or relative reference).
len Length of URI (0 to use strlen(uri)).
[out] result Pointer to SocketHTTP_URI structure to populate.
arena Arena for allocating parsed string components (must outlive result).
Returns
URI_PARSE_OK on success, or specific error code on failure.
Exceptions
Arena_Failed if memory allocation for components fails.
SocketHTTP_InvalidURI on invalid URI syntax, malformed components, or validation failures (e.g., invalid host, port out of range).
Thread Safety\n Yes, if arena is thread-safe or thread-local.
Parses URI per RFC 3986 generic syntax, supporting absolute URIs, origin form, and relative refs. Validates scheme, host (including [IPv6]), port, path, query, fragment. Rejects overly long URIs (> SOCKETHTTP_MAX_URI_LEN) and invalid characters. IPv6 hosts must be in RFC 3986 bracketed form. Does not percent-decode; components retain original encoding (use SocketHTTP_URI_decode()). Userinfo parsed but flagged as deprecated. Path is always non-NULL (empty for no path).
Note
Result strings point into arena-allocated memory or input buffer substrings.
See also
SocketHTTP_URI struct for component details.
SocketHTTP_URI_build() to reconstruct URI string from parsed components.
SocketHTTP_URI_get_port() for port resolution with defaults.
SocketHTTP_URI_result_string() for error descriptions.
SocketHTTP_URI_result_string()
const char * SocketHTTP_URI_result_string (SocketHTTP_URIResult result) extern
Get error description.
Parameters
result Parse result code
Returns
Static string describing the result
Thread Safety\n Yes
SocketHTTP_version_parse()
SocketHTTP_Version SocketHTTP_version_parse (const char * str, size_t len) extern
Parse version string.
Parameters
str Version string (e.g., "HTTP/1.1")
len String length (0 for strlen)
Returns
HTTP version, or HTTP_VERSION_0_9 if unrecognized
Thread Safety\n Yes
SocketHTTP_version_string()
const char * SocketHTTP_version_string (SocketHTTP_Version version) extern
Get version string.
Parameters
version HTTP version
Returns
Static string like "HTTP/1.1", or "HTTP/?" for unknown
Thread Safety\n Yes
SocketHTTPServer_config_defaults()
void SocketHTTPServer_config_defaults (SocketHTTPServer_Config * config) extern
Initialize SocketHTTPServer_Config with safe default values.
Populates the configuration structure with production-ready defaults:
port: 8080
bind_address: "0.0.0.0"
backlog: 128
max_header_size: 64KB
max_body_size: 10MB
timeouts: 30s request, 60s keepalive/write
limits: 1000 connections, 100 per client, etc.
TLS: NULL (HTTP)
HTTP/2 upgrade: disabled
Customize fields after initialization before passing to SocketHTTPServer_new(). Validates basic config sanity (e.g., positive limits) but does not bind/test.
Parameters
config Pointer to configuration structure to initialize. Must not be NULL; contents overwritten.
Thread Safety\n Yes - pure function, no side effects or shared state.
Note
Defaults can be overridden at compile-time via #defines (e.g., HTTPSERVER_DEFAULT_PORT).
See also
SocketHTTPServer_new() which consumes this config.
SocketHTTPServer_Config for field details and ranges.
Referenced by main().
SocketHTTPServer_drain()
int SocketHTTPServer_drain (SocketHTTPServer_T server, int timeout_ms) extern
Initiate graceful server shutdown by draining active connections.
Transitions server to DRAINING state: closes listening socket (no new accepts), allows in-flight requests/connections to complete naturally via timeouts or finish(). After specified timeout (or infinite), force-closes any remaining to STOPPED. Integrates with poll/process loop; call drain_poll() or drain_wait() to monitor. Signals OS/epoll to stop queuing new SYNs if possible.
Parameters
server Server instance (running state).
timeout_ms Max ms to wait for graceful completion (-1=infinite, 0=immediate force).
Returns
0 if drain started successfully, -1 on error (already stopped/draining).
Note
Existing connections: requests handled, but no new on them after start.
Timeout triggers abrupt close (possible data loss for unfinished responses).
Call before free() for clean shutdown; drain_wait() for blocking.
Stats preserved; errors during drain logged/incremented.
See also
SocketHTTPServer_drain_poll() to check progress in loop.
SocketHTTPServer_drain_wait() blocking convenience.
SocketHTTPServer_state() to query current state.
SocketHTTPServer_set_drain_callback() for completion notification.
docs/SIGNALS.md "Graceful Shutdown" for signal integration.
Thread Safety\n No - changes server state globally.
Exceptions
SocketHTTPServer_Failed if internal timer/setup fails.
SocketHTTPServer_drain_poll()
int SocketHTTPServer_drain_poll (SocketHTTPServer_T server) extern
Non-blocking check of drain progress and remaining work.
Queries number of active connections during DRAINING: polls internal pool/timer. Returns count of connections needing completion (processing or idle but open). Call in event loop (with process()) until 0 (complete) or -1 (timed out, force-closed). Complements drain_wait() for custom loops or integration.
Parameters
server Server in DRAINING (ignore otherwise).
Returns
>0 active connections remaining, 0 fully drained (STOPPED soon), -1 drain timed out (force-close triggered, state STOPPED).
Note
Decreases as requests finish/connections idle-timeout.
Call frequently during drain; pairs with process() for progress.
On -1, remaining connections closed abruptly (possible aborted requests).
Callback invoked on 0 or -1 transition.
See also
SocketHTTPServer_drain() initiates draining.
SocketHTTPServer_drain_wait() blocking wrapper using this.
SocketHTTPServer_state() alternative state query.
SocketHTTPServer_Stats.active_connections cross-check.
docs/SIGNALS.md for poll in signal handlers.
Thread Safety\n No - snapshots internal counts, may race.
SocketHTTPServer_drain_remaining_ms()
int64_t SocketHTTPServer_drain_remaining_ms (SocketHTTPServer_T server) extern
Calculate remaining time before drain timeout forces connection closure.
Returns ms left until DRAINING state force-closes lingering connections. Uses monotonic clock for accuracy; accounts for elapsed since drain start. 0 indicates immediate force-close imminent or already STOPPED. Useful for logging warnings or client notifications during shutdown.
Parameters
server Server instance (in DRAINING for meaningful >0).
Returns
>0 ms remaining, 0 not draining/imminent force, -1 infinite timeout.
Note
Precision ~1ms; negative not returned (clamped).
Updates dynamically as drain progresses/time passes.
When <=0, server may transition to STOPPED soon.
See also
SocketHTTPServer_state() pair with for full status.
SocketHTTPServer_drain() sets initial timeout.
Socket_get_monotonic_ms() underlying time source.
SocketHTTPServer_drain_wait() uses similar logic.
Thread Safety\n Yes - atomic computation from cached deadlines.
SocketHTTPServer_drain_wait()
int SocketHTTPServer_drain_wait (SocketHTTPServer_T server, int timeout_ms) extern
Block until graceful drain completes or times out.
Convenience function to wait for drain process: repeatedly calls process(0) and drain_poll() until STOPPED or timeout. Handles the loop internally. Uses provided timeout or falls back to drain() timeout if -1. Non-blocking alternative: manual loop with drain_poll().
Parameters
server Server in DRAINING state (after drain()).
timeout_ms Max additional ms to wait (-1=use drain timeout, 0=check once).
Returns
0 if fully drained gracefully (STOPPED, no force-close), -1 if timed out (remaining connections force-closed).
Note
Continues processing events during wait (requests complete).
Infinite timeout (-1) blocks forever if stuck (e.g., hanging client).
After return, server STOPPED; safe to free().
Callback (if set) invoked on completion regardless.
See also
SocketHTTPServer_drain() to initiate.
SocketHTTPServer_drain_poll() for non-blocking progress.
SocketHTTPServer_state() post-wait verification.
SocketHTTPServer_drain_remaining_ms() for time left.
Thread Safety\n No - blocks calling thread, modifies state.
Exceptions
Propagates from process()/drain_poll() (rare during shutdown).
SocketHTTPServer_fd()
int SocketHTTPServer_fd (SocketHTTPServer_T server) extern
Retrieve the file descriptor of the listening socket for external polling.
Allows integration with custom event loops (e.g., external SocketPoll or other libraries like libevent). Monitor for POLLIN to detect new connection attempts. Server's internal poll is still active if using SocketHTTPServer_process(); for full external control, avoid internal processing and handle accepts manually.
Returns -1 if server not started or stopped.
Parameters
server Server instance (started via SocketHTTPServer_start()).
Returns
Valid file descriptor (>=0) for listening socket, or -1 if not listening.
Thread Safety\n Yes - atomic read of cached fd.
Note
FD remains owned by server; do not close() it.
For accepts, use Socket_accept(server_fd) and add to your poll.
When using external poll, call server process functions manually or bypass.
See also
SocketHTTPServer_poll() for full internal poll instance.
Socket_accept() for manual connection acceptance.
Event System Group for polling details.
SocketHTTPServer_free()
void SocketHTTPServer_free (SocketHTTPServer_T * server) extern
Dispose of HTTP server instance and release all resources.
Closes listening socket, frees connection pool, timers, internal buffers, and arena allocations. Any ongoing requests are aborted and connections closed abruptly (no graceful drain). Call SocketHTTPServer_stop() or SocketHTTPServer_drain() first for clean shutdown.
Sets *server to NULL on success. Idempotent: safe to call on NULL or already-freed server.
Parameters
server Pointer to server instance (set to NULL after free). Must not be NULL.
Exceptions
SocketHTTPServer_Failed on internal cleanup errors (rare).
Thread Safety\n No - concurrent access to server undefined; use mutex if multi-threaded.
Warning
Does not wait for in-flight requests; data loss possible if called mid-process.
Note
TLS contexts are not freed (referenced only).
See also
SocketHTTPServer_drain_wait() for graceful shutdown before free.
SocketHTTPServer_stop() to halt without full cleanup.
Arena_T for memory management details.
Referenced by main().
SocketHTTPServer_new()
SocketHTTPServer_T SocketHTTPServer_new (const SocketHTTPServer_Config * config) extern
Allocate and initialize a new HTTP server instance.
Creates server with given configuration, allocating internal resources (arena, poll instance, buffers). Does not start listening; call SocketHTTPServer_start() or integrate with external poll loop. Validates config for sanity (e.g., valid port, limits >0).
Ownership: Caller owns the returned instance; free with SocketHTTPServer_free(). Internal resources (sockets, timers) managed automatically.
Parameters
config Configuration structure (copied internally; can be stack or reused). Must not be NULL. Invalid values may raise exceptions.
Returns
Opaque SocketHTTPServer_T instance on success.
Exceptions
SocketHTTPServer_Failed on memory allocation failure or invalid config.
Arena_Failed if internal arena allocation fails (propagated).
Thread Safety\n Yes - but concurrent calls may contend on system resources (e.g., ports).
Note
Config TLS context is referenced, not owned; manage its lifetime separately.
Server uses internal SocketPool for connection management if limits allow.
See also
SocketHTTPServer_config_defaults() to prepare config.
SocketHTTPServer_start() to begin listening.
SocketHTTPServer_free() for cleanup.
Connection Management for pooling details.
Referenced by main().
SocketHTTPServer_poll()
SocketPoll_T SocketHTTPServer_poll (SocketHTTPServer_T server) extern
Access the internal SocketPoll_T instance for custom event handling.
Provides direct access to server's poll multiplexer for advanced use cases:
Add custom fds/timers to the same poll loop.
Inspect registered sockets or events.
Replace or augment internal polling logic.
Returned poll is shared; modifications affect server behavior. Do not free() the returned poll (owned by server).
Parameters
server Server instance (started or not; NULL if not initialized).
Returns
Pointer to internal SocketPoll_T, or NULL if server invalid/not started.
Thread Safety\n Yes - returns const view, but modifications not thread-safe.
Warning
Adding/removing affects server; use cautiously to avoid races.
Internal timers/connections registered; do not del() them arbitrarily.
See also
SocketPoll_add(), SocketPoll_mod() for usage.
SocketHTTPServer_process() which uses this internally.
Event System Group for poll API details.
SocketTimer_add() for timer integration example.
SocketHTTPServer_process()
int SocketHTTPServer_process (SocketHTTPServer_T server, int timeout_ms) extern
Main event loop step: poll, accept, parse, handle requests.
Performs a single iteration of the internal event loop:
Polls registered fds (listening socket + client connections + timers) for timeout_ms.
Accepts new connections up to configured limits (rate, per-IP).
Reads/parses incoming data on connections (HTTP/1.1 or 2 frames).
Invokes validator and handler for complete requests.
Writes pending responses, applies flow control (HTTP/2).
Cleans up idle/timeout connections.
Triggers drain callback if applicable.
For continuous operation, call in loop with timeout -1 (infinite, interruptible). For integration, use smaller timeouts or external poll with SocketHTTPServer_fd().
Parameters
server Running server (started via SocketHTTPServer_start()).
timeout_ms Maximum wait time in ms (-1 = infinite/block until event).
Returns
Number of requests fully processed (handler invoked + response sent), or -1 on fatal error (raises exception).
Exceptions
SocketHTTPServer_ProtocolError on malformed requests.
SocketHTTPServer_Failed on I/O or internal errors.
Thread Safety\n No - advances shared server state.
Note
Returns early on timeout even if events pending; call repeatedly.
For high performance, tune SocketPoll via SocketHTTPServer_poll().
Metrics updated internally; query with SocketHTTPServer_stats().
See also
SocketHTTPServer_poll() for low-level poll access.
SocketHTTPServer_fd() for hybrid external/internal loop.
Event System for polling backend details.
Socket_get_monotonic_ms() for timing consistency.
Referenced by main().
SocketHTTPServer_Request_arena()
Arena_T SocketHTTPServer_Request_arena (SocketHTTPServer_Request_T req) extern
Get the Arena_T used for this request's allocations.
Provides per-request arena for temporary allocations (e.g., parsing buffers, response data). All request-local memory freed automatically after finish(). Use for short-lived objects during handler execution.
Parameters
req Request context.
Returns
Arena_T instance owned by connection/request (do not dispose).
See also
Arena_alloc(), Arena_calloc() for allocation.
Arena_clear() if needing reset mid-request (rare).
Foundation Group for arena details.
memory for allocation best practices.
SocketHTTPServer_Request_begin_stream()
int SocketHTTPServer_Request_begin_stream (SocketHTTPServer_Request_T req) extern
Initiate a streaming (chunked) response to the client.
Starts the response by sending status and headers with Transfer-Encoding: chunked (or equivalent HTTP/2 frames). Enables sending body in arbitrary chunks without knowing total length upfront. Ideal for dynamic content generation, large files, or real-time data (e.g., SSE, progress updates). Headers sent immediately; subsequent send_chunk() append body chunks. Must follow with end_stream() to finalize (sends trailers if any).
Parameters
req Request context (headers/status must be set prior).
Returns
0 on success (headers sent, ready for chunks), -1 on failure.
Note
Do not call status(), header(), body_data(), body_string(), or finish() after.
Chunk size unlimited per call, but internal buffers apply (8KB typical).
Client must support chunked (HTTP/1.1 default); HTTP/1.0 may fail.
For HTTP/2, translates to multiple DATA frames with end-stream flag on last.
Warning
No Content-Length set; clients buffer until end_stream().
See also
SocketHTTPServer_Request_send_chunk() to emit body chunks.
SocketHTTPServer_Request_end_stream() to finalize and close body.
SocketHTTP1_chunk_encode() low-level chunk formatting.
RFC 9112 Section 7.1 for chunked encoding spec.
docs/HTTP.md "Streaming Responses" for examples.
Thread Safety\n No - commits response, modifies connection state.
Exceptions
SocketHTTPServer_Failed on immediate send failure (e.g., closed conn).
SocketHTTPServer_Request_body()
const void * SocketHTTPServer_Request_body (SocketHTTPServer_Request_T req) extern
Get pointer to fully buffered request body data.
Returns the complete request body after full read/parse. Only valid if not using body streaming (default buffering mode). For large bodies exceeding max_body_size, returns NULL (413 sent). Data owned by server; valid until request finish, do not free/modify.
Parameters
req Request context.
Returns
Pointer to body bytes, or NULL if no body, streaming, or error.
Warning
For security, avoid trusting large bodies; validate Content-Type/Length.
See also
SocketHTTPServer_Request_body_len() for size.
SocketHTTPServer_Request_body_stream() to enable chunked processing.
SocketBuf_secureclear() if handling sensitive data post-use.
Referenced by request_handler().
SocketHTTPServer_Request_body_data()
void SocketHTTPServer_Request_body_data (SocketHTTPServer_Request_T req, const void * data, size_t len) extern
Set the complete response body from a data buffer.
Provides the full response body content. The body is sent after headers during finish(). Automatically computes and sets Content-Length header. For large or dynamic bodies (e.g., file streams), prefer streaming API. Data is referenced or copied internally; remains valid until finish().
Parameters
req Request context.
data Pointer to response body bytes (may be NULL if len=0).
len Exact length of body in bytes.
Note
Sets Content-Type to application/octet-stream if unspecified.
Supports zero-length bodies (no Content-Length or Transfer-Encoding).
Compression (e.g., gzip) applied if client accepts via Accept-Encoding.
For text content, explicitly set Content-Type with charset.
See also
SocketHTTPServer_Request_body_string() for null-terminated strings.
SocketHTTPServer_Request_begin_stream() for chunked/dynamic streaming.
SocketHTTPServer_Request_header("Content-Type", "application/json") for type.
SocketHTTP_Headers_set() for advanced header control.
Thread Safety\n No - sets shared body state.
Exceptions
SocketHTTPServer_Failed if len exceeds max_body_size or allocation fails.
Referenced by request_handler().
SocketHTTPServer_Request_body_expected()
int64_t SocketHTTPServer_Request_body_expected (SocketHTTPServer_Request_T req) extern
Retrieve the expected total length of the request body.
Returns the advertised body size from Content-Length header or -1 if unknown (e.g., chunked transfer-encoding or missing header). Useful for pre-allocating buffers or deciding streaming vs. buffering in handler/validator. Accurate after headers parsed, before body read (even if streaming enabled).
Parameters
req Request context (valid during handler or body callback).
Returns
>=0 exact expected bytes (Content-Length), or -1 if undetermined/chunked.
Note
For chunked, total unknown until final chunk; use body_len() post-complete.
0 indicates empty body (common for GET/HEAD).
May differ from actual received if client lies/truncated.
See also
SocketHTTPServer_Request_body_len() for actual received length (post-read).
SocketHTTPServer_Request_is_chunked() to detect transfer encoding.
SocketHTTP1_Parser_content_length() underlying parser value.
docs/HTTP.md "Request Body Handling" for details.
Thread Safety\n No - reads request state snapshot.
SocketHTTPServer_Request_body_len()
size_t SocketHTTPServer_Request_body_len (SocketHTTPServer_Request_T req) extern
Retrieve the length of the request body in bytes.
Returns size of body from Content-Length or parsed chunked total. 0 for no body (e.g., GET). Matches body() return if buffered. Accurate even if streaming (tracks total received).
Parameters
req Request context.
Returns
Body length in bytes, or 0 if unknown/no body.
See also
SocketHTTPServer_Request_body() for data access.
SocketHTTPServer_Request_body_expected() for advertised length (pre-read).
SocketHTTP1_Parser_content_length() underlying parser info.
Referenced by request_handler().
SocketHTTPServer_Request_body_stream()
void SocketHTTPServer_Request_body_stream (SocketHTTPServer_Request_T req, SocketHTTPServer_BodyCallback callback, void * userdata) extern
Enable streaming body callback.
Parameters
req Request context
callback Callback invoked for each body chunk @userdata User data passed to callback
Enables streaming mode for receiving request body. When enabled:
Body chunks are delivered via callback as they arrive
Body is NOT buffered in memory
SocketHTTPServer_Request_body() returns NULL
Call this before calling finish() to receive body data.
Thread Safety\n No
SocketHTTPServer_Request_body_string()
void SocketHTTPServer_Request_body_string (SocketHTTPServer_Request_T req, const char * str) extern
Set the response body from a null-terminated C string.
Convenience function for text-based responses. Computes length via strlen() and sets body accordingly. Equivalent to body_data(str, strlen(str)). Ideal for simple responses like JSON, HTML fragments, or plain text.
Parameters
req Request context.
str Pointer to null-terminated string (NULL for empty body).
Note
strlen() excludes null terminator; binary data with \0 requires body_data().
Sets Content-Type to text/plain; charset=utf-8 if not overridden.
Large strings buffered in memory; stream for generated content.
See also
SocketHTTPServer_Request_body_data() for binary data with explicit length.
SocketHTTPServer_Request_header("Content-Type", ...) to override type.
SocketHTTPServer_Request_begin_stream() for streaming text generation.
Thread Safety\n No.
Exceptions
Same as body_data(): allocation or size limit violations.
Referenced by request_handler(), and request_handler().
SocketHTTPServer_Request_client_addr()
const char * SocketHTTPServer_Request_client_addr (SocketHTTPServer_Request_T req) extern
Get the client (peer) IP address as string.
Returns formatted string representation of remote client address (IPv4/IPv6). From getpeername(); for proxied requests, use X-Forwarded-For header. Points to internal static buffer; valid during request, do not free. Format: "IP:port" or "unix:/path/to/socket".
Parameters
req Request context.
Returns
Client address string, or NULL if unknown (e.g., Unix domain).
Note
For rate limiting/IP tracking, prefer this over headers for accuracy.
See also
Socket_getpeeraddr() underlying call.
SocketIPTracker for IP-based limits.
Referenced by request_handler(), and request_handler().
SocketHTTPServer_Request_end_stream()
int SocketHTTPServer_Request_end_stream (SocketHTTPServer_Request_T req) extern
End streaming response.
Parameters
req Request context
Sends the final zero-length chunk and completes the response. After calling, the request context is complete.
Returns
0 on success, -1 on error
Thread Safety\n No
SocketHTTPServer_Request_finish()
void SocketHTTPServer_Request_finish (SocketHTTPServer_Request_T req) extern
Finalize the response and transmit it to the client.
Serializes the configured status, headers, and body into an HTTP message and sends it over the connection. For non-streaming responses, full body sent. Marks the request as complete; subsequent modifications ignored. Handles protocol specifics: chunked for HTTP/1.1 without length, frames for HTTP/2. Connection kept alive if possible (protocol, headers, timeouts allow).
Parameters
req Request context (invalidated after this call; do not use further).
Note
Call exactly once per request, typically at end of handler.
If streaming enabled, call after end_stream() (finish() not needed).
Auto-flushes buffers; blocks until sent or error/timeout.
Updates server stats (bytes sent, latency, error counters if fails).
Warning
After call, req and its contents may be freed/recycled.
See also
SocketHTTPServer_Request_status() and Request_header() before finish.
SocketHTTPServer_Request_body_data() or streaming alternatives.
SocketHTTPServer_Request_end_stream() for streaming completion.
SocketHTTPServer_process() underlying transmission loop.
Thread Safety\n No - finalizes shared state, sends on connection fd.
Exceptions
SocketHTTPServer_Failed on I/O errors (e.g., broken pipe, timeout).
SocketHTTPServer_ProtocolError on serialization failures (rare).
Referenced by request_handler(), and request_handler().
SocketHTTPServer_Request_header()
void SocketHTTPServer_Request_header (SocketHTTPServer_Request_T req, const char * name, const char * value) extern
Add a header field to the HTTP response.
Appends a name-value pair to the response headers collection. Headers are sent immediately after the status line when finish() or streaming begins. Supports multiple values for the same header (e.g., repeated Set-Cookie). Header names are normalized to lowercase for consistency.
Parameters
req Request context (valid during handler or validator).
name Null-terminated header name string (e.g., "Content-Type", "Authorization").
value Null-terminated header value string (may contain commas for multi-value).
Note
Validates header name and value per RFC 7230/9110: tokens, no invalid chars.
Server automatically adds mandatory headers: Date, Connection, Server (configurable).
Content-Length auto-set if body provided and not chunked.
For security, sanitize values to prevent injection (e.g., CRLF in values -> header smuggling).
See also
SocketHTTP_Headers_T for underlying header storage and advanced ops.
SocketHTTP_Headers_add() similar low-level function.
SocketHTTPServer_Request_headers() for direct access/modification.
docs/SECURITY.md "HTTP Header Security" for best practices and risks.
SocketHTTP_Headers_get() to query existing headers.
Thread Safety\n No - concurrent modifications to same req may corrupt headers.
Exceptions
SocketHTTPServer_ProtocolError if name/value invalid (e.g., empty name, control chars).
Referenced by request_handler(), and request_handler().
SocketHTTPServer_Request_headers()
SocketHTTP_Headers_T SocketHTTPServer_Request_headers (SocketHTTPServer_Request_T req) extern
Access the parsed request headers as a headers container.
Returns view of all request headers parsed from HTTP message. Headers are case-insensitive keys with multi-value support. Modifications to returned headers affect response (but not request). Valid during request lifetime.
Parameters
req Request context.
Returns
SocketHTTP_Headers_T instance (do not free; server-owned).
Note
Common headers like Host, Content-Length auto-parsed/extracted.
For streaming body, body not available; use callback instead.
See also
SocketHTTP_Headers_add(), get(), etc. for manipulation.
SocketHTTP_Headers_get() for single header lookup.
SocketHTTPServer_Request_is_chunked()
int SocketHTTPServer_Request_is_chunked (SocketHTTPServer_Request_T req) extern
Determine if the request body uses chunked transfer encoding.
Checks the Transfer-Encoding header for "chunked" (case-insensitive). Chunked used when Content-Length absent (HTTP/1.1 requirement for unknown length). Indicates body arrives in delimited chunks; total length unknown until end. Relevant for streaming decisions or buffer management.
Parameters
req Request context (after headers parsed).
Returns
1 if chunked encoding detected, 0 if not (fixed length or no body).
Note
HTTP/2 uses DATA frames (similar to chunked, but protocol-handled).
False for fixed-length bodies or GET/HEAD (no body).
In validator/handler, before body read; remains constant.
See also
SocketHTTPServer_Request_body_expected() for length if not chunked.
SocketHTTPServer_Request_body_stream() compatible with chunked.
SocketHTTP1_chunk_encode() for response chunking.
RFC 9112 Section 7.1 "Chunked Transfer Coding".
Thread Safety\n Yes - const query on parsed headers.
SocketHTTPServer_Request_is_http2()
int SocketHTTPServer_Request_is_http2 (SocketHTTPServer_Request_T req) extern
Check if the underlying connection uses HTTP/2 protocol.
Queries the negotiated protocol version for the connection/stream. HTTP/2 detected via ALPN (TLS), prior-knowledge, or upgrade (h2c). Enables/disables HTTP/2 features: multiplexing, push, header compression.
Parameters
req Request context (any stream on connection).
Returns
1 if HTTP/2 (or h2 via upgrade), 0 if HTTP/1.1 or lower.
Note
Constant for connection lifetime; not per-request.
HTTP/2 requires prior negotiation; plain HTTP/1.1 cannot upgrade post-start.
For h2c (cleartext HTTP/2), requires config enable_h2c_upgrade.
See also
SocketHTTPServer_Request_version() for exact version enum.
SocketHTTPServer_Config.max_version to control support.
SocketHTTP2_Conn for HTTP/2-specific APIs.
docs/HTTP.md "HTTP/2 Negotiation" for details.
Thread Safety\n Yes - reads immutable connection flag.
SocketHTTPServer_Request_is_websocket()
int SocketHTTPServer_Request_is_websocket (SocketHTTPServer_Request_T req) extern
Check if the request is a WebSocket upgrade attempt.
Inspects Upgrade: websocket header, Sec-WebSocket-Key, etc., per RFC 9112. True if client requests protocol switch from HTTP to WebSocket (ws/wss). Typically on GET with specific headers; server can accept/reject.
Parameters
req Request context (after headers parsed, in handler/validator).
Returns
1 if valid WebSocket upgrade request, 0 if not (standard HTTP).
Note
Requires HTTP/1.1+; HTTP/2 uses extended CONNECT but not standard here.
Validates all required headers (Upgrade, Connection: Upgrade, Sec-WebSocket-Key).
Origin header checked against config if security enabled.
See also
SocketHTTPServer_Request_upgrade_websocket() to accept and get WS handle.
SocketWS_T for WebSocket protocol handling.
RFC 9112 Appendix B "WebSocket Upgrade" for handshake details.
docs/WEBSOCKET.md for WebSocket integration guide.
Thread Safety\n Yes - const header check.
Referenced by request_handler().
SocketHTTPServer_Request_memory_used()
size_t SocketHTTPServer_Request_memory_used (SocketHTTPServer_Request_T req) extern
Query approximate memory usage for the underlying connection.
Sums allocations in connection arena, buffers (in/out), parsed structures, and body if buffered. Useful for monitoring/leak detection or limits. Does not include listening socket or global server memory.
Parameters
req Request context (per-connection view).
Returns
Estimated bytes allocated for this connection's resources.
Thread Safety\n No - snapshot of volatile state.
Note
Approximate; excludes kernel buffers, threads, etc.
Decreases after response sent and idle connections cleaned.
See also
SocketHTTPServer_stats() for aggregate server memory via pools.
Socket_debug_live_count() for global leak checks.
SocketHTTPServer_Request_method()
SocketHTTP_Method SocketHTTPServer_Request_method (SocketHTTPServer_Request_T req) extern
Retrieve the parsed HTTP method from the request.
Extracts the method from the request line (e.g., GET, POST, PUT). Valid after request parsing in handler or validator callbacks.
Parameters
req Request context.
Returns
SocketHTTP_Method enum value corresponding to the method.
See also
SocketHTTP_method_name() to convert to string (e.g., "GET").
SocketHTTP_method_properties() for method attributes (safe, idempotent, etc.).
SocketHTTP_method_parse() for parsing raw strings.
Referenced by request_handler().
SocketHTTPServer_Request_path()
const char * SocketHTTPServer_Request_path (SocketHTTPServer_Request_T req) extern
Get the request path (URI path component).
Returns the path part of the request URI after parsing (e.g., "/api/users/123"). Decoded and normalized; does not include query string. Points to internal buffer; valid during request lifetime.
Parameters
req Request context.
Returns
Null-terminated path string, or NULL if invalid/unparsed.
Note
Path is percent-decoded; use SocketHTTP_URI_decode() for custom.
See also
SocketHTTPServer_Request_query() for query parameters.
SocketHTTP_URI_parse() for URI handling details.
Referenced by request_handler(), and request_handler().
SocketHTTPServer_Request_push()
int SocketHTTPServer_Request_push (SocketHTTPServer_Request_T req, const char * path, SocketHTTP_Headers_T headers) extern
Initiate an HTTP/2 server push of a related resource to the client.
Sends a promised PUSH_PROMISE frame followed by pushed response (HEADERS + DATA). Allows server to preemptively send resources likely needed by client (e.g., CSS/JS for HTML). Only functional on HTTP/2 connections; HTTP/1.x returns -1 (no push support). Client may refuse (via RST_STREAM); check return for success. Path relative to request URI authority; full URL constructed internally.
Parameters
req Request context on HTTP/2 stream.
path Target resource path (e.g., "/style.css"; relative).
headers Optional headers for pushed request (method GET assumed; :method can override).
Returns
0 if push initiated successfully, -1 if failed/unsupported (not HTTP/2, client refused, error).
Note
Push streams consume window/bandwidth; use judiciously to avoid DoS.
Client settings (e.g., ENABLE_PUSH=0) or GOAWAY may disable.
Pushed responses still subject to server config limits/timeouts.
Warning
Over-pushing harms performance; base on Cache-Control, Link headers.
See also
SocketHTTPServer_Request_is_http2() to check protocol support.
SocketHTTP2_Stream for low-level push control.
RFC 9113 Section 6.6 "Server Push" for specification.
docs/HTTP.md "HTTP/2 Server Push" for usage patterns.
Thread Safety\n No - allocates push stream on connection.
Exceptions
SocketHTTPServer_ProtocolError if HTTP/2 frame errors.
SocketHTTPServer_Request_query()
const char * SocketHTTPServer_Request_query (SocketHTTPServer_Request_T req) extern
Get the query string portion of the request URI.
Returns raw query string after '?' in URI (e.g., "id=123&name=foo"). Not parsed into params; caller must parse (see SocketHTTP for helpers). Points to internal buffer; valid during request.
Parameters
req Request context.
Returns
Query string (may be empty ""), or NULL if no query.
Note
Includes leading '?' if present; trim if needed.
See also
SocketHTTP_URI_parse() for full URI breakdown.
Query parsing Utilities in SocketHTTP (future or custom).
SocketHTTPServer_Request_send_chunk()
int SocketHTTPServer_Request_send_chunk (SocketHTTPServer_Request_T req, const void * data, size_t len) extern
Send response chunk.
Parameters
req Request context @data Chunk data
len Chunk length
Sends a chunk of the response body. Can be called multiple times. begin_stream() must be called first.
Returns
0 on success, -1 on error
Thread Safety\n No
SocketHTTPServer_Request_status()
void SocketHTTPServer_Request_status (SocketHTTPServer_Request_T req, int code) extern
Set the HTTP status code for the response.
Specifies the status code to send in the response (e.g., 200 OK, 404 Not Found, 500 Internal Server Error). Must be called before adding headers, body, or calling finish(). If not set, defaults to 200 OK. Server may override in error cases (e.g., parsing failures -> 400/500).
Parameters
req Request context (valid during handler callback).
code HTTP status code (100-599 range recommended; validated).
Note
Reason phrase auto-appended using SocketHTTP_status_reason(code).
For client errors (4xx), consider logging request details for debugging.
For redirects (3xx), pair with Location header.
See also
SocketHTTP_status_reason(int) for standard reason phrases.
SocketHTTP_status_category(int) to classify codes (1xx informational, 2xx success, etc.).
SocketHTTP_status_valid(int) to check valid range.
SocketHTTPServer_Request_header() to add response headers (e.g., Location for redirects).
SocketHTTPServer_Request_finish() to send after setting status/headers/body.
docs/HTTP.md "HTTP Response Guidelines" for best practices.
Thread Safety\n No - modifies shared request state.
Referenced by request_handler(), and request_handler().
SocketHTTPServer_Request_upgrade_websocket()
SocketWS_T SocketHTTPServer_Request_upgrade_websocket (SocketHTTPServer_Request_T req) extern
Accept WebSocket upgrade and switch protocol.
Performs WebSocket handshake: sends 101 Switching Protocols response with Sec-WebSocket-Accept key, then returns opaque WebSocket_T handle for framing. Transitions connection from HTTP to WebSocket (ws:// or wss:// over TLS). After upgrade, use SocketWS APIs for messages, close, etc.; HTTP functions invalid. Request context and HTTP state discarded post-upgrade.
Parameters
req Request context with valid upgrade request (is_websocket() true).
Returns
SocketWS_T instance for WebSocket operations, or NULL on failure (e.g., invalid handshake).
Note
Validates client key, computes accept value per RFC 6455.
Sec-WebSocket-Protocol negotiated if offered (config or first).
TLS remains active if HTTPS (becomes wss://).
Warning
Connection now WebSocket-only; no revert to HTTP.
Note
Metrics: upgrades counted in stats; errors logged.
See also
SocketHTTPServer_Request_is_websocket() to check before upgrade.
SocketWS_T and group__websocket for WebSocket API.
RFC 6455 "The WebSocket Protocol" for handshake spec.
docs/WEBSOCKET.md "Upgrading from HTTP" for examples and config.
Thread Safety\n No - switches connection state, consumes req.
Exceptions
SocketHTTPServer_ProtocolError on handshake validation failure.
SocketHTTPServer_Failed on response send error.
Referenced by request_handler().
SocketHTTPServer_Request_version()
SocketHTTP_Version SocketHTTPServer_Request_version (SocketHTTPServer_Request_T req) extern
Determine the HTTP protocol version of the request.
Parsed from request line or negotiated via ALPN/Upgrade (HTTP/2). Indicates capabilities: e.g., HTTP/1.1 supports keep-alive/chunked, HTTP/2 supports multiplexing/push.
Parameters
req Request context.
Returns
SocketHTTP_Version enum (HTTP_VERSION_1_1, HTTP_VERSION_2, etc.).
See also
SocketHTTP_Version for possible values.
SocketHTTPServer_Request_is_http2() convenience check.
SocketHTTP2_Conn for HTTP/2 specific handling.
SocketHTTPServer_set_drain_callback()
void SocketHTTPServer_set_drain_callback (SocketHTTPServer_T server, SocketHTTPServer_DrainCallback callback, void * userdata) extern
Register callback for graceful drain completion notification.
Sets function invoked when drain reaches STOPPED: either graceful (all done) or timed-out (force-closed). Called from event thread during/after process(). Useful for final cleanup, logging shutdown stats, or signaling parent process. Replaces prior callback; NULL disables. Set before drain() for immediate effect.
Parameters
server Server instance.
callback Drain completion handler or NULL to disable.
userdata User data forwarded to callback unchanged.
Note
Invoked once per drain cycle, even if multiple drain() calls.
If timed_out=1, check stats for aborted connections.
Safe to free() server from callback (after invocation).
Not called on abrupt free()/errors; use atexit or signals for those.
See also
SocketHTTPServer_DrainCallback signature: receives server, timed_out flag.
SocketHTTPServer_drain() to start process triggering callback.
SocketHTTPServer_Stats for post-drain metrics snapshot.
docs/SIGNALS.md "Shutdown Hooks" for integration.
Thread Safety\n No - updates server callback slot.
SocketHTTPServer_set_handler()
void SocketHTTPServer_set_handler (SocketHTTPServer_T server, SocketHTTPServer_Handler handler, void * userdata) extern
Register the primary request handler callback and associated user data.
Sets the callback invoked for every valid HTTP request after parsing and validation. Previous handler (if any) is replaced. NULL handler disables request handling (server accepts but immediately closes connections with 500).
Userdata is stored and passed unchanged to every invocation of handler. Can be changed dynamically; affects future requests only.
Parameters
server Server instance (must be created but not required to be started).
handler Callback function or NULL to disable handling.
userdata Opaque pointer passed to handler on each request.
Thread Safety\n No - updates shared server state.
Note
Handler must be thread-safe if server uses multi-threaded poll (advanced).
Set before starting or processing to avoid missing requests.
For dynamic routing, implement path/method logic inside handler.
See also
SocketHTTPServer_Handler for callback signature and responsibilities.
SocketHTTPServer_Validator for pre-handler middleware.
HTTP Group for request/response types.
Referenced by main().
SocketHTTPServer_set_rate_limit()
void SocketHTTPServer_set_rate_limit (SocketHTTPServer_T server, const char * path_prefix, SocketRateLimit_T limiter) extern
Register a rate limiter for specific endpoints or globally.
Associates a SocketRateLimit_T instance with a path prefix (e.g., "/api/"). Incoming requests matching prefix (via Request_path() starts-with) checked against limiter before handler invocation. Exceeded limits trigger 429 Too Many Requests with Retry-After. NULL path_prefix applies globally (all requests). NULL limiter disables for prefix. Supports dynamic updates; affects new requests only.
Parameters
server Server instance (running or not).
path_prefix Path prefix to match (e.g., "/api/v1", NULL=global), case-sensitive.
limiter Rate limiter (owned by caller; server references, not frees).
Note
Up to HTTPSERVER_MAX_RATE_LIMIT_ENDPOINTS (64 default) slots.
Path matching simple prefix; for regex/glob, implement in validator.
Per-IP limits via max_connections_per_client; this is per-endpoint RPS.
Stats: rate_limited counter incremented on rejections.
See also
SocketRateLimit_T from Utilities group for token bucket config.
SocketHTTPServer_set_validator() for custom rate logic.
SocketHTTPServer_Stats.rate_limited for monitoring.
Utilities Group for SocketRateLimit details.
docs/SECURITY.md "Rate Limiting" for deployment tips.
Thread Safety\n No - updates server map; use mutex for multi-thread.
SocketHTTPServer_set_validator()
void SocketHTTPServer_set_validator (SocketHTTPServer_T server, SocketHTTPServer_Validator validator, void * userdata) extern
Install a middleware validator callback for incoming requests.
Registers a function executed after parsing headers but before body read/handler. Ideal for early rejection: auth (tokens, JWT), rate limiting, CORS, schema validation. Validator can set reject_status (e.g., 401) and return 0 to short-circuit (no handler). Runs per-request; stateful validators must be thread-safe or per-connection. Replaces prior validator; NULL disables.
Parameters
server Server instance.
validator Callback or NULL to disable validation.
userdata Opaque data passed to each invocation.
Note
Executes in event thread; fast operations preferred to avoid blocking poll.
Access to method, path, query, headers; body unavailable yet (use stream for large).
Rejection sends minimal error response (status + basic headers); customize via validator.
Chain multiple via wrapper if needed, but single slot provided.
See also
SocketHTTPServer_Validator callback signature and usage.
SocketHTTPServer_Request_* accessors available in validator (no body()).
SocketHTTPServer_set_rate_limit() for built-in endpoint limiting.
docs/SECURITY.md "Middleware and Validation" for patterns.
Thread Safety\n No - replaces server callback; concurrent set races.
SocketHTTPServer_start()
int SocketHTTPServer_start (SocketHTTPServer_T server) extern
Bind to address/port and start listening for incoming connections.
Performs system bind(2)/listen(2) on configured address/port using dual-stack IPv6 preferred (falls back to IPv4 if needed). Sets socket to non-blocking, reuseaddr/reuseport, and integrates with internal poll loop. Marks server as running; subsequent calls are no-ops (returns 0).
Does not block; returns immediately after setup. Use SocketHTTPServer_process() or external poll on SocketHTTPServer_fd() to accept/process connections.
Parameters
server Initialized server instance (from SocketHTTPServer_new()).
Returns
0 on success (already running or bind/listen succeeded), -1 on error (errno set; may also raise exceptions).
Exceptions
SocketHTTPServer_BindFailed on bind/listen system errors (EADDRINUSE, etc.).
SocketHTTPServer_Failed on socket creation or config issues.
Thread Safety\n No - server state modified; concurrent calls undefined.
Note
Port 0 binds to ephemeral port; query Socket_getlocalport() after.
For HTTPS, ensure tls_context configured and SocketTLS_enable() integrated.
Conflicts with prior binds raise EADDRINUSE; check with netstat/ss.
See also
SocketHTTPServer_stop() to cease listening.
SocketHTTPServer_fd() for poll integration.
SocketConfig for global socket options affecting behavior.
Core I/O Group for underlying socket primitives.
Referenced by main().
SocketHTTPServer_state()
SocketHTTPServer_State SocketHTTPServer_state (SocketHTTPServer_T server) extern
Query the current lifecycle state of the server.
Returns enum indicating operational phase: RUNNING (normal), DRAINING (shutdown initiated), or STOPPED (no activity). Useful for monitoring, logging, or conditional logic during shutdown. Atomic read for concurrency safety.
Parameters
server Server instance (any state).
Returns
SocketHTTPServer_State: RUNNING, DRAINING, or STOPPED.
Note
RUNNING: accepting/processing; DRAINING: finishing existing; STOPPED: idle/closed.
State changes via start()/stop()/drain()/free().
During DRAINING, process()/poll continue until complete.
See also
SocketHTTPServer_State enum definition.
SocketHTTPServer_drain() triggers DRAINING.
SocketHTTPServer_stop() may lead to DRAINING if connections active.
SocketHTTPServer_free() finalizes to implicit STOPPED.
docs/SIGNALS.md for state in signal handlers.
Thread Safety\n Yes - atomic enum read, no side effects.
SocketHTTPServer_stats()
void SocketHTTPServer_stats (SocketHTTPServer_T server, SocketHTTPServer_Stats * stats) extern
Populate statistics structure with current server metrics snapshot.
Atomically copies all counters, gauges, and computed values (RPS, percentiles) into the provided struct. Includes reset-tolerant fields like active_connections. Latency stats based on recent samples (ring buffer of last N requests).
Parameters
server Server instance.
stats Pointer to SocketHTTPServer_Stats to fill (must not be NULL).
Thread Safety\n No - brief pause on some counters during copy.
Note
RPS window fixed at compile-time (HTTPSERVER_RPS_WINDOW_SECONDS).
Latency percentiles approximate; exact via external sampling.
Bytes counters include headers; net of compression if enabled.
See also
SocketHTTPServer_Stats for field meanings.
SocketHTTPServer_stats_reset() to clear counters.
SocketMetrics_getsnapshot() for library-wide metrics.
SocketHTTPServer_stats_reset()
void SocketHTTPServer_stats_reset (SocketHTTPServer_T server) extern
Reset all resettable statistics counters to zero.
Clears cumulative counts (total_requests, bytes, errors, etc.) for fresh monitoring period. active_connections and current latencies preserved (reflect live state). Max latency reset to current if desired. Idempotent but concurrent calls race (use mutex if needed).
Parameters
server Server instance.
Thread Safety\n No - modifies shared counters.
Note
Does not affect per-connection stats or pool internals.
Call periodically for rate calculations or after restarts.
See also
SocketHTTPServer_stats() to read before/after reset.
SocketPool for connection-specific resets.
SocketHTTPServer_stop()
void SocketHTTPServer_stop (SocketHTTPServer_T server) extern
Stop accepting new connections while allowing existing ones to complete.
Closes the listening socket to prevent new accepts. Existing connections continue processing requests until idle timeout, keep-alive expiry, or explicit drain. Does not abort in-flight requests or close client sockets. Server remains in running state until all connections drain or free().
Idempotent: safe to call multiple times.
Parameters
server Running server instance.
Thread Safety\n No - modifies server state.
Note
To force closure of all connections, use SocketHTTPServer_free() directly.
For graceful shutdown with timeout, prefer SocketHTTPServer_drain().
See also
SocketHTTPServer_drain() for full graceful shutdown.
SocketHTTPServer_state() to check status.
SocketPoll_del() if using external poll (server handles internally).
Referenced by main().
Variable Documentation
HTTP2_CLIENT_PREFACE
const unsigned char HTTP2_CLIENT_PREFACE[24] = "PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n" static
Client connection preface magic string per RFC 9113.
The fixed 24-byte sequence "\x50\x52\x49\x20\x2a\x20\x48\x54\x54\x50\x2f\x32\x2e\x30\x0d\x0a\x0d\x0a\x53\x4d\x0d\x0a\x0d\x0a" (ASCII: "PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n") sent by clients to initiate HTTP/2.
See also
RFC 9113 Section 3.5 HTTP/2 Connection Preface
http2_process_frame() for preface validation during handshake.
Definition at line 62 of file SocketHTTP2-private.h.
SocketHPACK_Error
const Except_T SocketHPACK_Error extern
SocketHPACK_Error - General HPACK operation failure.
Raised when:
Invalid header block encoding
Huffman decoding error
Integer overflow
Size limits exceeded
HPACK bomb detected
SocketHTTP_Failed
const Except_T SocketHTTP_Failed extern
SocketHTTP_Failed - Generic HTTP module failure.
Use for general errors in HTTP core utilities. Specific errors should use module exceptions like SocketHTTP_ParseError, SocketHTTP1_ParseError.
sockethttp_hex_value
const unsigned char sockethttp_hex_value[256] extern
Hexadecimal digit value lookup table for decoding and validation.
Static array[256] mapping ASCII characters to their hex value (0-15) for valid digits, or 255 for invalid characters. Supports '0'-'9', 'a'-'f', 'A'-'F'.
Essential for percent-decoding (XX sequences) in URIs and chunked encoding sizes.
See also
SOCKETHTTP_HEX_VALUE() macro.
SocketHTTP_URI_decode() for URI percent-decoding usage.
SocketHTTP1 chunk size parsing in HTTP/1.1.
SocketHTTP_InvalidHeader
const Except_T SocketHTTP_InvalidHeader extern
SocketHTTP_InvalidHeader - Invalid HTTP header name or value.
Raised when adding or validating headers that violate RFC 9110 rules:
Invalid token characters in header names
Control characters (CR/LF/NUL) in header values (prevents injection)
Exceeding max name/value size limits
Header count exceeding configured maximum
See also
SocketHTTP_Headers_add() returns error but may raise in future strict modes.
SocketHTTP_header_name_valid() and SocketHTTP_header_value_valid() checks.
SocketHTTP_InvalidURI
const Except_T SocketHTTP_InvalidURI extern
SocketHTTP_InvalidURI - Invalid URI syntax or validation failure.
Specific to URI parsing and validation failures, such as malformed scheme, invalid host (e.g., bad IPv6 literal), out-of-range port, or disallowed characters in path/query/fragment per RFC 3986.
See also
SocketHTTP_URI_parse() throws this on invalid URI components.
SocketHTTP_URI_encode() and SocketHTTP_URI_decode() for percent-encoding errors.
SocketHTTP_ParseError
const Except_T SocketHTTP_ParseError extern
SocketHTTP_ParseError - Error during core HTTP parsing operations.
Raised for syntax errors in HTTP-date parsing, media type parsing, content negotiation, or other core string parsing functions in SocketHTTP module.
See also
SocketHTTP_date_parse() may raise this for invalid date formats.
SocketHTTP_MediaType_parse() for media type syntax errors.
SocketHTTP_parse_accept() for Accept header parsing failures.
sockethttp_tchar_table
const unsigned char sockethttp_tchar_table[256] extern
Lookup table for valid HTTP token characters (tchar) per RFC 9110 5.6.
Static array[256] where non-zero value indicates the character is a valid token char for HTTP header field names and values (excluding separators like :, ;, etc.).
tchar ::= "!" / "#" / "$" / "%" / "&" / "'" / "*" / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~" / DIGIT / ALPHA
Used for fast validation in header parsing and media type processing.
See also
SOCKETHTTP_IS_TCHAR() macro for usage.
Thread Safety\n Yes - static const array, read-only.
See also
SocketHTTP_Headers_add() for header validation context.
sockethttp_uri_unreserved
const unsigned char sockethttp_uri_unreserved[256] extern
Lookup table for URI unreserved characters per RFC 3986 2.3.
Static array[256] where non-zero value indicates characters that do not require percent-encoding in URI components: ALPHA / DIGIT / "-" / "." / "_" / "~"
Used in URI encoding to identify safe characters and in decoding validation.
See also
SOCKETHTTP_IS_UNRESERVED() macro.
Thread Safety\n Yes - static const array, read-only.
See also
SocketHTTP_URI_encode() and SocketHTTP_URI_decode().
RFC 3986 2.3 for unreserved set definition.
SocketHTTPServer_BindFailed
const Except_T SocketHTTPServer_BindFailed extern
Exception raised when binding to address/port fails (EADDRINUSE, EADDRNOTAVAIL, etc.).
See also
SocketHTTPServer_start()
Referenced by main().
SocketHTTPServer_Failed
const Except_T SocketHTTPServer_Failed extern
Exception raised on general server failures such as allocation errors or internal state corruption.
See also
SocketHTTPServer_new(), SocketHTTPServer_free(), SocketHTTPServer_process()
Referenced by main().
SocketHTTPServer_ProtocolError
const Except_T SocketHTTPServer_ProtocolError extern
Exception raised on HTTP protocol violations or parsing errors.
See also
SocketHTTPServer_process(), SocketHTTPServer_Request_T accessors