Tetsuo Pulse: Core I/O Modules
Core I/O Modules
Fundamental socket primitives for TCP, UDP, Unix domain, and DNS operations.
Modules
Asynchronous DNS Resolution
Thread pool-based DNS resolution with guaranteed timeouts and SocketPoll integration.
Live Socket Counting Utilities
Thread-safe global counter for tracking active Socket_T instances.
Internal TLS Field Utilities
Utilities for initializing and managing TLS state in Socket_T.
SocketProxy Private Implementation Details
Proxy Tunneling Module
Transparent TCP proxy support with sync/async APIs.
Files
file Socket-private.h
Private implementation details for Socket module: internal structure and shared utilities. Internal use only - included by Socket_*.c implementation files.
file Socket.h
High-level TCP/IP and Unix domain socket interface.
file SocketBuf.h
Circular buffer for efficient socket I/O operations.
file SocketCommon-private.h
Private declarations for SocketCommon module providing shared socket infrastructure.
file SocketCommon.h
Common utilities shared between Socket and SocketDgram modules.
file SocketDgram-private.h
Internal implementation details for datagram (UDP) socket structure.
file SocketIO.h
Internal I/O abstraction layer for socket operations with TLS support.
file SocketProxy-private.h
Internal structures and functions for SocketProxy module.
file SocketProxy.h
Proxy tunneling module for HTTP CONNECT and SOCKS protocols.
Data Structures
struct SocketStats_T
Per-socket I/O statistics structure.
struct SocketTCPInfo
TCP connection information structure (Linux-specific).
struct SocketBase_T
Internal implementation of SocketBase_T opaque type.
struct SocketLiveCount
Thread-safe live count tracker for socket instances.
struct SocketProxy_Conn_T
Opaque proxy connection context for managing tunneling negotiation.
struct SocketProxy_Config
Configuration structure for proxy connections.
Macros
#define UDP_MAX_PAYLOAD
Maximum UDP payload size excluding headers.
#define SAFE_UDP_SIZE 1472UL /* Safe for Ethernet MTU (1500 - IP/UDP ~28) */
Safe UDP payload size for Ethernet MTU.
#define SOCKET_SENDFILE_FALLBACK_BUFFER_SIZE 8192
Fallback buffer size for sendfile operations.
#define SOCKET_MAX_TTL 255 /* Standard IP TTL max */
Maximum IP TTL (Time To Live) value.
#define SOCKET_IPV6_MAX_PREFIX 128 /* IPv6 address bits */
Maximum IPv6 prefix length in bits.
#define SOCKET_IPV4_MAX_PREFIX 32 /* IPv4 address bits */
Maximum IPv4 prefix length in bits.
#define SOCKET_MAX_PORT 65535 /* Standard TCP/UDP port max */
Maximum TCP/UDP port number.
#define SOCKET_MAX_LISTEN_BACKLOG 1024
Maximum backlog for listen() system call.
#define SOCKET_MAX_FDS_PER_MSG 253 /* SCM_MAX_FD on most POSIX systems */
Maximum file descriptors per SCM_RIGHTS message.
#define SOCKETBUF_MIN_CAPACITY 512
Minimum capacity for circular buffers.
#define SOCKETBUF_INITIAL_CAPACITY 1024
Initial capacity when buffer reserve grows from zero.
#define SOCKETBUF_ALLOC_OVERHEAD 64
Allocation overhead for arena bookkeeping during buffer resize.
#define SOCKET_DNS_THREAD_COUNT 4
Number of DNS worker threads.
#define SOCKET_DNS_MAX_PENDING 1000
Maximum pending DNS requests.
#define SOCKET_DNS_MAX_LABEL_LENGTH 63
Maximum DNS label length.
#define SOCKET_DNS_WORKER_STACK_SIZE (128 * 1024)
DNS worker thread stack size.
#define SOCKET_DNS_REQUEST_HASH_SIZE 1021
DNS request hash table size.
#define SOCKET_DNS_PIPE_BUFFER_SIZE 256
Completion pipe read buffer size.
#define SOCKET_DNS_COMPLETION_SIGNAL_BYTE 1
Completion signal byte value for DNS pipe signaling.
#define SOCKET_DNS_PORT_STR_SIZE 16
Port number string buffer size.
#define SOCKET_DNS_THREAD_NAME_SIZE 16
Thread name buffer size.
#define SOCKET_DNS_DEFAULT_CACHE_TTL_SECONDS 300
Default DNS cache TTL in seconds.
#define SOCKET_DNS_DEFAULT_CACHE_MAX_ENTRIES 1000
Default maximum DNS cache entries.
#define SOCKET_DNS_CACHE_HASH_SIZE 1021
DNS cache hash table size.
#define SOCKET_HAS_SENDMSG 1
sendmsg() support flag.
#define SOCKET_HAS_RECVMSG 1
recvmsg() support flag.
#define SOCKET_DEFAULT_DNS_TIMEOUT_MS 5000 /* 5 seconds */
Default DNS resolution timeout.
#define SOCKET_STREAM_TYPE SOCK_STREAM
TCP stream socket type.
#define SOCKET_DGRAM_TYPE SOCK_DGRAM
UDP datagram socket type.
#define SOCKET_AF_UNSPEC AF_UNSPEC
Unspecified address family.
#define SOCKET_AF_INET AF_INET
IPv4 address family.
#define SOCKET_AF_INET6 AF_INET6
IPv6 address family.
#define SOCKET_AF_UNIX AF_UNIX
Unix domain socket address family.
#define SOCKET_IPPROTO_TCP IPPROTO_TCP
TCP protocol number.
#define SOCKET_IPPROTO_UDP IPPROTO_UDP
UDP protocol number.
#define SOCKET_IPPROTO_IP IPPROTO_IP
IP protocol number.
#define SOCKET_IPPROTO_IPV6 IPPROTO_IPV6
IPv6 protocol number.
#define SOCKET_SOL_SOCKET SOL_SOCKET
Socket options level.
#define SOCKET_SO_REUSEADDR SO_REUSEADDR
Allow reuse of local addresses.
#define SOCKET_SO_REUSEPORT 0
Allow reuse of local ports (if available).
#define SOCKET_SOCK_CLOEXEC 0
SOCK_CLOEXEC flag for socket creation (if available).
#define SOCKET_HAS_ACCEPT4 1
Linux-specific accept4() support flag.
#define SOCKET_FD_CLOEXEC FD_CLOEXEC
File descriptor close-on-exec flag.
#define SOCKET_SO_BROADCAST SO_BROADCAST
Enable broadcast transmission.
#define SOCKET_SO_KEEPALIVE SO_KEEPALIVE
Enable keep-alive packets.
#define SOCKET_SO_RCVTIMEO SO_RCVTIMEO
Receive timeout.
#define SOCKET_SO_SNDTIMEO SO_SNDTIMEO
Send timeout.
#define SOCKET_SO_RCVBUF SO_RCVBUF
Receive buffer size.
#define SOCKET_SO_SNDBUF SO_SNDBUF
Send buffer size.
#define SOCKET_SO_PEERCRED SO_PEERCRED
Peer credentials.
#define SOCKET_TCP_NODELAY TCP_NODELAY
Disable Nagle's algorithm.
#define SOCKET_TCP_KEEPIDLE TCP_KEEPIDLE
Keep-alive idle time.
#define SOCKET_TCP_KEEPINTVL TCP_KEEPINTVL
Keep-alive interval.
#define SOCKET_TCP_KEEPCNT TCP_KEEPCNT
Keep-alive probe count.
#define SOCKET_HAS_TCP_CONGESTION 0
TCP congestion control algorithm (if available).
#define SOCKET_HAS_TCP_FASTOPEN 0
TCP Fast Open support (if available).
#define SOCKET_HAS_TCP_USER_TIMEOUT 0
TCP user timeout support (if available).
#define SOCKET_IPV6_V6ONLY IPV6_V6ONLY
IPv6 only flag.
#define SOCKET_IPV6_UNICAST_HOPS IPV6_UNICAST_HOPS
IPv6 multicast add membership.
#define SOCKET_IP_TTL IP_TTL
IP time to live.
#define SOCKET_IP_ADD_MEMBERSHIP IP_ADD_MEMBERSHIP
IP multicast add membership.
#define SOCKET_IP_DROP_MEMBERSHIP IP_DROP_MEMBERSHIP
IP multicast drop membership.
#define SOCKET_AI_PASSIVE AI_PASSIVE
Passive socket flag for getaddrinfo().
#define SOCKET_AI_NUMERICHOST AI_NUMERICHOST
Numeric host address flag for getaddrinfo().
#define SOCKET_AI_NUMERICSERV AI_NUMERICSERV
Numeric service port flag for getaddrinfo().
#define SOCKET_NI_NUMERICHOST NI_NUMERICHOST
Numeric host address flag for getnameinfo().
#define SOCKET_NI_NUMERICSERV NI_NUMERICSERV
Numeric service port flag for getnameinfo().
#define SOCKET_NI_MAXHOST NI_MAXHOST
Maximum host name length for getnameinfo().
#define SOCKET_NI_MAXSERV NI_MAXSERV
Maximum service name length for getnameinfo().
#define SOCKET_SHUT_RD SHUT_RD
Shutdown read direction.
#define SOCKET_SHUT_WR SHUT_WR
Shutdown write direction.
#define SOCKET_SHUT_RDWR SHUT_RDWR
Shutdown both read and write directions.
#define MSG_NOSIGNAL 0
MSG_NOSIGNAL fallback for platforms without it.
#define SOCKET_MSG_NOSIGNAL MSG_NOSIGNAL
Suppress SIGPIPE on send operations.
#define SOCKET_HAS_SO_NOSIGPIPE 0
SO_NOSIGPIPE support flag.
#define SOCKET_DEFAULT_KEEPALIVE_IDLE 60
Default TCP keep-alive idle time (seconds).
#define SOCKET_DEFAULT_KEEPALIVE_INTERVAL 10
Default TCP keep-alive interval (seconds).
#define SOCKET_DEFAULT_KEEPALIVE_COUNT 3
Default TCP keep-alive probe count.
#define SOCKET_KEEPALIVE_MAX_IDLE (86400 * 365) /* 1 year in seconds */
Maximum TCP keep-alive idle time (seconds).
#define SOCKET_KEEPALIVE_MAX_INTERVAL 3600 /* 1 hour */
Maximum TCP keep-alive interval (seconds).
#define SOCKET_KEEPALIVE_MAX_COUNT 32
Maximum TCP keep-alive probe count.
#define SOCKET_MAX_DEFER_ACCEPT_SEC 3600 /* 1 hour */
Maximum TCP defer accept timeout (seconds).
#define SOCKET_MAX_CONGESTION_ALGO_LEN 63
Maximum congestion control algorithm name length.
#define SOCKET_DEFAULT_DATAGRAM_TTL 64
Default datagram TTL value.
#define SOCKET_MULTICAST_DEFAULT_INTERFACE 0
Default multicast interface index.
#define T Socket_T
Opaque context for managing asynchronous proxy tunneling operations.
#define SocketBase_T SocketBase_T
Opaque base structure for shared socket functionality.
#define SOCKETLIVECOUNT_STATIC_INIT
Static initializer for SocketLiveCount structure.
#define T SocketProxy_Conn_T
Opaque context for managing asynchronous proxy tunneling operations.
Typedefs
typedef struct SocketBuf_T * SocketBuf_T
Opaque handle to a circular buffer instance.
Enumerations
enum SocketProxyType {
SOCKET_PROXY_NONE = 0 ,
SOCKET_PROXY_HTTP ,
SOCKET_PROXY_HTTPS ,
SOCKET_PROXY_SOCKS4 ,
SOCKET_PROXY_SOCKS4A ,
SOCKET_PROXY_SOCKS5 ,
SOCKET_PROXY_SOCKS5H
}
Enumeration of supported proxy protocol types.
enum SocketProxy_Result {
PROXY_OK = 0 ,
PROXY_IN_PROGRESS ,
PROXY_ERROR ,
PROXY_ERROR_CONNECT ,
PROXY_ERROR_AUTH_REQUIRED ,
PROXY_ERROR_AUTH_FAILED ,
PROXY_ERROR_FORBIDDEN ,
PROXY_ERROR_HOST_UNREACHABLE ,
PROXY_ERROR_NETWORK_UNREACHABLE ,
PROXY_ERROR_CONNECTION_REFUSED ,
PROXY_ERROR_TTL_EXPIRED ,
PROXY_ERROR_PROTOCOL ,
PROXY_ERROR_UNSUPPORTED ,
PROXY_ERROR_TIMEOUT ,
PROXY_ERROR_CANCELLED
}
Result codes for proxy operations.
enum SocketProxy_State {
PROXY_STATE_IDLE = 0 ,
PROXY_STATE_CONNECTING_PROXY ,
PROXY_STATE_TLS_TO_PROXY ,
PROXY_STATE_HANDSHAKE_SEND ,
PROXY_STATE_HANDSHAKE_RECV ,
PROXY_STATE_AUTH_SEND ,
PROXY_STATE_AUTH_RECV ,
PROXY_STATE_CONNECTED ,
PROXY_STATE_FAILED ,
PROXY_STATE_CANCELLED
}
States in the proxy connection state machine.
Functions
int Socket_error_is_retryable (int err)
Check if an errno indicates a retryable error.
Socket_T Socket_new (int domain, int type, int protocol)
Create a new socket with specified domain, type, and protocol.
void SocketPair_new (int type, Socket_T *socket1, Socket_T *socket2)
Create a pair of connected Unix domain sockets for inter-process communication.
void Socket_free (Socket_T *socket)
Dispose of a socket instance and close the underlying file descriptor.
Socket_T Socket_new_from_fd (int fd)
Create Socket_T from existing file descriptor.
int Socket_debug_live_count (void)
Get number of live socket instances (test-only).
void Socket_getstats (const Socket_T socket, SocketStats_T *stats)
Retrieve current statistics for a socket.
void Socket_resetstats (Socket_T socket)
Reset statistics counters for a socket.
int Socket_probe (Socket_T socket, int timeout_ms)
Probe if a connection is still alive.
int Socket_get_error (Socket_T socket)
Get pending socket error (SO_ERROR).
int Socket_is_readable (Socket_T socket)
Check if socket has data available to read without blocking.
int Socket_is_writable (Socket_T socket)
Check if socket can accept writes without blocking.
int Socket_get_tcp_info (Socket_T socket, SocketTCPInfo *info)
Retrieve TCP connection statistics (Linux-specific).
int32_t Socket_get_rtt (Socket_T socket)
Get current RTT (round-trip time) estimate.
int32_t Socket_get_cwnd (Socket_T socket)
Get current congestion window size.
void Socket_bind (Socket_T socket, const char *host, int port)
Bind a socket to a local IP address and port.
void Socket_listen (Socket_T socket, int backlog)
Listen for incoming connections.
Socket_T Socket_accept (Socket_T socket)
Accept incoming connection.
void Socket_connect (Socket_T socket, const char *host, int port)
Establish a connection to a remote host and port.
ssize_t Socket_send (Socket_T socket, const void *buf, size_t len)
Send data.
ssize_t Socket_recv (Socket_T socket, void *buf, size_t len)
Receive data.
ssize_t Socket_sendall (Socket_T socket, const void *buf, size_t len)
Send all data (handles partial sends).
ssize_t Socket_recvall (Socket_T socket, void *buf, size_t len)
Receive all requested data (handles partial receives).
ssize_t Socket_sendv (Socket_T socket, const struct iovec *iov, int iovcnt)
Scatter/gather send (writev wrapper).
ssize_t Socket_recvv (Socket_T socket, struct iovec *iov, int iovcnt)
Scatter/gather receive (readv wrapper).
ssize_t Socket_sendvall (Socket_T socket, const struct iovec *iov, int iovcnt)
Scatter/gather send all (handles partial sends).
ssize_t Socket_recvvall (Socket_T socket, struct iovec *iov, int iovcnt)
Scatter/gather receive all (handles partial receives).
ssize_t Socket_sendfile (Socket_T socket, int file_fd, off_t *offset, size_t count)
Zero-copy file-to-socket transfer.
ssize_t Socket_sendfileall (Socket_T socket, int file_fd, off_t *offset, size_t count)
Zero-copy file-to-socket transfer (handles partial transfers).
ssize_t Socket_sendall_timeout (Socket_T socket, const void *buf, size_t len, int timeout_ms)
Send all data with timeout.
ssize_t Socket_recvall_timeout (Socket_T socket, void *buf, size_t len, int timeout_ms)
Receive all requested data with timeout.
ssize_t Socket_sendv_timeout (Socket_T socket, const struct iovec *iov, int iovcnt, int timeout_ms)
Scatter/gather send with timeout.
ssize_t Socket_recvv_timeout (Socket_T socket, struct iovec *iov, int iovcnt, int timeout_ms)
Scatter/gather receive with timeout.
ssize_t Socket_splice (Socket_T socket_in, Socket_T socket_out, size_t len)
Zero-copy socket-to-socket transfer (Linux splice).
int Socket_cork (Socket_T socket, int enable)
Control TCP_CORK option (Nagle corking).
ssize_t Socket_peek (Socket_T socket, void *buf, size_t len)
Peek at incoming data without consuming it.
Socket_T Socket_dup (Socket_T socket)
Duplicate a socket (creates new Socket_T sharing same fd).
Socket_T Socket_dup2 (Socket_T socket, int target_fd)
Duplicate socket fd to a specific file descriptor number.
ssize_t Socket_sendmsg (Socket_T socket, const struct msghdr *msg, int flags)
Send message with ancillary data (sendmsg wrapper).
ssize_t Socket_recvmsg (Socket_T socket, struct msghdr *msg, int flags)
Receive message with ancillary data (recvmsg wrapper).
int Socket_isconnected (Socket_T socket)
Check if socket is connected.
int Socket_isbound (Socket_T socket)
Check if socket is bound to an address.
int Socket_islistening (Socket_T socket)
Check if socket is listening for connections.
int Socket_fd (const Socket_T socket)
Get underlying file descriptor.
const char * Socket_getpeeraddr (const Socket_T socket)
Get peer IP address.
int Socket_getpeerport (const Socket_T socket)
Get peer port number.
const char * Socket_getlocaladdr (const Socket_T socket)
Get local IP address.
int Socket_getlocalport (const Socket_T socket)
Get local port number.
void Socket_setnonblocking (Socket_T socket)
Enable non-blocking mode.
void Socket_setreuseaddr (Socket_T socket)
Enable address reuse.
void Socket_setreuseport (Socket_T socket)
Enable port reuse across sockets.
void Socket_settimeout (Socket_T socket, int timeout_sec)
Set socket timeout.
void Socket_setkeepalive (Socket_T socket, int idle, int interval, int count)
Enable TCP keepalive.
void Socket_setnodelay (Socket_T socket, int nodelay)
Disable Nagle's algorithm.
int Socket_gettimeout (Socket_T socket)
Get socket timeout.
void Socket_getkeepalive (Socket_T socket, int *idle, int *interval, int *count)
Get TCP keepalive configuration.
int Socket_getnodelay (Socket_T socket)
Get TCP_NODELAY setting.
int Socket_getrcvbuf (Socket_T socket)
Get receive buffer size.
int Socket_getsndbuf (Socket_T socket)
Get send buffer size.
void Socket_setrcvbuf (Socket_T socket, int size)
Set receive buffer size.
void Socket_setsndbuf (Socket_T socket, int size)
Set send buffer size.
void Socket_setcongestion (Socket_T socket, const char *algorithm)
Set TCP congestion control algorithm.
int Socket_getcongestion (Socket_T socket, char *algorithm, size_t len)
Get TCP congestion control algorithm.
void Socket_setfastopen (Socket_T socket, int enable)
Enable TCP Fast Open.
int Socket_getfastopen (Socket_T socket)
Get TCP Fast Open setting.
void Socket_setusertimeout (Socket_T socket, unsigned int timeout_ms)
Set TCP user timeout.
unsigned int Socket_getusertimeout (Socket_T socket)
Get TCP user timeout.
void Socket_shutdown (Socket_T socket, int how)
Disable further sends and/or receives.
void Socket_setcloexec (Socket_T socket, int enable)
Control close-on-exec flag.
void Socket_setdeferaccept (Socket_T socket, int timeout_sec)
Enable TCP_DEFER_ACCEPT.
int Socket_getdeferaccept (Socket_T socket)
Get TCP_DEFER_ACCEPT timeout.
void Socket_timeouts_get (const Socket_T socket, SocketTimeouts_T *timeouts)
Retrieve per-socket timeout configuration.
void Socket_timeouts_set (Socket_T socket, const SocketTimeouts_T *timeouts)
Set per-socket timeout configuration.
void Socket_timeouts_getdefaults (SocketTimeouts_T *timeouts)
Get global default timeouts.
void Socket_timeouts_setdefaults (const SocketTimeouts_T *timeouts)
Set global default timeouts.
void Socket_timeouts_set_extended (Socket_T socket, const SocketTimeouts_Extended_T *extended)
Set per-socket extended timeout configuration.
void Socket_timeouts_get_extended (const Socket_T socket, SocketTimeouts_Extended_T *extended)
Retrieve per-socket extended timeout configuration.
void Socket_setbandwidth (Socket_T socket, size_t bytes_per_sec)
Set bandwidth limit for socket.
size_t Socket_getbandwidth (Socket_T socket)
Get bandwidth limit for socket.
ssize_t Socket_send_limited (Socket_T socket, const void *buf, size_t len)
Send data with bandwidth limiting.
ssize_t Socket_recv_limited (Socket_T socket, void *buf, size_t len)
Receive data with bandwidth limiting.
int64_t Socket_bandwidth_wait_ms (Socket_T socket, size_t bytes)
Get wait time until bandwidth available.
void Socket_bind_unix (Socket_T socket, const char *path)
Bind to Unix domain socket path.
void Socket_connect_unix (Socket_T socket, const char *path)
Connect to Unix domain socket path.
int Socket_getpeerpid (const Socket_T socket)
Get peer process ID (Linux only).
int Socket_getpeeruid (const Socket_T socket)
Get peer user ID (Linux only).
int Socket_getpeergid (const Socket_T socket)
Get peer group ID (Linux only).
int Socket_sendfd (Socket_T socket, int fd_to_pass)
Send a file descriptor over Unix domain socket.
int Socket_recvfd (Socket_T socket, int *fd_received)
Receive a file descriptor over Unix domain socket.
int Socket_sendfds (Socket_T socket, const int *fds, size_t count)
Send multiple file descriptors.
int Socket_recvfds (Socket_T socket, int *fds, size_t max_count, size_t *received_count)
Receive multiple file descriptors.
void SocketUnix_bind (SocketBase_T base, const char *path, Except_T exc_type)
Bind Unix domain socket to a filesystem path.
void SocketUnix_connect (SocketBase_T base, const char *path, Except_T exc_type)
Connect Unix domain socket to a filesystem path.
int SocketUnix_validate_unix_path (const char *path, size_t path_len)
Validate a Unix domain socket path.
Request_T Socket_bind_async (SocketDNS_T dns, Socket_T socket, const char *host, int port)
Start async DNS resolution for bind.
void Socket_bind_async_cancel (SocketDNS_T dns, Request_T req)
Cancel pending async bind resolution.
Request_T Socket_connect_async (SocketDNS_T dns, Socket_T socket, const char *host, int port)
Start async DNS resolution for connect.
void Socket_connect_async_cancel (SocketDNS_T dns, Request_T req)
Cancel pending async connect resolution.
void Socket_bind_with_addrinfo (Socket_T socket, struct addrinfo *res)
Bind socket using resolved address.
void Socket_connect_with_addrinfo (Socket_T socket, struct addrinfo *res)
Connect socket using resolved address.
int Socket_ignore_sigpipe (void)
Globally ignore SIGPIPE signal.
Socket_T Socket_listen_tcp (const char *host, int port, int backlog)
Create a listening TCP server socket in one call.
Socket_T Socket_connect_tcp (const char *host, int port, int timeout_ms)
Create a connected TCP client socket in one call.
Socket_T Socket_accept_timeout (Socket_T socket, int timeout_ms)
Accept incoming connection with explicit timeout.
int Socket_connect_nonblocking (Socket_T socket, const char *ip_address, int port)
Initiate non-blocking connect (no DNS, IP address only).
Socket_T Socket_listen_unix (const char *path, int backlog)
Create a listening Unix domain socket in one call.
void Socket_connect_unix_timeout (Socket_T socket, const char *path, int timeout_ms)
Connect to Unix domain socket with timeout.
SocketBuf_T SocketBuf_new (Arena_T arena, size_t capacity)
Create a new circular buffer with specified initial capacity.
void SocketBuf_release (SocketBuf_T *buf)
Release the buffer handle and invalidate the pointer.
size_t SocketBuf_write (SocketBuf_T buf, const void *data, size_t len)
Write data into the buffer.
size_t SocketBuf_read (SocketBuf_T buf, void *data, size_t len)
Read and remove data from the buffer.
size_t SocketBuf_peek (SocketBuf_T buf, void *data, size_t len)
Peek at data without removing it from the buffer.
void SocketBuf_consume (SocketBuf_T buf, size_t len)
Discard data from the front of the buffer without reading it.
size_t SocketBuf_available (const SocketBuf_T buf)
Query the number of bytes available for reading.
size_t SocketBuf_space (const SocketBuf_T buf)
Query the number of bytes available for writing.
int SocketBuf_empty (const SocketBuf_T buf)
Check if the buffer contains no data.
int SocketBuf_full (const SocketBuf_T buf)
Check if the buffer has no space for writing.
void SocketBuf_clear (SocketBuf_T buf)
Reset buffer to empty state without zeroing memory.
void SocketBuf_secureclear (SocketBuf_T buf)
Securely erase all data by zeroing memory contents.
void SocketBuf_reserve (SocketBuf_T buf, size_t min_space)
Dynamically resize buffer to ensure at least min_space available.
bool SocketBuf_check_invariants (const SocketBuf_T buf)
Validate internal buffer consistency without assertions.
const void * SocketBuf_readptr (SocketBuf_T buf, size_t *len)
Obtain a direct pointer to readable data for zero-copy access.
void * SocketBuf_writeptr (SocketBuf_T buf, size_t *len)
Obtain a direct pointer for zero-copy writing into the buffer.
void SocketBuf_written (SocketBuf_T buf, size_t len)
Commit bytes written via direct write pointer.
void SocketBuf_compact (SocketBuf_T buf)
Move data to front of buffer, maximizing contiguous write space.
int SocketBuf_ensure (SocketBuf_T buf, size_t min_space)
Ensure minimum write space is available, resizing if necessary.
ssize_t SocketBuf_find (SocketBuf_T buf, const void *needle, size_t needle_len)
Search for a byte sequence in the buffer.
ssize_t SocketBuf_readline (SocketBuf_T buf, char *line, size_t max_len)
Read a line (up to and including newline) from the buffer.
ssize_t SocketBuf_readv (SocketBuf_T buf, const struct iovec *iov, int iovcnt)
Scatter read from buffer into multiple iovecs.
ssize_t SocketBuf_writev (SocketBuf_T buf, const struct iovec *iov, int iovcnt)
Gather write from multiple iovecs into buffer.
int SocketBase_fd (SocketBase_T base)
Retrieve the socket file descriptor from the base structure.
Arena_T SocketBase_arena (SocketBase_T base)
Get the memory arena associated with the socket base.
int SocketBase_domain (SocketBase_T base)
Get the address domain (family) of the socket.
static char * SocketBase_remoteaddr (SocketBase_T base)
Get cached remote address string representation.
static int SocketBase_remoteport (SocketBase_T base)
Get remote peer port number.
void SocketBase_set_timeouts (SocketBase_T base, const SocketTimeouts_T *timeouts)
Set timeouts configuration in the socket base structure.
int SocketCommon_create_fd (int domain, int type, int protocol, Except_T exc_type)
Create a new socket file descriptor with error handling and CLOEXEC setup.
void SocketCommon_init_base (SocketBase_T base, int fd, int domain, int type, int protocol, Except_T exc_type)
Initialize pre-allocated SocketBase_T with FD and parameters.
int socketcommon_sanitize_timeout (int timeout_ms)
Sanitize raw timeout value, applying library policy for valid range.
void SocketCommon_setup_hints (struct addrinfo *hints, int socktype, int flags)
Initialize addrinfo hints structure for address resolution operations.
int SocketCommon_resolve_address (const char *host, int port, const struct addrinfo *hints, struct addrinfo **res, Except_T exception_type, int socket_family, int use_exceptions)
Resolve hostname/port to addrinfo structure using getaddrinfo wrapper.
void SocketCommon_validate_port (int port, Except_T exception_type)
Validate that a port number is within the valid range for socket operations.
void SocketCommon_validate_hostname (const char *host, Except_T exception_type)
Validate that a hostname string is not excessively long for system buffers.
const char * SocketCommon_normalize_wildcard_host (const char *host)
Normalize wildcard/any-address host strings to NULL for internal use.
int SocketCommon_cache_endpoint (Arena_T arena, const struct sockaddr *addr, socklen_t addrlen, char **addr_out, int *port_out)
Extract and cache human-readable numeric address and port from sockaddr structure.
int SocketCommon_setcloexec (int fd, int enable)
Set or clear the close-on-exec (CLOEXEC) flag on a file descriptor.
int SocketCommon_has_cloexec (int fd)
Check if close-on-exec flag is set.
int SocketCommon_getoption_int (int fd, int level, int optname, int *value, Except_T exception_type)
Get integer socket option.
int SocketCommon_getoption_timeval (int fd, int level, int optname, struct timeval *tv, Except_T exception_type)
Get timeval socket option.
int SocketCommon_reverse_lookup (const struct sockaddr *addr, socklen_t addrlen, char *host, socklen_t hostlen, char *serv, socklen_t servlen, int flags, Except_T exception_type)
Perform reverse DNS lookup (getnameinfo wrapper)
int SocketCommon_parse_ip (const char *ip_str, int *family)
Validate and parse IP address string.
int SocketCommon_cidr_match (const char *ip_str, const char *cidr_str)
Check if IP address matches CIDR range.
SocketBase_T SocketCommon_new_base (int domain, int type, int protocol)
Create a new socket base structure.
void SocketCommon_free_base (SocketBase_T *base_ptr)
Free a socket base structure.
void SocketCommon_set_option_int (SocketBase_T base, int level, int optname, int value, Except_T exc_type)
Set integer socket option.
void SocketCommon_set_ttl (SocketBase_T base, int family, int ttl, Except_T exc_type)
Set TTL or hop limit based on family.
void SocketCommon_join_multicast (SocketBase_T base, const char *group, const char *interface, Except_T exc_type)
Join multicast group.
void SocketCommon_leave_multicast (SocketBase_T base, const char *group, const char *interface, Except_T exc_type)
Leave multicast group.
void SocketCommon_set_nonblock (SocketBase_T base, bool enable, Except_T exc_type)
Set non-blocking mode.
size_t SocketCommon_calculate_total_iov_len (const struct iovec *iov, int iovcnt)
Calculate total length of iovec array with overflow protection.
void SocketCommon_advance_iov (struct iovec *iov, int iovcnt, size_t bytes)
Advance iovec array past sent/received bytes (modifies in place)
struct iovec * SocketCommon_find_active_iov (struct iovec *iov, int iovcnt, int *active_iovcnt)
Find first non-empty iovec in array.
void SocketCommon_sync_iov_progress (struct iovec *original, const struct iovec *copy, int iovcnt)
Sync original iovec with working copy progress.
struct iovec * SocketCommon_alloc_iov_copy (const struct iovec *iov, int iovcnt, Except_T exc_type)
Allocate and copy iovec array.
void SocketCommon_set_cloexec_fd (int fd, bool enable, Except_T exc_type)
Set close-on-exec flag on fd (unifies dups)
int SocketCommon_try_bind_address (SocketBase_T base, const struct sockaddr *addr, socklen_t addrlen, Except_T exc_type)
Try bind fd to address (extracted from Socket.c)
int SocketCommon_try_bind_resolved_addresses (SocketBase_T base, struct addrinfo *res, int family, Except_T exc_type)
Try bind to resolved addrinfo list.
int SocketCommon_handle_bind_error (int err, const char *addr_str, Except_T exc_type)
Log and raise bind error.
void SocketCommon_format_bind_error (const char *host, int port)
Format descriptive bind error message.
void SocketCommon_update_local_endpoint (SocketBase_T base)
Update local endpoint information from getsockname.
int SocketCommon_get_socket_family (SocketBase_T base)
Get socket's address family.
void SocketCommon_validate_host_not_null (const char *host, Except_T exception_type)
Validate host is not NULL.
struct addrinfo * SocketCommon_copy_addrinfo (const struct addrinfo *src)
Deep copy of addrinfo linked list.
void SocketCommon_free_addrinfo (struct addrinfo *ai)
Free addrinfo chain created by copy_addrinfo.
void SocketCommon_timeouts_getdefaults (SocketTimeouts_T *timeouts)
Get global default timeouts.
void SocketCommon_timeouts_setdefaults (const SocketTimeouts_T *timeouts)
Set global default timeouts.
static int SocketCommon_check_bound_ipv4 (const struct sockaddr_storage *addr)
Check if IPv4 socket is bound.
static int SocketCommon_check_bound_ipv6 (const struct sockaddr_storage *addr)
Check if IPv6 socket is bound.
static int SocketCommon_check_bound_unix (const struct sockaddr_storage *addr)
Check if Unix socket is bound.
static int SocketCommon_check_bound_by_family (const struct sockaddr_storage *addr)
Check if socket is bound based on family.
static void SocketLiveCount_increment (struct SocketLiveCount *tracker)
Increment live count (thread-safe)
static void SocketLiveCount_decrement (struct SocketLiveCount *tracker)
Decrement live count (thread-safe)
static int SocketLiveCount_get (struct SocketLiveCount *tracker)
Get current live count (thread-safe)
SocketDNS_T SocketCommon_get_dns_resolver (void)
Get global DNS resolver instance.
void SocketCommon_set_dns_timeout (int timeout_ms)
Set global DNS resolution timeout.
int SocketCommon_get_dns_timeout (void)
Get current global DNS timeout.
void SocketCommon_shutdown_globals (void)
Shutdown global resources (e.g., DNS resolver) to prevent leaks in testsCall at program exit after all operations complete.
ssize_t socket_send_internal (Socket_T socket, const void *buf, size_t len, int flags)
Internal send operation (TLS-aware)
ssize_t socket_recv_internal (Socket_T socket, void *buf, size_t len, int flags)
Internal receive operation (TLS-aware)
ssize_t socket_sendv_internal (Socket_T socket, const struct iovec *iov, int iovcnt, int flags)
Internal scatter/gather send (TLS-aware)
ssize_t socket_recvv_internal (Socket_T socket, struct iovec *iov, int iovcnt, int flags)
Internal scatter/gather receive (TLS-aware)
int socket_is_tls_enabled (const Socket_T socket)
Check if socket has TLS enabled.
int socket_tls_want_read (const Socket_T socket)
Check if TLS wants to read more data for handshake or protocol.
int socket_tls_want_write (const Socket_T socket)
Check if TLS wants to write more data for handshake or protocol.
int socket_handle_ssl_error (Socket_T socket, SSL *ssl, int ssl_result)
Helper to handle SSL error codes.
SSL * socket_get_ssl (Socket_T socket)
Get SSL object from socket.
SSL * socket_validate_tls_ready (Socket_T socket)
Validate TLS is ready for I/O.
static int socketio_is_wouldblock (void)
Check if errno indicates operation would block.
static int socketio_is_connection_closed_send (void)
Check if send error indicates closed connection.
static int socketio_is_connection_closed_recv (void)
Check if recv error indicates closed connection.
static int64_t socketproxy_get_time_ms (void)
Get current monotonic time in milliseconds.
static int64_t socketproxy_elapsed_ms (int64_t start_ms)
Calculate elapsed time since start in milliseconds.
int socketproxy_do_send (struct SocketProxy_Conn_T *conn)
Send pending protocol data from conn->send_buf.
int socketproxy_do_recv (struct SocketProxy_Conn_T *conn)
Receive protocol data into conn->recv_buf.
int socketproxy_parse_scheme (const char *url, SocketProxy_Config *config, const char **end)
Helper functions for parsing proxy URLs.
int socketproxy_parse_userinfo (const char *start, SocketProxy_Config *config, Arena_T arena, const char **end)
Parse optional [user[:pass]@] from URL.
int socketproxy_parse_hostport (const char *start, SocketProxy_Config *config, Arena_T arena, size_t *consumed_out)
Parse [host]:port from URL, handling IPv6 literals.
void SocketProxy_config_defaults (SocketProxy_Config *config)
Initialize proxy configuration with safe default values.
int SocketProxy_parse_url (const char *url, SocketProxy_Config *config, Arena_T arena)
Parse proxy URL string into configuration structure.
Socket_T SocketProxy_connect (const SocketProxy_Config *proxy, const char *target_host, int target_port)
Establish synchronous connection to target via proxy tunnel.
SocketProxy_Result SocketProxy_tunnel (Socket_T socket, const SocketProxy_Config *proxy, const char *target_host, int target_port, Arena_T arena)
Perform proxy handshake on pre-connected socket to establish tunnel.
SocketProxy_Conn_T SocketProxy_Conn_start (SocketDNS_T dns, SocketPoll_T poll, const SocketProxy_Config *proxy, const char *target_host, int target_port)
Initialize and start fully asynchronous proxy tunneling operation.
SocketProxy_Conn_T SocketProxy_Conn_new (const SocketProxy_Config *proxy, const char *target_host, int target_port)
Create proxy connection context with blocking proxy connect, async handshake.
int SocketProxy_Conn_poll (SocketProxy_Conn_T conn)
Query if proxy operation has completed.
void SocketProxy_Conn_process (SocketProxy_Conn_T conn)
Advance asynchronous proxy connection state machine.
Socket_T SocketProxy_Conn_socket (SocketProxy_Conn_T conn)
Extract successfully tunneled socket from completed context.
void SocketProxy_Conn_cancel (SocketProxy_Conn_T conn)
Cancel ongoing proxy connection and cleanup resources.
void SocketProxy_Conn_free (SocketProxy_Conn_T *conn)
Release proxy connection context and associated resources.
SocketProxy_State SocketProxy_Conn_state (SocketProxy_Conn_T conn)
Retrieve current state of proxy connection.
SocketProxy_Result SocketProxy_Conn_result (SocketProxy_Conn_T conn)
Get final result code after operation completion.
const char * SocketProxy_Conn_error (SocketProxy_Conn_T conn)
Retrieve human-readable error description for failed operations.
int SocketProxy_Conn_fd (SocketProxy_Conn_T conn)
Get underlying file descriptor for poll integration.
unsigned SocketProxy_Conn_events (SocketProxy_Conn_T conn)
Get poll event mask for current connection phase.
int SocketProxy_Conn_next_timeout_ms (SocketProxy_Conn_T conn)
Calculate milliseconds until next internal timeout.
const char * SocketProxy_result_string (SocketProxy_Result result)
Convert SocketProxy_Result code to descriptive string.
const char * SocketProxy_state_string (SocketProxy_State state)
Convert SocketProxy_State to descriptive string.
const char * SocketProxy_type_string (SocketProxyType type)
Convert proxy type enum to protocol name string.
Variables
const Except_T Socket_Failed
General socket operation failure exception.
const Except_T Socket_Closed
Connection closed by peer exception.
const Except_T SocketUnix_Failed
Unix domain socket operation failure.
const Except_T SocketBuf_Failed
Exception indicating failure in buffer operations such as allocation or resize errors.
const Except_T Socket_Failed
Module Exception Forward Declarations.
const Except_T SocketDgram_Failed
Datagram/UDP-specific operation failure exception.
const Except_T SocketCommon_Failed
Shared utility function failure exception.
const Except_T Socket_Failed
General TCP socket operation failure exception.
const Except_T SocketDgram_Failed
General UDP/datagram socket operation failure exception.
const Except_T SocketCommon_Failed
General failure in shared socket common utilities.
const Except_T SocketProxy_Failed
Exception raised on general proxy operation failures.
SocketBase_T SocketDgram_T::base
Detailed Description
Fundamental socket primitives for TCP, UDP, Unix domain, and DNS operations.
This group forms the foundation for all networking in the library, providing low-level but safe abstractions over POSIX sockets. It handles cross-platform differences, error mapping to exceptions, and common patterns like partial I/O.
Architecture Overview
   Application Modules
 HTTP, TLS, Pool, Poll, etc.
               Uses
     Core I/O Modules
 Socket_T, DNS, Proxy, Buf
               Uses
    Foundation Modules
 Arena, Except, Config, Util
Module Breakdown
| Module | Purpose | Key Features | Dependencies | |-----—|------—|-----------—|-----------—| | Socket_T | TCP/Unix sockets | Bind/connect/I/O/options/fd passing | Foundation | | SocketDgram_T | UDP/Datagram | Sendto/recvfrom/multicast/broadcast | Foundation | | SocketBuf_T | Circular buffers | Zero-copy read/write/secure clear | Arena | | SocketDNS_T | Async DNS | Worker threads/non-blocking resolve | Socket, Timer | | SocketProxy_T | Proxy tunneling | HTTP CONNECT/SOCKS4/5 | Socket, DNS |
Relationships
Depends on: Core Foundation Modules (memory, exceptions, utils)
Used by: Event System Modules (poll integration), Connection Management Modules (pooling), HTTP Modules (HTTP over sockets), Security Modules (protections), Async I/O Modules (happy eyeballs)
Thread Safety: Operations marked
Thread Safety\n; instances not shared
without locks
Performance: O(1) most ops; DNS may block unless async
See also
Core Foundation Modules Base infrastructure
Event System Modules Event system built on Core I/O
Socket_T Primary TCP/Unix abstraction
SocketDgram_T UDP abstraction
docs/ASYNC_IO.md Integration guide
Data Structure Documentation
SocketStats_T
struct SocketStats_T
Per-socket I/O statistics structure.
Tracks cumulative statistics for a single socket instance including bytes transferred, packet counts, and timing information. Statistics are updated automatically by send/recv operations and can be queried or reset via Socket_getstats() and Socket_resetstats().
All timing values use monotonic clock (milliseconds since epoch or socket creation).
Usage Example
Socket_T sock = Socket_new(AF_INET, SOCK_STREAM, 0);
Socket_connect(sock, "example.com", 80);
// ... send/recv operations ...
SocketStats_T stats;
Socket_getstats(sock, &stats);
printf("Sent: %zu bytes in %zu packets\n", stats.bytes_sent,
stats.packets_sent); printf("Connect time: %lld ms\n",
(long long)stats.connect_time_ms); printf("Last recv: %lld ms ago\n",
       (long long)(Socket_get_monotonic_ms() - stats.last_recv_time_ms));
Socket_resetstats(sock);  // Reset counters for next interval
Socket_free(&sock);
Thread Safety\n Partial - stats snapshot is atomic, but rapid updates may race
See also
Socket_getstats() to retrieve current statistics
Socket_resetstats() to reset counters
SocketMetrics_get_socket_count() for global socket metrics
Definition at line 666 of file Socket.h.
Data Fields
uint64_t bytes_received
Total bytes received since creation/reset
uint64_t bytes_sent
Total bytes sent since creation/reset
int64_t connect_time_ms
Time spent in connect() (0 if not connected)
int64_t create_time_ms
Socket creation timestamp
int64_t last_recv_time_ms
Last successful recv timestamp (0 if never)
int64_t last_send_time_ms
Last successful send timestamp (0 if never)
uint64_t packets_received
Number of recv operations
uint64_t packets_sent
Number of send operations
uint64_t recv_errors
Number of failed recv operations
int32_t rtt_us
Smoothed RTT in microseconds (-1 if N/A)
int32_t rtt_var_us
RTT variance in microseconds (-1 if N/A)
uint64_t send_errors
Number of failed send operations
SocketTCPInfo
struct SocketTCPInfo
TCP connection information structure (Linux-specific).
Provides detailed TCP stack information via TCP_INFO sockopt. All timing values are in microseconds unless noted.
See also
Socket_get_tcp_info() to retrieve this information
Definition at line 936 of file Socket.h.
Data Fields
uint32_t advmss
Advertised MSS
uint32_t ato_us
ACK timeout (microseconds)
uint8_t backoff
Backoff exponent for RTO
uint64_t bytes_acked
Bytes acknowledged
uint64_t bytes_received
Bytes received
uint8_t ca_state
Congestion avoidance state
uint32_t data_segs_in
Data segments received
uint32_t data_segs_out
Data segments sent
uint64_t delivery_rate
Delivery rate (bytes/sec)
uint32_t fackets
FACKed segments
uint32_t last_ack_recv_ms
Time since last ACK received (ms)
uint32_t last_ack_sent_ms
Time since last ACK sent (ms)
uint32_t last_data_recv_ms
Time since last data received (ms)
uint32_t last_data_sent_ms
Time since last data sent (ms)
uint32_t lost
Lost segments
uint64_t max_pacing_rate
Maximum pacing rate (bytes/sec)
uint32_t min_rtt_us
Minimum observed RTT (microseconds)
uint32_t notsent_bytes
Not-yet-sent bytes in write queue
uint8_t options
TCP options enabled
uint64_t pacing_rate
Current pacing rate (bytes/sec)
uint32_t pmtu
Path MTU
uint8_t probes
Number of unanswered zero-window probes
uint32_t rcv_mss
Receive MSS
uint32_t rcv_rtt_us
Receiver RTT estimate (microseconds)
uint32_t rcv_space
Receive buffer space
uint32_t rcv_ssthresh
Receive slow-start threshold
uint8_t rcv_wscale
Receive window scale
uint32_t reordering
Reordering metric
uint32_t retrans
Retransmitted segments
uint8_t retransmits
Number of unrecovered RTOs
uint32_t rto_us
Retransmission timeout (microseconds)
uint32_t rtt_us
Smoothed RTT (microseconds)
uint32_t rttvar_us
RTT variance (microseconds)
uint32_t sacked
SACKed segments
uint32_t segs_in
Segments received
uint32_t segs_out
Segments sent
uint32_t snd_cwnd
Send congestion window
uint32_t snd_mss
Send MSS
uint32_t snd_ssthresh
Send slow-start threshold
uint8_t snd_wscale
Send window scale
uint8_t state
TCP state (TCP_ESTABLISHED, etc.)
uint32_t total_retrans
Total retransmissions
uint32_t unacked
Unacknowledged segments
SocketBase_T
struct SocketBase_T
Internal implementation of SocketBase_T opaque type.
Complete structure definition for the shared socket base, which is embedded directly within subtype implementations (e.g., struct Socket_T, struct SocketDgram_T). Centralizes management of common socket state: file descriptor, memory arena, endpoint addresses/ports, timeouts, metrics, and synchronization primitives.
Embedding Pattern
Subtypes declare:
struct Subtype_T {
  SocketBase_T base;  // Embedded, not pointer
  // Subtype-specific fields
};
Access via getters/setters in this private header to maintain encapsulation.
Thread Safety
Read Access: Conditional - safe for immutable fields (domain, type) without lock.
Write Access: Requires pthread_mutex_lock(&base.mutex) / unlock.
Concurrent Use: External synchronization needed for shared sockets across threads.
Resource Lifecycle
Creation: SocketCommon_new_base() or SocketCommon_init_base() allocates arena, initializes mutex, sets CLOEXEC.
Cleanup: SocketCommon_free_base() closes fd, destroys mutex, disposes arena.
Order: FD close before mutex destroy before arena dispose.
Note
Endpoint strings (localaddr, remoteaddr) allocated in base.arena; lifetime tied to base.
Metrics snapshot updated by I/O operations; use for per-socket statistics.
Timeouts applied to connect, send/recv, etc. via base.timeouts.
See also
SocketBase_T opaque typedef in SocketCommon.h
SocketCommon_new_base() for allocation
SocketCommon_free_base() for deallocation
SocketCommon_init_base() for initialization from existing FD
docs/METRICS.md for metrics usage
core/SocketConfig.h for SocketTimeouts_T details
Definition at line 141 of file SocketCommon-private.h.
Data Fields
Arena_T arena
Per-socket memory arena for lifecycle
int domain
Address domain (AF_INET, AF_INET6, AF_UNIX)
int fd
Socket file descriptor (-1 if closed)
struct sockaddr_storage local_addr
Local bound address
socklen_t local_addrlen
Length of local_addr
char * localaddr
String representation of local address (allocated in arena)
int localport
Local port number
SocketMetricsSnapshot metrics
Per-socket metrics snapshot (legacy)
pthread_mutex_t mutex
Mutex for thread-safe base access (options, endpoints)
int protocol
Protocol (0 for default)
struct sockaddr_storage remote_addr
Remote peer address
socklen_t remote_addrlen
Length of remote_addr
char * remoteaddr
String representation of remote address (allocated in arena)
int remoteport
Remote port number
SocketStats_T stats
Cumulative I/O statistics for this socket
SocketTimeouts_T timeouts
Timeout configuration
int type
Socket type (SOCK_STREAM, SOCK_DGRAM)
SocketLiveCount
struct SocketLiveCount
Thread-safe live count tracker for socket instances.
Provides thread-safe increment/decrement operations for tracking live socket instances. Used by both Socket_T and SocketDgram_T implementations for debugging and leak detection.
See also
Socket_debug_live_count() for querying the count.
Definition at line 1069 of file SocketCommon.h.
Data Fields
int count
pthread_mutex_t mutex
SocketProxy_Conn_T
struct SocketProxy_Conn_T
Opaque proxy connection context for managing tunneling negotiation.
Central structure for a single proxy operation, handling configuration, resources, asynchronous components, state machine, I/O buffering, timing, and error tracking.
Lifecycle: Allocated from arena in public APIs like SocketProxy_Conn_new(); fields private. Success transfers socket to caller; failure sets error; free cleans remaining.
Groups:
Configuration (copied from user config): proxy/target details, creds, timeouts, headers, TLS.
Resources (owned/managed): arena for memory, socket for I/O (transferred), recvbuf for parsing.
Async resources: dns resolver, poll instance, HappyEyeballs for connect racing (optional external).
HTTP specific: http_parser for CONNECT response validation.
State machine: high-level state, proto_state, result code, SOCKS5 auth flags.
Timing: start times for timeout enforcement using monotonic clock.
I/O state: send/recv buffers (SOCKET_PROXY_BUFFER_SIZE=64KB), offsets for partial transfers.
Error handling: error_buf for messages, transferred flag to prevent double-free.
Thread safety: No - single-threaded design; concurrent access undefined. Memory safety: Arena-managed; secure clear for creds if implemented. TLS conditional: tls_ctx and tls_enabled for HTTPS proxy support.
Note
Opaque to public; internal access only via module functions.
owns_dns_poll flag determines cleanup of async resources.
Buffer sizes configurable via defines; error_buf fixed size.
See also
SocketProxy.h public SocketProxy_Conn_* API for usage.
SocketProxy_Conn_T fields (internal reference).
SocketProxy_ProtoState for detailed protocol sub-states.
SocketProxy_State for connection lifecycle states.
SocketHappyEyeballs_T::he for Proxy Tunneling Module server connection.
SocketHTTP1_Parser_T::http_parser for HTTP parsing.
SocketBuf_T::recvbuf for receive buffering.
Arena_T::arena for memory management.
DNS module for resolution.
Event system for poll integration.
Security module for TLS.
docs/PROXY.md for internals and examples.
docs/MEMORY_MANAGEMENT.md for arena usage.
Definition at line 611 of file SocketProxy-private.h.
Data Fields
Arena_T arena
Memory arena for all allocations
int connect_timeout_ms
Proxy connect timeout
SocketDNS_T dns
DNS resolver for async connection
char error_buf[256]
Error message
SocketHTTP_Headers_T extra_headers
HTTP CONNECT extra headers
int64_t handshake_start_time_ms
When handshake started
int handshake_timeout_ms
Handshake timeout
SocketHE_T he
HappyEyeballs context (during connect)
SocketHTTP1_Parser_T http_parser
HTTP response parser
int owns_dns_poll
1 if we own dns/poll (sync wrapper), 0 if external
char * password
Password (arena copy, may be NULL)
SocketPoll_T poll
Poll instance for async connection
SocketProxy_ProtoState proto_state
Protocol sub-state
char * proxy_host
Proxy hostname (arena copy)
int proxy_port
Proxy port
unsigned char recv_buf[65536]
Temp receive buffer
size_t recv_len
Data in receive buffer
size_t recv_offset
Bytes already processed
SocketBuf_T recvbuf
Receive buffer for protocol parsing
SocketProxy_Result result
Final result
unsigned char send_buf[65536]
Send buffer
size_t send_len
Data in send buffer
size_t send_offset
Bytes already sent
Socket_T socket
Proxy socket (transferred to caller on success)
int socks5_auth_method
Selected auth method
int socks5_need_auth
1 if auth required
int64_t start_time_ms
When operation started
SocketProxy_State state
Main state
char * target_host
Target hostname (arena copy)
int target_port
Target port
SocketTLSContext_T tls_ctx
TLS context from config (copied ptr)
int tls_enabled
1 after successful TLS handshake to proxy
int transferred
1 if socket transferred to caller
SocketProxyType type
Proxy type
char * username
Username (arena copy, may be NULL)
SocketProxy_Config
struct SocketProxy_Config
Configuration structure for proxy connections.
Proxy configuration structure (opaque).
Specifies proxy type, server details, authentication credentials, optional HTTP headers, TLS context (for HTTPS proxies), and timeouts.
Important: String fields (host, username, password) are borrowed references. The caller must ensure these pointers remain valid throughout the proxy operation lifetime. Use Arena allocation or static strings accordingly. Sensitive data in password is securely cleared after use where possible.
Default ports per type:
HTTP/HTTPS: 8080
SOCKS: 1080
See also
SocketProxy_config_defaults() to initialize with safe defaults.
SocketProxy_parse_url() to populate from URL string.
HTTP module for extra_headers usage.
Security module for TLS configuration.
docs/SECURITY.md for credential handling best practices.
Connection Management for Proxy Tunneling Module details.
include/socket/SocketProxy.h for full Proxy Tunneling Module API.
Definition at line 379 of file SocketProxy.h.
Data Fields
int connect_timeout_ms Timeout configuration (0 = use module defaults).
Timeout for connecting to proxy server (default: 30s).
SocketHTTP_Headers_T extra_headers HTTP CONNECT-specific options.
Additional request headers. NULL for none. Owned by caller.
int handshake_timeout_ms
Timeout for proxy protocol handshake and auth (default: 30s).
const char * host Proxy server details.
Proxy hostname or IP address. Must remain valid during operation.
const char * password
Password string. NULL if no auth or username NULL. Securely handled.
int port
Proxy port. 0 uses default for type (SOCKS:1080, HTTP:8080).
SocketTLSContext_T tls_ctx TLS configuration for HTTPS proxies (TLS to proxy server).
TLS context. NULL uses secure system defaults if available. Requires if SOCKET_HAS_TLS.
SocketProxyType type Proxy protocol type (e.g., SOCKET_PROXY_SOCKS5).
const char * username Optional authentication credentials for SOCKS5 or HTTP Basic auth.
Username string. NULL if no auth required. Borrowed reference.
Macro Definition Documentation
MSG_NOSIGNAL
#define MSG_NOSIGNAL 0
MSG_NOSIGNAL fallback for platforms without it.
Suppress SIGPIPE on send operations (Linux/FreeBSD). On platforms without MSG_NOSIGNAL (macOS), we use SO_NOSIGPIPE instead which is set at socket creation time. When MSG_NOSIGNAL is unavailable, we define it as 0 so it can be safely OR'd into flags without effect.
See also
MSG_NOSIGNAL
Definition at line 2469 of file SocketConfig.h.
SAFE_UDP_SIZE
#define SAFE_UDP_SIZE 1472UL /* Safe for Ethernet MTU (1500 - IP/UDP ~28) */
Safe UDP payload size for Ethernet MTU.
Ensures packets fit within standard 1500-byte Ethernet MTU after IP/UDP headers (~28 bytes).
See also
UDP_MAX_PAYLOAD for protocol maximum.
Definition at line 302 of file SocketConfig.h.
SOCKET_AF_INET
#define SOCKET_AF_INET AF_INET
IPv4 address family.
See also
AF_INET
Definition at line 1984 of file SocketConfig.h.
SOCKET_AF_INET6
#define SOCKET_AF_INET6 AF_INET6
IPv6 address family.
See also
AF_INET6
Definition at line 1992 of file SocketConfig.h.
SOCKET_AF_UNIX
#define SOCKET_AF_UNIX AF_UNIX
Unix domain socket address family.
See also
AF_UNIX
Definition at line 2000 of file SocketConfig.h.
SOCKET_AF_UNSPEC
#define SOCKET_AF_UNSPEC AF_UNSPEC
Unspecified address family.
See also
AF_UNSPEC
Definition at line 1976 of file SocketConfig.h.
SOCKET_AI_NUMERICHOST
#define SOCKET_AI_NUMERICHOST AI_NUMERICHOST
Numeric host address flag for getaddrinfo().
See also
AI_NUMERICHOST
Definition at line 2386 of file SocketConfig.h.
SOCKET_AI_NUMERICSERV
#define SOCKET_AI_NUMERICSERV AI_NUMERICSERV
Numeric service port flag for getaddrinfo().
See also
AI_NUMERICSERV
Definition at line 2394 of file SocketConfig.h.
SOCKET_AI_PASSIVE
#define SOCKET_AI_PASSIVE AI_PASSIVE
Passive socket flag for getaddrinfo().
See also
AI_PASSIVE
Definition at line 2378 of file SocketConfig.h.
SOCKET_DEFAULT_DATAGRAM_TTL
#define SOCKET_DEFAULT_DATAGRAM_TTL 64
Default datagram TTL value.
Definition at line 2577 of file SocketConfig.h.
SOCKET_DEFAULT_DNS_TIMEOUT_MS
#define SOCKET_DEFAULT_DNS_TIMEOUT_MS 5000 /* 5 seconds */
Default DNS resolution timeout.
See also
SocketHappyEyeballs_T for Happy Eyeballs implementation.
Definition at line 1411 of file SocketConfig.h.
SOCKET_DEFAULT_KEEPALIVE_COUNT
#define SOCKET_DEFAULT_KEEPALIVE_COUNT 3
Default TCP keep-alive probe count.
Definition at line 2520 of file SocketConfig.h.
SOCKET_DEFAULT_KEEPALIVE_IDLE
#define SOCKET_DEFAULT_KEEPALIVE_IDLE 60
Default TCP keep-alive idle time (seconds).
Definition at line 2506 of file SocketConfig.h.
SOCKET_DEFAULT_KEEPALIVE_INTERVAL
#define SOCKET_DEFAULT_KEEPALIVE_INTERVAL 10
Default TCP keep-alive interval (seconds).
Definition at line 2513 of file SocketConfig.h.
SOCKET_DGRAM_TYPE
#define SOCKET_DGRAM_TYPE SOCK_DGRAM
UDP datagram socket type.
See also
SOCK_DGRAM
Definition at line 1968 of file SocketConfig.h.
SOCKET_DNS_CACHE_HASH_SIZE
#define SOCKET_DNS_CACHE_HASH_SIZE 1021
DNS cache hash table size.
Prime number for optimal hash distribution in cache lookups.
Definition at line 630 of file SocketConfig.h.
SOCKET_DNS_COMPLETION_SIGNAL_BYTE
#define SOCKET_DNS_COMPLETION_SIGNAL_BYTE 1
Completion signal byte value for DNS pipe signaling.
Definition at line 573 of file SocketConfig.h.
SOCKET_DNS_DEFAULT_CACHE_MAX_ENTRIES
#define SOCKET_DNS_DEFAULT_CACHE_MAX_ENTRIES 1000
Default maximum DNS cache entries.
Limits memory usage by capping cached DNS results. When exceeded, oldest entries are evicted (LRU).
See also
SocketDNS_cache_set_max_entries() to configure at runtime.
Definition at line 619 of file SocketConfig.h.
SOCKET_DNS_DEFAULT_CACHE_TTL_SECONDS
#define SOCKET_DNS_DEFAULT_CACHE_TTL_SECONDS 300
Default DNS cache TTL in seconds.
Controls how long DNS resolution results are cached before being considered stale. Default 5 minutes balances freshness with performance.
See also
SocketDNS_cache_set_ttl() to configure at runtime.
Definition at line 606 of file SocketConfig.h.
SOCKET_DNS_MAX_LABEL_LENGTH
#define SOCKET_DNS_MAX_LABEL_LENGTH 63
Maximum DNS label length.
Per RFC 1035, DNS labels are limited to 63 characters.
Definition at line 534 of file SocketConfig.h.
SOCKET_DNS_MAX_PENDING
#define SOCKET_DNS_MAX_PENDING 1000
Maximum pending DNS requests.
See also
SocketDNS_T for DNS implementation.
Definition at line 523 of file SocketConfig.h.
SOCKET_DNS_PIPE_BUFFER_SIZE
#define SOCKET_DNS_PIPE_BUFFER_SIZE 256
Completion pipe read buffer size.
Definition at line 564 of file SocketConfig.h.
SOCKET_DNS_PORT_STR_SIZE
#define SOCKET_DNS_PORT_STR_SIZE 16
Port number string buffer size.
Definition at line 582 of file SocketConfig.h.
SOCKET_DNS_REQUEST_HASH_SIZE
#define SOCKET_DNS_REQUEST_HASH_SIZE 1021
DNS request hash table size.
Prime number for optimal hash distribution.
See also
SOCKET_DNS_MAX_PENDING for request limits.
Definition at line 555 of file SocketConfig.h.
SOCKET_DNS_THREAD_COUNT
#define SOCKET_DNS_THREAD_COUNT 4
Number of DNS worker threads.
See also
SocketDNS_T for async DNS resolution.
Definition at line 513 of file SocketConfig.h.
SOCKET_DNS_THREAD_NAME_SIZE
#define SOCKET_DNS_THREAD_NAME_SIZE 16
Thread name buffer size.
POSIX maximum 16 characters including null terminator.
Definition at line 593 of file SocketConfig.h.
SOCKET_DNS_WORKER_STACK_SIZE
#define SOCKET_DNS_WORKER_STACK_SIZE (128 * 1024)
DNS worker thread stack size.
Definition at line 543 of file SocketConfig.h.
SOCKET_FD_CLOEXEC
#define SOCKET_FD_CLOEXEC FD_CLOEXEC
File descriptor close-on-exec flag.
See also
FD_CLOEXEC
Definition at line 2119 of file SocketConfig.h.
SOCKET_HAS_ACCEPT4
#define SOCKET_HAS_ACCEPT4 1
Linux-specific accept4() support flag.
Linux-specific features detection.
Detects Linux platform (linux) to enable Linux-only optimizations and options:
accept4(): Atomic accept with non-blocking and CLOEXEC flags.
SO_DOMAIN: Socket option to query address family (AF_INET, etc.).
On non-Linux platforms, these fall back to standard accept() + fcntl() and no SO_DOMAIN support.
See also
accept4(2) Linux man page for accept4 details.
Socket_accept() portable wrapper.
getsockopt(2) for SO_DOMAIN usage.
Definition at line 2105 of file SocketConfig.h.
SOCKET_HAS_RECVMSG
#define SOCKET_HAS_RECVMSG 1
recvmsg() support flag.
Standard POSIX - always available.
Definition at line 1365 of file SocketConfig.h.
SOCKET_HAS_SENDMSG
#define SOCKET_HAS_SENDMSG 1
sendmsg() support flag.
Standard POSIX - always available.
Definition at line 1356 of file SocketConfig.h.
SOCKET_HAS_SO_NOSIGPIPE
#define SOCKET_HAS_SO_NOSIGPIPE 0
SO_NOSIGPIPE support flag.
BSD/macOS socket option to suppress SIGPIPE. This is set once at socket creation time as an alternative to MSG_NOSIGNAL. On Linux, MSG_NOSIGNAL is preferred and this macro will be 0.
See also
SO_NOSIGPIPE
Definition at line 2493 of file SocketConfig.h.
SOCKET_HAS_TCP_CONGESTION
#define SOCKET_HAS_TCP_CONGESTION 0
TCP congestion control algorithm (if available).
See also
TCP_CONGESTION
Definition at line 2224 of file SocketConfig.h.
SOCKET_HAS_TCP_FASTOPEN
#define SOCKET_HAS_TCP_FASTOPEN 0
TCP Fast Open support (if available).
See also
TCP_FASTOPEN
Definition at line 2240 of file SocketConfig.h.
SOCKET_HAS_TCP_USER_TIMEOUT
#define SOCKET_HAS_TCP_USER_TIMEOUT 0
TCP user timeout support (if available).
See also
TCP_USER_TIMEOUT
Definition at line 2253 of file SocketConfig.h.
SOCKET_IP_ADD_MEMBERSHIP
#define SOCKET_IP_ADD_MEMBERSHIP IP_ADD_MEMBERSHIP
IP multicast add membership.
See also
IP_ADD_MEMBERSHIP
Definition at line 2357 of file SocketConfig.h.
SOCKET_IP_DROP_MEMBERSHIP
#define SOCKET_IP_DROP_MEMBERSHIP IP_DROP_MEMBERSHIP
IP multicast drop membership.
See also
IP_DROP_MEMBERSHIP
Definition at line 2365 of file SocketConfig.h.
SOCKET_IP_TTL
#define SOCKET_IP_TTL IP_TTL
IP time to live.
See also
IP_TTL
Definition at line 2349 of file SocketConfig.h.
SOCKET_IPPROTO_IP
#define SOCKET_IPPROTO_IP IPPROTO_IP
IP protocol number.
See also
IPPROTO_IP
Definition at line 2024 of file SocketConfig.h.
SOCKET_IPPROTO_IPV6
#define SOCKET_IPPROTO_IPV6 IPPROTO_IPV6
IPv6 protocol number.
See also
IPPROTO_IPV6
Definition at line 2032 of file SocketConfig.h.
SOCKET_IPPROTO_TCP
#define SOCKET_IPPROTO_TCP IPPROTO_TCP
TCP protocol number.
See also
IPPROTO_TCP
Definition at line 2008 of file SocketConfig.h.
SOCKET_IPPROTO_UDP
#define SOCKET_IPPROTO_UDP IPPROTO_UDP
UDP protocol number.
See also
IPPROTO_UDP
Definition at line 2016 of file SocketConfig.h.
SOCKET_IPV4_MAX_PREFIX
#define SOCKET_IPV4_MAX_PREFIX 32 /* IPv4 address bits */
Maximum IPv4 prefix length in bits.
Definition at line 342 of file SocketConfig.h.
SOCKET_IPV6_MAX_PREFIX
#define SOCKET_IPV6_MAX_PREFIX 128 /* IPv6 address bits */
Maximum IPv6 prefix length in bits.
Definition at line 333 of file SocketConfig.h.
SOCKET_IPV6_UNICAST_HOPS
#define SOCKET_IPV6_UNICAST_HOPS IPV6_UNICAST_HOPS
IPv6 multicast add membership.
See also
IPV6_ADD_MEMBERSHIP, IPV6_JOIN_GROUP
IPv6 multicast drop membership.
See also
IPV6_DROP_MEMBERSHIP, IPV6_LEAVE_GROUP
IPv6 unicast hop limit.
See also
IPV6_UNICAST_HOPS
Definition at line 2336 of file SocketConfig.h.
SOCKET_IPV6_V6ONLY
#define SOCKET_IPV6_V6ONLY IPV6_V6ONLY
IPv6 only flag.
Restricts socket to IPv6 only (no IPv4-mapped IPv6 addresses).
See also
IPV6_V6ONLY
Definition at line 2300 of file SocketConfig.h.
SOCKET_KEEPALIVE_MAX_COUNT
#define SOCKET_KEEPALIVE_MAX_COUNT 32
Maximum TCP keep-alive probe count.
Limits the number of failed probes before disconnect.
Definition at line 2549 of file SocketConfig.h.
SOCKET_KEEPALIVE_MAX_IDLE
#define SOCKET_KEEPALIVE_MAX_IDLE (86400 * 365) /* 1 year in seconds */
Maximum TCP keep-alive idle time (seconds).
Limits the idle time before first probe to 1 year.
Definition at line 2529 of file SocketConfig.h.
SOCKET_KEEPALIVE_MAX_INTERVAL
#define SOCKET_KEEPALIVE_MAX_INTERVAL 3600 /* 1 hour */
Maximum TCP keep-alive interval (seconds).
Limits the interval between probes to 1 hour.
Definition at line 2539 of file SocketConfig.h.
SOCKET_MAX_CONGESTION_ALGO_LEN
#define SOCKET_MAX_CONGESTION_ALGO_LEN 63
Maximum congestion control algorithm name length.
Maximum length of TCP_CONGESTION algorithm name string (excluding null).
Definition at line 2569 of file SocketConfig.h.
SOCKET_MAX_DEFER_ACCEPT_SEC
#define SOCKET_MAX_DEFER_ACCEPT_SEC 3600 /* 1 hour */
Maximum TCP defer accept timeout (seconds).
Limits TCP_DEFER_ACCEPT/SO_ACCEPTFILTER timeout to 1 hour.
Definition at line 2559 of file SocketConfig.h.
SOCKET_MAX_FDS_PER_MSG
#define SOCKET_MAX_FDS_PER_MSG 253 /* SCM_MAX_FD on most POSIX systems */
Maximum file descriptors per SCM_RIGHTS message.
Unix domain socket file descriptor passing limit.
See also
Socket_sendfds() for FD passing implementation.
Definition at line 387 of file SocketConfig.h.
SOCKET_MAX_LISTEN_BACKLOG
#define SOCKET_MAX_LISTEN_BACKLOG 1024
Maximum backlog for listen() system call.
See also
Socket_listen() for server socket setup.
Definition at line 375 of file SocketConfig.h.
SOCKET_MAX_PORT
#define SOCKET_MAX_PORT 65535 /* Standard TCP/UDP port max */
Maximum TCP/UDP port number.
Standard maximum for port numbers.
Definition at line 353 of file SocketConfig.h.
SOCKET_MAX_TTL
#define SOCKET_MAX_TTL 255 /* Standard IP TTL max */
Maximum IP TTL (Time To Live) value.
Standard maximum for IP packets.
Definition at line 324 of file SocketConfig.h.
SOCKET_MSG_NOSIGNAL
#define SOCKET_MSG_NOSIGNAL MSG_NOSIGNAL
Suppress SIGPIPE on send operations.
See also
MSG_NOSIGNAL
Definition at line 2478 of file SocketConfig.h.
SOCKET_MULTICAST_DEFAULT_INTERFACE
#define SOCKET_MULTICAST_DEFAULT_INTERFACE 0
Default multicast interface index.
Definition at line 2584 of file SocketConfig.h.
SOCKET_NI_MAXHOST
#define SOCKET_NI_MAXHOST NI_MAXHOST
Maximum host name length for getnameinfo().
See also
NI_MAXHOST
Definition at line 2418 of file SocketConfig.h.
SOCKET_NI_MAXSERV
#define SOCKET_NI_MAXSERV NI_MAXSERV
Maximum service name length for getnameinfo().
See also
NI_MAXSERV
Definition at line 2426 of file SocketConfig.h.
SOCKET_NI_NUMERICHOST
#define SOCKET_NI_NUMERICHOST NI_NUMERICHOST
Numeric host address flag for getnameinfo().
See also
NI_NUMERICHOST
Definition at line 2402 of file SocketConfig.h.
SOCKET_NI_NUMERICSERV
#define SOCKET_NI_NUMERICSERV NI_NUMERICSERV
Numeric service port flag for getnameinfo().
See also
NI_NUMERICSERV
Definition at line 2410 of file SocketConfig.h.
SOCKET_SENDFILE_FALLBACK_BUFFER_SIZE
#define SOCKET_SENDFILE_FALLBACK_BUFFER_SIZE 8192
Fallback buffer size for sendfile operations.
Used when sendfile() is not available or fails.
Definition at line 313 of file SocketConfig.h.
SOCKET_SHUT_RD
#define SOCKET_SHUT_RD SHUT_RD
Shutdown read direction.
See also
SHUT_RD
Definition at line 2439 of file SocketConfig.h.
SOCKET_SHUT_RDWR
#define SOCKET_SHUT_RDWR SHUT_RDWR
Shutdown both read and write directions.
See also
SHUT_RDWR
Definition at line 2455 of file SocketConfig.h.
SOCKET_SHUT_WR
#define SOCKET_SHUT_WR SHUT_WR
Shutdown write direction.
See also
SHUT_WR
Definition at line 2447 of file SocketConfig.h.
SOCKET_SO_BROADCAST
#define SOCKET_SO_BROADCAST SO_BROADCAST
Enable broadcast transmission.
See also
SO_BROADCAST
Definition at line 2127 of file SocketConfig.h.
SOCKET_SO_KEEPALIVE
#define SOCKET_SO_KEEPALIVE SO_KEEPALIVE
Enable keep-alive packets.
See also
SO_KEEPALIVE
Definition at line 2135 of file SocketConfig.h.
SOCKET_SO_PEERCRED
#define SOCKET_SO_PEERCRED SO_PEERCRED
Peer credentials.
See also
SO_PEERCRED
Definition at line 2175 of file SocketConfig.h.
SOCKET_SO_RCVBUF
#define SOCKET_SO_RCVBUF SO_RCVBUF
Receive buffer size.
See also
SO_RCVBUF
Definition at line 2159 of file SocketConfig.h.
SOCKET_SO_RCVTIMEO
#define SOCKET_SO_RCVTIMEO SO_RCVTIMEO
Receive timeout.
See also
SO_RCVTIMEO
Definition at line 2143 of file SocketConfig.h.
SOCKET_SO_REUSEADDR
#define SOCKET_SO_REUSEADDR SO_REUSEADDR
Allow reuse of local addresses.
See also
SO_REUSEADDR
Definition at line 2053 of file SocketConfig.h.
SOCKET_SO_REUSEPORT
#define SOCKET_SO_REUSEPORT 0
Allow reuse of local ports (if available).
See also
SO_REUSEPORT
Definition at line 2065 of file SocketConfig.h.
SOCKET_SO_SNDBUF
#define SOCKET_SO_SNDBUF SO_SNDBUF
Send buffer size.
See also
SO_SNDBUF
Definition at line 2167 of file SocketConfig.h.
SOCKET_SO_SNDTIMEO
#define SOCKET_SO_SNDTIMEO SO_SNDTIMEO
Send timeout.
See also
SO_SNDTIMEO
Definition at line 2151 of file SocketConfig.h.
SOCKET_SOCK_CLOEXEC
#define SOCKET_SOCK_CLOEXEC 0
SOCK_CLOEXEC flag for socket creation (if available).
See also
SOCK_CLOEXEC
Definition at line 2079 of file SocketConfig.h.
SOCKET_SOL_SOCKET
#define SOCKET_SOL_SOCKET SOL_SOCKET
Socket options level.
See also
SOL_SOCKET
Definition at line 2045 of file SocketConfig.h.
SOCKET_STREAM_TYPE
#define SOCKET_STREAM_TYPE SOCK_STREAM
TCP stream socket type.
See also
SOCK_STREAM
Definition at line 1960 of file SocketConfig.h.
SOCKET_TCP_KEEPCNT
#define SOCKET_TCP_KEEPCNT TCP_KEEPCNT
Keep-alive probe count.
See also
TCP_KEEPCNT
Definition at line 2212 of file SocketConfig.h.
SOCKET_TCP_KEEPIDLE
#define SOCKET_TCP_KEEPIDLE TCP_KEEPIDLE
Keep-alive idle time.
See also
TCP_KEEPIDLE
Definition at line 2196 of file SocketConfig.h.
SOCKET_TCP_KEEPINTVL
#define SOCKET_TCP_KEEPINTVL TCP_KEEPINTVL
Keep-alive interval.
See also
TCP_KEEPINTVL
Definition at line 2204 of file SocketConfig.h.
SOCKET_TCP_NODELAY
#define SOCKET_TCP_NODELAY TCP_NODELAY
Disable Nagle's algorithm.
See also
TCP_NODELAY
Definition at line 2188 of file SocketConfig.h.
SocketBase_T
typedef struct SocketBase_T * SocketBase_T SocketBase_T
Opaque base structure for shared socket functionality.
Contains common fields shared across socket subtypes (Socket_T, SocketDgram_T, etc.):
File descriptor (fd)
Memory arena for lifecycle management
Local and remote endpoint information (addresses, ports)
Timeouts configuration
Metrics snapshot
Domain, type, protocol
Subtypes embed a pointer to SocketBase_T for shared resource management. Allocation: Use SocketCommon_new_base() which creates arena and initializes. Deallocation: Use SocketCommon_free_base() in reverse order. Thread Safety: Individual fields not thread-safe; protect with external mutexes if shared.
Rationale: Reduces code duplication in creation, initialization, cleanup across modules. Ensures consistent resource acquisition/cleanup order per layered architecture rules.
Definition at line 660 of file SocketCommon.h.
SOCKETBUF_ALLOC_OVERHEAD
#define SOCKETBUF_ALLOC_OVERHEAD 64
Allocation overhead for arena bookkeeping during buffer resize.
See also
SocketBuf_T for buffer implementation.
Definition at line 485 of file SocketConfig.h.
SOCKETBUF_INITIAL_CAPACITY
#define SOCKETBUF_INITIAL_CAPACITY 1024
Initial capacity when buffer reserve grows from zero.
See also
SocketBuf_T for buffer implementation.
Definition at line 475 of file SocketConfig.h.
SOCKETBUF_MIN_CAPACITY
#define SOCKETBUF_MIN_CAPACITY 512
Minimum capacity for circular buffers.
See also
SocketBuf_T for buffer implementation.
Definition at line 465 of file SocketConfig.h.
SOCKETLIVECOUNT_STATIC_INIT
#define SOCKETLIVECOUNT_STATIC_INIT
Value:
  {                                                                           \
    0, PTHREAD_MUTEX_INITIALIZER                                              \
  }
Static initializer for SocketLiveCount structure.
Initializes the count to 0 and the mutex to the default unlocked state using PTHREAD_MUTEX_INITIALIZER.
Usage: static struct SocketLiveCount tracker = SOCKETLIVECOUNT_STATIC_INIT;
See also
struct SocketLiveCount for field details.
SocketLiveCount_increment(), SocketLiveCount_decrement() for usage.
Definition at line 1088 of file SocketCommon.h.
T [1/2]
#define T Socket_T
Opaque context for managing asynchronous proxy tunneling operations.
Handles connection to proxy server, protocol handshake, authentication, and state transitions for various proxy types (HTTP CONNECT, SOCKS). Integrates with SocketPoll for event-driven processing and SocketDNS for proxy server resolution.
See also
SocketProxy_Conn_new() for creating a new connection context.
SocketProxy_Conn_start() for fully asynchronous start.
SocketProxy_Conn_free() for resource cleanup.
SocketProxy_State for connection states.
docs/PROXY.md for detailed Proxy Tunneling Module configuration and usage.
Definition at line 174 of file Socket.h.
T [2/2]
#define T SocketProxy_Conn_T
Opaque context for managing asynchronous proxy tunneling operations.
Handles connection to proxy server, protocol handshake, authentication, and state transitions for various proxy types (HTTP CONNECT, SOCKS). Integrates with SocketPoll for event-driven processing and SocketDNS for proxy server resolution.
See also
SocketProxy_Conn_new() for creating a new connection context.
SocketProxy_Conn_start() for fully asynchronous start.
SocketProxy_Conn_free() for resource cleanup.
SocketProxy_State for connection states.
docs/PROXY.md for detailed Proxy Tunneling Module configuration and usage.
Definition at line 117 of file SocketProxy.h.
UDP_MAX_PAYLOAD
#define UDP_MAX_PAYLOAD
Value:
  65507UL /* IPv4/6 max UDP payload excluding headers                         \
           */
Maximum UDP payload size excluding headers.
Respects IPv4/IPv6 protocol maximums to avoid fragmentation.
See also
SAFE_UDP_SIZE for MTU-safe size.
Definition at line 288 of file SocketConfig.h.
Typedef Documentation
SocketBuf_T
typedef struct SocketBuf_T* SocketBuf_T
Opaque handle to a circular buffer instance.
This type represents a circular buffer used for efficient buffering in socket I/O operations. It supports zero-copy read/write, dynamic resizing, and secure clearing for sensitive data.
Memory is managed via an associated Arena_T, allowing batch deallocation. The buffer automatically handles wraparound logic internally.
Thread Safety\n Conditional - individual operations are atomic, but concurrent
access requires external synchronization for multi-threaded use.
See also
SocketBuf_new() to create an instance.
SocketBuf_release() to release the handle (sets pointer to NULL).
Arena_T for memory management.
SocketPool_T in Connection Management Modules for pool-integrated buffers.
SocketHTTP1_Parser_T in HTTP Modules for HTTP parsing usage.
Definition at line 115 of file SocketBuf.h.
Enumeration Type Documentation
SocketProxy_Result
enum SocketProxy_Result
Result codes for proxy operations.
Standardized error and status codes mapping protocol-specific responses (e.g., SOCKS5 reply codes, HTTP status) to a unified interface. Use SocketProxy_result_string() for human-readable descriptions.
See also
SocketProxy_Conn_result() to retrieve after async completion.
SocketProxy_result_string() for string conversion.
docs/PROXY.md for mapping to specific protocol errors.
Enumerator
PROXY_OK
Success: tunnel established and ready for use.
PROXY_IN_PROGRESS
Asynchronous operation still in progress.
PROXY_ERROR
Generic proxy error (unspecified cause).
PROXY_ERROR_CONNECT
Failed to establish connection to proxy server.
PROXY_ERROR_AUTH_REQUIRED
Proxy requires authentication not provided.
PROXY_ERROR_AUTH_FAILED
Provided credentials rejected by proxy.
PROXY_ERROR_FORBIDDEN
Proxy forbids connection to specified target.
PROXY_ERROR_HOST_UNREACHABLE
Target host cannot be reached (SOCKS5 code 3).
PROXY_ERROR_NETWORK_UNREACHABLE
Target network unreachable (SOCKS5 code 4).
PROXY_ERROR_CONNECTION_REFUSED
Connection refused by target (SOCKS5 code 5).
PROXY_ERROR_TTL_EXPIRED
TTL expired en route to target (SOCKS5 code 6).
PROXY_ERROR_PROTOCOL
Protocol-level error (invalid response, etc.).
PROXY_ERROR_UNSUPPORTED
Command or address type not supported by proxy.
PROXY_ERROR_TIMEOUT
Operation timed out (connect or handshake).
PROXY_ERROR_CANCELLED
Operation explicitly cancelled by user.
Definition at line 287 of file SocketProxy.h.
SocketProxy_State
enum SocketProxy_State
States in the proxy connection state machine.
Tracks progress through proxy connection phases: resolution, connection, TLS (if HTTPS proxy), authentication, and protocol handshake.
State transition diagram: IDLE CONNECTING_PROXY [TLS_TO_PROXY (HTTPS only)] HANDSHAKE_SEND CONNECTED HANDSHAKE_RECV [AUTH_SEND/AUTH_RECV (SOCKS5)] FAILED or CANCELLED
See also
SocketProxy_Conn_state() to query current state.
SocketProxy_state_string() for string names.
docs/ASYNC_IO.md for integration with event loops.
Enumerator
PROXY_STATE_IDLE
Initial state: connection not started.
PROXY_STATE_CONNECTING_PROXY
Resolving/connecting to proxy server via HappyEyeballs.
PROXY_STATE_TLS_TO_PROXY
Performing TLS handshake to HTTPS proxy.
PROXY_STATE_HANDSHAKE_SEND
Sending proxy protocol request (CONNECT or SOCKS).
PROXY_STATE_HANDSHAKE_RECV
Awaiting and parsing proxy response.
PROXY_STATE_AUTH_SEND
Sending SOCKS5 authentication subnegotiation.
PROXY_STATE_AUTH_RECV
Receiving SOCKS5 auth response.
PROXY_STATE_CONNECTED
Success: tunnel ready for target communication.
PROXY_STATE_FAILED
Terminal: operation failed with error.
PROXY_STATE_CANCELLED
Terminal: operation cancelled by user.
Definition at line 335 of file SocketProxy.h.
SocketProxyType
enum SocketProxyType
Enumeration of supported proxy protocol types.
Defines the proxy protocols handled by the SocketProxy module, including HTTP CONNECT for web proxies and SOCKS variants for general tunneling.
See also
SocketProxy_Config::type for configuration.
SocketProxy_type_string() for string representations.
docs/PROXY.md for protocol-specific details and limitations.
Enumerator
SOCKET_PROXY_NONE
No proxy - direct connection to target.
SOCKET_PROXY_HTTP
HTTP CONNECT method (RFC 7231). Supports Basic auth.
SOCKET_PROXY_HTTPS
HTTPS CONNECT - TLS-encrypted connection to proxy before handshake.
SOCKET_PROXY_SOCKS4
SOCKS4 protocol - IPv4 addresses only, no auth.
SOCKET_PROXY_SOCKS4A
SOCKS4a extension - supports domain name resolution at proxy.
SOCKET_PROXY_SOCKS5
SOCKS5 protocol (RFC 1928) - supports IPv6, auth, UDP.
SOCKET_PROXY_SOCKS5H
SOCKS5 with hostname resolution performed by proxy server.
Definition at line 254 of file SocketProxy.h.
Function Documentation
Socket_accept()
Socket_T Socket_accept (Socket_T socket) extern
Accept incoming connection.
Parameters
socket Listening socket.
Returns
New socket or NULL if would block (EAGAIN/EWOULDBLOCK).
Exceptions
Socket_Failed on error.
Note
Returns NULL for non-blocking sockets when no connection is pending.
See also
Socket_listen() for setting up listening sockets.
Referenced by main(), and main().
Socket_accept_timeout()
Socket_T Socket_accept_timeout (Socket_T socket, int timeout_ms) extern
Accept incoming connection with explicit timeout.
Like Socket_accept() but with explicit timeout support. Useful for servers that need to periodically check for shutdown signals or perform maintenance.
Parameters
[in] socket Listening socket
[in] timeout_ms Timeout in milliseconds (0 = return immediately if no connection, -1 = block indefinitely)
Returns
New client socket, or NULL if timeout expired with no connection
Exceptions
Socket_Failed on accept error (not including timeout/EAGAIN)
Thread Safety\n Yes - operates on listening socket
Example
while (running) {
    Socket_T client = Socket_accept_timeout(server, 1000);
    if (client) {
        handle_client(client);
    }
    // Check shutdown flag every second
}
Note
Temporarily sets socket to non-blocking mode if needed
Returns NULL (not exception) when timeout expires
See also
Socket_accept() for basic accept without timeout
Socket_listen_tcp() for creating listening socket
Socket_bandwidth_wait_ms()
int64_t Socket_bandwidth_wait_ms (Socket_T socket, size_t bytes) extern
Get wait time until bandwidth available.
Parameters
socket Socket to query.
bytes Number of bytes needed.
Returns
Milliseconds to wait, 0 if immediate, -1 if impossible.
Thread Safety\n Yes.
Useful for event loop integration - use as poll timeout.
See also
Socket_send_limited() for bandwidth-limited operations.
Socket_bind()
void Socket_bind (Socket_T socket, const char * host, int port) extern
Bind a socket to a local IP address and port.
Associates the socket with a local network address and port using bind(2). This is required for servers (before listen()) and clients wanting specific local endpoints (e.g., source IP selection). Hostnames trigger synchronous DNS resolution, which may block; use IP literals or async DNS for non-blocking.
Supported formats for host:
NULL or "0.0.0.0": Bind to all IPv4 interfaces
"::": Bind to all IPv6 interfaces (dual-stack if possible)
Specific IP: "192.168.1.100" or "[2001:db8::1]"
Hostname: Resolves via getaddrinfo(3), blocks up to ~30s on failure
Port range: 1-65535 (SOCKET_MAX_PORT); 0 for kernel-assigned ephemeral port.
Edge cases:
Port 0: OS assigns available port; query with Socket_getlocalport()
Already bound: Raises Socket_Failed (EINVAL or EADDRINUSE)
Permission denied on privileged ports (<1024): Socket_Failed (EACCES)
Address not local: Socket_Failed (EADDRNOTAVAIL)
For non-blocking bind, resolve hostname first with SocketDNS_resolve_sync() or async.
Parameters
[in,out] socket Unbound socket to bind (updated with local addr/port state)
[in] host Local address string (IP or hostname; NULL for any)
[in] port Local port (1-65535; 0 for ephemeral)
Exceptions
Socket_Failed Bind failed: EADDRINUSE (port busy), EADDRNOTAVAIL (invalid local addr), EACCES (permission), ENETDOWN (interface down), getaddrinfo errors for hostnames
Thread Safety\n Yes - binds specific socket instance atomically
Basic Server Bind
Socket_T server = Socket_new(AF_INET, SOCK_STREAM, 0);
Socket_bind(server, NULL, 8080);  // Bind to any IP on port 8080
Socket_listen(server, SOMAXCONN);
Client Bind to Specific Interface
TRY {
    Socket_T client = Socket_new(AF_INET6, SOCK_STREAM, 0);
    Socket_bind(client, "::1", 0);  // Bind to loopback, ephemeral port
    Socket_connect(client, "example.com", 80);
    int local_port = Socket_getlocalport(client);  // Query assigned port
} EXCEPT(Socket_Failed) {
    // Handle bind/connect failure
} END_TRY;
Async DNS for Non-Blocking
SocketDNS_T dns = SocketDNS_new();
Request_T req = Socket_bind_async(dns, sock, "localhost", 8080);
// Poll dns fd or integrate with event loop
struct addrinfo *res = SocketDNS_getresult(dns, req);
if (res) Socket_bind_with_addrinfo(sock, res);
freeaddrinfo(res);
Note
After bind, use Socket_getlocaladdr() and Socket_getlocalport() to confirm
For IPv6, prefer "::" for dual-stack; use SocketConfig_set_ipv6only() for v6-only
Warning
Hostname resolution blocks; use Socket_bind_async() or IP for async apps
Privileged ports require root or cap_net_bind_service; use setcap or non-privileged
In containers/Docker, ensure –cap-add=NET_BIND_SERVICE or run as root
Complexity\n O(1) for IP bind; O(n) for hostname resolution where n=lookup
time
See also
Socket_listen() next step for servers
Socket_getlocaladdr(), Socket_getlocalport() for bound address query
Socket_bind_unix() for Unix domain binding
Socket_bind_async(), Socket_bind_with_addrinfo() for async variant
SocketDNS_T Core I/O Modules for async resolution
docs/SECURITY.md bind Security Modules considerations
Referenced by main(), and main().
Socket_bind_async()
Request_T Socket_bind_async (SocketDNS_T dns, Socket_T socket, const char * host, int port) extern
Start async DNS resolution for bind.
Parameters
dns DNS resolver instance.
socket Socket to bind.
host IP address or hostname (NULL for any).
port Port number (1 to SOCKET_MAX_PORT).
Returns
DNS request handle.
Exceptions
Socket_Failed on error.
See also
Socket_bind_async_cancel() for canceling the request.
Socket_bind_with_addrinfo() for binding with resolved address.
Socket_bind_async_cancel()
void Socket_bind_async_cancel (SocketDNS_T dns, Request_T req) extern
Cancel pending async bind resolution.
Parameters
dns DNS resolver instance.
req Request handle returned by Socket_bind_async.
See also
Socket_bind_async() for starting async bind.
Socket_bind_unix()
void Socket_bind_unix (Socket_T socket, const char * path) extern
Bind to Unix domain socket path.
Parameters
socket Socket to bind (AF_UNIX).
path Socket file path.
Exceptions
Socket_Failed on error.
Note
Fails with EADDRINUSE if path exists. Max path length ~108 bytes.
Supports abstract namespace sockets on Linux (path starting with '@').
See also
Socket_connect_unix() for connecting to Unix sockets.
Socket_bind_with_addrinfo()
void Socket_bind_with_addrinfo (Socket_T socket, struct addrinfo * res) extern
Bind socket using resolved address.
Parameters
socket Socket to bind.
res Resolved addrinfo result from DNS resolution.
Exceptions
Socket_Failed on error.
See also
Socket_bind_async() for async DNS resolution.
Socket_bind() for direct binding.
Socket_connect()
void Socket_connect (Socket_T socket, const char * host, int port) extern
Establish a connection to a remote host and port.
Initiates a connection to the remote endpoint using connect(2). For TCP sockets, this performs the 3-way handshake; for UDP, sets default peer address for send(). Hostnames trigger synchronous DNS via getaddrinfo(3), potentially blocking.
Supported host formats:
IP address: "192.168.1.1", "[2001:db8::1]"
Hostname: "example.com" - resolves A/AAAA records
IPv6 literals require [] brackets
Port: 1-65535; common services like 80 (HTTP), 443 (HTTPS)
Behavior:
Blocking mode: Waits for handshake completion or timeout/failure
Non-blocking: Returns immediately; use Socket_isconnected() or poll for completion
Edge cases:
Unreachable host: Socket_Failed (ETIMEDOUT or ENETUNREACH)
Refused connection: Socket_Failed (ECONNREFUSED)
DNS failure: Socket_Failed with EAI_* mapped to errno
Already connected: Socket_Failed (EISCONN)
For non-blocking connect, pair with SocketPoll for writable event.
Parameters
[in,out] socket Unconnected socket (updated with peer addr/port on success)
[in] host Remote address (IP or hostname)
[in] port Remote port (1-65535)
Exceptions
Socket_Failed Connect failed: ECONNREFUSED (no listener), ETIMEDOUT (no route/response), ENETUNREACH/EHOSTUNREACH (routing), getaddrinfo/DNS errors, EMSGSIZE (MTU issue)
Thread Safety\n Yes - connects specific socket instance
Basic Client Connect
Socket_T sock = Socket_new(AF_INET, SOCK_STREAM, 0);
Socket_connect(sock, "www.example.com", 80);
// Now connected; send HTTP request
ssize_t n = Socket_sendall(sock, "GET / HTTP/1.1\r\nHost:
example.com\r\n\r\n", len); Socket_free(&sock);
Non-Blocking Connect
Socket_T sock = Socket_new(AF_INET, SOCK_STREAM, 0);
Socket_setnonblocking(sock);
TRY {
    Socket_connect(sock, "example.com", 443);
} EXCEPT(Socket_Failed) {
    if (Socket_geterrno() == EINPROGRESS) {
        // Poll for writable
        SocketPoll_T poll = SocketPoll_new(1);
        SocketPoll_add(poll, sock, POLL_WRITE, sock);
        SocketEvent_T *ev = NULL;
        if (SocketPoll_wait(poll, &ev, timeout) > 0) {
            // Check getsockopt SO_ERROR for connect result
        }
    }
}
With Local Bind and Timeout
SocketTimeouts_T to = { .connect_ms = 5000 };
Socket_timeouts_set(sock, &to);
Socket_bind(sock, "192.168.1.10", 0);  // Specific source IP
Socket_connect(sock, "::1", 8080);  // IPv6 loopback
Note
Success sets peer address; query with Socket_getpeeraddr/port()
For UDP, connect sets default peer for send() without addr
Dual-stack: Prefers IPv6 if available; configure via hints in async DNS
Warning
Synchronous DNS blocks; use Socket_connect_async() for event loops
Firewalls/NAT may affect connectivity; test with real networks
In non-blocking, EINPROGRESS means pending - check SO_ERROR later
Complexity\n O(1) handshake time; O(n) for DNS where n=resolution latency
See also
Socket_isconnected() to verify connection status
Socket_getpeeraddr(), Socket_getpeerport() for remote endpoint
Socket_bind() for local address binding before connect
Socket_connect_async(), Socket_connect_with_addrinfo() for async
Socket_timeouts_set() for connect timeout control
docs/ASYNC_IO.md non-blocking connect patterns
docs/SECURITY.md secure connect practices (TLS, verify host)
Referenced by main().
Socket_connect_async()
Request_T Socket_connect_async (SocketDNS_T dns, Socket_T socket, const char * host, int port) extern
Start async DNS resolution for connect.
Parameters
dns DNS resolver instance.
socket Socket to connect.
host Remote IP address or hostname.
port Remote port (1 to SOCKET_MAX_PORT).
Returns
DNS request handle.
Exceptions
Socket_Failed on error.
See also
Socket_connect_async_cancel() for canceling the request.
Socket_connect_with_addrinfo() for connecting with resolved address.
Socket_connect_async_cancel()
void Socket_connect_async_cancel (SocketDNS_T dns, Request_T req) extern
Cancel pending async connect resolution.
Parameters
dns DNS resolver instance.
req Request handle returned by Socket_connect_async.
See also
Socket_connect_async() for starting async connect.
Socket_connect_nonblocking()
int Socket_connect_nonblocking (Socket_T socket, const char * ip_address, int port) extern
Initiate non-blocking connect (no DNS, IP address only).
Starts a non-blocking TCP connect operation. Unlike Socket_connect(), this function:
Only accepts IP addresses (no DNS resolution)
Returns immediately without blocking
Requires polling for completion via SocketPoll or select/poll
After calling, poll the socket for writability. When writable, check SO_ERROR via getsockopt() or call Socket_isconnected().
Parameters
[in,out] socket Socket (will be set to non-blocking mode)
[in] ip_address Remote IP address (IPv4 or IPv6, no hostnames)
[in] port Remote port (1-65535)
Returns
0 if connect completed immediately, 1 if in progress (poll for completion)
Exceptions
Socket_Failed on invalid IP or immediate connect failure
Thread Safety\n Yes - operates on single socket
Example
Socket_T sock = Socket_new(AF_INET, SOCK_STREAM, 0);
int status = Socket_connect_nonblocking(sock, "192.168.1.1", 8080);
if (status == 1) {
    // In progress - add to poll
    SocketPoll_add(poll, sock, POLL_WRITE, NULL);
    // When writable, check Socket_isconnected()
}
Note
For hostname resolution, use Socket_connect_async() with SocketDNS_T
Socket is left in non-blocking mode after this call
See also
Socket_isconnected() to check connection status
Socket_connect_async() for async DNS + connect
SocketHappyEyeballs for RFC 8305 connection racing
Socket_connect_tcp()
Socket_T Socket_connect_tcp (const char * host, int port, int timeout_ms) extern
Create a connected TCP client socket in one call.
Convenience function that combines Socket_new(), Socket_connect() with timeout support. Creates a connected TCP client socket ready for I/O.
Parameters
[in] host Remote address (IP or hostname)
[in] port Remote port (1-65535)
[in] timeout_ms Connection timeout in milliseconds (0 = no timeout)
Returns
New connected socket ready for Socket_send()/Socket_recv()
Exceptions
Socket_Failed on socket creation, DNS resolution, or connect failure
Thread Safety\n Yes - creates new socket instance
Example
Socket_T client = Socket_connect_tcp("api.example.com", 443, 5000);
Socket_sendall(client, request, len);
ssize_t n = Socket_recv(client, response, sizeof(response));
Socket_free(&client);
Note
DNS resolution uses synchronous getaddrinfo() which may block
For non-blocking connect, use Socket_setnonblocking() + Socket_connect()
See also
Socket_connect_unix_timeout() for Unix domain sockets
Socket_connect() for more control over socket options
Socket_connect_unix()
void Socket_connect_unix (Socket_T socket, const char * path) extern
Connect to Unix domain socket path.
Parameters
socket Socket to connect (AF_UNIX).
path Socket file path.
Exceptions
Socket_Failed on error.
Note
Supports abstract namespace sockets on Linux (path starting with '@').
See also
Socket_bind_unix() for binding Unix sockets.
Socket_connect_unix_timeout()
void Socket_connect_unix_timeout (Socket_T socket, const char * path, int timeout_ms) extern
Connect to Unix domain socket with timeout.
Connects an existing Unix domain socket to a server path with timeout support. The socket must already be created with AF_UNIX domain.
Parameters
[in,out] socket Unix domain socket (AF_UNIX)
[in] path Server socket path
[in] timeout_ms Connection timeout in milliseconds (0 = no timeout)
Exceptions
SocketUnix_Failed on connect failure or timeout
Thread Safety\n Yes - operates on single socket
Example
Socket_T sock = Socket_new(AF_UNIX, SOCK_STREAM, 0);
Socket_connect_unix_timeout(sock, "/var/run/myapp.sock", 5000);
Socket_sendall(sock, message, len);
Socket_free(&sock);
Note
For one-call client creation, first create socket then call this
See also
Socket_connect_unix() for connect without timeout
Socket_listen_unix() for creating Unix domain server
Socket_connect_with_addrinfo()
void Socket_connect_with_addrinfo (Socket_T socket, struct addrinfo * res) extern
Connect socket using resolved address.
Parameters
socket Socket to connect.
res Resolved addrinfo result from DNS resolution.
Exceptions
Socket_Failed on error.
See also
Socket_connect_async() for async DNS resolution.
Socket_connect() for direct connection.
Socket_cork()
int Socket_cork (Socket_T socket, int enable) extern
Control TCP_CORK option (Nagle corking).
When corking is enabled, TCP accumulates small writes into larger segments before sending. Useful for building complete messages before transmission (e.g., HTTP headers + body).
Parameters
[in] socket TCP socket
[in] enable 1 to enable corking, 0 to disable (flush)
Returns
0 on success, -1 if not supported
Thread Safety\n Yes
Platform Support
Platform Support
Linux Full (TCP_CORK)
FreeBSD/macOS Partial (TCP_NOPUSH)
Other Returns -1
Example
// Cork while building response
Socket_cork(sock, 1);
Socket_send(sock, headers, header_len);
Socket_send(sock, body, body_len);
Socket_cork(sock, 0);  // Flush all data
Note
Corking is automatically released when socket buffer is full
Different from TCP_NODELAY which disables Nagle algorithm entirely
See also
Socket_setnodelay() for disabling Nagle algorithm
Socket_debug_live_count()
int Socket_debug_live_count (void) extern
Get number of live socket instances (test-only).
Returns
Current count of allocated Socket_T instances.
Note
For testing and leak detection.
Socket_dup()
Socket_T Socket_dup (Socket_T socket) extern
Duplicate a socket (creates new Socket_T sharing same fd).
Creates a new Socket_T instance with a duplicated file descriptor (via dup()). Both sockets share the same underlying connection but have independent Socket_T state (buffers, settings, etc.).
Parameters
[in] socket Socket to duplicate
Returns
New Socket_T with duplicated fd, or NULL on error
Exceptions
Socket_Failed on dup() or allocation failure
Thread Safety\n Yes
Use Cases
Separate reader/writer for same connection
Passing socket to child process (fork safety)
Multiple references to same connection
Example
Socket_T reader = socket;
Socket_T writer = Socket_dup(socket);
// Now can use in separate threads
// reader thread: Socket_recv(reader, ...)
// writer thread: Socket_send(writer, ...)
Socket_free(&writer);  // Closes duplicated fd
Socket_free(&reader);  // Closes original fd
Note
Both sockets must be freed separately
Closing one does not affect the other's fd
Socket options are shared (both see setsockopt changes)
See also
Socket_dup2() for duplicating to specific fd
Socket_dup2()
Socket_T Socket_dup2 (Socket_T socket, int target_fd) extern
Duplicate socket fd to a specific file descriptor number.
Creates a new Socket_T instance with the file descriptor duplicated to a specific number (via dup2()). If target_fd is already open, it is closed first.
Parameters
[in] socket Socket to duplicate
[in] target_fd Target file descriptor number
Returns
New Socket_T with fd = target_fd, or NULL on error
Exceptions
Socket_Failed on dup2() or allocation failure
Thread Safety\n Yes
Example
// Duplicate socket to specific fd for exec()
Socket_T sock_on_fd3 = Socket_dup2(socket, 3);
if (fork() == 0) {
    // Child: fd 3 is the socket
    execl("/usr/bin/handler", "handler", NULL);
}
Socket_free(&sock_on_fd3);
Note
target_fd is closed if already open (like dup2 behavior)
Original socket is unchanged
See also
Socket_dup() for simple duplication
Socket_error_is_retryable()
int Socket_error_is_retryable (int err) extern
Check if an errno indicates a retryable error.
Parameters
err errno value to check.
Returns
1 if retryable, 0 if not.
Thread Safety\n Yes
See also
Socket_geterrno() for getting current errno.
Socket_Failed exception for when this is used.
This is a convenience wrapper around SocketError_is_retryable_errno() for socket-specific error handling.
Retryable errors (return 1):
ECONNREFUSED: Server not listening, may start later
ECONNRESET: Connection dropped, can reconnect
ETIMEDOUT: Timeout, may succeed on retry
ENETUNREACH: Network route may recover
EHOSTUNREACH: Host may become reachable
EAGAIN/EWOULDBLOCK: Resource temporarily unavailable
EINTR: Interrupted by signal
Fatal errors (return 0):
EACCES: Permission denied (won't change)
EADDRINUSE: Address in use (won't change)
EBADF: Bad file descriptor (programming error)
EINVAL: Invalid argument (programming error)
ENOMEM: Out of memory (system issue)
EMFILE/ENFILE: Too many open files (system limit)
Usage: TRY Socket_connect(sock, host, port); EXCEPT(Socket_Failed) if (Socket_error_is_retryable(Socket_geterrno())) // Schedule retry with backoff else // Log error and give up END_TRY;
Socket_fd()
int Socket_fd (const Socket_T socket) extern
Get underlying file descriptor.
Parameters
socket Socket instance.
Returns
File descriptor.
See also
Socket_new_from_fd() for creating sockets from file descriptors.
Referenced by main().
Socket_free()
void Socket_free (Socket_T * socket) extern
Dispose of a socket instance and close the underlying file descriptor.
Closes the socket's file descriptor using close(2) and frees all associated resources including internal state, buffers, and timers. The pointer *socket is set to NULL after successful cleanup to prevent use-after-free.
This function is idempotent: calling on NULL does nothing. It handles partial cleanup if socket is in inconsistent state (e.g., after exception).
IMPORTANT: Always pass pointer to socket (&sock) so it can be nulled. Failing to do so may lead to use-after-free bugs.
For testing, use Socket_debug_live_count() to ensure all sockets freed.
Edge cases:
Already freed socket (NULL): no-op
Socket in connect/bind state: aborts operations gracefully
TLS-enabled socket: performs TLS shutdown if connected
Parameters
[in,out] socket Pointer to Socket_T (set to NULL on success)
Exceptions
None - errors during close are logged but not raised (Socket_Failed would be swallowed)
Thread Safety\n Yes - per-socket cleanup, no shared state modification
Basic Usage
Socket_T sock = Socket_new(AF_INET, SOCK_STREAM, 0);
// ... use sock ...
Socket_free(&sock);  // Pass address to nullify
In TRY/EXCEPT Block
Socket_T sock = NULL;
TRY {
    sock = Socket_new(AF_INET, SOCK_STREAM, 0);
    // Operations that may fail
} EXCEPT(Socket_Failed) {
    // Error handling
} FINALLY {
    Socket_free(&sock);  // Safe even if sock NULL
} END_TRY;
Note
Always use &sock in Socket_free(&sock) to enable nulling.
For pooled sockets, use SocketPool_remove() before free.
Warning
Do not access socket after free - undefined behavior.
In multithreaded code, ensure no other thread uses socket during free.
Complexity\n O(1) - close(2) call plus resource cleanup
See also
Socket_new() for creation
Socket_debug_live_count() for leak detection in tests
SocketPool_T for connection pooling alternatives
Referenced by main(), and main().
Socket_get_cwnd()
int32_t Socket_get_cwnd (Socket_T socket) extern
Get current congestion window size.
Retrieves the TCP congestion window (cwnd) which limits how much unacknowledged data can be in flight. Useful for network diagnostics.
Parameters
[in] socket Connected TCP socket
Returns
Congestion window in segments, or -1 if unavailable
Thread Safety\n Yes
Example
int32_t cwnd = Socket_get_cwnd(sock);
if (cwnd >= 0) {
    printf("Congestion window: %d segments\n", cwnd);
}
Note
Linux-specific; returns -1 on other platforms
cwnd is dynamically adjusted by congestion control algorithm
See also
Socket_get_tcp_info() for comprehensive TCP statistics (Linux)
Socket_get_error()
int Socket_get_error (Socket_T socket) extern
Get pending socket error (SO_ERROR).
Retrieves and clears the pending socket error via getsockopt(SO_ERROR). Useful after non-blocking connect() or to check for async errors.
Parameters
[in] socket Socket to check
Returns
0 if no error, otherwise errno value (ECONNREFUSED, ETIMEDOUT, etc.)
Thread Safety\n Yes - atomic getsockopt call
Common Error Values
Error Meaning
0 No error
ECONNREFUSED Connection refused by peer
ECONNRESET Connection reset by peer
ETIMEDOUT Connection timed out
ENETUNREACH Network unreachable
EHOSTUNREACH Host unreachable
Example
// After non-blocking connect, poll for writability, then:
int error = Socket_get_error(sock);
if (error != 0) {
    fprintf(stderr, "Connect failed: %s\n", strerror(error));
} else {
    printf("Connected successfully\n");
}
Note
SO_ERROR is cleared after retrieval (per POSIX)
See also
Socket_probe() for comprehensive health check
Socket_connect_nonblocking() for async connect usage
Socket_get_rtt()
int32_t Socket_get_rtt (Socket_T socket) extern
Get current RTT (round-trip time) estimate.
Retrieves the TCP stack's smoothed RTT estimate for the connection. On Linux, uses TCP_INFO; on other platforms, may return -1.
Parameters
[in] socket Connected TCP socket
Returns
RTT in microseconds, or -1 if unavailable
Thread Safety\n Yes
Example
int32_t rtt = Socket_get_rtt(sock);
if (rtt >= 0) {
    printf("RTT: %.2f ms\n", rtt / 1000.0);
} else {
    printf("RTT unavailable on this platform\n");
}
Note
TCP stack updates RTT based on ACK timing; may not reflect current
For UDP, always returns -1
See also
Socket_get_tcp_info() for comprehensive TCP statistics (Linux)
Socket_getstats() for SocketStats_T with rtt_us field
socket_get_ssl()
SSL * socket_get_ssl (Socket_T socket) extern
Get SSL object from socket.
Parameters
socket Socket instance
Returns
SSL object or NULL if TLS not enabled
Thread Safety\n Yes - read-only access to socket state.
See also
socket_is_tls_enabled() to check TLS status before calling.
socket_validate_tls_ready() to ensure TLS readiness for I/O.
socket_handle_ssl_error() for handling errors with the SSL object.
Security Module for TLS integration.
Socket_get_tcp_info()
int Socket_get_tcp_info (Socket_T socket, SocketTCPInfo * info) extern
Retrieve TCP connection statistics (Linux-specific).
Retrieves detailed TCP stack information via getsockopt(TCP_INFO). Provides RTT measurements, congestion window, MSS, retransmission counts, and other TCP internals useful for diagnostics and monitoring.
Parameters
[in] socket Connected TCP socket
[out] info Output structure for TCP information
Returns
0 on success, -1 on error (errno set)
Thread Safety\n Yes - atomic getsockopt call
Example
SocketTCPInfo info;
if (Socket_get_tcp_info(sock, &info) == 0) {
    printf("RTT: %.2f ms (variance: %.2f ms)\n",
           info.rtt_us / 1000.0, info.rttvar_us / 1000.0);
    printf("Congestion window: %u segments\n", info.snd_cwnd);
    printf("Retransmissions: %u\n", info.total_retrans);
    if (info.delivery_rate > 0) {
        printf("Delivery rate: %.2f Mbps\n",
               info.delivery_rate * 8.0 / 1e6);
    }
}
Note
Linux-specific; not available on other platforms
Some fields require newer kernel versions (noted in structure)
See also
Socket_get_rtt() for simple RTT query
Socket_get_cwnd() for congestion window query
SocketTCPInfo for field descriptions
Socket_getbandwidth()
size_t Socket_getbandwidth (Socket_T socket) extern
Get bandwidth limit for socket.
Parameters
socket Socket to query.
Returns
Bandwidth limit in bytes per second (0 if unlimited).
Thread Safety\n Yes.
See also
Socket_setbandwidth() for setting bandwidth limit.
Socket_getcongestion()
int Socket_getcongestion (Socket_T socket, char * algorithm, size_t len) extern
Get TCP congestion control algorithm.
Parameters
socket Socket to query.
algorithm Output buffer for algorithm name.
len Buffer length.
Returns
0 on success, -1 on error or if not supported.
See also
Socket_setcongestion() for setting algorithm.
Socket_getdeferaccept()
int Socket_getdeferaccept (Socket_T socket) extern
Get TCP_DEFER_ACCEPT timeout.
Parameters
socket Listening socket.
Returns
Current defer accept timeout in seconds, 0 if disabled.
Exceptions
Socket_Failed on error.
Thread Safety\n Yes.
See also
Socket_setdeferaccept() for setting defer accept.
Socket_getfastopen()
int Socket_getfastopen (Socket_T socket) extern
Get TCP Fast Open setting.
Parameters
socket Socket to query.
Returns
1 if enabled, 0 if disabled, -1 on error.
See also
Socket_setfastopen() for enabling Fast Open.
Socket_getkeepalive()
void Socket_getkeepalive (Socket_T socket, int * idle, int * interval, int * count) extern
Get TCP keepalive configuration.
Parameters
socket Socket to query.
idle Output - idle timeout in seconds.
interval Output - interval between probes in seconds.
count Output - number of probes before declaring dead.
Exceptions
Socket_Failed on error.
See also
Socket_setkeepalive() for setting keepalive parameters.
Socket_getlocaladdr()
const char * Socket_getlocaladdr (const Socket_T socket) extern
Get local IP address.
Parameters
socket Socket instance.
Returns
IP address string (IPv4/IPv6) or "(unknown)" if unavailable.
Note
String is owned by socket, valid until socket freed.
See also
Socket_getlocalport() for local port.
Socket_bind() for binding to addresses.
Referenced by main().
Socket_getlocalport()
int Socket_getlocalport (const Socket_T socket) extern
Get local port number.
Parameters
socket Socket instance.
Returns
Port number (1 to SOCKET_MAX_PORT) or 0 if unavailable.
See also
Socket_getlocaladdr() for local address.
Socket_bind() for binding to ports.
Referenced by main().
Socket_getnodelay()
int Socket_getnodelay (Socket_T socket) extern
Get TCP_NODELAY setting.
Parameters
socket Socket to query.
Returns
1 if Nagle's algorithm is disabled, 0 if enabled.
Exceptions
Socket_Failed on error.
See also
Socket_setnodelay() for setting Nagle algorithm.
Socket_getpeeraddr()
const char * Socket_getpeeraddr (const Socket_T socket) extern
Get peer IP address.
Parameters
socket Connected socket.
Returns
IP address string (IPv4/IPv6) or "(unknown)" if unavailable.
Note
String is owned by socket, valid until socket freed.
See also
Socket_getpeerport() for peer port.
Socket_connect() for establishing connections.
Referenced by handle_client_data(), main(), main(), and simulate_work_wrapper().
Socket_getpeergid()
int Socket_getpeergid (const Socket_T socket) extern
Get peer group ID (Linux only).
Parameters
socket Connected Unix domain socket.
Returns
Peer group ID, or (gid_t)-1 if unavailable.
See also
Socket_getpeerpid() for peer process ID.
Socket_getpeeruid() for peer user ID.
Socket_getpeerpid()
int Socket_getpeerpid (const Socket_T socket) extern
Get peer process ID (Linux only).
Parameters
socket Connected Unix domain socket.
Returns
Peer process ID, or -1 if unavailable.
See also
Socket_getpeeruid() for peer user ID.
Socket_getpeergid() for peer group ID.
Socket_getpeerport()
int Socket_getpeerport (const Socket_T socket) extern
Get peer port number.
Parameters
socket Connected socket.
Returns
Port number (1 to SOCKET_MAX_PORT) or 0 if unavailable.
See also
Socket_getpeeraddr() for peer address.
Socket_connect() for establishing connections.
Referenced by handle_client_data(), main(), main(), and simulate_work_wrapper().
Socket_getpeeruid()
int Socket_getpeeruid (const Socket_T socket) extern
Get peer user ID (Linux only).
Parameters
socket Connected Unix domain socket.
Returns
Peer user ID, or (uid_t)-1 if unavailable.
See also
Socket_getpeerpid() for peer process ID.
Socket_getpeergid() for peer group ID.
Socket_getrcvbuf()
int Socket_getrcvbuf (Socket_T socket) extern
Get receive buffer size.
Parameters
socket Socket to query.
Returns
Receive buffer size in bytes.
Exceptions
Socket_Failed on error.
See also
Socket_setrcvbuf() for setting receive buffer size.
Socket_getsndbuf()
int Socket_getsndbuf (Socket_T socket) extern
Get send buffer size.
Parameters
socket Socket to query.
Returns
Send buffer size in bytes.
Exceptions
Socket_Failed on error.
See also
Socket_setsndbuf() for setting send buffer size.
Socket_getstats()
void Socket_getstats (const Socket_T socket, SocketStats_T * stats) extern
Retrieve current statistics for a socket.
Copies the current per-socket statistics to the provided structure. Statistics include cumulative bytes/packets transferred, error counts, and timing information.
Parameters
[in] socket Socket to query
[out] stats Output structure for statistics (must not be NULL)
Exceptions
Socket_Failed if socket is invalid
Thread Safety\n Yes - atomic snapshot of statistics
Example
SocketStats_T stats;
Socket_getstats(sock, &stats);
printf("Transfer: %zu bytes sent, %zu bytes received\n",
       (size_t)stats.bytes_sent, (size_t)stats.bytes_received);
printf("Packets: %zu sent, %zu received\n",
       (size_t)stats.packets_sent, (size_t)stats.packets_received);
if (stats.rtt_us >= 0) {
    printf("RTT: %.2f ms\n", stats.rtt_us / 1000.0);
}
Note
RTT fields only populated on Linux via TCP_INFO; -1 on other platforms
See also
Socket_resetstats() to reset counters
SocketStats_T for field descriptions
Referenced by main().
Socket_gettimeout()
int Socket_gettimeout (Socket_T socket) extern
Get socket timeout.
Parameters
socket Socket to query.
Returns
Timeout in seconds (0 if disabled).
Exceptions
Socket_Failed on error.
See also
Socket_settimeout() for setting timeout.
Socket_getusertimeout()
unsigned int Socket_getusertimeout (Socket_T socket) extern
Get TCP user timeout.
Parameters
socket Socket to query.
Returns
Timeout in milliseconds, or 0 on error.
See also
Socket_setusertimeout() for setting user timeout.
socket_handle_ssl_error()
int socket_handle_ssl_error (Socket_T socket, SSL * ssl, int ssl_result) extern
Helper to handle SSL error codes.
Parameters
socket Socket instance
ssl SSL object
ssl_result Result from SSL operation
Returns
0 on success, -1 on error (sets errno)
Thread Safety\n Yes - operates on single socket.
Note
Maps SSL error codes to errno values and updates socket state.
Used by TLS-aware I/O functions for consistent error handling.
See also
socket_send_internal() and socket_recv_internal() for usage examples.
SSL_get_error() OpenSSL documentation for error mapping details.
SocketTLS_Failed for raised exceptions.
Socket_ignore_sigpipe()
int Socket_ignore_sigpipe (void) extern
Globally ignore SIGPIPE signal.
Returns
0 on success, -1 on error (sets errno).
Thread Safety\n Yes - can be called from any thread, idempotent operation.
NOTE: This function is NOT required when using this library. The library handles SIGPIPE internally via:
MSG_NOSIGNAL flag on send operations (Linux/FreeBSD)
SO_NOSIGPIPE socket option at creation (BSD/macOS)
This convenience function is provided for:
Legacy code migration (applications that previously handled SIGPIPE)
Applications mixing this library with raw socket code
Defense-in-depth preference
Usage: // Optional - call once at program startup if desired Socket_ignore_sigpipe();
IMPORTANT: Do not call this if your application needs to handle SIGPIPE for other purposes (e.g., detecting broken pipes in shell pipelines).
See also
Socket_send() for SIGPIPE-safe sending operations.
Socket_is_readable()
int Socket_is_readable (Socket_T socket) extern
Check if socket has data available to read without blocking.
Performs a quick check to see if recv() would return data immediately. Uses poll() with zero timeout to check POLLIN status.
Parameters
[in] socket Socket to check
Returns
1 if data available, 0 if would block, -1 on error
Thread Safety\n Yes - atomic poll call
Example
// Check before blocking recv
if (Socket_is_readable(sock) > 0) {
    ssize_t n = Socket_recv(sock, buf, sizeof(buf));
    // Process data
}
// In select/poll alternative
while (Socket_is_readable(sock) > 0) {
    process_incoming_data(sock);
}
Note
Also returns 1 if peer has closed connection (recv will return 0)
For more efficient I/O multiplexing, use SocketPoll
See also
Socket_is_writable() for write readiness check
SocketPoll for efficient event-driven I/O
socket_is_tls_enabled()
int socket_is_tls_enabled (const Socket_T socket) extern
Check if socket has TLS enabled.
Parameters
socket Socket to check.
Returns
1 if TLS is enabled on the socket, 0 otherwise.
Thread Safety\n Yes - atomic read of socket state.
See also
SocketTLS_enable() to enable TLS on a socket.
socket_tls_want_read() and socket_tls_want_write() for checking TLS handshake needs.
group__security for TLS module documentation.
Socket_is_writable()
int Socket_is_writable (Socket_T socket) extern
Check if socket can accept writes without blocking.
Performs a quick check to see if send() would succeed immediately. Uses poll() with zero timeout to check POLLOUT status.
Parameters
[in] socket Socket to check
Returns
1 if write ready, 0 if would block, -1 on error
Thread Safety\n Yes - atomic poll call
Example
// Check before potentially blocking send
if (Socket_is_writable(sock) > 0) {
    ssize_t n = Socket_send(sock, buf, len);
} else {
    // Buffer full, queue for later
    queue_pending_write(buf, len);
}
Note
Returns 1 if send buffer has space; doesn't guarantee all data fits
For non-blocking connect, writable means connect completed (check error)
See also
Socket_is_readable() for read readiness check
Socket_get_error() to check after non-blocking connect
Socket_isbound()
int Socket_isbound (Socket_T socket) extern
Check if socket is bound to an address.
Parameters
socket Socket to check.
Returns
1 if bound, 0 if not bound.
Thread Safety\n Yes.
See also
Socket_bind() for binding sockets.
Socket_isconnected() for checking connection state.
Socket_isconnected()
int Socket_isconnected (Socket_T socket) extern
Check if socket is connected.
Parameters
socket Socket to check.
Returns
1 if connected, 0 if not connected.
Thread Safety\n Yes.
See also
Socket_connect() for establishing connections.
Socket_isbound() for checking binding state.
Socket_islistening()
int Socket_islistening (Socket_T socket) extern
Check if socket is listening for connections.
Parameters
socket Socket to check.
Returns
1 if listening, 0 if not listening.
Thread Safety\n Yes.
See also
Socket_listen() for setting up listening sockets.
Socket_accept() for accepting connections.
Socket_listen()
void Socket_listen (Socket_T socket, int backlog) extern
Listen for incoming connections.
Parameters
socket Bound socket.
backlog Maximum pending connections.
Exceptions
Socket_Failed on error.
See also
Socket_bind() for binding sockets.
Socket_accept() for accepting connections.
Referenced by main(), and main().
Socket_listen_tcp()
Socket_T Socket_listen_tcp (const char * host, int port, int backlog) extern
Create a listening TCP server socket in one call.
Convenience function that combines Socket_new(), Socket_setreuseaddr(), Socket_bind(), and Socket_listen() into a single call. Creates a ready-to-accept TCP server socket.
Parameters
[in] host Local address to bind (NULL or "" for INADDR_ANY/all interfaces)
[in] port Local port to bind (1-65535)
[in] backlog Maximum pending connections (use SOMAXCONN for system max)
Returns
New listening socket ready for Socket_accept()
Exceptions
Socket_Failed on socket creation, bind, or listen failure
Thread Safety\n Yes - creates new socket instance
Example
Socket_T server = Socket_listen_tcp("0.0.0.0", 8080, 128);
while (running) {
    Socket_T client = Socket_accept(server);
    if (client) handle_client(client);
}
Socket_free(&server);
Note
Socket is created with SO_REUSEADDR enabled
For IPv6, use "::" as host for dual-stack binding
See also
Socket_accept() for accepting connections
Socket_listen_unix() for Unix domain sockets
Socket_listen_unix()
Socket_T Socket_listen_unix (const char * path, int backlog) extern
Create a listening Unix domain socket in one call.
Convenience function that combines Socket_new(AF_UNIX), Socket_bind_unix(), and Socket_listen() into a single call. Creates a ready-to-accept Unix domain socket server.
Parameters
[in] path Socket file path (max ~108 bytes, or '@' prefix for abstract)
[in] backlog Maximum pending connections
Returns
New listening Unix domain socket ready for Socket_accept()
Exceptions
SocketUnix_Failed on creation, bind, or listen failure
Thread Safety\n Yes - creates new socket instance
Example
Socket_T server = Socket_listen_unix("/var/run/myapp.sock", 128);
while (running) {
    Socket_T client = Socket_accept(server);
    if (client) handle_client(client);
}
Socket_free(&server);
unlink("/var/run/myapp.sock");  // Clean up socket file
Note
Existing socket file at path will cause EADDRINUSE - remove first
Abstract sockets (Linux): prefix path with '@' (no file created)
See also
Socket_listen_tcp() for TCP sockets
Socket_bind_unix() for more control
Socket_new()
Socket_T Socket_new (int domain, int type, int protocol) extern
Create a new socket with specified domain, type, and protocol.
Creates and initializes a new socket instance using the socket(2) system call. The socket is created in blocking mode by default. SIGPIPE is automatically handled internally via platform-specific mechanisms (MSG_NOSIGNAL on Linux, SO_NOSIGPIPE on BSD/macOS). The library sets reasonable default socket options including close-on-exec and non-SIGPIPE behavior.
Supported domains: AF_INET (IPv4), AF_INET6 (IPv6), AF_UNIX (Unix domain). Supported types: SOCK_STREAM (TCP), SOCK_DGRAM (UDP), SOCK_SEQPACKET (SCTP). Protocol is usually 0 to select default for the domain/type combination.
Edge cases:
Invalid domain/type/protocol combinations raise Socket_Failed immediately.
Resource limits (EMFILE, ENFILE) raise Socket_Failed.
Permission issues (EACCES) raise Socket_Failed.
For UDP, use SocketDgram_new() instead for datagram-specific features.
Parameters
[in] domain Address family (AF_INET, AF_INET6, AF_UNIX)
[in] type Socket type (SOCK_STREAM for TCP, SOCK_DGRAM for UDP)
[in] protocol Protocol number (0 for default)
Returns
New Socket_T instance on success, raises exception on failure.
Exceptions
Socket_Failed System call failed (EACCES permission denied, EMFILE/ENFILE too many files, ENOMEM out of memory, EINVAL invalid arguments)
Thread Safety\n Yes - creates independent instance safe from concurrent calls
Basic Usage
// Create TCP IPv4 socket
Socket_T sock = Socket_new(AF_INET, SOCK_STREAM, 0);
Socket_connect(sock, "example.com", 80);
// ... use socket ...
Socket_free(&sock);
With Error Handling and Options
TRY {
    Socket_T sock = Socket_new(AF_INET6, SOCK_STREAM, 0);
    Socket_setreuseaddr(sock);  // Allow address reuse
    Socket_setnonblocking(sock);  // Non-blocking mode
    Socket_bind(sock, "::", 8080);
    Socket_listen(sock, 128);
    // Server loop...
} EXCEPT(Socket_Failed) {
    fprintf(stderr, "Socket creation failed: %s\n", Socket_GetLastError());
    // Handle error (e.g., retry or exit)
} FINALLY {
    Socket_free(&sock);
} END_TRY;
Note
Socket is blocking by default; use Socket_setnonblocking() for async I/O.
For Unix domain sockets, use AF_UNIX domain.
Warning
Ensure proper cleanup with Socket_free() to avoid fd leaks.
SOCK_DGRAM with this function creates basic UDP socket; use SocketDgram_new() for full UDP features like multicast.
Complexity\n O(1) - single socket(2) system call plus option setup
See also
Socket_free() for resource cleanup
Socket_connect() for client connections
Socket_bind() and Socket_listen() for servers
SocketDgram_new() for UDP/datagram sockets
Socket_new_from_fd() for wrapping existing fds
docs/ASYNC_IO.md for non-blocking patterns
Referenced by main(), and main().
Socket_new_from_fd()
Socket_T Socket_new_from_fd (int fd) extern
Create Socket_T from existing file descriptor.
Parameters
fd File descriptor (must be valid socket, will be set to non-blocking).
Returns
New Socket_T instance or NULL on failure.
Exceptions
Socket_Failed on error.
Thread Safety\n Yes - returns new instance without modifying shared state.
See also
Socket_new() for creating new sockets.
Socket_fd() for getting file descriptors from Socket_T instances.
Socket_peek()
ssize_t Socket_peek (Socket_T socket, void * buf, size_t len) extern
Peek at incoming data without consuming it.
Reads data from the socket receive buffer without removing it. Subsequent recv() calls will return the same data.
Parameters
[in] socket Connected socket
[out] buf Buffer for peeked data
[in] len Maximum bytes to peek
Returns
Bytes peeked (> 0), 0 if no data available, or raises
Exceptions
Socket_Closed on peer close
Socket_Failed on other errors
Thread Safety\n Yes - for same socket with proper synchronization
Example
// Peek at protocol header to determine message type
char header[4];
if (Socket_peek(sock, header, sizeof(header)) >= 4) {
    int msg_type = header[0];
    int msg_len = (header[1] << 16) | (header[2] << 8) | header[3];
    // Now read full message
    Socket_recvall(sock, buffer, msg_len);
}
Note
Useful for protocol detection and message framing
Non-blocking sockets return 0 if no data available
See also
Socket_recv() for consuming data
Socket_is_readable() for checking data availability
Socket_probe()
int Socket_probe (Socket_T socket, int timeout_ms) extern
Probe if a connection is still alive.
Performs a non-destructive check to determine if the connection is still valid. Uses a combination of:
SO_ERROR check for pending socket errors
Zero-byte MSG_PEEK recv to detect closed connections
Optional write probe (if enabled)
Parameters
[in] socket Connected socket to probe
[in] timeout_ms Maximum time to wait for response (-1 for non-blocking)
Returns
1 if connection appears healthy, 0 if connection is dead/error
Thread Safety\n Yes - read-only probe
Return Values
Return Meaning
1 Connection healthy (no errors detected)
0 Connection dead, reset, or error pending
Example
// Quick health check before expensive operation
if (!Socket_probe(sock, 0)) {
    printf("Connection lost, reconnecting...\n");
    reconnect(sock);
}
// With timeout for more thorough check
if (!Socket_probe(sock, 100)) {  // 100ms probe
    handle_disconnect();
}
Note
This is a best-effort check; TCP half-open states may not be detected
For TCP, a true liveness check requires application-level heartbeats
See also
Socket_get_error() for retrieving specific error codes
Socket_isconnected() for basic connection state check
Socket_recv()
ssize_t Socket_recv (Socket_T socket, void * buf, size_t len) extern
Receive data.
Parameters
socket Connected socket.
buf Buffer for received data.
len Buffer size (> 0).
Returns
Bytes received (> 0) or 0 if would block (EAGAIN/EWOULDBLOCK).
Exceptions
Socket_Closed on peer close or ECONNRESET, Socket_Failed on other errors.
See also
Socket_recvall() for guaranteed complete reception.
Socket_send() for sending data.
Referenced by handle_client_data(), and main().
socket_recv_internal()
ssize_t socket_recv_internal (Socket_T socket, void * buf, size_t len, int flags) extern
Internal receive operation (TLS-aware)
Parameters
socket Socket instance
buf Buffer for received data
len Buffer size
flags Receive flags
Returns
Number of bytes received, or 0 if would block (EAGAIN/EWOULDBLOCK) or EOF (connection closed).
Exceptions
Socket_Failed on underlying socket errors such as invalid file descriptor or network issues.
SocketTLS_Failed on TLS decryption or read failures (#if SOCKET_HAS_TLS).
Socket_Closed on connection closure detected by recv returning 0 or ECONNRESET.
Thread Safety\n Yes - operates on single socket.
Note
Routes through SSL_read() if TLS is enabled, otherwise uses recv().
Maps SSL errors to errno (EAGAIN for WANT_READ/WRITE).
See also
Socket_recv() for the public synchronous receive interface.
socket_send_internal() for the corresponding send operation.
socket_recvv_internal() for scatter-gather receive support.
SocketTLS_Failed exception for TLS-specific errors.
Socket_Closed on EOF detection.
Socket_recv_limited()
ssize_t Socket_recv_limited (Socket_T socket, void * buf, size_t len) extern
Receive data with bandwidth limiting.
Parameters
socket Connected socket.
buf Buffer for received data.
len Buffer size (> 0).
Returns
Bytes received (> 0), 0 if rate limited or would block, or raises.
Exceptions
Socket_Closed on peer close, Socket_Failed on other errors.
Thread Safety\n Yes - uses per-socket bandwidth limiter with internal locking.
Like Socket_recv() but respects bandwidth limit set by Socket_setbandwidth(). If bandwidth limiting is disabled (0), behaves like Socket_recv().
See also
Socket_send_limited() for bandwidth-limited sending.
Socket_recvall()
ssize_t Socket_recvall (Socket_T socket, void * buf, size_t len) extern
Receive all requested data (handles partial receives).
Parameters
socket Connected socket.
buf Buffer for received data.
len Buffer size (> 0).
Returns
Total bytes received (always equals len on success).
Exceptions
Socket_Closed on peer close or ECONNRESET, Socket_Failed on other errors.
See also
Socket_recv() for partial receive operations.
Socket_sendall() for sending all data.
Socket_recvall_timeout()
ssize_t Socket_recvall_timeout (Socket_T socket, void * buf, size_t len, int timeout_ms) extern
Receive all requested data with timeout.
Like Socket_recvall() but with a timeout. Ensures all requested data is received or times out. Partial receives are possible on timeout.
Parameters
[in] socket Connected socket
[out] buf Buffer for received data
[in] len Number of bytes to receive
[in] timeout_ms Timeout in milliseconds (0 = no timeout, -1 = block)
Returns
Total bytes received on success (may be < len on timeout)
Exceptions
Socket_Closed on peer close or ECONNRESET
Socket_Failed on other errors
Thread Safety\n Yes - for same socket with proper synchronization
Example
char buf[1024];
ssize_t n = Socket_recvall_timeout(sock, buf, sizeof(buf), 5000);
if (n < (ssize_t)sizeof(buf)) {
    printf("Only received %zd bytes (timeout or EOF)\n", n);
}
See also
Socket_recvall() for blocking receive
Socket_recv() for single receive operation
Socket_recvfd()
int Socket_recvfd (Socket_T socket, int * fd_received) extern
Receive a file descriptor over Unix domain socket.
Parameters
socket Connected Unix domain socket (AF_UNIX).
fd_received Output pointer for received file descriptor.
Returns
1 on success, 0 if would block (EAGAIN/EWOULDBLOCK).
Exceptions
Socket_Failed on error, Socket_Closed on disconnect.
Receives a file descriptor from the peer process via SCM_RIGHTS. The received fd is owned by this process and must be closed when done.
OWNERSHIP: Caller takes ownership of the received fd and MUST close it.
Thread Safety\n Yes - uses thread-local error buffers for safe concurrent
operation.
See also
Socket_sendfd() for sending file descriptors.
Socket_recvfds() for receiving multiple descriptors.
Socket_recvfds()
int Socket_recvfds (Socket_T socket, int * fds, size_t max_count, size_t * received_count) extern
Receive multiple file descriptors.
Parameters
socket Connected Unix domain socket (AF_UNIX).
fds Output array for received descriptors (must have max_count capacity).
max_count Maximum descriptors to receive.
received_count Output for actual count received.
Returns
1 on success, 0 if would block (EAGAIN/EWOULDBLOCK).
Exceptions
Socket_Failed on error, Socket_Closed on disconnect.
Receives multiple file descriptors from a single message. On success, *received_count contains the number of fds received.
OWNERSHIP: Caller takes ownership of all received fds and MUST close them.
Thread Safety\n Yes - uses thread-local error buffers for safe concurrent
operation.
See also
Socket_sendfds() for sending multiple descriptors.
Socket_recvfd() for receiving single descriptor.
Socket_recvmsg()
ssize_t Socket_recvmsg (Socket_T socket, struct msghdr * msg, int flags) extern
Receive message with ancillary data (recvmsg wrapper).
Parameters
socket Connected socket.
msg Message structure for data, address, and ancillary data.
flags Message flags (MSG_DONTWAIT, MSG_PEEK, etc.).
Returns
Total bytes received (> 0) or 0 if would block.
Exceptions
Socket_Closed on peer close or ECONNRESET, Socket_Failed on other errors.
See also
Socket_sendmsg() for sending messages with ancillary data.
Socket_recvfd() for receiving file descriptors.
Socket_recvv()
ssize_t Socket_recvv (Socket_T socket, struct iovec * iov, int iovcnt) extern
Scatter/gather receive (readv wrapper).
Parameters
socket Connected socket.
iov Array of iovec structures.
iovcnt Number of iovec structures (> 0, <= IOV_MAX).
Returns
Total bytes received (> 0) or 0 if would block.
Exceptions
Socket_Closed on peer close or ECONNRESET, Socket_Failed on other errors.
See also
Socket_recvvall() for guaranteed complete scatter/gather receive.
Socket_sendv() for scatter/gather send.
socket_recvv_internal()
ssize_t socket_recvv_internal (Socket_T socket, struct iovec * iov, int iovcnt, int flags) extern
Internal scatter/gather receive (TLS-aware)
Parameters
socket Socket instance
iov Array of iovec structures
iovcnt Number of iovec structures
flags Receive flags
Returns
Total number of bytes received into iov buffers, or 0 if would block or EOF.
Exceptions
Socket_Failed on underlying socket or vectored I/O errors.
SocketTLS_Failed on TLS read failures (#if SOCKET_HAS_TLS).
Socket_Closed on connection closure detected by readv returning 0 or ECONNRESET.
Thread Safety\n Yes - operates on single socket.
Note
For TLS: Calls SSL_read() into first iov, advances manually.
For non-TLS: Uses readv() directly.
See also
Socket_recvv() for public vectored receive interface.
socket_recv_internal() for simple buffer receive.
Socket_Closed on connection EOF.
SocketTLS_Failed for TLS errors.
Socket_recvv_timeout()
ssize_t Socket_recvv_timeout (Socket_T socket, struct iovec * iov, int iovcnt, int timeout_ms) extern
Scatter/gather receive with timeout.
Like Socket_recvv() but with a timeout. May perform partial receives.
Parameters
[in] socket Connected socket
[in,out] iov Array of iovec structures
[in] iovcnt Number of iovec structures
[in] timeout_ms Timeout in milliseconds (0 = no timeout, -1 = block)
Returns
Total bytes received (> 0), 0 if would block/timeout, or raises
Exceptions
Socket_Closed on peer close or ECONNRESET
Socket_Failed on other errors
Thread Safety\n Yes - for same socket with proper synchronization
See also
Socket_recvvall() for guaranteed complete receive (no timeout)
Socket_sendv_timeout() for scatter/gather send with timeout
Socket_recvvall()
ssize_t Socket_recvvall (Socket_T socket, struct iovec * iov, int iovcnt) extern
Scatter/gather receive all (handles partial receives).
Parameters
socket Connected socket.
iov Array of iovec structures.
iovcnt Number of iovec structures (> 0, <= IOV_MAX).
Returns
Total bytes received (always equals sum of all iov_len on success).
Exceptions
Socket_Closed on peer close or ECONNRESET, Socket_Failed on other errors.
See also
Socket_recvv() for partial scatter/gather receive.
Socket_sendvall() for sending all scatter/gather data.
Socket_resetstats()
void Socket_resetstats (Socket_T socket) extern
Reset statistics counters for a socket.
Resets all per-socket statistics counters to zero except for create_time_ms which preserves the original creation timestamp. Useful for interval-based monitoring where you want to track stats per time period.
Parameters
[in] socket Socket to reset
Exceptions
Socket_Failed if socket is invalid
Thread Safety\n Yes - atomic reset
Example
// Log stats every minute
while (running) {
    sleep(60);
    SocketStats_T stats;
    Socket_getstats(sock, &stats);
    log_stats(&stats);
    Socket_resetstats(sock);  // Reset for next interval
}
See also
Socket_getstats() to retrieve statistics
SocketStats_T for field descriptions
Socket_send()
ssize_t Socket_send (Socket_T socket, const void * buf, size_t len) extern
Send data.
Parameters
socket Connected socket.
buf Data to send.
len Length of data (> 0).
Returns
Bytes sent (> 0) or 0 if would block (EAGAIN/EWOULDBLOCK).
Exceptions
Socket_Closed on EPIPE/ECONNRESET, Socket_Failed on other errors.
See also
Socket_sendall() for guaranteed complete transmission.
Socket_recv() for receiving data.
socket_send_internal()
ssize_t socket_send_internal (Socket_T socket, const void * buf, size_t len, int flags) extern
Internal send operation (TLS-aware)
Parameters
socket Socket instance
buf Data to send
len Length of data
flags Send flags (MSG_NOSIGNAL, etc.)
Returns
Number of bytes sent, or 0 if operation would block (EAGAIN/EWOULDBLOCK).
Exceptions
Socket_Failed on underlying socket errors such as invalid file descriptor or network issues.
SocketTLS_Failed on TLS encryption or write failures (#if SOCKET_HAS_TLS).
Thread Safety\n Yes - operates on single socket.
Note
Routes through SSL_write() if TLS is enabled, otherwise uses send().
Handles partial sends and EAGAIN mapping.
See also
Socket_send() for the public synchronous send interface.
socket_recv_internal() for the corresponding receive operation.
socket_sendv_internal() for scatter-gather send support.
SocketTLS_Failed exception for TLS-specific errors.
Socket_send_limited()
ssize_t Socket_send_limited (Socket_T socket, const void * buf, size_t len) extern
Send data with bandwidth limiting.
Parameters
socket Connected socket.
buf Data to send.
len Length of data (> 0).
Returns
Bytes sent (> 0), 0 if rate limited (try again later), or raises.
Exceptions
Socket_Closed on EPIPE/ECONNRESET, Socket_Failed on other errors.
Thread Safety\n Yes - uses per-socket bandwidth limiter with internal locking.
Like Socket_send() but respects bandwidth limit set by Socket_setbandwidth(). If bandwidth limiting is disabled (0), behaves like Socket_send(). If rate limited, returns 0 and caller should wait before retrying. Use Socket_bandwidth_wait_ms() to get recommended wait time.
See also
Socket_recv_limited() for bandwidth-limited receiving.
Socket_bandwidth_wait_ms() for wait time calculation.
Socket_sendall()
ssize_t Socket_sendall (Socket_T socket, const void * buf, size_t len) extern
Send all data (handles partial sends).
Parameters
socket Connected socket.
buf Data to send.
len Length of data (> 0).
Returns
Total bytes sent (always equals len on success).
Exceptions
Socket_Closed on EPIPE/ECONNRESET, Socket_Failed on other errors.
See also
Socket_send() for partial send operations.
Socket_recvall() for receiving all data.
Referenced by handle_client_data(), and main().
Socket_sendall_timeout()
ssize_t Socket_sendall_timeout (Socket_T socket, const void * buf, size_t len, int timeout_ms) extern
Send all data with timeout.
Like Socket_sendall() but with a timeout. Ensures all data is sent or times out. Partial sends are possible on timeout.
Parameters
[in] socket Connected socket
[in] buf Data to send
[in] len Length of data (> 0)
[in] timeout_ms Timeout in milliseconds (0 = no timeout, -1 = block)
Returns
Total bytes sent on success (may be < len on timeout)
Exceptions
Socket_Closed on EPIPE/ECONNRESET
Socket_Failed on other errors
Thread Safety\n Yes - for same socket with proper synchronization
Return Values
Return Meaning
len All data sent successfully
0 < n < len Partial send (timeout expired)
-1 Error (exception raised)
Example
// Send with 5 second timeout
ssize_t sent = Socket_sendall_timeout(sock, data, len, 5000);
if (sent < (ssize_t)len) {
    printf("Only sent %zd of %zu bytes (timeout)\n", sent, len);
}
See also
Socket_sendall() for blocking send
Socket_send() for single send operation
Socket_sendfd()
int Socket_sendfd (Socket_T socket, int fd_to_pass) extern
Send a file descriptor over Unix domain socket.
Parameters
socket Connected Unix domain socket (AF_UNIX).
fd_to_pass File descriptor to pass (must be >= 0).
Returns
1 on success, 0 if would block (EAGAIN/EWOULDBLOCK).
Exceptions
Socket_Failed on error, Socket_Closed on disconnect.
Passes a single file descriptor to the peer process using SCM_RIGHTS. The receiving process gets a new fd referring to the same kernel object.
PLATFORM REQUIREMENTS:
POSIX-compliant Unix domain socket (AF_UNIX)
NOT available on Windows
SECURITY NOTES:
Only works with connected Unix domain sockets
Receiving process should validate the fd type before use
Thread Safety\n Yes - uses thread-local error buffers for safe concurrent
operation.
See also
Socket_recvfd() for receiving file descriptors.
Socket_sendfds() for sending multiple descriptors.
Socket_sendfds()
int Socket_sendfds (Socket_T socket, const int * fds, size_t count) extern
Send multiple file descriptors.
Parameters
socket Connected Unix domain socket (AF_UNIX).
fds Array of file descriptors to pass (all must be >= 0).
count Number of descriptors (1 to SOCKET_MAX_FDS_PER_MSG).
Returns
1 on success, 0 if would block (EAGAIN/EWOULDBLOCK).
Exceptions
Socket_Failed on error, Socket_Closed on disconnect.
Passes multiple file descriptors atomically in a single message. All descriptors are either sent together or none are sent.
Thread Safety\n Yes - uses thread-local error buffers for safe concurrent
operation.
See also
Socket_recvfds() for receiving multiple descriptors.
Socket_sendfd() for sending single descriptor.
Socket_sendfile()
ssize_t Socket_sendfile (Socket_T socket, int file_fd, off_t * offset, size_t count) extern
Zero-copy file-to-socket transfer.
Parameters
socket Connected socket to send to.
file_fd File descriptor to read from (must be a regular file).
offset File offset to start reading from (NULL for current position).
count Number of bytes to transfer (0 for entire file from offset).
Returns
Total bytes transferred (> 0) or 0 if would block.
Exceptions
Socket_Closed on EPIPE/ECONNRESET, Socket_Failed on other errors.
See also
Socket_sendfileall() for guaranteed complete transfer.
Socket_send() for buffer-based sending.
Socket_sendfileall()
ssize_t Socket_sendfileall (Socket_T socket, int file_fd, off_t * offset, size_t count) extern
Zero-copy file-to-socket transfer (handles partial transfers).
Parameters
socket Connected socket to send to.
file_fd File descriptor to read from (must be a regular file).
offset File offset to start reading from (NULL for current position).
count Number of bytes to transfer (0 for entire file from offset).
Returns
Total bytes transferred (always equals count on success).
Exceptions
Socket_Closed on EPIPE/ECONNRESET, Socket_Failed on other errors.
See also
Socket_sendfile() for partial transfer operations.
Socket_sendall() for buffer-based guaranteed sending.
Socket_sendmsg()
ssize_t Socket_sendmsg (Socket_T socket, const struct msghdr * msg, int flags) extern
Send message with ancillary data (sendmsg wrapper).
Parameters
socket Connected socket.
msg Message structure with data, address, and ancillary data.
flags Message flags (MSG_NOSIGNAL, MSG_DONTWAIT, etc.).
Returns
Total bytes sent (> 0) or 0 if would block.
Exceptions
Socket_Closed on EPIPE/ECONNRESET, Socket_Failed on other errors.
See also
Socket_recvmsg() for receiving messages with ancillary data.
Socket_sendfd() for sending file descriptors.
Socket_sendv()
ssize_t Socket_sendv (Socket_T socket, const struct iovec * iov, int iovcnt) extern
Scatter/gather send (writev wrapper).
Parameters
socket Connected socket.
iov Array of iovec structures.
iovcnt Number of iovec structures (> 0, <= IOV_MAX).
Returns
Total bytes sent (> 0) or 0 if would block.
Exceptions
Socket_Closed on EPIPE/ECONNRESET, Socket_Failed on other errors.
See also
Socket_sendvall() for guaranteed complete scatter/gather send.
Socket_recvv() for scatter/gather receive.
socket_sendv_internal()
ssize_t socket_sendv_internal (Socket_T socket, const struct iovec * iov, int iovcnt, int flags) extern
Internal scatter/gather send (TLS-aware)
Parameters
socket Socket instance
iov Array of iovec structures
iovcnt Number of iovec structures
flags Send flags
Returns
Total number of bytes sent from iov buffers, or 0 if would block.
Exceptions
Socket_Failed on underlying socket or vectored I/O errors.
SocketTLS_Failed on TLS write failures or buffer allocation issues (#if SOCKET_HAS_TLS).
Thread Safety\n Yes - operates on single socket.
Note
For TLS: Copies iov to temp buffer, calls SSL_write().
For non-TLS: Uses writev() directly.
Allocates temp buffer via socket->arena if needed.
See also
Socket_sendv() for public vectored send interface.
socket_send_internal() for simple buffer send.
Arena_T for memory allocation details.
SocketTLS_Failed for TLS errors.
Socket_sendv_timeout()
ssize_t Socket_sendv_timeout (Socket_T socket, const struct iovec * iov, int iovcnt, int timeout_ms) extern
Scatter/gather send with timeout.
Like Socket_sendv() but with a timeout. May perform partial sends.
Parameters
[in] socket Connected socket
[in] iov Array of iovec structures
[in] iovcnt Number of iovec structures
[in] timeout_ms Timeout in milliseconds (0 = no timeout, -1 = block)
Returns
Total bytes sent (> 0), 0 if would block/timeout, or raises
Exceptions
Socket_Closed on EPIPE/ECONNRESET
Socket_Failed on other errors
Thread Safety\n Yes - for same socket with proper synchronization
See also
Socket_sendvall() for guaranteed complete send (no timeout)
Socket_recvv_timeout() for scatter/gather receive with timeout
Socket_sendvall()
ssize_t Socket_sendvall (Socket_T socket, const struct iovec * iov, int iovcnt) extern
Scatter/gather send all (handles partial sends).
Parameters
socket Connected socket.
iov Array of iovec structures.
iovcnt Number of iovec structures (> 0, <= IOV_MAX).
Returns
Total bytes sent (always equals sum of all iov_len on success).
Exceptions
Socket_Closed on EPIPE/ECONNRESET, Socket_Failed on other errors.
See also
Socket_sendv() for partial scatter/gather send.
Socket_recvvall() for receiving all scatter/gather data.
Socket_setbandwidth()
void Socket_setbandwidth (Socket_T socket, size_t bytes_per_sec) extern
Set bandwidth limit for socket.
Parameters
socket Socket to modify.
bytes_per_sec Maximum bytes per second (0 to disable limiting).
Exceptions
Socket_Failed on allocation failure.
Thread Safety\n Yes - uses internal mutex for synchronization.
Enables bandwidth throttling using a token bucket algorithm. The burst capacity is set to bytes_per_sec (1 second of data). Use Socket_send_limited() for rate-limited sending.
See also
Socket_getbandwidth() for retrieving current limit.
Socket_send_limited() for rate-limited operations.
Socket_setcloexec()
void Socket_setcloexec (Socket_T socket, int enable) extern
Control close-on-exec flag.
Parameters
socket Socket to modify.
enable 1 to enable CLOEXEC, 0 to disable.
Exceptions
Socket_Failed on error.
Note
By default, sockets have CLOEXEC enabled.
Socket_setcongestion()
void Socket_setcongestion (Socket_T socket, const char * algorithm) extern
Set TCP congestion control algorithm.
Parameters
socket Socket to modify.
algorithm Algorithm name (e.g., "cubic", "reno", "bbr").
Exceptions
Socket_Failed on error or if not supported.
Note
Only available on Linux 2.6.13+.
See also
Socket_getcongestion() for retrieving current algorithm.
Socket_setdeferaccept()
void Socket_setdeferaccept (Socket_T socket, int timeout_sec) extern
Enable TCP_DEFER_ACCEPT.
Parameters
socket Listening socket.
timeout_sec Seconds to wait for data before completing accept (0 to disable, max platform-specific).
Delays accept() completion until client sends data, preventing
SYN-only connections from consuming application resources. This is a key defense against SYN flood attacks.
Linux: Uses TCP_DEFER_ACCEPT socket option BSD/macOS: Uses SO_ACCEPTFILTER with "dataready" filter
Exceptions
Socket_Failed on error or if unsupported.
Thread Safety\n Yes.
See also
Socket_getdeferaccept() for retrieving current setting.
Socket_accept() for accepting connections.
Socket_setfastopen()
void Socket_setfastopen (Socket_T socket, int enable) extern
Enable TCP Fast Open.
Parameters
socket Socket to modify.
enable 1 to enable, 0 to disable.
Exceptions
Socket_Failed on error or if not supported.
See also
Socket_getfastopen() for retrieving Fast Open setting.
Socket_setkeepalive()
void Socket_setkeepalive (Socket_T socket, int idle, int interval, int count) extern
Enable TCP keepalive.
Parameters
socket Socket to modify.
idle Seconds before sending keepalive probes.
interval Interval between keepalive probes.
count Number of probes before declaring dead.
Exceptions
Socket_Failed on error.
See also
Socket_getkeepalive() for retrieving keepalive settings.
Socket_setnodelay()
void Socket_setnodelay (Socket_T socket, int nodelay) extern
Disable Nagle's algorithm.
Parameters
socket Socket to modify.
nodelay 1 to disable Nagle, 0 to enable.
Exceptions
Socket_Failed on error.
See also
Socket_getnodelay() for retrieving Nagle setting.
Socket_setnonblocking()
void Socket_setnonblocking (Socket_T socket) extern
Enable non-blocking mode.
Parameters
socket Socket to modify.
Exceptions
Socket_Failed on error.
See also
Socket_accept() for non-blocking accept behavior.
Socket_send() for non-blocking send behavior.
Referenced by main(), and main().
Socket_setrcvbuf()
void Socket_setrcvbuf (Socket_T socket, int size) extern
Set receive buffer size.
Parameters
socket Socket to modify.
size Buffer size in bytes (> 0).
Exceptions
Socket_Failed on error.
See also
Socket_getrcvbuf() for retrieving receive buffer size.
Socket_setreuseaddr()
void Socket_setreuseaddr (Socket_T socket) extern
Enable address reuse.
Parameters
socket Socket to modify.
Exceptions
Socket_Failed on error.
See also
Socket_bind() for binding operations.
Socket_setreuseport() for port reuse.
Referenced by main(), and main().
Socket_setreuseport()
void Socket_setreuseport (Socket_T socket) extern
Enable port reuse across sockets.
Parameters
socket Socket to modify.
Exceptions
Socket_Failed on error (or if SO_REUSEPORT unsupported).
See also
Socket_setreuseaddr() for address reuse.
Socket_bind() for binding operations.
Socket_setsndbuf()
void Socket_setsndbuf (Socket_T socket, int size) extern
Set send buffer size.
Parameters
socket Socket to modify.
size Buffer size in bytes (> 0).
Exceptions
Socket_Failed on error.
See also
Socket_getsndbuf() for retrieving send buffer size.
Socket_settimeout()
void Socket_settimeout (Socket_T socket, int timeout_sec) extern
Set socket timeout.
Parameters
socket Socket to modify.
timeout_sec Timeout in seconds (0 to disable).
Exceptions
Socket_Failed on error.
Note
Sets both send and receive timeouts.
See also
Socket_gettimeout() for retrieving current timeout.
Socket_setusertimeout()
void Socket_setusertimeout (Socket_T socket, unsigned int timeout_ms) extern
Set TCP user timeout.
Parameters
socket Socket to modify.
timeout_ms Timeout in milliseconds (> 0).
Exceptions
Socket_Failed on error or if not supported.
Note
Only available on Linux 2.6.37+.
See also
Socket_getusertimeout() for retrieving user timeout.
Socket_shutdown()
void Socket_shutdown (Socket_T socket, int how) extern
Disable further sends and/or receives.
Parameters
socket Connected socket.
how Shutdown mode (SHUT_RD, SHUT_WR, or SHUT_RDWR).
Exceptions
Socket_Failed on error.
See also
Socket_close() for full connection teardown.
Referenced by main().
Socket_splice()
ssize_t Socket_splice (Socket_T socket_in, Socket_T socket_out, size_t len) extern
Zero-copy socket-to-socket transfer (Linux splice).
Transfers data between two sockets using the kernel's splice() system call, avoiding copies between kernel and user space. Significantly more efficient for proxying and data forwarding.
Parameters
[in] socket_in Source socket to read from
[in] socket_out Destination socket to write to
[in] len Maximum bytes to transfer (0 for default chunk size)
Returns
Bytes transferred (> 0), 0 if would block, -1 if not supported
Exceptions
Socket_Closed on connection closed
Socket_Failed on other errors
Thread Safety\n Yes - for distinct socket pairs
Platform Support
Platform Support
Linux 2.6.17+ Full (via splice())
Other Returns -1 (use Socket_recv/Socket_send fallback)
Example
// Proxy data from client to upstream
while ((n = Socket_splice(client, upstream, 0)) > 0) {
    total += n;
}
if (n == 0) {
    // Would block - use poll
} else if (n < 0) {
    // Not supported - fallback to recv/send
    char buf[4096];
    while ((n = Socket_recv(client, buf, sizeof(buf))) > 0) {
        Socket_sendall(upstream, buf, n);
    }
}
Note
Requires both sockets to be in compatible state
For file-to-socket, use Socket_sendfile() instead
See also
Socket_sendfile() for file-to-socket zero-copy
Socket_timeouts_get()
void Socket_timeouts_get (const Socket_T socket, SocketTimeouts_T * timeouts) extern
Retrieve per-socket timeout configuration.
Parameters
socket Socket instance.
timeouts Output timeout structure.
See also
Socket_timeouts_set() for setting timeouts.
Socket_timeouts_getdefaults() for global defaults.
Socket_timeouts_get_extended()
void Socket_timeouts_get_extended (const Socket_T socket, SocketTimeouts_Extended_T * extended) extern
Retrieve per-socket extended timeout configuration.
Parameters
socket Socket to query.
extended Output structure for extended timeouts.
Retrieves the current extended timeout configuration. If extended timeouts haven't been set, returns the basic timeouts mapped to the extended structure.
Thread Safety\n No - caller must ensure exclusive access to socket.
See also
Socket_timeouts_set_extended() for setting extended timeouts.
Socket_timeouts_getdefaults()
void Socket_timeouts_getdefaults (SocketTimeouts_T * timeouts) extern
Get global default timeouts.
Parameters
timeouts Output timeout structure containing current defaults.
See also
Socket_timeouts_setdefaults() for changing defaults.
Socket_timeouts_get() for per-socket timeouts.
Socket_timeouts_set()
void Socket_timeouts_set (Socket_T socket, const SocketTimeouts_T * timeouts) extern
Set per-socket timeout configuration.
Parameters
socket Socket instance.
timeouts Timeout configuration (NULL to reset to defaults).
See also
Socket_timeouts_get() for retrieving timeouts.
Socket_timeouts_setdefaults() for changing global defaults.
Socket_timeouts_set_extended()
void Socket_timeouts_set_extended (Socket_T socket, const SocketTimeouts_Extended_T * extended) extern
Set per-socket extended timeout configuration.
Parameters
socket Socket to modify.
extended Extended per-phase timeout configuration.
Sets granular per-phase timeouts for advanced use cases. The extended timeouts provide finer control than SocketTimeouts_T, allowing different timeouts for DNS, connect, TLS, and request phases.
Values of 0 in the extended structure mean "inherit from basic timeouts". Values of -1 mean "no timeout (infinite)".
Thread Safety\n No - caller must ensure exclusive access to socket.
See also
Socket_timeouts_get_extended() for retrieving extended timeouts.
SocketTimeouts_Extended_T for timeout structure details.
Socket_timeouts_setdefaults()
void Socket_timeouts_setdefaults (const SocketTimeouts_T * timeouts) extern
Set global default timeouts.
Parameters
timeouts New default timeout configuration.
See also
Socket_timeouts_getdefaults() for retrieving defaults.
Socket_timeouts_set() for per-socket overrides.
socket_tls_want_read()
int socket_tls_want_read (const Socket_T socket) extern
Check if TLS wants to read more data for handshake or protocol.
Parameters
socket TLS-enabled socket to query.
Returns
1 if TLS needs more input data, 0 otherwise.
Note
Used in event loops to determine if POLL_READ should be enabled for TLS sockets.
Thread Safety\n Yes - read-only access to TLS state.
See also
SocketTLS_handshake() for performing TLS handshake.
socket_tls_want_write() for write readiness.
SocketPoll_T for event system integration.
group__security for TLS details.
socket_tls_want_write()
int socket_tls_want_write (const Socket_T socket) extern
Check if TLS wants to write more data for handshake or protocol.
Parameters
socket TLS-enabled socket to query.
Returns
1 if TLS needs to output data, 0 otherwise.
Note
Used in event loops to determine if POLL_WRITE should be enabled for TLS sockets.
Thread Safety\n Yes - read-only access to TLS state.
See also
SocketTLS_handshake() for performing TLS handshake.
socket_tls_want_read() for read readiness.
SocketPoll_T for event system integration.
group__security for TLS details.
socket_validate_tls_ready()
SSL * socket_validate_tls_ready (Socket_T socket) extern
Validate TLS is ready for I/O.
Parameters
socket Socket instance
Returns
SSL* pointer if TLS is fully ready for I/O operations.
Exceptions
Socket_Failed if socket is invalid or TLS not enabled.
SocketTLS_HandshakeFailed if TLS handshake is not complete or failed (#if SOCKET_HAS_TLS).
Thread Safety\n Yes - operates on single socket.
Note
Shared helper for TLS I/O functions.
See also
socket_send_internal() and similar for TLS readiness check.
SocketTLS_handshake() if manual handshake needed.
SocketTLS_Failed or Socket_Failed on error.
SocketBase_arena()
Arena_T SocketBase_arena (SocketBase_T base) extern
Get the memory arena associated with the socket base.
Returns the per-socket Arena_T used for all allocations related to this socket instance, ensuring consistent lifecycle management and avoiding leaks.
Parameters
[in] base Socket base instance
Returns
Arena_T used for this socket's allocations
Exceptions
None
Thread Safety\n Conditional - safe if no concurrent arena modification
(typically read-only)
Complexity\n O(1) - direct field return
Usage Example
Arena_T arena = SocketBase_arena(base);
char *endpoint = ALLOC(arena, strlen(host) + 1);
strcpy(endpoint, host);  // Arena-managed allocation
Note
All socket-related allocations (buffers, endpoint strings) should use this arena.
Arena lifetime tied to socket base; dispose via SocketCommon_free_base().
See also
core/Arena.h for arena API and ALLOC()/CALLOC() macros
Foundation Module Group for memory management details
SocketBase_T for arena role in resource management
SocketBase_domain()
int SocketBase_domain (SocketBase_T base) extern
Get the address domain (family) of the socket.
Returns the address family used when creating the socket, determining supported address types (IPv4, IPv6, Unix domain).
Parameters
[in] base Socket base instance
Returns
Domain constant (AF_INET, AF_INET6, AF_UNIX, etc.)
Exceptions
None
Thread Safety\n Yes - immutable after creation, no lock needed
Complexity\n O(1) - direct field access
Note
Set during socket creation; immutable throughout lifetime.
Used internally for address validation, option setting, resolution hints.
Usage Example
int domain = SocketBase_domain(base);
if (domain == AF_INET) {
    // IPv4-specific handling
} else if (domain == AF_INET6) {
    // IPv6-specific handling
}
See also
getaddrinfo(3) for address resolution using domain
AF_* constants in <sys/socket.h>
SocketCommon_resolve_address() in SocketCommon.h for domain-aware resolution
SocketBase_fd()
int SocketBase_fd (SocketBase_T base) extern
Retrieve the socket file descriptor from the base structure.
Provides access to the underlying file descriptor for low-level system calls like poll(2), epoll_ctl(2), or direct read/write operations.
Parameters
[in] base Socket base instance (non-NULL)
Returns
File descriptor (int fd, -1 if closed/invalid)
Exceptions
None
Thread Safety\n Conditional - safe if no concurrent modification to base (fd
typically read-only after init)
Complexity\n O(1) - direct field access
Usage
int fd = SocketBase_fd(base);
if (fd >= 0) {
    // Use fd for poll or epoll
    struct pollfd pfd = { .fd = fd, .events = POLLIN };
    poll(&pfd, 1, timeout);
}
Note
Direct fd access bypasses library wrappers; prefer high-level Socket_* functions.
Warning
fd is owned by base; do NOT close(2) directly - use Socket_free()
See also
socket(2), close(2)
SocketCommon.h for public API equivalents like Socket_fd()
SocketBase_remoteaddr()
static char * SocketBase_remoteaddr (SocketBase_T base) inline static
Get cached remote address string representation.
Returns the pre-cached string representation of the remote peer's address, formatted as numeric IP (IPv4/IPv6) or Unix domain path.
Parameters
[in] base Socket base instance
Returns
Pointer to arena-allocated string, or NULL if unset, unconnected, or invalid
Exceptions
None
Thread Safety\n Conditional - acquire base->mutex if concurrent modification to
endpoints possible
Complexity\n O(1) - direct pointer return
Usage Example
const char *remote_ip = SocketBase_remoteaddr(base);
if (remote_ip) {
    SOCKET_LOG_INFO_MSG("Connected to %s", remote_ip);
} else {
    SOCKET_LOG_WARN_MSG("No remote address available");
}
Note
String allocated in base.arena; valid until base disposal or recaching.
Cached via SocketCommon_cache_endpoint() after connect/accept.
Format: "192.168.1.1" (IPv4), "[::1]" (IPv6), "/tmp/socket" (Unix)
Warning
Do not free() the returned string - managed by arena.
See also
SocketBase_remoteport() for companion port getter
SocketCommon_cache_endpoint() for caching mechanism details
Socket_getpeeraddr() public wrapper in Socket.h
Definition at line 328 of file SocketCommon-private.h.
References SocketBase_T::remoteaddr.
SocketBase_remoteport()
static int SocketBase_remoteport (SocketBase_T base) inline static
Get remote peer port number.
Parameters
base Socket base instance.
Returns
Remote port (0 if unknown/unconnected).
Thread Safety\n Conditional - acquire base->mutex if concurrent access possible.
See also
SocketBase_remoteaddr()
Socket_getpeerport() public wrapper.
Definition at line 344 of file SocketCommon-private.h.
References SocketBase_T::remoteport.
SocketBase_set_timeouts()
void SocketBase_set_timeouts (SocketBase_T base, const SocketTimeouts_T * timeouts) extern
Set timeouts configuration in the socket base structure.
Copies timeout values from source to base.timeouts, applying to subsequent operations like connect(), send/recv, DNS resolution. NULL source uses global defaults. Safe no-op if base or source NULL.
Timeout Structure (SocketTimeouts_T)
Field Purpose Default
connect_ms Connection establishment 30000 ms
send_ms Send operations 0 (no timeout)
recv_ms Receive operations 0 (no timeout)
dns_ms DNS resolution Global default
Parameters
[in] base Socket base instance to update
[in] timeouts Source configuration to copy (NULL = global defaults)
Exceptions
None - defensive against NULL inputs
Thread Safety\n No - caller must lock base->mutex to prevent concurrent access
Complexity\n O(1) - structure copy
Usage Example
pthread_mutex_lock(&base->mutex);
SocketTimeouts_T custom = { .connect_ms = 5000, .send_ms = 10000 };
SocketBase_set_timeouts(base, &custom);
pthread_mutex_unlock(&base->mutex);
// Or use defaults
SocketBase_set_timeouts(base, NULL);
Note
Copies values; source ownership unchanged. Updates apply immediately to new operations.
Global defaults via SocketCommon_timeouts_getdefaults(); modifiable via SocketCommon_timeouts_setdefaults().
For socket-level SO_SNDTIMEO/SO_RCVTIMEO, use SocketCommon_settimeout().
Warning
Without mutex, race conditions may corrupt timeouts during concurrent sets.
See also
SocketBase_timeouts() for direct pointer access (lock required)
SocketCommon_timeouts_getdefaults() for copying global defaults
SocketCommon_timeouts_setdefaults() for setting globals
SocketCommon_settimeout() for low-level socket option timeouts
core/SocketConfig.h for SocketTimeouts_T definition
docs/TIMEOUTS.md for timeout best practices
SocketBuf_available()
size_t SocketBuf_available (const SocketBuf_T buf) extern
Query the number of bytes available for reading.
Parameters
buf The buffer to query.
Returns
Number of bytes currently stored in the buffer (0 if empty).
Note
Constant time query; no side effects.
Performance: O(1).
Thread Safety\n Yes - read-only query, safe concurrently.
See also
SocketBuf_space() for available write space.
SocketBuf_empty() for boolean emptiness check.
SocketBuf_read() or SocketBuf_peek() to access data.
SocketBuf_check_invariants()
bool SocketBuf_check_invariants (const SocketBuf_T buf) extern
Validate internal buffer consistency without assertions.
Parameters
buf The buffer to validate (const, read-only access).
Returns
true if all invariants hold (e.g., pointers valid, no overflow), false otherwise.
Note
Intended for debugging, fuzzing, or production integrity checks.
Does not modify buffer; suitable for periodic health checks.
Performance: O(1) typically, may scan in debug modes.
Thread Safety\n Yes - const inspection only.
See also
SocketBuf_reserve() which internally validates invariants.
Utilities for metrics and monitoring integration.
SocketBuf_clear()
void SocketBuf_clear (SocketBuf_T buf) extern
Reset buffer to empty state without zeroing memory.
Parameters
buf The buffer to clear.
Exceptions
SocketBuf_Failed if buffer is invalid.
Note
Only updates read/write pointers; memory contents may remain until overwritten.
Warning
Not suitable for sensitive data - use SocketBuf_secureclear() to prevent leakage.
Note
Performance: O(1) - no memory operations.
Thread Safety\n No - modifies buffer state.
See also
SocketBuf_secureclear() for zeroing sensitive data.
SocketBuf_consume() for partial discard.
SocketBuf_write() to repopulate after clear.
Security Modules for Security Modules best practices with buffers.
SocketBuf_compact()
void SocketBuf_compact (SocketBuf_T buf) extern
Move data to front of buffer, maximizing contiguous write space.
Parameters
buf The buffer to compact.
Moves all readable data to the beginning of the buffer (head=0). This maximizes contiguous write space for zero-copy operations. Useful before large writes or when writeptr() returns less than space().
Exceptions
SocketBuf_Failed if buffer is invalid.
Note
Performance: O(n) where n = bytes in buffer (memmove).
No-op if buffer is empty or already compacted.
Thread Safety\n No - modifies buffer internals.
Example
size_t space;
void *ptr = SocketBuf_writeptr(buf, &space);
if (space < needed) {
    SocketBuf_compact(buf);  // Make space contiguous
    ptr = SocketBuf_writeptr(buf, &space);
}
See also
SocketBuf_writeptr() for zero-copy writes.
SocketBuf_space() to check total available space.
SocketBuf_consume()
void SocketBuf_consume (SocketBuf_T buf, size_t len) extern
Discard data from the front of the buffer without reading it.
Parameters
buf The buffer to modify.
len Number of bytes to discard.
Exceptions
SocketBuf_Failed if buffer is invalid or len > available data.
Note
Behavior undefined (assert in debug) if len > SocketBuf_available(buf).
Efficient for skipping known-length headers or invalid data.
Performance: O(1) - only updates internal pointers.
Thread Safety\n No - modifies shared state; requires locking for concurrency.
See also
SocketBuf_available() to verify sufficient data before consuming.
SocketBuf_read() for read-and-discard operation.
SocketBuf_clear() for discarding all data.
SocketBuf_empty()
int SocketBuf_empty (const SocketBuf_T buf) extern
Check if the buffer contains no data.
Parameters
buf The buffer to check.
Returns
Non-zero (true) if empty, zero (false) otherwise.
Note
Equivalent to SocketBuf_available(buf) == 0.
Performance: O(1).
Thread Safety\n Yes - read-only query.
See also
SocketBuf_available() for exact count.
SocketBuf_full() for full buffer check.
SocketBuf_clear() to make buffer empty.
SocketBuf_ensure()
int SocketBuf_ensure (SocketBuf_T buf, size_t min_space) extern
Ensure minimum write space is available, resizing if necessary.
Parameters
buf The buffer to ensure space in.
min_space Minimum required write space in bytes.
Returns
1 if space is available, 0 on failure.
Combines compact and reserve operations. First attempts to compact (move data to front), then resizes if still insufficient.
Exceptions
SocketBuf_Failed if resize fails.
Note
Performance: O(n) for compact or resize, O(1) if already sufficient.
Thread Safety\n No - may modify buffer.
Example
if (SocketBuf_ensure(buf, 1024)) {
    // Guaranteed at least 1024 bytes of write space
    SocketBuf_write(buf, data, 1024);
}
See also
SocketBuf_reserve() for resize without compact.
SocketBuf_compact() for compact without resize.
SocketBuf_space() to check current space.
SocketBuf_find()
ssize_t SocketBuf_find (SocketBuf_T buf, const void * needle, size_t needle_len) extern
Search for a byte sequence in the buffer.
Parameters
buf The buffer to search.
needle Pointer to byte sequence to find.
needle_len Length of needle in bytes.
Returns
Offset from head where needle starts, or -1 if not found.
Searches the readable portion of the buffer for the needle sequence. Handles circular buffer wraparound transparently.
Exceptions
SocketBuf_Failed if buffer invalid or needle NULL with len > 0.
Note
Performance: O(n*m) worst case (n=buffer size, m=needle length).
Empty needle (len=0) returns 0.
Thread Safety\n Conditional - safe if buffer not mutated during search.
Example
// Find end of HTTP headers
ssize_t pos = SocketBuf_find(buf, "\r\n\r\n", 4);
if (pos >= 0) {
    size_t header_len = pos + 4;
    char headers[8192];
    SocketBuf_read(buf, headers, header_len);
}
See also
SocketBuf_readline() for line-oriented reading.
SocketBuf_peek() to examine data without searching.
SocketBuf_full()
int SocketBuf_full (const SocketBuf_T buf) extern
Check if the buffer has no space for writing.
Parameters
buf The buffer to check.
Returns
Non-zero (true) if full, zero (false) otherwise.
Note
Equivalent to SocketBuf_space(buf) == 0.
Performance: O(1).
Thread Safety\n Yes - read-only.
See also
SocketBuf_space() for exact free space.
SocketBuf_empty() for empty check.
SocketBuf_reserve() to expand capacity if full.
SocketBuf_new()
SocketBuf_T SocketBuf_new (Arena_T arena, size_t capacity) extern
Create a new circular buffer with specified initial capacity.
Allocates and initializes a circular buffer instance using the provided arena. The buffer starts empty with the given capacity. Capacity can grow dynamically via SocketBuf_reserve() if needed.
Parameters
[in] arena Arena for all buffer memory allocations (must not be NULL).
[in] capacity Initial buffer size in bytes (must be > 0; power-of-2 recommended for alignment).
Returns
Newly created buffer instance.
Exceptions
SocketBuf_Failed If arena allocation fails (ENOMEM), capacity <= 0, or arena NULL.
Thread Safety\n Yes - safe to call from any thread; returns independent
instance.
Complexity\n O(1) - single allocation via arena; O(capacity) for initial
zeroing if implemented.
Basic Usage
Arena_T arena = Arena_new();
SocketBuf_T buf = NULL;
TRY {
    buf = SocketBuf_new(arena, 4096);  // 4KB buffer
    // Use buf...
} EXCEPT(SocketBuf_Failed) {
    // Allocation failed - handle error
    fprintf(stderr, "Failed to create buffer: %s\n",
Except_message(Except_stack));
    // buf remains NULL
} FINALLY {
    if (buf) SocketBuf_release(&buf);
} END_TRY;
Arena_dispose(&arena);
In Connection Pools
Buffers are commonly created per-connection in SocketPool_T:
Connection_T conn = SocketPool_add(pool, socket);
SocketBuf_T inbuf = Connection_inbuf(conn);  // Pool-managed buffer
Note
Buffer lifecycle tied to arena - dispose arena to free all buffers at once.
Warning
Capacity=0 or very small may lead to frequent resizes; choose appropriately.
See also
SocketBuf_reserve() for dynamic growth.
SocketBuf_release() for handle invalidation (not memory free).
Arena_new() / Arena_dispose() in Core Foundation Modules for arena lifecycle.
SocketPool_T for integrated usage.
SocketBuf_peek()
size_t SocketBuf_peek (SocketBuf_T buf, void * data, size_t len) extern
Peek at data without removing it from the buffer.
Parameters
buf The source buffer.
data Destination for peeked data.
len Maximum bytes to peek.
Returns
Number of bytes copied to data (<= len); 0 if empty.
Exceptions
SocketBuf_Failed if buffer is invalid or data is NULL with len > 0.
Note
Non-destructive: data remains available for subsequent reads.
Useful for protocol parsing without consuming stream.
Performance: O(n) time where n = bytes peeked.
Thread Safety\n Conditional - safe if no concurrent modifications.
See also
SocketBuf_read() for consuming data after peeking.
SocketBuf_readptr() for zero-copy peeking.
SocketBuf_available() to query readable data length.
SocketBuf_read()
size_t SocketBuf_read (SocketBuf_T buf, void * data, size_t len) extern
Read and remove data from the buffer.
Parameters
buf The source buffer.
data Destination buffer for read data.
len Maximum bytes to read into data.
Returns
Number of bytes read and removed (<= len); 0 if empty.
Exceptions
SocketBuf_Failed if buffer is invalid or data is NULL with len > 0.
Note
Partial reads possible if less data available.
Data is removed from buffer after successful read.
Performance: O(n) time where n = bytes read.
Thread Safety\n No - concurrent reads/writes require external synchronization.
See also
SocketBuf_peek() for non-destructive read.
SocketBuf_readptr() for zero-copy read access.
SocketBuf_consume() to remove data without copying.
SocketBuf_available() to check readable bytes.
SocketBuf_empty() to check if no data available.
SocketBuf_readline()
ssize_t SocketBuf_readline (SocketBuf_T buf, char * line, size_t max_len) extern
Read a line (up to and including newline) from the buffer.
Parameters
buf The buffer to read from.
line Destination buffer for the line.
max_len Maximum bytes to read (including null terminator).
Returns
Number of bytes read (excluding null), or -1 if no newline found.
Reads up to and including the first newline ('
') or until max_len-1. The output is null-terminated. Handles both LF and CRLF line endings. Does NOT consume data if no complete line found (returns -1).
Exceptions
SocketBuf_Failed if buffer invalid or line NULL.
Note
Performance: O(n) where n = line length.
Returns -1 if no '
' found in available data.
Thread Safety\n No - reads and consumes data.
Example
char line[256];
ssize_t len;
while ((len = SocketBuf_readline(buf, line, sizeof(line))) > 0) {
    printf("Line: %s", line);  // line includes '\n'
}
See also
SocketBuf_find() for searching without reading.
SocketBuf_read() for length-based reading.
SocketBuf_readptr()
const void * SocketBuf_readptr (SocketBuf_T buf, size_t * len) extern
Obtain a direct pointer to readable data for zero-copy access.
Parameters
buf The buffer.
len Output parameter: number of contiguous bytes available at *return.
Returns
Pointer to start of readable data, or NULL if buffer empty. The pointed data is valid until next write/consume operation.
Note
Guarantees contiguous block; may be less than available() due to wraparound.
Caller must not retain pointer across mutating calls (write, consume, etc.).
Performance: O(1).
Thread Safety\n Conditional - pointer invalidates on concurrent mutation.
See also
SocketBuf_consume() to advance past the read data.
SocketBuf_read() for copying alternative.
SocketBuf_peek() for size-limited copy-based peek.
send() system call for zero-copy socket transmission.
SocketBuf_readv()
ssize_t SocketBuf_readv (SocketBuf_T buf, const struct iovec * iov, int iovcnt) extern
Scatter read from buffer into multiple iovecs.
Parameters
buf The buffer to read from.
iov Array of iovec structures to scatter data into.
iovcnt Number of iovec entries.
Returns
Total bytes read, or -1 on error.
Reads data from the buffer and scatters it across multiple memory regions. Consumes data from buffer after successful read. Handles wraparound.
Exceptions
SocketBuf_Failed if buffer invalid or iov NULL with iovcnt > 0.
Note
Performance: O(n) where n = total bytes read.
Partial fills possible if buffer has less data than iov capacity.
Thread Safety\n No - modifies buffer state.
Example
struct header hdr;
char body[1024];
struct iovec iov[2] = {
    {.iov_base = &hdr, .iov_len = sizeof(hdr)},
    {.iov_base = body, .iov_len = sizeof(body)}
};
ssize_t n = SocketBuf_readv(buf, iov, 2);
See also
SocketBuf_writev() for gather write.
SocketBuf_read() for single-buffer read.
readv(2) system call for analogous operation.
SocketBuf_release()
void SocketBuf_release (SocketBuf_T * buf) extern
Release the buffer handle and invalidate the pointer.
Parameters
buf Pointer to the buffer handle (set to NULL on success).
This function nullifies the buffer pointer but does not free the underlying memory, as it is managed by the arena. It prevents use-after-free or dangling pointer issues.
Note
Arena-managed memory persists until Arena_dispose() or Arena_clear().
No exception thrown; idempotent if *buf is already NULL.
Thread Safety\n Yes - safe to call concurrently if no overlapping access to
*buf.
See also
SocketBuf_new() for buffer creation.
Arena_dispose() in Core Foundation Modules for full memory cleanup.
Foundation group for memory management principles.
SocketBuf_reserve()
void SocketBuf_reserve (SocketBuf_T buf, size_t min_space) extern
Dynamically resize buffer to ensure at least min_space available.
Parameters
buf The buffer to potentially resize.
min_space Required minimum free space after operation.
Exceptions
SocketBuf_Failed if reallocation fails or arithmetic overflow occurs.
Note
Strategy: doubles capacity or sets to max(current, min_space); copies data.
May trigger on write if space insufficient (configurable?).
Validates internal invariants post-resize.
Thread Safety\n No - concurrent resize undefined; serialize access.
See also
SocketBuf_space() to check current space without resize.
SocketBuf_new() specify initial capacity to avoid frequent resizes.
Arena for underlying memory source.
SocketBuf_secureclear()
void SocketBuf_secureclear (SocketBuf_T buf) extern
Securely erase all data by zeroing memory contents.
Parameters
buf The buffer containing potentially sensitive data.
Exceptions
SocketBuf_Failed if buffer is invalid.
Note
Overwrites entire buffer capacity with zeros before resetting pointers.
Essential for cryptographic keys, credentials, or PII to mitigate timing attacks or memory dumps.
Warning
Performance: O(n) where n = current capacity; slower than clear().
Thread Safety\n No - writes to shared memory; lock before use in multi-thread.
See also
SocketBuf_clear() for non-secure fast reset.
Security Module for TLS/crypto integration.
SocketPool_T in Connection Management Modules for connection buffer secure cleanup.
SocketTLS_send() in Security Modules for secure I/O patterns.
SocketBuf_space()
size_t SocketBuf_space (const SocketBuf_T buf) extern
Query the number of bytes available for writing.
Parameters
buf The buffer to query.
Returns
Free space in bytes (capacity - available data; 0 if full).
Note
Constant time; no modification to buffer state.
Performance: O(1).
Thread Safety\n Yes - read-only, concurrent safe.
See also
SocketBuf_available() for symmetric read query.
SocketBuf_full() for boolean full check.
SocketBuf_write() to add data if space > 0.
SocketBuf_reserve() to ensure minimum space.
SocketBuf_write()
size_t SocketBuf_write (SocketBuf_T buf, const void * data, size_t len) extern
Write data into the buffer.
Parameters
buf The target buffer.
data Pointer to data to append.
len Number of bytes to write.
Returns
Number of bytes successfully written (<= len); 0 if full.
Exceptions
SocketBuf_Failed if buffer is invalid or data is NULL with len > 0.
Note
Writes as much as possible; partial writes possible if space limited.
Handles internal wraparound transparently.
Performance: O(n) time where n = bytes written, due to potential memcpy.
Thread Safety\n No - concurrent writes may corrupt buffer; use locks externally.
See also
SocketBuf_space() to check available write space before writing.
SocketBuf_writeptr() for zero-copy alternative.
SocketBuf_read() for symmetric read operation.
SocketBuf_full() to check if buffer is full.
SocketBuf_writeptr()
void * SocketBuf_writeptr (SocketBuf_T buf, size_t * len) extern
Obtain a direct pointer for zero-copy writing into the buffer.
Parameters
buf The buffer.
len Output: maximum contiguous bytes that can be written at *return.
Returns
Pointer to write location, or NULL if no space available.
Note
After writing up to *len bytes, call SocketBuf_written(actual_len).
May return less than space() due to wraparound; buffer handles it.
Pointer invalid after any other buffer operation.
Performance: O(1).
Thread Safety\n No - concurrent writes corrupt buffer.
See also
SocketBuf_written() to commit the written bytes.
SocketBuf_write() for safe copying alternative.
recv() system call integration for zero-copy receive.
SocketBuf_writev()
ssize_t SocketBuf_writev (SocketBuf_T buf, const struct iovec * iov, int iovcnt) extern
Gather write from multiple iovecs into buffer.
Parameters
buf The buffer to write to.
iov Array of iovec structures containing data to gather.
iovcnt Number of iovec entries.
Returns
Total bytes written, or -1 on error.
Gathers data from multiple memory regions and writes into the buffer. Handles circular buffer wraparound transparently.
Exceptions
SocketBuf_Failed if buffer invalid or iov NULL with iovcnt > 0.
Note
Performance: O(n) where n = total bytes written.
Partial writes possible if buffer space insufficient.
Thread Safety\n No - modifies buffer state.
Example
struct header hdr = {...};
char body[] = "Hello, World!";
struct iovec iov[2] = {
    {.iov_base = &hdr, .iov_len = sizeof(hdr)},
    {.iov_base = body, .iov_len = strlen(body)}
};
ssize_t n = SocketBuf_writev(buf, iov, 2);
See also
SocketBuf_readv() for scatter read.
SocketBuf_write() for single-buffer write.
writev(2) system call for analogous operation.
SocketBuf_written()
void SocketBuf_written (SocketBuf_T buf, size_t len) extern
Commit bytes written via direct write pointer.
Parameters
buf The buffer where data was written.
len Exact number of bytes written at the pointer from writeptr().
Exceptions
SocketBuf_Failed if buffer is invalid or len > available space.
Note
Must match or be <= the len from corresponding SocketBuf_writeptr() call.
Behavior undefined (assert in debug) if len exceeds available space.
Updates internal write position and available space.
Performance: O(1).
Thread Safety\n No - must be called by same thread/lock holder as writeptr().
See also
SocketBuf_writeptr() to obtain write location and space.
SocketBuf_write() for alternative non-zero-copy write.
Core I/O for zero-copy patterns with sockets.
SocketCommon_advance_iov()
void SocketCommon_advance_iov (struct iovec * iov, int iovcnt, size_t bytes) extern
Advance iovec array past sent/received bytes (modifies in place)
Parameters
iov Array of iovec structures to advance
iovcnt Number of iovec structures
bytes Bytes to advance (must <= total iov len)
Note
Behavior: Sets advanced iovs to len=0/base=NULL, partial to offset/len reduced
Exceptions
SocketCommon_Failed if bytes > total iov len or invalid params
Note
Thread-safe: Yes (local ops)
Unifies duplicated advance logic for sendvall/recvvall
SocketCommon_alloc_iov_copy()
struct iovec * SocketCommon_alloc_iov_copy (const struct iovec * iov, int iovcnt, Except_T exc_type) extern
Allocate and copy iovec array.
Parameters
iov Source iovec array to copy
iovcnt Number of iovec structures (>0, <=IOV_MAX)
exc_type Exception type to raise on allocation failure
Returns
Newly allocated copy of iovec array (caller must free)
Exceptions
exc_type on allocation failure
Note
Thread-safe: Yes
Common helper for sendvall/recvvall implementations. Consolidates duplicate calloc+memcpy patterns across Socket and SocketDgram modules.
SocketCommon_cache_endpoint()
int SocketCommon_cache_endpoint (Arena_T arena, const struct sockaddr * addr, socklen_t addrlen, char ** addr_out, int * port_out)
Extract and cache human-readable numeric address and port from sockaddr structure.
Converts a binary sockaddr (from getsockname, getpeername, etc.) to numeric string representation (IP:port) allocated from the provided arena. Uses getnameinfo() with NI_NUMERICHOST and NI_NUMERICSERV flags for numeric-only output (no reverse DNS).
Purpose: Facilitates logging, metrics, debugging by providing string form of endpoints without repeated formatting or temporary allocations. Arena allocation ties lifetime to owning object (e.g., socket base).
Supported families: AF_INET, AF_INET6, AF_UNIX (for Unix, addr_str may be path, port=0). On failure, outputs unchanged, error logged via SocketLog, errno not set.
Edge cases:
Invalid addr/addrlen: Logs error, returns -1
Arena allocation fail: Returns -1, addr_out unchanged
Unsupported family: getnameinfo fails, returns -1
Unix domain: port=0, addr_str = socket path (if available)
Parameters
[in] arena Arena_T for allocating the address string copy. Must be valid.
[in] addr const sockaddr* to format (IPv4, IPv6, Unix supported).
[in] addrlen socklen_t length of addr structure.
[out] addr_out char** set to arena-allocated numeric address string (e.g., "127.0.0.1" or "[::1]"). Unchanged on failure. Caller does not free - arena-managed.
[out] port_out int* set to extracted port number (host byte order, 0 if not available e.g., Unix).
Returns
0 on success (outputs populated), -1 on failure (getnameinfo or alloc error). On failure, error details logged via SOCKET_ERROR_MSG; check Socket_GetLastError().
Exceptions
None - returns error code instead of raising.
Thread Safety\n Yes - local buffers, getnameinfo thread-safe on modern systems.
Usage Example (After getsockname)
struct sockaddr_storage local_addr;
socklen_t len = sizeof(local_addr);
getsockname(fd, (struct sockaddr*)&local_addr, &len);
char *cached_addr;
int cached_port;
if (SocketCommon_cache_endpoint(arena, (struct sockaddr*)&local_addr, len,
                                &cached_addr, &cached_port) == 0) {
    SOCKET_LOG_INFO_MSG("Bound to %s:%d", cached_addr, cached_port);
    // cached_addr lifetime = arena
} else {
    SOCKET_LOG_WARN_MSG("Failed to cache local endpoint");
}
Peer Address Caching
// After accept or connect
struct sockaddr_storage peer;
socklen_t peer_len = sizeof(peer);
getpeername(sock_fd, (struct sockaddr*)&peer, &peer_len);
char *peer_ip;
int peer_port;
SocketCommon_cache_endpoint(SocketBase_arena(base), (struct sockaddr*)&peer,
peer_len, &peer_ip, &peer_port);
// Use for logging: "Peer %s:%d connected", peer_ip, peer_port
Note
String format: IPv4 "x.x.x.x", IPv6 "[xxxx::xxxx]" per getnameinfo numeric.
Port parsing from service string; fails gracefully to 0 if invalid.
For Unix domain, addr_str may be path up to NI_MAXHOST length.
Warning
Buffers internally sized to NI_MAXHOST/NI_MAXSERV - truncation possible but rare.
Complexity\n O(1) - getnameinfo bounded time, arena alloc constant.
See also
getnameinfo(3) for numeric formatting details
SocketBase_T local/remote endpoint caching which uses this
Socket_getlocaladdr/port, Socket_getpeeraddr/port public wrappers
core/Arena.h for allocation management
SocketCommon_calculate_total_iov_len()
size_t SocketCommon_calculate_total_iov_len (const struct iovec * iov, int iovcnt) extern
Calculate total length of iovec array with overflow protection.
Parameters
iov Array of iovec structures
iovcnt Number of iovec structures (>0, <=IOV_MAX)
Returns
Total bytes across all iov_len
Exceptions
SocketCommon_Failed on integer overflow during summation
Note
Thread-safe: Yes
Unifies duplicated calculation loops across modules
SocketCommon_check_bound_by_family()
static int SocketCommon_check_bound_by_family (const struct sockaddr_storage * addr) inline static
Check if socket is bound based on family.
Parameters
addr sockaddr_storage containing address
Returns
1 if bound, 0 otherwise
Definition at line 1043 of file SocketCommon.h.
References SocketCommon_check_bound_ipv4(), SocketCommon_check_bound_ipv6(), and SocketCommon_check_bound_unix().
SocketCommon_check_bound_ipv4()
static int SocketCommon_check_bound_ipv4 (const struct sockaddr_storage * addr) inline static
Check if IPv4 socket is bound.
Parameters
addr sockaddr_storage containing address
Returns
1 if bound (port != 0), 0 otherwise
Definition at line 1004 of file SocketCommon.h.
Referenced by SocketCommon_check_bound_by_family().
SocketCommon_check_bound_ipv6()
static int SocketCommon_check_bound_ipv6 (const struct sockaddr_storage * addr) inline static
Check if IPv6 socket is bound.
Parameters
addr sockaddr_storage containing address
Returns
1 if bound (port != 0), 0 otherwise
Definition at line 1017 of file SocketCommon.h.
Referenced by SocketCommon_check_bound_by_family().
SocketCommon_check_bound_unix()
static int SocketCommon_check_bound_unix (const struct sockaddr_storage * addr) inline static
Check if Unix socket is bound.
Parameters
addr sockaddr_storage containing address (unused)
Returns
1 (Unix domain sockets are bound if getsockname succeeds)
Definition at line 1030 of file SocketCommon.h.
Referenced by SocketCommon_check_bound_by_family().
SocketCommon_cidr_match()
int SocketCommon_cidr_match (const char * ip_str, const char * cidr_str)
Check if IP address matches CIDR range.
Parameters
ip_str IP address string to check
cidr_str CIDR notation string (e.g., "192.168.1.0/24" or "2001:db8::/32")
Returns
1 if IP matches CIDR range, 0 if not, -1 on error
Note
Thread-safe: Yes
Supports both IPv4 and IPv6 CIDR notation.
Returns -1 if IP or CIDR string is invalid.
SocketCommon_copy_addrinfo()
struct addrinfo * SocketCommon_copy_addrinfo (const struct addrinfo * src) extern
Deep copy of addrinfo linked list.
Parameters
src Source chain to copy (may be NULL)
Returns
malloc-allocated deep copy, or NULL on error
Note
Deep copies the entire chain including ai_addr and ai_canonname fields.
Caller takes ownership and MUST free with SocketCommon_free_addrinfo().
Do NOT use freeaddrinfo() on the result - it's undefined behavior.
No exceptions raised; returns NULL on malloc failure or src==NULL.
Thread-safe: Yes
SocketCommon_create_fd()
int SocketCommon_create_fd (int domain, int type, int protocol, Except_T exc_type) extern
Create a new socket file descriptor with error handling and CLOEXEC setup.
Low-level wrapper around socket(2) system call that creates a new file descriptor, sets FD_CLOEXEC flag, disables SIGPIPE generation (platform-specific), and raises specified exception on failure. Used during socket instance creation before base init.
Error Conditions
errno Meaning Retryable
EACCES Permission denied No
EMFILE Per-process fd limit Yes (after close)
ENFILE System-wide fd limit Yes (system resource)
EAFNOSUPPORT Address family unsupported No
ENOBUFS No buffer space Yes (transient)
Parameters
[in] domain Address family (AF_INET, AF_INET6, AF_UNIX)
[in] type Socket type (SOCK_STREAM, SOCK_DGRAM)
[in] protocol Protocol (usually 0 for default)
[in] exc_type Exception type to raise on failure (e.g., Socket_Failed)
Returns
New non-negative file descriptor on success, -1 on error (raises exc_type)
Exceptions
exc_type on socket(2) failure with formatted message including errno
Thread Safety\n Yes - no shared state or globals modified
Complexity\n O(1) - single system call + flag setup
Usage Example
TRY {
    int fd = SocketCommon_create_fd(AF_INET, SOCK_STREAM, 0, Socket_Failed);
    SocketBase_T base = CALLOC(NULL, 1, sizeof(struct SocketBase_T));
    SocketCommon_init_base(base, fd, AF_INET, SOCK_STREAM, 0,
Socket_Failed);
    // Now embed base in subtype struct
} EXCEPT(Socket_Failed) {
    SOCKET_LOG_ERROR_MSG("Failed to create socket: %s",
Socket_GetLastError()); return -1; } END_TRY;
Note
Automatically sets FD_CLOEXEC to prevent fd inheritance on execve(2).
Handles platform-specific SIGPIPE suppression (SO_NOSIGPIPE or MSG_NOSIGNAL policy).
Caller responsible for closing fd on error paths before raising.
Warning
Do not use directly in application code; internal library use only.
See also
socket(2) for underlying system call
SocketCommon_init_base() for initializing SocketBase_T with returned fd
SocketCommon_setcloexec_with_error() for explicit CLOEXEC handling
SocketCommon_disable_sigpipe() for SIGPIPE details
docs/SECURITY.md#file-descriptor-leaks for CLOEXEC importance
SocketCommon_find_active_iov()
struct iovec * SocketCommon_find_active_iov (struct iovec * iov, int iovcnt, int * active_iovcnt) extern
Find first non-empty iovec in array.
Parameters
iov Array of iovec structures to search
iovcnt Number of iovec structures
active_iovcnt Output for count of remaining iovecs from active position
Returns
Pointer to first iovec with iov_len > 0, or NULL if all empty
Note
Thread-safe: Yes (read-only operation)
Used by sendvall/recvvall to find the next active buffer segment after partial I/O operations have consumed some of the iovec array.
SocketCommon_format_bind_error()
void SocketCommon_format_bind_error (const char * host, int port) extern
Format descriptive bind error message.
Parameters
host Host string (NULL defaults to "any")
port Port number
Note
Formats error in socket_error_buf based on errno (EADDRINUSE, EACCES, etc.)
Consolidated helper for Socket and SocketDgram bind error handling.
Does not raise - caller should raise after calling this.
SocketCommon_free_addrinfo()
void SocketCommon_free_addrinfo (struct addrinfo * ai) extern
Free addrinfo chain created by copy_addrinfo.
Parameters
ai Chain to free (may be NULL, safe no-op)
Note
Frees all nodes in the chain including ai_addr and ai_canonname fields.
Use this instead of freeaddrinfo() for chains from SocketCommon_copy_addrinfo.
Thread-safe: Yes
SocketCommon_free_base()
void SocketCommon_free_base (SocketBase_T * base_ptr) extern
Free a socket base structure.
Parameters
base_ptr Pointer to socket base (will be set to NULL).
Note
Cleans up all resources associated with the socket base.
SocketCommon_get_dns_resolver()
SocketDNS_T SocketCommon_get_dns_resolver (void) extern
Get global DNS resolver instance.
Returns
Global DNS resolver (lazily initialized on first call)
Note
Thread-safe: Yes - uses pthread_once for initialization
The global DNS resolver is shared across all Socket and SocketDgram operations. It provides timeout guarantees for DNS resolution.
SocketCommon_get_dns_timeout()
int SocketCommon_get_dns_timeout (void) extern
Get current global DNS timeout.
Returns
Current timeout in milliseconds (0 = infinite)
Note
Thread-safe: Yes
SocketCommon_get_socket_family()
int SocketCommon_get_socket_family (SocketBase_T base) extern
Get socket's address family.
Parameters
base Socket base to query
Returns
Socket family or AF_UNSPEC on error
Note
Uses SO_DOMAIN on Linux, falls back to getsockname() on other platforms.
SocketCommon_getoption_int()
int SocketCommon_getoption_int (int fd, int level, int optname, int * value, Except_T exception_type)
Get integer socket option.
Parameters
fd File descriptor
level Option level (SOL_SOCKET, IPPROTO_TCP, etc.)
optname Option name (SO_KEEPALIVE, TCP_NODELAY, etc.)
value Output pointer for option value
exception_type Exception type to raise on failure
Returns
0 on success, -1 on failure
Exceptions
Specified exception type on failure
Note
Thread-safe: Yes (operates on single fd)
SocketCommon_getoption_timeval()
int SocketCommon_getoption_timeval (int fd, int level, int optname, struct timeval * tv, Except_T exception_type)
Get timeval socket option.
Parameters
fd File descriptor
level Option level (SOL_SOCKET)
optname Option name (SO_RCVTIMEO, SO_SNDTIMEO)
tv Output pointer for timeval structure
exception_type Exception type to raise on failure
Returns
0 on success, -1 on failure
Exceptions
Specified exception type on failure
Note
Thread-safe: Yes (operates on single fd)
SocketCommon_handle_bind_error()
int SocketCommon_handle_bind_error (int err, const char * addr_str, Except_T exc_type) extern
Log and raise bind error.
Parameters
err errno from bind
addr_str Addr string for log
exc_type Type to raise
Note
Graceful for non-fatal (e.g., EADDRINUSE log warn return -1), fatal raise
SocketCommon_has_cloexec()
int SocketCommon_has_cloexec (int fd)
Check if close-on-exec flag is set.
Parameters
fd File descriptor to check
Returns
1 if CLOEXEC is set, 0 if not set, -1 on error
Note
Thread-safe: Yes (operates on single fd)
SocketCommon_init_base()
void SocketCommon_init_base (SocketBase_T base, int fd, int domain, int type, int protocol, Except_T exc_type) extern
Initialize pre-allocated SocketBase_T with FD and parameters.
Performs full initialization of a pre-allocated base structure: sets fields, creates per-socket arena, initializes mutex, sets CLOEXEC flag, disables SIGPIPE, caches initial endpoints if possible, initializes timeouts and metrics to defaults. Used when creating sockets from existing FDs (e.g., accept(2), dup(2), or raw socket()).
Parameters
[in,out] base Pre-allocated base structure (must be zeroed or from CALLOC)
[in] fd File descriptor to associate (must be valid socket FD)
[in] domain Address family matching FD (AF_INET, etc.)
[in] type Socket type matching FD (SOCK_STREAM, etc.)
[in] protocol Protocol matching FD (usually 0)
[in] exc_type Exception type for any initialization failures
Exceptions
exc_type on failures: arena alloc, mutex init, fcntl CLOEXEC, getsockname cache
Thread Safety\n No - assumes exclusive access to base and FD
Complexity\n O(1) - fixed operations + potential getsockname(2)
Usage Example
TRY {
    int fd = accept(server_fd, NULL, 0);  // Or socket(), etc.
    if (fd >= 0) {
        SocketBase_T base = CALLOC(arena, 1, sizeof(*base));
        SocketCommon_init_base(base, fd, AF_INET, SOCK_STREAM, 0,
Socket_Failed);
        // Embed base in Socket_T or SocketDgram_T
        // Update endpoints post-accept via getsockname/getpeername
    }
} EXCEPT(Socket_Failed) {
    close(fd);  // Cleanup on error
} END_TRY;
Note
Takes ownership of fd; closes on error paths via exception handling.
Arena created internally; all subsequent allocations use it.
Mutex initialized to PTHREAD_MUTEX_DEFAULT; recursive locks possible but discouraged.
Endpoints cached if possible (getsockname success); otherwise lazy.
Warning
base must not be used before init; post-init, follow lock protocol.
Note
Alternative to SocketCommon_new_base() when FD pre-exists.
See also
SocketCommon_new_base() for allocation + init in one step
SocketCommon_create_fd() for creating FD prior to init
SocketCommon_setcloexec_with_error() internal CLOEXEC call
SocketCommon_update_local_endpoint() for post-bind endpoint refresh
docs/ERROR_HANDLING.md for TRY/EXCEPT patterns with FD cleanup
SocketCommon_join_multicast()
void SocketCommon_join_multicast (SocketBase_T base, const char * group, const char * interface, Except_T exc_type) extern
Join multicast group.
Parameters
base Socket base with fd (must be datagram for standard use)
group Multicast group string (e.g., "239.0.0.1" or "ff02::1")
interface Interface IP or NULL for default
exc_type Exception to raise on failure
Note
Resolves group, joins via setsockopt based on family (IPv4/IPv6)
Handles resolution, interface setup, family-specific mreq
Thread-safe for own fd
SocketCommon_leave_multicast()
void SocketCommon_leave_multicast (SocketBase_T base, const char * group, const char * interface, Except_T exc_type) extern
Leave multicast group.
Parameters
base Socket base with fd
group Multicast group string
interface Interface IP or NULL
exc_type Exception to raise on failure
Note
Symmetric to join; drops membership via setsockopt
SocketCommon_new_base()
SocketBase_T SocketCommon_new_base (int domain, int type, int protocol) extern
Create a new socket base structure.
Parameters
domain Address family (AF_INET, AF_INET6, AF_UNIX).
type Socket type (SOCK_STREAM, SOCK_DGRAM).
protocol Protocol (usually 0 for default).
Returns
New socket base instance.
Exceptions
SocketCommon_Failed on allocation failure.
SocketCommon_normalize_wildcard_host()
const char * SocketCommon_normalize_wildcard_host (const char * host)
Normalize wildcard/any-address host strings to NULL for internal use.
Converts common wildcard address strings to NULL, which is the canonical representation for "bind/connect to any interface" in socket operations. This simplifies internal logic in bind/connect where NULL host means INADDR_ANY.
Recognized wildcards:
NULL input -> NULL (already canonical)
"0.0.0.0" -> NULL (IPv4 any)
"::" -> NULL (IPv6 any) Other strings returned unchanged (caller responsible for resolution).
Does not perform DNS resolution or validation - pure string comparison. Case-sensitive match.
Parameters
[in] host Host string to normalize (may be NULL).
Returns
NULL if input represents wildcard/any, otherwise original host string (const). Return value is always either NULL or the input pointer (no allocation).
Exceptions
None
Thread Safety\n Yes - read-only string comparison, no shared state.
Usage Example
const char *effective_host =
SocketCommon_normalize_wildcard_host("0.0.0.0");
// effective_host == NULL
SocketCommon_resolve_address(effective_host, 8080, &hints, &res, ...);  //
Resolves to any local addr
Non-Wildcard
const char *host = "192.168.1.1";
const char *norm = SocketCommon_normalize_wildcard_host(host);
// norm == host (unchanged)
Note
Used internally by Socket_bind() and Socket_connect() for canonical handling.
Does not handle other wildcard forms like "any" or "*" - only numeric any addresses.
For IPv6, only "::" recognized; full "::0" or others not normalized here.
Complexity\n O(1) average - fixed string comparisons
See also
SocketCommon_resolve_address() which uses this for wildcard handling
Socket_bind() and Socket_connect() consumers
SocketCommon_parse_ip()
int SocketCommon_parse_ip (const char * ip_str, int * family)
Validate and parse IP address string.
Parameters
ip_str IP address string to validate
family Output pointer for address family (AF_INET or AF_INET6), can be NULL
Returns
1 if valid IP address, 0 if invalid
Note
Thread-safe: Yes
Validates both IPv4 and IPv6 addresses. Sets family to AF_INET for IPv4, AF_INET6 for IPv6, or AF_UNSPEC if invalid.
SocketCommon_resolve_address()
int SocketCommon_resolve_address (const char * host, int port, const struct addrinfo * hints, struct addrinfo ** res, Except_T exception_type, int socket_family, int use_exceptions)
Resolve hostname/port to addrinfo structure using getaddrinfo wrapper.
Parameters
host Hostname or IP address (NULL for wildcard/any).
port Port number (1 to SOCKET_MAX_PORT).
hints Addrinfo hints structure (prepared via SocketCommon_setup_hints()).
res Output pointer to resolved addrinfo list (caller must free with freeaddrinfo()).
exception_type Exception type to raise on failure.
socket_family Preferred socket family to match (AF_UNSPEC for any).
use_exceptions If true, raise exceptions on failure; if false, return error codes and set errno.
Returns
0 on success, -1 on failure (if not using exceptions).
Exceptions
Specified exception_type on resolution failure (getaddrinfo errors, invalid port, etc.).
Note
Uses global DNS resolver (SocketCommon_get_dns_resolver()) for timeout guarantees if hostname provided.
Filters resolved addresses to match socket_family if specified (e.g., AF_INET only).
Caller responsible for validating and freeing the addrinfo chain.
Thread-safe: Yes (uses thread-local error buffers).
See also
SocketCommon_setup_hints() for preparing hints structure.
Socket_bind() and Socket_connect() which use this internally.
SocketCommon_get_dns_resolver() for global DNS timeout configuration.
SocketCommon_copy_addrinfo() for duplicating resolved chains.
freeaddrinfo(3) for cleaning up resolved structures.
docs/ERROR_HANDLING.md for exception patterns in network code.
SocketCommon_reverse_lookup()
int SocketCommon_reverse_lookup (const struct sockaddr * addr, socklen_t addrlen, char * host, socklen_t hostlen, char * serv, socklen_t servlen, int flags, Except_T exception_type)
Perform reverse DNS lookup (getnameinfo wrapper)
Parameters
addr Socket address to look up
addrlen Length of socket address
host Output buffer for hostname (NULL to skip)
hostlen Size of host buffer
serv Output buffer for service/port (NULL to skip)
servlen Size of service buffer
flags getnameinfo flags (NI_NUMERICHOST, NI_NAMEREQD, etc.)
exception_type Exception type to raise on failure
Returns
0 on success, -1 on failure
Exceptions
Specified exception type on failure
Note
Thread-safe: Yes
Wrapper around getnameinfo() for reverse DNS lookups.
Use NI_NUMERICHOST flag to get numeric IP address instead of hostname.
socketcommon_sanitize_timeout()
int socketcommon_sanitize_timeout (int timeout_ms) extern
Sanitize raw timeout value, applying library policy for valid range.
Clamps and normalizes timeout milliseconds to prevent invalid or overflow values in socket operations. Library policy:
Negative: Treated as 0 (no timeout/infinite)
Zero: No timeout
Positive huge (>INT_MAX): Clamped to INT_MAX
Invalid input (e.g., NaN if float cast): -1 error
Used defensively in all timeout setters (connect_ms, send_ms, etc.) to ensure safe values before applying to base.timeouts or SO_*TIMEO options.
Input/Output Mapping
Input (ms) Output (ms) Behavior
< 0 0 Infinite/no timeout
0 0 No timeout
1..INT_MAX unchanged Valid timeout
> INT_MAX INT_MAX Clamped max
Invalid -1 Error (caller handles)
Parameters
[in] timeout_ms Raw timeout value from config or user input
Returns
Sanitized timeout (>=0 valid, -1 error)
Exceptions
None - returns error code instead
Thread Safety\n Yes - pure function, no state
Complexity\n O(1) - simple comparisons and clamps
Usage Example
int safe_timeout = socketcommon_sanitize_timeout(user_config->connect_ms);
if (safe_timeout < 0) {
    SOCKET_LOG_WARN_MSG("Invalid timeout; using default");
    safe_timeout = SOCKET_DEFAULT_CONNECT_TIMEOUT_MS;
}
base->timeouts.connect_ms = safe_timeout;
Note
Prevents signed overflow in time calculations (e.g., SocketTimeout_deadline_ms).
Consistent policy across all timeout fields in SocketTimeouts_T.
Warning
Callers must check return <0 and fallback to defaults.
Note
Used internally by SocketBase_set_timeouts() and option setters.
See also
SocketTimeouts_T fields (connect_ms, send_ms, recv_ms, dns_ms)
SocketCommon_settimeout() for applying to SO_SNDTIMEO/SO_RCVTIMEO
core/SocketConfig.h for default timeout constants
docs/TIMEOUTS.md for timeout configuration guide
SocketCommon_set_cloexec_fd()
void SocketCommon_set_cloexec_fd (int fd, bool enable, Except_T exc_type) extern
Set close-on-exec flag on fd (unifies dups)
Parameters
fd File descriptor
enable True to enable FD_CLOEXEC
exc_type Raise on fail
Note
Uses fcntl F_SETFD; called after socket()/socketpair()/accept() fallback
SocketCommon_set_dns_timeout()
void SocketCommon_set_dns_timeout (int timeout_ms) extern
Set global DNS resolution timeout.
Parameters
timeout_ms Timeout in milliseconds (0 = infinite, -1 = use default)
Note
Thread-safe: Yes - protected by mutex
Affects all subsequent hostname resolution via Socket/SocketDgram APIs.
Default: SOCKET_DEFAULT_DNS_TIMEOUT_MS (5000ms)
Setting timeout_ms to 0 disables timeout (infinite wait).
Setting timeout_ms to -1 resets to default.
SocketCommon_set_nonblock()
void SocketCommon_set_nonblock (SocketBase_T base, bool enable, Except_T exc_type) extern
Set non-blocking mode.
Parameters
base Base with fd
enable True to enable non-block
exc_type Raise on fail
Note
Unifies duplicated fcntl calls for O_NONBLOCK
SocketCommon_set_option_int()
void SocketCommon_set_option_int (SocketBase_T base, int level, int optname, int value, Except_T exc_type) extern
Set integer socket option.
Parameters
base Base with fd
level Option level (SOL_SOCKET, IPPROTO_TCP, etc.)
optname Option name (SO_REUSEADDR, TCP_NODELAY, etc.)
value Value to set
exc_type Exception to raise on failure
Note
Generic setter for standard socket options, unifies duplicated setsockopt calls
Thread-safe: Yes for own resources
SocketCommon_set_ttl()
void SocketCommon_set_ttl (SocketBase_T base, int family, int ttl, Except_T exc_type) extern
Set TTL or hop limit based on family.
Parameters
base Base with fd
family AF_INET or AF_INET6
ttl TTL value
exc_type Raise on fail
Note
Unifies set_ipv4_ttl and set_ipv6_hop_limit
SocketCommon_setcloexec()
int SocketCommon_setcloexec (int fd, int enable)
Set or clear the close-on-exec (CLOEXEC) flag on a file descriptor.
Modifies the FD_CLOEXEC file descriptor flag using fcntl(F_SETFD) to control whether the file descriptor is automatically closed across execve() calls (e.g., fork+exec).
Enabling CLOEXEC (enable=1) is a security best practice to prevent unintended FD leakage to child processes in multi-process applications. Disabling (enable=0) is rarely needed but supported for compatibility.
This function is called automatically after socket(), accept(), etc., to ensure library sockets have CLOEXEC set by default (configurable via SocketConfig).
On failure, sets errno to EBADF (invalid fd) or EINVAL (invalid flag).
Parameters
[in] fd File descriptor to modify (must be valid open FD).
[in] enable Non-zero to set FD_CLOEXEC, 0 to clear it.
Returns
0 on success, -1 on failure (errno set).
Exceptions
None - uses return code/errno convention.
Thread Safety\n Yes - fcntl operates on single FD atomically.
Usage Example
// Enable CLOEXEC on newly created socket FD
int sock_fd = socket(AF_INET, SOCK_STREAM, 0);
if (SocketCommon_setcloexec(sock_fd, 1) < 0) {
    close(sock_fd);
    perror("Failed to set CLOEXEC");
    return -1;
}
// Now safe for exec after fork
Disable for Specific FD
// Rare: clear CLOEXEC (e.g., for FD passing)
SocketCommon_setcloexec(fd, 0);  // Allows FD to survive exec
Note
Automatically called by library after socket creation for security hardening.
Equivalent to fcntl(fd, F_SETFD, enable ? FD_CLOEXEC : 0)
On failure, check errno: EBADF invalid fd, EINVAL bad flag value.
Warning
Always enable CLOEXEC unless FD inheritance is explicitly needed (security risk).
Complexity\n O(1) - single fcntl system call
See also
SocketCommon_has_cloexec() to query current flag state
fcntl(2) F_SETFD/F_GETFD for POSIX details
docs/SECURITY.md for FD leakage prevention best practices
SocketCommon_setup_hints()
void SocketCommon_setup_hints (struct addrinfo * hints, int socktype, int flags)
Initialize addrinfo hints structure for address resolution operations.
Prepares a struct addrinfo hints for use with getaddrinfo() or SocketCommon_resolve_address(). This function ensures dual-stack IPv4/IPv6 support by setting ai_family to AF_UNSPEC, and configures the socket type and additional resolution flags. The hints structure must be zero-initialized before calling this function to avoid garbage data.
Important notes:
Always zero the hints structure first with memset(hints, 0, sizeof(*hints))
ai_protocol remains 0 (default protocol for socktype)
For binding operations, use AI_PASSIVE | AI_ADDRCONFIG flags
For connecting/sending, use AI_ADDRCONFIG for preferring configured interfaces
This setup enables Happy Eyeballs (RFC 6555) compatible resolution when used with SocketDNS
Parameters
[in,out] hints Pointer to addrinfo structure to initialize. Must point to valid memory. The structure will be zeroed and configured with standard values.
[in] socktype Socket type: SOCK_STREAM for TCP, SOCK_DGRAM for UDP.
[in] flags Resolution flags: e.g., AI_PASSIVE for bind, 0 for connect/sendto. Common combinations: AI_PASSIVE | AI_ADDRCONFIG for servers.
Returns
None (void function)
Exceptions
None
Thread Safety\n Yes - operates only on caller-provided structure, no shared
state.
Usage Example
// For TCP server bind (passive mode)
struct addrinfo hints, *res;
SocketCommon_setup_hints(&hints, SOCK_STREAM, AI_PASSIVE | AI_ADDRCONFIG);
int rv = getaddrinfo("0.0.0.0", "8080", &hints, &res);
if (rv == 0) {
    // Use res for binding
    freeaddrinfo(res);
}
Client Connection Setup
// For TCP client connect
struct addrinfo hints;
SocketCommon_setup_hints(&hints, SOCK_STREAM, AI_ADDRCONFIG);
struct addrinfo *res;
SocketCommon_resolve_address("example.com", 80, &hints, &res, Socket_Failed,
AF_UNSPEC, 1);
// Use res...
SocketCommon_free_addrinfo(res);  // If copied, use this instead of
freeaddrinfo
Note
Always pair with SocketCommon_resolve_address() for exception-safe resolution.
For Unix domain sockets, set ai_family = AF_UNIX manually after this call.
This function does not set ai_protocol; it defaults to 0 (auto-select).
Complexity\n O(1) - constant time memory operations
See also
SocketCommon_resolve_address() for complete resolution with error handling
getaddrinfo(3) for POSIX specification
Socket_bind() and Socket_connect() which use similar setup internally
docs/ASYNC_IO.md for advanced resolution patterns with SocketDNS
SocketCommon_shutdown_globals()
void SocketCommon_shutdown_globals (void) extern
Shutdown global resources (e.g., DNS resolver) to prevent leaks in testsCall at program exit after all operations complete.
Thread Safety\n Yes - but call from main thread only.
Note
Frees global DNS resolver and other static resources.
SocketCommon_sync_iov_progress()
void SocketCommon_sync_iov_progress (struct iovec * original, const struct iovec * copy, int iovcnt) extern
Sync original iovec with working copy progress.
Parameters
original Original iovec array to update
copy Working copy that has been advanced
iovcnt Number of iovec structures
Note
Updates the original iovec array to reflect progress made in the copy.
Used when recvvall needs to update caller's iovec on partial completion.
Thread-safe: Yes (local ops)
SocketCommon_timeouts_getdefaults()
void SocketCommon_timeouts_getdefaults (SocketTimeouts_T * timeouts) extern
Get global default timeouts.
Parameters
timeouts Output pointer for timeout structure
Note
Thread-safe: Yes (uses mutex protection)
SocketCommon_timeouts_setdefaults()
void SocketCommon_timeouts_setdefaults (const SocketTimeouts_T * timeouts) extern
Set global default timeouts.
Parameters
timeouts Timeout values to set as defaults
Note
Thread-safe: Yes (uses mutex protection)
SocketCommon_try_bind_address()
int SocketCommon_try_bind_address (SocketBase_T base, const struct sockaddr * addr, socklen_t addrlen, Except_T exc_type) extern
Try bind fd to address (extracted from Socket.c)
Parameters
base Socket base with fd
addr Address to bind
addrlen Addr length
exc_type Raise on fail
Returns
0 success, -1 fail (raises on error)
Note
Integrates with base endpoints if success (caller handles)
SocketCommon_try_bind_resolved_addresses()
int SocketCommon_try_bind_resolved_addresses (SocketBase_T base, struct addrinfo * res, int family, Except_T exc_type) extern
Try bind to resolved addrinfo list.
Parameters
base Socket base with fd
res addrinfo list from resolve
family Preferred family (AF_INET etc)
exc_type Raise on all fails
Returns
0 success (bound to first successful), -1 fail
Note
Loops addresses, calls try_bind_address, sets base local endpoint on success
Handles dual-stack, reuseaddr hints via set_option_int
SocketCommon_update_local_endpoint()
void SocketCommon_update_local_endpoint (SocketBase_T base) extern
Update local endpoint information from getsockname.
Parameters
base Socket base to update.
Note
Non-raising helper for updating local address/port after bind.
SocketCommon_validate_host_not_null()
void SocketCommon_validate_host_not_null (const char * host, Except_T exception_type) extern
Validate host is not NULL.
Parameters
host Host string to validate
exception_type Exception type to raise on NULL host
Exceptions
Specified exception type if host is NULL
Note
Thread-safe: Yes
SocketCommon_validate_hostname()
void SocketCommon_validate_hostname (const char * host, Except_T exception_type)
Validate that a hostname string is not excessively long for system buffers.
Checks the length of the hostname string against the maximum allowed for system network functions (typically NI_MAXHOST or 255 bytes). Too long hostnames can cause failures in getaddrinfo(), getnameinfo(), etc. Raises exception with details on failure.
This validation prevents buffer overflows or truncation in underlying system calls. Does not perform DNS resolution or syntax validation - only length check. NULL host is considered invalid (use SocketCommon_validate_host_not_null for that).
Defined max length: SOCKET_MAX_HOSTNAME_LEN (from SocketConfig.h, usually 255)
Parameters
[in] host C-string hostname to validate (non-NULL expected).
[in] exception_type Except_T to raise if length exceeds limit.
Returns
None (void) - raises on failure.
Exceptions
exception_type with message detailing the length violation and max allowed.
Thread Safety\n Yes - reads only, no shared state.
Usage Example
const char *hostname = "example.com";
TRY {
    SocketCommon_validate_hostname(hostname, Socket_Failed);
    // Safe to use in resolve_address or connect
    SocketCommon_resolve_address(hostname, 80, &hints, &res, Socket_Failed,
AF_UNSPEC, 1); } EXCEPT(Socket_Failed) { SOCKET_LOG_ERROR_MSG("Hostname too
long: %s", hostname); } END_TRY;
Note
Call before resolution to catch early.
For IP addresses, length check still applies but usually pass.
Does not check for valid hostname format (use regex or library if needed).
Complexity\n O(n) where n=strlen(host) - linear scan for length.
See also
SocketCommon_validate_port() companion function
SocketCommon_validate_host_not_null() for NULL check
SocketCommon_resolve_address() internal caller
SocketConfig.h SOCKET_MAX_HOSTNAME_LEN constant
SocketCommon_validate_port()
void SocketCommon_validate_port (int port, Except_T exception_type)
Validate that a port number is within the valid range for socket operations.
Ensures the provided port is between 0 and 65535 inclusive. Port 0 is allowed for cases where the OS assigns an ephemeral port (e.g., during bind for outgoing connections). Invalid ports trigger an immediate exception raise with a descriptive message including the invalid value.
This function is used internally by resolution and bind/connect operations to catch invalid port parameters early. It does not perform any system calls or allocations.
Edge cases:
port < 0: Invalid, raises exception
port == 0: Valid (ephemeral)
port > 65535: Invalid, raises exception
Non-integer ports: Caller responsibility (port is int param)
Parameters
[in] port Port number to validate (int value).
[in] exception_type Except_T type to raise on validation failure.
Returns
None (void function) - raises exception on failure.
Exceptions
exception_type with message "Invalid port number: %d (must be 0-65535, 0 = OS-assigned)" where d is the invalid port value.
Thread Safety\n Yes - no shared state or system calls, pure validation.
Usage Example
// In connect or bind preparation
TRY {
    SocketCommon_validate_port(8080, Socket_Failed);
    // Proceed with bind/connect using port 8080
} EXCEPT(Socket_Failed) {
    // This won't trigger for valid port
} END_TRY;
With Ephemeral Port
int ephemeral_port = 0;  // OS assign
SocketCommon_validate_port(ephemeral_port, Socket_Failed);  // Valid, no
exception
Invalid Port Handling
TRY {
    SocketCommon_validate_port(70000, Socket_Failed);  // Raises exception
} EXCEPT(Socket_Failed) {
    // Caught here with detailed message
    const char *msg = Except_message(Except_stack);  // Access error details
    SOCKET_LOG_ERROR_MSG("Port validation failed: %s", msg);
} END_TRY;
Note
Commonly called before getaddrinfo(), Socket_bind(), Socket_connect().
For string ports, validate after parsing with strtol() or similar.
Does not check privileged ports (<1024) - that's OS permission check.
Complexity\n O(1) - simple integer comparison
See also
SocketCommon_validate_hostname() for host validation
SocketCommon_resolve_address() which calls this internally
docs/SECURITY.md for port Security Modules considerations
SocketConfig.h for SOCKET_MAX_PORT definition (usually 65535)
socketio_is_connection_closed_recv()
static int socketio_is_connection_closed_recv (void) inline static
Check if recv error indicates closed connection.
Returns
1 if ECONNRESET, 0 otherwise
Thread Safety\n Yes - reads errno (thread-local in POSIX).
Note
Use after recv() failure to check for connection close.
See also
socketio_is_wouldblock() for non-blocking checks.
socketio_is_connection_closed_send() for send counterpart.
ECONNRESET in <errno.h>.
Definition at line 279 of file SocketIO.h.
socketio_is_connection_closed_send()
static int socketio_is_connection_closed_send (void) inline static
Check if send error indicates closed connection.
Returns
1 if EPIPE/ECONNRESET, 0 otherwise
Thread Safety\n Yes - reads errno (thread-local in POSIX).
Note
Use after send() failure to check for connection close.
See also
socketio_is_wouldblock() for non-blocking checks.
socketio_is_connection_closed_recv() for recv counterpart.
EPIPE and ECONNRESET in <errno.h>.
Definition at line 262 of file SocketIO.h.
socketio_is_wouldblock()
static int socketio_is_wouldblock (void) inline static
Check if errno indicates operation would block.
Returns
1 if EAGAIN/EWOULDBLOCK, 0 otherwise
Thread Safety\n Yes - reads errno (thread-local in POSIX).
Note
Use this instead of inline errno checks for consistency.
See also
socketio_is_connection_closed_send() and socketio_is_connection_closed_recv() for related error checks.
EAGAIN and EWOULDBLOCK in <errno.h> for details.
Definition at line 245 of file SocketIO.h.
SocketLiveCount_decrement()
static void SocketLiveCount_decrement (struct SocketLiveCount * tracker) inline static
Decrement live count (thread-safe)
Parameters
tracker Live count tracker
Definition at line 1112 of file SocketCommon.h.
References SocketLiveCount::count, and SocketLiveCount::mutex.
SocketLiveCount_get()
static int SocketLiveCount_get (struct SocketLiveCount * tracker) inline static
Get current live count (thread-safe)
Parameters
tracker Live count tracker
Returns
Current count value
Definition at line 1127 of file SocketCommon.h.
References SocketLiveCount::count, and SocketLiveCount::mutex.
SocketLiveCount_increment()
static void SocketLiveCount_increment (struct SocketLiveCount * tracker) inline static
Increment live count (thread-safe)
Parameters
tracker Live count tracker
Definition at line 1099 of file SocketCommon.h.
References SocketLiveCount::count, and SocketLiveCount::mutex.
SocketPair_new()
void SocketPair_new (int type, Socket_T * socket1, Socket_T * socket2) extern
Create a pair of connected Unix domain sockets for inter-process communication.
Creates two connected Unix domain sockets using socketpair(2) system call. The sockets are of the specified type (SOCK_STREAM or SOCK_DGRAM) and are immediately connected to each other. No bind() or connect() is needed. Both sockets are created in blocking mode with default options (CLOEXEC, no SIGPIPE). This is useful for parent-child process communication after fork(), or for thread-to-thread IPC without network stack overhead.
Supported types: SOCK_STREAM (reliable byte stream), SOCK_DGRAM (datagrams). Domain is always AF_UNIX internally.
Edge cases:
Unsupported type raises Socket_Failed (EINVAL)
Resource limits raise Socket_Failed (EMFILE, ENFILE)
On success, both *socket1 and *socket2 are non-NULL and connected.
After use, free both sockets with Socket_free().
Parameters
[in] type Socket type (SOCK_STREAM or SOCK_DGRAM)
[out] socket1 First socket of the pair (set to new Socket_T or NULL on error)
[out] socket2 Second socket of the pair (set to new Socket_T or NULL on error)
Exceptions
Socket_Failed System call failed (EINVAL invalid type, EMFILE/ENFILE too many files, ENOMEM, EAFNOSUPPORT)
Thread Safety\n Yes - creates independent socket pair safe from concurrent calls
Basic Usage
Socket_T sock1, sock2;
SocketPair_new(SOCK_STREAM, &sock1, &sock2);
// Now sock1 and sock2 are connected
// Send from sock1, receive on sock2, etc.
Socket_free(&sock1);
Socket_free(&sock2);
With Error Handling for Fork IPC
TRY {
    Socket_T parent_sock, child_sock;
    SocketPair_new(SOCK_STREAM, &parent_sock, &child_sock);
    pid_t pid = fork();
    if (pid == 0) {  // Child
        Socket_free(&parent_sock);  // Close unused
        // Use child_sock for IPC
    } else {  // Parent
        Socket_free(&child_sock);
        // Use parent_sock for IPC
    }
} EXCEPT(Socket_Failed) {
    perror("Socket pair creation failed");
} END_TRY;
Note
Sockets are bidirectional: data sent on one can be received on the other.
For DGRAM type, it's like connected UDP - sendto not needed.
Warning
Always free both sockets to avoid fd leaks.
After fork(), close the unused socket in both parent and child to avoid deadlocks.
Complexity\n O(1) - single socketpair(2) call
See also
Socket_new() for single socket creation
Socket_free() for cleanup
Socket_sendfd() for passing fds over Unix sockets
man socketpair(2) for low-level details
SocketProxy_config_defaults()
void SocketProxy_config_defaults (SocketProxy_Config * config) extern
Initialize proxy configuration with safe default values.
Parameters
config Pointer to configuration structure to populate.
Sets type to SOCKET_PROXY_NONE, clears strings and headers to NULL, sets default ports implicitly via type, and applies module default timeouts. For HTTPS proxies, tls_ctx remains NULL (uses secure defaults if needed).
Thread Safety\n Yes - pure function, no shared state.
See also
SocketProxy_Config for field details.
SocketProxy_parse_url() for URL-based initialization.
docs/PROXY.md for configuration best practices.
Referenced by main().
SocketProxy_Conn_cancel()
void SocketProxy_Conn_cancel (SocketProxy_Conn_T conn) extern
Cancel ongoing proxy connection and cleanup resources.
Parameters
conn Proxy connection context to cancel.
Immediately aborts operation: closes socket, cancels DNS/timers, transitions to PROXY_STATE_CANCELLED and PROXY_ERROR_CANCELLED. Safe to call from any state; idempotent.
Use to gracefully stop long-running operations or handle app shutdown. After cancel, SocketProxy_Conn_poll() will return true; result is CANCELLED. SocketProxy_Conn_socket() returns NULL.
Thread Safety\n No - modifies connection state and closes shared socket.
Note
Does not block; asynchronous cleanup via poll if needed.
Resources freed on next process or free; call free soon after.
Warning
Cancelling mid-handshake may leave proxy in inconsistent state.
See also
SocketProxy_Conn_free() for complete cleanup (auto-cancels if pending).
SocketProxy_Conn_result() will return PROXY_ERROR_CANCELLED.
docs/ASYNC_IO.md for cancellation patterns in event loops.
SocketProxy_Conn_error()
const char * SocketProxy_Conn_error (SocketProxy_Conn_T conn) extern
Retrieve human-readable error description for failed operations.
Parameters
conn Proxy connection context in FAILED state.
Returns
Const string describing failure (e.g., "Authentication failed"), or NULL if not in FAILED state or no specific message. String allocated from internal arena; valid until SocketProxy_Conn_free().
Provides diagnostic details beyond SocketProxy_Conn_result() code, including protocol responses, system errors, or timeout reasons. Intended for logging; not for programmatic error handling (use result code).
Thread Safety\n No - borrowed reference to internal string buffer.
Note
String may be truncated for long errors; use for display/logging.
Cleared on cancel or success; check state first.
Warning
Do not free or modify returned string; internal ownership.
See also
SocketProxy_Conn_result() for structured error code.
SocketProxy_Conn_state() to confirm FAILED state.
SocketLog_emit() for logging this error.
docs/LOGGING.md for error logging best practices.
SocketProxy_Conn_events()
unsigned SocketProxy_Conn_events (SocketProxy_Conn_T conn) extern
Get poll event mask for current connection phase.
Parameters
conn Proxy connection context.
Returns
Bitmask of SocketPoll_Events (POLL_READ | POLL_WRITE | POLL_ERROR) required for current state (e.g., READ for response, WRITE for request). 0 if no polling needed (terminal states).
Dynamically updates based on state: e.g., WRITE during send phases, READ during recv. Use with SocketPoll_mod() to update registration.
Thread Safety\n No - reflects current I/O direction.
Note
Compatible with SocketPoll events.
Call before/after state changes or process to refresh mask.
Warning
Incorrect events may stall or error the handshake.
See also
SocketProxy_Conn_fd() to get FD for registration.
SocketPoll_mod() for updating event mask.
Event System for polling mechanics.
SocketProxy_Conn_fd()
int SocketProxy_Conn_fd (SocketProxy_Conn_T conn) extern
Get underlying file descriptor for poll integration.
Parameters
conn Proxy connection context.
Returns
Socket FD to monitor with SocketPoll_add(), or -1 if no active socket (init, completed, or failed state).
For custom poll loops: add this FD with SocketProxy_Conn_events() mask. Context auto-manages registration if using internal poll, but expose for external or multi-poll scenarios. FD valid while in progress states; deregister on completion/cancel.
Thread Safety\n No - FD may change or close concurrently.
Note
FD is non-blocking after initial connect.
Use Socket_get_fd() on extracted socket post-success for app polling.
Warning
Do not close or modify FD directly; use conn methods.
See also
SocketProxy_Conn_events() for required event mask.
SocketPoll_add() for registration example.
Poll module for FD management.
SocketProxy_Conn_free()
void SocketProxy_Conn_free (SocketProxy_Conn_T * conn) extern
Release proxy connection context and associated resources.
Parameters
conn Pointer to SocketProxy_Conn_T (set to NULL on success).
Frees all allocated resources: socket, internal buffers, timers, DNS requests. If operation pending, auto-cancels first (closes socket, signals completion). Idempotent and null-safe: handles NULL pointer or already-freed context.
Call after successful socket extraction or on error/cancel. For internal resources (from SocketProxy_Conn_new()), fully self-contained. For external (SocketProxy_Conn_start()), does not free user-provided dns/poll.
Thread Safety\n No - frees shared state; avoid concurrent access.
Note
Follows Arena-managed pattern but uses internal arena for most allocs.
Socket ownership: If not extracted via SocketProxy_Conn_socket(), socket auto-closed here.
Warning
Do not access conn after free; undefined behavior.
See also
SocketProxy_Conn_socket() before free to transfer socket ownership.
SocketProxy_Conn_cancel() for explicit abort without full free.
Arena module for memory management context.
docs/MEMORY_MANAGEMENT.md for resource lifecycle guidelines.
SocketProxy_Conn_new()
SocketProxy_Conn_T SocketProxy_Conn_new (const SocketProxy_Config * proxy, const char * target_host, int target_port) extern
Create proxy connection context with blocking proxy connect, async handshake.
Parameters
proxy Proxy configuration (copied; strings borrowed).
target_host Target hostname or IP for tunneling.
target_port Target port (1-65535).
Returns
New SocketProxy_Conn_T on success, NULL on failure.
Exceptions
SocketProxy_Failed on config validation or initial resource allocation failure.
Thread Safety\n Yes - creates isolated instance with internal resources.
Convenience wrapper for simpler async integration: performs blocking TCP connect and DNS resolution to proxy server (up to connect_timeout_ms), then switches to non-blocking mode for handshake, TLS, auth via internal poll/timer/DNS instances.
Unlike SocketProxy_Conn_start(), this blocks briefly for proxy reachability but allows event-driven completion of protocol negotiation.
Post-init usage same as async API:
Poll loop: process events SocketProxy_Conn_process() check completion
On done: SocketProxy_Conn_socket() transfers ownership, then free conn
Internal resources auto-managed; no external dns/poll required from caller.
Note
Blocks only for proxy connect phase; handshake fully async.
Suitable for apps with existing event loops but wanting quick proxy validation.
Warning
Still requires poll integration for full non-blocking after connect.
Internal poll uses epoll/kqueue; ensure compatible with app loop.
See also
SocketProxy_Conn_start() for fully non-blocking from start (requires external resources).
SocketProxy_connect() for fully synchronous end-to-end.
SocketProxy_Conn_process() and friends for runtime management.
Event System for poll backend details.
docs/PROXY.md#hybrid-api for hybrid sync/async patterns.
SocketProxy_Conn_next_timeout_ms()
int SocketProxy_Conn_next_timeout_ms (SocketProxy_Conn_T conn) extern
Calculate milliseconds until next internal timeout.
Parameters
conn Proxy connection context.
Returns
Positive: ms until timeout expiry (use for poll timeout). 0: Immediate timeout pending (process urgently). -1: No timeout active (poll indefinitely or use defaults).
Accounts for connect_timeout_ms, handshake_timeout_ms, and internal timers. Decrements in real-time; call periodically in loop for accuracy. Helps prevent unnecessary busy-polling while respecting deadlines.
Thread Safety\n No - based on volatile monotonic time.
Note
Uses Socket_get_monotonic_ms() for precise timing.
Negative values indicate expired timeout (error imminent).
Warning
Stale calls may lead to missed deadlines; refresh often.
See also
SocketPoll_wait() - pass this value as timeout param.
SocketTimeout Utilities in SocketUtil for advanced timing.
docs/TIMEOUTS.md for timeout configuration and behavior.
SocketProxy_Conn_poll()
int SocketProxy_Conn_poll (SocketProxy_Conn_T conn) extern
Query if proxy operation has completed.
Parameters
conn Proxy connection context to check.
Returns
1 if operation finished (CONNECTED, FAILED, or CANCELLED state), 0 if still in progress.
Call after SocketProxy_Conn_process() in event loop to detect completion. On true, check SocketProxy_Conn_state() or SocketProxy_Conn_result() for outcome.
Thread Safety\n No - reads shared connection state.
See also
SocketProxy_Conn_state() for detailed status.
SocketProxy_Conn_result() for error/success code.
SocketProxy_Conn_socket() to retrieve tunneled socket on success.
SocketProxy_Conn_process()
void SocketProxy_Conn_process (SocketProxy_Conn_T conn) extern
Advance asynchronous proxy connection state machine.
Parameters
conn Proxy connection context to process.
Call this after detecting events on SocketProxy_Conn_fd() via your poll loop. Performs non-blocking I/O: reads/writes protocol messages, handles timeouts, advances through handshake phases (TLS, auth, connect response).
May transition state and potentially complete operation; always follow with SocketProxy_Conn_poll() to check.
Does nothing if no events pending or in terminal state.
Thread Safety\n No - modifies connection state and socket buffers.
Note
Integrates with SocketPoll; deregisters FD on completion/close.
Warning
Must call promptly after events to avoid protocol timeouts.
Not for synchronous use; pair with event-driven polling.
See also
SocketProxy_Conn_fd() and SocketProxy_Conn_events() for poll setup.
SocketProxy_Conn_poll() to check post-process completion.
Poll module for event handling examples.
SocketProxy_Conn_result()
SocketProxy_Result SocketProxy_Conn_result (SocketProxy_Conn_T conn) extern
Get final result code after operation completion.
Parameters
conn Completed proxy connection context.
Returns
SocketProxy_Result indicating outcome (PROXY_OK on success, error code on failure).
Valid only after SocketProxy_Conn_poll() returns 1 (terminal state). Provides protocol-specific error mapping for debugging and retry logic. On success, socket available via SocketProxy_Conn_socket().
Thread Safety\n No - reads result stored in connection state.
See also
SocketProxy_Result for code meanings.
SocketProxy_result_string() for descriptive strings.
SocketProxy_Conn_error() for additional error details.
docs/ERROR_HANDLING.md for error categorization and recovery.
SocketProxy_Conn_socket()
Socket_T SocketProxy_Conn_socket (SocketProxy_Conn_T conn) extern
Extract successfully tunneled socket from completed context.
Parameters
conn Proxy connection context (must be in CONNECTED state).
Returns
On success (PROXY_OK and CONNECTED): Socket_T tunneled to target. Ownership transferred to caller; must Socket_free() after use. Otherwise: NULL (failed, cancelled, or pending).
Call only after SocketProxy_Conn_poll() returns true and result is PROXY_OK. Detaches socket from context; subsequent calls return NULL. Socket is non-blocking, connected, and ready for app I/O or TLS handshake.
Thread Safety\n No - transfers ownership and clears internal reference.
Note
Socket retains proxy tunnel; transparent to application.
Warning
Calling on non-success states leaks no resources but returns NULL.
Free context after extraction to avoid double-free.
See also
SocketProxy_Conn_result() to verify success before extraction.
SocketProxy_Conn_free() after successful socket transfer.
Socket.h for socket operations post-tunnel.
TLS module for HTTPS target handshakes.
SocketProxy_Conn_start()
SocketProxy_Conn_T SocketProxy_Conn_start (SocketDNS_T dns, SocketPoll_T poll, const SocketProxy_Config * proxy, const char * target_host, int target_port) extern
Initialize and start fully asynchronous proxy tunneling operation.
Parameters
dns Caller-provided SocketDNS_T instance for proxy server resolution. Must remain valid and operational during entire operation.
poll Caller-provided SocketPoll_T for event notifications. Connection FD auto-registered; must not be freed prematurely.
proxy Proxy configuration (copied internally; strings borrowed).
target_host Target hostname or IP to tunnel connection to.
target_port Target TCP port number (1-65535).
Returns
New SocketProxy_Conn_T context on success, NULL on init failure.
Exceptions
SocketProxy_Failed on invalid config or resource allocation error.
Thread Safety\n No - context tied to specific dns/poll instances; single-thread
use.
This low-level API provides complete control for integrating proxy tunneling into custom event loops. It uses provided DNS for non-blocking resolution and poll for I/O events. No blocking calls after initialization.
Integration pattern:
Register conn->fd with poll if not auto-registered.
Loop: SocketPoll_wait() SocketProxy_Conn_process() check SocketProxy_Conn_poll()
On completion: Extract socket with SocketProxy_Conn_socket(), then free conn.
Cleanup: SocketProxy_Conn_cancel() or free during progress.
Handles: DNS resolution, TCP connect (HappyEyeballs), TLS (HTTPS), handshake, auth, error recovery within timeouts.
Note
dns and poll ownership remains with caller; conn does not free them.
Context internally manages timers via poll; no external SocketTimer needed.
Warning
Failure to process events promptly may cause timeouts or stalls.
Cancel or free during active state closes underlying socket.
See also
SocketProxy_Conn_process() for advancing state machine.
SocketProxy_Conn_poll() for completion check.
SocketProxy_Conn_next_timeout_ms() for poll timeout calculation.
Event System for poll integration examples.
DNS module for async resolution details.
docs/ASYNC_IO.md for full event loop patterns.
docs/PROXY.md#async-api for advanced async features.
SocketProxy_Conn_state()
SocketProxy_State SocketProxy_Conn_state (SocketProxy_Conn_T conn) extern
Retrieve current state of proxy connection.
Parameters
conn Proxy connection context.
Returns
Current SocketProxy_State (e.g., CONNECTING_PROXY, CONNECTED).
Use for logging, UI updates, or conditional logic during async progress. Valid states reflect real-time progress through connection phases.
Thread Safety\n No - reads volatile internal state.
See also
SocketProxy_State enumeration for state details and transitions.
SocketProxy_Conn_poll() to check if terminal state reached.
SocketProxy_state_string() for human-readable state name.
SocketProxy_connect()
Socket_T SocketProxy_connect (const SocketProxy_Config * proxy, const char * target_host, int target_port) extern
Establish synchronous connection to target via proxy tunnel.
Parameters
proxy Configuration specifying proxy type, server, auth, etc.
target_host Target hostname or IP address to tunnel to.
target_port Target TCP port (valid range: 1-65535).
Returns
On success: new Socket_T connected through proxy to target. Caller must Socket_free() when done. On failure: NULL, with SocketProxy_Failed raised.
Exceptions
SocketProxy_Failed on proxy connection, handshake, or auth failure. Specific causes available via last error if using async variant.
Thread Safety\n Yes - creates independent socket and resources.
This convenience function handles full lifecycle:
Socket creation (TCP)
DNS resolution and connection to proxy (via HappyEyeballs for speed)
Optional TLS to proxy (HTTPS proxy type)
Protocol handshake (CONNECT or SOCKS)
Returns tunneled socket ready for immediate use.
Blocking behavior: May block up to config timeouts for connect + handshake. For non-blocking, use SocketProxy_Conn_new() or SocketProxy_Conn_start().
Post-success: Socket is in connected state to target; application can immediately perform SocketTLS_handshake() for HTTPS targets or send data.
Warning
Config strings must outlive the returned socket.
No connection reuse or pooling; new socket per call.
See also
SocketProxy_tunnel() for existing socket tunneling.
SocketProxy_Conn_new() for async version.
Async I/O module for event-driven alternatives.
DNS module for resolution details.
docs/PROXY.md for proxy-specific behaviors and limitations.
docs/SECURITY.md for TLS and auth Security Modules considerations.
Referenced by main().
socketproxy_do_recv()
int socketproxy_do_recv (struct SocketProxy_Conn_T * conn) extern
Receive protocol data into conn->recv_buf.
Parameters
conn Proxy connection context.
Uses Socket_recv or SocketTLS_recv to fill recv_buf from recv_offset, handles partial receives. Appends to existing data.
Returns
>0 bytes received, 0 EOF, -1 error (EAGAIN returns -1 but ok, check errno).
Note
Updates recv_len, handles TLS if enabled.
See also
SocketProxy_Conn_T::recv_buf, ::recv_len, ::recv_offset
socketproxy_advance_state() after successful recv.
socketproxy_do_send()
int socketproxy_do_send (struct SocketProxy_Conn_T * conn) extern
Send pending protocol data from conn->send_buf.
Parameters
conn Proxy connection context.
Uses Socket_send or SocketTLS_send (if TLS) to send remaining bytes, updates send_offset. Handles partial sends (non-blocking).
Returns
0 all sent, 1 partial (EAGAIN), -1 error (sets errno, may raise).
Note
Handles TLS if conn->tls_enabled.
See also
SocketProxy_Conn_T::send_buf, ::send_len, ::send_offset
socketproxy_advance_state() called after full send.
socketproxy_elapsed_ms()
static int64_t socketproxy_elapsed_ms (int64_t start_ms) inline static
Calculate elapsed time since start in milliseconds.
Parameters
start_ms Start time from socketproxy_get_time_ms().
Computes current time - start_ms, clamping to 0 if negative (clock issues).
Returns
Non-negative elapsed milliseconds.
Note
Thread-safe: Yes, as it calls thread-safe functions.
See also
socketproxy_get_time_ms() for obtaining timestamps.
Socket_get_monotonic_ms() alternative in SocketUtil.h.
Definition at line 718 of file SocketProxy-private.h.
References socketproxy_get_time_ms().
socketproxy_get_time_ms()
static int64_t socketproxy_get_time_ms (void) inline static
Get current monotonic time in milliseconds.
Uses CLOCK_MONOTONIC for reliable, non-decreasing time suitable for timeouts.
Returns
Monotonic time since some unspecified point (ms), or 0 on clock failure.
Note
Thread-safe: Yes, clock_gettime is atomic.
Prefer over gettimeofday() to avoid system time changes affecting timeouts.
See also
socketproxy_elapsed_ms() for elapsed time calculation.
SocketUtil.h "Timeout Utilities" for related functions.
Definition at line 692 of file SocketProxy-private.h.
References SOCKET_PROXY_MS_PER_SEC, and SOCKET_PROXY_NS_PER_MS.
Referenced by socketproxy_elapsed_ms().
socketproxy_parse_hostport()
int socketproxy_parse_hostport (const char * start, SocketProxy_Config * config, Arena_T arena, size_t * consumed_out) extern
Parse [host]:port from URL, handling IPv6 literals.
Parameters
start Start of host/port section (after userinfo@).
[out] config Output, sets proxy_host and proxy_port (default per type).
arena Arena for host copy; NULL uses static.
[out] consumed_out Optional: bytes parsed (including port).
Parses host (domain/IPv4/IPv6), optional :port (defaults: 1080 socks, 8080 http). Validates port range, copies host to arena or static buf.
Returns
0 success, -1 invalid host/port.
Note
IPv6 requires [] brackets.
See also
SocketProxy_Config::proxy_host, ::proxy_port
socket_util_arena_strdup() for copying.
socketproxy_parse_scheme()
int socketproxy_parse_scheme (const char * url, SocketProxy_Config * config, const char ** end) extern
Helper functions for parsing proxy URLs.
Parses proxy://userinfo@host:port format into config. Supports socks4://, socks5://, http:// schemes.
See also
SocketProxy_Config for output structure.
socketproxy_parse_scheme(), parse_userinfo(), parse_hostport().
Parse proxy URL scheme and set type.
Parameters
url Input URL string (e.g., "socks5://proxy.example.com").
[out] config Output config, sets type based on scheme.
[out] end Pointer after parsed scheme:// (for next parse step).
Recognizes "socks4", "socks5", "http"; sets SOCKET_PROXY_SOCKS4 etc.
Returns
0 on success, -1 on unknown scheme (sets errno EINVAL).
See also
SocketProxyType enum values.
SocketProxy_Config::type
SocketProxy_parse_url()
int SocketProxy_parse_url (const char * url, SocketProxy_Config * config, Arena_T arena) extern
Parse proxy URL string into configuration structure.
Parameters
url Null-terminated proxy URL string.
config Output: populated configuration structure.
arena Optional arena for allocating parsed strings (host, user, pass). If NULL, uses thread-local static buffer (overwritten on next call).
Returns
0 on successful parse, -1 on invalid URL format or allocation failure.
Supported schemes (case-insensitive):
http://[user:pass@]host[:port] (HTTP CONNECT)
https://[user:pass@]host[:port] (HTTPS CONNECT, requires TLS)
socks4://host[:port] (SOCKS4)
socks4a://host[:port] (SOCKS4a)
socks5://[user:pass@]host[:port] (SOCKS5)
socks5h://[user:pass@]host[:port](SOCKS5 hostname resolution)
Port defaults: HTTP/HTTPS=8080, SOCKS=1080. Userinfo parsing supports % encoding; passwords securely handled. Does not support IPv6 literals in URL (use hostname or SocketDNS).
Thread safety: Conditional. Safe if arena provided and thread-safe; static buffer is per-thread if no arena.
See also
SocketProxy_config_defaults() for manual initialization.
SocketProxy_Config for field ownership rules.
docs/PROXY.md#url-format for extended URL features.
Arena module for memory management.
Referenced by main().
socketproxy_parse_userinfo()
int socketproxy_parse_userinfo (const char * start, SocketProxy_Config * config, Arena_T arena, const char ** end) extern
Parse optional [user[:pass]@] from URL.
Parameters
start Start of potential userinfo (after scheme://).
[out] config Output, sets username/password if present.
arena Arena for strdup copies; NULL uses static buffer (non-thread-safe).
[out] end Updated to after @ or start if none.
Supports basic auth parsing; URL-decodes if needed? (simple colon split).
Returns
0 success (found or not), -1 parse error (long creds).
See also
SocketProxy_Config::username, ::password
Arena_T for memory management.
SocketProxy_result_string()
const char * SocketProxy_result_string (SocketProxy_Result result) extern
Convert SocketProxy_Result code to descriptive string.
Parameters
result Result code to stringify.
Returns
Static const char* (e.g., "PROXY_OK", "PROXY_ERROR_AUTH_FAILED"). Never NULL; valid for all valid codes.
Utility for logging, debugging, or user-facing error messages. Strings are interned static; no allocation.
Thread Safety\n Yes - static read-only strings.
See also
SocketProxy_Conn_result() for runtime result retrieval.
SocketProxy_Result enum for code list.
docs/LOGGING.md for integration with SocketLog.
SocketProxy_state_string()
const char * SocketProxy_state_string (SocketProxy_State state) extern
Convert SocketProxy_State to descriptive string.
Parameters
state State enum value to stringify.
Returns
Static const char* (e.g., "PROXY_STATE_CONNECTED", "PROXY_STATE_FAILED"). Never NULL; covers all states.
For debugging, logging, or state machine visualization. Compact format suitable for trace output.
Thread Safety\n Yes - static constants.
See also
SocketProxy_Conn_state() to get current state.
SocketProxy_State enum for state documentation.
SocketProxy_tunnel()
SocketProxy_Result SocketProxy_tunnel (Socket_T socket, const SocketProxy_Config * proxy, const char * target_host, int target_port, Arena_T arena) extern
Perform proxy handshake on pre-connected socket to establish tunnel.
Parameters
socket Pre-connected Socket_T to proxy server (non-blocking recommended).
proxy Proxy configuration (type, auth, headers, timeouts). Host/port must match socket connection.
target_host Target hostname/IP to request tunnel for (sent to proxy).
target_port Target port to request (1-65535).
arena Optional arena for temporary allocations (e.g., TLS context, buffers). If NULL, uses internal arena (limited lifetime).
Returns
PROXY_OK on success (tunnel established), other SocketProxy_Result on failure. Socket remains owned by caller; state updated for tunneling.
Exceptions
SocketProxy_Failed on handshake, auth, or protocol errors.
Thread Safety\n No - modifies socket state and uses shared internal resources.
Use this for custom connection flows (e.g., connection pooling, custom DNS). Assumes socket already connected to proxy->host:proxy->port via Socket_connect() or equivalent. Performs:
Optional TLS handshake (HTTPS proxy)
Protocol-specific handshake (CONNECT, SOCKS request/response)
Authentication subnegotiation (SOCKS5)
For HTTPS proxies: If proxy->tls_ctx NULL and arena provided, auto-creates secure TLS context. Without arena or tls_ctx, fails with PROXY_ERROR.
On success: Socket ready for read/write to target (proxy-transparent). On failure: Socket may be closed; check SocketProxy_Result for details.
Warning
Socket must not be shared across threads during call.
Config and arena must outlive the operation.
For async, use SocketProxy_Conn_start() with external poll/DNS.
See also
SocketProxy_connect() for full synchronous connection (socket creation included).
SocketProxy_Config for TLS and timeout config.
Security module for HTTPS Proxy Tunneling Module TLS requirements.
docs/PROXY.md#custom-socket for advanced usage examples.
SocketProxy_type_string()
const char * SocketProxy_type_string (SocketProxyType type) extern
Convert proxy type enum to protocol name string.
Parameters
type SocketProxyType enum value.
Returns
Static const char* describing protocol (e.g., "HTTP CONNECT", "SOCKS5", "none"). Never NULL; user-friendly for logs/UI.
Examples:
SOCKET_PROXY_HTTP "HTTP CONNECT"
SOCKET_PROXY_SOCKS5 "SOCKS5"
SOCKET_PROXY_NONE "direct"
Thread Safety\n Yes - static strings.
See also
SocketProxyType enum for supported types.
SocketProxy_Config::type for runtime configuration.
docs/PROXY.md for type-specific protocol details.
SocketUnix_bind()
void SocketUnix_bind (SocketBase_T base, const char * path, Except_T exc_type) extern
Bind Unix domain socket to a filesystem path.
Parameters
base The socket base structure containing the file descriptor and domain.
path Null-terminated string specifying the Unix socket path.
exc_type Exception type to raise on failure.
Exceptions
exc_type On bind errors such as EADDRINUSE, ENOENT, or EACCES.
Internal helper function that performs Unix domain socket binding. Validates the path and calls bind(2) system call. Supports both filesystem paths and abstract sockets (Linux).
See also
Socket_bind_unix() for the public high-level interface.
SocketUnix_connect() for the connect counterpart.
SocketUnix_validate_unix_path() for path validation.
Thread Safety\n Conditional - safe if base fd is not shared across threads
without locking.
SocketUnix_connect()
void SocketUnix_connect (SocketBase_T base, const char * path, Except_T exc_type) extern
Connect Unix domain socket to a filesystem path.
Parameters
base The socket base structure containing the file descriptor and domain.
path Null-terminated string specifying the remote Unix socket path.
exc_type Exception type to raise on failure.
Exceptions
exc_type On connect errors such as ECONNREFUSED, ENOENT, or EACCES.
Internal helper function that performs Unix domain socket connection. Validates the path and calls connect(2) system call. Supports both filesystem paths and abstract sockets (Linux).
See also
Socket_connect_unix() for the public high-level interface.
SocketUnix_bind() for the bind counterpart.
SocketUnix_validate_unix_path() for path validation.
Thread Safety\n Conditional - safe if base fd is not shared across threads
without locking.
SocketUnix_validate_unix_path()
int SocketUnix_validate_unix_path (const char * path, size_t path_len) extern
Validate a Unix domain socket path.
Parameters
path The path string to validate.
path_len Length of the path string (excluding null terminator).
Returns
1 if the path is valid for Unix socket operations, 0 otherwise.
Checks path constraints:
Length <= UNIX_PATH_MAX (typically 108 bytes)
Not empty
Supports abstract socket prefix (\0 on Linux)
Used by bind and connect helpers to ensure valid paths before system calls.
See also
SocketUnix_bind()
SocketUnix_connect()
Thread Safety\n Yes - pure function, no side effects.
Variable Documentation
base
SocketDgram_T::base
Private structure for SocketDgram_T opaque type.
Private structure for SocketDgram_T opaque type.
Embeds SocketBase_T for common socket fields (fd, arena, endpoints, timeouts, metrics). Includes conditional DTLS fields when #SOCKET_HAS_TLS is enabled, providing support for secure datagram encryption parallel to TLS in Socket_T.
Common base structure shared with other socket types. Contains file descriptor, memory arena, local/remote addresses, timeouts, and metrics tracking.
Note
This structure is not part of the public API and may change without notice. Additional datagram-specific fields (e.g., multicast state) can be added here.
See also
SocketDgram.h for public interface.
SocketCommon-private.h for SocketBase_T details.
Socket-private.h for stream socket equivalent.
SocketDTLS.h for DTLS fields usage (if enabled).
Embeds SocketBase_T for common socket fields (fd, arena, endpoints, timeouts, metrics). Includes conditional DTLS fields when #SOCKET_HAS_TLS is enabled, providing support for secure datagram encryption parallel to TLS in Socket_T.
Common base structure shared with other socket types. Contains file descriptor, memory arena, local/remote addresses, timeouts, and metrics tracking.
Note
This structure is not part of the public API and may change without notice. Additional datagram-specific fields (e.g., multicast state) can be added here.
See also
SocketDgram.h for public interface.
SocketCommon-private.h for SocketBase_T details.
Socket-private.h for stream socket equivalent.
SocketDTLS.h for DTLS fields usage (if enabled).
Definition at line 45 of file SocketDgram-private.h.
Socket_Closed
const Except_T Socket_Closed extern
Connection closed by peer exception.
Category: NETWORK Retryable: Yes - indicates graceful close or reset, reconnect may succeed
Raised when:
recv() returns 0 (graceful close)
ECONNRESET during I/O (connection reset)
EPIPE during send (broken pipe)
This is a normal condition for connection-oriented sockets.
See also
Socket_recv() for read operations that may raise this.
Socket_send() for write operations that may raise this.
Referenced by handle_client_data().
Socket_Failed [1/3]
const Except_T Socket_Failed extern
General socket operation failure exception.
Indicates failure in any socket-related system call or library operation. This is the primary exception for most Socket_T API errors.
Error Category:
NETWORK: Transient issues like timeouts, resets, unreachable hosts
PROTOCOL: Invalid configuration or state (e.g., bind on used port)
SYSTEM: Resource exhaustion or permission issues
Retryability: Use Socket_error_is_retryable(Socket_geterrno()) to determine if safe to retry the operation. Examples:
Retryable: ECONNREFUSED, ETIMEDOUT, EAGAIN
Non-retryable: EACCES, EINVAL, EMFILE
Always check Socket_geterrno() and Socket_GetLastError() in EXCEPT block for details.
Common triggers:
socket(2), bind(2), listen(2), accept(4), connect(2) failures
send(2), recv(2), sendmsg(2), recvmsg(2) errors
setsockopt(2), getsockopt(2) failures
Internal allocation failures (ENOMEM)
See also
Socket_geterrno() to retrieve errno value
Socket_GetLastError() for human-readable error string
Socket_error_is_retryable() to check if operation can be retried
Handling Example
TRY {
    Socket_T sock = Socket_new(AF_INET, SOCK_STREAM, 0);
    Socket_connect(sock, "invalid-host", 80);
} EXCEPT(Socket_Failed) {
    int err = Socket_geterrno();
    if (Socket_error_is_retryable(err)) {
        SOCKET_LOG_WARN_MSG("Retryable socket error %d: %s", err,
Socket_GetLastError());
        // Implement backoff and retry logic
    } else {
        SOCKET_LOG_ERROR_MSG("Fatal socket error %d: %s", err,
Socket_GetLastError());
        // Abort or fallback
    }
} END_TRY;
Note
errno is preserved thread-locally; safe in multithreaded contexts
Use Socket_safe_strerror() for safe strerror() wrapper
Warning
Do not assume all Socket_Failed are network errors - check errno
In non-blocking mode, EAGAIN may not raise exception (returns 0 instead)
See also
Socket_Closed for peer disconnection cases
SocketUnix_Failed for Unix-specific errors
Referenced by handle_client_data(), main(), and main().
Socket_Failed [2/3]
const Except_T Socket_Failed extern
Module Exception Forward Declarations.
Forward declarations of module-specific exception types (Except_T) for use in internal implementations. Enables consistent error raising across Socket, SocketDgram, and common utilities without per-file definitions.
These exceptions are also exposed publicly in SocketCommon.h for application-level TRY/EXCEPT handling. Definitions provided in respective .c source files.
Exception Usage Pattern
SOCKET_DECLARE_MODULE_EXCEPTION(SocketCommon);  // In .c file
// Raising
SOCKET_RAISE_FMT(SocketCommon, SocketCommon_Failed, "resolve failed: %s",
gai_strerror(err));
Category and Retryability
All socket exceptions:
Category: NETWORK (system calls) or APPLICATION (validation)
Retryable: Use SocketError_is_retryable_errno(Socket_geterrno()) to check
Details: Available via Socket_GetLastError(), Socket_geterrno()
Note
Thread-safe: Yes (Except_T is value type, stack-based)
See also
core/Except.h for TRY/EXCEPT/FINALLY/END_TRY macros and Except_T details
SOCKET_DECLARE_MODULE_EXCEPTION() and SOCKET_RAISE_* macros in internal headers
docs/ERROR_HANDLING.md for comprehensive exception patterns and best practices
SocketError_categorize_errno() for automatic categorization
Generic socket operation failure exception.
Raised for core socket operations failures: socket(2), bind(2), connect(2), listen(2), accept(2), send/recv family, Unix domain ops, option setting.
Common Triggers
System resource exhaustion (EMFILE, ENFILE, ENOBUFS)
Permission issues (EACCES, EPERM)
Address errors (EADDRINUSE, EADDRNOTAVAIL, EINVAL)
Connection issues (ECONNREFUSED, ETIMEDOUT, ECONNRESET)
Category: NETWORK Retryable: Yes for transient errors (use SocketError_is_retryable_errno())
See also
Socket.h for TCP-specific details
SocketDgram.h for UDP details
Socket_geterrno() for underlying errno
Socket_Failed [3/3]
const Except_T Socket_Failed extern
General TCP socket operation failure exception.
See Socket.h for detailed documentation on when this is raised, retryability, and error categorization.
See also
Socket_Failed in Socket.h for full details.
SocketBuf_Failed
const Except_T SocketBuf_Failed extern
Exception indicating failure in buffer operations such as allocation or resize errors.
Raised when internal buffer operations fail due to memory exhaustion, invalid parameters, or other runtime errors.
See also
SocketBuf_new() for allocation failure cases.
SocketBuf_reserve() for resize failure cases.
Except_T for exception handling framework.
docs/ERROR_HANDLING.md for TRY/EXCEPT usage patterns.
SocketCommon_Failed [1/2]
const Except_T SocketCommon_Failed extern
Shared utility function failure exception.
For errors in common utilities: address resolution (getaddrinfo), hostname/port validation, iovec calculations/advances, option setting helpers, endpoint caching.
Common Triggers
DNS resolution timeouts/failures (gai errors)
Invalid input (bad port, too-long hostname, iov overflow)
Option setting failures (setsockopt EINVAL, ENOPROTOOPT)
Memory allocation in helpers (via Arena_Failed chaining)
Category: NETWORK or APPLICATION Retryable: Yes for network transients, no for validation errors
See also
SocketCommon_resolve_address() for resolution errors
SocketCommon_validate_port() and validate_hostname() for input validation
SocketCommon_calculate_total_iov_len() for iovec ops
SocketCommon_Failed [2/2]
const Except_T SocketCommon_Failed extern
General failure in shared socket common utilities.
Category: NETWORK or APPLICATION Retryable: Depends on errno - use Socket_error_is_retryable() to check
Raised for errors in common functions such as:
Address resolution failures (getaddrinfo errors)
Hostname/port validation failures
Socket option setting failures (setsockopt)
iovec manipulation errors (overflow, invalid parameters)
Bind/connect helper failures
Multicast join/leave errors
Always check errno via Socket_geterrno() for specific error details.
See also
Socket_resolve_address() for address resolution that may raise this.
SocketCommon_validate_port() for port validation.
SocketCommon_set_option_int() for option setting.
SocketCommon_calculate_total_iov_len() for iovec operations.
Socket_error_is_retryable() for retry decisions.
Socket_geterrno() for error code access.
docs/ERROR_HANDLING.md for exception handling patterns.
SocketDgram_Failed [1/2]
const Except_T SocketDgram_Failed extern
Datagram/UDP-specific operation failure exception.
Specific to UDP/SocketDgram operations: sendto(2)/recvfrom(2), multicast join/leave, broadcast enable, TTL setting, connected UDP mode.
Common Triggers
Multicast errors (invalid group, permission denied)
Broadcast without SO_BROADCAST
TTL/hop limit out of range
Datagram too large (EMSGSIZE)
Category: NETWORK Retryable: Depends on errno - check SocketError_is_retryable_errno()
See also
SocketDgram.h for full UDP API documentation
SocketCommon_join_multicast() for multicast-specific errors
Referenced by main().
SocketDgram_Failed [2/2]
const Except_T SocketDgram_Failed extern
General UDP/datagram socket operation failure exception.
Raised for errors specific to datagram sockets such as:
Invalid multicast group addresses
Broadcast permission failures
TTL/hop limit setting errors
Category: NETWORK Retryable: Depends on errno
See also
SocketDgram.h for detailed documentation.
Socket_error_is_retryable() for retryability checking.
SocketProxy_Failed
const Except_T SocketProxy_Failed extern
Exception raised on general proxy operation failures.
Thrown when proxy connection establishment, authentication, or handshake fails for any reason. For detailed error information in asynchronous operations, query SocketProxy_Conn_result() after completion.
See also
SocketProxy_Conn_result() for specific SocketProxy_Result codes.
SocketProxy_Failed for common triggers like network errors, authentication failures, or protocol violations.
docs/ERROR_HANDLING.md for exception handling guidelines.
Referenced by main().
SocketUnix_Failed
const Except_T SocketUnix_Failed extern
Unix domain socket operation failure.
Category: NETWORK or APPLICATION Retryable: Depends on errno
Raised for Unix domain socket specific errors:
Path too long
Socket file doesn't exist (ENOENT)
Permission denied (EACCES)