Tetsuo Pulse: http_post.c File Reference
http_post.c File Reference
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "core/Except.h"
#include "http/SocketHTTPClient.h"
Functions
int main (int argc, char **argv)
Variables
static const char * json_payload
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 35 of file http_post.c.
References SocketHTTPClient_Response::body, SocketHTTPClient_Response::body_len, END_TRY, EXCEPT, FINALLY, HTTP_METHOD_POST, json_payload, SocketHTTPClient_ConnectFailed, SocketHTTPClient_DNSFailed, SocketHTTPClient_Failed, SocketHTTPClient_free(), SocketHTTPClient_json_post(), SocketHTTPClient_new(), SocketHTTPClient_post(), SocketHTTPClient_Request_body(), SocketHTTPClient_Request_execute(), SocketHTTPClient_Request_free(), SocketHTTPClient_Request_header(), SocketHTTPClient_Request_new(), SocketHTTPClient_Request_timeout(), SocketHTTPClient_Response_free(), SocketHTTPClient_Timeout, SocketHTTPClient_TLSFailed, SocketHTTPClient_Response::status_code, and TRY.
Variable Documentation
json_payload
const char* json_payload static
Initial value:
= "{\n"
                                  "  \"name\": \"Socket Library\",\n"
                                  "  \"version\": \"1.0.0\",\n"
                                  "  \"features\": [\"HTTP/1.1\", \"HTTP/2\", "
                                  "\"WebSocket\", \"TLS 1.3\"]\n"
                                  "}"
http_post.c - HTTP POST Examples
Demonstrates HTTP POST operations using SocketHTTPClient APIs:
Simple POST with JSON payload
Request builder API with custom headers
JSON POST with automatic serialization
Build: cmake -DBUILD_EXAMPLES=ON .. make example_http_post
Usage: ./example_http_post [url] ./example_http_post https://httpbin.org/post
Definition at line 27 of file http_post.c.
Referenced by main().