Tetsuo Pulse: http_server.c File Reference
http_server.c File Reference
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "core/Except.h"
#include "http/SocketHTTP.h"
#include "http/SocketHTTPServer.h"
Functions
static void signal_handler (int signo)
static void request_handler (SocketHTTPServer_Request_T req, void *userdata)
int main (int argc, char **argv)
Variables
static volatile int running = 1
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 167 of file http_server.c.
References SocketHTTPServer_Config::backlog, SocketHTTPServer_Config::bind_address, END_TRY, EXCEPT, FINALLY, SocketHTTPServer_Config::keepalive_timeout_ms, SocketHTTPServer_Config::max_body_size, SocketHTTPServer_Config::max_connections, SocketHTTPServer_Config::max_header_size, SocketHTTPServer_Config::port, request_handler(), SocketHTTPServer_Config::request_timeout_ms, running, signal_handler(), SocketHTTPServer_BindFailed, SocketHTTPServer_config_defaults(), SocketHTTPServer_Failed, SocketHTTPServer_free(), SocketHTTPServer_new(), SocketHTTPServer_process(), SocketHTTPServer_set_handler(), SocketHTTPServer_start(), SocketHTTPServer_stop(), and TRY.
request_handler()
static void request_handler (SocketHTTPServer_Request_T req, void * userdata) static
HTTP request handler
Routes requests based on path and responds appropriately.
Definition at line 47 of file http_server.c.
References HTTP_METHOD_POST, SocketHTTP_method_name(), SocketHTTPServer_Request_body(), SocketHTTPServer_Request_body_data(), SocketHTTPServer_Request_body_len(), SocketHTTPServer_Request_body_string(), SocketHTTPServer_Request_client_addr(), SocketHTTPServer_Request_finish(), SocketHTTPServer_Request_header(), SocketHTTPServer_Request_method(), SocketHTTPServer_Request_path(), and SocketHTTPServer_Request_status().
Referenced by main().
signal_handler()
static void signal_handler (int signo) static
Definition at line 35 of file http_server.c.
References running.
Referenced by main().
Variable Documentation
running
volatile int running = 1 static
http_server.c - Basic HTTP Server Example
Demonstrates a simple HTTP server using the SocketHTTPServer API. Supports HTTP/1.1 with keep-alive.
Build: cmake -DBUILD_EXAMPLES=ON .. make example_http_server
Usage: ./example_http_server [port] ./example_http_server 8080
Test with: curl http://localhost:8080/ curl http://localhost:8080/hello curl http://localhost:8080/json curl -X POST -d "test=data" http://localhost:8080/echo
Definition at line 32 of file http_server.c.
Referenced by main(), and signal_handler().