http2_client.c File Reference
http2_client.c File Reference
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "core/Except.h"
#include "http/SocketHTTPClient.h"
Functions
static const char * http_version_string (SocketHTTP_Version version)
http2_client.c - HTTP/2 Client Example
int main (int argc, char **argv)
Function Documentation
http_version_string()
static const char * http_version_string (SocketHTTP_Version version) static
http2_client.c - HTTP/2 Client Example
Demonstrates HTTP/2 with ALPN negotiation and protocol detection. The SocketHTTPClient automatically negotiates HTTP/2 when available.
Build: cmake -DBUILD_EXAMPLES=ON .. make example_http2_client
Usage: ./example_http2_client [url] ./example_http2_client https://www.google.com
Note: HTTP/2 requires TLS (HTTPS). HTTP/2 cleartext (h2c) is also supported but rarely used in practice.
Definition at line 28 of file http2_client.c.
References HTTP_VERSION_1_0, HTTP_VERSION_1_1, and HTTP_VERSION_2.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 44 of file http2_client.c.
References SocketHTTPClient_Response::body, SocketHTTPClient_Response::body_len, SocketHTTPClient_Config::enable_connection_pool, END_TRY, EXCEPT, FINALLY, HTTP_VERSION_2, http_version_string(), SocketHTTPClient_Config::max_connections_per_host, SocketHTTPClient_Config::max_version, SocketHTTPClient_config_defaults(), SocketHTTPClient_ConnectFailed, SocketHTTPClient_DNSFailed, SocketHTTPClient_Failed, SocketHTTPClient_free(), SocketHTTPClient_get(), SocketHTTPClient_new(), SocketHTTPClient_Response_free(), SocketHTTPClient_Timeout, SocketHTTPClient_TLSFailed, SocketHTTPClient_Response::status_code, TRY, and SocketHTTPClient_Response::version.