Tetsuo Pulse: http_get.c File Reference
http_get.c File Reference
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "core/Except.h"
#include "http/SocketHTTPClient.h"
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
http_get.c - HTTP GET Request Examples
Demonstrates various HTTP GET operations using SocketHTTPClient APIs:
Basic GET request
JSON GET with automatic parsing
File download
Build: cmake -DBUILD_EXAMPLES=ON .. make example_http_get
Usage: ./example_http_get [url] ./example_http_get https://httpbin.org/json
Definition at line 27 of file http_get.c.
References SocketHTTPClient_Response::body, SocketHTTPClient_Response::body_len, END_TRY, EXCEPT, FINALLY, HTTP_VERSION_1_0, HTTP_VERSION_2, SocketHTTPClient_ConnectFailed, SocketHTTPClient_DNSFailed, SocketHTTPClient_download(), SocketHTTPClient_Failed, SocketHTTPClient_free(), SocketHTTPClient_get(), SocketHTTPClient_json_get(), SocketHTTPClient_new(), SocketHTTPClient_Response_free(), SocketHTTPClient_Timeout, SocketHTTPClient_TLSFailed, SocketHTTPClient_Response::status_code, TRY, and SocketHTTPClient_Response::version.