Tetsuo Pulse: proxy_connect.c File Reference
proxy_connect.c File Reference
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "core/Except.h"
#include "socket/Socket.h"
#include "socket/SocketProxy.h"
#include "tls/SocketTLS.h"
#include "tls/SocketTLSContext.h"
Functions
static const char * proxy_type_name (SocketProxyType type)
static const char * proxy_result_string (SocketProxy_Result result)
static void print_usage (const char *program)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 129 of file proxy_connect.c.
References END_TRY, EXCEPT, FINALLY, SocketProxy_Config::host, SocketProxy_Config::password, SocketProxy_Config::port, print_usage(), proxy_type_name(), Socket_Failed, Socket_fd(), Socket_free(), Socket_getlocaladdr(), Socket_getlocalport(), Socket_recv(), Socket_sendall(), SocketProxy_config_defaults(), SocketProxy_connect(), SocketProxy_Failed, SocketProxy_parse_url(), SocketTLS_enable(), SocketTLS_get_cipher(), SocketTLS_get_version(), SocketTLS_handshake(), SocketTLS_HandshakeFailed, SocketTLS_recv(), SocketTLS_send(), SocketTLS_set_hostname(), SocketTLS_shutdown(), SocketTLS_VerifyFailed, SocketTLSContext_free(), SocketTLSContext_new_client(), TRY, SocketProxy_Config::type, and SocketProxy_Config::username.
print_usage()
static void print_usage (const char * program) static
Definition at line 110 of file proxy_connect.c.
Referenced by main().
proxy_result_string()
static const char * proxy_result_string (SocketProxy_Result result) static
Definition at line 70 of file proxy_connect.c.
References PROXY_ERROR, PROXY_ERROR_AUTH_FAILED, PROXY_ERROR_AUTH_REQUIRED, PROXY_ERROR_CANCELLED, PROXY_ERROR_CONNECT, PROXY_ERROR_CONNECTION_REFUSED, PROXY_ERROR_FORBIDDEN, PROXY_ERROR_HOST_UNREACHABLE, PROXY_ERROR_NETWORK_UNREACHABLE, PROXY_ERROR_PROTOCOL, PROXY_ERROR_TIMEOUT, PROXY_ERROR_TTL_EXPIRED, PROXY_ERROR_UNSUPPORTED, PROXY_IN_PROGRESS, and PROXY_OK.
proxy_type_name()
static const char * proxy_type_name (SocketProxyType type) static
proxy_connect.c - Proxy Tunneling Example
Demonstrates connecting to a target server through various proxy types:
SOCKS5 (most common for general proxying)
SOCKS4/4a (legacy)
HTTP CONNECT (for HTTP proxies)
Build: cmake -DBUILD_EXAMPLES=ON .. make example_proxy_connect
Usage: ./example_proxy_connect <proxy_url> <target_host> <target_port>
Examples:
SOCKS5 proxy without authentication
./example_proxy_connect socks5://localhost:1080 example.com 80
SOCKS5 proxy with authentication
./example_proxy_connect socks5://user:pass@.nosp@m.prox.nosp@m.y.exa.nosp@m.mple.nosp@m..com:1080 example.com 443
HTTP CONNECT proxy
./example_proxy_connect http://proxy.example.com:8080 example.com 443
SOCKS5H (hostname resolution at proxy)
./example_proxy_connect socks5h://localhost:1080 internal.example.com 80
Definition at line 46 of file proxy_connect.c.
References SOCKET_PROXY_HTTP, SOCKET_PROXY_HTTPS, SOCKET_PROXY_NONE, SOCKET_PROXY_SOCKS4, SOCKET_PROXY_SOCKS4A, SOCKET_PROXY_SOCKS5, and SOCKET_PROXY_SOCKS5H.
Referenced by main().