SocketHTTPServer.h File Reference
SocketHTTPServer.h File Reference
#include <stddef.h>
#include <stdint.h>
#include <sys/types.h>
#include "core/Arena.h"
#include "core/Except.h"
#include "core/SocketRateLimit.h"
#include "http/SocketHTTP.h"
#include "poll/SocketPoll.h"
#include "socket/Socket.h"
#include "tls/SocketTLSContext.h"
Data Structures
struct SocketHTTPServer_Config
HTTP server configuration.
Macros
#define HTTPSERVER_DEFAULT_BACKLOG 128
Default listen backlog.
#define HTTPSERVER_DEFAULT_PORT 8080
Default listen port.
#define HTTPSERVER_DEFAULT_BIND_ADDR "0.0.0.0"
Default bind address.
#define HTTPSERVER_DEFAULT_ENABLE_H2C_UPGRADE 0
Default enable H2C upgrade.
#define HTTPSERVER_CONTENT_LENGTH_BUF_SIZE 32
Buffer sizes for strings and chunks.
#define HTTPSERVER_CHUNK_FINAL_BUF_SIZE 64
#define HTTPSERVER_CLIENT_ADDR_MAX 64
#define HTTPSERVER_DRAIN_POLL_MS 100
#define HTTPSERVER_DEFAULT_MAX_CONNECTIONS 1000
Default maximum connections.
#define HTTPSERVER_DEFAULT_REQUEST_TIMEOUT_MS 30000
Default request timeout (ms) - idle timeout between requests.
#define HTTPSERVER_DEFAULT_KEEPALIVE_TIMEOUT_MS 60000
Default keep-alive timeout (ms)
#define HTTPSERVER_DEFAULT_MAX_HEADER_SIZE (64 * 1024)
Default maximum header size ENFORCEMENT: Passed to HTTP/1.1 parser config, enforced during parsing.
#define HTTPSERVER_DEFAULT_MAX_BODY_SIZE (10 * 1024 * 1024)
Default maximum body size ENFORCEMENT: Checked before body allocation.
#define HTTPSERVER_DEFAULT_MAX_REQUESTS_PER_CONN 1000
Default maximum requests per connection.
#define HTTPSERVER_DEFAULT_REQUEST_READ_TIMEOUT_MS 30000
Default request read timeout (ms) - time to read full request.
#define HTTPSERVER_DEFAULT_RESPONSE_WRITE_TIMEOUT_MS 60000
Default response write timeout (ms) - time to send full response.
#define HTTPSERVER_DEFAULT_MAX_CONNECTIONS_PER_CLIENT 100
Default max connections per client IP.
#define HTTPSERVER_DEFAULT_MAX_CONCURRENT_REQUESTS 100
Default max concurrent requests per connection (HTTP/2 multiplexing)
#define HTTPSERVER_DEFAULT_STREAM_CHUNK_SIZE 8192
Default streaming chunk size for response.
#define HTTPSERVER_RPS_WINDOW_SECONDS 10
Requests per second window (seconds) for RPS calculation.
#define HTTPSERVER_IO_BUFFER_SIZE 8192
I/O buffer size per connection (bytes)
#define HTTPSERVER_RECV_BUFFER_SIZE 4096
Receive buffer size for reading from sockets (bytes)
#define HTTPSERVER_RESPONSE_HEADER_BUFFER_SIZE 8192
Response header serialization buffer size (bytes)
#define HTTPSERVER_MAX_CLIENTS_PER_ACCEPT 10
Max clients to accept per event loop iteration.
#define HTTPSERVER_CHUNK_BUFFER_SIZE 16384
Chunk buffer size for streaming responses (bytes)
#define HTTPSERVER_MAX_RATE_LIMIT_ENDPOINTS 64
Max rate limit endpoints.
#define HTTPSERVER_LATENCY_SAMPLES 1000
Number of latency samples to track.
Typedefs
typedef struct SocketWS * SocketWS_T
SocketHTTPServer.h - HTTP Server API.
typedef struct SocketHTTPServer * SocketHTTPServer_T
HTTP server instance.
typedef struct SocketHTTPServer_Request * SocketHTTPServer_Request_T
Server request context.
typedef void(* SocketHTTPServer_Handler) (SocketHTTPServer_Request_T req, void *userdata)
Request handler callback.
typedef int(* SocketHTTPServer_BodyCallback) (SocketHTTPServer_Request_T req, const void *chunk, size_t len, int is_final, void *userdata)
Request body streaming callback.
typedef int(* SocketHTTPServer_Validator) (SocketHTTPServer_Request_T req, int *reject_status, void *userdata)
Request validation callback (middleware)
typedef void(* SocketHTTPServer_DrainCallback) (SocketHTTPServer_T server, int timed_out, void *userdata)
Drain completion callback.
Enumerations
enum SocketHTTPServer_State {
HTTPSERVER_STATE_RUNNING ,
HTTPSERVER_STATE_DRAINING ,
HTTPSERVER_STATE_STOPPED
}
Server lifecycle state for graceful shutdown.
Functions
void SocketHTTPServer_config_defaults (SocketHTTPServer_Config *config)
SocketHTTPServer_config_defaults - Initialize config with defaults @config: Configuration structure.
SocketHTTPServer_T SocketHTTPServer_new (const SocketHTTPServer_Config *config)
SocketHTTPServer_new - Create HTTP server @config: Configuration.
void SocketHTTPServer_free (SocketHTTPServer_T *server)
SocketHTTPServer_free - Free server and resources @server: Pointer to server (set to NULL)
int SocketHTTPServer_start (SocketHTTPServer_T server)
SocketHTTPServer_start - Start listening @server: Server instance.
void SocketHTTPServer_stop (SocketHTTPServer_T server)
SocketHTTPServer_stop - Stop server @server: Server instance.
void SocketHTTPServer_set_handler (SocketHTTPServer_T server, SocketHTTPServer_Handler handler, void *userdata)
SocketHTTPServer_set_handler - Set request handler @server: Server instance @handler: Handler callback @userdata: User data passed to handler.
int SocketHTTPServer_fd (SocketHTTPServer_T server)
SocketHTTPServer_fd - Get server socket for poll @server: Server instance.
int SocketHTTPServer_process (SocketHTTPServer_T server, int timeout_ms)
SocketHTTPServer_process - Process events @server: Server instance @timeout_ms: Poll timeout in milliseconds.
SocketPoll_T SocketHTTPServer_poll (SocketHTTPServer_T server)
SocketHTTPServer_poll - Get poll instance @server: Server instance.
SocketHTTP_Method SocketHTTPServer_Request_method (SocketHTTPServer_Request_T req)
SocketHTTPServer_Request_method - Get request method.
const char * SocketHTTPServer_Request_path (SocketHTTPServer_Request_T req)
SocketHTTPServer_Request_path - Get request path.
const char * SocketHTTPServer_Request_query (SocketHTTPServer_Request_T req)
SocketHTTPServer_Request_query - Get query string.
SocketHTTP_Headers_T SocketHTTPServer_Request_headers (SocketHTTPServer_Request_T req)
SocketHTTPServer_Request_headers - Get request headers.
const void * SocketHTTPServer_Request_body (SocketHTTPServer_Request_T req)
SocketHTTPServer_Request_body - Get request body.
size_t SocketHTTPServer_Request_body_len (SocketHTTPServer_Request_T req)
SocketHTTPServer_Request_body_len - Get request body length.
const char * SocketHTTPServer_Request_client_addr (SocketHTTPServer_Request_T req)
SocketHTTPServer_Request_client_addr - Get client address.
SocketHTTP_Version SocketHTTPServer_Request_version (SocketHTTPServer_Request_T req)
SocketHTTPServer_Request_version - Get HTTP version.
Arena_T SocketHTTPServer_Request_arena (SocketHTTPServer_Request_T req)
SocketHTTPServer_Request_arena - Get request arena.
size_t SocketHTTPServer_Request_memory_used (SocketHTTPServer_Request_T req)
SocketHTTPServer_Request_memory_used - Get connection memory usage @req: Request context.
Variables
const Except_T SocketHTTPServer_Failed
General server failure.
const Except_T SocketHTTPServer_BindFailed
Bind failure.
const Except_T SocketHTTPServer_ProtocolError
Protocol error.
Data Structure Documentation
SocketHTTPServer_Config
struct SocketHTTPServer_Config
HTTP server configuration.
Definition at line 268 of file SocketHTTPServer.h.
Data Fields
int backlog Listen backlog.
const char * bind_address Bind address (NULL = all interfaces)
int enable_h2c_upgrade Allow HTTP/2 upgrade (default: 0)
int keepalive_timeout_ms Keep-alive timeout.
size_t max_body_size
size_t max_concurrent_requests Max concurrent requests (HTTP/2)
size_t max_connections Total max connections.
int max_connections_per_client Max connections per client IP.
size_t max_header_size
size_t max_requests_per_connection Max requests per connection.
SocketHTTP_Version max_version Max HTTP version (default: HTTP/2)
int port Listen port.
int request_read_timeout_ms Max time to read complete request.
int request_timeout_ms Idle timeout between requests.
int response_write_timeout_ms Max time to send complete response.
SocketTLSContext_T tls_context TLS context (NULL = HTTP only)
Macro Definition Documentation
HTTPSERVER_CHUNK_BUFFER_SIZE
#define HTTPSERVER_CHUNK_BUFFER_SIZE 16384
Chunk buffer size for streaming responses (bytes)
Definition at line 221 of file SocketHTTPServer.h.
HTTPSERVER_CHUNK_FINAL_BUF_SIZE
#define HTTPSERVER_CHUNK_FINAL_BUF_SIZE 64
Definition at line 121 of file SocketHTTPServer.h.
HTTPSERVER_CLIENT_ADDR_MAX
#define HTTPSERVER_CLIENT_ADDR_MAX 64
Definition at line 125 of file SocketHTTPServer.h.
HTTPSERVER_CONTENT_LENGTH_BUF_SIZE
#define HTTPSERVER_CONTENT_LENGTH_BUF_SIZE 32
Buffer sizes for strings and chunks.
Definition at line 117 of file SocketHTTPServer.h.
HTTPSERVER_DEFAULT_BACKLOG
#define HTTPSERVER_DEFAULT_BACKLOG 128
Default listen backlog.
Definition at line 97 of file SocketHTTPServer.h.
HTTPSERVER_DEFAULT_BIND_ADDR
#define HTTPSERVER_DEFAULT_BIND_ADDR "0.0.0.0"
Default bind address.
Definition at line 107 of file SocketHTTPServer.h.
HTTPSERVER_DEFAULT_ENABLE_H2C_UPGRADE
#define HTTPSERVER_DEFAULT_ENABLE_H2C_UPGRADE 0
Default enable H2C upgrade.
Definition at line 112 of file SocketHTTPServer.h.
HTTPSERVER_DEFAULT_KEEPALIVE_TIMEOUT_MS
#define HTTPSERVER_DEFAULT_KEEPALIVE_TIMEOUT_MS 60000
Default keep-alive timeout (ms)
Definition at line 145 of file SocketHTTPServer.h.
HTTPSERVER_DEFAULT_MAX_BODY_SIZE
#define HTTPSERVER_DEFAULT_MAX_BODY_SIZE (10 * 1024 * 1024)
Default maximum body size ENFORCEMENT: Checked before body allocation.
Returns 413 Payload Too Large.
Definition at line 161 of file SocketHTTPServer.h.
HTTPSERVER_DEFAULT_MAX_CONCURRENT_REQUESTS
#define HTTPSERVER_DEFAULT_MAX_CONCURRENT_REQUESTS 100
Default max concurrent requests per connection (HTTP/2 multiplexing)
Definition at line 186 of file SocketHTTPServer.h.
HTTPSERVER_DEFAULT_MAX_CONNECTIONS
#define HTTPSERVER_DEFAULT_MAX_CONNECTIONS 1000
Default maximum connections.
Definition at line 135 of file SocketHTTPServer.h.
HTTPSERVER_DEFAULT_MAX_CONNECTIONS_PER_CLIENT
#define HTTPSERVER_DEFAULT_MAX_CONNECTIONS_PER_CLIENT 100
Default max connections per client IP.
Definition at line 181 of file SocketHTTPServer.h.
HTTPSERVER_DEFAULT_MAX_HEADER_SIZE
#define HTTPSERVER_DEFAULT_MAX_HEADER_SIZE (64 * 1024)
Default maximum header size ENFORCEMENT: Passed to HTTP/1.1 parser config, enforced during parsing.
Definition at line 153 of file SocketHTTPServer.h.
HTTPSERVER_DEFAULT_MAX_REQUESTS_PER_CONN
#define HTTPSERVER_DEFAULT_MAX_REQUESTS_PER_CONN 1000
Default maximum requests per connection.
Definition at line 166 of file SocketHTTPServer.h.
HTTPSERVER_DEFAULT_PORT
#define HTTPSERVER_DEFAULT_PORT 8080
Default listen port.
Definition at line 102 of file SocketHTTPServer.h.
HTTPSERVER_DEFAULT_REQUEST_READ_TIMEOUT_MS
#define HTTPSERVER_DEFAULT_REQUEST_READ_TIMEOUT_MS 30000
Default request read timeout (ms) - time to read full request.
Definition at line 171 of file SocketHTTPServer.h.
HTTPSERVER_DEFAULT_REQUEST_TIMEOUT_MS
#define HTTPSERVER_DEFAULT_REQUEST_TIMEOUT_MS 30000
Default request timeout (ms) - idle timeout between requests.
Definition at line 140 of file SocketHTTPServer.h.
HTTPSERVER_DEFAULT_RESPONSE_WRITE_TIMEOUT_MS
#define HTTPSERVER_DEFAULT_RESPONSE_WRITE_TIMEOUT_MS 60000
Default response write timeout (ms) - time to send full response.
Definition at line 176 of file SocketHTTPServer.h.
HTTPSERVER_DEFAULT_STREAM_CHUNK_SIZE
#define HTTPSERVER_DEFAULT_STREAM_CHUNK_SIZE 8192
Default streaming chunk size for response.
Definition at line 191 of file SocketHTTPServer.h.
HTTPSERVER_DRAIN_POLL_MS
#define HTTPSERVER_DRAIN_POLL_MS 100
Definition at line 129 of file SocketHTTPServer.h.
HTTPSERVER_IO_BUFFER_SIZE
#define HTTPSERVER_IO_BUFFER_SIZE 8192
I/O buffer size per connection (bytes)
Definition at line 201 of file SocketHTTPServer.h.
HTTPSERVER_LATENCY_SAMPLES
#define HTTPSERVER_LATENCY_SAMPLES 1000
Number of latency samples to track.
Definition at line 231 of file SocketHTTPServer.h.
HTTPSERVER_MAX_CLIENTS_PER_ACCEPT
#define HTTPSERVER_MAX_CLIENTS_PER_ACCEPT 10
Max clients to accept per event loop iteration.
Definition at line 216 of file SocketHTTPServer.h.
HTTPSERVER_MAX_RATE_LIMIT_ENDPOINTS
#define HTTPSERVER_MAX_RATE_LIMIT_ENDPOINTS 64
Max rate limit endpoints.
Definition at line 226 of file SocketHTTPServer.h.
HTTPSERVER_RECV_BUFFER_SIZE
#define HTTPSERVER_RECV_BUFFER_SIZE 4096
Receive buffer size for reading from sockets (bytes)
Definition at line 206 of file SocketHTTPServer.h.
HTTPSERVER_RESPONSE_HEADER_BUFFER_SIZE
#define HTTPSERVER_RESPONSE_HEADER_BUFFER_SIZE 8192
Response header serialization buffer size (bytes)
Definition at line 211 of file SocketHTTPServer.h.
HTTPSERVER_RPS_WINDOW_SECONDS
#define HTTPSERVER_RPS_WINDOW_SECONDS 10
Requests per second window (seconds) for RPS calculation.
Definition at line 196 of file SocketHTTPServer.h.
Typedef Documentation
SocketHTTPServer_BodyCallback
typedef int(* SocketHTTPServer_BodyCallback) (SocketHTTPServer_Request_T req, const void *chunk, size_t len, int is_final, void *userdata)
Request body streaming callback.
Called incrementally as request body data arrives. Enables processing large uploads without buffering the entire body in memory.
@req: Request context @chunk: Body data chunk @len: Chunk length @is_final: 1 if this is the last chunk, 0 otherwise @userdata: User data from SocketHTTPServer_Request_body_stream()
Returns: 0 to continue receiving, non-zero to abort and close connection
Definition at line 341 of file SocketHTTPServer.h.
SocketHTTPServer_DrainCallback
typedef void(* SocketHTTPServer_DrainCallback) (SocketHTTPServer_T server, int timed_out, void *userdata)
Drain completion callback.
Called when graceful shutdown completes or times out.
@server: Server instance @timed_out: 1 if drain timed out (forced shutdown), 0 if graceful @userdata: User data from SocketHTTPServer_set_drain_callback()
Definition at line 369 of file SocketHTTPServer.h.
SocketHTTPServer_Handler
typedef void(* SocketHTTPServer_Handler) (SocketHTTPServer_Request_T req, void *userdata)
Request handler callback.
Called for each incoming HTTP request. The handler should:
Read request details using accessor functions
Set response status and headers
Send response body
Call finish() when done
The request context is valid only during the callback.
Definition at line 324 of file SocketHTTPServer.h.
SocketHTTPServer_Request_T
typedef struct SocketHTTPServer_Request* SocketHTTPServer_Request_T
Server request context.
Definition at line 307 of file SocketHTTPServer.h.
SocketHTTPServer_T
typedef struct SocketHTTPServer* SocketHTTPServer_T
HTTP server instance.
Definition at line 304 of file SocketHTTPServer.h.
SocketHTTPServer_Validator
typedef int(* SocketHTTPServer_Validator) (SocketHTTPServer_Request_T req, int *reject_status, void *userdata)
Request validation callback (middleware)
Called before the request handler to validate/authenticate requests. Can reject requests before they reach the handler.
@req: Request context @reject_status: Output - HTTP status code if rejecting (e.g., 401, 403) @userdata: User data from SocketHTTPServer_set_validator()
Returns: Non-zero to allow request (call handler), 0 to reject
Definition at line 357 of file SocketHTTPServer.h.
SocketWS_T
typedef struct SocketWS* SocketWS_T
SocketHTTPServer.h - HTTP Server API.
Part of the Socket Library
High-level HTTP server supporting HTTP/1.1 and HTTP/2:
Event-driven request handling
Connection management with keep-alive
Protocol negotiation (ALPN for HTTP/2)
WebSocket upgrade support
Request body streaming for large uploads
Response body streaming (chunked transfer encoding)
HTTP/2 server push support
Rate limiting per endpoint
Per-client connection limiting
Request validation middleware
Granular timeout enforcement
Graceful shutdown (drain)
Dependencies (leveraged, not duplicated):
SocketHTTP for headers, URI, methods, status codes
SocketHTTP1 for HTTP/1.1 parsing
SocketHTTP2 for HTTP/2 protocol
SocketPoll for event loop integration
SocketRateLimit for rate limiting
SocketIPTracker for per-client limits
Thread safety: Server instances are NOT thread-safe. Use one server per thread or external synchronization.
PLATFORM REQUIREMENTS:
POSIX-compliant system (Linux, BSD, macOS)
pthread for mutex synchronization
OpenSSL for TLS (optional, via SOCKET_HAS_TLS)
Definition at line 59 of file SocketHTTPServer.h.
Enumeration Type Documentation
SocketHTTPServer_State
enum SocketHTTPServer_State
Server lifecycle state for graceful shutdown.
Enumerator
HTTPSERVER_STATE_RUNNING
Normal operation.
HTTPSERVER_STATE_DRAINING
Draining - finishing existing requests.
HTTPSERVER_STATE_STOPPED
Stopped - all requests complete.
Definition at line 254 of file SocketHTTPServer.h.
Function Documentation
SocketHTTPServer_config_defaults()
void SocketHTTPServer_config_defaults (SocketHTTPServer_Config * config) extern
SocketHTTPServer_config_defaults - Initialize config with defaults @config: Configuration structure.
Thread-safe: Yes
Referenced by main().
SocketHTTPServer_fd()
int SocketHTTPServer_fd (SocketHTTPServer_T server) extern
SocketHTTPServer_fd - Get server socket for poll @server: Server instance.
Returns: File descriptor for listening socket Thread-safe: Yes
SocketHTTPServer_free()
void SocketHTTPServer_free (SocketHTTPServer_T * server) extern
SocketHTTPServer_free - Free server and resources @server: Pointer to server (set to NULL)
Thread-safe: No
Referenced by main().
SocketHTTPServer_new()
SocketHTTPServer_T SocketHTTPServer_new (const SocketHTTPServer_Config * config) extern
SocketHTTPServer_new - Create HTTP server @config: Configuration.
Returns: New server instance Raises: SocketHTTPServer_Failed on error Thread-safe: Yes
Referenced by main().
SocketHTTPServer_poll()
SocketPoll_T SocketHTTPServer_poll (SocketHTTPServer_T server) extern
SocketHTTPServer_poll - Get poll instance @server: Server instance.
Returns: Internal SocketPoll_T for advanced integration Thread-safe: Yes
SocketHTTPServer_process()
int SocketHTTPServer_process (SocketHTTPServer_T server, int timeout_ms) extern
SocketHTTPServer_process - Process events @server: Server instance @timeout_ms: Poll timeout in milliseconds.
Accepts new connections, reads requests, and invokes handlers.
Returns: Number of requests processed Thread-safe: No
Referenced by main().
SocketHTTPServer_Request_arena()
Arena_T SocketHTTPServer_Request_arena (SocketHTTPServer_Request_T req) extern
SocketHTTPServer_Request_arena - Get request arena.
SocketHTTPServer_Request_body()
const void * SocketHTTPServer_Request_body (SocketHTTPServer_Request_T req) extern
SocketHTTPServer_Request_body - Get request body.
Referenced by request_handler().
SocketHTTPServer_Request_body_len()
size_t SocketHTTPServer_Request_body_len (SocketHTTPServer_Request_T req) extern
SocketHTTPServer_Request_body_len - Get request body length.
Referenced by request_handler().
SocketHTTPServer_Request_client_addr()
const char * SocketHTTPServer_Request_client_addr (SocketHTTPServer_Request_T req) extern
SocketHTTPServer_Request_client_addr - Get client address.
Referenced by request_handler(), and request_handler().
SocketHTTPServer_Request_headers()
SocketHTTP_Headers_T SocketHTTPServer_Request_headers (SocketHTTPServer_Request_T req) extern
SocketHTTPServer_Request_headers - Get request headers.
SocketHTTPServer_Request_memory_used()
size_t SocketHTTPServer_Request_memory_used (SocketHTTPServer_Request_T req) extern
SocketHTTPServer_Request_memory_used - Get connection memory usage @req: Request context.
Returns: Total bytes allocated for this connection (including buffers, body) Thread-safe: No
SocketHTTPServer_Request_method()
SocketHTTP_Method SocketHTTPServer_Request_method (SocketHTTPServer_Request_T req) extern
SocketHTTPServer_Request_method - Get request method.
Referenced by request_handler().
SocketHTTPServer_Request_path()
const char * SocketHTTPServer_Request_path (SocketHTTPServer_Request_T req) extern
SocketHTTPServer_Request_path - Get request path.
Referenced by request_handler(), and request_handler().
SocketHTTPServer_Request_query()
const char * SocketHTTPServer_Request_query (SocketHTTPServer_Request_T req) extern
SocketHTTPServer_Request_query - Get query string.
SocketHTTPServer_Request_version()
SocketHTTP_Version SocketHTTPServer_Request_version (SocketHTTPServer_Request_T req) extern
SocketHTTPServer_Request_version - Get HTTP version.
SocketHTTPServer_set_handler()
void SocketHTTPServer_set_handler (SocketHTTPServer_T server, SocketHTTPServer_Handler handler, void * userdata) extern
SocketHTTPServer_set_handler - Set request handler @server: Server instance @handler: Handler callback @userdata: User data passed to handler.
Thread-safe: No
Referenced by main().
SocketHTTPServer_start()
int SocketHTTPServer_start (SocketHTTPServer_T server) extern
SocketHTTPServer_start - Start listening @server: Server instance.
Returns: 0 on success, -1 on error Thread-safe: No
Referenced by main().
SocketHTTPServer_stop()
void SocketHTTPServer_stop (SocketHTTPServer_T server) extern
SocketHTTPServer_stop - Stop server @server: Server instance.
Stops accepting new connections. Existing connections continue. Thread-safe: No
Referenced by main().
Variable Documentation
SocketHTTPServer_BindFailed
const Except_T SocketHTTPServer_BindFailed extern
Bind failure.
Referenced by main().
SocketHTTPServer_Failed
const Except_T SocketHTTPServer_Failed extern
General server failure.
Referenced by main().
SocketHTTPServer_ProtocolError
const Except_T SocketHTTPServer_ProtocolError extern
Protocol error.