SocketWS.h File Reference
SocketWS.h File Reference
#include <stddef.h>
#include <stdint.h>
#include "core/Except.h"
#include "http/SocketHTTP.h"
#include "socket/Socket.h"
Data Structures
struct SocketWS_Config
struct SocketWS_Frame
struct SocketWS_Message
Macros
#define T SocketWS_T
Typedefs
typedef struct SocketPoll_T * SocketPoll_T
typedef struct SocketWS * SocketWS_T
Enumerations
enum SocketWS_Opcode {
WS_OPCODE_CONTINUATION = 0x0 ,
WS_OPCODE_TEXT = 0x1 ,
WS_OPCODE_BINARY = 0x2 ,
WS_OPCODE_CLOSE = 0x8 ,
WS_OPCODE_PING = 0x9 ,
WS_OPCODE_PONG = 0xA
}
enum SocketWS_CloseCode {
WS_CLOSE_NORMAL = 1000 ,
WS_CLOSE_GOING_AWAY = 1001 ,
WS_CLOSE_PROTOCOL_ERROR = 1002 ,
WS_CLOSE_UNSUPPORTED_DATA = 1003 ,
WS_CLOSE_NO_STATUS = 1005 ,
WS_CLOSE_ABNORMAL = 1006 ,
WS_CLOSE_INVALID_PAYLOAD = 1007 ,
WS_CLOSE_POLICY_VIOLATION = 1008 ,
WS_CLOSE_MESSAGE_TOO_BIG = 1009 ,
WS_CLOSE_MANDATORY_EXT = 1010 ,
WS_CLOSE_INTERNAL_ERROR = 1011 ,
WS_CLOSE_SERVICE_RESTART = 1012 ,
WS_CLOSE_TRY_AGAIN_LATER = 1013 ,
WS_CLOSE_BAD_GATEWAY = 1014 ,
WS_CLOSE_TLS_HANDSHAKE = 1015
}
enum SocketWS_State {
WS_STATE_CONNECTING ,
WS_STATE_OPEN ,
WS_STATE_CLOSING ,
WS_STATE_CLOSED
}
enum SocketWS_Role {
WS_ROLE_CLIENT ,
WS_ROLE_SERVER
}
enum SocketWS_Error {
WS_OK = 0 ,
WS_ERROR ,
WS_ERROR_HANDSHAKE ,
WS_ERROR_PROTOCOL ,
WS_ERROR_FRAME_TOO_LARGE ,
WS_ERROR_MESSAGE_TOO_LARGE ,
WS_ERROR_INVALID_UTF8 ,
WS_ERROR_COMPRESSION ,
WS_ERROR_CLOSED ,
WS_ERROR_WOULD_BLOCK ,
WS_ERROR_TIMEOUT
}
Functions
void SocketWS_config_defaults (SocketWS_Config *config)
SocketWS_config_defaults - Initialize configuration with defaults @config: Configuration to initialize.
SocketWS_T SocketWS_client_new (Socket_T socket, const char *host, const char *path, const SocketWS_Config *config)
SocketWS_client_new - Create client WebSocket from connected socket @socket: Connected TCP socket @host: Host header value (required) @path: Request path (e.g., "/ws", default: "/") @config: Configuration (NULL for defaults)
int SocketWS_is_upgrade (const SocketHTTP_Request *request)
SocketWS_is_upgrade - Check if HTTP request is WebSocket upgrade @request: Parsed HTTP request.
SocketWS_T SocketWS_server_accept (Socket_T socket, const SocketHTTP_Request *request, const SocketWS_Config *config)
SocketWS_server_accept - Accept WebSocket upgrade @socket: TCP socket with pending upgrade request @request: Parsed HTTP upgrade request @config: Configuration (NULL for defaults)
void SocketWS_server_reject (Socket_T socket, int status_code, const char *reason)
SocketWS_server_reject - Reject upgrade with HTTP response @socket: TCP socket @status_code: HTTP status (e.g., 400, 403) @reason: Rejection reason.
void SocketWS_free (SocketWS_T *ws)
SocketWS_free - Free WebSocket connection @ws: Pointer to WebSocket (set to NULL after free)
int SocketWS_handshake (SocketWS_T ws)
SocketWS_handshake - Perform/continue handshake @ws: WebSocket instance.
SocketWS_State SocketWS_state (SocketWS_T ws)
SocketWS_state - Get current state @ws: WebSocket instance.
Socket_T SocketWS_socket (SocketWS_T ws)
SocketWS_socket - Get underlying socket @ws: WebSocket instance.
const char * SocketWS_selected_subprotocol (SocketWS_T ws)
SocketWS_selected_subprotocol - Get negotiated subprotocol @ws: WebSocket instance.
int SocketWS_compression_enabled (SocketWS_T ws)
SocketWS_compression_enabled - Check if compression active @ws: WebSocket instance.
int SocketWS_send_text (SocketWS_T ws, const char *data, size_t len)
SocketWS_send_text - Send text message @ws: WebSocket instance @data: UTF-8 text data @len: Length in bytes.
int SocketWS_send_binary (SocketWS_T ws, const void *data, size_t len)
SocketWS_send_binary - Send binary message @ws: WebSocket instance @data: Binary data @len: Length in bytes.
int SocketWS_ping (SocketWS_T ws, const void *data, size_t len)
SocketWS_ping - Send PING control frame @ws: WebSocket instance @data: Optional payload (max 125 bytes, may be NULL) @len: Payload length.
int SocketWS_pong (SocketWS_T ws, const void *data, size_t len)
SocketWS_pong - Send unsolicited PONG @ws: WebSocket instance @data: Payload (max 125 bytes, may be NULL) @len: Payload length.
Variables
const Except_T SocketWS_Failed
SocketWS_Failed - General WebSocket operation failure.
const Except_T SocketWS_ProtocolError
SocketWS_ProtocolError - WebSocket protocol violation.
const Except_T SocketWS_Closed
SocketWS_Closed - WebSocket connection closed.
Data Structure Documentation
SocketWS_Config
struct SocketWS_Config
Definition at line 183 of file SocketWS.h.
Data Fields
int deflate_max_window_bits LZ77 window size (8-15, default: 15)
int deflate_no_context_takeover Don't reuse compression context.
int enable_permessage_deflate Enable compression (default: no)
size_t max_fragments Max fragments per message (default: 1000)
size_t max_frame_size Max single frame (default: 16MB)
size_t max_message_size Max reassembled message (default: 64MB)
int ping_interval_ms Auto-ping interval (0 = disabled)
int ping_timeout_ms Pong timeout.
SocketWS_Role role Client or server role.
const char ** subprotocols NULL-terminated list of subprotocols.
int validate_utf8 Validate UTF-8 in text frames (default: yes)
SocketWS_Frame
struct SocketWS_Frame
Definition at line 212 of file SocketWS.h.
Data Fields
int fin Final fragment flag.
SocketWS_Opcode opcode Frame opcode.
const unsigned char * payload Payload data.
size_t payload_len Payload length.
int rsv1 Reserved bit 1 (compression)
SocketWS_Message
struct SocketWS_Message
Definition at line 225 of file SocketWS.h.
Data Fields
unsigned char * data Message data (caller must free)
size_t len Message length.
SocketWS_Opcode type TEXT or BINARY.
Macro Definition Documentation
T
#define T SocketWS_T
Definition at line 83 of file SocketWS.h.
Typedef Documentation
SocketPoll_T
typedef struct SocketPoll_T* SocketPoll_T
Definition at line 77 of file SocketWS.h.
SocketWS_T
typedef struct SocketWS* SocketWS_T
Definition at line 84 of file SocketWS.h.
Enumeration Type Documentation
SocketWS_CloseCode
enum SocketWS_CloseCode
Enumerator
WS_CLOSE_NORMAL
Normal closure.
WS_CLOSE_GOING_AWAY
Endpoint going away.
WS_CLOSE_PROTOCOL_ERROR
Protocol error.
WS_CLOSE_UNSUPPORTED_DATA
Unsupported data type.
WS_CLOSE_NO_STATUS
No status received (internal)
WS_CLOSE_ABNORMAL
Abnormal closure (internal)
WS_CLOSE_INVALID_PAYLOAD
Invalid frame payload (e.g., bad UTF-8)
WS_CLOSE_POLICY_VIOLATION
Policy violation.
WS_CLOSE_MESSAGE_TOO_BIG
Message too big.
WS_CLOSE_MANDATORY_EXT
Mandatory extension missing.
WS_CLOSE_INTERNAL_ERROR
Internal server error.
WS_CLOSE_SERVICE_RESTART
Service restart.
WS_CLOSE_TRY_AGAIN_LATER
Try again later.
WS_CLOSE_BAD_GATEWAY
Bad gateway.
WS_CLOSE_TLS_HANDSHAKE
TLS handshake failure (internal)
Definition at line 123 of file SocketWS.h.
SocketWS_Error
enum SocketWS_Error
Enumerator
WS_OK
Success.
WS_ERROR
General error.
WS_ERROR_HANDSHAKE
Handshake failed.
WS_ERROR_PROTOCOL
Protocol violation.
WS_ERROR_FRAME_TOO_LARGE
Frame exceeds limit.
WS_ERROR_MESSAGE_TOO_LARGE
Message exceeds limit.
WS_ERROR_INVALID_UTF8
Invalid UTF-8 in text.
WS_ERROR_COMPRESSION
Compression error.
WS_ERROR_CLOSED
Connection closed.
WS_ERROR_WOULD_BLOCK
Would block (non-blocking)
WS_ERROR_TIMEOUT
Operation timed out.
Definition at line 164 of file SocketWS.h.
SocketWS_Opcode
enum SocketWS_Opcode
Enumerator
WS_OPCODE_CONTINUATION
Continuation frame.
WS_OPCODE_TEXT
Text frame (UTF-8)
WS_OPCODE_BINARY
Binary frame.
WS_OPCODE_CLOSE
Close frame.
WS_OPCODE_PING
Ping frame.
WS_OPCODE_PONG
Pong frame.
Definition at line 109 of file SocketWS.h.
SocketWS_Role
enum SocketWS_Role
Enumerator
WS_ROLE_CLIENT
Client role (masks frames)
WS_ROLE_SERVER
Server role (doesn't mask)
Definition at line 154 of file SocketWS.h.
SocketWS_State
enum SocketWS_State
Enumerator
WS_STATE_CONNECTING
Handshake in progress.
WS_STATE_OPEN
Ready for messages.
WS_STATE_CLOSING
Close handshake in progress.
WS_STATE_CLOSED
Connection terminated.
Definition at line 146 of file SocketWS.h.
Function Documentation
SocketWS_client_new()
SocketWS_T SocketWS_client_new (Socket_T socket, const char * host, const char * path, const SocketWS_Config * config) extern
SocketWS_client_new - Create client WebSocket from connected socket @socket: Connected TCP socket @host: Host header value (required) @path: Request path (e.g., "/ws", default: "/") @config: Configuration (NULL for defaults)
Creates a WebSocket in CONNECTING state. Call SocketWS_handshake() to complete the HTTP upgrade.
Returns: WebSocket instance Raises: SocketWS_Failed on error Thread-safe: Yes
Referenced by main().
SocketWS_compression_enabled()
int SocketWS_compression_enabled (SocketWS_T ws) extern
SocketWS_compression_enabled - Check if compression active @ws: WebSocket instance.
Returns: 1 if permessage-deflate enabled, 0 otherwise Thread-safe: No
Referenced by main().
SocketWS_config_defaults()
void SocketWS_config_defaults (SocketWS_Config * config) extern
SocketWS_config_defaults - Initialize configuration with defaults @config: Configuration to initialize.
Thread-safe: Yes
Referenced by main().
SocketWS_free()
void SocketWS_free (SocketWS_T * ws) extern
SocketWS_free - Free WebSocket connection @ws: Pointer to WebSocket (set to NULL after free)
Thread-safe: No
Referenced by main(), process_websocket_clients(), and request_handler().
SocketWS_handshake()
int SocketWS_handshake (SocketWS_T ws) extern
SocketWS_handshake - Perform/continue handshake @ws: WebSocket instance.
For clients: Sends HTTP upgrade request, receives and validates response. For servers: Sends HTTP 101 response.
Returns: 0 if complete, 1 if in progress (call again), -1 on error Thread-safe: No
Referenced by main(), and request_handler().
SocketWS_is_upgrade()
int SocketWS_is_upgrade (const SocketHTTP_Request * request) extern
SocketWS_is_upgrade - Check if HTTP request is WebSocket upgrade @request: Parsed HTTP request.
Returns: 1 if WebSocket upgrade request, 0 otherwise Thread-safe: Yes
SocketWS_ping()
int SocketWS_ping (SocketWS_T ws, const void * data, size_t len) extern
SocketWS_ping - Send PING control frame @ws: WebSocket instance @data: Optional payload (max 125 bytes, may be NULL) @len: Payload length.
Returns: 0 on success, -1 on error Thread-safe: No
Referenced by main().
SocketWS_pong()
int SocketWS_pong (SocketWS_T ws, const void * data, size_t len) extern
SocketWS_pong - Send unsolicited PONG @ws: WebSocket instance @data: Payload (max 125 bytes, may be NULL) @len: Payload length.
Returns: 0 on success, -1 on error Thread-safe: No
SocketWS_selected_subprotocol()
const char * SocketWS_selected_subprotocol (SocketWS_T ws) extern
SocketWS_selected_subprotocol - Get negotiated subprotocol @ws: WebSocket instance.
Returns: Selected subprotocol string, or NULL if none Thread-safe: No
Referenced by main().
SocketWS_send_binary()
int SocketWS_send_binary (SocketWS_T ws, const void * data, size_t len) extern
SocketWS_send_binary - Send binary message @ws: WebSocket instance @data: Binary data @len: Length in bytes.
Returns: 0 on success, -1 on error Thread-safe: No
Referenced by main(), and process_websocket_clients().
SocketWS_send_text()
int SocketWS_send_text (SocketWS_T ws, const char * data, size_t len) extern
SocketWS_send_text - Send text message @ws: WebSocket instance @data: UTF-8 text data @len: Length in bytes.
Data is validated for UTF-8 if validate_utf8 enabled. Large messages are automatically fragmented.
Returns: 0 on success, -1 on error Thread-safe: No
Referenced by main(), and process_websocket_clients().
SocketWS_server_accept()
SocketWS_T SocketWS_server_accept (Socket_T socket, const SocketHTTP_Request * request, const SocketWS_Config * config) extern
SocketWS_server_accept - Accept WebSocket upgrade @socket: TCP socket with pending upgrade request @request: Parsed HTTP upgrade request @config: Configuration (NULL for defaults)
Creates a WebSocket in CONNECTING state. Call SocketWS_handshake() to send the HTTP 101 response.
Returns: WebSocket instance Raises: SocketWS_Failed on error Thread-safe: Yes
SocketWS_server_reject()
void SocketWS_server_reject (Socket_T socket, int status_code, const char * reason) extern
SocketWS_server_reject - Reject upgrade with HTTP response @socket: TCP socket @status_code: HTTP status (e.g., 400, 403) @reason: Rejection reason.
Thread-safe: Yes
SocketWS_socket()
Socket_T SocketWS_socket (SocketWS_T ws) extern
SocketWS_socket - Get underlying socket @ws: WebSocket instance.
Returns: TCP socket (do not close directly) Thread-safe: No
SocketWS_state()
SocketWS_State SocketWS_state (SocketWS_T ws) extern
SocketWS_state - Get current state @ws: WebSocket instance.
Returns: Current state (CONNECTING, OPEN, CLOSING, CLOSED) Thread-safe: No (read-only, safe for status checks)
Referenced by main(), process_websocket_clients(), and request_handler().
Variable Documentation
SocketWS_Closed
const Except_T SocketWS_Closed extern
SocketWS_Closed - WebSocket connection closed.
Referenced by main().
SocketWS_Failed
const Except_T SocketWS_Failed extern
SocketWS_Failed - General WebSocket operation failure.
Referenced by main().
SocketWS_ProtocolError
const Except_T SocketWS_ProtocolError extern
SocketWS_ProtocolError - WebSocket protocol violation.
Referenced by main().