Socket.h File Reference
Socket.h File Reference
#include "core/Except.h"
#include "core/SocketConfig.h"
#include "dns/SocketDNS.h"
#include "socket/SocketCommon.h"
Macros
#define T Socket_T
Typedefs
typedef struct Socket_T * Socket_T
Functions
int Socket_error_is_retryable (int err)
Socket_T Socket_new (int domain, int type, int protocol)
void SocketPair_new (int type, Socket_T *socket1, Socket_T *socket2)
void Socket_free (Socket_T *socket)
Socket_T Socket_new_from_fd (int fd)
int Socket_debug_live_count (void)
void Socket_bind (Socket_T socket, const char *host, int port)
void Socket_listen (Socket_T socket, int backlog)
Socket_T Socket_accept (Socket_T socket)
void Socket_connect (Socket_T socket, const char *host, int port)
ssize_t Socket_send (Socket_T socket, const void *buf, size_t len)
ssize_t Socket_recv (Socket_T socket, void *buf, size_t len)
ssize_t Socket_sendall (Socket_T socket, const void *buf, size_t len)
ssize_t Socket_recvall (Socket_T socket, void *buf, size_t len)
ssize_t Socket_sendv (Socket_T socket, const struct iovec *iov, int iovcnt)
ssize_t Socket_recvv (Socket_T socket, struct iovec *iov, int iovcnt)
ssize_t Socket_sendvall (Socket_T socket, const struct iovec *iov, int iovcnt)
ssize_t Socket_recvvall (Socket_T socket, struct iovec *iov, int iovcnt)
ssize_t Socket_sendfile (Socket_T socket, int file_fd, off_t *offset, size_t count)
ssize_t Socket_sendfileall (Socket_T socket, int file_fd, off_t *offset, size_t count)
ssize_t Socket_sendmsg (Socket_T socket, const struct msghdr *msg, int flags)
ssize_t Socket_recvmsg (Socket_T socket, struct msghdr *msg, int flags)
int Socket_isconnected (Socket_T socket)
int Socket_isbound (Socket_T socket)
int Socket_islistening (Socket_T socket)
int Socket_fd (const Socket_T socket)
const char * Socket_getpeeraddr (const Socket_T socket)
int Socket_getpeerport (const Socket_T socket)
const char * Socket_getlocaladdr (const Socket_T socket)
int Socket_getlocalport (const Socket_T socket)
void Socket_setnonblocking (Socket_T socket)
void Socket_setreuseaddr (Socket_T socket)
void Socket_setreuseport (Socket_T socket)
void Socket_settimeout (Socket_T socket, int timeout_sec)
void Socket_setkeepalive (Socket_T socket, int idle, int interval, int count)
void Socket_setnodelay (Socket_T socket, int nodelay)
int Socket_gettimeout (Socket_T socket)
void Socket_getkeepalive (Socket_T socket, int *idle, int *interval, int *count)
int Socket_getnodelay (Socket_T socket)
int Socket_getrcvbuf (Socket_T socket)
int Socket_getsndbuf (Socket_T socket)
void Socket_setrcvbuf (Socket_T socket, int size)
void Socket_setsndbuf (Socket_T socket, int size)
void Socket_setcongestion (Socket_T socket, const char *algorithm)
int Socket_getcongestion (Socket_T socket, char *algorithm, size_t len)
void Socket_setfastopen (Socket_T socket, int enable)
int Socket_getfastopen (Socket_T socket)
void Socket_setusertimeout (Socket_T socket, unsigned int timeout_ms)
unsigned int Socket_getusertimeout (Socket_T socket)
void Socket_shutdown (Socket_T socket, int how)
void Socket_setcloexec (Socket_T socket, int enable)
void Socket_setdeferaccept (Socket_T socket, int timeout_sec)
int Socket_getdeferaccept (Socket_T socket)
void Socket_timeouts_get (const Socket_T socket, SocketTimeouts_T *timeouts)
void Socket_timeouts_set (Socket_T socket, const SocketTimeouts_T *timeouts)
void Socket_timeouts_getdefaults (SocketTimeouts_T *timeouts)
void Socket_timeouts_setdefaults (const SocketTimeouts_T *timeouts)
void Socket_timeouts_set_extended (Socket_T socket, const SocketTimeouts_Extended_T *extended)
void Socket_timeouts_get_extended (const Socket_T socket, SocketTimeouts_Extended_T *extended)
void Socket_setbandwidth (Socket_T socket, size_t bytes_per_sec)
size_t Socket_getbandwidth (Socket_T socket)
ssize_t Socket_send_limited (Socket_T socket, const void *buf, size_t len)
ssize_t Socket_recv_limited (Socket_T socket, void *buf, size_t len)
int64_t Socket_bandwidth_wait_ms (Socket_T socket, size_t bytes)
void Socket_bind_unix (Socket_T socket, const char *path)
void Socket_connect_unix (Socket_T socket, const char *path)
int Socket_getpeerpid (const Socket_T socket)
int Socket_getpeeruid (const Socket_T socket)
int Socket_getpeergid (const Socket_T socket)
int Socket_sendfd (Socket_T socket, int fd_to_pass)
int Socket_recvfd (Socket_T socket, int *fd_received)
int Socket_sendfds (Socket_T socket, const int *fds, size_t count)
int Socket_recvfds (Socket_T socket, int *fds, size_t max_count, size_t *received_count)
void SocketUnix_bind (SocketBase_T base, const char *path, Except_T exc_type)
void SocketUnix_connect (SocketBase_T base, const char *path, Except_T exc_type)
int SocketUnix_validate_unix_path (const char *path, size_t path_len)
SocketDNS_Request_T Socket_bind_async (SocketDNS_T dns, Socket_T socket, const char *host, int port)
void Socket_bind_async_cancel (SocketDNS_T dns, SocketDNS_Request_T req)
SocketDNS_Request_T Socket_connect_async (SocketDNS_T dns, Socket_T socket, const char *host, int port)
void Socket_connect_async_cancel (SocketDNS_T dns, SocketDNS_Request_T req)
void Socket_bind_with_addrinfo (Socket_T socket, struct addrinfo *res)
void Socket_connect_with_addrinfo (Socket_T socket, struct addrinfo *res)
int Socket_ignore_sigpipe (void)
Variables
const Except_T Socket_Failed
const Except_T Socket_Closed
const Except_T SocketUnix_Failed
Macro Definition Documentation
T
#define T Socket_T
Socket.h - Socket Abstraction Layer
Part of the Socket Library
High-level, exception-based TCP/IP/Unix domain socket interface. This header consolidates all socket operations including:
Core socket creation and I/O
State query functions
Socket options configuration
Async DNS operations
Unix domain socket support
PLATFORM REQUIREMENTS:
POSIX-compliant system (Linux, BSD, macOS, etc.)
IPv6 support in kernel (for dual-stack sockets)
POSIX threads (pthread) for thread-safe error reporting
NOT portable to Windows without Winsock adaptation
SIGPIPE HANDLING (automatic - no application action required): The library handles SIGPIPE internally. All send operations use MSG_NOSIGNAL (Linux/FreeBSD), and SO_NOSIGPIPE is set at socket creation (BSD/macOS). Applications do NOT need to call signal(SIGPIPE, SIG_IGN).
Error Handling:
Socket_Failed: General socket errors
Socket_Closed: Connection terminated by peer
Some functions return NULL/0 for non-blocking EAGAIN/EWOULDBLOCK
Timeouts:
Global defaults configurable via Socket_timeouts_setdefaults()
Per-socket overrides via Socket_timeouts_set()
Applied to DNS resolution and blocking connect() paths
Definition at line 44 of file Socket.h.
Typedef Documentation
Socket_T
typedef struct Socket_T* Socket_T
Definition at line 45 of file Socket.h.
Function Documentation
Socket_accept()
Socket_T Socket_accept (Socket_T socket) extern
Socket_accept - Accept incoming connection @socket: Listening socket Returns: New socket or NULL if would block (EAGAIN/EWOULDBLOCK) Raises: Socket_Failed on error
Referenced by main().
Socket_bandwidth_wait_ms()
int64_t Socket_bandwidth_wait_ms (Socket_T socket, size_t bytes) extern
Socket_bandwidth_wait_ms - Get wait time until bandwidth available @socket: Socket to query @bytes: Number of bytes needed
Returns: Milliseconds to wait, 0 if immediate, -1 if impossible Thread-safe: Yes
Useful for event loop integration - use as poll timeout.
Socket_bind()
void Socket_bind (Socket_T socket, const char * host, int port) extern
Socket_bind - Bind socket to address and port @socket: Socket to bind @host: IP address or NULL/"0.0.0.0" for any @port: Port number (1 to SOCKET_MAX_PORT) WARNING: May block 30+ seconds during DNS resolution if hostname provided. Raises: Socket_Failed on error
Referenced by main().
Socket_bind_async()
SocketDNS_Request_T Socket_bind_async (SocketDNS_T dns, Socket_T socket, const char * host, int port) extern
Socket_bind_async - Start async DNS resolution for bind @dns: DNS resolver instance @socket: Socket to bind @host: IP address or hostname (NULL for any) @port: Port number (1 to SOCKET_MAX_PORT) Returns: DNS request handle Raises: Socket_Failed on error
Socket_bind_async_cancel()
void Socket_bind_async_cancel (SocketDNS_T dns, SocketDNS_Request_T req) extern
Socket_bind_async_cancel - Cancel pending async bind resolution @dns: DNS resolver instance @req: Request handle returned by Socket_bind_async
Socket_bind_unix()
void Socket_bind_unix (Socket_T socket, const char * path) extern
Socket_bind_unix - Bind to Unix domain socket path @socket: Socket to bind (AF_UNIX) @path: Socket file path Raises: Socket_Failed on error Note: Fails with EADDRINUSE if path exists. Max path length ~108 bytes. Supports abstract namespace sockets on Linux (path starting with '@').
Socket_bind_with_addrinfo()
void Socket_bind_with_addrinfo (Socket_T socket, struct addrinfo * res) extern
Socket_bind_with_addrinfo - Bind socket using resolved address @socket: Socket to bind @res: Resolved addrinfo result from DNS resolution Raises: Socket_Failed on error
Socket_connect()
void Socket_connect (Socket_T socket, const char * host, int port) extern
Socket_connect - Connect to remote host @socket: Socket to connect @host: Remote IP address or hostname @port: Remote port WARNING: May block 30+ seconds during DNS resolution if hostname provided. Raises: Socket_Failed on error
Referenced by main().
Socket_connect_async()
SocketDNS_Request_T Socket_connect_async (SocketDNS_T dns, Socket_T socket, const char * host, int port) extern
Socket_connect_async - Start async DNS resolution for connect @dns: DNS resolver instance @socket: Socket to connect @host: Remote IP address or hostname @port: Remote port (1 to SOCKET_MAX_PORT) Returns: DNS request handle Raises: Socket_Failed on error
Socket_connect_async_cancel()
void Socket_connect_async_cancel (SocketDNS_T dns, SocketDNS_Request_T req) extern
Socket_connect_async_cancel - Cancel pending async connect resolution @dns: DNS resolver instance @req: Request handle returned by Socket_connect_async
Socket_connect_unix()
void Socket_connect_unix (Socket_T socket, const char * path) extern
Socket_connect_unix - Connect to Unix domain socket path @socket: Socket to connect (AF_UNIX) @path: Socket file path Raises: Socket_Failed on error Note: Supports abstract namespace sockets on Linux (path starting with '@').
Socket_connect_with_addrinfo()
void Socket_connect_with_addrinfo (Socket_T socket, struct addrinfo * res) extern
Socket_connect_with_addrinfo - Connect socket using resolved address @socket: Socket to connect @res: Resolved addrinfo result from DNS resolution Raises: Socket_Failed on error
Socket_debug_live_count()
int Socket_debug_live_count (void) extern
Socket_debug_live_count - Get number of live socket instances (test-only) Returns: Current count of allocated Socket_T instances
Socket_error_is_retryable()
int Socket_error_is_retryable (int err) extern
Socket_error_is_retryable - Check if an errno indicates a retryable error @err: errno value to check
Returns: 1 if error is typically retryable, 0 if fatal Thread-safe: Yes (pure function)
This is a convenience wrapper around SocketError_is_retryable_errno() for socket-specific error handling.
Retryable errors (return 1):
ECONNREFUSED: Server not listening, may start later
ECONNRESET: Connection dropped, can reconnect
ETIMEDOUT: Timeout, may succeed on retry
ENETUNREACH: Network route may recover
EHOSTUNREACH: Host may become reachable
EAGAIN/EWOULDBLOCK: Resource temporarily unavailable
EINTR: Interrupted by signal
Fatal errors (return 0):
EACCES: Permission denied (won't change)
EADDRINUSE: Address in use (won't change)
EBADF: Bad file descriptor (programming error)
EINVAL: Invalid argument (programming error)
ENOMEM: Out of memory (system issue)
EMFILE/ENFILE: Too many open files (system limit)
Usage: TRY Socket_connect(sock, host, port); EXCEPT(Socket_Failed) if (Socket_error_is_retryable(Socket_geterrno())) // Schedule retry with backoff else // Log error and give up END_TRY;
Socket_fd()
int Socket_fd (const Socket_T socket) extern
Socket_fd - Get underlying file descriptor @socket: Socket instance Returns: File descriptor
Referenced by main().
Socket_free()
void Socket_free (Socket_T * socket) extern
Socket_free - Free a socket and close the connection @socket: Pointer to socket (will be set to NULL)
Referenced by main(), and main().
Socket_getbandwidth()
size_t Socket_getbandwidth (Socket_T socket) extern
Socket_getbandwidth - Get bandwidth limit for socket @socket: Socket to query
Returns: Bandwidth limit in bytes per second (0 if unlimited) Thread-safe: Yes
Socket_getcongestion()
int Socket_getcongestion (Socket_T socket, char * algorithm, size_t len) extern
Socket_getcongestion - Get TCP congestion control algorithm @socket: Socket to query @algorithm: Output buffer for algorithm name @len: Buffer length Returns: 0 on success, -1 on error or if not supported
Socket_getdeferaccept()
int Socket_getdeferaccept (Socket_T socket) extern
Socket_getdeferaccept - Get TCP_DEFER_ACCEPT timeout @socket: Listening socket
Returns: Current defer accept timeout in seconds, 0 if disabled Raises: Socket_Failed on error Thread-safe: Yes
Socket_getfastopen()
int Socket_getfastopen (Socket_T socket) extern
Socket_getfastopen - Get TCP Fast Open setting @socket: Socket to query Returns: 1 if enabled, 0 if disabled, -1 on error
Socket_getkeepalive()
void Socket_getkeepalive (Socket_T socket, int * idle, int * interval, int * count) extern
Socket_getkeepalive - Get TCP keepalive configuration @socket: Socket to query @idle: Output - idle timeout in seconds @interval: Output - interval between probes in seconds @count: Output - number of probes before declaring dead Raises: Socket_Failed on error
Socket_getlocaladdr()
const char * Socket_getlocaladdr (const Socket_T socket) extern
Socket_getlocaladdr - Get local IP address @socket: Socket instance Returns: IP address string (IPv4/IPv6) or "(unknown)" if unavailable Note: String is owned by socket, valid until socket freed.
Referenced by main().
Socket_getlocalport()
int Socket_getlocalport (const Socket_T socket) extern
Socket_getlocalport - Get local port number @socket: Socket instance Returns: Port number (1 to SOCKET_MAX_PORT) or 0 if unavailable
Referenced by main().
Socket_getnodelay()
int Socket_getnodelay (Socket_T socket) extern
Socket_getnodelay - Get TCP_NODELAY setting @socket: Socket to query Returns: 1 if Nagle's algorithm is disabled, 0 if enabled Raises: Socket_Failed on error
Socket_getpeeraddr()
const char * Socket_getpeeraddr (const Socket_T socket) extern
Socket_getpeeraddr - Get peer IP address @socket: Connected socket Returns: IP address string (IPv4/IPv6) or "(unknown)" if unavailable Note: String is owned by socket, valid until socket freed.
Referenced by handle_client_data(), and main().
Socket_getpeergid()
int Socket_getpeergid (const Socket_T socket) extern
Socket_getpeergid - Get peer group ID (Linux only) @socket: Connected Unix domain socket Returns: Peer group ID, or (gid_t)-1 if unavailable
Socket_getpeerpid()
int Socket_getpeerpid (const Socket_T socket) extern
Socket_getpeerpid - Get peer process ID (Linux only) @socket: Connected Unix domain socket Returns: Peer process ID, or -1 if unavailable
Socket_getpeerport()
int Socket_getpeerport (const Socket_T socket) extern
Socket_getpeerport - Get peer port number @socket: Connected socket Returns: Port number (1 to SOCKET_MAX_PORT) or 0 if unavailable
Referenced by handle_client_data(), and main().
Socket_getpeeruid()
int Socket_getpeeruid (const Socket_T socket) extern
Socket_getpeeruid - Get peer user ID (Linux only) @socket: Connected Unix domain socket Returns: Peer user ID, or (uid_t)-1 if unavailable
Socket_getrcvbuf()
int Socket_getrcvbuf (Socket_T socket) extern
Socket_getrcvbuf - Get receive buffer size @socket: Socket to query Returns: Receive buffer size in bytes Raises: Socket_Failed on error
Socket_getsndbuf()
int Socket_getsndbuf (Socket_T socket) extern
Socket_getsndbuf - Get send buffer size @socket: Socket to query Returns: Send buffer size in bytes Raises: Socket_Failed on error
Socket_gettimeout()
int Socket_gettimeout (Socket_T socket) extern
Socket_gettimeout - Get socket timeout @socket: Socket to query Returns: Timeout in seconds (0 if disabled) Raises: Socket_Failed on error
Socket_getusertimeout()
unsigned int Socket_getusertimeout (Socket_T socket) extern
Socket_getusertimeout - Get TCP user timeout @socket: Socket to query Returns: Timeout in milliseconds, or 0 on error
Socket_ignore_sigpipe()
int Socket_ignore_sigpipe (void) extern
Socket_ignore_sigpipe - Globally ignore SIGPIPE signal
NOTE: This function is NOT required when using this library. The library handles SIGPIPE internally via:
MSG_NOSIGNAL flag on send operations (Linux/FreeBSD)
SO_NOSIGPIPE socket option at creation (BSD/macOS)
This convenience function is provided for:
Legacy code migration (applications that previously handled SIGPIPE)
Applications mixing this library with raw socket code
Defense-in-depth preference
Returns: 0 on success, -1 on error (sets errno) Thread-safe: Yes (can be called from any thread, idempotent)
Usage: // Optional - call once at program startup if desired Socket_ignore_sigpipe();
IMPORTANT: Do not call this if your application needs to handle SIGPIPE for other purposes (e.g., detecting broken pipes in shell pipelines).
Socket_isbound()
int Socket_isbound (Socket_T socket) extern
Socket_isbound - Check if socket is bound to an address @socket: Socket to check Returns: 1 if bound, 0 if not bound Thread-safe: Yes
Socket_isconnected()
int Socket_isconnected (Socket_T socket) extern
Socket_isconnected - Check if socket is connected @socket: Socket to check Returns: 1 if connected, 0 if not connected Thread-safe: Yes
Socket_islistening()
int Socket_islistening (Socket_T socket) extern
Socket_islistening - Check if socket is listening for connections @socket: Socket to check Returns: 1 if listening, 0 if not listening Thread-safe: Yes
Socket_listen()
void Socket_listen (Socket_T socket, int backlog) extern
Socket_listen - Listen for incoming connections @socket: Bound socket @backlog: Maximum pending connections Raises: Socket_Failed on error
Referenced by main().
Socket_new()
Socket_T Socket_new (int domain, int type, int protocol) extern
Referenced by main(), and main().
Socket_new_from_fd()
Socket_T Socket_new_from_fd (int fd) extern
Socket_new_from_fd - Create Socket_T from existing file descriptor @fd: File descriptor (must be valid socket, will be set to non-blocking) Returns: New Socket_T instance or NULL on failure Raises: Socket_Failed on error Thread-safe: Yes - returns new instance
Socket_recv()
ssize_t Socket_recv (Socket_T socket, void * buf, size_t len) extern
Socket_recv - Receive data @socket: Connected socket @buf: Buffer for received data @len: Buffer size (> 0) Returns: Bytes received (> 0) or 0 if would block (EAGAIN/EWOULDBLOCK) Raises: Socket_Closed on peer close or ECONNRESET, Socket_Failed on other
Referenced by handle_client_data(), and main().
Socket_recv_limited()
ssize_t Socket_recv_limited (Socket_T socket, void * buf, size_t len) extern
Socket_recv_limited - Receive data with bandwidth limiting @socket: Connected socket @buf: Buffer for received data @len: Buffer size (> 0)
Returns: Bytes received (> 0), 0 if rate limited or would block, or raises Raises: Socket_Closed on peer close, Socket_Failed on other errors Thread-safe: Yes - uses socket's bandwidth limiter
Like Socket_recv() but respects bandwidth limit set by Socket_setbandwidth(). If bandwidth limiting is disabled (0), behaves like Socket_recv().
Socket_recvall()
ssize_t Socket_recvall (Socket_T socket, void * buf, size_t len) extern
Socket_recvall - Receive all requested data (handles partial receives) @socket: Connected socket @buf: Buffer for received data @len: Buffer size (> 0) Returns: Total bytes received (always equals len on success) Raises: Socket_Closed on peer close or ECONNRESET, Socket_Failed on other
Socket_recvfd()
int Socket_recvfd (Socket_T socket, int * fd_received) extern
Socket_recvfd - Receive a file descriptor over Unix domain socket @socket: Connected Unix domain socket (AF_UNIX) @fd_received: Output pointer for received file descriptor
Returns: 1 on success, 0 if would block (EAGAIN/EWOULDBLOCK) Raises: Socket_Failed on error, Socket_Closed on disconnect
Receives a file descriptor from the peer process via SCM_RIGHTS. The received fd is owned by this process and must be closed when done.
OWNERSHIP: Caller takes ownership of the received fd and MUST close it.
Thread-safe: Yes (uses thread-local error buffers)
Socket_recvfds()
int Socket_recvfds (Socket_T socket, int * fds, size_t max_count, size_t * received_count) extern
Socket_recvfds - Receive multiple file descriptors @socket: Connected Unix domain socket (AF_UNIX) @fds: Output array for received descriptors (must have max_count capacity) @max_count: Maximum descriptors to receive @received_count: Output for actual count received
Returns: 1 on success, 0 if would block (EAGAIN/EWOULDBLOCK) Raises: Socket_Failed on error, Socket_Closed on disconnect
Receives multiple file descriptors from a single message. On success, *received_count contains the number of fds received.
OWNERSHIP: Caller takes ownership of all received fds and MUST close them.
Thread-safe: Yes (uses thread-local error buffers)
Socket_recvmsg()
ssize_t Socket_recvmsg (Socket_T socket, struct msghdr * msg, int flags) extern
Socket_recvmsg - Receive message with ancillary data (recvmsg wrapper) @socket: Connected socket @msg: Message structure for data, address, and ancillary data @flags: Message flags (MSG_DONTWAIT, MSG_PEEK, etc.) Returns: Total bytes received (> 0) or 0 if would block Raises: Socket_Closed on peer close or ECONNRESET, Socket_Failed on other
Socket_recvv()
ssize_t Socket_recvv (Socket_T socket, struct iovec * iov, int iovcnt) extern
Socket_recvv - Scatter/gather receive (readv wrapper) @socket: Connected socket @iov: Array of iovec structures @iovcnt: Number of iovec structures (> 0, <= IOV_MAX) Returns: Total bytes received (> 0) or 0 if would block Raises: Socket_Closed on peer close or ECONNRESET, Socket_Failed on other
Socket_recvvall()
ssize_t Socket_recvvall (Socket_T socket, struct iovec * iov, int iovcnt) extern
Socket_recvvall - Scatter/gather receive all (handles partial receives) @socket: Connected socket @iov: Array of iovec structures @iovcnt: Number of iovec structures (> 0, <= IOV_MAX) Returns: Total bytes received (always equals sum of all iov_len on success) Raises: Socket_Closed on peer close or ECONNRESET, Socket_Failed on other
Socket_send()
ssize_t Socket_send (Socket_T socket, const void * buf, size_t len) extern
Socket_send - Send data @socket: Connected socket @buf: Data to send @len: Length of data (> 0) Returns: Bytes sent (> 0) or 0 if would block (EAGAIN/EWOULDBLOCK) Raises: Socket_Closed on EPIPE/ECONNRESET, Socket_Failed on other errors
Socket_send_limited()
ssize_t Socket_send_limited (Socket_T socket, const void * buf, size_t len) extern
Socket_send_limited - Send data with bandwidth limiting @socket: Connected socket @buf: Data to send @len: Length of data (> 0)
Returns: Bytes sent (> 0), 0 if rate limited (try again later), or raises Raises: Socket_Closed on EPIPE/ECONNRESET, Socket_Failed on other errors Thread-safe: Yes - uses socket's bandwidth limiter
Like Socket_send() but respects bandwidth limit set by Socket_setbandwidth(). If bandwidth limiting is disabled (0), behaves like Socket_send(). If rate limited, returns 0 and caller should wait before retrying. Use Socket_bandwidth_wait_ms() to get recommended wait time.
Socket_sendall()
ssize_t Socket_sendall (Socket_T socket, const void * buf, size_t len) extern
Socket_sendall - Send all data (handles partial sends) @socket: Connected socket @buf: Data to send @len: Length of data (> 0) Returns: Total bytes sent (always equals len on success) Raises: Socket_Closed on EPIPE/ECONNRESET, Socket_Failed on other errors
Referenced by handle_client_data(), and main().
Socket_sendfd()
int Socket_sendfd (Socket_T socket, int fd_to_pass) extern
Socket_sendfd - Send a file descriptor over Unix domain socket @socket: Connected Unix domain socket (AF_UNIX) @fd_to_pass: File descriptor to pass (must be >= 0)
Returns: 1 on success, 0 if would block (EAGAIN/EWOULDBLOCK) Raises: Socket_Failed on error, Socket_Closed on disconnect
Passes a single file descriptor to the peer process using SCM_RIGHTS. The receiving process gets a new fd referring to the same kernel object.
PLATFORM REQUIREMENTS:
POSIX-compliant Unix domain socket (AF_UNIX)
NOT available on Windows
SECURITY NOTES:
Only works with connected Unix domain sockets
Receiving process should validate the fd type before use
Thread-safe: Yes (uses thread-local error buffers)
Socket_sendfds()
int Socket_sendfds (Socket_T socket, const int * fds, size_t count) extern
Socket_sendfds - Send multiple file descriptors @socket: Connected Unix domain socket (AF_UNIX) @fds: Array of file descriptors to pass (all must be >= 0) @count: Number of descriptors (1 to SOCKET_MAX_FDS_PER_MSG)
Returns: 1 on success, 0 if would block (EAGAIN/EWOULDBLOCK) Raises: Socket_Failed on error, Socket_Closed on disconnect
Passes multiple file descriptors atomically in a single message. All descriptors are either sent together or none are sent.
Thread-safe: Yes (uses thread-local error buffers)
Socket_sendfile()
ssize_t Socket_sendfile (Socket_T socket, int file_fd, off_t * offset, size_t count) extern
Socket_sendfile - Zero-copy file-to-socket transfer @socket: Connected socket to send to @file_fd: File descriptor to read from (must be a regular file) @offset: File offset to start reading from (NULL for current position) @count: Number of bytes to transfer (0 for entire file from offset) Returns: Total bytes transferred (> 0) or 0 if would block Raises: Socket_Closed on EPIPE/ECONNRESET, Socket_Failed on other errors
Socket_sendfileall()
ssize_t Socket_sendfileall (Socket_T socket, int file_fd, off_t * offset, size_t count) extern
Socket_sendfileall - Zero-copy file-to-socket transfer (handles partial) @socket: Connected socket to send to @file_fd: File descriptor to read from (must be a regular file) @offset: File offset to start reading from (NULL for current position) @count: Number of bytes to transfer (0 for entire file from offset) Returns: Total bytes transferred (always equals count on success) Raises: Socket_Closed on EPIPE/ECONNRESET, Socket_Failed on other errors
Socket_sendmsg()
ssize_t Socket_sendmsg (Socket_T socket, const struct msghdr * msg, int flags) extern
Socket_sendmsg - Send message with ancillary data (sendmsg wrapper) @socket: Connected socket @msg: Message structure with data, address, and ancillary data @flags: Message flags (MSG_NOSIGNAL, MSG_DONTWAIT, etc.) Returns: Total bytes sent (> 0) or 0 if would block Raises: Socket_Closed on EPIPE/ECONNRESET, Socket_Failed on other errors
Socket_sendv()
ssize_t Socket_sendv (Socket_T socket, const struct iovec * iov, int iovcnt) extern
Socket_sendv - Scatter/gather send (writev wrapper) @socket: Connected socket @iov: Array of iovec structures @iovcnt: Number of iovec structures (> 0, <= IOV_MAX) Returns: Total bytes sent (> 0) or 0 if would block Raises: Socket_Closed on EPIPE/ECONNRESET, Socket_Failed on other errors
Socket_sendvall()
ssize_t Socket_sendvall (Socket_T socket, const struct iovec * iov, int iovcnt) extern
Socket_sendvall - Scatter/gather send all (handles partial sends) @socket: Connected socket @iov: Array of iovec structures @iovcnt: Number of iovec structures (> 0, <= IOV_MAX) Returns: Total bytes sent (always equals sum of all iov_len on success) Raises: Socket_Closed on EPIPE/ECONNRESET, Socket_Failed on other errors
Socket_setbandwidth()
void Socket_setbandwidth (Socket_T socket, size_t bytes_per_sec) extern
Socket_setbandwidth - Set bandwidth limit for socket @socket: Socket to modify @bytes_per_sec: Maximum bytes per second (0 to disable limiting)
Raises: Socket_Failed on allocation failure Thread-safe: Yes - uses internal mutex
Enables bandwidth throttling using a token bucket algorithm. The burst capacity is set to bytes_per_sec (1 second of data). Use Socket_send_limited() for rate-limited sending.
Socket_setcloexec()
void Socket_setcloexec (Socket_T socket, int enable) extern
Socket_setcloexec - Control close-on-exec flag @socket: Socket to modify @enable: 1 to enable CLOEXEC, 0 to disable Raises: Socket_Failed on error
Socket_setcongestion()
void Socket_setcongestion (Socket_T socket, const char * algorithm) extern
Socket_setcongestion - Set TCP congestion control algorithm @socket: Socket to modify @algorithm: Algorithm name (e.g., "cubic", "reno", "bbr") Raises: Socket_Failed on error or if not supported Note: Only available on Linux 2.6.13+.
Socket_setdeferaccept()
void Socket_setdeferaccept (Socket_T socket, int timeout_sec) extern
Socket_setdeferaccept - Enable TCP_DEFER_ACCEPT @socket: Listening socket @timeout_sec: Seconds to wait for data before completing accept (0 to disable, max platform-specific)
Delays accept() completion until client sends data, preventing SYN-only connections from consuming application resources. This is a key defense against SYN flood attacks.
Linux: Uses TCP_DEFER_ACCEPT socket option BSD/macOS: Uses SO_ACCEPTFILTER with "dataready" filter
Raises: Socket_Failed on error or if unsupported Thread-safe: Yes
Socket_setfastopen()
void Socket_setfastopen (Socket_T socket, int enable) extern
Socket_setfastopen - Enable TCP Fast Open @socket: Socket to modify @enable: 1 to enable, 0 to disable Raises: Socket_Failed on error or if not supported
Socket_setkeepalive()
void Socket_setkeepalive (Socket_T socket, int idle, int interval, int count) extern
Socket_setkeepalive - Enable TCP keepalive @socket: Socket to modify @idle: Seconds before sending keepalive probes @interval: Interval between keepalive probes @count: Number of probes before declaring dead Raises: Socket_Failed on error
Socket_setnodelay()
void Socket_setnodelay (Socket_T socket, int nodelay) extern
Socket_setnodelay - Disable Nagle's algorithm @socket: Socket to modify @nodelay: 1 to disable Nagle, 0 to enable Raises: Socket_Failed on error
Socket_setnonblocking()
void Socket_setnonblocking (Socket_T socket) extern
Socket_setnonblocking - Enable non-blocking mode @socket: Socket to modify Raises: Socket_Failed on error
Referenced by main().
Socket_setrcvbuf()
void Socket_setrcvbuf (Socket_T socket, int size) extern
Socket_setrcvbuf - Set receive buffer size @socket: Socket to modify @size: Buffer size in bytes (> 0) Raises: Socket_Failed on error
Socket_setreuseaddr()
void Socket_setreuseaddr (Socket_T socket) extern
Socket_setreuseaddr - Enable address reuse @socket: Socket to modify Raises: Socket_Failed on error
Referenced by main().
Socket_setreuseport()
void Socket_setreuseport (Socket_T socket) extern
Socket_setreuseport - Enable port reuse across sockets @socket: Socket to modify Raises: Socket_Failed on error (or if SO_REUSEPORT unsupported)
Socket_setsndbuf()
void Socket_setsndbuf (Socket_T socket, int size) extern
Socket_setsndbuf - Set send buffer size @socket: Socket to modify @size: Buffer size in bytes (> 0) Raises: Socket_Failed on error
Socket_settimeout()
void Socket_settimeout (Socket_T socket, int timeout_sec) extern
Socket_settimeout - Set socket timeout @socket: Socket to modify @timeout_sec: Timeout in seconds (0 to disable) Sets both send and receive timeouts Raises: Socket_Failed on error
Socket_setusertimeout()
void Socket_setusertimeout (Socket_T socket, unsigned int timeout_ms) extern
Socket_setusertimeout - Set TCP user timeout @socket: Socket to modify @timeout_ms: Timeout in milliseconds (> 0) Raises: Socket_Failed on error or if not supported Note: Only available on Linux 2.6.37+.
Socket_shutdown()
void Socket_shutdown (Socket_T socket, int how) extern
Socket_shutdown - Disable further sends and/or receives @socket: Connected socket @how: Shutdown mode (SHUT_RD, SHUT_WR, or SHUT_RDWR) Raises: Socket_Failed on error
Socket_timeouts_get()
void Socket_timeouts_get (const Socket_T socket, SocketTimeouts_T * timeouts) extern
Socket_timeouts_get - Retrieve per-socket timeout configuration @socket: Socket instance @timeouts: Output timeout structure
Socket_timeouts_get_extended()
void Socket_timeouts_get_extended (const Socket_T socket, SocketTimeouts_Extended_T * extended) extern
Socket_timeouts_get_extended - Retrieve per-socket extended timeout configuration @socket: Socket to query @extended: Output structure for extended timeouts
Retrieves the current extended timeout configuration. If extended timeouts haven't been set, returns the basic timeouts mapped to the extended structure.
Thread-safe: No - caller must ensure exclusive access
Socket_timeouts_getdefaults()
void Socket_timeouts_getdefaults (SocketTimeouts_T * timeouts) extern
Socket_timeouts_getdefaults - Get global default timeouts @timeouts: Output timeout structure containing current defaults
Socket_timeouts_set()
void Socket_timeouts_set (Socket_T socket, const SocketTimeouts_T * timeouts) extern
Socket_timeouts_set - Set per-socket timeout configuration @socket: Socket instance @timeouts: Timeout configuration (NULL to reset to defaults)
Socket_timeouts_set_extended()
void Socket_timeouts_set_extended (Socket_T socket, const SocketTimeouts_Extended_T * extended) extern
Socket_timeouts_set_extended - Set per-socket extended timeout configuration @socket: Socket to modify @extended: Extended per-phase timeout configuration
Sets granular per-phase timeouts for advanced use cases. The extended timeouts provide finer control than SocketTimeouts_T, allowing different timeouts for DNS, connect, TLS, and request phases.
Values of 0 in the extended structure mean "inherit from basic timeouts". Values of -1 mean "no timeout (infinite)".
Thread-safe: No - caller must ensure exclusive access
Socket_timeouts_setdefaults()
void Socket_timeouts_setdefaults (const SocketTimeouts_T * timeouts) extern
Socket_timeouts_setdefaults - Set global default timeouts @timeouts: New default timeout configuration
SocketPair_new()
void SocketPair_new (int type, Socket_T * socket1, Socket_T * socket2) extern
SocketPair_new - Create a pair of connected Unix domain sockets @type: Socket type (SOCK_STREAM or SOCK_DGRAM) @socket1: Output - first socket of the pair @socket2: Output - second socket of the pair Raises: Socket_Failed on error Thread-safe: Yes (creates new sockets) Note: Creates two connected Unix domain sockets for IPC. Both sockets are ready to use - no bind/connect needed.
SocketUnix_bind()
void SocketUnix_bind (SocketBase_T base, const char * path, Except_T exc_type) extern
SocketUnix_connect()
void SocketUnix_connect (SocketBase_T base, const char * path, Except_T exc_type) extern
SocketUnix_validate_unix_path()
int SocketUnix_validate_unix_path (const char * path, size_t path_len) extern
Variable Documentation
Socket_Closed
const Except_T Socket_Closed extern
Socket_Closed - Connection closed by peer
Category: NETWORK Retryable: Yes - indicates graceful close or reset, reconnect may succeed
Raised when:
recv() returns 0 (graceful close)
ECONNRESET during I/O (connection reset)
EPIPE during send (broken pipe)
This is a normal condition for connection-oriented sockets.
Referenced by handle_client_data().
Socket_Failed
const Except_T Socket_Failed extern
Socket_Failed - General socket operation failure
Category: NETWORK (usually) or PROTOCOL (configuration errors) Retryable: Depends on errno - use Socket_error_is_retryable() to check
Raised for:
Socket creation failures (socket(), bind(), listen(), accept())
Connection failures (connect())
I/O failures (send(), recv())
Option setting failures (setsockopt())
Check errno via Socket_geterrno() for specific error code.
Referenced by handle_client_data(), main(), and main().
SocketUnix_Failed
const Except_T SocketUnix_Failed extern
SocketUnix_Failed - Unix domain socket operation failure
Category: NETWORK or APPLICATION Retryable: Depends on errno
Raised for Unix domain socket specific errors:
Path too long
Socket file doesn't exist (ENOENT)
Permission denied (EACCES)