SocketReconnect-private.h File Reference
SocketReconnect-private.h File Reference
Connection Management Modules
Internal implementation details for automatic reconnection framework.
#include "core/Arena.h"
#include "core/SocketCrypto.h"
#include "core/SocketUtil.h"
#include "socket/Socket.h"
#include "socket/SocketReconnect.h"
#include <stdint.h>
Data Structures
struct SocketReconnect_T
Opaque context for managing reconnecting socket connections.
Macros
#define SOCKET_RECONNECT_ERROR_BUFSIZE 256
Maximum length for internal error messages.
#define SOCKET_RECONNECT_MAX_HOST_LEN 255
Maximum length for hostname strings (excluding null terminator).
Enumerations
enum SocketReconnect_CircuitState {
CIRCUIT_CLOSED = 0 ,
CIRCUIT_OPEN ,
CIRCUIT_HALF_OPEN
}
Internal circuit breaker states used in reconnection logic.
Functions
static int64_t socketreconnect_get_time_ms (void)
Get current monotonic time in milliseconds.
static int64_t socketreconnect_elapsed_ms (int64_t start_ms)
Calculate elapsed time since a start timestamp.
static double socketreconnect_random_double (void)
Generate a random double in [0.0, 1.0) for backoff jitter.
Detailed Description
Internal implementation details for automatic reconnection framework.
Definition in file SocketReconnect-private.h.
Macro Definition Documentation
SOCKET_RECONNECT_ERROR_BUFSIZE
#define SOCKET_RECONNECT_ERROR_BUFSIZE 256
Maximum length for internal error messages.
Note
Fixed size to avoid dynamic allocation in hot paths.
Definition at line 37 of file SocketReconnect-private.h.
SOCKET_RECONNECT_MAX_HOST_LEN
#define SOCKET_RECONNECT_MAX_HOST_LEN 255
Maximum length for hostname strings (excluding null terminator).
Note
Matches standard DNS name limits, sufficient for IPv6 literals.
Definition at line 46 of file SocketReconnect-private.h.
Function Documentation
socketreconnect_elapsed_ms()
static int64_t socketreconnect_elapsed_ms (int64_t start_ms) inline static
Calculate elapsed time since a start timestamp.
Thread Safety\n Yes - simple arithmetic on input values.
Parameters
start_ms Start time from socketreconnect_get_time_ms().
Returns
Elapsed milliseconds since start (non-negative).
Uses monotonic time to ensure accurate, non-decreasing measurements.
See also
socketreconnect_get_time_ms() for timestamp acquisition.
Definition at line 167 of file SocketReconnect-private.h.
References socketreconnect_get_time_ms().
socketreconnect_get_time_ms()
static int64_t socketreconnect_get_time_ms (void) inline static
Get current monotonic time in milliseconds.
Thread Safety\n Yes - reentrant system clock query.
Returns
Current monotonic time in milliseconds (int64_t).
Internal helper using Socket_get_monotonic_ms() to ensure monotonic time resistant to system clock adjustments.
See also
Socket_get_monotonic_ms() in SocketUtil for details.
socketreconnect_elapsed_ms() for elapsed time calculation.
Definition at line 150 of file SocketReconnect-private.h.
References Socket_get_monotonic_ms().
Referenced by socketreconnect_elapsed_ms().
socketreconnect_random_double()
static double socketreconnect_random_double (void) inline static
Generate a random double in [0.0, 1.0) for backoff jitter.
Returns
Random double value in [0.0, 1.0).
Prefers cryptographically secure randomness via SocketCrypto_random_bytes(). Falls back to thread-local xorshift PRNG seeded by monotonic time. Intended only for non-cryptographic use like exponential backoff jitter.
Note
Thread-safe: Uses thread-local storage for fallback PRNG seed.
Warning
Not suitable for security-sensitive randomness.
See also
SocketCrypto_random_bytes() for secure source.
SocketReconnect_Policy_T::jitter for policy integration.
socketreconnect_get_time_ms() for time-based seeding.
Definition at line 190 of file SocketReconnect-private.h.
References Socket_get_monotonic_ms(), and SocketCrypto_random_bytes().