SocketProxy.h File Reference
SocketProxy.h File Reference
#include <stddef.h>
#include "core/Arena.h"
#include "core/Except.h"
#include "dns/SocketDNS.h"
#include "poll/SocketPoll.h"
#include "socket/Socket.h"
#include "tls/SocketTLSContext.h"
Data Structures
struct SocketProxy_Config
SocketProxy_Config - Proxy configuration.
Macros
#define T SocketProxy_Conn_T
#define SOCKET_PROXY_DEFAULT_CONNECT_TIMEOUT_MS 30000
Default timeout for connecting to proxy server (ms)
#define SOCKET_PROXY_DEFAULT_HANDSHAKE_TIMEOUT_MS 30000
Default timeout for proxy handshake (ms)
#define SOCKET_PROXY_MAX_HOSTNAME_LEN 255
Maximum hostname length for SOCKS5 (RFC 1928)
#define SOCKET_PROXY_MAX_USERNAME_LEN 255
Maximum username length for SOCKS5 (RFC 1929)
#define SOCKET_PROXY_MAX_PASSWORD_LEN 255
Maximum password length for SOCKS5 (RFC 1929)
#define SOCKET_PROXY_DEFAULT_SOCKS_PORT 1080
Default SOCKS port.
#define SOCKET_PROXY_DEFAULT_HTTP_PORT 8080
Default HTTP proxy port.
#define SOCKET_PROXY_DEFAULT_HTTPS_PORT 8080
Default HTTPS proxy port.
Typedefs
typedef struct SocketHTTP_Headers * SocketHTTP_Headers_T
typedef struct SocketProxy_Conn_T * SocketProxy_Conn_T
Enumerations
enum SocketProxyType {
SOCKET_PROXY_NONE = 0 ,
SOCKET_PROXY_HTTP ,
SOCKET_PROXY_HTTPS ,
SOCKET_PROXY_SOCKS4 ,
SOCKET_PROXY_SOCKS4A ,
SOCKET_PROXY_SOCKS5 ,
SOCKET_PROXY_SOCKS5H
}
SocketProxyType - Supported proxy protocol types.
enum SocketProxy_Result {
PROXY_OK = 0 ,
PROXY_IN_PROGRESS ,
PROXY_ERROR ,
PROXY_ERROR_CONNECT ,
PROXY_ERROR_AUTH_REQUIRED ,
PROXY_ERROR_AUTH_FAILED ,
PROXY_ERROR_FORBIDDEN ,
PROXY_ERROR_HOST_UNREACHABLE ,
PROXY_ERROR_NETWORK_UNREACHABLE ,
PROXY_ERROR_CONNECTION_REFUSED ,
PROXY_ERROR_TTL_EXPIRED ,
PROXY_ERROR_PROTOCOL ,
PROXY_ERROR_UNSUPPORTED ,
PROXY_ERROR_TIMEOUT ,
PROXY_ERROR_CANCELLED
}
SocketProxy_Result - Proxy operation result codes.
enum SocketProxy_State {
PROXY_STATE_IDLE = 0 ,
PROXY_STATE_CONNECTING_PROXY ,
PROXY_STATE_TLS_TO_PROXY ,
PROXY_STATE_HANDSHAKE_SEND ,
PROXY_STATE_HANDSHAKE_RECV ,
PROXY_STATE_AUTH_SEND ,
PROXY_STATE_AUTH_RECV ,
PROXY_STATE_CONNECTED ,
PROXY_STATE_FAILED ,
PROXY_STATE_CANCELLED
}
SocketProxy_State - Proxy connection state machine.
Functions
void SocketProxy_config_defaults (SocketProxy_Config *config)
SocketProxy_config_defaults - Initialize config with defaults @config: Configuration structure to initialize.
int SocketProxy_parse_url (const char *url, SocketProxy_Config *config, Arena_T arena)
SocketProxy_parse_url - Parse proxy URL into config @url: Proxy URL (e.g., "socks5://user:pass@proxy:1080") @config: Output configuration @arena: Arena for string allocation (NULL to use static buffer)
Socket_T SocketProxy_connect (const SocketProxy_Config *proxy, const char *target_host, int target_port)
SocketProxy_connect - Connect to target through proxy (blocking) @proxy: Proxy configuration @target_host: Target hostname or IP @target_port: Target port (1-65535)
SocketProxy_Result SocketProxy_tunnel (Socket_T socket, const SocketProxy_Config *proxy, const char *target_host, int target_port)
SocketProxy_tunnel - Establish tunnel on existing socket (blocking) @socket: Already-connected socket to proxy server @proxy: Proxy configuration (type, auth, timeouts) @target_host: Target hostname or IP @target_port: Target port (1-65535)
SocketProxy_Conn_T SocketProxy_Conn_start (SocketDNS_T dns, SocketPoll_T poll, const SocketProxy_Config *proxy, const char *target_host, int target_port)
SocketProxy_Conn_start - Start truly async proxy connection (event-driven) @dns: DNS resolver instance (caller-owned, must outlive operation) @poll: Poll instance for connection monitoring (caller-owned) @proxy: Proxy configuration @target_host: Target hostname or IP @target_port: Target port (1-65535)
SocketProxy_Conn_T SocketProxy_Conn_new (const SocketProxy_Config *proxy, const char *target_host, int target_port)
SocketProxy_Conn_new - Start async proxy connection (blocking connect) @proxy: Proxy configuration @target_host: Target hostname or IP @target_port: Target port (1-65535)
int SocketProxy_Conn_poll (SocketProxy_Conn_T conn)
SocketProxy_Conn_poll - Check if operation is complete @conn: Proxy connection context.
void SocketProxy_Conn_process (SocketProxy_Conn_T conn)
SocketProxy_Conn_process - Process async connection @conn: Proxy connection context.
Socket_T SocketProxy_Conn_socket (SocketProxy_Conn_T conn)
SocketProxy_Conn_socket - Get tunneled socket from completed operation @conn: Proxy connection context.
void SocketProxy_Conn_cancel (SocketProxy_Conn_T conn)
SocketProxy_Conn_cancel - Cancel in-progress operation @conn: Proxy connection context.
void SocketProxy_Conn_free (SocketProxy_Conn_T *conn)
SocketProxy_Conn_free - Free proxy connection context @conn: Pointer to context (will be set to NULL)
SocketProxy_State SocketProxy_Conn_state (SocketProxy_Conn_T conn)
SocketProxy_Conn_state - Get current connection state @conn: Proxy connection context.
SocketProxy_Result SocketProxy_Conn_result (SocketProxy_Conn_T conn)
SocketProxy_Conn_result - Get result after completion @conn: Proxy connection context.
const char * SocketProxy_Conn_error (SocketProxy_Conn_T conn)
SocketProxy_Conn_error - Get error message for failed operation @conn: Proxy connection context.
int SocketProxy_Conn_fd (SocketProxy_Conn_T conn)
SocketProxy_Conn_fd - Get file descriptor for poll @conn: Proxy connection context.
unsigned SocketProxy_Conn_events (SocketProxy_Conn_T conn)
SocketProxy_Conn_events - Get events to poll for @conn: Proxy connection context.
int SocketProxy_Conn_next_timeout_ms (SocketProxy_Conn_T conn)
SocketProxy_Conn_next_timeout_ms - Get time until next timeout @conn: Proxy connection context.
const char * SocketProxy_result_string (SocketProxy_Result result)
SocketProxy_result_string - Get human-readable result description.
const char * SocketProxy_state_string (SocketProxy_State state)
SocketProxy_state_string - Get human-readable state name @state: State value.
const char * SocketProxy_type_string (SocketProxyType type)
SocketProxy_type_string - Get human-readable proxy type name @type: Proxy type.
Variables
const Except_T SocketProxy_Failed
SocketProxy_Failed - General proxy operation failure.
Data Structure Documentation
SocketProxy_Config
struct SocketProxy_Config
SocketProxy_Config - Proxy configuration.
All strings are borrowed (not copied) - caller must ensure they remain valid for the duration of the proxy operation.
Definition at line 242 of file SocketProxy.h.
Data Fields
int connect_timeout_ms Timeout connecting to proxy.
SocketHTTP_Headers_T extra_headers Additional headers (optional)
int handshake_timeout_ms Timeout for proxy handshake.
const char * host Proxy hostname or IP.
const char * password Password for SOCKS5/HTTP Basic auth.
int port Proxy port (0 = default for type)
SocketTLSContext_T * tls_ctx TLS context for HTTPS proxies (NULL = use secure defaults)
SocketProxyType type Proxy type.
const char * username Username for SOCKS5/HTTP Basic auth.
Macro Definition Documentation
SOCKET_PROXY_DEFAULT_CONNECT_TIMEOUT_MS
#define SOCKET_PROXY_DEFAULT_CONNECT_TIMEOUT_MS 30000
Default timeout for connecting to proxy server (ms)
Definition at line 122 of file SocketProxy.h.
SOCKET_PROXY_DEFAULT_HANDSHAKE_TIMEOUT_MS
#define SOCKET_PROXY_DEFAULT_HANDSHAKE_TIMEOUT_MS 30000
Default timeout for proxy handshake (ms)
Definition at line 127 of file SocketProxy.h.
SOCKET_PROXY_DEFAULT_HTTP_PORT
#define SOCKET_PROXY_DEFAULT_HTTP_PORT 8080
Default HTTP proxy port.
Definition at line 152 of file SocketProxy.h.
SOCKET_PROXY_DEFAULT_HTTPS_PORT
#define SOCKET_PROXY_DEFAULT_HTTPS_PORT 8080
Default HTTPS proxy port.
Definition at line 157 of file SocketProxy.h.
SOCKET_PROXY_DEFAULT_SOCKS_PORT
#define SOCKET_PROXY_DEFAULT_SOCKS_PORT 1080
Default SOCKS port.
Definition at line 147 of file SocketProxy.h.
SOCKET_PROXY_MAX_HOSTNAME_LEN
#define SOCKET_PROXY_MAX_HOSTNAME_LEN 255
Maximum hostname length for SOCKS5 (RFC 1928)
Definition at line 132 of file SocketProxy.h.
SOCKET_PROXY_MAX_PASSWORD_LEN
#define SOCKET_PROXY_MAX_PASSWORD_LEN 255
Maximum password length for SOCKS5 (RFC 1929)
Definition at line 142 of file SocketProxy.h.
SOCKET_PROXY_MAX_USERNAME_LEN
#define SOCKET_PROXY_MAX_USERNAME_LEN 255
Maximum username length for SOCKS5 (RFC 1929)
Definition at line 137 of file SocketProxy.h.
T
#define T SocketProxy_Conn_T
Definition at line 101 of file SocketProxy.h.
Typedef Documentation
SocketHTTP_Headers_T
typedef struct SocketHTTP_Headers* SocketHTTP_Headers_T
Definition at line 95 of file SocketProxy.h.
SocketProxy_Conn_T
typedef struct SocketProxy_Conn_T* SocketProxy_Conn_T
Definition at line 102 of file SocketProxy.h.
Enumeration Type Documentation
SocketProxy_Result
enum SocketProxy_Result
SocketProxy_Result - Proxy operation result codes.
Maps protocol-specific errors to unified result codes.
Enumerator
PROXY_OK
Success - tunnel established.
PROXY_IN_PROGRESS
Operation in progress (async)
PROXY_ERROR
Generic error.
PROXY_ERROR_CONNECT
Failed to connect to proxy.
PROXY_ERROR_AUTH_REQUIRED
Proxy requires authentication.
PROXY_ERROR_AUTH_FAILED
Authentication rejected.
PROXY_ERROR_FORBIDDEN
Proxy refused connection to target.
PROXY_ERROR_HOST_UNREACHABLE
Target host unreachable.
PROXY_ERROR_NETWORK_UNREACHABLE
Target network unreachable.
PROXY_ERROR_CONNECTION_REFUSED
Target connection refused.
PROXY_ERROR_TTL_EXPIRED
TTL expired.
PROXY_ERROR_PROTOCOL
Protocol error.
PROXY_ERROR_UNSUPPORTED
Unsupported command/feature.
PROXY_ERROR_TIMEOUT
Operation timed out.
PROXY_ERROR_CANCELLED
Operation cancelled.
Definition at line 187 of file SocketProxy.h.
SocketProxy_State
enum SocketProxy_State
SocketProxy_State - Proxy connection state machine.
State transitions: IDLE -> CONNECTING_PROXY -> HANDSHAKE_* -> CONNECTED (success) -> FAILED (error) Any state -> CANCELLED (explicit cancel)
Enumerator
PROXY_STATE_IDLE
Not started.
PROXY_STATE_CONNECTING_PROXY
Connecting to proxy (HappyEyeballs)
PROXY_STATE_TLS_TO_PROXY
TLS handshake to proxy (HTTPS)
PROXY_STATE_HANDSHAKE_SEND
Sending protocol request.
PROXY_STATE_HANDSHAKE_RECV
Receiving protocol response.
PROXY_STATE_AUTH_SEND
Sending SOCKS5 auth.
PROXY_STATE_AUTH_RECV
Receiving SOCKS5 auth response.
PROXY_STATE_CONNECTED
Tunnel established.
PROXY_STATE_FAILED
Error occurred.
PROXY_STATE_CANCELLED
User cancelled.
Definition at line 218 of file SocketProxy.h.
SocketProxyType
enum SocketProxyType
SocketProxyType - Supported proxy protocol types.
Enumerator
SOCKET_PROXY_NONE
No proxy (direct connection)
SOCKET_PROXY_HTTP
HTTP CONNECT proxy.
SOCKET_PROXY_HTTPS
HTTPS CONNECT proxy (TLS to proxy)
SOCKET_PROXY_SOCKS4
SOCKS4 proxy (IPv4 only)
SOCKET_PROXY_SOCKS4A
SOCKS4a proxy (hostname at proxy)
SOCKET_PROXY_SOCKS5
SOCKS5 proxy (RFC 1928)
SOCKET_PROXY_SOCKS5H
SOCKS5 with hostname at proxy.
Definition at line 167 of file SocketProxy.h.
Function Documentation
SocketProxy_config_defaults()
void SocketProxy_config_defaults (SocketProxy_Config * config) extern
SocketProxy_config_defaults - Initialize config with defaults @config: Configuration structure to initialize.
Thread-safe: Yes
Sets all fields to zero/NULL except timeouts which get defaults.
Referenced by main().
SocketProxy_Conn_cancel()
void SocketProxy_Conn_cancel (SocketProxy_Conn_T conn) extern
SocketProxy_Conn_cancel - Cancel in-progress operation @conn: Proxy connection context.
Thread-safe: No
Closes the connection and transitions to CANCELLED state.
SocketProxy_Conn_error()
const char * SocketProxy_Conn_error (SocketProxy_Conn_T conn) extern
SocketProxy_Conn_error - Get error message for failed operation @conn: Proxy connection context.
Returns: Error message string, or NULL if not in FAILED state Thread-safe: No
The returned string is valid until SocketProxy_Conn_free() is called.
SocketProxy_Conn_events()
unsigned SocketProxy_Conn_events (SocketProxy_Conn_T conn) extern
SocketProxy_Conn_events - Get events to poll for @conn: Proxy connection context.
Returns: Poll events bitmask (POLL_READ, POLL_WRITE) Thread-safe: No
SocketProxy_Conn_fd()
int SocketProxy_Conn_fd (SocketProxy_Conn_T conn) extern
SocketProxy_Conn_fd - Get file descriptor for poll @conn: Proxy connection context.
Returns: File descriptor to poll, or -1 if none active Thread-safe: No
SocketProxy_Conn_free()
void SocketProxy_Conn_free (SocketProxy_Conn_T * conn) extern
SocketProxy_Conn_free - Free proxy connection context @conn: Pointer to context (will be set to NULL)
Thread-safe: No
Releases all resources. If operation is still in progress, it will be cancelled first. Safe to call with NULL or *conn == NULL.
SocketProxy_Conn_new()
SocketProxy_Conn_T SocketProxy_Conn_new (const SocketProxy_Config * proxy, const char * target_host, int target_port) extern
SocketProxy_Conn_new - Start async proxy connection (blocking connect) @proxy: Proxy configuration @target_host: Target hostname or IP @target_port: Target port (1-65535)
Returns: Proxy connection context Raises: SocketProxy_Failed on initialization failure Thread-safe: Yes (creates new instance)
NOTE: This function blocks during the initial proxy connection phase. For fully non-blocking operation, use SocketProxy_Conn_start() instead.
Starts proxy connection with blocking connect to proxy server, then async handshake. This is a convenience wrapper that creates internal DNS and poll resources.
Caller must:
Call SocketProxy_Conn_process() after each poll wait
Check SocketProxy_Conn_poll() for completion
Call SocketProxy_Conn_socket() to get the tunneled socket
Call SocketProxy_Conn_free() to release context
SocketProxy_Conn_next_timeout_ms()
int SocketProxy_Conn_next_timeout_ms (SocketProxy_Conn_T conn) extern
SocketProxy_Conn_next_timeout_ms - Get time until next timeout @conn: Proxy connection context.
Returns: Milliseconds until timeout, or -1 if no pending timeout Thread-safe: No
Use as timeout argument to SocketPoll_wait().
SocketProxy_Conn_poll()
int SocketProxy_Conn_poll (SocketProxy_Conn_T conn) extern
SocketProxy_Conn_poll - Check if operation is complete @conn: Proxy connection context.
Returns: 1 if complete (success, failure, or cancelled), 0 if in progress Thread-safe: No
SocketProxy_Conn_process()
void SocketProxy_Conn_process (SocketProxy_Conn_T conn) extern
SocketProxy_Conn_process - Process async connection @conn: Proxy connection context.
Thread-safe: No
Call after SocketPoll_wait() returns with events on the connection fd. This advances the state machine and handles protocol I/O.
SocketProxy_Conn_result()
SocketProxy_Result SocketProxy_Conn_result (SocketProxy_Conn_T conn) extern
SocketProxy_Conn_result - Get result after completion @conn: Proxy connection context.
Returns: Result code (only valid after SocketProxy_Conn_poll() returns 1) Thread-safe: No
SocketProxy_Conn_socket()
Socket_T SocketProxy_Conn_socket (SocketProxy_Conn_T conn) extern
SocketProxy_Conn_socket - Get tunneled socket from completed operation @conn: Proxy connection context.
Returns: Tunneled socket, or NULL if failed/cancelled/pending Thread-safe: No
Transfers socket ownership to caller. Caller must Socket_free() when done. Can only be called once per successful connection - subsequent calls return NULL.
SocketProxy_Conn_start()
SocketProxy_Conn_T SocketProxy_Conn_start (SocketDNS_T dns, SocketPoll_T poll, const SocketProxy_Config * proxy, const char * target_host, int target_port) extern
SocketProxy_Conn_start - Start truly async proxy connection (event-driven) @dns: DNS resolver instance (caller-owned, must outlive operation) @poll: Poll instance for connection monitoring (caller-owned) @proxy: Proxy configuration @target_host: Target hostname or IP @target_port: Target port (1-65535)
Returns: Proxy connection context Raises: SocketProxy_Failed on initialization failure Thread-safe: No (operate from single thread)
Starts fully asynchronous proxy connection using external DNS and poll resources. This is the preferred API for event-driven applications. The operation is completely non-blocking from the start.
Caller must:
Call SocketProxy_Conn_process() after each poll wait
Check SocketProxy_Conn_poll() for completion
Call SocketProxy_Conn_socket() to get the tunneled socket
Call SocketProxy_Conn_free() to release context
Usage example: SocketProxy_Conn_T conn = SocketProxy_Conn_start(dns, poll, &proxy, "target.com", 443); while (!SocketProxy_Conn_poll(conn)) { int timeout = SocketProxy_Conn_next_timeout_ms(conn); SocketPoll_wait(poll, &events, timeout); SocketProxy_Conn_process(conn); } Socket_T sock = SocketProxy_Conn_socket(conn); SocketProxy_Conn_free(&conn);
SocketProxy_Conn_state()
SocketProxy_State SocketProxy_Conn_state (SocketProxy_Conn_T conn) extern
SocketProxy_Conn_state - Get current connection state @conn: Proxy connection context.
Returns: Current state Thread-safe: No
SocketProxy_connect()
Socket_T SocketProxy_connect (const SocketProxy_Config * proxy, const char * target_host, int target_port) extern
SocketProxy_connect - Connect to target through proxy (blocking) @proxy: Proxy configuration @target_host: Target hostname or IP @target_port: Target port (1-65535)
Returns: Connected socket on success, NULL on failure Raises: SocketProxy_Failed on error Thread-safe: Yes (uses internal resources)
Creates a new socket, connects to the proxy server using HappyEyeballs, performs the proxy handshake, and returns the tunneled socket.
After success, the returned socket is connected to the target through the proxy tunnel. Perform TLS handshake after this if connecting to an HTTPS endpoint.
WARNING: This function may block for up to connect_timeout_ms + handshake_timeout_ms during proxy connection and handshake.
Referenced by main().
SocketProxy_parse_url()
int SocketProxy_parse_url (const char * url, SocketProxy_Config * config, Arena_T arena) extern
SocketProxy_parse_url - Parse proxy URL into config @url: Proxy URL (e.g., "socks5://user:pass@proxy:1080") @config: Output configuration @arena: Arena for string allocation (NULL to use static buffer)
Returns: 0 on success, -1 on parse error Thread-safe: Yes (if arena is thread-safe or NULL)
Supported URL formats: http://[user:pass@]host[:port] https://[user:pass@]host[:port] socks4://host[:port] socks4a://host[:port] socks5://[user:pass@]host[:port] socks5h://[user:pass@]host[:port]
When arena is NULL, strings are allocated from a static thread-local buffer and are valid until the next call to SocketProxy_parse_url() from the same thread.
Referenced by main().
SocketProxy_result_string()
const char * SocketProxy_result_string (SocketProxy_Result result) extern
SocketProxy_result_string - Get human-readable result description.
Returns
: Result code
Returns: Static string describing the result Thread-safe: Yes
SocketProxy_state_string()
const char * SocketProxy_state_string (SocketProxy_State state) extern
SocketProxy_state_string - Get human-readable state name @state: State value.
Returns: Static string with state name Thread-safe: Yes
SocketProxy_tunnel()
SocketProxy_Result SocketProxy_tunnel (Socket_T socket, const SocketProxy_Config * proxy, const char * target_host, int target_port) extern
SocketProxy_tunnel - Establish tunnel on existing socket (blocking) @socket: Already-connected socket to proxy server @proxy: Proxy configuration (type, auth, timeouts) @target_host: Target hostname or IP @target_port: Target port (1-65535)
Returns: PROXY_OK on success, error code on failure Thread-safe: No
Performs proxy handshake on an already-connected socket. Use this when you need control over the proxy connection establishment.
The socket should already be connected to proxy->host:proxy->port.
SocketProxy_type_string()
const char * SocketProxy_type_string (SocketProxyType type) extern
SocketProxy_type_string - Get human-readable proxy type name @type: Proxy type.
Returns: Static string (e.g., "SOCKS5", "HTTP CONNECT") Thread-safe: Yes
Variable Documentation
SocketProxy_Failed
const Except_T SocketProxy_Failed extern
SocketProxy_Failed - General proxy operation failure.
Raised when proxy connection or handshake fails. Use SocketProxy_Conn_result() for specific error codes.
Referenced by main().