SocketHTTPClient.h File Reference
SocketHTTPClient.h File Reference
#include <stddef.h>
#include <stdint.h>
#include <sys/types.h>
#include <time.h>
#include "core/Arena.h"
#include "core/Except.h"
#include "http/SocketHTTP.h"
#include "tls/SocketTLSContext.h"
Data Structures
struct SocketHTTPClient_Auth
Authentication credentials.
struct SocketHTTPClient_Config
HTTP client configuration.
struct SocketHTTPClient_Response
HTTP response (owned by caller)
struct SocketHTTPClient_Cookie
Cookie attributes.
struct SocketHTTPClient_PoolStats
Pool statistics.
Macros
#define HTTPCLIENT_DEFAULT_MAX_CONNS_PER_HOST 6
SocketHTTPClient.h - HTTP Client API.
#define HTTPCLIENT_DEFAULT_MAX_TOTAL_CONNS 100
Default maximum total connections.
#define HTTPCLIENT_DEFAULT_CONNECT_TIMEOUT_MS 30000
Default connect timeout (ms)
#define HTTPCLIENT_DEFAULT_REQUEST_TIMEOUT_MS 60000
Default request timeout (ms)
#define HTTPCLIENT_DEFAULT_DNS_TIMEOUT_MS 10000
Default DNS timeout (ms)
#define HTTPCLIENT_DEFAULT_IDLE_TIMEOUT_MS 60000
Default idle connection timeout (ms)
#define HTTPCLIENT_DEFAULT_MAX_REDIRECTS 10
Default maximum redirects.
#define HTTPCLIENT_DEFAULT_MAX_RESPONSE_SIZE 0
Default maximum response body size (0 = unlimited)
#define HTTPCLIENT_DEFAULT_USER_AGENT "SocketHTTPClient/1.0"
Default User-Agent string.
#define HTTPCLIENT_POOL_HASH_SIZE 127
Connection pool hash table size.
#define HTTPCLIENT_ENCODING_IDENTITY 0x00
#define HTTPCLIENT_ENCODING_GZIP 0x01
#define HTTPCLIENT_ENCODING_DEFLATE 0x02
#define HTTPCLIENT_ENCODING_BR 0x04
Typedefs
typedef struct SocketHTTPClient * SocketHTTPClient_T
HTTP client instance.
typedef struct SocketHTTPClient_Request * SocketHTTPClient_Request_T
HTTP request builder.
typedef struct SocketHTTPClient_AsyncRequest * SocketHTTPClient_AsyncRequest_T
Async request handle.
typedef struct SocketHTTPClient_CookieJar * SocketHTTPClient_CookieJar_T
Cookie jar.
Enumerations
enum SocketHTTPClient_Error {
HTTPCLIENT_OK = 0 ,
HTTPCLIENT_ERROR_DNS ,
HTTPCLIENT_ERROR_CONNECT ,
HTTPCLIENT_ERROR_TLS ,
HTTPCLIENT_ERROR_TIMEOUT ,
HTTPCLIENT_ERROR_PROTOCOL ,
HTTPCLIENT_ERROR_TOO_MANY_REDIRECTS ,
HTTPCLIENT_ERROR_RESPONSE_TOO_LARGE ,
HTTPCLIENT_ERROR_CANCELLED ,
HTTPCLIENT_ERROR_OUT_OF_MEMORY
}
Error codes for async operations.
enum SocketHTTPClient_AuthType {
HTTP_AUTH_NONE = 0 ,
HTTP_AUTH_BASIC ,
HTTP_AUTH_DIGEST ,
HTTP_AUTH_BEARER ,
HTTP_AUTH_NTLM ,
HTTP_AUTH_NEGOTIATE
}
Authentication scheme types.
Functions
void SocketHTTPClient_config_defaults (SocketHTTPClient_Config *config)
SocketHTTPClient_config_defaults - Initialize config with defaults @config: Configuration structure to initialize.
SocketHTTPClient_T SocketHTTPClient_new (const SocketHTTPClient_Config *config)
SocketHTTPClient_new - Create HTTP client @config: Configuration (NULL for defaults)
void SocketHTTPClient_free (SocketHTTPClient_T *client)
SocketHTTPClient_free - Free client and all resources @client: Pointer to client (set to NULL)
int SocketHTTPClient_get (SocketHTTPClient_T client, const char *url, SocketHTTPClient_Response *response)
SocketHTTPClient_get - Perform GET request @client: Client instance @url: Full URL (http:// or https://) @response: Output response (caller must free via Response_free)
int SocketHTTPClient_head (SocketHTTPClient_T client, const char *url, SocketHTTPClient_Response *response)
SocketHTTPClient_head - Perform HEAD request.
int SocketHTTPClient_post (SocketHTTPClient_T client, const char *url, const char *content_type, const void *body, size_t body_len, SocketHTTPClient_Response *response)
SocketHTTPClient_post - Perform POST request @client: Client @url: Full URL @content_type: Content-Type header value @body: Request body @body_len: Body length @response: Output response.
int SocketHTTPClient_put (SocketHTTPClient_T client, const char *url, const char *content_type, const void *body, size_t body_len, SocketHTTPClient_Response *response)
SocketHTTPClient_put - Perform PUT request.
int SocketHTTPClient_delete (SocketHTTPClient_T client, const char *url, SocketHTTPClient_Response *response)
SocketHTTPClient_delete - Perform DELETE request.
void SocketHTTPClient_Response_free (SocketHTTPClient_Response *response)
SocketHTTPClient_Response_free - Free response resources @response: Response to free.
SocketHTTPClient_Request_T SocketHTTPClient_Request_new (SocketHTTPClient_T client, SocketHTTP_Method method, const char *url)
SocketHTTPClient_Request_new - Create request builder @client: Client instance @method: HTTP method @url: Full URL.
void SocketHTTPClient_Request_free (SocketHTTPClient_Request_T *req)
SocketHTTPClient_Request_free - Free request builder @req: Pointer to request (set to NULL)
: Cookie name
SocketHTTPClient_CookieJar_get - Get cookie by name @jar: Cookie jar @domain: Domain to match @path: Path to match
Returns: Cookie or NULL if not found
const SocketHTTPClient_Cookie * SocketHTTPClient_CookieJar_get (SocketHTTPClient_CookieJar_T jar, const char *domain, const char *path, const char *name)
SocketHTTPClient_CookieJar_clear - Clear all cookies @jar: Cookie jar.
void SocketHTTPClient_CookieJar_clear (SocketHTTPClient_CookieJar_T jar)
SocketHTTPClient_CookieJar_clear - Clear all cookies @jar: Cookie jar.
void SocketHTTPClient_CookieJar_clear_expired (SocketHTTPClient_CookieJar_T jar)
SocketHTTPClient_CookieJar_clear_expired - Clear expired cookies @jar: Cookie jar.
int SocketHTTPClient_CookieJar_load (SocketHTTPClient_CookieJar_T jar, const char *filename)
SocketHTTPClient_CookieJar_load - Load cookies from file @jar: Cookie jar @filename: File path.
int SocketHTTPClient_CookieJar_save (SocketHTTPClient_CookieJar_T jar, const char *filename)
SocketHTTPClient_CookieJar_save - Save cookies to file @jar: Cookie jar @filename: File path.
void SocketHTTPClient_set_auth (SocketHTTPClient_T client, const SocketHTTPClient_Auth *auth)
SocketHTTPClient_set_auth - Set default authentication @client: Client @auth: Authentication credentials.
void SocketHTTPClient_pool_stats (SocketHTTPClient_T client, SocketHTTPClient_PoolStats *stats)
SocketHTTPClient_pool_stats - Get pool statistics @client: Client @stats: Output statistics.
void SocketHTTPClient_pool_clear (SocketHTTPClient_T client)
SocketHTTPClient_pool_clear - Clear all pooled connections @client: Client.
SocketHTTPClient_Error SocketHTTPClient_last_error (SocketHTTPClient_T client)
SocketHTTPClient_last_error - Get last error code @client: Client.
const char * SocketHTTPClient_error_string (SocketHTTPClient_Error error)
SocketHTTPClient_error_string - Get error description @error: Error code.
Variables
const Except_T SocketHTTPClient_Failed
General client failure.
const Except_T SocketHTTPClient_DNSFailed
DNS resolution failure.
const Except_T SocketHTTPClient_ConnectFailed
Connection failure.
const Except_T SocketHTTPClient_TLSFailed
TLS/SSL failure.
const Except_T SocketHTTPClient_Timeout
Request timeout.
const Except_T SocketHTTPClient_ProtocolError
Protocol error (HTTP parse error)
const Except_T SocketHTTPClient_TooManyRedirects
Too many redirects.
const Except_T SocketHTTPClient_ResponseTooLarge
Response too large.
: Header name
SocketHTTPClient_Request_header - Add header @req: Request
@value: Header value
Returns: 0 on success, -1 on error
enum SocketHTTPClient_SameSite {
COOKIE_SAMESITE_NONE = 0 ,
COOKIE_SAMESITE_LAX = 1 ,
COOKIE_SAMESITE_STRICT = 2
}
Cookie SameSite attribute values.
typedef void(* SocketHTTPClient_Callback) (SocketHTTPClient_AsyncRequest_T req, SocketHTTPClient_Response *response, SocketHTTPClient_Error error, void *userdata)
Async completion callback.
int SocketHTTPClient_Request_header (SocketHTTPClient_Request_T req, const char *name, const char *value)
Cookie SameSite attribute values.
int SocketHTTPClient_Request_body (SocketHTTPClient_Request_T req, const void *data, size_t len)
SocketHTTPClient_Request_body - Set request body @req: Request @data: Body data @len: Data length.
int SocketHTTPClient_Request_body_stream (SocketHTTPClient_Request_T req, ssize_t(*read_cb)(void *buf, size_t len, void *userdata), void *userdata)
SocketHTTPClient_Request_body_stream - Set streaming body @req: Request @read_cb: Callback to read body data @userdata: User data for callback.
void SocketHTTPClient_Request_timeout (SocketHTTPClient_Request_T req, int ms)
SocketHTTPClient_Request_timeout - Set per-request timeout @req: Request @ms: Timeout in milliseconds.
void SocketHTTPClient_Request_auth (SocketHTTPClient_Request_T req, const SocketHTTPClient_Auth *auth)
SocketHTTPClient_Request_auth - Set per-request authentication @req: Request @auth: Authentication credentials.
int SocketHTTPClient_Request_execute (SocketHTTPClient_Request_T req, SocketHTTPClient_Response *response)
SocketHTTPClient_Request_execute - Execute request @req: Request @response: Output response.
SocketHTTPClient_AsyncRequest_T SocketHTTPClient_get_async (SocketHTTPClient_T client, const char *url, SocketHTTPClient_Callback callback, void *userdata)
SocketHTTPClient_get_async - Start async GET.
SocketHTTPClient_AsyncRequest_T SocketHTTPClient_post_async (SocketHTTPClient_T client, const char *url, const char *content_type, const void *body, size_t body_len, SocketHTTPClient_Callback callback, void *userdata)
SocketHTTPClient_post_async - Start async POST.
SocketHTTPClient_AsyncRequest_T SocketHTTPClient_Request_async (SocketHTTPClient_Request_T req, SocketHTTPClient_Callback callback, void *userdata)
SocketHTTPClient_Request_async - Start async custom request.
void SocketHTTPClient_AsyncRequest_cancel (SocketHTTPClient_AsyncRequest_T req)
SocketHTTPClient_AsyncRequest_cancel - Cancel async request.
int SocketHTTPClient_process (SocketHTTPClient_T client, int timeout_ms)
SocketHTTPClient_process - Process async requests @client: Client @timeout_ms: Poll timeout.
SocketHTTPClient_CookieJar_T SocketHTTPClient_CookieJar_new (void)
SocketHTTPClient_CookieJar_new - Create cookie jar.
void SocketHTTPClient_CookieJar_free (SocketHTTPClient_CookieJar_T *jar)
SocketHTTPClient_CookieJar_free - Free cookie jar @jar: Pointer to jar (set to NULL)
void SocketHTTPClient_set_cookie_jar (SocketHTTPClient_T client, SocketHTTPClient_CookieJar_T jar)
SocketHTTPClient_set_cookie_jar - Associate jar with client @client: Client @jar: Cookie jar (NULL to remove)
SocketHTTPClient_CookieJar_T SocketHTTPClient_get_cookie_jar (SocketHTTPClient_T client)
SocketHTTPClient_get_cookie_jar - Get associated cookie jar @client: Client.
int SocketHTTPClient_CookieJar_set (SocketHTTPClient_CookieJar_T jar, const SocketHTTPClient_Cookie *cookie)
SocketHTTPClient_CookieJar_set - Set cookie @jar: Cookie jar @cookie: Cookie to set.
Data Structure Documentation
SocketHTTPClient_Auth
struct SocketHTTPClient_Auth
Authentication credentials.
Definition at line 183 of file SocketHTTPClient.h.
Data Fields
const char * password For Basic, Digest.
const char * realm Optional realm filter.
const char * token For Bearer.
SocketHTTPClient_AuthType type
const char * username For Basic, Digest.
SocketHTTPClient_Config
struct SocketHTTPClient_Config
HTTP client configuration.
Definition at line 205 of file SocketHTTPClient.h.
Data Fields
int accept_encoding Bitmask: GZIP | DEFLATE | BR.
int allow_http2_cleartext Allow h2c upgrade (default: 0)
int auto_decompress Auto-decompress responses (default: 1)
int connect_timeout_ms Connection timeout.
int dns_timeout_ms DNS resolution timeout.
int enable_connection_pool Enable pooling (default: 1)
int follow_redirects Max redirects (0 = disabled)
int idle_timeout_ms Idle connection timeout.
size_t max_connections_per_host Per-host limit (default: 6)
size_t max_response_size Max response body (0 = unlimited)
size_t max_total_connections Total limit (default: 100)
SocketHTTP_Version max_version Max HTTP version (default: HTTP/2)
SocketProxy_Config * proxy Default proxy (NULL for none)
int redirect_on_post Follow redirects for POST (default: 0)
int request_timeout_ms Request timeout.
SocketTLSContext_T tls_context Custom TLS context (NULL for default)
const char * user_agent User-Agent header.
int verify_ssl Verify certificates (default: 1)
SocketHTTPClient_Response
struct SocketHTTPClient_Response
HTTP response (owned by caller)
Definition at line 267 of file SocketHTTPClient.h.
Data Fields
Arena_T arena For cleanup - caller must dispose.
void * body
size_t body_len
SocketHTTP_Headers_T headers
int status_code
SocketHTTP_Version version
SocketHTTPClient_Cookie
struct SocketHTTPClient_Cookie
Cookie attributes.
Definition at line 524 of file SocketHTTPClient.h.
Data Fields
const char * domain
time_t expires
int http_only
const char * name
const char * path
SocketHTTPClient_SameSite same_site
int secure
const char * value
SocketHTTPClient_PoolStats
struct SocketHTTPClient_PoolStats
Pool statistics.
Definition at line 644 of file SocketHTTPClient.h.
Data Fields
size_t active_connections
size_t idle_connections
size_t reused_connections
size_t total_requests
Macro Definition Documentation
HTTPCLIENT_DEFAULT_CONNECT_TIMEOUT_MS
#define HTTPCLIENT_DEFAULT_CONNECT_TIMEOUT_MS 30000
Default connect timeout (ms)
Definition at line 67 of file SocketHTTPClient.h.
HTTPCLIENT_DEFAULT_DNS_TIMEOUT_MS
#define HTTPCLIENT_DEFAULT_DNS_TIMEOUT_MS 10000
Default DNS timeout (ms)
Definition at line 77 of file SocketHTTPClient.h.
HTTPCLIENT_DEFAULT_IDLE_TIMEOUT_MS
#define HTTPCLIENT_DEFAULT_IDLE_TIMEOUT_MS 60000
Default idle connection timeout (ms)
Definition at line 82 of file SocketHTTPClient.h.
HTTPCLIENT_DEFAULT_MAX_CONNS_PER_HOST
#define HTTPCLIENT_DEFAULT_MAX_CONNS_PER_HOST 6
SocketHTTPClient.h - HTTP Client API.
Part of the Socket Library Following C Interfaces and Implementations patterns
High-level HTTP client abstracting HTTP/1.1 and HTTP/2 with:
Connection pooling with per-host limits
Automatic protocol negotiation (ALPN for HTTP/2)
Cookie handling (RFC 6265)
Authentication (Basic/Digest/Bearer)
Compression (gzip/deflate/brotli)
Redirect following
Both synchronous and asynchronous APIs
Dependencies (leveraged, not duplicated):
SocketHTTP for headers, URI, methods, status codes
SocketHTTP1 for HTTP/1.1 parsing/serialization
SocketHTTP2 for HTTP/2 protocol
SocketHappyEyeballs for fast connection establishment
SocketCrypto for authentication (base64, MD5, SHA256)
Thread safety: Client instances are NOT thread-safe. Use one client per thread or external synchronization.
PLATFORM REQUIREMENTS:
POSIX-compliant system (Linux, BSD, macOS)
pthread for mutex synchronization
OpenSSL for TLS (optional, via SOCKET_HAS_TLS) Default maximum connections per host
Definition at line 57 of file SocketHTTPClient.h.
HTTPCLIENT_DEFAULT_MAX_REDIRECTS
#define HTTPCLIENT_DEFAULT_MAX_REDIRECTS 10
Default maximum redirects.
Definition at line 87 of file SocketHTTPClient.h.
HTTPCLIENT_DEFAULT_MAX_RESPONSE_SIZE
#define HTTPCLIENT_DEFAULT_MAX_RESPONSE_SIZE 0
Default maximum response body size (0 = unlimited)
Definition at line 92 of file SocketHTTPClient.h.
HTTPCLIENT_DEFAULT_MAX_TOTAL_CONNS
#define HTTPCLIENT_DEFAULT_MAX_TOTAL_CONNS 100
Default maximum total connections.
Definition at line 62 of file SocketHTTPClient.h.
HTTPCLIENT_DEFAULT_REQUEST_TIMEOUT_MS
#define HTTPCLIENT_DEFAULT_REQUEST_TIMEOUT_MS 60000
Default request timeout (ms)
Definition at line 72 of file SocketHTTPClient.h.
HTTPCLIENT_DEFAULT_USER_AGENT
#define HTTPCLIENT_DEFAULT_USER_AGENT "SocketHTTPClient/1.0"
Default User-Agent string.
Definition at line 97 of file SocketHTTPClient.h.
HTTPCLIENT_ENCODING_BR
#define HTTPCLIENT_ENCODING_BR 0x04
Definition at line 112 of file SocketHTTPClient.h.
HTTPCLIENT_ENCODING_DEFLATE
#define HTTPCLIENT_ENCODING_DEFLATE 0x02
Definition at line 111 of file SocketHTTPClient.h.
HTTPCLIENT_ENCODING_GZIP
#define HTTPCLIENT_ENCODING_GZIP 0x01
Definition at line 110 of file SocketHTTPClient.h.
HTTPCLIENT_ENCODING_IDENTITY
#define HTTPCLIENT_ENCODING_IDENTITY 0x00
Definition at line 109 of file SocketHTTPClient.h.
HTTPCLIENT_POOL_HASH_SIZE
#define HTTPCLIENT_POOL_HASH_SIZE 127
Connection pool hash table size.
Definition at line 102 of file SocketHTTPClient.h.
Typedef Documentation
SocketHTTPClient_AsyncRequest_T
typedef struct SocketHTTPClient_AsyncRequest* SocketHTTPClient_AsyncRequest_T
Async request handle.
Definition at line 255 of file SocketHTTPClient.h.
SocketHTTPClient_Callback
typedef void(* SocketHTTPClient_Callback) (SocketHTTPClient_AsyncRequest_T req, SocketHTTPClient_Response *response, SocketHTTPClient_Error error, void *userdata)
Async completion callback.
Definition at line 460 of file SocketHTTPClient.h.
SocketHTTPClient_CookieJar_T
typedef struct SocketHTTPClient_CookieJar* SocketHTTPClient_CookieJar_T
Cookie jar.
Definition at line 258 of file SocketHTTPClient.h.
SocketHTTPClient_Request_T
typedef struct SocketHTTPClient_Request* SocketHTTPClient_Request_T
HTTP request builder.
Definition at line 252 of file SocketHTTPClient.h.
SocketHTTPClient_T
typedef struct SocketHTTPClient* SocketHTTPClient_T
HTTP client instance.
Definition at line 249 of file SocketHTTPClient.h.
Enumeration Type Documentation
SocketHTTPClient_AuthType
enum SocketHTTPClient_AuthType
Authentication scheme types.
Enumerator
HTTP_AUTH_NONE
HTTP_AUTH_BASIC
RFC 7617.
HTTP_AUTH_DIGEST
RFC 7616.
HTTP_AUTH_BEARER
RFC 6750.
HTTP_AUTH_NTLM
Microsoft NTLM (not implemented)
HTTP_AUTH_NEGOTIATE
SPNEGO/Kerberos (not implemented)
Definition at line 170 of file SocketHTTPClient.h.
SocketHTTPClient_Error
enum SocketHTTPClient_Error
Error codes for async operations.
Enumerator
HTTPCLIENT_OK
HTTPCLIENT_ERROR_DNS
HTTPCLIENT_ERROR_CONNECT
HTTPCLIENT_ERROR_TLS
HTTPCLIENT_ERROR_TIMEOUT
HTTPCLIENT_ERROR_PROTOCOL
HTTPCLIENT_ERROR_TOO_MANY_REDIRECTS
HTTPCLIENT_ERROR_RESPONSE_TOO_LARGE
HTTPCLIENT_ERROR_CANCELLED
HTTPCLIENT_ERROR_OUT_OF_MEMORY
Definition at line 149 of file SocketHTTPClient.h.
SocketHTTPClient_SameSite
enum SocketHTTPClient_SameSite
Cookie SameSite attribute values.
Enumerator
COOKIE_SAMESITE_NONE
COOKIE_SAMESITE_LAX
COOKIE_SAMESITE_STRICT
Definition at line 514 of file SocketHTTPClient.h.
Function Documentation
SocketHTTPClient_AsyncRequest_cancel()
void SocketHTTPClient_AsyncRequest_cancel (SocketHTTPClient_AsyncRequest_T req) extern
SocketHTTPClient_AsyncRequest_cancel - Cancel async request.
SocketHTTPClient_config_defaults()
void SocketHTTPClient_config_defaults (SocketHTTPClient_Config * config) extern
SocketHTTPClient_config_defaults - Initialize config with defaults @config: Configuration structure to initialize.
Thread-safe: Yes
Referenced by main().
SocketHTTPClient_CookieJar_clear()
void SocketHTTPClient_CookieJar_clear (SocketHTTPClient_CookieJar_T jar) extern
SocketHTTPClient_CookieJar_clear - Clear all cookies @jar: Cookie jar.
SocketHTTPClient_CookieJar_clear_expired()
void SocketHTTPClient_CookieJar_clear_expired (SocketHTTPClient_CookieJar_T jar) extern
SocketHTTPClient_CookieJar_clear_expired - Clear expired cookies @jar: Cookie jar.
SocketHTTPClient_CookieJar_free()
void SocketHTTPClient_CookieJar_free (SocketHTTPClient_CookieJar_T * jar) extern
SocketHTTPClient_CookieJar_free - Free cookie jar @jar: Pointer to jar (set to NULL)
SocketHTTPClient_CookieJar_get()
const SocketHTTPClient_Cookie * SocketHTTPClient_CookieJar_get (SocketHTTPClient_CookieJar_T jar, const char * domain, const char * path, const char * name) extern
SocketHTTPClient_CookieJar_clear - Clear all cookies @jar: Cookie jar.
SocketHTTPClient_CookieJar_load()
int SocketHTTPClient_CookieJar_load (SocketHTTPClient_CookieJar_T jar, const char * filename) extern
SocketHTTPClient_CookieJar_load - Load cookies from file @jar: Cookie jar @filename: File path.
Returns: 0 on success, -1 on error
SocketHTTPClient_CookieJar_new()
SocketHTTPClient_CookieJar_T SocketHTTPClient_CookieJar_new (void) extern
SocketHTTPClient_CookieJar_new - Create cookie jar.
Returns: New cookie jar Thread-safe: Yes
SocketHTTPClient_CookieJar_save()
int SocketHTTPClient_CookieJar_save (SocketHTTPClient_CookieJar_T jar, const char * filename) extern
SocketHTTPClient_CookieJar_save - Save cookies to file @jar: Cookie jar @filename: File path.
Returns: 0 on success, -1 on error
SocketHTTPClient_CookieJar_set()
int SocketHTTPClient_CookieJar_set (SocketHTTPClient_CookieJar_T jar, const SocketHTTPClient_Cookie * cookie) extern
SocketHTTPClient_CookieJar_set - Set cookie @jar: Cookie jar @cookie: Cookie to set.
Returns: 0 on success, -1 on error
SocketHTTPClient_delete()
int SocketHTTPClient_delete (SocketHTTPClient_T client, const char * url, SocketHTTPClient_Response * response) extern
SocketHTTPClient_delete - Perform DELETE request.
SocketHTTPClient_error_string()
const char * SocketHTTPClient_error_string (SocketHTTPClient_Error error) extern
SocketHTTPClient_error_string - Get error description @error: Error code.
Returns: Static string Thread-safe: Yes
SocketHTTPClient_free()
void SocketHTTPClient_free (SocketHTTPClient_T * client) extern
SocketHTTPClient_free - Free client and all resources @client: Pointer to client (set to NULL)
Thread-safe: No
Referenced by main().
SocketHTTPClient_get()
int SocketHTTPClient_get (SocketHTTPClient_T client, const char * url, SocketHTTPClient_Response * response) extern
SocketHTTPClient_get - Perform GET request @client: Client instance @url: Full URL (http:// or https://) @response: Output response (caller must free via Response_free)
Returns: 0 on success, -1 on error Raises: Various exceptions on failure Thread-safe: No
Referenced by main().
SocketHTTPClient_get_async()
SocketHTTPClient_AsyncRequest_T SocketHTTPClient_get_async (SocketHTTPClient_T client, const char * url, SocketHTTPClient_Callback callback, void * userdata) extern
SocketHTTPClient_get_async - Start async GET.
SocketHTTPClient_get_cookie_jar()
SocketHTTPClient_CookieJar_T SocketHTTPClient_get_cookie_jar (SocketHTTPClient_T client) extern
SocketHTTPClient_get_cookie_jar - Get associated cookie jar @client: Client.
Returns: Cookie jar or NULL
SocketHTTPClient_head()
int SocketHTTPClient_head (SocketHTTPClient_T client, const char * url, SocketHTTPClient_Response * response) extern
SocketHTTPClient_head - Perform HEAD request.
SocketHTTPClient_last_error()
SocketHTTPClient_Error SocketHTTPClient_last_error (SocketHTTPClient_T client) extern
SocketHTTPClient_last_error - Get last error code @client: Client.
Returns: Error code
SocketHTTPClient_new()
SocketHTTPClient_T SocketHTTPClient_new (const SocketHTTPClient_Config * config) extern
SocketHTTPClient_new - Create HTTP client @config: Configuration (NULL for defaults)
Returns: New client instance Raises: SocketHTTPClient_Failed on allocation failure Thread-safe: Yes
Referenced by main().
SocketHTTPClient_pool_clear()
void SocketHTTPClient_pool_clear (SocketHTTPClient_T client) extern
SocketHTTPClient_pool_clear - Clear all pooled connections @client: Client.
SocketHTTPClient_pool_stats()
void SocketHTTPClient_pool_stats (SocketHTTPClient_T client, SocketHTTPClient_PoolStats * stats) extern
SocketHTTPClient_pool_stats - Get pool statistics @client: Client @stats: Output statistics.
SocketHTTPClient_post()
int SocketHTTPClient_post (SocketHTTPClient_T client, const char * url, const char * content_type, const void * body, size_t body_len, SocketHTTPClient_Response * response) extern
SocketHTTPClient_post - Perform POST request @client: Client @url: Full URL @content_type: Content-Type header value @body: Request body @body_len: Body length @response: Output response.
Referenced by main().
SocketHTTPClient_post_async()
SocketHTTPClient_AsyncRequest_T SocketHTTPClient_post_async (SocketHTTPClient_T client, const char * url, const char * content_type, const void * body, size_t body_len, SocketHTTPClient_Callback callback, void * userdata) extern
SocketHTTPClient_post_async - Start async POST.
SocketHTTPClient_process()
int SocketHTTPClient_process (SocketHTTPClient_T client, int timeout_ms) extern
SocketHTTPClient_process - Process async requests @client: Client @timeout_ms: Poll timeout.
Returns: Number of completed requests Thread-safe: No
Call in event loop to process pending async requests.
SocketHTTPClient_put()
int SocketHTTPClient_put (SocketHTTPClient_T client, const char * url, const char * content_type, const void * body, size_t body_len, SocketHTTPClient_Response * response) extern
SocketHTTPClient_put - Perform PUT request.
SocketHTTPClient_Request_async()
SocketHTTPClient_AsyncRequest_T SocketHTTPClient_Request_async (SocketHTTPClient_Request_T req, SocketHTTPClient_Callback callback, void * userdata) extern
SocketHTTPClient_Request_async - Start async custom request.
SocketHTTPClient_Request_auth()
void SocketHTTPClient_Request_auth (SocketHTTPClient_Request_T req, const SocketHTTPClient_Auth * auth) extern
SocketHTTPClient_Request_auth - Set per-request authentication @req: Request @auth: Authentication credentials.
SocketHTTPClient_Request_body()
int SocketHTTPClient_Request_body (SocketHTTPClient_Request_T req, const void * data, size_t len) extern
SocketHTTPClient_Request_body - Set request body @req: Request @data: Body data @len: Data length.
Returns: 0 on success, -1 on error
Referenced by main().
SocketHTTPClient_Request_body_stream()
int SocketHTTPClient_Request_body_stream (SocketHTTPClient_Request_T req, ssize_t(*)(void *buf, size_t len, void *userdata) read_cb, void * userdata) extern
SocketHTTPClient_Request_body_stream - Set streaming body @req: Request @read_cb: Callback to read body data @userdata: User data for callback.
Returns: 0 on success, -1 on error
SocketHTTPClient_Request_execute()
int SocketHTTPClient_Request_execute (SocketHTTPClient_Request_T req, SocketHTTPClient_Response * response) extern
SocketHTTPClient_Request_execute - Execute request @req: Request @response: Output response.
Returns: 0 on success, -1 on error Thread-safe: No
Referenced by main().
SocketHTTPClient_Request_free()
void SocketHTTPClient_Request_free (SocketHTTPClient_Request_T * req) extern
SocketHTTPClient_Request_free - Free request builder @req: Pointer to request (set to NULL)
Referenced by main().
SocketHTTPClient_Request_header()
int SocketHTTPClient_Request_header (SocketHTTPClient_Request_T req, const char * name, const char * value) extern
Cookie SameSite attribute values.
Referenced by main().
SocketHTTPClient_Request_new()
SocketHTTPClient_Request_T SocketHTTPClient_Request_new (SocketHTTPClient_T client, SocketHTTP_Method method, const char * url) extern
SocketHTTPClient_Request_new - Create request builder @client: Client instance @method: HTTP method @url: Full URL.
Returns: Request builder Thread-safe: No
Referenced by main().
SocketHTTPClient_Request_timeout()
void SocketHTTPClient_Request_timeout (SocketHTTPClient_Request_T req, int ms) extern
SocketHTTPClient_Request_timeout - Set per-request timeout @req: Request @ms: Timeout in milliseconds.
Referenced by main().
SocketHTTPClient_Response_free()
void SocketHTTPClient_Response_free (SocketHTTPClient_Response * response) extern
SocketHTTPClient_Response_free - Free response resources @response: Response to free.
Thread-safe: No
Referenced by main().
SocketHTTPClient_set_auth()
void SocketHTTPClient_set_auth (SocketHTTPClient_T client, const SocketHTTPClient_Auth * auth) extern
SocketHTTPClient_set_auth - Set default authentication @client: Client @auth: Authentication credentials.
SocketHTTPClient_set_cookie_jar()
void SocketHTTPClient_set_cookie_jar (SocketHTTPClient_T client, SocketHTTPClient_CookieJar_T jar) extern
SocketHTTPClient_set_cookie_jar - Associate jar with client @client: Client @jar: Cookie jar (NULL to remove)
Variable Documentation
SocketHTTPClient_ConnectFailed
const Except_T SocketHTTPClient_ConnectFailed extern
Connection failure.
Referenced by main().
SocketHTTPClient_DNSFailed
const Except_T SocketHTTPClient_DNSFailed extern
DNS resolution failure.
Referenced by main().
SocketHTTPClient_Failed
const Except_T SocketHTTPClient_Failed extern
General client failure.
Referenced by main().
SocketHTTPClient_ProtocolError
const Except_T SocketHTTPClient_ProtocolError extern
Protocol error (HTTP parse error)
SocketHTTPClient_ResponseTooLarge
const Except_T SocketHTTPClient_ResponseTooLarge extern
Response too large.
SocketHTTPClient_Timeout
const Except_T SocketHTTPClient_Timeout extern
Request timeout.
Referenced by main().
SocketHTTPClient_TLSFailed
const Except_T SocketHTTPClient_TLSFailed extern
TLS/SSL failure.
Referenced by main().
SocketHTTPClient_TooManyRedirects
const Except_T SocketHTTPClient_TooManyRedirects extern
Too many redirects.