Tetsuo Pulse: tcp_echo_server.c File Reference
tcp_echo_server.c File Reference
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "core/Except.h"
#include "socket/Socket.h"
Functions
static void signal_handler (int signo)
int main (int argc, char **argv)
Variables
static volatile int running = 1
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 39 of file tcp_echo_server.c.
References END_TRY, EXCEPT, running, signal_handler(), Socket_accept(), Socket_bind(), Socket_Failed, Socket_free(), Socket_getpeeraddr(), Socket_getpeerport(), Socket_listen(), Socket_new(), Socket_recv(), Socket_sendall(), Socket_setnonblocking(), Socket_setreuseaddr(), and TRY.
signal_handler()
static void signal_handler (int signo) static
Definition at line 32 of file tcp_echo_server.c.
References running.
Referenced by main().
Variable Documentation
running
volatile int running = 1 static
tcp_echo_server.c - Basic TCP Echo Server Example
Demonstrates a simple TCP echo server using the core Socket API. Shows basic socket operations: bind, listen, accept, recv, send.
Build: cmake -DBUILD_EXAMPLES=ON .. make example_tcp_echo_server
Usage: ./example_tcp_echo_server [port] ./example_tcp_echo_server 8080
Test with: echo "Hello, World!" | nc localhost 8080 telnet localhost 8080
Definition at line 29 of file tcp_echo_server.c.
Referenced by main(), and signal_handler().