Tetsuo Pulse: tls_advanced.c File Reference
tls_advanced.c File Reference
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "core/Except.h"
#include "core/SocketUtil.h"
#include "socket/Socket.h"
#include "tls/SocketTLS.h"
#include "tls/SocketTLSContext.h"
Data Structures
struct CertLookupContext
Functions
static X509 * example_cert_lookup (X509_STORE_CTX *store_ctx, const X509_NAME *name, void *user_data)
int main (int argc, char **argv)
Data Structure Documentation
CertLookupContext
struct CertLookupContext
tls_advanced.c - Advanced TLS Features Example
Demonstrates advanced TLS features including:
OCSP stapling (client-side request)
Certificate lookup callbacks
Certificate pinning
Certificate Transparency (CT) verification
Build: cmake -DENABLE_TLS=ON -DBUILD_EXAMPLES=ON .. make example_tls_advanced
Usage: ./example_tls_advanced [host] [port] ./example_tls_advanced www.google.com 443 ./example_tls_advanced github.com 443
Note: Requires OpenSSL/LibreSSL support compiled in.
Definition at line 44 of file tls_advanced.c.
Data Fields
int lookup_count
const char * source_name
Function Documentation
example_cert_lookup()
static X509 * example_cert_lookup (X509_STORE_CTX * store_ctx, const X509_NAME * name, void * user_data) static
Definition at line 51 of file tls_advanced.c.
References CertLookupContext::lookup_count, and CertLookupContext::source_name.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 94 of file tls_advanced.c.
References ELSE, END_TRY, example_cert_lookup(), EXCEPT, SocketTLS_CertInfo::fingerprint, SocketTLS_CertInfo::issuer, CertLookupContext::lookup_count, SocketTLS_CertInfo::not_after, SocketTLS_CertInfo::not_before, SocketTLS_CertInfo::serial, Socket_connect(), Socket_Failed, Socket_free(), Socket_GetLastError(), Socket_new(), SocketTLS_enable(), SocketTLS_Failed, SocketTLS_get_cipher(), SocketTLS_get_ocsp_next_update(), SocketTLS_get_ocsp_response_status(), SocketTLS_get_peer_cert_info(), SocketTLS_get_verify_result(), SocketTLS_get_version(), SocketTLS_handshake_auto(), SocketTLS_HandshakeFailed, SocketTLS_recv(), SocketTLS_send(), SocketTLS_set_hostname(), SocketTLS_shutdown(), SocketTLS_VerifyFailed, SocketTLSContext_enable_ocsp_stapling(), SocketTLSContext_free(), SocketTLSContext_new_client(), SocketTLSContext_ocsp_stapling_enabled(), SocketTLSContext_set_cert_lookup_callback(), SocketTLS_CertInfo::subject, TLS_HANDSHAKE_COMPLETE, TRY, and SocketTLS_CertInfo::version.