Tetsuo Pulse: udp_echo_client.c File Reference
udp_echo_client.c File Reference
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "core/Except.h"
#include "socket/SocketDgram.h"
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
udp_echo_client.c - Basic UDP Echo Client Example
Demonstrates a simple UDP echo client using the SocketDgram API. Shows UDP socket operations: connect, send, recv.
Build: cmake -DBUILD_EXAMPLES=ON .. make example_udp_echo_client
Usage: ./example_udp_echo_client [host] [port] [message] ./example_udp_echo_client localhost 8080 "Hello, World!"
Definition at line 25 of file udp_echo_client.c.
References END_TRY, EXCEPT, SocketDgram_connect(), SocketDgram_Failed, SocketDgram_free(), SocketDgram_new(), SocketDgram_recv(), SocketDgram_send(), and TRY.