Tetsuo Pulse: udp_echo_server.c File Reference
udp_echo_server.c File Reference
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "core/Except.h"
#include "socket/SocketDgram.h"
Functions
static void signal_handler (int signo)
int main (int argc, char **argv)
Variables
static volatile int running = 1
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 39 of file udp_echo_server.c.
References END_TRY, EXCEPT, running, signal_handler(), SocketDgram_bind(), SocketDgram_Failed, SocketDgram_free(), SocketDgram_new(), SocketDgram_recvfrom(), SocketDgram_sendto(), and TRY.
signal_handler()
static void signal_handler (int signo) static
Definition at line 32 of file udp_echo_server.c.
References running.
Referenced by main().
Variable Documentation
running
volatile int running = 1 static
udp_echo_server.c - Basic UDP Echo Server Example
Demonstrates a simple UDP echo server using the SocketDgram API. Shows UDP socket operations: bind, recvfrom, sendto.
Build: cmake -DBUILD_EXAMPLES=ON .. make example_udp_echo_server
Usage: ./example_udp_echo_server [port] ./example_udp_echo_server 8080
Test with: echo "Hello, World!" | nc -u localhost 8080 python3 -c "import socket; s=socket.socket(socket.AF_INET,socket.SOCK_DGRAM); s.sendto(b'Hello',('localhost',8080)); print(s.recv(1024))"
Definition at line 29 of file udp_echo_server.c.
Referenced by main(), and signal_handler().