websocket_server.c File Reference
websocket_server.c File Reference
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "core/Except.h"
#include "http/SocketHTTP.h"
#include "http/SocketHTTPServer.h"
#include "poll/SocketPoll.h"
#include "socket/Socket.h"
#include "socket/SocketWS.h"
Macros
#define MAX_CLIENTS 100
Functions
static void signal_handler (int signo)
static int add_ws_client (SocketWS_T ws)
static void remove_ws_client (SocketWS_T ws)
static void request_handler (SocketHTTPServer_Request_T req, void *userdata)
static void process_websocket_clients (void)
int main (int argc, char **argv)
Variables
static volatile int running = 1
static SocketWS_T ws_clients [100]
static int ws_count = 0
Macro Definition Documentation
MAX_CLIENTS
#define MAX_CLIENTS 100
websocket_server.c - WebSocket Echo Server Example
Demonstrates a WebSocket server that echoes messages back to clients. Integrates with HTTP server for WebSocket upgrade handling.
Build: cmake -DBUILD_EXAMPLES=ON .. make example_websocket_server
Usage: ./example_websocket_server [port] ./example_websocket_server 8080
Test with browser console: ws = new WebSocket('ws://localhost:8080/ws'); ws.onmessage = (e) => console.log('Received:', e.data); ws.send('Hello, Server!');
Or with the websocket_client example: ./example_websocket_client localhost 8080 /ws
Definition at line 37 of file websocket_server.c.
Function Documentation
add_ws_client()
static int add_ws_client (SocketWS_T ws) static
Add a WebSocket client to the list
Definition at line 55 of file websocket_server.c.
References MAX_CLIENTS, ws_clients, and ws_count.
Referenced by request_handler().
main()
int main (int argc, char ** argv)
Definition at line 287 of file websocket_server.c.
References SocketHTTPServer_Config::backlog, SocketHTTPServer_Config::bind_address, END_TRY, EXCEPT, FINALLY, SocketHTTPServer_Config::keepalive_timeout_ms, SocketHTTPServer_Config::max_connections, SocketHTTPServer_Config::port, process_websocket_clients(), request_handler(), running, signal_handler(), SocketHTTPServer_BindFailed, SocketHTTPServer_config_defaults(), SocketHTTPServer_Failed, SocketHTTPServer_free(), SocketHTTPServer_new(), SocketHTTPServer_process(), SocketHTTPServer_set_handler(), SocketHTTPServer_start(), SocketHTTPServer_stop(), SocketWS_close(), SocketWS_free(), TRY, ws_clients, WS_CLOSE_GOING_AWAY, and ws_count.
process_websocket_clients()
static void process_websocket_clients (void) static
Process WebSocket clients
Definition at line 233 of file websocket_server.c.
References SocketWS_Message::data, SocketWS_Message::len, remove_ws_client(), SocketWS_close_code(), SocketWS_free(), SocketWS_recv_available(), SocketWS_recv_message(), SocketWS_send_binary(), SocketWS_send_text(), SocketWS_state(), SocketWS_Message::type, ws_clients, ws_count, WS_OPCODE_TEXT, and WS_STATE_CLOSED.
Referenced by main().
remove_ws_client()
static void remove_ws_client (SocketWS_T ws) static
Remove a WebSocket client from the list
Definition at line 69 of file websocket_server.c.
References ws_clients, and ws_count.
Referenced by process_websocket_clients().
request_handler()
static void request_handler (SocketHTTPServer_Request_T req, void * userdata) static
HTTP request handler
Handles WebSocket upgrades and regular HTTP requests.
Definition at line 92 of file websocket_server.c.
References add_ws_client(), SocketHTTPServer_Request_body_string(), SocketHTTPServer_Request_client_addr(), SocketHTTPServer_Request_finish(), SocketHTTPServer_Request_header(), SocketHTTPServer_Request_is_websocket(), SocketHTTPServer_Request_path(), SocketHTTPServer_Request_status(), SocketHTTPServer_Request_upgrade_websocket(), SocketWS_close(), SocketWS_free(), SocketWS_handshake(), SocketWS_state(), WS_CLOSE_TRY_AGAIN_LATER, ws_count, and WS_STATE_OPEN.
Referenced by main().
signal_handler()
static void signal_handler (int signo) static
Definition at line 45 of file websocket_server.c.
References running.
Referenced by main().
Variable Documentation
running
volatile int running = 1 static
Definition at line 40 of file websocket_server.c.
Referenced by main(), and signal_handler().
ws_clients
SocketWS_T ws_clients[100] static
Definition at line 41 of file websocket_server.c.
Referenced by add_ws_client(), main(), process_websocket_clients(), and remove_ws_client().
ws_count
int ws_count = 0 static
Definition at line 42 of file websocket_server.c.
Referenced by add_ws_client(), main(), process_websocket_clients(), remove_ws_client(), and request_handler().