Tetsuo Pulse: websocket_client.c File Reference
websocket_client.c File Reference
#include <poll.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "core/Except.h"
#include "socket/Socket.h"
#include "socket/SocketWS.h"
Functions
static void signal_handler (int signo)
int main (int argc, char **argv)
Variables
static volatile int running = 1
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 41 of file websocket_client.c.
References SocketWS_Message::data, END_TRY, EXCEPT, FINALLY, SocketWS_Message::len, SocketWS_Config::ping_interval_ms, SocketWS_Config::role, running, signal_handler(), Socket_connect(), Socket_Failed, Socket_fd(), Socket_free(), Socket_new(), SocketWS_client_new(), SocketWS_close(), SocketWS_close_code(), SocketWS_close_reason(), SocketWS_Closed, SocketWS_compression_enabled(), SocketWS_config_defaults(), SocketWS_error_string(), SocketWS_Failed, SocketWS_free(), SocketWS_handshake(), SocketWS_last_error(), SocketWS_ping(), SocketWS_process(), SocketWS_ProtocolError, SocketWS_recv_available(), SocketWS_recv_message(), SocketWS_selected_subprotocol(), SocketWS_send_binary(), SocketWS_send_text(), SocketWS_socket(), SocketWS_state(), TRY, SocketWS_Message::type, SocketWS_Config::validate_utf8, WS_CLOSE_NORMAL, WS_OPCODE_TEXT, WS_ROLE_CLIENT, WS_STATE_CLOSED, and WS_STATE_OPEN.
signal_handler()
static void signal_handler (int signo) static
Definition at line 34 of file websocket_client.c.
References running.
Referenced by main().
Variable Documentation
running
volatile int running = 1 static
websocket_client.c - WebSocket Client Example
Demonstrates connecting to a WebSocket server, sending and receiving messages.
Build: cmake -DBUILD_EXAMPLES=ON .. make example_websocket_client
Usage: ./example_websocket_client [host] [port] [path] ./example_websocket_client echo.websocket.org 80 / ./example_websocket_client localhost 8080 /ws
Note: For wss:// (TLS), you would use SocketTLS to wrap the socket before creating the WebSocket.
Definition at line 31 of file websocket_client.c.
Referenced by main(), and signal_handler().