/* Auto-generated by tools/protoc-gen-socketgrpc. DO NOT EDIT. */
#ifndef COMPLEX_SOCKETGRPC_GENERATED_H
#define COMPLEX_SOCKETGRPC_GENERATED_H

#include <stddef.h>
#include <stdint.h>

#include "core/Arena.h"
#include "grpc/SocketGRPC.h"

typedef struct test_complex_Envelope_Meta test_complex_Envelope_Meta;
typedef struct test_complex_Envelope test_complex_Envelope;
typedef struct test_complex_ComplexRequest test_complex_ComplexRequest;
typedef struct test_complex_ComplexResponse test_complex_ComplexResponse;

struct test_complex_Envelope_Meta
{
  uint64_t timestamp;
  char *source;
};

extern void test_complex_Envelope_Meta_init (test_complex_Envelope_Meta *message);
extern void test_complex_Envelope_Meta_free (test_complex_Envelope_Meta *message);
extern int test_complex_Envelope_Meta_encode (const test_complex_Envelope_Meta *message, uint8_t *out, size_t out_len, size_t *written);
extern int test_complex_Envelope_Meta_decode (test_complex_Envelope_Meta *message, const uint8_t *data, size_t len, Arena_T arena);

typedef enum test_complex_Envelope_payloadCase
{
  TEST_COMPLEX_ENVELOPE_PAYLOADCASE_NOT_SET = 0,
  TEST_COMPLEX_ENVELOPE_PAYLOADCASE_TEXT = 5,
  TEST_COMPLEX_ENVELOPE_PAYLOADCASE_BLOB = 6,
  TEST_COMPLEX_ENVELOPE_PAYLOADCASE_REF_ID = 7,
} test_complex_Envelope_payloadCase;

struct test_complex_Envelope
{
  test_complex_Envelope_Meta meta;
  int has_meta;
  char **tags;
  size_t tags_count;
  uint32_t *scores;
  size_t scores_count;
  uint8_t **attachments;
  size_t *attachments_len;
  size_t attachments_count;
  test_complex_Envelope_payloadCase payload_case;
  union
  {
    char *text;
    struct { uint8_t *data; size_t len; } blob;
    uint64_t ref_id;
  } payload;
};

extern void test_complex_Envelope_init (test_complex_Envelope *message);
extern void test_complex_Envelope_free (test_complex_Envelope *message);
extern int test_complex_Envelope_encode (const test_complex_Envelope *message, uint8_t *out, size_t out_len, size_t *written);
extern int test_complex_Envelope_decode (test_complex_Envelope *message, const uint8_t *data, size_t len, Arena_T arena);

struct test_complex_ComplexRequest
{
  test_complex_Envelope envelope;
  int has_envelope;
  char **notes;
  size_t notes_count;
  uint32_t *codes;
  size_t codes_count;
};

extern void test_complex_ComplexRequest_init (test_complex_ComplexRequest *message);
extern void test_complex_ComplexRequest_free (test_complex_ComplexRequest *message);
extern int test_complex_ComplexRequest_encode (const test_complex_ComplexRequest *message, uint8_t *out, size_t out_len, size_t *written);
extern int test_complex_ComplexRequest_decode (test_complex_ComplexRequest *message, const uint8_t *data, size_t len, Arena_T arena);

struct test_complex_ComplexResponse
{
  int accepted;
  char *reason;
};

extern void test_complex_ComplexResponse_init (test_complex_ComplexResponse *message);
extern void test_complex_ComplexResponse_free (test_complex_ComplexResponse *message);
extern int test_complex_ComplexResponse_encode (const test_complex_ComplexResponse *message, uint8_t *out, size_t out_len, size_t *written);
extern int test_complex_ComplexResponse_decode (test_complex_ComplexResponse *message, const uint8_t *data, size_t len, Arena_T arena);

typedef struct test_complex_ComplexService_ServerHandlers
{
  int (*Process) (const test_complex_ComplexRequest *request, test_complex_ComplexResponse *response, void *userdata, Arena_T arena);
  void *userdata;
} test_complex_ComplexService_ServerHandlers;

typedef struct test_complex_ComplexService_Client
{
  SocketGRPC_Channel_T channel;
  const test_complex_ComplexService_ServerHandlers *local_handlers;
} test_complex_ComplexService_Client;

extern void test_complex_ComplexService_Client_init (test_complex_ComplexService_Client *client, SocketGRPC_Channel_T channel);
extern void test_complex_ComplexService_Client_bind_local (test_complex_ComplexService_Client *client, const test_complex_ComplexService_ServerHandlers *handlers);
extern int test_complex_ComplexService_Client_Process (test_complex_ComplexService_Client *client, const test_complex_ComplexRequest *request, test_complex_ComplexResponse *response, Arena_T arena);

#endif /* COMPLEX_SOCKETGRPC_GENERATED_H */
