/* Auto-generated by tools/protoc-gen-socketgrpc. DO NOT EDIT. */
#ifndef STREAMING_SOCKETGRPC_GENERATED_H
#define STREAMING_SOCKETGRPC_GENERATED_H

#include <stddef.h>
#include <stdint.h>

#include "core/Arena.h"
#include "grpc/SocketGRPC.h"

typedef struct test_streaming_Chunk test_streaming_Chunk;
typedef struct test_streaming_Ack test_streaming_Ack;

struct test_streaming_Chunk
{
  uint8_t *data;
  size_t data_len;
  uint32_t sequence;
};

extern void test_streaming_Chunk_init (test_streaming_Chunk *message);
extern void test_streaming_Chunk_free (test_streaming_Chunk *message);
extern int test_streaming_Chunk_encode (const test_streaming_Chunk *message, uint8_t *out, size_t out_len, size_t *written);
extern int test_streaming_Chunk_decode (test_streaming_Chunk *message, const uint8_t *data, size_t len, Arena_T arena);

struct test_streaming_Ack
{
  uint32_t received;
};

extern void test_streaming_Ack_init (test_streaming_Ack *message);
extern void test_streaming_Ack_free (test_streaming_Ack *message);
extern int test_streaming_Ack_encode (const test_streaming_Ack *message, uint8_t *out, size_t out_len, size_t *written);
extern int test_streaming_Ack_decode (test_streaming_Ack *message, const uint8_t *data, size_t len, Arena_T arena);

typedef struct test_streaming_Streamer_ServerHandlers
{
  int (*Upload_stream) (void *stream_ctx, void *userdata, Arena_T arena);
  int (*Subscribe_stream) (void *stream_ctx, void *userdata, Arena_T arena);
  int (*Chat_stream) (void *stream_ctx, void *userdata, Arena_T arena);
  void *userdata;
} test_streaming_Streamer_ServerHandlers;

typedef struct test_streaming_Streamer_Client
{
  SocketGRPC_Channel_T channel;
  const test_streaming_Streamer_ServerHandlers *local_handlers;
} test_streaming_Streamer_Client;

extern void test_streaming_Streamer_Client_init (test_streaming_Streamer_Client *client, SocketGRPC_Channel_T channel);
extern void test_streaming_Streamer_Client_bind_local (test_streaming_Streamer_Client *client, const test_streaming_Streamer_ServerHandlers *handlers);
extern int test_streaming_Streamer_Client_Upload_stream (test_streaming_Streamer_Client *client, void *stream_ctx, Arena_T arena);
extern int test_streaming_Streamer_Client_Subscribe_stream (test_streaming_Streamer_Client *client, void *stream_ctx, Arena_T arena);
extern int test_streaming_Streamer_Client_Chat_stream (test_streaming_Streamer_Client *client, void *stream_ctx, Arena_T arena);

#endif /* STREAMING_SOCKETGRPC_GENERATED_H */
