/* Auto-generated by tools/protoc-gen-socketgrpc. DO NOT EDIT. */

#include "unary.socketgrpc.h"

#include "grpc/SocketProto.h"

#include <stdlib.h>
#include <string.h>

#define SOCKETGRPC_GEN_EMBEDDED_LIMIT 65536U

#define SOCKETGRPC_GEN_ALLOC(arena, nbytes) ((arena) ? ALLOC ((arena), (nbytes)) : malloc ((nbytes)))
#define SOCKETGRPC_GEN_CALLOC(arena, count, nbytes) ((arena) ? CALLOC ((arena), (count), (nbytes)) : calloc ((count), (nbytes)))

void test_unary_HelloRequest_init (test_unary_HelloRequest *message)
{
  if (message == NULL)
    return;
  memset (message, 0, sizeof (*message));
}

void test_unary_HelloRequest_free (test_unary_HelloRequest *message)
{
  if (message == NULL)
    return;
  /* Arena-backed decoded pointers are not individually freed. */
  memset (message, 0, sizeof (*message));
}

int test_unary_HelloRequest_encode (const test_unary_HelloRequest *message, uint8_t *out, size_t out_len, size_t *written)
{
  SocketProto_Message_T wire;
  SocketProto_Result rc;
  if (message == NULL || out == NULL || written == NULL)
    return -1;
  wire = SocketProto_Message_new (NULL, NULL, NULL);
  if (wire == NULL)
    return -1;
  if (message->name != NULL)
    {
      rc = SocketProto_Message_append_bytes (wire, 1, (const uint8_t *)message->name, strlen (message->name));
      if (rc != SOCKET_PROTO_OK)
        { SocketProto_Message_free (&wire); return -1; }
    }
  if (message->id != (uint32_t)0)
    {
      rc = SocketProto_Message_append_varint (wire, 2, (uint64_t)message->id);
      if (rc != SOCKET_PROTO_OK)
        { SocketProto_Message_free (&wire); return -1; }
    }
  rc = SocketProto_Message_encode (wire, out, out_len, written);
  SocketProto_Message_free (&wire);
  return (rc == SOCKET_PROTO_OK) ? 0 : -1;
}

int test_unary_HelloRequest_decode (test_unary_HelloRequest *message, const uint8_t *data, size_t len, Arena_T arena)
{
  SocketProto_Message_T parsed;
  if (message == NULL || (data == NULL && len != 0) || arena == NULL)
    return -1;
  test_unary_HelloRequest_init (message);
  parsed = SocketProto_Message_new (arena, NULL, NULL);
  if (parsed == NULL)
    return -1;
  if (SocketProto_Message_parse (parsed, data, len) != SOCKET_PROTO_OK)
    {
      SocketProto_Message_free (&parsed);
      return -1;
    }
  for (size_t i = 0; i < SocketProto_Message_field_count (parsed); i++)
    {
      const SocketProto_Field *field = SocketProto_Message_field_at (parsed, i);
      if (field == NULL)
        continue;
      switch (field->field_number)
        {
        case 1:
          {
            char *copy = (char *)SOCKETGRPC_GEN_ALLOC (arena, field->value_len + 1U);
            if (copy != NULL)
              {
                memcpy (copy, field->value, field->value_len);
                copy[field->value_len] = '\0';
                message->name = copy;
              }
          }
          break;
        case 2:
          {
            uint64_t value = 0;
            if (SocketProto_Field_decode_u64 (field, &value) == SOCKET_PROTO_OK)
              message->id = (uint32_t)value;
          }
          break;
        default:
          break;
        }
    }
  SocketProto_Message_free (&parsed);
  return 0;
}

void test_unary_HelloResponse_init (test_unary_HelloResponse *message)
{
  if (message == NULL)
    return;
  memset (message, 0, sizeof (*message));
}

void test_unary_HelloResponse_free (test_unary_HelloResponse *message)
{
  if (message == NULL)
    return;
  /* Arena-backed decoded pointers are not individually freed. */
  memset (message, 0, sizeof (*message));
}

int test_unary_HelloResponse_encode (const test_unary_HelloResponse *message, uint8_t *out, size_t out_len, size_t *written)
{
  SocketProto_Message_T wire;
  SocketProto_Result rc;
  if (message == NULL || out == NULL || written == NULL)
    return -1;
  wire = SocketProto_Message_new (NULL, NULL, NULL);
  if (wire == NULL)
    return -1;
  if (message->greeting != NULL)
    {
      rc = SocketProto_Message_append_bytes (wire, 1, (const uint8_t *)message->greeting, strlen (message->greeting));
      if (rc != SOCKET_PROTO_OK)
        { SocketProto_Message_free (&wire); return -1; }
    }
  if (message->code != (uint32_t)0)
    {
      rc = SocketProto_Message_append_varint (wire, 2, (uint64_t)message->code);
      if (rc != SOCKET_PROTO_OK)
        { SocketProto_Message_free (&wire); return -1; }
    }
  rc = SocketProto_Message_encode (wire, out, out_len, written);
  SocketProto_Message_free (&wire);
  return (rc == SOCKET_PROTO_OK) ? 0 : -1;
}

int test_unary_HelloResponse_decode (test_unary_HelloResponse *message, const uint8_t *data, size_t len, Arena_T arena)
{
  SocketProto_Message_T parsed;
  if (message == NULL || (data == NULL && len != 0) || arena == NULL)
    return -1;
  test_unary_HelloResponse_init (message);
  parsed = SocketProto_Message_new (arena, NULL, NULL);
  if (parsed == NULL)
    return -1;
  if (SocketProto_Message_parse (parsed, data, len) != SOCKET_PROTO_OK)
    {
      SocketProto_Message_free (&parsed);
      return -1;
    }
  for (size_t i = 0; i < SocketProto_Message_field_count (parsed); i++)
    {
      const SocketProto_Field *field = SocketProto_Message_field_at (parsed, i);
      if (field == NULL)
        continue;
      switch (field->field_number)
        {
        case 1:
          {
            char *copy = (char *)SOCKETGRPC_GEN_ALLOC (arena, field->value_len + 1U);
            if (copy != NULL)
              {
                memcpy (copy, field->value, field->value_len);
                copy[field->value_len] = '\0';
                message->greeting = copy;
              }
          }
          break;
        case 2:
          {
            uint64_t value = 0;
            if (SocketProto_Field_decode_u64 (field, &value) == SOCKET_PROTO_OK)
              message->code = (uint32_t)value;
          }
          break;
        default:
          break;
        }
    }
  SocketProto_Message_free (&parsed);
  return 0;
}

void test_unary_Greeter_Client_init (test_unary_Greeter_Client *client, SocketGRPC_Channel_T channel)
{
  if (client == NULL)
    return;
  client->channel = channel;
  client->local_handlers = NULL;
}

void test_unary_Greeter_Client_bind_local (test_unary_Greeter_Client *client, const test_unary_Greeter_ServerHandlers *handlers)
{
  if (client == NULL)
    return;
  client->local_handlers = handlers;
}

int test_unary_Greeter_Client_SayHello (test_unary_Greeter_Client *client, const test_unary_HelloRequest *request, test_unary_HelloResponse *response, Arena_T arena)
{
  if (client == NULL || request == NULL || response == NULL || arena == NULL)
    return -1;
  if (client->local_handlers == NULL || client->local_handlers->SayHello == NULL)
    return SOCKET_GRPC_STATUS_UNIMPLEMENTED;
  return client->local_handlers->SayHello (request, response, client->local_handlers->userdata, arena);
}
