# CMake generated Testfile for 
# Source directory: /home/tetsuo/git/tetsuo-socket
# Build directory: /home/tetsuo/git/tetsuo-socket/build_test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_new_features "/home/tetsuo/git/tetsuo-socket/build_test/test_new_features")
set_tests_properties(test_new_features PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_arena "/home/tetsuo/git/tetsuo-socket/build_test/test_arena")
set_tests_properties(test_arena PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_except "/home/tetsuo/git/tetsuo-socket/build_test/test_except")
set_tests_properties(test_except PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_hashtable "/home/tetsuo/git/tetsuo-socket/build_test/test_hashtable")
set_tests_properties(test_hashtable PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_timewindow "/home/tetsuo/git/tetsuo-socket/build_test/test_timewindow")
set_tests_properties(test_timewindow PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_socketerror "/home/tetsuo/git/tetsuo-socket/build_test/test_socketerror")
set_tests_properties(test_socketerror PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_socketevent "/home/tetsuo/git/tetsuo-socket/build_test/test_socketevent")
set_tests_properties(test_socketevent PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_safe_arithmetic "/home/tetsuo/git/tetsuo-socket/build_test/test_safe_arithmetic")
set_tests_properties(test_safe_arithmetic PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_url_utils "/home/tetsuo/git/tetsuo-socket/build_test/test_url_utils")
set_tests_properties(test_url_utils PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_socket "/home/tetsuo/git/tetsuo-socket/build_test/test_socket")
set_tests_properties(test_socket PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_simple_recv_line "/home/tetsuo/git/tetsuo-socket/build_test/test_simple_recv_line")
set_tests_properties(test_simple_recv_line PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_simple_dns_overflow "/home/tetsuo/git/tetsuo-socket/build_test/test_simple_dns_overflow")
set_tests_properties(test_simple_dns_overflow PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_simple_poll_udp "/home/tetsuo/git/tetsuo-socket/build_test/test_simple_poll_udp")
set_tests_properties(test_simple_poll_udp PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_socketbuf "/home/tetsuo/git/tetsuo-socket/build_test/test_socketbuf")
set_tests_properties(test_socketbuf PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_socketdgram "/home/tetsuo/git/tetsuo-socket/build_test/test_socketdgram")
set_tests_properties(test_socketdgram PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_socketpoll "/home/tetsuo/git/tetsuo-socket/build_test/test_socketpoll")
set_tests_properties(test_socketpoll PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_socketpool "/home/tetsuo/git/tetsuo-socket/build_test/test_socketpool")
set_tests_properties(test_socketpool PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_pool_health "/home/tetsuo/git/tetsuo-socket/build_test/test_pool_health")
set_tests_properties(test_pool_health PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_iptracker "/home/tetsuo/git/tetsuo-socket/build_test/test_iptracker")
set_tests_properties(test_iptracker PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_socketdns "/home/tetsuo/git/tetsuo-socket/build_test/test_socketdns")
set_tests_properties(test_socketdns PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_dns_wire "/home/tetsuo/git/tetsuo-socket/build_test/test_dns_wire")
set_tests_properties(test_dns_wire PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_dns_transport "/home/tetsuo/git/tetsuo-socket/build_test/test_dns_transport")
set_tests_properties(test_dns_transport PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_dns_config "/home/tetsuo/git/tetsuo-socket/build_test/test_dns_config")
set_tests_properties(test_dns_config PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_dns_cache "/home/tetsuo/git/tetsuo-socket/build_test/test_dns_cache")
set_tests_properties(test_dns_cache PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_dns_resolver "/home/tetsuo/git/tetsuo-socket/build_test/test_dns_resolver")
set_tests_properties(test_dns_resolver PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_dns_queue_limit "/home/tetsuo/git/tetsuo-socket/build_test/test_dns_queue_limit")
set_tests_properties(test_dns_queue_limit PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_dnssec "/home/tetsuo/git/tetsuo-socket/build_test/test_dnssec")
set_tests_properties(test_dnssec PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_dnscookie "/home/tetsuo/git/tetsuo-socket/build_test/test_dnscookie")
set_tests_properties(test_dnscookie PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_dnserror "/home/tetsuo/git/tetsuo-socket/build_test/test_dnserror")
set_tests_properties(test_dnserror PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_dns_negcache "/home/tetsuo/git/tetsuo-socket/build_test/test_dns_negcache")
set_tests_properties(test_dns_negcache PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_dns_servfailcache "/home/tetsuo/git/tetsuo-socket/build_test/test_dns_servfailcache")
set_tests_properties(test_dns_servfailcache PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_dns_deadserver "/home/tetsuo/git/tetsuo-socket/build_test/test_dns_deadserver")
set_tests_properties(test_dns_deadserver PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_integration "/home/tetsuo/git/tetsuo-socket/build_test/test_integration")
set_tests_properties(test_integration PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_threadsafety "/home/tetsuo/git/tetsuo-socket/build_test/test_threadsafety")
set_tests_properties(test_threadsafety PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_happy_eyeballs "/home/tetsuo/git/tetsuo-socket/build_test/test_happy_eyeballs")
set_tests_properties(test_happy_eyeballs PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_reconnect "/home/tetsuo/git/tetsuo-socket/build_test/test_reconnect")
set_tests_properties(test_reconnect PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_ratelimit "/home/tetsuo/git/tetsuo-socket/build_test/test_ratelimit")
set_tests_properties(test_ratelimit PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_simple_ratelimit "/home/tetsuo/git/tetsuo-socket/build_test/test_simple_ratelimit")
set_tests_properties(test_simple_ratelimit PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_async "/home/tetsuo/git/tetsuo-socket/build_test/test_async")
set_tests_properties(test_async PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_coverage "/home/tetsuo/git/tetsuo-socket/build_test/test_coverage")
set_tests_properties(test_coverage PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_synprotect "/home/tetsuo/git/tetsuo-socket/build_test/test_synprotect")
set_tests_properties(test_synprotect PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_crypto "/home/tetsuo/git/tetsuo-socket/build_test/test_crypto")
set_tests_properties(test_crypto PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_utf8 "/home/tetsuo/git/tetsuo-socket/build_test/test_utf8")
set_tests_properties(test_utf8 PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_http_core "/home/tetsuo/git/tetsuo-socket/build_test/test_http_core")
set_tests_properties(test_http_core PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_http1_parser "/home/tetsuo/git/tetsuo-socket/build_test/test_http1_parser")
set_tests_properties(test_http1_parser PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_hpack "/home/tetsuo/git/tetsuo-socket/build_test/test_hpack")
set_tests_properties(test_hpack PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_http2 "/home/tetsuo/git/tetsuo-socket/build_test/test_http2")
set_tests_properties(test_http2 PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_http2_priority "/home/tetsuo/git/tetsuo-socket/build_test/test_http2_priority")
set_tests_properties(test_http2_priority PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_http2_rate_limit "/home/tetsuo/git/tetsuo-socket/build_test/test_http2_rate_limit")
set_tests_properties(test_http2_rate_limit PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_http_client "/home/tetsuo/git/tetsuo-socket/build_test/test_http_client")
set_tests_properties(test_http_client PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_proxy "/home/tetsuo/git/tetsuo-socket/build_test/test_proxy")
set_tests_properties(test_proxy PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_simple_proxy_url "/home/tetsuo/git/tetsuo-socket/build_test/test_simple_proxy_url")
set_tests_properties(test_simple_proxy_url PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_websocket "/home/tetsuo/git/tetsuo-socket/build_test/test_websocket")
set_tests_properties(test_websocket PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_security "/home/tetsuo/git/tetsuo-socket/build_test/test_security")
set_tests_properties(test_security PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_json_injection "/home/tetsuo/git/tetsuo-socket/build_test/test_json_injection")
set_tests_properties(test_json_injection PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_http_integration "/home/tetsuo/git/tetsuo-socket/build_test/test_http_integration")
set_tests_properties(test_http_integration PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_ws_integration "/home/tetsuo/git/tetsuo-socket/build_test/test_ws_integration")
set_tests_properties(test_ws_integration PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_http2_integration "/home/tetsuo/git/tetsuo-socket/build_test/test_http2_integration")
set_tests_properties(test_http2_integration PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_proxy_integration "/home/tetsuo/git/tetsuo-socket/build_test/test_proxy_integration")
set_tests_properties(test_proxy_integration PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_httpserver_load "/home/tetsuo/git/tetsuo-socket/build_test/test_httpserver_load")
set_tests_properties(test_httpserver_load PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_signals "/home/tetsuo/git/tetsuo-socket/build_test/test_signals")
set_tests_properties(test_signals PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_cross_module_integration "/home/tetsuo/git/tetsuo-socket/build_test/test_cross_module_integration")
set_tests_properties(test_cross_module_integration PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_load_integration "/home/tetsuo/git/tetsuo-socket/build_test/test_load_integration")
set_tests_properties(test_load_integration PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_connection_resilience "/home/tetsuo/git/tetsuo-socket/build_test/test_connection_resilience")
set_tests_properties(test_connection_resilience PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_platform_integration "/home/tetsuo/git/tetsuo-socket/build_test/test_platform_integration")
set_tests_properties(test_platform_integration PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_multi_protocol_integration "/home/tetsuo/git/tetsuo-socket/build_test/test_multi_protocol_integration")
set_tests_properties(test_multi_protocol_integration PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_socketretry "/home/tetsuo/git/tetsuo-socket/build_test/test_socketretry")
set_tests_properties(test_socketretry PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_socketio "/home/tetsuo/git/tetsuo-socket/build_test/test_socketio")
set_tests_properties(test_socketio PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_timer "/home/tetsuo/git/tetsuo-socket/build_test/test_timer")
set_tests_properties(test_timer PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_metrics "/home/tetsuo/git/tetsuo-socket/build_test/test_metrics")
set_tests_properties(test_metrics PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_httpserver "/home/tetsuo/git/tetsuo-socket/build_test/test_httpserver")
set_tests_properties(test_httpserver PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_varint "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_varint")
set_tests_properties(test_quic_varint PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_error "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_error")
set_tests_properties(test_quic_error PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_version "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_version")
set_tests_properties(test_quic_version PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_connid "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_connid")
set_tests_properties(test_quic_connid PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_connid_pool "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_connid_pool")
set_tests_properties(test_quic_connid_pool PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_stream "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_stream")
set_tests_properties(test_quic_stream PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_stream_state "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_stream_state")
set_tests_properties(test_quic_stream_state PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_packet "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_packet")
set_tests_properties(test_quic_packet PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_wire "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_wire")
set_tests_properties(test_quic_wire PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_frame "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_frame")
set_tests_properties(test_quic_frame PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_stream_frame_encode "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_stream_frame_encode")
set_tests_properties(test_quic_stream_frame_encode PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_new_token_frame "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_new_token_frame")
set_tests_properties(test_quic_new_token_frame PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_path_frame "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_path_frame")
set_tests_properties(test_quic_path_frame PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_frame_close "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_frame_close")
set_tests_properties(test_quic_frame_close PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_connection "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_connection")
set_tests_properties(test_quic_connection PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_transport_params "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_transport_params")
set_tests_properties(test_quic_transport_params PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_pmtu "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_pmtu")
set_tests_properties(test_quic_pmtu PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_addr_validation "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_addr_validation")
set_tests_properties(test_quic_addr_validation PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_migration "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_migration")
set_tests_properties(test_quic_migration PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_handshake "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_handshake")
set_tests_properties(test_quic_handshake PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_termination "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_termination")
set_tests_properties(test_quic_termination PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_flow "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_flow")
set_tests_properties(test_quic_flow PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_crypto_frame_encode "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_crypto_frame_encode")
set_tests_properties(test_quic_crypto_frame_encode PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_ack "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_ack")
set_tests_properties(test_quic_ack PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_loss "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_loss")
set_tests_properties(test_quic_loss PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_quic_initial "/home/tetsuo/git/tetsuo-socket/build_test/test_quic_initial")
set_tests_properties(test_quic_initial PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_tls_ct "/home/tetsuo/git/tetsuo-socket/build_test/test_tls_ct")
set_tests_properties(test_tls_ct PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_tls_integration "/home/tetsuo/git/tetsuo-socket/build_test/test_tls_integration")
set_tests_properties(test_tls_integration PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_tls_ocsp "/home/tetsuo/git/tetsuo-socket/build_test/test_tls_ocsp")
set_tests_properties(test_tls_ocsp PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_tls_phase4 "/home/tetsuo/git/tetsuo-socket/build_test/test_tls_phase4")
set_tests_properties(test_tls_phase4 PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_tls_pinning "/home/tetsuo/git/tetsuo-socket/build_test/test_tls_pinning")
set_tests_properties(test_tls_pinning PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_tls_performance "/home/tetsuo/git/tetsuo-socket/build_test/test_tls_performance")
set_tests_properties(test_tls_performance PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_dtls_integration "/home/tetsuo/git/tetsuo-socket/build_test/test_dtls_integration")
set_tests_properties(test_dtls_integration PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_socketpool_tls "/home/tetsuo/git/tetsuo-socket/build_test/test_socketpool_tls")
set_tests_properties(test_socketpool_tls PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_dtls_basic "/home/tetsuo/git/tetsuo-socket/build_test/test_dtls_basic")
set_tests_properties(test_dtls_basic PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_dtls_cookie "/home/tetsuo/git/tetsuo-socket/build_test/test_dtls_cookie")
set_tests_properties(test_dtls_cookie PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_dtls_mtu "/home/tetsuo/git/tetsuo-socket/build_test/test_dtls_mtu")
set_tests_properties(test_dtls_mtu PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_mtls "/home/tetsuo/git/tetsuo-socket/build_test/test_mtls")
set_tests_properties(test_mtls PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_tls_context "/home/tetsuo/git/tetsuo-socket/build_test/test_tls_context")
set_tests_properties(test_tls_context PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_tls_enable_disable "/home/tetsuo/git/tetsuo-socket/build_test/test_tls_enable_disable")
set_tests_properties(test_tls_enable_disable PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_tls_handshake "/home/tetsuo/git/tetsuo-socket/build_test/test_tls_handshake")
set_tests_properties(test_tls_handshake PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_tls_http2 "/home/tetsuo/git/tetsuo-socket/build_test/test_tls_http2")
set_tests_properties(test_tls_http2 PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_tls_io "/home/tetsuo/git/tetsuo-socket/build_test/test_tls_io")
set_tests_properties(test_tls_io PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_tls_security "/home/tetsuo/git/tetsuo-socket/build_test/test_tls_security")
set_tests_properties(test_tls_security PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_tls_session "/home/tetsuo/git/tetsuo-socket/build_test/test_tls_session")
set_tests_properties(test_tls_session PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_tls_crl "/home/tetsuo/git/tetsuo-socket/build_test/test_tls_crl")
set_tests_properties(test_tls_crl PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_tls_crl_integration "/home/tetsuo/git/tetsuo-socket/build_test/test_tls_crl_integration")
set_tests_properties(test_tls_crl_integration PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_tls_ktls "/home/tetsuo/git/tetsuo-socket/build_test/test_tls_ktls")
set_tests_properties(test_tls_ktls PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_tls_reconnect "/home/tetsuo/git/tetsuo-socket/build_test/test_tls_reconnect")
set_tests_properties(test_tls_reconnect PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_http2_server_push "/home/tetsuo/git/tetsuo-socket/build_test/test_http2_server_push")
set_tests_properties(test_http2_server_push PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_websocket_h2 "/home/tetsuo/git/tetsuo-socket/build_test/test_websocket_h2")
set_tests_properties(test_websocket_h2 PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_dns_over_tls "/home/tetsuo/git/tetsuo-socket/build_test/test_dns_over_tls")
set_tests_properties(test_dns_over_tls PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_dns_over_https "/home/tetsuo/git/tetsuo-socket/build_test/test_dns_over_https")
set_tests_properties(test_dns_over_https PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;885;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
