# CMake generated Testfile for 
# Source directory: /home/tetsuo/git/tetsuo-socket
# Build directory: /home/tetsuo/git/tetsuo-socket/build-sanitizer
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_arena "/home/tetsuo/git/tetsuo-socket/build-sanitizer/test_arena")
set_tests_properties(test_arena PROPERTIES  _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;321;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_except "/home/tetsuo/git/tetsuo-socket/build-sanitizer/test_except")
set_tests_properties(test_except PROPERTIES  _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;321;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_socketerror "/home/tetsuo/git/tetsuo-socket/build-sanitizer/test_socketerror")
set_tests_properties(test_socketerror PROPERTIES  _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;321;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_socket "/home/tetsuo/git/tetsuo-socket/build-sanitizer/test_socket")
set_tests_properties(test_socket PROPERTIES  _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;321;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_socketbuf "/home/tetsuo/git/tetsuo-socket/build-sanitizer/test_socketbuf")
set_tests_properties(test_socketbuf PROPERTIES  _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;321;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_socketdgram "/home/tetsuo/git/tetsuo-socket/build-sanitizer/test_socketdgram")
set_tests_properties(test_socketdgram PROPERTIES  _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;321;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_socketpoll "/home/tetsuo/git/tetsuo-socket/build-sanitizer/test_socketpoll")
set_tests_properties(test_socketpoll PROPERTIES  _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;321;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_socketpool "/home/tetsuo/git/tetsuo-socket/build-sanitizer/test_socketpool")
set_tests_properties(test_socketpool PROPERTIES  _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;321;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_socketdns "/home/tetsuo/git/tetsuo-socket/build-sanitizer/test_socketdns")
set_tests_properties(test_socketdns PROPERTIES  _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;321;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_integration "/home/tetsuo/git/tetsuo-socket/build-sanitizer/test_integration")
set_tests_properties(test_integration PROPERTIES  _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;321;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_tls_integration "/home/tetsuo/git/tetsuo-socket/build-sanitizer/test_tls_integration")
set_tests_properties(test_tls_integration PROPERTIES  _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;321;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_tls_phase4 "/home/tetsuo/git/tetsuo-socket/build-sanitizer/test_tls_phase4")
set_tests_properties(test_tls_phase4 PROPERTIES  _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;321;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_threadsafety "/home/tetsuo/git/tetsuo-socket/build-sanitizer/test_threadsafety")
set_tests_properties(test_threadsafety PROPERTIES  _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;321;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_socketpool_tls "/home/tetsuo/git/tetsuo-socket/build-sanitizer/test_socketpool_tls")
set_tests_properties(test_socketpool_tls PROPERTIES  _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;321;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_happy_eyeballs "/home/tetsuo/git/tetsuo-socket/build-sanitizer/test_happy_eyeballs")
set_tests_properties(test_happy_eyeballs PROPERTIES  _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;321;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_reconnect "/home/tetsuo/git/tetsuo-socket/build-sanitizer/test_reconnect")
set_tests_properties(test_reconnect PROPERTIES  _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;321;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
add_test(test_ratelimit "/home/tetsuo/git/tetsuo-socket/build-sanitizer/test_ratelimit")
set_tests_properties(test_ratelimit PROPERTIES  _BACKTRACE_TRIPLES "/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;321;add_test;/home/tetsuo/git/tetsuo-socket/CMakeLists.txt;0;")
